### ISSUE TITLE
set_bucket_notification() in Python Minio SDK

### ISSUE THREAD

**Issue by 2020testuser** [minio/minio#10165]
This is related to the issue - Set notification namespace for NotificationConfiguration #6789 . The set_bucket_notification() is not working in Python as expected in s3 (not the sandbox). 
 I'm using docker minio client and server. Could anyone let me know whether this function works in Python?

## Expected Behavior
When I use set_bucket_notification() in Minio Python SDK, it should work. However, getting an error.
`from minio import Minio
from minio.error import (ResponseError, SignatureDoesNotMatch, BucketAlreadyOwnedByYou,
                         BucketAlreadyExists)

    # Initialize minioClient with an endpoint and access/secret keys.
minioClient = Minio('localhost:9000',
                    access_key='xxxx',
                    secret_key='xxx'              
                   )

print("Connection successful")
notification = {
    'CloudFunctionConfigurations': [
        {
            'Arn': 'arn1',
            'Events': ['s3:ObjectCreated:*'],
            'Filter': {
                'Key': {
                    'FilterRules': [
                        {
                            'Name': 'suffix',
                            'Value': '.xml'
                        }
                    ]
                }
            }
           # 'CloudFunction': 'http://localhost:8000/testapi'
        }
    ]
}
try:
    minioClient.set_bucket_notification('testbucket', notification)
except ResponseError as err:
    # handle error response from service.
    print(err)`

## Current Behavior
Currently, using set_bucket_notification() in Minio Python SDK, gives an error. Below is the error msg.
`Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 384, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "events-notify-s3.py", line 35, in <module>
    minioClient.set_bucket_notification('otdatahub', notification)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 524, in set_bucket_notification
    self._url_open(
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 1997, in _url_open
    response = self._http.urlopen(method, url,
  File "/usr/local/lib/python3.8/site-packages/urllib3/poolmanager.py", line 336, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 754, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /otdatahub/?notification= (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))`

## Steps to Reproduce (for bugs)

1. Run the below code which uses set_bucket_notification() in Minio Python SDK.

2. You will get an error.

## Your Environment

* Version used (`minio --version`): Using the latest docker minio client
* Server setup and configuration: Using the latest docker minio client
* Operating System : MAC OS

**Comment by harshavardhana** [comment]
> raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=9000): Max retries exceeded with url: /otdatahub/?notification= (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1123)')))`

You don't have SSL configured locally and MinioClient defaults to SSL 

> minioClient = Minio('localhost:9000',
> access_key='xxxx',
> secret_key='xxx'
> secure=False
> )

Set `secure=False`
