### ISSUE TITLE
[faq] How to upload image in Minio using python flask ?

### ISSUE THREAD

**Issue by Sangram9693** [minio/minio#10227]
I am trying to upload image into minio server using python flask api.

I am following min.io documentation. I followed below steps to active but i am getting error. 

can anyone tell where i am doing wrong?

**Code**

    def getMinioClient():
        minioClient = Minio(
            constants.LOCAL_MINIO,
            access_key='minioadmin',
            secret_key='minioadmin',
            secure=False,
        )
        return minioClient
    
    @app.route('upload/media/<product_id>/<media_id>', methods=['POST'])
    def uploadMediaByTenantIdMediaId(product_id, media_id):
        status = 500
        message = 'Internal Server Error'
        con = getConnection()
        try:
            minioClient = getMinioClient()
            bucketFound = minioClient.bucket_exists(product_id)
            if not bucketFound:
                minioClient.make_bucket(product_id)
            else:
                print('Exist')
    
            image_url = constants.BASE_SERVER + product_id + '/' + media_id + '.png'
            imgeData = request.files.getlist("img")[0]
            value_as_bytes = base64.b64encode(imgeData.read())
                    
            minioClient.put_object(product_id, media_id, value_as_bytes, 'image/png')
                
            return jsonify({'message': 'Upload Success', 'image_url': image_url}), 200
        except Exception as error:
            message = error
            con.rollback()
            print(error)
        finally:
            con.close()
    
        return jsonify({'message': message}), status

**Error**

    'bytes' object has no attribute 'read'
    127.0.0.1 - - [08/Aug/2020 18:15:53] "[35m[1mPOST /v1/api/upload/media/345tyu-18da-4d9c-9a08-df45678/4e53478e-2ae8-4994-9893-5de5ae7dda5b HTTP/1.1[0m" 500 -
    Traceback (most recent call last):
      File "C:\Python38\Lib\site-packages\flask\app.py", line 2463, in __call__
        return self.wsgi_app(environ, start_response)
      File "C:\Python38\Lib\site-packages\flask\app.py", line 2449, in wsgi_app
        response = self.handle_exception(e)
      File "C:\Python38\Lib\site-packages\flask\app.py", line 1866, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Python38\Lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "C:\Python38\Lib\site-packages\flask\app.py", line 2446, in wsgi_app
        response = self.full_dispatch_request()
      File "C:\Python38\Lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "C:\Python38\Lib\site-packages\flask\app.py", line 1820, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Python38\Lib\site-packages\flask\_compat.py", line 39, in reraise
        raise value
      File "C:\Python38\Lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
        rv = self.dispatch_request()
      File "C:\Python38\Lib\site-packages\flask\app.py", line 1935, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "D:\sangram\fiveer\bflitt\order 14\odn-media\api.py", line 98, in uploadMediaByTenantIdMediaId
        return jsonify({'message': message}), status
      File "C:\Python38\Lib\site-packages\flask\json\__init__.py", line 370, in jsonify
        dumps(data, indent=indent, separators=separators) + "\n",
      File "C:\Python38\Lib\site-packages\flask\json\__init__.py", line 211, in dumps
        rv = _json.dumps(obj, **kwargs)
      File "C:\Python38\Lib\site-packages\simplejson\__init__.py", line 398, in dumps
        return cls(
      File "C:\Python38\Lib\site-packages\simplejson\encoder.py", line 298, in encode
        chunks = list(chunks)
      File "C:\Python38\Lib\site-packages\simplejson\encoder.py", line 696, in _iterencode
        for chunk in _iterencode_dict(o, _current_indent_level):
      File "C:\Python38\Lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
        for chunk in chunks:
      File "C:\Python38\Lib\site-packages\simplejson\encoder.py", line 716, in _iterencode
        o = _default(o)
      File "C:\Python38\Lib\site-packages\flask\json\__init__.py", line 100, in default
        return _json.JSONEncoder.default(self, o)
      File "C:\Python38\Lib\site-packages\simplejson\encoder.py", line 272, in default
        raise TypeError('Object of type %s is not JSON serializable' %
    TypeError: Object of type AttributeError is not JSON serializable

**Comment by OrjwanZaafarani** [comment]
Hello, how did you manage to upload images?

**Comment by CheezusMaria** [comment]
any solution for this error ?
