### ISSUE TITLE
unexpected " aws  s3 mv " behavior

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#1027]
I am trying to do basic minio operations with aws CLI, I tried executing move(mv) operation. Please find detailed debug operation output.

```
$ aws --debug --endpoint-url http://localhost:9000 s3 mv hello.txt s3://mybucket/hello.txt 
2016-01-09 15:51:56,246 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.9.17 Python/2.7.6 Linux/3.13.0-38-generic botocore/1.3.17
2016-01-09 15:51:56,246 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', '--endpoint-url', 'http://localhost:9000', 's3', 'mv', 'hello.txt', 's3://mybucket/hello.txt']
2016-01-09 15:51:56,247 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7f5eb89c67d0>
2016-01-09 15:51:56,247 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7f5eb8a18f50>
2016-01-09 15:51:56,248 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-01-09 15:51:56,248 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7f5eb8a23668>
2016-01-09 15:51:56,252 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,253 - MainThread - botocore.hooks - DEBUG - Event building-command-table.mv: calling handler <function add_waiters at 0x7f5eb8a23668>
2016-01-09 15:51:56,259 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.sse-c-key: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,259 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.grants: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,260 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.content-language: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,260 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.page-size: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,260 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.anonymous: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,260 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.sse-c-copy-source-key: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,261 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.paths: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,261 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.anonymous: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,261 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.source-region: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,261 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.content-encoding: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,261 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.content-disposition: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,262 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.cache-control: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,262 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.metadata: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,262 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.dryrun: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,262 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.mv: calling handler <awscli.argprocess.ParamShorthand object at 0x7f5eb89df250>
2016-01-09 15:51:56,262 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.sse-c: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,263 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.expires: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,263 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.sse-c-copy-source: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,263 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.ignore-glacier-warnings: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,263 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.mv: calling handler <awscli.argprocess.ParamShorthand object at 0x7f5eb89df250>
2016-01-09 15:51:56,263 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.content-type: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,264 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.sse: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,264 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.metadata-directive: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,264 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.only-show-errors: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,264 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.mv: calling handler <awscli.argprocess.ParamShorthand object at 0x7f5eb89df250>
2016-01-09 15:51:56,264 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.anonymous: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,264 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.quiet: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,265 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.mv: calling handler <awscli.argprocess.ParamShorthand object at 0x7f5eb89df250>
2016-01-09 15:51:56,265 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.acl: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,265 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.storage-class: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,265 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.sse-kms-key-id: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,265 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.website-redirect: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,265 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.mv.follow-symlinks: calling handler <function uri_param at 0x7f5eb8b9e578>
2016-01-09 15:51:56,266 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.mv: calling handler <awscli.argprocess.ParamShorthand object at 0x7f5eb89df250>
2016-01-09 15:51:56,266 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-01-09 15:51:56,266 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-01-09 15:51:56,266 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2016-01-09 15:51:56,267 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2016-01-09 15:51:56,339 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-01-09 15:51:56,346 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f5eb8fb3b18>
2016-01-09 15:51:56,347 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f5eb8f9a758>
2016-01-09 15:51:56,352 - MainThread - botocore.client - DEBUG - Switching signature version for service s3 to version s3v4 based on config file override.
2016-01-09 15:51:56,354 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-01-09 15:51:56,356 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-01-09 15:51:56,359 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f5eb8fb3b18>
2016-01-09 15:51:56,359 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f5eb8f9a758>
2016-01-09 15:51:56,373 - MainThread - botocore.client - DEBUG - Switching signature version for service s3 to version s3v4 based on config file override.
2016-01-09 15:51:56,375 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-01-09 15:51:56,376 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-01-09 15:51:56,379 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f5eb8fb3b18>
2016-01-09 15:51:56,379 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f5eb8f9a758>
2016-01-09 15:51:56,384 - MainThread - botocore.client - DEBUG - Switching signature version for service s3 to version s3v4 based on config file override.
2016-01-09 15:51:56,385 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-01-09 15:51:56,386 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a part size of 8388608
2016-01-09 15:51:56,386 - MainThread - awscli.customizations.s3.executor - DEBUG - Using max queue size for s3 tasks of: 1000
2016-01-09 15:51:56,387 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a part size of 8388608
2016-01-09 15:51:56,387 - MainThread - awscli.customizations.s3.executor - DEBUG - Using max queue size for s3 tasks of: 2
2016-01-09 15:51:56,388 - MainThread - awscli.customizations.s3.executor - DEBUG - Using a threadpool size of: 10
2016-01-09 15:51:56,393 - MainThread - awscli.customizations.s3.executor - DEBUG - Submitting task: <awscli.customizations.s3.tasks.BasicTask object at 0x7f5eb8322a90>
2016-01-09 15:51:56,393 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,393 - Thread-5 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,393 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Worker thread invoking task: <awscli.customizations.s3.tasks.BasicTask object at 0x7f5eb8322a90>
2016-01-09 15:51:56,393 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,394 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,395 - Thread-7 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,395 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,395 - Thread-8 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,397 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,397 - Thread-9 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,405 - Thread-10 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,406 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,406 - Thread-11 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,408 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,408 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,409 - Thread-12 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,409 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,410 - Thread-13 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,410 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:51:56,411 - Thread-14 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-5, stopped daemon 140044777039616)>
2016-01-09 15:51:56,412 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-5, stopped daemon 140044777039616)>
2016-01-09 15:51:56,413 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-6, started daemon 140044768646912)>
2016-01-09 15:51:56,415 - Thread-6 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7f5eb8f461b8>
2016-01-09 15:51:56,415 - Thread-6 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x7f5eb8f46140>
2016-01-09 15:51:56,422 - Thread-6 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x7f5eb8f460c8>
2016-01-09 15:51:56,422 - Thread-6 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x7f5eb8f46578>
2016-01-09 15:51:56,422 - Thread-6 - botocore.handlers - DEBUG - Adding expect 100 continue header to request.
2016-01-09 15:51:56,423 - Thread-6 - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7f5eb8674dd0> (verify_ssl=True) with params: {'body': <open file u'/home/koolhead17/Desktop/hello.txt', mode 'rb' at 0x7f5eb8692e40>, 'url': u'http://localhost:9000/mybucket/hello.txt', 'headers': {'Content-MD5': u'vkNdAOO/Ly2ljOSDSGUr2w==', u'Content-Type': 'text/plain', 'Expect': '100-continue', 'User-Agent': 'aws-cli/1.9.17 Python/2.7.6 Linux/3.13.0-38-generic botocore/1.3.17'}, 'query_string': {}, 'url_path': u'/mybucket/hello.txt', 'method': u'PUT'}
2016-01-09 15:51:56,423 - Thread-6 - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f5eb85fe150>>
2016-01-09 15:51:56,424 - Thread-6 - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-01-09 15:51:56,425 - Thread-6 - botocore.auth - DEBUG - CanonicalRequest:
PUT
/mybucket/hello.txt

content-md5:vkNdAOO/Ly2ljOSDSGUr2w==
content-type:text/plain
expect:100-continue
host:localhost:9000
user-agent:aws-cli/1.9.17 Python/2.7.6 Linux/3.13.0-38-generic botocore/1.3.17
x-amz-content-sha256:bb4a9cbd401e3ed8b9bad674bbb50febe8b9df0acb4e2f87be7a79369ead6430
x-amz-date:20160109T102156Z

content-md5;content-type;expect;host;user-agent;x-amz-content-sha256;x-amz-date
bb4a9cbd401e3ed8b9bad674bbb50febe8b9df0acb4e2f87be7a79369ead6430
2016-01-09 15:51:56,425 - Thread-6 - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160109T102156Z
20160109/us-east-1/s3/aws4_request
fa978c7737c79e8975e8ee2e074f2a612c4c18f6e03005d8690ecdc218d4cf2e
2016-01-09 15:51:56,426 - Thread-6 - botocore.auth - DEBUG - Signature:
61ccd1d89d75417c85a552e7ed5c5f156e356d5e24d0e0ce693e68540d8f6d05
2016-01-09 15:51:56,438 - Thread-6 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2016-01-09 15:51:56,439 - Thread-6 - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2016-01-09 15:51:56,440 - Thread-6 - botocore.awsrequest - DEBUG - Waiting for 100 Continue response.
2016-01-09 15:51:56,442 - Thread-6 - botocore.awsrequest - DEBUG - 100 Continue response seen, now sending request body.
2016-01-09 15:51:56,445 - Thread-6 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /mybucket/hello.txt HTTP/1.1" 403 311
2016-01-09 15:51:56,446 - Thread-6 - botocore.parsers - DEBUG - Response headers: {'content-length': '311', 'accept-ranges': 'bytes', 'vary': 'Origin', 'server': 'Minio/OFFICIAL.2015-12-23T01-54-02Z (linux; amd64)', 'connection': 'close', 'x-amz-request-id': '8KN4WBHKH0MW2AMC', 'date': 'Sat, 09 Jan 2016 10:21:56 GMT', 'content-type': 'text/xml; charset=utf-8'}
2016-01-09 15:51:56,447 - Thread-6 - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided.</Message><Key></Key><BucketName></BucketName><Resource>/mybucket/hello.txt</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
2016-01-09 15:51:56,448 - Thread-6 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f5eb8427f50>
2016-01-09 15:51:56,448 - Thread-6 - botocore.retryhandler - DEBUG - No retry needed.
2016-01-09 15:51:56,448 - Thread-6 - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <function enhance_error_msg at 0x7f5eb8a187d0>
2016-01-09 15:51:56,448 - Thread-6 - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <awscli.errorhandler.ErrorHandler object at 0x7f5eb89df310>
2016-01-09 15:51:56,449 - Thread-6 - awscli.errorhandler - DEBUG - HTTP Response Code: 403
2016-01-09 15:51:56,449 - Thread-6 - awscli.customizations.s3.tasks - DEBUG - A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.
Traceback (most recent call last):
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/tasks.py", line 95, in _execute_task
    getattr(filename, filename.operation_name)(**kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.py", line 338, in move
    self.upload()
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.py", line 259, in upload
    self._handle_upload(body)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.py", line 270, in _handle_upload
    response_data = self.client.put_object(**params)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/client.py", line 403, in _make_api_call
    model=operation_model, context=request_context
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
ClientError: A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.
2016-01-09 15:51:56,452 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: PrintTask(message=u'move failed: ./hello.txt to s3://mybucket/hello.txt A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.', error=True, total_parts=None, warning=None)
move failed: ./hello.txt to s3://mybucket/hello.txt A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.
2016-01-09 15:51:56,452 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:51:56,463 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-6, stopped daemon 140044768646912)>
2016-01-09 15:51:56,464 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-7, stopped daemon 140044760254208)>
2016-01-09 15:51:56,464 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-7, stopped daemon 140044760254208)>
2016-01-09 15:51:56,464 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-8, stopped daemon 140044751861504)>
2016-01-09 15:51:56,465 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-8, stopped daemon 140044751861504)>
2016-01-09 15:51:56,465 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-9, stopped daemon 140044743468800)>
2016-01-09 15:51:56,465 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-9, stopped daemon 140044743468800)>
2016-01-09 15:51:56,465 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-10, stopped daemon 140044735076096)>
2016-01-09 15:51:56,465 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-10, stopped daemon 140044735076096)>
2016-01-09 15:51:56,466 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-11, stopped daemon 140044253787904)>
2016-01-09 15:51:56,466 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-11, stopped daemon 140044253787904)>
2016-01-09 15:51:56,466 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-12, stopped daemon 140044245395200)>
2016-01-09 15:51:56,466 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-12, stopped daemon 140044245395200)>
2016-01-09 15:51:56,467 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-13, stopped daemon 140044237002496)>
2016-01-09 15:51:56,467 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-13, stopped daemon 140044237002496)>
2016-01-09 15:51:56,467 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-14, stopped daemon 140044228609792)>
2016-01-09 15:51:56,467 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-14, stopped daemon 140044228609792)>
2016-01-09 15:51:56,467 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for result thread.
2016-01-09 15:51:56,468 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for IO thread.
2016-01-09 15:51:56,468 - Thread-2 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in IO thread, shutting down.
2016-01-09 15:51:56,468 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in print thread, shutting down print thread.
2016-01-09 15:51:56,469 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for result thread to shutdown.
2016-01-09 15:51:56,469 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for IO thread to shutdown.
2016-01-09 15:51:56,470 - MainThread - awscli.customizations.s3.executor - DEBUG - All threads have been shutdown.

```

**Comment by harshavardhana** [comment]
This works too.
