### ISSUE TITLE
unexpected " aws s3 cp " behavior

### ISSUE THREAD

**Issue by koolhead17** [minio/minio#1028]
I am trying to do basic minio operations with aws CLI, I tried executing copy operation. Please find detailed debug operation output.

```
$ aws --debug --endpoint-url http://localhost:9000 s3 cp share/sharegain/filter-coffee.jpg s3://mybucket/coffee.jpg
2016-01-09 15:58:14,858 - MainThread - awscli.clidriver - DEBUG - CLI version: aws-cli/1.9.17 Python/2.7.6 Linux/3.13.0-38-generic botocore/1.3.17
2016-01-09 15:58:14,858 - MainThread - awscli.clidriver - DEBUG - Arguments entered to CLI: ['--debug', '--endpoint-url', 'http://localhost:9000', 's3', 'cp', 'share/sharegain/filter-coffee.jpg', 's3://mybucket/coffee.jpg']
2016-01-09 15:58:14,858 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function add_scalar_parsers at 0x7fbef1fbd7d0>
2016-01-09 15:58:14,858 - MainThread - botocore.hooks - DEBUG - Event session-initialized: calling handler <function inject_assume_role_provider_cache at 0x7fbef200ff50>
2016-01-09 15:58:14,859 - MainThread - botocore.credentials - DEBUG - Skipping environment variable credential check because profile name was explicitly set.
2016-01-09 15:58:14,859 - MainThread - botocore.hooks - DEBUG - Event building-command-table.s3: calling handler <function add_waiters at 0x7fbef201a668>
2016-01-09 15:58:14,861 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.s3.anonymous: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,861 - MainThread - botocore.hooks - DEBUG - Event building-command-table.cp: calling handler <function add_waiters at 0x7fbef201a668>
2016-01-09 15:58:14,867 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-key: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,867 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expected-size: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,867 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.grants: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,868 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-language: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,868 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.page-size: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,868 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,868 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source-key: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,869 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.paths: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,869 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,869 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.source-region: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,869 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-encoding: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,870 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-disposition: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,870 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.cache-control: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,870 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,870 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.dryrun: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,870 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthand object at 0x7fbef1fd6250>
2016-01-09 15:58:14,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.expires: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-c-copy-source: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,871 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.ignore-glacier-warnings: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,872 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthand object at 0x7fbef1fd6250>
2016-01-09 15:58:14,872 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.content-type: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,872 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,873 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.metadata-directive: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,873 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.only-show-errors: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,873 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthand object at 0x7fbef1fd6250>
2016-01-09 15:58:14,873 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.anonymous: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,874 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.quiet: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,874 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthand object at 0x7fbef1fd6250>
2016-01-09 15:58:14,874 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.acl: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.storage-class: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.sse-kms-key-id: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.website-redirect: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,875 - MainThread - botocore.hooks - DEBUG - Event load-cli-arg.custom.cp.follow-symlinks: calling handler <function uri_param at 0x7fbef2195578>
2016-01-09 15:58:14,875 - MainThread - botocore.hooks - DEBUG - Event process-cli-arg.custom.cp: calling handler <awscli.argprocess.ParamShorthand object at 0x7fbef1fd6250>
2016-01-09 15:58:14,876 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: env
2016-01-09 15:58:14,876 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: assume-role
2016-01-09 15:58:14,876 - MainThread - botocore.credentials - DEBUG - Looking for credentials via: shared-credentials-file
2016-01-09 15:58:14,877 - MainThread - botocore.credentials - INFO - Found credentials in shared credentials file: ~/.aws/credentials
2016-01-09 15:58:14,949 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-01-09 15:58:14,957 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fbef25aab18>
2016-01-09 15:58:14,957 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fbef2591758>
2016-01-09 15:58:14,964 - MainThread - botocore.client - DEBUG - Switching signature version for service s3 to version s3v4 based on config file override.
2016-01-09 15:58:14,967 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-01-09 15:58:14,969 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-01-09 15:58:14,972 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fbef25aab18>
2016-01-09 15:58:14,972 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fbef2591758>
2016-01-09 15:58:14,982 - MainThread - botocore.client - DEBUG - Switching signature version for service s3 to version s3v4 based on config file override.
2016-01-09 15:58:14,983 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-01-09 15:58:14,984 - MainThread - botocore.client - DEBUG - Registering retry handlers for service: s3
2016-01-09 15:58:14,988 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7fbef25aab18>
2016-01-09 15:58:14,988 - MainThread - botocore.hooks - DEBUG - Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7fbef2591758>
2016-01-09 15:58:14,993 - MainThread - botocore.client - DEBUG - Switching signature version for service s3 to version s3v4 based on config file override.
2016-01-09 15:58:14,994 - MainThread - botocore.endpoint - DEBUG - Setting s3 timeout as (60, 60)
2016-01-09 15:58:14,995 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a part size of 8388608
2016-01-09 15:58:14,996 - MainThread - awscli.customizations.s3.executor - DEBUG - Using max queue size for s3 tasks of: 1000
2016-01-09 15:58:14,996 - MainThread - awscli.customizations.s3.s3handler - DEBUG - Using a multipart threshold of 8388608 and a part size of 8388608
2016-01-09 15:58:14,997 - MainThread - awscli.customizations.s3.executor - DEBUG - Using max queue size for s3 tasks of: 2
2016-01-09 15:58:14,998 - MainThread - awscli.customizations.s3.executor - DEBUG - Using a threadpool size of: 10
2016-01-09 15:58:15,002 - MainThread - awscli.customizations.s3.executor - DEBUG - Submitting task: <awscli.customizations.s3.tasks.BasicTask object at 0x7fbef1918b50>
2016-01-09 15:58:15,003 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,003 - Thread-5 - awscli.customizations.s3.executor - DEBUG - Worker thread invoking task: <awscli.customizations.s3.tasks.BasicTask object at 0x7fbef1918b50>
2016-01-09 15:58:15,004 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,004 - Thread-6 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,005 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,006 - Thread-7 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,006 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,006 - Thread-8 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,008 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,008 - Thread-9 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,009 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,010 - Thread-10 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,011 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,011 - Thread-11 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,012 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,013 - Thread-12 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,013 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,014 - Thread-13 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,015 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for worker thread (priority: 11)
2016-01-09 15:58:15,015 - Thread-14 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,015 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-5, started daemon 140458056455936)>
2016-01-09 15:58:15,029 - Thread-5 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7fbef253d1b8>
2016-01-09 15:58:15,030 - Thread-5 - botocore.hooks - DEBUG - Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x7fbef253d140>
2016-01-09 15:58:15,035 - Thread-5 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x7fbef253d0c8>
2016-01-09 15:58:15,035 - Thread-5 - botocore.hooks - DEBUG - Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x7fbef253d578>
2016-01-09 15:58:15,036 - Thread-5 - botocore.handlers - DEBUG - Adding expect 100 continue header to request.
2016-01-09 15:58:15,036 - Thread-5 - botocore.endpoint - DEBUG - Making request for <botocore.model.OperationModel object at 0x7fbef1c6bed0> (verify_ssl=True) with params: {'body': <open file u'/home/koolhead17/Desktop/share/sharegain/filter-coffee.jpg', mode 'rb' at 0x7fbef1c8ae40>, 'url': u'http://localhost:9000/mybucket/coffee.jpg', 'headers': {'Content-MD5': u'7FgxPuugREsJH7jrMSpq8A==', u'Content-Type': 'image/jpeg', 'Expect': '100-continue', 'User-Agent': 'aws-cli/1.9.17 Python/2.7.6 Linux/3.13.0-38-generic botocore/1.3.17'}, 'query_string': {}, 'url_path': u'/mybucket/coffee.jpg', 'method': u'PUT'}
2016-01-09 15:58:15,036 - Thread-5 - botocore.hooks - DEBUG - Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7fbef1bf5250>>
2016-01-09 15:58:15,038 - Thread-5 - botocore.auth - DEBUG - Calculating signature using v4 auth.
2016-01-09 15:58:15,038 - Thread-5 - botocore.auth - DEBUG - CanonicalRequest:
PUT
/mybucket/coffee.jpg

content-md5:7FgxPuugREsJH7jrMSpq8A==
content-type:image/jpeg
expect:100-continue
host:localhost:9000
user-agent:aws-cli/1.9.17 Python/2.7.6 Linux/3.13.0-38-generic botocore/1.3.17
x-amz-content-sha256:85d43d9100694f7a81ae286710321225b718776a902f51a538e716b51e2a3bf1
x-amz-date:20160109T102815Z

content-md5;content-type;expect;host;user-agent;x-amz-content-sha256;x-amz-date
85d43d9100694f7a81ae286710321225b718776a902f51a538e716b51e2a3bf1
2016-01-09 15:58:15,039 - Thread-5 - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20160109T102815Z
20160109/us-east-1/s3/aws4_request
db7ee8f2ed579c7be29a2132bab18045ae1e710c0c55d3ffed3dd4eb622cdbbc
2016-01-09 15:58:15,039 - Thread-5 - botocore.auth - DEBUG - Signature:
3ecf16f313afbf30b7abe2f34a7c60fba0ea15b6415401530f7f6fe9c707f4fd
2016-01-09 15:58:15,047 - Thread-5 - botocore.endpoint - DEBUG - Sending http request: <PreparedRequest [PUT]>
2016-01-09 15:58:15,050 - Thread-5 - botocore.vendored.requests.packages.urllib3.connectionpool - INFO - Starting new HTTP connection (1): localhost
2016-01-09 15:58:15,051 - Thread-5 - botocore.awsrequest - DEBUG - Waiting for 100 Continue response.
2016-01-09 15:58:15,053 - Thread-5 - botocore.awsrequest - DEBUG - 100 Continue response seen, now sending request body.
2016-01-09 15:58:15,056 - Thread-5 - botocore.vendored.requests.packages.urllib3.connectionpool - DEBUG - "PUT /mybucket/coffee.jpg HTTP/1.1" 403 312
2016-01-09 15:58:15,058 - Thread-5 - botocore.parsers - DEBUG - Response headers: {'content-length': '312', 'accept-ranges': 'bytes', 'vary': 'Origin', 'server': 'Minio/OFFICIAL.2015-12-23T01-54-02Z (linux; amd64)', 'connection': 'close', 'x-amz-request-id': '0UA5XAMUBDM69VX1', 'date': 'Sat, 09 Jan 2016 10:28:15 GMT', 'content-type': 'text/xml; charset=utf-8'}
2016-01-09 15:58:15,059 - Thread-5 - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided.</Message><Key></Key><BucketName></BucketName><Resource>/mybucket/coffee.jpg</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
2016-01-09 15:58:15,060 - Thread-5 - botocore.hooks - DEBUG - Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7fbef1991090>
2016-01-09 15:58:15,060 - Thread-5 - botocore.retryhandler - DEBUG - No retry needed.
2016-01-09 15:58:15,060 - Thread-5 - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <function enhance_error_msg at 0x7fbef200f7d0>
2016-01-09 15:58:15,061 - Thread-5 - botocore.hooks - DEBUG - Event after-call.s3.PutObject: calling handler <awscli.errorhandler.ErrorHandler object at 0x7fbef1fd6310>
2016-01-09 15:58:15,061 - Thread-5 - awscli.errorhandler - DEBUG - HTTP Response Code: 403
2016-01-09 15:58:15,061 - Thread-5 - awscli.customizations.s3.tasks - DEBUG - A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.
Traceback (most recent call last):
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/tasks.py", line 95, in _execute_task
    getattr(filename, filename.operation_name)(**kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.py", line 259, in upload
    self._handle_upload(body)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/customizations/s3/fileinfo.py", line 270, in _handle_upload
    response_data = self.client.put_object(**params)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/client.py", line 403, in _make_api_call
    model=operation_model, context=request_context
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/hooks.py", line 226, in emit
    return self._emit(event_name, kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/botocore/hooks.py", line 209, in _emit
    response = handler(**kwargs)
  File "/home/koolhead17/.local/lib/aws/local/lib/python2.7/site-packages/awscli/errorhandler.py", line 70, in __call__
    http_status_code=http_response.status_code)
ClientError: A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.
2016-01-09 15:58:15,063 - Thread-5 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in worker thread, shutting down worker thread.
2016-01-09 15:58:15,064 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Received print task: PrintTask(message=u'upload failed: share/sharegain/filter-coffee.jpg to s3://mybucket/coffee.jpg A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.', error=True, total_parts=None, warning=None)
upload failed: share/sharegain/filter-coffee.jpg to s3://mybucket/coffee.jpg A client error (SignatureDoesNotMatch) occurred when calling the PutObject operation: The request signature we calculated does not match the signature you provided.
2016-01-09 15:58:15,087 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-5, stopped daemon 140458056455936)>
2016-01-09 15:58:15,087 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-6, stopped daemon 140457845716736)>
2016-01-09 15:58:15,088 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-6, stopped daemon 140457845716736)>
2016-01-09 15:58:15,088 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-7, stopped daemon 140457837324032)>
2016-01-09 15:58:15,089 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-7, stopped daemon 140457837324032)>
2016-01-09 15:58:15,089 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-8, stopped daemon 140457828931328)>
2016-01-09 15:58:15,090 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-8, stopped daemon 140457828931328)>
2016-01-09 15:58:15,090 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-9, stopped daemon 140457820538624)>
2016-01-09 15:58:15,091 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-9, stopped daemon 140457820538624)>
2016-01-09 15:58:15,091 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-10, stopped daemon 140457812145920)>
2016-01-09 15:58:15,092 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-10, stopped daemon 140457812145920)>
2016-01-09 15:58:15,092 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-11, stopped daemon 140457803753216)>
2016-01-09 15:58:15,092 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-11, stopped daemon 140457803753216)>
2016-01-09 15:58:15,092 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-12, stopped daemon 140457795360512)>
2016-01-09 15:58:15,092 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-12, stopped daemon 140457795360512)>
2016-01-09 15:58:15,093 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-13, stopped daemon 140457308845824)>
2016-01-09 15:58:15,093 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-13, stopped daemon 140457308845824)>
2016-01-09 15:58:15,093 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for thread to shutdown: <Worker(Thread-14, stopped daemon 140457300453120)>
2016-01-09 15:58:15,093 - MainThread - awscli.customizations.s3.executor - DEBUG - Thread has been shutdown: <Worker(Thread-14, stopped daemon 140457300453120)>
2016-01-09 15:58:15,094 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for result thread.
2016-01-09 15:58:15,094 - MainThread - awscli.customizations.s3.executor - DEBUG - Queueing end sentinel for IO thread.

2016-01-09 15:58:15,094 - Thread-1 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in print thread, shutting down print thread.
2016-01-09 15:58:15,095 - Thread-2 - awscli.customizations.s3.executor - DEBUG - Shutdown request received in IO thread, shutting down.
2016-01-09 15:58:15,095 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for result thread to shutdown.
2016-01-09 15:58:15,096 - MainThread - awscli.customizations.s3.executor - DEBUG - Waiting for IO thread to shutdown.
2016-01-09 15:58:15,096 - MainThread - awscli.customizations.s3.executor - DEBUG - All threads have been shutdown.
```

**Comment by harshavardhana** [comment]
```
$ aws --endpoint-url http://localhost:9000 s3 cp /usr/bin/emacs s3://testbbucket
upload: ../../../../../../../usr/bin/emacs to s3://testbbucket/emacs
```

```
$ aws --endpoint-url http://localhost:9000 s3 sync /usr/bin s3://testbbucket
...
...
upload: ../../../../../../../usr/bin/zfgrep to s3://testbbucket/zfgrep
upload: ../../../../../../../usr/bin/zforce to s3://testbbucket/zforce
upload: ../../../../../../../usr/bin/zgrep to s3://testbbucket/zgrep
upload: ../../../../../../../usr/bin/zip to s3://testbbucket/zip
upload: ../../../../../../../usr/bin/zipcloak to s3://testbbucket/zipcloak
upload: ../../../../../../../usr/bin/zipdetails to s3://testbbucket/zipdetails
upload: ../../../../../../../usr/bin/zipdetails5.16 to s3://testbbucket/zipdetails5.16
upload: ../../../../../../../usr/bin/zipdetails5.18 to s3://testbbucket/zipdetails5.18
upload: ../../../../../../../usr/bin/zipgrep to s3://testbbucket/zipgrep
upload: ../../../../../../../usr/bin/zipinfo to s3://testbbucket/zipinfo
upload: ../../../../../../../usr/bin/zipnote to s3://testbbucket/zipnote
upload: ../../../../../../../usr/bin/zipsplit to s3://testbbucket/zipsplit
upload: ../../../../../../../usr/bin/zless to s3://testbbucket/zless
upload: ../../../../../../../usr/bin/zmore to s3://testbbucket/zmore
upload: ../../../../../../../usr/bin/znew to s3://testbbucket/znew
upload: ../../../../../../../usr/bin/zprint to s3://testbbucket/zprint
```

**Comment by harshavardhana** [comment]
Failed for me too..
