### ISSUE TITLE
IO wait error

### ISSUE THREAD

**Issue by shouldnotappearcalm** [minio/minio#10316]
My minio will get stuck in SDK calls every 10 hours or so, and there are many IO Wait errors in the log,my minio data disk is mounted via nfs,and the reading and writing of nfs is between 20MB/s and 50MB/s

```log
goroutine 11840082 [IO wait, 3 minutes]:
internal/poll.runtime_pollWait(0x7f302deee8c0, 0x72, 0xffffffffffffffff)
	/opt/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc000d88018, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc000d88000, 0xc000e55000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc000d88000, 0xc000e55000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0011b6028, 0xc000e55000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:177 +0x69
github.com/minio/minio/cmd/http.(*DeadlineConn).Read(0xc0023c8150, 0xc000e55000, 0x1000, 0x1000, 0xc0018f1860, 0x1955fa7, 0xe)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/deadlineconn.go:49 +0x63
net/http.(*connReader).Read(0xc0023c81e0, 0xc000e55000, 0x1000, 0x1000, 0x0, 0xffffffffffffffff, 0x0)
	/opt/go/src/net/http/server.go:787 +0x107
bufio.(*Reader).fill(0xc000e7c060)
	/opt/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc000e7c060, 0xc000cf5a0a, 0x195b3bd, 0xc000cf5b00, 0x40be29, 0xc000179c00, 0x100)
	/opt/go/src/bufio/bufio.go:356 +0x3d
bufio.(*Reader).ReadLine(0xc000e7c060, 0xc000cf5b08, 0xc00086a380, 0x7f30306de460, 0x0, 0x48999d, 0x18b2800)
	/opt/go/src/bufio/bufio.go:385 +0x34
net/textproto.(*Reader).readLineSlice(0xc001f28270, 0xc000179c00, 0xc000d88000, 0x0, 0x0, 0x0)
	/opt/go/src/net/textproto/reader.go:55 +0x6f
net/textproto.(*Reader).ReadLine(...)
	/opt/go/src/net/textproto/reader.go:36
net/http.readRequest(0xc000e7c060, 0x0, 0xc000179c00, 0x0, 0x0)
	/opt/go/src/net/http/request.go:968 +0x8d
net/http.(*conn).readRequest(0xc001046640, 0x1c36a60, 0xc0004b81c0, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/server.go:967 +0x163
net/http.(*conn).serve(0xc001046640, 0x1c36a60, 0xc0004b81c0)
	/opt/go/src/net/http/server.go:1819 +0x6ad
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2884 +0x2f4

goroutine 12075973 [IO wait, 4 minutes]:
internal/poll.runtime_pollWait(0x7f302e176d08, 0x72, 0xffffffffffffffff)
	/opt/go/src/runtime/netpoll.go:182 +0x56
internal/poll.(*pollDesc).wait(0xc001012d18, 0x72, 0x1000, 0x1000, 0xffffffffffffffff)
	/opt/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b
internal/poll.(*pollDesc).waitRead(...)
	/opt/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc001012d00, 0xc0015b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/internal/poll/fd_unix.go:169 +0x19b
net.(*netFD).Read(0xc001012d00, 0xc0015b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc00073e228, 0xc0015b2000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/opt/go/src/net/net.go:177 +0x69
github.com/minio/minio/cmd/http.(*DeadlineConn).Read(0xc000569710, 0xc0015b2000, 0x1000, 0x1000, 0xc0019ea2d0, 0x1955fa7, 0xe)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/deadlineconn.go:49 +0x63
net/http.(*connReader).Read(0xc0005697a0, 0xc0015b2000, 0x1000, 0x1000, 0x200, 0xc00123c5d0, 0x0)
	/opt/go/src/net/http/server.go:787 +0x107
bufio.(*Reader).fill(0xc0015b4660)
	/opt/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadSlice(0xc0015b4660, 0xa, 0x28, 0xc000821b00, 0x40be29, 0xc0014a4900, 0x100)
	/opt/go/src/bufio/bufio.go:356 +0x3d
bufio.(*Reader).ReadLine(0xc0015b4660, 0xc000821b08, 0xc000adae00, 0x7f30306dd6d0, 0x0, 0x40c6b8, 0x30)
	/opt/go/src/bufio/bufio.go:385 +0x34
net/textproto.(*Reader).readLineSlice(0xc00123c5d0, 0xc0014a4900, 0xc001012d00, 0x0, 0x0, 0x0)
	/opt/go/src/net/textproto/reader.go:55 +0x6f
net/textproto.(*Reader).ReadLine(...)
	/opt/go/src/net/textproto/reader.go:36
net/http.readRequest(0xc0015b4660, 0x0, 0xc0014a4900, 0x0, 0x0)
	/opt/go/src/net/http/request.go:968 +0x8d
net/http.(*conn).readRequest(0xc000630f00, 0x1c36a60, 0xc000485300, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/server.go:967 +0x163
net/http.(*conn).serve(0xc000630f00, 0x1c36a60, 0xc000485300)
	/opt/go/src/net/http/server.go:1819 +0x6ad
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2884 +0x2f4
```

```
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.minio.MinioClient.executeReq(MinioClient.java:1097)
	at io.minio.MinioClient.execute(MinioClient.java:1056)
	at io.minio.MinioClient.executePost(MinioClient.java:1354)
	at io.minio.MinioClient.initMultipartUpload(MinioClient.java:4720)
	at io.minio.MinioClient.putObject(MinioClient.java:4046)
	at io.minio.MinioClient.putObject(MinioClient.java:3952)
	at com.thunisoft.cloud.storage.client.minio.client.MinioClient.putObject(MinioClient.java:155)
	... 144 common frames omitted
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 171 common frames omitted
```

## Your Environment

* Version used (`minio --version`):
2019-08-07T01:59:21Z
* Server setup and configuration:
* Operating System and version (`uname -a`):
Centos7 3.10.0-862-el7.x86_64

[nohup_202008201941.txt](https://github.com/minio/minio/files/5107827/nohup_202008201941.txt)

**Comment by klauspost** [comment]
Your server version is almost a year old. Please upgrade.

**Comment by shouldnotappearcalm** [comment]
> Your server version is almost a year old. Please upgrade.

Has anyone reported this issue? Do you have similar issues?

**Comment by harshavardhana** [comment]
> Has anyone reported this issue? Do you have similar issues?

@shouldnotappearcalm no we do not, but better to look at `NFS` mounts here

**Comment by shouldnotappearcalm** [comment]
thanks
