### ISSUE TITLE
The upload is not passed into the Content-Length minio and cannot be processed normally

### ISSUE THREAD

**Issue by shouldnotappearcalm** [minio/minio#10334]
I encountered a strange problem when using minio. First of all, this problem may be related to nfs mount, but I am not sure. My minio will get stuck after using it for a day. When using minio-client java sdk, the upload will fail. The error message informs me that there is no Content-Length parameter in the request header. Then I modified it to use the putObject method that passed in the fileSize. This stuttering problem will not occur, but after I restarted my minio, the putObject method does not pass fileSize and this error message will not appear, but this situation can only last for about one day,minio version is not high, but because For some reasons, we cannot upgrade temporarily.we try to use minio-client 7 without passing in fileSize and there will be no problems.

```java
Caused by: java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:232)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:286)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:241)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
	at io.minio.MinioClient.executeReq(MinioClient.java:1097)
	at io.minio.MinioClient.execute(MinioClient.java:1056)
	at io.minio.MinioClient.executePost(MinioClient.java:1354)
	at io.minio.MinioClient.initMultipartUpload(MinioClient.java:4720)
	at io.minio.MinioClient.putObject(MinioClient.java:4046)
	at io.minio.MinioClient.putObject(MinioClient.java:3952)
	at com.thunisoft.cloud.storage.client.minio.client.MinioClient.putObject(MinioClient.java:155)
	... 144 common frames omitted
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:140)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	... 171 common frames omitted
```

## Your Environment

minio: 2019-08-07T01:59:21Z
operation-system: Centos7 3.10.0-862-el7.x86_64

**Comment by harshavardhana** [comment]
@shouldnotappearcalm the issue description is super confusing, not sure what are you trying to say here..

Can you provide information regarding

- A sample code which you use?
- upgrade MinIO if possible, looks like more than year old?

**Comment by shouldnotappearcalm** [comment]
Indeed, this problem is very contradictory. After minio runs for a day, uploading using `putObject(String bucketName, String objectName, String fileName)` will fail, throwing errors related to Socket closed, but using `putObject(String bucketName, String objectName, InputStream) stream, long size, String contentType)` he can still upload normally

**Comment by shouldnotappearcalm** [comment]
After restarting minio, the file uploaded by the `putObject(String bucketName, String objectName, String fileName)` method can be uploaded to minio normally for one day, but after a day, it cannot be uploaded to minio using this method.

**Comment by harshavardhana** [comment]
> Indeed, this problem is very contradictory. After minio runs for a day, uploading using `putObject(String bucketName, String objectName, String fileName)` will fail, throwing errors related to Socket closed, but using `putObject(String bucketName, String objectName, InputStream) stream, long size, String contentType)` he can still upload normally

That looks like connection leak issue of some kind on the client.

Which version of Java SDK are you using?
Why not upgrade the server and test?

**Comment by shouldnotappearcalm** [comment]
We tested that minio client java 6.0.13 will also have this problem, and minio cannot be upgraded temporarily for some other reasons.

**Comment by shouldnotappearcalm** [comment]
It does not feel that the client connection leaks, because I restart the client and there should still be problems

**Comment by harshavardhana** [comment]
> We tested that minio client java 6.0.13 will also have this problem, and minio cannot be upgraded temporarily for some other reasons.

We can only debug here if you upgrade @shouldnotappearcalm the code has changed significantly.

Get back to us once you have upgraded

**Comment by shouldnotappearcalm** [comment]
Okay, let's try upgrading too, thanks

**Comment by klauspost** [comment]
Closing for now. Feel free to open another issue.
