### ISSUE TITLE
[resolved] [FS] CopyObject returns 404 Not Found even though headObject succeeds in 

### ISSUE THREAD

**Issue by lallinger-tech** [minio/minio#10475]
When trying to update a objects metadata using copyObject and metadata directive `REPLACE` the call fails with 404 Not Found even though the key exists and a previous headObject returns 200 Ok.

## Expected Behavior
If headObject on a key succeeds it should be possible to call copyObject immediately after.

## Current Behavior
The headObject operation succeeds with 200 Ok but a following copyObject call with the same bucket and key and same source and destination fails with 404 Not Found.

## Steps to Reproduce (for bugs)

1. docker run lallinger/minio-test

Output from the container:
```
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Added `minio` successfully.
total 40992
-rw-r--r-- 1 root root 41943040 Sep 14 11:40 big
-rw-r--r-- 1 root root    32768 Sep 14 11:40 small
mc: <DEBUG> GET /minio/admin/v3/trace?all=false&err=false HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-09-03T00:08:28Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200914T114039Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Security-Policy: block-all-mixed-content
Content-Type: text/event-stream
Date: Mon, 14 Sep 2020 11:40:39 GMT
Vary: Origin
X-Accel-Buffering: no
X-Amz-Request-Id: 1634A397B4643257
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  24.610747ms

localhost [REQUEST s3.GetBucketLocation] 11:40:39.608
localhost GET /test/?location=
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T114039Z
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=881c6262d5034bc3639b9ad0f5d2e816efa82bfaaf0f314bbc76ec1ebd91e2c1
localhost Content-Length: 0
localhost
localhost [RESPONSE] [11:40:39.608] [ Duration 173µs  ↑ 77 B  ↓ 378 B ]
localhost 200 OK
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634A397B5C21D34
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 128
localhost Content-Security-Policy: block-all-mixed-content
localhost <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
localhost
localhost [REQUEST s3.HeadBucket] 11:40:39.609
localhost HEAD /test/
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T114039Z
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=b778d08c01da3c0b18e20abb8bdb60596561fde87a8aa54425109747b6fb65d9
localhost Content-Length: 0
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost
localhost [RESPONSE] [11:40:39.609] [ Duration 127µs  ↑ 77 B  ↓ 218 B ]
localhost 200 OK
localhost Accept-Ranges: bytes
localhost Content-Length: 0
localhost Content-Security-Policy: block-all-mixed-content
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634A397B5D3D54C
localhost X-Xss-Protection: 1; mode=block
localhost
localhost
localhost [REQUEST s3.ListObjectsV2] 11:40:39.610
localhost GET /test/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost X-Amz-Date: 20200914T114039Z
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=f95892907ece133f0d9588c70e1d8c6a9f25b05ea44a2ac2e30bc9a7470abb3f
localhost Content-Length: 0
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost
localhost [RESPONSE] [11:40:39.610] [ Duration 396µs  ↑ 77 B  ↓ 1.1 KiB ]
localhost 200 OK
localhost Content-Length: 926
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634A397B5DE1537
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix></Prefix><KeyCount>2</KeyCount><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><Contents><Key>big</Key><LastModified>2020-09-14T11:40:39.592Z</LastModified><ETag>&#34;00000000000000000000000000000000-1&#34;</ETag><Size>41943040</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName></DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents><Contents><Key>small</Key><LastModified>2020-09-14T11:40:39.569Z</LastModified><ETag>&#34;00000000000000000000000000000000-1&#34;</ETag><Size>32768</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName></DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents><EncodingType>url</EncodingType></ListBucketResult>
localhost
[2020-09-14 11:40:39 UTC]   40MiB big
[2020-09-14 11:40:39 UTC]   32KiB small
start
localhost [REQUEST s3.HeadObject] 11:40:44.787
localhost HEAD /test/big
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=66434d1cbabac31003fa2ab35789b49193c520db55d7806cc54cf2a70571ae6c
localhost Connection: close
localhost Content-Length: 0
localhost User-Agent: aws-sdk-nodejs/2.751.0 linux/v10.22.0 promise
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T114044Z
localhost
localhost [RESPONSE] [11:40:44.787] [ Duration 316µs  ↑ 88 B  ↓ 352 B ]
localhost 200 OK
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost Content-Type: application/octet-stream
localhost Last-Modified: Mon, 14 Sep 2020 11:40:39 GMT
localhost Content-Security-Policy: block-all-mixed-content
localhost ETag: "00000000000000000000000000000000-1"
localhost X-Amz-Request-Id: 1634A398EA77BDB8
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 41943040
localhost
localhost

API: CopyObject(bucket=test, object=big)
Time: 11:40:45 UTC 09/14/2020
DeploymentID: d49c7684-4898-47c5-829a-8e34900ce0e8
RequestID: 1634A3992712908A
RemoteHost: 127.0.0.1
Host: localhost:9000
UserAgent: aws-sdk-nodejs/2.751.0 linux/v10.22.0 promise
Error: file not found
       5: cmd/fs-v1.go:625:cmd.(*FSObjects).CopyObject()
       4: cmd/object-handlers.go:1255:cmd.objectAPIHandlers.CopyObjectHandler()
       3: cmd/http-tracer.go:127:cmd.Trace()
       2: cmd/handler-utils.go:354:cmd.httpTraceAll.func1()
       1: net/http/server.go:2041:http.HandlerFunc.ServeHTTP()
localhost [REQUEST s3.CopyObject] 11:40:45.804
localhost PUT /test/big
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-meta-id1;x-amz-metadata-directive, Signature=750aa4047c0bc503cc70b0ca49591d7cabc8c88ac1777ba6abcbef2e27a020fb
localhost Content-Length: 0
localhost Content-Type: application/octet-stream
localhost User-Agent: aws-sdk-nodejs/2.751.0 linux/v10.22.0 promise
localhost X-Amz-Date: 20200914T114045Z
localhost X-Amz-Meta-Id1: Test
localhost X-Amz-Metadata-Directive: REPLACE
localhost Connection: close
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Copy-Source: test/big
localhost
localhost [RESPONSE] [11:40:45.804] [ Duration 430µs  ↑ 159 B  ↓ 550 B ]
localhost 404 Not Found
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634A3992712908A
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 293
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>big</Key><BucketName>test</BucketName><Resource>/test/big</Resource><RequestId>1634A3992712908A</RequestId><HostId>d49c7684-4898-47c5-829a-8e34900ce0e8</HostId></Error>
localhost
{ NoSuchKey: The specified key does not exist.
    at Request.extractError (/home/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (/home/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message: 'The specified key does not exist.',
  code: 'NoSuchKey',
  region: null,
  time: 2020-09-14T11:40:45.809Z,
  requestId: '1634A3992712908A',
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 404,
  retryable: false,
  retryDelay: 49.06644666051376 }
```

Dockerfile:
```
from minio/minio:RELEASE.2020-09-10T22-02-45Z as minio
from node:10

RUN mkdir /CREDITS
COPY --from=minio /usr/bin/minio /usr/bin/minio
COPY --from=minio /CREDITS/ /CREDITS/
COPY --from=minio /usr/bin/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENV MINIO_ACCESS_KEY=admin
ENV MINIO_SECRET_KEY=admintest
ENV npm_config_loglevel=error

WORKDIR /home
RUN head -c 32k </dev/urandom | base64 - | head -c 32k > small
RUN head -c 40M </dev/urandom | base64 - | head -c 40M > big
RUN npm install aws-sdk
RUN wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
RUN chmod +x mc
RUN mv mc /usr/bin/mc
COPY test.js /home/test.js
COPY startup.sh /home/startup.sh
RUN chmod +x /home/startup.sh

CMD ["/home/startup.sh"]
```

startup.sh:
```
#/bin/sh
mkdir -p /data/test 
/usr/bin/docker-entrypoint.sh minio server /data & 
sleep 5
mc alias set minio http://localhost:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY 
mc admin trace minio --debug -v & 
cp /home/small /data/test/
cp /home/big /data/test/
ls -l /data/test
mc ls minio/test
sleep 5
node /home/test.js
```

test.js:
```
const fs = require('fs');
const file = 'small';
const file2 = 'big';
const bucket = 'test';
const http = require('http');
const AWS = require("aws-sdk");
const s3Client = new AWS.S3({
    accessKeyId: 'admin',
    secretAccessKey: 'admintest',
    endpoint: 'http://localhost:9000',
    sslEnabled: false,
    s3ForcePathStyle: true,
    httpOptions: {
        agent: new http.Agent({})
    }
});

function Sleep(milliseconds) {
    return new Promise(resolve => setTimeout(resolve, milliseconds));
}

async function head() {
    let data = await s3Client.headObject({
        Bucket: bucket,
        Key: file2
    }).promise();

    if (!data) {
        console.log('head failed for ' + file2 + ' with:', err);
        return;
    }
    let origMeta = data['Metadata'];
    let myMeta = { id1: 'Test' };
    let fullMeta = Object.assign(origMeta, myMeta);
    await Sleep(1000);
    await copy(bucket, file2, fullMeta);
    return;
}

async function copy(bucket, key, metadata) {
    try {
        let data = await s3Client.copyObject({
            Bucket: bucket,
            Key: key,
            CopySource: bucket + '/' + key,
            Metadata: metadata,
            MetadataDirective: 'REPLACE'
        }).promise();

        if (!data) {
            console.log('copy failed for ' + bucket + '/' + key + ' with:', d);
            return;
        }
    } catch (err) {
        console.log(err);
    }
}

console.log('start');
head()    
```

## Context

We are using Noobaa to upload files to MinIO (deployed as standalone in an OKD 4.5 cluster) and after every upload we trigger a nodejs function which performs a headObject to retrieve the metadata. To the original metadata we add an id and use copyObject with the replace metadata directive to add this id to the object. This fails from time to time with a 404 Not Found, even though the headObject before succeeds. I was not able to reproduce the complete setup with the upload from the aws nodejs sdk in a container and getting the same error behavior.

Also the root cause seems to be a race condition, because i can easily reproduce the error when using port forwarding when i have low latency and can not reproduce it with higher latency. I'll provide logs for this race condition tommorow.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-09-10T22-02-45Z
* Server setup and configuration: OKD 4.5 cluster
* Operating System and version (`uname -a`): Linux minio-5d5bf4bbb4-57p5v 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 Linux

**Comment by harshavardhana** [comment]
Thanks for the detailed issue report and such a nice reproducer, should be fixed in #10485

**Comment by lallinger-tech** [comment]
Thank you for the very fast pull request! I was too busy today to try it out, i will test it tomorrow and give you feedback!

**Comment by lallinger-tech** [comment]
Thanks alot this is fixed as far as i can see!
