### ISSUE TITLE
[not our bug] CopyObject fails with SignatureDoesNotMatch when using uppercase metadata

### ISSUE THREAD

**Issue by lallinger-tech** [minio/minio#10488]
When you use copyObject twice on the same object with metadata-directive replace and set a uppercase metadata property the second time always fails with SignatureDoesNotMatch.

## Expected Behavior

Both copyObject calls should succeed even with a uppercase metadata property.

## Current Behavior

The first copyObject succeeds and the second one fails with SignatureDoesNotMatch.

## Steps to Reproduce (for bugs)

1. `docker run lallinger/minio-test-meta`

Output from the container:
```
Attempting encryption of all config, IAM users and policies on MinIO backend
Endpoint:  http://172.17.0.2:9000  http://127.0.0.1:9000

Browser Access:
   http://172.17.0.2:9000  http://127.0.0.1:9000

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Added `minio` successfully.
mc: <DEBUG> GET /minio/admin/v3/trace?all=false&err=false HTTP/1.1
Host: localhost:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/2020-09-03T00:08:28Z
Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200914T210316Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Transfer-Encoding: chunked
Cache-Control: no-cache
Content-Security-Policy: block-all-mixed-content
Content-Type: text/event-stream
Date: Mon, 14 Sep 2020 21:03:16 GMT
Vary: Origin
X-Accel-Buffering: no
X-Amz-Request-Id: 1634C24B62566062
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  3.2901ms

localhost [REQUEST s3.GetBucketLocation] 21:03:16.653
localhost GET /test/?location=
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=63321a43a6f86bfa07b9ca0e219339210f7a391f75fd01c52cd8bc6902331734
localhost Content-Length: 0
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T210316Z
localhost
localhost [RESPONSE] [21:03:16.653] [ Duration 247µs  ↑ 77 B  ↓ 378 B ]
localhost 200 OK
localhost Accept-Ranges: bytes
localhost Content-Length: 128
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24B626D6A6E
localhost X-Xss-Protection: 1; mode=block
localhost <?xml version="1.0" encoding="UTF-8"?>
<LocationConstraint xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></LocationConstraint>
localhost
localhost [REQUEST s3.HeadBucket] 21:03:16.654
localhost HEAD /test/
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1883fc8222b5bf5d7fb57a26342cabfa9dafef5384452904d249f30398908627
localhost Content-Length: 0
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T210316Z
localhost
localhost [RESPONSE] [21:03:16.654] [ Duration 197µs  ↑ 77 B  ↓ 218 B ]
localhost 200 OK
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24B6280DFAE
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 0
localhost Content-Security-Policy: block-all-mixed-content
localhost
localhost
localhost [REQUEST s3.HeadBucket] 21:03:16.656
localhost HEAD /test/
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1883fc8222b5bf5d7fb57a26342cabfa9dafef5384452904d249f30398908627
localhost Content-Length: 0
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T210316Z
localhost
localhost [RESPONSE] [21:03:16.656] [ Duration 247µs  ↑ 77 B  ↓ 218 B ]
localhost 200 OK
localhost Content-Length: 0
localhost Content-Security-Policy: block-all-mixed-content
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24B6299C2C6
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost
localhost
localhost [REQUEST s3.GetBucketObjectLockConfig] 21:03:16.657
localhost GET /test/?object-lock=
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Content-Length: 0
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T210316Z
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=44c5f92c81ba77c25c42daa35e14c3122d9d96b39e159088b3b222ac50414fcb
localhost
localhost [RESPONSE] [21:03:16.657] [ Duration 189µs  ↑ 77 B  ↓ 583 B ]
localhost 404 Not Found
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24B62ADCA82
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 326
localhost Content-Security-Policy: block-all-mixed-content
localhost <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ObjectLockConfigurationNotFoundError</Code><Message>Object Lock configuration does not exist for this bucket</Message><BucketName>test</BucketName><Resource>/test/</Resource><RequestId>1634C24B62ADCA82</RequestId><HostId>5eddb874-a61c-44b4-8a1e-5c2090179d62</HostId></Error>
localhost
localhost [REQUEST s3.HeadBucket] 21:03:16.658
localhost HEAD /test/
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost X-Amz-Date: 20200914T210316Z
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=1883fc8222b5bf5d7fb57a26342cabfa9dafef5384452904d249f30398908627
localhost Content-Length: 0
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost
localhost [RESPONSE] [21:03:16.658] [ Duration 208µs  ↑ 77 B  ↓ 218 B ]
localhost 200 OK
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 0
localhost Content-Security-Policy: block-all-mixed-content
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24B62C2444E
localhost
localhost
`/home/big` -> `minio/test/big`
localhost [REQUEST s3.PutObject] 21:03:16.852
localhost PUT /test/big
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-09-03T00:08:28Z
localhost X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
localhost X-Amz-Date: 20200914T210316Z
localhost X-Amz-Decoded-Content-Length: 41943040
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=889499de4f3890d7057321af08f34fe90b86956bf5f27a8eb7b81148fb2f9c1d
localhost Content-Length: 42000726
localhost Content-Type: application/octet-stream
localhost <BODY>
localhost [RESPONSE] [21:03:16.852] [ Duration 191.981ms  ↑ 40 MiB  ↓ 259 B ]
localhost 200 OK
localhost X-Amz-Request-Id: 1634C24B62DB88AA
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 0
localhost Content-Security-Policy: block-all-mixed-content
localhost ETag: "ca6508c525b9c58dc7fb6fe0a43707e7"
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost <BODY>
localhost
Total: 0 B, Transferred: 40.00 MiB, Speed: 203.99 MiB/s
localhost [REQUEST s3.HeadObject] 21:03:22.037
localhost HEAD /test/big
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Content-Length: 0
localhost User-Agent: aws-sdk-nodejs/2.751.0 linux/v10.22.0 promise
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T210322Z
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=021f68c98395ac9c8defb837eb544424078c967147e1f127fa7c600dd55722fe
localhost Connection: close
localhost
localhost [RESPONSE] [21:03:22.037] [ Duration 567µs  ↑ 88 B  ↓ 350 B ]
localhost 200 OK
localhost Accept-Ranges: bytes
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/octet-stream
localhost ETag: "ca6508c525b9c58dc7fb6fe0a43707e7"
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Content-Length: 41943040
localhost Last-Modified: Mon, 14 Sep 2020 21:03:16 GMT
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24CA3575016
localhost X-Xss-Protection: 1; mode=block
localhost
localhost
localhost [REQUEST s3.CopyObject] 21:03:22.053
localhost PUT /test/big
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost User-Agent: aws-sdk-nodejs/2.751.0 linux/v10.22.0 promise
localhost X-Amz-Date: 20200914T210322Z
localhost X-Amz-Meta-Id1: Test
localhost X-Amz-Meta-Parentid: none
localhost X-Amz-Meta-Uuid: 4cc9ee05-00be-4cdb-a489-4c90c201ca9e
localhost X-Amz-Metadata-Directive: REPLACE
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-meta-id1;x-amz-meta-parentid;x-amz-meta-uuid;x-amz-metadata-directive, Signature=7859355a1ca9110c1b90c36ae5acb9fc6094c32afa8c374b38a46981ecc74b2b
localhost Connection: close
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Copy-Source: test/big
localhost Content-Length: 0
localhost Content-Type: application/octet-stream
localhost
localhost [RESPONSE] [21:03:22.053] [ Duration 4.59ms  ↑ 195 B  ↓ 523 B ]
localhost 200 OK
localhost ETag: "ca6508c525b9c58dc7fb6fe0a43707e7"
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24CA4051282
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 232
localhost Content-Security-Policy: block-all-mixed-content
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost <?xml version="1.0" encoding="UTF-8"?>
<CopyObjectResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><LastModified>2020-09-14T21:03:16.846Z</LastModified><ETag>&#34;ca6508c525b9c58dc7fb6fe0a43707e7&#34;</ETag></CopyObjectResult>
localhost
localhost [REQUEST s3.HeadObject] 21:03:22.061
localhost HEAD /test/big
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Content-Length: 0
localhost User-Agent: aws-sdk-nodejs/2.751.0 linux/v10.22.0 promise
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Date: 20200914T210322Z
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=021f68c98395ac9c8defb837eb544424078c967147e1f127fa7c600dd55722fe
localhost Connection: close
localhost
localhost [RESPONSE] [21:03:22.061] [ Duration 305µs  ↑ 88 B  ↓ 451 B ]
localhost 200 OK
localhost Accept-Ranges: bytes
localhost Content-Length: 41943040
localhost Content-Security-Policy: block-all-mixed-content
localhost ETag: "ca6508c525b9c58dc7fb6fe0a43707e7"
localhost x-amz-meta-parentid: none
localhost Content-Type: application/octet-stream
localhost Last-Modified: Mon, 14 Sep 2020 21:03:16 GMT
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24CA4CE7276
localhost X-Xss-Protection: 1; mode=block
localhost x-amz-meta-id1: Test
localhost x-amz-meta-uuid: 4cc9ee05-00be-4cdb-a489-4c90c201ca9e
localhost
localhost
localhost [REQUEST s3.CopyObject] 21:03:22.064
localhost PUT /test/big
localhost Proto: HTTP/1.1
localhost Host: localhost:9000
localhost Content-Length: 0
localhost User-Agent: aws-sdk-nodejs/2.751.0 linux/v10.22.0 promise
localhost X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
localhost X-Amz-Copy-Source: test/big
localhost X-Amz-Meta-Id1: Test
localhost X-Amz-Meta-Uuid: 2a4e617f-8233-455f-b51d-265b0f7a4e32
localhost X-Amz-Metadata-Directive: REPLACE
localhost Authorization: AWS4-HMAC-SHA256 Credential=admin/20200914/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-copy-source;x-amz-date;x-amz-meta-id1;x-amz-meta-parentid;x-amz-meta-parentid;x-amz-meta-uuid;x-amz-metadata-directive, Signature=2950cd7f162b1e530180c459ddf4137ed7af960306d7586c5c415f1e21a045f3
localhost Connection: close
localhost Content-Type: application/octet-stream
localhost X-Amz-Date: 20200914T210322Z
localhost X-Amz-Meta-Parentid: none
localhost
localhost [RESPONSE] [21:03:22.064] [ Duration 185µs  ↑ 195 B  ↓ 642 B ]
localhost 403 Forbidden
localhost Content-Type: application/xml
localhost Server: MinIO/RELEASE.2020-09-10T22-02-45Z
localhost Vary: Origin
localhost X-Amz-Request-Id: 1634C24CA4F69F9E
localhost X-Xss-Protection: 1; mode=block
localhost Accept-Ranges: bytes
localhost Content-Length: 385
localhost Content-Security-Policy: block-all-mixed-content
localhost <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><Key>big</Key><BucketName>test</BucketName><Resource>/test/big</Resource><RequestId>1634C24CA4F69F9E</RequestId><HostId>5eddb874-a61c-44b4-8a1e-5c2090179d62</HostId></Error>
localhost
{ SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Request.extractError (/home/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (/home/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  region: null,
  time: 2020-09-14T21:03:22.066Z,
  requestId: '1634C24CA4F69F9E',
  extendedRequestId: undefined,
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 65.42353443435631 }
```

Dockerfile:
```
from minio/minio:RELEASE.2020-09-10T22-02-45Z as minio


from node:10
RUN mkdir /CREDITS
COPY --from=minio /usr/bin/minio /usr/bin/minio
COPY --from=minio /CREDITS/ /CREDITS/
COPY --from=minio /usr/bin/docker-entrypoint.sh /usr/bin/docker-entrypoint.sh

ENV MINIO_ACCESS_KEY=admin
ENV MINIO_SECRET_KEY=admintest
ENV npm_config_loglevel=error

WORKDIR /home
RUN head -c 32k </dev/urandom | base64 - | head -c 32k > small
RUN head -c 40M </dev/urandom | base64 - | head -c 40M > big
RUN npm install aws-sdk
RUN wget -q https://dl.min.io/client/mc/release/linux-amd64/mc
RUN chmod +x mc
RUN mv mc /usr/bin/mc
COPY test.js /home/test.js
COPY startup.sh /home/startup.sh
RUN chmod +x /home/startup.sh

CMD ["/home/startup.sh"]
```

startup.sh:
```
#/bin/sh
mkdir -p /data/test 
/usr/bin/docker-entrypoint.sh minio server /data & 
sleep 5
mc alias set minio http://localhost:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY 
mc admin trace minio --debug -v & 
mc cp /home/big minio/test/
sleep 5
node /home/test.js
```

test.js:
```
const fs = require('fs');
const file = 'big';
const bucket = 'test';
const http = require('http');
const AWS = require("aws-sdk");
const s3Client = new AWS.S3({
    accessKeyId: 'admin',
    secretAccessKey: 'admintest',
    endpoint: 'http://localhost:9000',
    sslEnabled: false,
    s3ForcePathStyle: true,
    httpOptions: {
        agent: new http.Agent({})
    }
});

async function head() {
    const key = file;
    let data = await s3Client.headObject({
        Bucket: bucket,
        Key: key
    }).promise();

    if (!data) {
        console.log('head failed for ' + key + ' with:', err);
        return;
    }
    let orig_meta = data['Metadata'];

    const { v4: uuidv4 } = require('uuid');
    let uuid_var = uuidv4();
    let myArray = { id1: 'Test', uuid: uuid_var, parentID: 'none' };
    let fullArray = Object.assign(orig_meta, myArray);
    await copy(bucket, key, fullArray);
    return;
}

async function copy(bucket, key, metadata) {
    try {
        let data = await s3Client.copyObject({
            Bucket: bucket,
            Key: key,
            CopySource: bucket + '/' + key,
            Metadata: metadata,
            MetadataDirective: 'REPLACE'
        }).promise();

        if (!data) {
            console.log('copy failed for ' + bucket + '/' + key + ' with:', d);
            return;
        }
    } catch (err) {
        console.log(err)
    }
}

async function start(){
    await head()
    await head()
}

start()
```

However if you change `parentID` in test.js to `parentid` it succeeds. Try:
`docker run lallinger/minio-test-meta-lowercase`

## Context

We are using Noobaa to upload files to MinIO (deployed as standalone in an OKD 4.5 cluster) and after every upload we trigger a nodejs function which performs a headObject to retrieve the metadata. To the original metadata we add an id and use copyObject with the replace metadata directive to add this id to the object.

## Your Environment

* Version used (`minio --version`): RELEASE.2020-09-10T22-02-45Z
* Server setup and configuration: OKD 4.5 cluster
* Operating System and version (`uname -a`): Linux minio-5d5bf4bbb4-57p5v 5.6.19-300.fc32.x86_64 #1 SMP Wed Jun 17 16:10:48 UTC 2020 x86_64 Linux

**Comment by harshavardhana** [comment]
@lallinger-arbeit this looks like a bug in AWS SDK, HTTP headers keys are case insensitive.

Most probably the AWS SDK here is calculating the signature without canonicalizing it.

There were similar issues fixed in AWS SDK java in the past. MinIO relies on net/http in Go which always canonicalizes the header key names.

**Comment by harshavardhana** [comment]
I ended up testing this with AWS S3 as well which fails with same error, so we have nothing on our end that needs to be fixed. 

```
 docker run --rm y4m4/minio:test1
Added `minio` successfully.
`/home/big` -> `minio/harshavardhana/big`
Total: 0 B, Transferred: 1.00 MiB, Speed: 624.35 KiB/s
2020-09-22T01:29:27.521Z [DEBUG] logger name: [AWS s3 400 0.133s 0 retries] headBucket({ Bucket: 'harshavardhana' })
2020-09-22T01:29:27.690Z [DEBUG] logger name: [AWS s3 200 0.474s 1 retries] headObject({ Bucket: 'harshavardhana', Key: 'big' })
2020-09-22T01:29:27.947Z [DEBUG] logger name: [AWS s3 200 0.241s 0 retries] copyObject({ Bucket: 'harshavardhana',
  Key: 'big',
  CopySource: 'harshavardhana/big',
  Metadata:
   { id1: 'Test',
     uuid: '0441e5d7-341f-40fd-946e-1c4c084bb2c9',
     parentId: 'none' },
  MetadataDirective: 'REPLACE' })
2020-09-22T01:29:28.100Z [DEBUG] logger name: [AWS s3 200 0.151s 0 retries] headObject({ Bucket: 'harshavardhana', Key: 'big' })
2020-09-22T01:29:28.255Z [DEBUG] logger name: [AWS s3 403 0.153s 0 retries] copyObject({ Bucket: 'harshavardhana',
  Key: 'big',
  CopySource: 'harshavardhana/big',
  Metadata:
   { uuid: 'fdd28af0-be42-4f22-8c96-306f0891afd5',
     id1: 'Test',
     parentid: 'none',
     parentId: 'none' },
  MetadataDirective: 'REPLACE' })
{ SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
    at Request.extractError (/home/node_modules/aws-sdk/lib/services/s3.js:837:35)
    at Request.callListeners (/home/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/home/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/home/node_modules/aws-sdk/lib/request.js:688:14)
    at Request.transition (/home/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/node_modules/aws-sdk/lib/request.js:690:12)
    at Request.callListeners (/home/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
  message:
   'The request signature we calculated does not match the signature you provided. Check your key and signing method.',
  code: 'SignatureDoesNotMatch',
  region: null,
  time: 2020-09-22T01:29:28.253Z,
  requestId: 'C64B74CA5C7CC3D1',
  extendedRequestId:
   'x5NsRZnKRIwr8vFdUGIdwRjtkRTqMm3i3F8YI+3+5OxbFB9yI4L0QAOkuIfEp92IPXoyJH15JxE=',
  cfId: undefined,
  statusCode: 403,
  retryable: false,
  retryDelay: 14.232053800100775 }
```

The bug should be reported to aws-sdk-js @lallinger-arbeit
