### ISSUE TITLE
Certificate not valid for <bucket>.play.minio.io

### ISSUE THREAD

**Issue by fwessels** [minio/minio#1049]
Running program below reports an error for invalid certificate:

```
panic: RequestError: send request failed
caused by: Get https://frank.play.minio.io:9000/: x509: certificate is valid for *.minio.io, minio.io, not frank.play.minio.io

goroutine 1 [running]:
main.(*Client).List(0xc820086690)
    /Users/frankw/golang/src/github.com/fwessels/minio-cp-test/minio-ls-test.go:39 +0x493
```

Running as HTTP gives a 'malformed HTTP response':

```
panic: RequestError: send request failed
caused by: Get http://frank.play.minio.io:9000/: malformed HTTP response "\x15\x03\x01\x00\x02\x02"

goroutine 1 [running]:
main.(*Client).List(0xc820086690)
    /Users/frankw/golang/src/github.com/fwessels/minio-cp-test/minio-cp-test.go:39 +0x493
```

(I also had to add 'frank.play.minio.io' to local hosts)

Test program:

```
package main

import (
    "fmt"
    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/s3"
    "github.com/aws/aws-sdk-go/aws/credentials"
)

type Client struct {
    Bucket     string
    Endpoint   string
    Region     string
    AccessKey  string
    SecretKey  string
}

func (c *Client) getAwsConfig() *aws.Config {
    return &aws.Config{
        Credentials: credentials.NewStaticCredentials(c.AccessKey, c.SecretKey, ""),
        Endpoint: aws.String(c.Endpoint),
        Region: aws.String(c.Region)}
}

func (c *Client) List() {

    client := s3.New(session.New(), c.getAwsConfig())
    params := &s3.ListObjectsInput{Bucket: &c.Bucket}
    err := client.ListObjectsPages(params, func(page *s3.ListObjectsOutput, more bool) bool {
        for _, obj := range page.Contents {
            fmt.Println(*obj.Key)
        }

        return true
    })

    if err != nil {
        panic(err)
    }
}

func main() {

    clnt := &Client{Bucket: "frank", Endpoint: "https://play.minio.io:9000", Region: "us-east-1", AccessKey: "PLAY", SecretKey: "SECRET"}

    clnt.List()
}
```

**Comment by harshavardhana** [comment]
Certificate is valid its just that we do not support virtual style for buckets like Amazon S3, you have to use PathStyle to make requests to play.minio.io

```
newSession := session.New()
    s3Config := &aws.Config{
        Credentials: credentials.NewStaticCredentials("<YOUR-ACCESS-KEY-ID>", "<YOUR-SECRET-ACCESS-KEY", ""),
        Endpoint:         aws.String("https://play.minio.io:9000"),
        Region:           aws.String("us-east-1"),
        S3ForcePathStyle: aws.Bool(true),
    }
```

**Comment by fwessels** [comment]
Verified, works accordingly.
