### ISSUE TITLE
s3 gateway panic on github.com/minio/minio/cmd/http/dial_dnscache.go:60

### ISSUE THREAD

**Issue by dpgarrick** [minio/minio#10705]
## Expected Behavior

minio runs without panic
## Current Behavior

I updated minio to latest, and now minio exits with panic:

```
Oct 19 15:50:01 hurricane minio[4204]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 19 15:50:01 hurricane minio[4204]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x947195]
Oct 19 15:50:01 hurricane minio[4204]: goroutine 77 [running]:
Oct 19 15:50:01 hurricane minio[4204]: github.com/minio/minio/cmd/http.DialContextWithDNSCache.func1(0x20e4c20, 0xc00003e068, 0x1da9d22, 0x3, 0xc000b2f660, 0x12, 0x0, 0x0, 0x0, 0x0)
Oct 19 15:50:01 hurricane minio[4204]:         github.com/minio/minio/cmd/http/dial_dnscache.go:60 +0xd5
Oct 19 15:50:01 hurricane minio[4204]: net/http.(*Transport).dial(0xc00050c000, 0x20e4c20, 0xc00003e068, 0x1da9d22, 0x3, 0xc000b2f660, 0x12, 0x0, 0xc000790460, 0x0, ...)
Oct 19 15:50:01 hurricane minio[4204]:         net/http/transport.go:1141 +0x1fd
Oct 19 15:50:01 hurricane minio[4204]: net/http.(*Transport).dialConn(0xc00050c000, 0x20e4c20, 0xc00003e068, 0x0, 0xc0002d3c20, 0x4, 0xc000b2f660, 0x12, 0x0, 0xc00062b9e0, ...)
Oct 19 15:50:01 hurricane minio[4204]:         net/http/transport.go:1575 +0x1abb
Oct 19 15:50:01 hurricane minio[4204]: net/http.(*Transport).dialConnFor(0xc00050c000, 0xc001023b80)
Oct 19 15:50:01 hurricane minio[4204]:         net/http/transport.go:1421 +0xc6
Oct 19 15:50:01 hurricane minio[4204]: created by net/http.(*Transport).queueForDial
Oct 19 15:50:01 hurricane minio[4204]:         net/http/transport.go:1390 +0x40f
```

## Steps to Reproduce (for bugs)

A basic s3 gateway deployment running on local port 9001 via the following command

```
minio gateway s3 --address :9001
```

With the following ENVs set
```
MINIO_CACHE="on"
MINIO_CACHE_DRIVES="/minio/cache"
MINIO_CACHE_EXCLUDE="mybucket/*"
MINIO_CACHE_QUOTA=80
MINIO_CACHE_AFTER=0
MINIO_CACHE_WATERMARK_LOW=70
MINIO_CACHE_WATERMARK_HIGH=90
```

## Context

I have had this s3 gateway running for months behind a proxy using Caddy without issue. Now I cannot start the gateway.

## Regression

Seems to be related to these changes https://github.com/minio/minio/pull/10693

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

```
minio version RELEASE.2020-10-18T21-54-12Z
Linux hurricane 5.3.0-53-generic #47~18.04.1-Ubuntu SMP Thu May 7 13:10:50 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
Good catch fixing @dpgarrick
