### ISSUE TITLE
spark.write failing for minio Docker container until homebrew install (FileAlreadyExistsException: path is a file)

### ISSUE THREAD

**Issue by kwhickey** [minio/minio#10744]
## Expected Behavior

Data in a Spark `DataFrame` should be writable as a csv file to a minio bucket via `s3a://` URI when running minio as a docker container, and its backing data store is a docker volume.

```
df.write.csv("s3a://data/output")
```

- bucket `data` exists in minio, 
- hadoop/spark configuration is as described in https://docs.min.io/docs/disaggregated-spark-and-hadoop-hive-with-minio.html

## Current Behavior

Spark cannot write to the local bucket and errors with:
```
org.apache.hadoop.fs.FileAlreadyExistsException: Path is a file: s3a://data/output/_temporary/0
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerMkdirs(S3AFileSystem.java:1512)
```

My suspicion was that somehow the way that docker mounts the underlying volume as files on disk causes minio to think the data written under the bucket (in temp dirs here) is a file rather than a directory.

NOTE: I simplified and tried to reproduce the results in https://github.com/minio/minio/issues/7020, running against the same dockerized minio, and got a similar error:
```
SPARK_LOCAL_IP=127.0.0.1 AWS_ACCESS_KEY=minio AWS_SECRET_KEY=minio123 pyspark --conf spark.hadoop.fs.s3a.endpoint=http://localhost:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.committer.name=directory --conf spark.hadoop.fs.s3a.committer.staging.tmp.path=/tmp/staging --conf spark.hadoop.mapreduce.reduce.speculative=false --jars "spark/jars/hadoop-aws-2.8.5.jar,spark/jars/httpclient-4.5.3.jar,spark/jars/aws-java-sdk-core-1.11.234.jar,spark/jars/aws-java-sdk-kms-1.11.234.jar,spark/jars/aws-java-sdk-1.11.234.jar,spark/jars/aws-java-sdk-s3-1.11.234.jar,spark/jars/joda-time-2.9.9.jar"

Python 2.7.16 (default, Jun  5 2020, 22:59:21) 
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc- on darwin

Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.4.5
      /_/

Using Python version 2.7.16 (default, Jun  5 2020 22:59:21)
SparkSession available as 'spark'.
>>> df1 = spark.createDataFrame([('john', 33)], ('name', 'age'))
>>> df1.write.json('s3a://vadmeste/test_1')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/spark/python/pyspark/sql/readwriter.py", line 817, in json
    self._jwrite.json(path)
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: u'path s3a://vadmeste/test_1 already exists.;'
```

**HOWEVER**

To test this theory about docker being the cause of the problem, I then tried to install minio using `brew install minio/stable/minio`. Results:

1. The #7020 scenario worked on undockerized minio
2. The #7020 scenario **started working** in dockerized minio (same docker volume mounted as before)
3. The pyspark script I had writing a DataFrame to CSV **started working** in dockerized minio also (same docker volume mounted as before)

_So the question I have really is: **Is the homebrew install of minio on Mac somehow able to resolve or rectify known issues with the dockerized version?**_
- _is there perhaps a global or user configuration file that gets updated with the homebrew install?_
- _if it did fix or change anything, what was it?_

Full stack trace from pyspark script below:
```
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.path.style.access=true
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.access.key=minio
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.max.total.tasks=5
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.multiobjectdelete.enable=true
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.multipart.purge=false
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.connection.establish.timeout=5000
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.multipart.purge.age=86400
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.threads.max=10
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.threads.keepalivetime=60
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.multipart.threshold=2147483647
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.buffer.dir=${hadoop.tmp.dir}/s3a
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.fast.upload.active.blocks=4
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.block.size=32M
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.fast.upload=false
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.connection.maximum=15
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.paging.maximum=5000
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.readahead.range=64K
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.attempts.maximum=20
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.multipart.size=100M
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.socket.recv.buffer=8192
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.connection.ssl.enabled=false
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.secret.key=minio123
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.fast.upload.buffer=disk
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.connection.timeout=200000
20/10/21 06:25:41 INFO log_hadoop_config: fs.AbstractFileSystem.s3a.impl=org.apache.hadoop.fs.s3a.S3A
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.socket.send.buffer=8192
20/10/21 06:25:41 INFO log_hadoop_config: fs.s3a.endpoint=localhost:9000
20/10/21 06:25:43 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 1
20/10/21 06:25:43 INFO output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
20/10/21 06:25:43 INFO datasources.SQLHadoopMapReduceCommitProtocol: Using output committer class org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter
Traceback (most recent call last):
  File "/Users/.../write_to_s3.py", line 102, in <module>
    main()
  File "/Users/.../write_to_s3.py", line 96, in main
    f"s3a://data/output/"
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 932, in csv
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/usr/local/spark/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
  File "/usr/local/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o976.csv.
: org.apache.hadoop.fs.FileAlreadyExistsException: Path is a file: s3a://data/output/_temporary/0
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerMkdirs(S3AFileSystem.java:1512)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:1482)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:1914)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.setupJob(FileOutputCommitter.java:343)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupJob(HadoopMapReduceCommitProtocol.scala:162)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:139)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:159)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at org.apache.spark.sql.DataFrameWriter.csv(DataFrameWriter.scala:664)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)

20/10/21 06:25:43 INFO spark.SparkContext: Invoking stop() from shutdown hook
```

## Possible Solution

- Clarify any system-level config that may need to exist or be changed in order for writes to minio in docker to work.
- Test the behavior of #7020 on a clean system (without ever installing minio) where the minio server is run out of docker

## Steps to Reproduce (for bugs)

1. Fresh Mac Catalina environment, where minio has not yet been installed on mac (e.g. via homebrew)
2. run `docker-compose up` using the docker-compose.yml snippet from the **Server setup and configuration** section below
3. create a `data` bucket in minio via GUI at http://localhost:9000
4. run pyspark program copied below, setting all config values from https://docs.min.io/docs/disaggregated-spark-and-hadoop-hive-with-minio.html that are not already the default (seen in pyspark program below)

`write_to_s3.py`
```python
import sys
import uuid
import random

from pyspark.sql import SparkSession, Row
from pyspark import SparkConf


def main():
    conf = SparkConf()
    conf.set("spark.yarn.maxAppAttempts", "1")
    conf.set("spark.hadoop.fs.s3a.endpoint", "localhost:9000")
    conf.set("spark.hadoop.fs.s3a.access.key", "minio")
    conf.set("spark.hadoop.fs.s3a.secret.key", "minio123")
    conf.set("spark.hadoop.fs.s3a.connection.ssl.enabled", "false")
    # "Enable S3 path style access ie disabling the default virtual hosting behaviour.
    # Useful for S3A-compliant storage providers as it removes the need to set up DNS for virtual hosting."
    conf.set("spark.hadoop.fs.s3a.path.style.access", "true")
    # Set Committer config compliant with MinIO
    conf.set("spark.hadoop.fs.s3a.committer.name", "directory")
    conf.set("spark.hadoop.fs.s3a.committer.staging.conflict-mode", "replace")
    conf.set("spark.hadoop.fs.s3a.committer.staging.tmp.path", "/tmp/staging")

    spark = SparkSession.builder.appName("Dockerized Minio Spark Test").config(conf=conf).getOrCreate()

    data = [
        {"first_col": "row 1", "id": str(uuid.uuid4()), "color": "blue", "numeric_val": random.randint(-100, 100)},
        {"first_col": "row 2", "id": str(uuid.uuid4()), "color": "green", "numeric_val": random.randint(-100, 100)},
        {"first_col": "row 3", "id": str(uuid.uuid4()), "color": "pink", "numeric_val": random.randint(-100, 100)},
        {"first_col": "row 4", "id": str(uuid.uuid4()), "color": "yellow", "numeric_val": random.randint(-100, 100)},
        {"first_col": "row 5", "id": str(uuid.uuid4()), "color": "red", "numeric_val": random.randint(-100, 100)},
        {"first_col": "row 6", "id": str(uuid.uuid4()), "color": "orange", "numeric_val": random.randint(-100, 100)},
        {"first_col": "row 7", "id": str(uuid.uuid4()), "color": "magenta", "numeric_val": random.randint(-100, 100)},
    ]

    df = spark.createDataFrame([Row(**data_row) for data_row in data])
    df.write.csv(f"s3a://data/output/")

    spark.stop()


if __name__ == "__main__":
    main()

```

## Context

_I want a docker-based setup to be a reliable way for our dev team to use minio as a substitute for s3 in a local spark dev env, but don't want it to be **accidental success**_

## Regression

Not sure.

### Version used (`minio --version`):
Docker minio image: `docker images | grep minio`: `minio/minio RELEASE.2020-10-03T02-19-42Z 17bc01922d1b`

Homebrew minio:
```
〉brew info minio                
minio: stable 20201003021942 (bottled), HEAD
High Performance, Kubernetes Native Object Storage
https://min.io
/usr/local/Cellar/minio/RELEASE.2020-10-18T21-54-12Z_1 (3 files, 50.4MB) *
  Built from source on 2020-10-22 at 21:08:25
/usr/local/Cellar/minio/20200428235656 (7 files, 68.4MB)
  Poured from bottle on 2020-06-20 at 09:50:02
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/minio.rb
License: Apache-2.0
```
### Server setup and configuration: 
Minio run out of `docker-compose` using the config below, which exposes a server to the Spark program running on localhost at `http://localhost:9000`.

- Docker version 19.03.12, build 48a66213fe
- docker-compose version 1.26.2, build eefe0d31

```
  minio:
    image: minio/minio
    volumes:
      - type: bind
        source: ${MINIO_DATA_DIR:-../data/s3}
        target: /data
    ports:
      - ${MINIO_PORT:-9000}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${MINIO_HOST:-localhost}:${MINIO_PORT:-9000}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
```

Later, minio homebrew run with
`MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio server data`
(from a different directory than where the pyspark script was run or the minio docker volume was mounted)

PySpark script running on localhost with:

```
SPARK_LOCAL_IP=127.0.0.1 spark-submit --packages org.apache.hadoop:hadoop-aws:2.8.5,com.amazonaws:aws-java-sdk:1.11.759 write_to_s3.py
```

Spark 2.4.5
Hadoop 2.8.5
Python 3.6.10

### Operating System and version (`uname -a`): 
`Darwin C02CJ0AMMD6V.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`

**Comment by vadmeste** [comment]
Hey @kwhickey. Thanks for reporting this. 

I didn't try your steps yet but could you test an erasure coding server ? 

To activate the erasure coding in your docker-compose, just pass 4 arguments to command option:
```
command: server /data/disk{1...4}
```

Make sure you have the latest MinIO image as well.

**Comment by kwhickey** [comment]
----
_**[UPDATE 2: Upgrading Docker for Mac may have had more to do with this. Read more below.]**_

----
~~_**`[UPDATE BELOW: Changing volume type to `volume` seems necessary for "erasure" disk]**_~~

----

The minio docker container exits immediately (after creating `disk1` .. `disk4` folders in the mounted `data/s3/` host folder) with:

```
ERROR Unable to initialize backend: Unable to write to the backend
> Please ensure your disk supports O_DIRECT
HINT:
Disks do not support O_DIRECT flags, MinIO erasure coding requires filesystems with O_DIRECT support
```

Tried this with the same failure on:
- `minio/minio:edge (a30c0469e8bc)`
- `minio/minio:RELEASE.2020-10-28T08-16-50Z (51f319bbcc47)`

I am running on `macOS Catalina version 10.15.7`.
Docker version `Docker version 19.03.12, build 48a66213fe`
Docker Compose version `docker-compose version 1.26.2, build eefe0d31`

**Comment by harshavardhana** [comment]
> The minio docker container exits immediately (after creating `disk1` .. `disk4` folders in the mounted `data/s3/` host folder) with:
> 
> ```
> ERROR Unable to initialize backend: Unable to write to the backend
> > Please ensure your disk supports O_DIRECT
> HINT:
> Disks do not support O_DIRECT flags, MinIO erasure coding requires filesystems with O_DIRECT support
> ```
> 
> Tried this with the same failure on:
> 
> * `minio/minio:edge (a30c0469e8bc)`
> * `minio/minio:RELEASE.2020-10-28T08-16-50Z (51f319bbcc47)`
> 
> I am running on `macOS Catalina version 10.15.7`.
> Docker version `Docker version 19.03.12, build 48a66213fe`
> Docker Compose version `docker-compose version 1.26.2, build eefe0d31`

This is not related to this bug, the issue you have is your backend doesn't support O_DIRECT which is necessary for erasure coded setup. 

Docker on macOS uses a dumb filesystem with no real persistent guarantees. You should use Linux or don't use erasure coding on macOS through docker just use it on the host OS.

**Comment by kwhickey** [comment]
@harshavardhana ok, I concur, this filesystem problem doesn't seem to be related to the issue I originally brought up. I was only attempting the erasure setup because asked. Let's forget about that then and revisit the original issue.

**Comment by kwhickey** [comment]
So I can recreate the problem again by removing the brew-installed minio binary from mac (see steps below).

_**But now I can't recreate the (accidental) "solution"**_
What worked before (running the same test in undockerized minio running at localhost:9000) doesn't seem to "fix" the docker setup anymore. I can't recreate whatever steps in running or debugging the minio server or using `mc` may have "fixed" docker. 

1. Remove Mac minio binary: `brew uninstall minio/stable/minio`
2. Remove docker minio images: `docker rmi $(docker images minio/minio -aq)`
3. Pull latest minio docker image: `docker pull minio/minio:latest`
4. Run dockerized minio `docker-compose up -d`
5. Make a `vadmeste` bucket: `mc alias set local http://localhost:9000 minio minio123` and then `mc mb local/vadmeste`
6. Run #7020 example: 
    ```
    SPARK_LOCAL_IP=127.0.0.1 AWS_ACCESS_KEY=minio AWS_SECRET_KEY=minio123 pyspark --conf spark.hadoop.fs.s3a.endpoint=http://localhost:9000 --conf spark.hadoop.fs.s3a.path.style.access=true --conf spark.hadoop.fs.s3a.committer.name=directory --conf spark.hadoop.fs.s3a.committer.staging.tmp.path=/tmp/staging --conf spark.hadoop.mapreduce.reduce.speculative=false --jars "spark/jars/hadoop-aws-2.8.5.jar,spark/jars/httpclient-4.5.3.jar,spark/jars/aws-java-sdk-core-1.11.234.jar,spark/jars/aws-java-sdk-kms-1.11.234.jar,spark/jars/aws-java-sdk-1.11.234.jar,spark/jars/aws-java-sdk-s3-1.11.234.jar,spark/jars/joda-time-2.9.9.jar"
    ```
7. `>>> df1 = spark.createDataFrame([('john', 33)], ('name', 'age'))`
8. `>>> df1.write.json('s3a://vadmeste/test_1')`
9. ERROR (below)
10. Shut down docker: `docker-compose down`
11. Remove and remake host `../data` and `../data/s3/` directories for a clean slate: `rm -rf ../data && mkdir -p ../data/s3/`
12. Install Mac minio binary using homebrew: `brew install minio/stable/minio`
13. Run minio server on Mac localhost:9000: `MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio server ../data/s3/`
13. Repeat step 5, 6, 7, 8
14. ERROR (below)


Writing a Spark `DataFrame` object to `s3a://` backed by minio running in Docker or on macOS consistently fails for #7020 and the `write_to_s3.py` program with the below error:

```
org.apache.spark.sql.AnalysisException: path s3a://vadmeste/test_1 already exists.;
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:114)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult$lzycompute(commands.scala:104)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.sideEffectResult(commands.scala:102)
	at org.apache.spark.sql.execution.command.DataWritingCommandExec.doExecute(commands.scala:122)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:131)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:155)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:152)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:127)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:83)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:81)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter$$anonfun$runCommand$1.apply(DataFrameWriter.scala:676)
	at org.apache.spark.sql.execution.SQLExecution$$anonfun$withNewExecutionId$1.apply(SQLExecution.scala:80)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:127)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:75)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:676)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at org.apache.spark.sql.DataFrameWriter.json(DataFrameWriter.scala:545)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kwhickey** [comment]
@harshavardhana or @vadmeste were you able to recreate this problem with the simple 2-line #7020 pyspark code or the script I provided above? 

If you all are able to show it works for you, I can wipe my environment and try different setups to try to narrow down what it is on my machine that is interfering.

**Comment by kwhickey** [comment]
_**Small update re: an "erasure coding server".**_

----
_**[UPDATE: Upgrading Docker for Mac may have had more to do with this working than the mount type. Read more below.]**_

----

If I change the Docker Volume type to `volume` rather than `bind`, the erasure approach works. I think this is because with `volume` type docker is using the Linux VM running on the mac for disk operations, rather than pushing them out to the Mac host.

Still ... same errors running the pyspark jobs, even on this "erasure" dockerized setup. 

`docker-compose.yaml` change:
```
version: '3.7'

services:
  minio:
    image: minio/minio
    volumes:
      - type: volume
        source: local_s3_storage
        target: /data
    ports:
      - ${MINIO_PORT:-9000}:9000
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
    command: server /data/disk{1...4}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${MINIO_HOST:-localhost}:${MINIO_PORT:-9000}/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
volumes:
  local_s3_storage:
```

Output:

```
〉docker-compose up
Creating network "minio_default" with the default driver
Creating volume "minio_local_s3_storage" with default driver
Creating minio_minio_1 ... done
Attaching to minio_minio_1
minio_1  | Formatting 1st zone, 1 set(s), 4 drives per set.
minio_1  | WARNING: Host local has more than 2 drives of set. A host failure will result in data becoming unavailable.
minio_1  | Attempting encryption of all config, IAM users and policies on MinIO backend
minio_1  | Status:         4 Online, 0 Offline. 
minio_1  | Endpoint:  http://172.21.0.2:9000  http://127.0.0.1:9000
minio_1  | 
minio_1  | Browser Access:
minio_1  |    http://172.21.0.2:9000  http://127.0.0.1:9000
minio_1  | 
minio_1  | Object API (Amazon S3 compatible):
minio_1  |    Go:         https://docs.min.io/docs/golang-client-quickstart-guide
minio_1  |    Java:       https://docs.min.io/docs/java-client-quickstart-guide
minio_1  |    Python:     https://docs.min.io/docs/python-client-quickstart-guide
minio_1  |    JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
minio_1  |    .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

**Comment by kwhickey** [comment]
Not sure what changed in my env, but everything just started working. 

The _only_ thing I can think may have played a factor is that I upgraded Docker for Mac. (old engine `19.03.12`, new listed below).

- It's possibly related to https://github.com/docker/for-mac/issues/4943 which mentioned stale cache entries leading to `file exists` errors on `mkdir`

That also means that the previous comment about using a `volume` type mount rather than a `bind` mount to make the erasure disk work may not have been necessary. The erasure disk setup worked when testing the bind mount again too. 

**Working setup:**
1. **Spark**: `2.4.5` and `pyspark==2.4.5` from pypi
2. **Hadoop**: `2.8.5`
3. **aws-java-sdk** JAR and dependent JARs: `1.11.759` or `1.11.234` (both worked)
4. **minio binary for Mac**: _Not installed_
5. **minio docker image**: `minio/minio:latest` (RepoDigest: `556b51c1c835`)
6. **Docker**: Docker Desktop Community (for Mac) `2.5.0.0 (49427) - stable`. Engine: `Docker version 19.03.13, build 4484c46d9d`
7. **Docker Compose**: `docker-compose version 1.27.4, build 40524192`
8. **Python**: `3.6.10`

If it _stops_ working again and I can pinpoint why, I'll reply back.

**Comment by klauspost** [comment]
Closing for now.
