### ISSUE TITLE
[fs] Multipart upload fails for large files

### ISSUE THREAD

**Issue by Druckles** [minio/minio#10785]
We have a process that downloads a .zip file, unpacks it and then re-uploads it over MinIO using the AWS SDK Transfer Manager. We wrap the created Transfer in a progress listener which in turn sets a Promise/Future it's finished (to prevent blocking). That all looks more or less like this:

```
var downloadedZipFile = createTempFile("...");
var download = s3TransferManager.download("bucket", "myzip.zip", downloadedZipFile);
return S3TransferFuture.from(download)
    .flatMap(v -> {
        process(downloadedZipFile, unpackedDirectory);
        return S3TransferFuture.from(s3TransferManager.uploadDirectory("bucket", "myzip", unpackedDirectory, true));
    });
```

However, when uploading a larger file (440 MB), the upload fails near the end with the following error message:

> com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 164192A79B98EE3C; S3 Extended Request ID: c54b6718-d7ab-4314-913d-c1e1a767add8), S3 Extended Request ID: c54b6718-d7ab-4314-913d-c1e1a767add8

The Upload works with smaller files and only fails sometimes (~1/3 - 1/2 the time). We've had no problems with Amazon S3.

It seems (yet to confirm), that the files were actually uploaded, despite the error and exist in the repository already.

## Example logs

Here is an example recorded over three different logs:

1. MinIO trace log (`mc admin trace`)
2. Tomcat
3. Transfer progress listener

At 15:56:20 (UTC+1), a 503 appears in (1):

> 14:56:20.737 [503 Service Unavailable] s3.CompleteMultipartUpload [name]:9000/bucket/root/79/1bb850c4-39ff-4a66-be55-97920b8fac01/[filename]?uploadId=035fff62-17ef-487e-a7a4-fbd1c6346d7e  10.9.58.35        7.461423s    ↑ 7.1 KiB ↓ 775 B

_Names have been removed._

The Upload doesn't seem to suffer, however, and there are two `CLIENT_REQUEST_RETRY_EVENT`s in (3) over the next five minutes:

* 15:56:25,702
* 15:56:30,736

Then a few milliseconds later there's the 404 in (1) which seems to cause it to fail:

> 14:56:30.888 [404 Not Found] s3.CompleteMultipartUpload [name]:9000/bucket/root/79/1bb850c4-39ff-4a66-be55-97920b8fac01/[filename]?uploadId=035fff62-17ef-487e-a7a4-fbd1c6346d7e  10.9.58.35        1.027ms      ↑ 7.1 KiB ↓ 760 B

Then there are three events in (3):

* 15:56:30,890 CLIENT_REQUEST_FAILED_EVENT
* 15:56:30,891 TRANSFER_FAILED_EVENT
* 15:56:30,891 TRANSFER_FAILED_EVENT

and the error is logged out in Tomcat (2):

> com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 164192A79B98EE3C; S3 Extended Request ID: c54b6718-d7ab-4314-913d-c1e1a767add8), S3 Extended Request ID: c54b6718-d7ab-4314-913d-c1e1a767add8

### MinIO Error logs

There were no errors for the above Upload found in the log. The only errors present are `file not found` and they don't correspond to uploads. E.g.

```
Error: file not found
uploadID=158f064c-efe4-4958-b315-74590c393c76
uploadIDDir=D:\[path]\[to]\[repo]/.minio.sys/multipart/be742c2a5922f592ca42b2251f3e59b75f3b6eb398c278a118aefcd2c87c85db/158f064c-efe4-4958-b315-74590c393c76
       1: cmd\fs-v1-multipart.go:93:cmd.(*FSObjects).backgroundAppend()
```

## Steps to Reproduce (for bugs)

No, not really.

The customer can reproduce it relatively regularly. We haven't managed to reproduce it locally and we have never encountered a problem with Amazon S3. My guess would therefore be that it's a race condition happening.

## Context

The customer can't upload large files. Retrying isn't much of an option for them. Although the processing only takes a maximum of ~3 minutes including download & re-upload (usually much less), the initial upload (using a presigned-URL) takes >15 minutes. And although they can upload smaller files, such file sizes are not uncommon.

## Your Environment

* Windows Server 2012 R2
* MinIO 2020.06.22 (we also tested with a newer version downloaded on 14.10, I assume: 2020-10-12).
* `aws-java-sdk-s3-.1.11.710` (updating didn't help)
* Tomcat 9.0.37
* Java OpenJDK 11.0.8-1
* Tomcat and MinIO are both running behind an SSL-secured Apache Server reverse proxy although Tomcat speaks directly to MinIO using its domain name: http://xyz:9000.

**Comment by kannappanr** [comment]
@Druckles Can you please provide code to reproduce the issue?

**Comment by Druckles** [comment]
Sadly not. As described above, this only occurs in one environment and we cannot reproduce it locally. It also doesn't always happen reliably. Which is why we believe it's a race condition.

Is there anything else that can be done to help analyse this problem? At the moment all the information we can get from MinIO is described above.

**Comment by harshavardhana** [comment]
> Sadly not. As described above, this only occurs in one environment and we cannot reproduce it locally. It also doesn't always happen reliably. Which is why we believe it's a race condition.
> 
> Is there anything else that can be done to help analyse this problem? At the moment all the information we can get from MinIO is described above.

Please try with the latest release and let us know @Druckles

**Comment by Druckles** [comment]
RELEASE.2020-11-25T22-36-25Z? Will do. It may take a few days for the customer to have tested it on their system. And thank you :-)

**Comment by mfzarko** [comment]
We have observed the same in Presto. We can replicate this consistently.
On AWS S3 it  finishes sucessfully
Unforunately this still happens on `RELEASE.2020-11-25T22-36-25Z`

Steps to replicate:
1. Get and unpack the docker setup 
[minio-multipart-bug.zip](https://github.com/minio/minio/files/5629481/minio-multipart-bug.zip)
2. Get [Presto CLI](https://repo1.maven.org/maven2/io/prestosql/presto-cli/347/presto-cli-347-executable.jar) 
3. Start container and give it 3 mins to spin up.
`docker-compose up -d`
4. Try creating a CSV table on minio using TPCH data.
`./presto-cli-347-executable.jar -f _test_multipart.sql --progress`

This will try creating 60M row table (couple GB).
After processing all data, it will fail with following stacktrace.

```
io.prestosql.spi.PrestoException: Error committing write to Hive
	at io.prestosql.plugin.hive.RecordFileWriter.commit(RecordFileWriter.java:191)
	at io.prestosql.plugin.hive.HiveWriter.commit(HiveWriter.java:86)
	at io.prestosql.plugin.hive.HivePageSink.doFinish(HivePageSink.java:190)
	at io.prestosql.plugin.hive.authentication.NoHdfsAuthentication.doAs(NoHdfsAuthentication.java:23)
	at io.prestosql.plugin.hive.HdfsEnvironment.doAs(HdfsEnvironment.java:96)
	at io.prestosql.plugin.hive.HivePageSink.finish(HivePageSink.java:181)
	at io.prestosql.plugin.base.classloader.ClassLoaderSafeConnectorPageSink.finish(ClassLoaderSafeConnectorPageSink.java:77)
	at io.prestosql.operator.TableWriterOperator.finish(TableWriterOperator.java:208)
	at io.prestosql.operator.Driver.processInternal(Driver.java:397)
	at io.prestosql.operator.Driver.lambda$processFor$8(Driver.java:283)
	at io.prestosql.operator.Driver.tryWithLock(Driver.java:675)
	at io.prestosql.operator.Driver.processFor(Driver.java:276)
	at io.prestosql.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:1076)
	at io.prestosql.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:163)
	at io.prestosql.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:484)
	at io.prestosql.$gen.Presto_346_e____20201201_140349_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 164C9D914682F799; S3 Extended Request ID: 663ae88d-ea6d-4c1b-a0a5-cd8652100e0f), S3 Extended Request ID: 663ae88d-ea6d-4c1b-a0a5-cd8652100e0f
	at io.prestosql.plugin.hive.s3.PrestoS3FileSystem$PrestoS3OutputStream.uploadObject(PrestoS3FileSystem.java:1368)
	at io.prestosql.plugin.hive.s3.PrestoS3FileSystem$PrestoS3OutputStream.close(PrestoS3FileSystem.java:1314)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at org.apache.hadoop.fs.FSDataOutputStream$PositionCache.close(FSDataOutputStream.java:72)
	at org.apache.hadoop.fs.FSDataOutputStream.close(FSDataOutputStream.java:101)
	at org.apache.hadoop.io.compress.CompressionOutputStream.close(CompressionOutputStream.java:63)
	at org.apache.hadoop.io.compress.CompressorStream.close(CompressorStream.java:106)
	at io.prestosql.plugin.hive.util.TextRecordWriter.close(TextRecordWriter.java:74)
	at io.prestosql.plugin.hive.RecordFileWriter.commit(RecordFileWriter.java:187)
	... 18 more
Caused by: com.amazonaws.services.s3.model.AmazonS3Exception: The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchUpload; Request ID: 164C9D914682F799; S3 Extended Request ID: 663ae88d-ea6d-4c1b-a0a5-cd8652100e0f)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1799)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1383)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1359)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1139)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:796)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5054)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5000)
	at com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3483)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.call(CompleteMultipartUpload.java:92)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartUpload.call(CompleteMultipartUpload.java:38)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

You should be able to get what is necessary from minino container afterwards.

**Comment by harshavardhana** [comment]
@mfzarko used the latest release and do not see this problem

```
~ ./presto-cli-347-executable.jar -f _test_multipart.sql --progress
CREATE TABLE: 59986052 rows_u5gxk [RUNNING] i[60M 0B 0B] o[60M 0B 0B] splits[0/18/20]/3]

Query 20201210_012059_00000_u5gxk, FINISHED, 1 node
Splits: 38 total, 38 done (100.00%)
18:05 [60M rows, 0B] [55.3K rows/s, 0B/s]

```

**Comment by harshavardhana** [comment]
```
~ MC_HOST_presto=http://minio-access-key:minio-secret-key@localhost:9000 mc ls presto/some-bucket/tpch_sf10_text/
[2020-12-09 17:39:01 PST] 2.2GiB 20201210_012059_00000_u5gxk_88fa822c-c98e-420d-a2ba-635b5b374891.gz
```

**Comment by harshavardhana** [comment]
Please test with the latest release and let us know if you face the same issue. Closing this issue for now.

**Comment by Druckles** [comment]
Unfortunately I have to open this again. Our customer has finally run it using an up-to-date version of MinIO (RELEASE.2021-01-16T02-19-44Z).

These are from the MinIO error logs (semi-sensitive data replaced with `---`):

```
API: CompleteMultipartUpload(bucket=bucket, object=root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4)
 Time: 14:54:31 UTC 01/29/2021
 DeploymentID: c54b6718-d7ab-4314-913d-c1e1a767add8
 RequestID: 165EBBADB18EDF5C
 RemoteHost: 10.9.58.35
 UserAgent: aws-sdk-java/1.11.710 Windows_Server_2012_R2/6.3 OpenJDK_64-Bit_Server_VM/11.0.8+10-LTS java/11.0.8 vendor/ojdkbuild
 Error: file not found (cmd.StorageErr)
 uploadIDDir=D:\---\---\repo/.minio.sys/multipart/0d63658d6718fd00721df9e9ac399ab263bd674d974278d4c50dccc5c12cb468/afc11b43-4433-4227-8f3e-5fa7f1e05f60
        5: cmd\fs-v1-multipart.go:588:cmd.(*FSObjects).CompleteMultipartUpload()
        4: cmd\object-handlers.go:2640:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
        3: cmd\http-tracer.go:204:cmd.Trace()
        2: cmd\handler-utils.go:355:cmd.httpTraceAll.func1()
        1: net\http\server.go:2042:http.HandlerFunc.ServeHTTP()

 API: CompleteMultipartUpload(bucket=bucket, object=root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4)
 Time: 14:54:31 UTC 01/29/2021
 DeploymentID: c54b6718-d7ab-4314-913d-c1e1a767add8
 RequestID: 165EBBADB18EDF5C
 RemoteHost: 10.9.58.35
 UserAgent: aws-sdk-java/1.11.710 Windows_Server_2012_R2/6.3 OpenJDK_64-Bit_Server_VM/11.0.8+10-LTS java/11.0.8 vendor/ojdkbuild
 Error: file not found (cmd.StorageErr)
 uploadIDDir=D:\---\---\repo/.minio.sys/multipart/0d63658d6718fd00721df9e9ac399ab263bd674d974278d4c50dccc5c12cb468/afc11b43-4433-4227-8f3e-5fa7f1e05f60
        5: cmd\fs-v1-multipart.go:588:cmd.(*FSObjects).CompleteMultipartUpload()
        4: cmd\object-handlers.go:2640:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
        3: cmd\http-tracer.go:204:cmd.Trace()
        2: cmd\handler-utils.go:355:cmd.httpTraceAll.func1()
        1: net\http\server.go:2042:http.HandlerFunc.ServeHTTP()

 API: CompleteMultipartUpload(bucket=bucket, object=root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4)
 Time: 14:54:31 UTC 01/29/2021
 DeploymentID: c54b6718-d7ab-4314-913d-c1e1a767add8
 RequestID: 165EBBADB18EDF5C
 RemoteHost: 10.9.58.35
 UserAgent: aws-sdk-java/1.11.710 Windows_Server_2012_R2/6.3 OpenJDK_64-Bit_Server_VM/11.0.8+10-LTS java/11.0.8 vendor/ojdkbuild
 Error: file not found (cmd.StorageErr)
 uploadIDDir=D:\---\---\repo/.minio.sys/multipart/0d63658d6718fd00721df9e9ac399ab263bd674d974278d4c50dccc5c12cb468/afc11b43-4433-4227-8f3e-5fa7f1e05f60
        6: cmd\api-errors.go:2003:cmd.toAPIErrorCode()
        5: cmd\api-errors.go:2028:cmd.toAPIError()
        4: cmd\object-handlers.go:2648:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
        3: cmd\http-tracer.go:204:cmd.Trace()
        2: cmd\handler-utils.go:355:cmd.httpTraceAll.func1()
        1: net\http\server.go:2042:http.HandlerFunc.ServeHTTP()

 API: CompleteMultipartUpload(bucket=bucket, object=root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4)
 Time: 14:54:31 UTC 01/29/2021
 DeploymentID: c54b6718-d7ab-4314-913d-c1e1a767add8
 RequestID: 165EBBADB18EDF5C
 RemoteHost: 10.9.58.35
 UserAgent: aws-sdk-java/1.11.710 Windows_Server_2012_R2/6.3 OpenJDK_64-Bit_Server_VM/11.0.8+10-LTS java/11.0.8 vendor/ojdkbuild
 Error: file not found (cmd.StorageErr)
 uploadIDDir=D:\---\---\repo/.minio.sys/multipart/0d63658d6718fd00721df9e9ac399ab263bd674d974278d4c50dccc5c12cb468/afc11b43-4433-4227-8f3e-5fa7f1e05f60
        6: cmd\api-errors.go:2003:cmd.toAPIErrorCode()
        5: cmd\api-errors.go:2028:cmd.toAPIError()
        4: cmd\object-handlers.go:2648:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
        3: cmd\http-tracer.go:204:cmd.Trace()
        2: cmd\handler-utils.go:355:cmd.httpTraceAll.func1()
        1: net\http\server.go:2042:http.HandlerFunc.ServeHTTP()
```

And these are the trace logs towards the end of the upload:

```
14:54:30.017 [200 OK] s3.PutObjectPart ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72&partNumber=16  10.9.58.35        792.046ms    ↑ 5.0 MiB ↓ 230 B
14:54:30.820 [200 OK] s3.HeadBucket ---:9000/bucket/ 10.9.58.35        0s           ↑ 137 B ↓ 189 B
14:54:30.831 [200 OK] s3.HeadBucket ---:9000/bucket/ 10.9.58.35        0s           ↑ 137 B ↓ 189 B
14:54:30.519 [200 OK] s3.PutObjectPart ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72&partNumber=20  10.9.58.35        627.038ms    ↑ 5.0 MiB ↓ 230 B
14:54:31.180 [200 OK] s3.HeadBucket ---:9000/bucket/ 10.9.58.35        0s           ↑ 137 B ↓ 189 B
14:54:31.185 [200 OK] s3.PutObjectPart ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72&partNumber=25  10.9.58.35        32.006ms     ↑ 3.8 KiB ↓ 230 B
14:54:30.598 [200 OK] s3.PutObjectPart ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72&partNumber=21  10.9.58.35        728.046ms    ↑ 5.0 MiB ↓ 230 B
14:54:26.246 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=afc11b43-4433-4227-8f3e-5fa7f1e05f60  10.9.58.35        5.095291s    ↑ 944 B ↓ 760 B
14:54:30.768 [200 OK] s3.PutObjectPart ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72&partNumber=22  10.9.58.35        729.041ms    ↑ 5.0 MiB ↓ 230 B
14:54:30.857 [200 OK] s3.PutObjectPart ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72&partNumber=24  10.9.58.35        714.042ms    ↑ 5.0 MiB ↓ 230 B
14:54:30.874 [200 OK] s3.PutObjectPart ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72&partNumber=23  10.9.58.35        712.04ms     ↑ 5.0 MiB ↓ 230 B
14:54:31.601 [200 OK] s3.HeadBucket ---:9000/bucket/ 10.9.58.35        0s           ↑ 137 B ↓ 189 B
14:54:31.327 [500 Internal Server Error] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=afc11b43-4433-4227-8f3e-5fa7f1e05f60  10.9.58.35        361.02ms     ↑ 944 B ↓ 759 B
14:54:32.033 [404 Not Found] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=afc11b43-4433-4227-8f3e-5fa7f1e05f60  10.9.58.35        1ms          ↑ 944 B ↓ 775 B
14:54:24.948 [499 ] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=320275df-666b-4d03-8dd4-4f847ed0f461  10.9.58.35        7.206415s    ↑ 1.4 KiB ↓ 723 B
14:54:20.326 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=2099c355-29a0-47b2-b72a-df920ea77089  10.9.58.35        12.328709s   ↑ 1.4 KiB ↓ 687 B
14:54:25.362 [499 ] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=2099c355-29a0-47b2-b72a-df920ea77089  10.9.58.35        7.426426s    ↑ 1.4 KiB ↓ 737 B
14:54:28.646 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=34f7a4d9-e044-4858-83ec-08bbd9fb0679  10.9.58.35        4.599298s    ↑ 1.6 KiB ↓ 744 B
14:54:30.730 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=2099c355-29a0-47b2-b72a-df920ea77089  10.9.58.35        3.417232s    ↑ 1.4 KiB ↓ 762 B
14:54:30.035 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=320275df-666b-4d03-8dd4-4f847ed0f461  10.9.58.35        4.709333s    ↑ 1.4 KiB ↓ 748 B
14:54:31.603 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/shared/---.mp4?uploadId=5be5da72-b936-40cd-b841-b3594ebdaa72  10.9.58.35        3.670274s    ↑ 2.3 KiB ↓ 748 B
14:54:23.246 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/---.ttcp?uploadId=e96f7c0f-29d8-4d21-b391-6785564f9074  10.9.58.35        16.721253s   ↑ 7.1 KiB ↓ 643 B
14:54:43.985 [200 OK] s3.HeadBucket ---:9000/bucket/ 10.9.58.35        999µs       ↑ 137 B ↓ 189 B
14:54:43.987 [200 OK] s3.HeadObject ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/---.ttcp 10.9.58.35        2ms          ↑ 137 B ↓ 313 B
14:54:28.313 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/---.ttcp?uploadId=e96f7c0f-29d8-4d21-b391-6785564f9074  10.9.58.35        24.609692s   ↑ 7.1 KiB ↓ 644 B
14:54:33.465 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/---.ttcp?uploadId=e96f7c0f-29d8-4d21-b391-6785564f9074  10.9.58.35        19.57237s    ↑ 7.1 KiB ↓ 643 B
14:54:38.631 [200 OK] s3.CompleteMultipartUpload ---:9000/bucket/root/75/97a019fc-ebf9-47c9-970f-d41de88c96ce/---.ttcp?uploadId=e96f7c0f-29d8-4d21-b391-6785564f9074  10.9.58.35        14.452933s   ↑ 7.1 KiB ↓ 643 B
14:55:27.400 [200 OK] s3.HeadBucket ---:9000/bucket/ 10.9.58.35        0s           ↑ 137 B ↓ 189 B
14:55:27.401 [200 OK] s3.ListObjectsV1 ---:9000/bucket/?prefix=root%2F75%2Ff3f246f0-74b6-4b9a-b5c7-4ca4e773d8e7%2F---.ttcp&delimiter=%2F&encoding-type=url  10.9.58.35
```

Notable are the 500, 404 and 499 errors. The 499 reflects the exception we received in the log (for this single test, in the past it hasn't timed out):

```
com.amazonaws.SdkClientException: Unable to execute HTTP request: Read timed out
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1189)
        ...
```

However, the 500 and 404 are strange. Is a 500 returned as a response? Why did it even occur? Why is a 404 being reported? Which status corresponds to the logged exceptions?

We previously (as described above) saw a 503 followed by a 404. Has the error code simply been changed?

Although the time out is not directly relevant and one could raise the timeout threshold, I believe it may be a factor in the problem's reproducibility, i.e. there's some race condition going on.

**Comment by Druckles** [comment]
Ignore the last comment. We've set the socket timeouts higher and it now works! The improved behaviour from MinIO and subsequent error messages put us on the right track. Thank you :-)

For those of you using the S3 SDK or the TransferManager:

```
AmazonS3ClientBuilder builder = AmazonS3ClientBuilder.standard()
		.withClientConfiguration(new ClientConfiguration()
                                // ...
				.withSocketTimeout(socketTimeout)); // <-- increase this timeout here.
```
