### ISSUE TITLE
[fixed] Download file occurs connection reset

### ISSUE THREAD

**Issue by crossnote** [minio/minio#10807]
I use java sdk 7.1.0 to download a file from the minio server, and then return it to the browser, my application reports the following error
`java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:209)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.InputRecord.readFully(InputRecord.java 465)
        at sun.security.ssl.InputRecord.read(InputRecord.java:503)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
        at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.iava:930)
        at sun. securi ty. ssl. AppInputStream.read(AppInputStream.java:105)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okht tp3.internal. http1.HttplExchangeCodec$AbstractSource.read(HttplExchangeCodec.java:389)
        at okhttp3.internal.http1.HttpExchangeCodec$FixedLengthSource.read(Http1Exchangecodec.java:127)
        at okhttp3.internal.connection.Exchange$ResponseBodySource. read(Exchange.java:286)
        at okio.RealBufferedSouce$1.read(RealBufferedSouce.java:447)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:236)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        at java.io.FilterInputStream.read(FilterInputStream.java:107)
        at com.zhsz.zygl.webapires.service.impl.ResFileServiceImpl.downloadFile`
This is my code to download the file:
`@RequestMapping(value = "/download", method = RequestMethod.GET)
    @ApiOperation("downloaf file")
    public void download(@RequestParam("fileName") String fileName,
                           @RequestParam("bucketName") String bucketName, HttpServletResponse response) {

        try {
            //get object given the bucket and object name
            InputStream fileInputStream = minioUtil.getObject(bucketName, fileName);
            response.setHeader("Content-Disposition", "attachment;filename=" + fileName);
            response.setContentType("application/force-download");
            response.setCharacterEncoding("UTF-8");
            // return fileInputStream to browser
            IOUtils.copy(fileInputStream, response.getOutputStream());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }`
I have set the socket connection time as follows:
`minioClient.setTimeout(10*60*1000, 10*60*1000,10*60*1000);`

I want to ask if this has anything to do with my network and how should I set it up to solve this problem
## Current Behavior

It should be pointed out that this problem does not happen every time a file is downloaded, it happens once in a while.
The result of using mc admin trace is as shown below. When the download is successful, the complete file is 3.5GiB. When the download fails, minio only returns 1.9GiB.
![P01030-091822(1)(1)](https://user-images.githubusercontent.com/22958160/97651243-7da03500-1a96-11eb-8d91-11934e4dce29.jpg)

## Possible Solution

If it is because the browser is too slow to receive files and cannot keep up with the speed of the minio service, which causes the connection to be reset, is there any good suggestion to quickly send the file stream to the browser?
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`): minio version RELEASE.2020-07-18T18-48-16Z
* Server setup and configuration: The server are four linux machines, using a self-signed certificate to build https access，no nginx proxy is used.
* Operating System and version (`uname -a`): centOs 7

**Comment by harshavardhana** [comment]
Can you use latest release and let us know?

**Comment by crossnote** [comment]
thank you, i will try, then tell you if this method works

**Comment by harshavardhana** [comment]
Closing this issue as fixed already in latest releases.

**Comment by crossnote** [comment]
yes,I updated to the latest version and the problem no longer occurs,thank you
