### ISSUE TITLE
When set MinIO `export MINIO_CACHE_COMMIT=writeback`, uploading files using minio-java SDK throws NullPointerException

### ISSUE THREAD

**Issue by blinkfox** [minio/minio#10974]
When I use MinIO Gateway for NAS, I set

```bash
export MINIO_CACHE_COMMIT=writeback
```

Then using minio-java SDK to upload files, it will throw a `NullPointerException`:

```bash
java.lang.NullPointerException: null
	at io.minio.MinioClient.putObject(MinioClient.java:7596) ~[minio-7.1.4.jar:7.1.4]
	at io.minio.MinioClient.putObject(MinioClient.java:4682) ~[minio-7.1.4.jar:7.1.4]
	at io.minio.MinioClient.putObject(MinioClient.java:4881) ~[minio-7.1.4.jar:7.1.4]
	at com.blinkfox.optimus.tcs.minio.service.MinioClientService.putObject(MinioClientService.java:155) ~[classes/:na]
	at com.blinkfox.optimus.tcs.minio.service.MinioService.upload(MinioService.java:80) ~[classes/:na]
	at com.blinkfox.optimus.tcs.minio.controller.MinioController.upload(MinioController.java:67) ~[classes/:na]
```

I debugged and found that the cause of the exception was the value of `response.header("ETag")` is `null`:

```java
try (Response response =
    execute(
        Method.PUT,
        bucketName,
        objectName,
        getRegion(bucketName, region),
        headers,
        extraQueryParams,
        data,
        length)) {
    return new ObjectWriteResponse(
        response.headers(),
        bucketName,
        region,
        objectName,
        response.header("ETag").replaceAll("\"", ""),
        response.header("x-amz-version-id"));
}
```

The version of minio I used is `RELEASE.2020-11-19T23-48-16Z`, the version of minio-java SDK is `7.1.4`, I tried the `8.0.1` version and still have this problem.

**Comment by poornas** [comment]
what are your other cache settings? I could not repro the issue with the sdk versions and minio release in question. You can also see if `mc admin trace -v myminio` shows the ETag

**Comment by blinkfox** [comment]
The cache settings:

```bash
export MINIO_CACHE="on"
export MINIO_CACHE_DRIVES="/data/temp-drive"
export MINIO_CACHE_COMMIT=writeback
export MINIO_CACHE_QUOTA=80
export MINIO_CACHE_AFTER=3
export MINIO_CACHE_WATERMARK_LOW=70
export MINIO_CACHE_WATERMARK_HIGH=90
```

I found that it should be caused by the instability of using the `MINIO_CACHE_COMMIT=writeback` in MinIO. If it is a large file, it will succeed, but a small file will fail. 

I guess that the problem should be on the MinIO Server side. My upload results in the MinIO browser page are also unstable, but it is very likely to succeed if it exceeds `1 MB`, and it will fail if it is less than `1MB`:

The following is the `trace` information of a small file about `10KB` that I uploaded:

```bash
172.16.14.82 [REQUEST s3.PutObject] 02:29:40.393
172.16.14.82 PUT /perform-test4/2017/02/18/18/37/AJV7KqqXp.docx
172.16.14.82 Host: 172.16.14.82:9102
172.16.14.82 Accept-Encoding: identity
172.16.14.82 Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
172.16.14.82 User-Agent: MinIO (amd64; amd64) minio-java/5.2.8.RELEASE
172.16.14.82 X-Amz-Date: 20201126T022940Z
172.16.14.82 Authorization: AWS4-HMAC-SHA256 Credential=admin/20201126/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=b8e663f1c3eef444a965b2c2ac63305b5fd5e83982ab21422a57068cb435d197
172.16.14.82 Connection: Keep-Alive
172.16.14.82 Content-Length: 10522
172.16.14.82 Content-Md5: B1JotSwa/w53FEXUdiBg0g==
172.16.14.82 X-Amz-Content-Sha256: b1110ca7a1af544378a385162b798ffbc4c6e00299d9f970ab563336736d7eb9
172.16.14.82 <BODY>
172.16.14.82 [RESPONSE] [02:29:40.395] [ Duration 1.862ms  ↑ 129 B  ↓ 189 B ]
172.16.14.82 200 OK
172.16.14.82 X-Amz-Request-Id: 164AEDE3F2856555
172.16.14.82 X-Xss-Protection: 1; mode=block
172.16.14.82 Accept-Ranges: bytes
172.16.14.82 Content-Length: 0
172.16.14.82 Content-Security-Policy: block-all-mixed-content
172.16.14.82 Server: MinIO
172.16.14.82 Vary: Origin
172.16.14.82 <BODY>
```

The upload result failed, the exception is:

```bash
java.lang.NullPointerException: null
    at io.minio.MinioClient.putObject(MinioClient.java:7596) ~[minio-7.1.4.jar:7.1.4]
    at io.minio.MinioClient.putObject(MinioClient.java:4682) ~[minio-7.1.4.jar:7.1.4]
    at io.minio.MinioClient.putObject(MinioClient.java:4881) ~[minio-7.1.4.jar:7.1.4]
    at com.blinkfox.optimus.tcs.minio.service.MinioClientService.putObject(MinioClientService.java:155) ~[classes/:na]
    at com.blinkfox.optimus.tcs.minio.service.MinioService.randomUpload(MinioService.java:102) ~[classes/:na]
    at com.blinkfox.optimus.tcs.minio.controller.MinioController.randomUpload(MinioController.java:78) ~[classes/:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191]
```

The following is the `trace` information of a file about `4.99MB`:

```bash
172.16.14.82 [REQUEST s3.PutObject] 02:52:06.055
172.16.14.82 PUT /perform-test2/2019/08/30/12/18/a.txt
172.16.14.82 Host: 172.16.14.82:9102
172.16.14.82 Content-Length: 5232676
172.16.14.82 Content-Md5: bn/5VETgaU7vW9DQdRVqyw==
172.16.14.82 X-Amz-Content-Sha256: e88eebf1163b41bd6674d42a2faf53a241004a3c50635368aa920b38be205e39
172.16.14.82 Authorization: AWS4-HMAC-SHA256 Credential=admin/20201126/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=85da1dc280f1e28579e24fb88abf1510584dad45484f82f2e0b13c39dd153f4f
172.16.14.82 Connection: Keep-Alive
172.16.14.82 User-Agent: MinIO (amd64; amd64) minio-java/5.2.8.RELEASE
172.16.14.82 X-Amz-Date: 20201126T025206Z
172.16.14.82 Accept-Encoding: identity
172.16.14.82 Content-Type: text/plain
172.16.14.82 <BODY>
172.16.14.82 [RESPONSE] [02:52:06.056] [ Duration 1.296ms  ↑ 129 B  ↓ 189 B ]
172.16.14.82 200 OK
172.16.14.82 X-Amz-Request-Id: 164AEF1D4237DAEE
172.16.14.82 X-Xss-Protection: 1; mode=block
172.16.14.82 Accept-Ranges: bytes
172.16.14.82 Content-Length: 0
172.16.14.82 Content-Security-Policy: block-all-mixed-content
172.16.14.82 Server: MinIO
172.16.14.82 Vary: Origin
172.16.14.82 <BODY>
```

The upload result also failed, the exception is:

```bash
Caused by: java.net.SocketException: Connection reset by peer: socket write error
    at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_191]
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111) ~[na:1.8.0_191]
    at java.net.SocketOutputStream.write(SocketOutputStream.java:155) ~[na:1.8.0_191]
    at okio.Okio$1.write(Okio.java:79) ~[okio-1.17.2.jar:na]
    at okio.AsyncTimeout$1.write(AsyncTimeout.java:180) ~[okio-1.17.2.jar:na]
    at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179) ~[okio-1.17.2.jar:na]
    at okio.RealBufferedSink.write(RealBufferedSink.java:42) ~[okio-1.17.2.jar:na]
    at okhttp3.internal.http1.Http1ExchangeCodec$KnownLengthSink.write(Http1ExchangeCodec.java:324) ~[okhttp-3.14.9.jar:na]
    at okio.ForwardingSink.write(ForwardingSink.java:35) ~[okio-1.17.2.jar:na]
    at okhttp3.internal.connection.Exchange$RequestBodySink.write(Exchange.java:231) ~[okhttp-3.14.9.jar:na]
    at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179) ~[okio-1.17.2.jar:na]
    at okio.RealBufferedSink.write(RealBufferedSink.java:117) ~[okio-1.17.2.jar:na]
    at io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:78) ~[minio-7.1.4.jar:7.1.4]
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:69) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:na]
    at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar:na]
    at io.minio.MinioClient.execute(MinioClient.java:1014) ~[minio-7.1.4.jar:7.1.4]
    at io.minio.MinioClient.putObject(MinioClient.java:7582) ~[minio-7.1.4.jar:7.1.4]
    at io.minio.MinioClient.putObject(MinioClient.java:4682) ~[minio-7.1.4.jar:7.1.4]
    at io.minio.MinioClient.putObject(MinioClient.java:4881) ~[minio-7.1.4.jar:7.1.4]
```

The following is the `trace` information of the file about `5.42MB`. The upload was successful this time without any exception:

```bash
172.16.14.82 [REQUEST s3.NewMultipartUpload] 02:47:08.199
172.16.14.82 POST /perform-test2/2017/02/08/03/26/a.txt?uploads=
172.16.14.82 Host: 172.16.14.82:9102
172.16.14.82 Accept-Encoding: identity
172.16.14.82 Connection: Keep-Alive
172.16.14.82 Content-Type: text/plain
172.16.14.82 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.16.14.82 X-Amz-Date: 20201126T024708Z
172.16.14.82 Authorization: AWS4-HMAC-SHA256 Credential=admin/20201126/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=f0836ebc58e55db8e4954e3ccdd6ae49d35c1fd261bbb7b568ecc4dbd73efd3d
172.16.14.82 Content-Length: 0
172.16.14.82 Content-Md5: 1B2M2Y8AsgTpgAmY7PhCfg==
172.16.14.82 User-Agent: MinIO (amd64; amd64) minio-java/5.2.8.RELEASE
172.16.14.82
172.16.14.82 [RESPONSE] [02:47:08.649] [ Duration 449.79ms  ↑ 129 B  ↓ 491 B ]
172.16.14.82 200 OK
172.16.14.82 Server: MinIO
172.16.14.82 Vary: Origin
172.16.14.82 X-Amz-Request-Id: 164AEED7E89FCCED
172.16.14.82 X-Xss-Protection: 1; mode=block
172.16.14.82 Accept-Ranges: bytes
172.16.14.82 Content-Length: 270
172.16.14.82 Content-Security-Policy: block-all-mixed-content
172.16.14.82 Content-Type: application/xml
172.16.14.82 <?xml version="1.0" encoding="UTF-8"?>
<InitiateMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Bucket>perform-test2</Bucket><Key>2017/02/08/03/26/a.txt</Key><UploadId>9661e8db-419a-42a9-b3d2-1164b34696cd</UploadId></InitiateMultipartUploadResult>
172.16.14.82
172.16.14.82 [REQUEST s3.PutObjectPart] 02:47:08.778
172.16.14.82 PUT /perform-test2/2017/02/08/03/26/a.txt?uploadId=9661e8db-419a-42a9-b3d2-1164b34696cd&partNumber=1
172.16.14.82 Host: 172.16.14.82:9102
172.16.14.82 Content-Type: application/octet-stream
172.16.14.82 X-Amz-Date: 20201126T024708Z
172.16.14.82 Authorization: AWS4-HMAC-SHA256 Credential=admin/20201126/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=7e01d68faecc56bedba6f933221457a9011b8a8ab3b6d0cb0191e29aabc0ca7e
172.16.14.82 Content-Length: 5242880
172.16.14.82 Content-Md5: 1kNg81ybQKu3UBc6TK7iOQ==
172.16.14.82 X-Amz-Content-Sha256: 3f3cffbe34250e1474c0cd8d760f83d5a20ae2210c0b3bde8c7e0fdccf191b4b
172.16.14.82 Accept-Encoding: identity
172.16.14.82 Connection: Keep-Alive
172.16.14.82 User-Agent: MinIO (amd64; amd64) minio-java/5.2.8.RELEASE
172.16.14.82 <BODY>
172.16.14.82 [RESPONSE] [02:47:17.549] [ Duration 8.770668s  ↑ 5.0 MiB  ↓ 230 B ]
172.16.14.82 200 OK
172.16.14.82 X-Xss-Protection: 1; mode=block
172.16.14.82 Accept-Ranges: bytes
172.16.14.82 Content-Length: 0
172.16.14.82 Content-Security-Policy: block-all-mixed-content
172.16.14.82 ETag: "d64360f35c9b40abb750173a4caee239"
172.16.14.82 Server: MinIO
172.16.14.82 Vary: Origin
172.16.14.82 X-Amz-Request-Id: 164AEED80B273EAE
172.16.14.82 <BODY>
172.16.14.82
172.16.14.82 [REQUEST s3.PutObjectPart] 02:47:17.618
172.16.14.82 PUT /perform-test2/2017/02/08/03/26/a.txt?uploadId=9661e8db-419a-42a9-b3d2-1164b34696cd&partNumber=2
172.16.14.82 Host: 172.16.14.82:9102
172.16.14.82 Content-Length: 442878
172.16.14.82 X-Amz-Content-Sha256: 3b43dd8c14a65022a1f63b9ed682363b3087d95e668b1b24d1e467fd0ea28824
172.16.14.82 X-Amz-Date: 20201126T024717Z
172.16.14.82 Accept-Encoding: identity
172.16.14.82 Connection: Keep-Alive
172.16.14.82 Content-Type: application/octet-stream
172.16.14.82 User-Agent: MinIO (amd64; amd64) minio-java/5.2.8.RELEASE
172.16.14.82 Authorization: AWS4-HMAC-SHA256 Credential=admin/20201126/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=5cdf5feb5bd465882fcd8a8578402dc10f87d87dc6b12dd8e81ef28b134b9634
172.16.14.82 Content-Md5: J5hcVTu50exjr5Mco2+zXg==
172.16.14.82 <BODY>
172.16.14.82 [RESPONSE] [02:47:20.621] [ Duration 3.002567s  ↑ 433 KiB  ↓ 230 B ]
172.16.14.82 200 OK
172.16.14.82 Content-Length: 0
172.16.14.82 Content-Security-Policy: block-all-mixed-content
172.16.14.82 ETag: "27985c553bb9d1ec63af931ca36fb35e"
172.16.14.82 Server: MinIO
172.16.14.82 Vary: Origin
172.16.14.82 X-Amz-Request-Id: 164AEEDA1A0E85D5
172.16.14.82 X-Xss-Protection: 1; mode=block
172.16.14.82 Accept-Ranges: bytes
172.16.14.82 <BODY>
172.16.14.82
172.16.14.82 [REQUEST s3.CompleteMultipartUpload] 02:47:20.678
172.16.14.82 POST /perform-test2/2017/02/08/03/26/a.txt?uploadId=9661e8db-419a-42a9-b3d2-1164b34696cd
172.16.14.82 Host: 172.16.14.82:9102
172.16.14.82 Accept-Encoding: identity
172.16.14.82 Authorization: AWS4-HMAC-SHA256 Credential=admin/20201126/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=80904a6034f4a81c9759d753d17e02d282fc2b24dcc1749ff0a414d9b812dd04
172.16.14.82 Content-Length: 267
172.16.14.82 Content-Type: application/octet-stream
172.16.14.82 X-Amz-Content-Sha256: 287b9e156a8d18c28ea8233afe17168f1442954df3c1809543ea2d6ed67da51e
172.16.14.82 Connection: Keep-Alive
172.16.14.82 Content-Md5: UEgAV022qM9H7BctmXxTtg==
172.16.14.82 User-Agent: MinIO (amd64; amd64) minio-java/5.2.8.RELEASE
172.16.14.82 X-Amz-Date: 20201126T024720Z
172.16.14.82 <CompleteMultipartUpload xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Part><PartNumber>1</PartNumber><ETag>d64360f35c9b40abb750173a4caee239</ETag></Part><Part><PartNumber>2</PartNumber><ETag>27985c553bb9d1ec63af931ca36fb35e</ETag></Part></CompleteMultipartUpload>
172.16.14.82 [RESPONSE] [02:47:23.517] [ Duration 2.839221s  ↑ 396 B  ↓ 662 B ]
172.16.14.82 200 OK
172.16.14.82 Content-Length: 352
172.16.14.82 Content-Security-Policy: block-all-mixed-content
172.16.14.82 Vary: Origin
172.16.14.82 X-Accel-Buffering: no
172.16.14.82 X-Amz-Request-Id: 164AEEDAD06D0BBD
172.16.14.82 X-Xss-Protection: 1; mode=block
172.16.14.82 Cache-Control: no-cache
172.16.14.82 Content-Type: application/xml
172.16.14.82 ETag: "088542673afed9032b23cff6c9dc3eb8-2"
172.16.14.82 Server: MinIO
172.16.14.82 Accept-Ranges: bytes
172.16.14.82 <?xml version="1.0" encoding="UTF-8"?>
<CompleteMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Location>http://172.16.14.82:9102/perform-test2/2017/02/08/03/26/a.txt</Location><Bucket>perform-test2</Bucket><Key>2017/02/08/03/26/a.txt</Key><ETag>&#34;088542673afed9032b23cff6c9dc3eb8-2&#34;</ETag></CompleteMultipartUploadResult>
```
