### ISSUE TITLE
fput_object always throws error 'minio.error.InvalidArgumentError: InvalidArgumentError: message: Part size * max_parts(10000) is  lesser than input length'

### ISSUE THREAD

**Issue by kkraju555** [minio/minio#10988]
Installed Python module Minio to connect S3 Compatible local storage in office premises using python pip command

Running Python code on AIX box 
Python 3.7.6
AIX 7 

I  was able to transfer files of smaller size ( less than MB) . For file which is 63 GB backup file , Got the below error 

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    minioClient.fput_object('backupon27oct2020','Corniche_Reports/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001','/db2t/glxydev3/db2backups/bkup02/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001',part_size=-1)
  File "/opt/freeware/lib/python3.7/site-packages/minio/api.py", line 752, in fput_object
    progress, part_size)
  File "/opt/freeware/lib/python3.7/site-packages/minio/api.py", line 1028, in put_object
    raise InvalidArgumentError('Part size * max_parts(10000) is '
minio.error.InvalidArgumentError: InvalidArgumentError: message: Part size * max_parts(10000) is  lesser than input length.

Tried to Run the fput_object with various options and Part_Size . but it always throught the above error

Failed 
minioClient.fput_object('backupon27oct2020','Corniche_Reports/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001','/db2t/glxydev3/db2backups/bkup02/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001)
  
Failed

minioClient.fput_object('backupon27oct2020','Corniche_Reports/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001','/db2t/glxydev3/db2backups/bkup02/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001',part_size=-1)

Can you help why the error is occurring  and help in resolving the same 

## Expected Behavior
minioClient.fput_object('backupon27oct2020','Corniche_Reports/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001','/db2t/glxydev3/db2backups/bkup02/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001') 
should be successful irrespective of size of file and without part_size option also 

## Current Behavior
lxydev3/db2backups/bkup02/DBDEV2A.0.glxydev2.DBPART002.20201126033352.001',part_size=-1)
  File "/opt/freeware/lib/python3.7/site-packages/minio/api.py", line 752, in fput_object
    progress, part_size)
  File "/opt/freeware/lib/python3.7/site-packages/minio/api.py", line 1028, in put_object
    raise InvalidArgumentError('Part size * max_parts(10000) is '
minio.error.InvalidArgumentError: InvalidArgumentError: message: Part size * max_parts(10000) is  lesser than input length.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):

**Comment by harshavardhana** [comment]
Moving the issue to minio-py
