### ISSUE TITLE
minio restart failed in distributed deployment

### ISSUE THREAD

**Issue by Gavineil** [minio/minio#11240]
five node each with one disk. 

mc admin service restart minio.

one node restart failed.

error:
runtime: pointer 0xc00012e000 to unused region of span span.base()=0xc00012e000 span.limit=0xc00012e000 span.state=1
fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

goroutine 1 [running, locked to thread]:
runtime.throw(0x1e75935, 0x3e)
        runtime/panic.go:1116 +0x72 fp=0xc000122d08 sp=0xc000122cd8 pc=0x437952
runtime.badPointer(0x7f51c6118910, 0xc00012e000, 0x0, 0x0)
        runtime/mbitmap.go:380 +0x235 fp=0xc000122d50 sp=0xc000122d08 pc=0x415875
runtime.findObject(0xc00012e000, 0x0, 0x0, 0xc00012e000, 0x60, 0x58)
        runtime/mbitmap.go:416 +0x9b fp=0xc000122d88 sp=0xc000122d50 pc=0x41593b
runtime.SetFinalizer(0x1b2bd20, 0xc00012e000, 0x1ac7380, 0x1ea2a70)
        runtime/mfinal.go:329 +0x89 fp=0xc000122e70 sp=0xc000122d88 pc=0x419c89
os.newFile(0x0, 0x1e0b8cf, 0xa, 0x0, 0x0)
        os/file_unix.go:170 +0x133 fp=0xc000122ec0 sp=0xc000122e70 pc=0x4b1413
os.NewFile(0x0, 0x1e0b8cf, 0xa, 0x0)
        os/file_unix.go:92 +0x65 fp=0xc000122ef8 sp=0xc000122ec0 pc=0x4b12a5
os.init()
        os/file.go:63 +0x205 fp=0xc000122f28 sp=0xc000122ef8 pc=0x4b61a5
runtime.doInit(0x2cbf460)
        runtime/proc.go:5646 +0x8a fp=0xc000122f58 sp=0xc000122f28 pc=0x44748a
runtime.doInit(0x2cb5680)
        runtime/proc.go:5641 +0x57 fp=0xc000122f88 sp=0xc000122f58 pc=0x447457
runtime.main()
        runtime/proc.go:191 +0x1c5 fp=0xc000122fe0 sp=0xc000122f88 pc=0x43a105
runtime.goexit()
        runtime/asm_amd64.s:1374 +0x1 fp=0xc000122fe8 sp=0xc000122fe0 pc=0x470701

goroutine 2 [force gc (idle)]:
runtime.gopark(0x1ea2e70, 0x32931e0, 0x1411, 0x1)
        runtime/proc.go:306 +0xe5 fp=0xc000088fb0 sp=0xc000088f90 pc=0x43a545
runtime.goparkunlock(...)
        runtime/proc.go:312
runtime.forcegchelper()
        runtime/proc.go:255 +0xc5 fp=0xc000088fe0 sp=0xc000088fb0 pc=0x43a3e5
runtime.goexit()
        runtime/asm_amd64.s:1374 +0x1 fp=0xc000088fe8 sp=0xc000088fe0 pc=0x470701
created by runtime.init.6
        runtime/proc.go:243 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x1ea2e70, 0x3293840, 0x140c, 0x1)
        runtime/proc.go:306 +0xe5 fp=0xc0000897a8 sp=0xc000089788 pc=0x43a545
runtime.goparkunlock(...)
        runtime/proc.go:312
runtime.bgsweep(0xc0000a8000)
        runtime/mgcsweep.go:163 +0x9e fp=0xc0000897d8 sp=0xc0000897a8 pc=0x424a7e
runtime.goexit()
        runtime/asm_amd64.s:1374 +0x1 fp=0xc0000897e0 sp=0xc0000897d8 pc=0x470701
created by runtime.gcenable
        runtime/mgc.go:217 +0x5c

goroutine 4 [GC scavenge wait]:
runtime.gopark(0x1ea2e70, 0x3294460, 0x140d, 0x1)
        runtime/proc.go:306 +0xe5 fp=0xc000089f78 sp=0xc000089f58 pc=0x43a545
runtime.goparkunlock(...)
        runtime/proc.go:312
runtime.bgscavenge(0xc0000a8000)
        runtime/mgcscavenge.go:265 +0xd2 fp=0xc000089fd8 sp=0xc000089f78 pc=0x422ab2
runtime.goexit()
        runtime/asm_amd64.s:1374 +0x1 fp=0xc000089fe0 sp=0xc000089fd8 pc=0x470701
created by runtime.gcenable
        runtime/mgc.go:218 +0x7e

**Comment by Gavineil** [comment]
need your help

**Comment by harshavardhana** [comment]
> error:
> runtime: pointer 0xc00012e000 to unused region of span span.base()=0xc00012e000 span.limit=0xc00012e000 span.state=1
> fatal error: found bad pointer in Go heap (incorrect use of unsafe or cgo?)

We do not use cgo - did you compile the program yourself? what is the go version here?

**Comment by Gavineil** [comment]
i just download program from https://dl.min.io/server/minio/release/darwin-amd64/minio. go not installed on the server.

**Comment by Gavineil** [comment]
i just download program from https://dl.min.io/server/minio/release/darwin-amd64/minio. go not installed on the server. # @harshavardhana

**Comment by harshavardhana** [comment]
> i just download program from https://dl.min.io/server/minio/release/darwin-amd64/minio. go not installed on the server. # @harshavardhana

This looks like an upstream Go bug in their runtime

**Comment by Gavineil** [comment]
does minio program use go? what else can i do? @harshavardhana

**Comment by harshavardhana** [comment]
> does minio program use go? what else can i do? @harshavardhana

Me and you cannot do anything just restart the service manually for now. I don't think there is a solution right now, This needs to be fixed in Go upstream.

**Comment by Gavineil** [comment]
if i update minio program, this issue could be fixed? the server is online, restart is not a good chioce. @harshavardhana

**Comment by harshavardhana** [comment]
> if i update minio program, this issue could be fixed? the server is online, restart is not a good chioce. @harshavardhana

oh wait server didn't fail? its `mc` that died @Gavineil ?
