### ISSUE TITLE
MissingHeaderBodySeparatorDefect (again)

### ISSUE THREAD

**Issue by rb-determined-ai** [minio/minio#11245]
Seems to be the exact same behavior as #6540, which was supposedly fixed years ago.

## Expected Behavior

Uploading an empty file followed by uploading a non-empty file should not hang.

## Current Behavior
Uploading an empty file followed by uploading a non-empty file hangs.

## Steps to Reproduce (for bugs)

1. Run this script.

```python
import boto3
import logging

if __name__ == "__main__":
    logging.basicConfig(level="DEBUG")
    logging.debug(f"boto3 version: {boto3.__version__}")

    client = boto3.client(
        's3',
        endpoint_url="http://localhost:9000",
        aws_access_key_id="minio",
        aws_secret_access_key="12341234",
    )
    bucket = "test"

    with open("asdf", "w") as f:
        f.write("asdf")

    # This line finishes, but seems to cause the next upload to hang.
    client.put_object(Bucket=bucket, Key="empty", Body=b"")

    # This line prints.
    logging.debug("-------------------------------------")

    # This line prints an error and hangs.
    client.put_object(Bucket=bucket, Key="asdf", Body=b"asdf")
```

2. See log output:

```
DEBUG:root:boto3 version: 1.16.50
DEBUG:botocore.hooks:Changing event name from creating-client-class.iot-data to creating-client-class.iot-data-plane
DEBUG:botocore.hooks:Changing event name from before-call.apigateway to before-call.api-gateway
DEBUG:botocore.hooks:Changing event name from request-created.machinelearning.Predict to request-created.machine-learning.Predict
DEBUG:botocore.hooks:Changing event name from before-parameter-build.autoscaling.CreateLaunchConfiguration to before-parameter-build.auto-scaling.CreateLaunchConfiguration
DEBUG:botocore.hooks:Changing event name from before-parameter-build.route53 to before-parameter-build.route-53
DEBUG:botocore.hooks:Changing event name from request-created.cloudsearchdomain.Search to request-created.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.autoscaling.CreateLaunchConfiguration.complete-section to docs.*.auto-scaling.CreateLaunchConfiguration.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.logs.CreateExportTask to before-parameter-build.cloudwatch-logs.CreateExportTask
DEBUG:botocore.hooks:Changing event name from docs.*.logs.CreateExportTask.complete-section to docs.*.cloudwatch-logs.CreateExportTask.complete-section
DEBUG:botocore.hooks:Changing event name from before-parameter-build.cloudsearchdomain.Search to before-parameter-build.cloudsearch-domain.Search
DEBUG:botocore.hooks:Changing event name from docs.*.cloudsearchdomain.Search.complete-section to docs.*.cloudsearch-domain.Search.complete-section
DEBUG:botocore.loaders:Loading JSON file: /home/rb/miniconda3/envs/det/lib/python3.6/site-packages/botocore/data/endpoints.json
DEBUG:botocore.hooks:Event choose-service-name: calling handler <function handle_service_name_alias at 0x7f23dd2dae18>
DEBUG:botocore.loaders:Loading JSON file: /home/rb/miniconda3/envs/det/lib/python3.6/site-packages/botocore/data/s3/2006-03-01/service-2.json
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function add_generate_presigned_post at 0x7f23dd3098c8>
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function lazy_call.<locals>._handler at 0x7f23df05cea0>
DEBUG:botocore.hooks:Event creating-client-class.s3: calling handler <function add_generate_presigned_url at 0x7f23dd3096a8>
DEBUG:botocore.endpoint:Setting s3 timeout as (60, 60)
DEBUG:botocore.loaders:Loading JSON file: /home/rb/miniconda3/envs/det/lib/python3.6/site-packages/botocore/data/_retry.json
DEBUG:botocore.client:Registering retry handlers for service: s3
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x7f23dd2a8e18>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7f23dd2a82f0>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x7f23dd2aa730>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x7f23dd2a8268>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f23dca90cf8>>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f23de64c320>>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function generate_idempotent_uuid at 0x7f23dd2a80d0>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x7f23dd407840>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x7f23dd2a8598>
DEBUG:botocore.handlers:Adding expect 100 continue header to request.
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f23dca90cf8>>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function inject_api_version_header_if_needed at 0x7f23dd2aa840>
DEBUG:botocore.endpoint:Making request for OperationModel(name=PutObject) with params: {'url_path': '/test/empty', 'query_string': {}, 'method': 'PUT', 'headers': {'User-Agent': 'Boto3/1.16.50 Python/3.6.9 Linux/5.9.9-arch1-1 Botocore/1.19.50', 'Content-MD5': '1B2M2Y8AsgTpgAmY7PhCfg==', 'Expect': '100-continue'}, 'body': <_io.BytesIO object at 0x7f23dcabc308>, 'url': 'http://localhost:9000/test/empty', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config.Config object at 0x7f23dca1ac50>, 'has_streaming_input': True, 'auth_type': None, 'signing': {'bucket': 'test'}}}
DEBUG:botocore.hooks:Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f23dca1a7b8>>
DEBUG:botocore.hooks:Event choose-signer.s3.PutObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f23dcd28630>>
DEBUG:botocore.hooks:Event choose-signer.s3.PutObject: calling handler <function set_operation_specific_signer at 0x7f23dd2a3f28>
DEBUG:botocore.hooks:Event before-sign.s3.PutObject: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f23de64c390>>
DEBUG:botocore.utils:Using S3 path style addressing.
DEBUG:botocore.auth:Calculating signature using v4 auth.
DEBUG:botocore.auth:CanonicalRequest:
PUT
/test/empty

content-md5:1B2M2Y8AsgTpgAmY7PhCfg==
host:localhost:9000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20210107T201922Z

content-md5;host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
DEBUG:botocore.auth:StringToSign:
AWS4-HMAC-SHA256
20210107T201922Z
20210107/us-west-2/s3/aws4_request
929b74a7644ce82ca4fce6a24ff763ba0a443804e7fefc17842b5f16c7ff089d
DEBUG:botocore.auth:Signature:
f06c9a60fbbb161938c012fbf8065dd03825cdc6174f625f648f255482e181e2
DEBUG:botocore.endpoint:Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=http://localhost:9000/test/empty, headers={'User-Agent': b'Boto3/1.16.50 Python/3.6.9 Linux/5.9.9-arch1-1 Botocore/1.19.50', 'Content-MD5': b'1B2M2Y8AsgTpgAmY7PhCfg==', 'Expect': b'100-continue', 'X-Amz-Date': b'20210107T201922Z', 'X-Amz-Content-SHA256': b'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minio/20210107/us-west-2/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=f06c9a60fbbb161938c012fbf8065dd03825cdc6174f625f648f255482e181e2', 'Content-Length': '0'}>
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:9000
DEBUG:botocore.awsrequest:Waiting for 100 Continue response.
DEBUG:botocore.awsrequest:Received a non 100 Continue response from the server, NOT sending request body.
DEBUG:urllib3.connectionpool:http://localhost:9000 "PUT /test/empty HTTP/1.1" 200 0
DEBUG:botocore.parsers:Response headers: {'Accept-Ranges': 'bytes', 'Content-Length': '0', 'Content-Security-Policy': 'block-all-mixed-content', 'ETag': '"d41d8cd98f00b204e9800998ecf8427e"', 'Server': 'MinIO', 'Vary': 'Origin', 'X-Amz-Request-Id': '16580CA373EC32BE', 'X-Xss-Protection': '1; mode=block', 'Date': 'Thu, 07 Jan 2021 20:19:22 GMT'}
DEBUG:botocore.parsers:Response body:
b''
DEBUG:botocore.hooks:Event needs-retry.s3.PutObject: calling handler <botocore.retryhandler.RetryHandler object at 0x7f23dca90b70>
DEBUG:botocore.retryhandler:No retry needed.
DEBUG:botocore.hooks:Event needs-retry.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f23dca90cf8>>
DEBUG:root:-------------------------------------
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function validate_ascii_metadata at 0x7f23dd2a8e18>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function sse_md5 at 0x7f23dd2a82f0>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function convert_body_to_file_like_object at 0x7f23dd2aa730>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function validate_bucket_name at 0x7f23dd2a8268>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <botocore.utils.S3RegionRedirector object at 0x7f23dca90cf8>>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <bound method S3ArnParamHandler.handle_arn of <botocore.utils.S3ArnParamHandler object at 0x7f23de64c320>>
DEBUG:botocore.hooks:Event before-parameter-build.s3.PutObject: calling handler <function generate_idempotent_uuid at 0x7f23dd2a80d0>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function conditionally_calculate_md5 at 0x7f23dd407840>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function add_expect_header at 0x7f23dd2a8598>
DEBUG:botocore.handlers:Adding expect 100 continue header to request.
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <bound method S3RegionRedirector.set_request_url of <botocore.utils.S3RegionRedirector object at 0x7f23dca90cf8>>
DEBUG:botocore.hooks:Event before-call.s3.PutObject: calling handler <function inject_api_version_header_if_needed at 0x7f23dd2aa840>
DEBUG:botocore.endpoint:Making request for OperationModel(name=PutObject) with params: {'url_path': '/test/asdf', 'query_string': {}, 'method': 'PUT', 'headers': {'User-Agent': 'Boto3/1.16.50 Python/3.6.9 Linux/5.9.9-arch1-1 Botocore/1.19.50', 'Content-MD5': 'kS7IA7LOSeSlQQaNSVq1cA==', 'Expect': '100-continue'}, 'body': <_io.BytesIO object at 0x7f23de604d58>, 'url': 'http://localhost:9000/test/asdf', 'context': {'client_region': 'us-west-2', 'client_config': <botocore.config.Config object at 0x7f23dca1ac50>, 'has_streaming_input': True, 'auth_type': None, 'signing': {'bucket': 'test'}}}
DEBUG:botocore.hooks:Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f23dca1a7b8>>
DEBUG:botocore.hooks:Event choose-signer.s3.PutObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f23dcd28630>>
DEBUG:botocore.hooks:Event choose-signer.s3.PutObject: calling handler <function set_operation_specific_signer at 0x7f23dd2a3f28>
DEBUG:botocore.hooks:Event before-sign.s3.PutObject: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f23de64c390>>
DEBUG:botocore.auth:Calculating signature using v4 auth.
DEBUG:botocore.auth:CanonicalRequest:
PUT
/test/asdf

content-md5:kS7IA7LOSeSlQQaNSVq1cA==
host:localhost:9000
x-amz-content-sha256:f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b
x-amz-date:20210107T201922Z

content-md5;host;x-amz-content-sha256;x-amz-date
f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b
DEBUG:botocore.auth:StringToSign:
AWS4-HMAC-SHA256
20210107T201922Z
20210107/us-west-2/s3/aws4_request
3c0ffa3abf4e44bc5e689a45aca16e306b9931dd98644f49b88e5c8b9d187839
DEBUG:botocore.auth:Signature:
8afc30ae8f2db378456e9d7046f81d50bd00ecf496533c36190f64e45748404b
DEBUG:botocore.endpoint:Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=http://localhost:9000/test/asdf, headers={'User-Agent': b'Boto3/1.16.50 Python/3.6.9 Linux/5.9.9-arch1-1 Botocore/1.19.50', 'Content-MD5': b'kS7IA7LOSeSlQQaNSVq1cA==', 'Expect': b'100-continue', 'X-Amz-Date': b'20210107T201922Z', 'X-Amz-Content-SHA256': b'f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minio/20210107/us-west-2/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=8afc30ae8f2db378456e9d7046f81d50bd00ecf496533c36190f64e45748404b', 'Content-Length': '4'}>
DEBUG:botocore.awsrequest:Waiting for 100 Continue response.
DEBUG:botocore.awsrequest:100 Continue response seen, now sending request body.
DEBUG:urllib3.connectionpool:http://localhost:9000 "PUT /test/asdf HTTP/1.1" 200 None
WARNING:urllib3.connectionpool:Failed to parse headers (url=http://localhost:9000/test/asdf): [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nAccept-Ranges: bytes\r\nContent-Length: 0\r\nContent-Security-Policy: block-all-mixed-content\r\nETag: "912ec803b2ce49e4a541068d495ab570"\r\nServer: MinIO\r\nVary: Origin\r\nX-Amz-Request-Id: 16580CA3741548F9\r\nX-Xss-Protection: 1; mode=block\r\nDate: Thu, 07 Jan 2021 20:19:22 GMT\r\n\r\n'
Traceback (most recent call last):
  File "/home/rb/miniconda3/envs/det/lib/python3.6/site-packages/urllib3/connectionpool.py", line 441, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/home/rb/miniconda3/envs/det/lib/python3.6/site-packages/urllib3/util/response.py", line 71, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nAccept-Ranges: bytes\r\nContent-Length: 0\r\nContent-Security-Policy: block-all-mixed-content\r\nETag: "912ec803b2ce49e4a541068d495ab570"\r\nServer: MinIO\r\nVary: Origin\r\nX-Amz-Request-Id: 16580CA3741548F9\r\nX-Xss-Protection: 1; mode=block\r\nDate: Thu, 07 Jan 2021 20:19:22 GMT\r\n\r\n'
```

## Regression
Is this issue a regression? **Yes, I think**
If Yes, optionally please include minio version or commit id or PR# that caused this regression, if you have these details.
**I don't know**

## Your Environment

* Version used (`minio --version`): **`minio version RELEASE.2021-01-05T05-22-38Z`**
* Server setup and configuration: **`sudo MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=12341234 minio server /tmp`**
* Operating System and version (`uname -a`): archlinux

**Comment by harshavardhana** [comment]
This is bug in boto3 @rb-determined-ai - they have never fixed it.

**Comment by harshavardhana** [comment]
@vadmeste can you look at this? if order change in handlers added this issue back?

**Comment by harshavardhana** [comment]
A simplest most basic implementation of Go net/http shows this to be a client-side bug

```go
package main

import (
        "fmt"
        "io"
        "io/ioutil"
        "log"
        "net"
        "net/http"
        "runtime"
        "time"
)

func basicHandler(w http.ResponseWriter, r *http.Request) {
        switch r.Method {
        case http.MethodGet:
                <-r.Context().Done()
                fmt.Println(r.URL, r.Method)
        case http.MethodPut:
                fmt.Println("Number of routines", runtime.NumGoroutine())
                io.Copy(ioutil.Discard, r.Body)
                fmt.Println(r.URL, r.Method)
        case http.MethodPost:
                fmt.Println("Number of routines", runtime.NumGoroutine())
                <-r.Context().Done()
                fmt.Println(r.URL, r.Method)
        default:
                fmt.Fprintf(w, "Sorry, only POST methods are supported.")
        }
}

func main() {
        mux := http.NewServeMux()
        mux.HandleFunc("/", basicHandler)

        s := &http.Server{
                Addr:              ":4222",
                Handler:           mux,
                ReadHeaderTimeout: 2 * time.Second,
                IdleTimeout:       10 * time.Second,
                MaxHeaderBytes:    1 << 20,
                ConnState: func(c net.Conn, state http.ConnState) {
                        fmt.Println("ConnState", c, state)
                },
        }

        if err := s.ListenAndServe(); err != nil {
                log.Fatal(err)
        }
}
```

```
~ go run webhook.go
```

```
~ tp://localhost:4222/testbucket/asdf', 'context': {'client_region': 'us-east-1', 'client_config': <botocore.config.Config object at 0x7f4514b442b0>, 'has_streaming_input': True, 'auth_type': None, 'signing': {'bucket': 'testbucket'}}}
DEBUG:botocore.hooks:Event request-created.s3.PutObject: calling handler <bound method RequestSigner.handler of <botocore.signers.RequestSigner object at 0x7f4514b440d0>>
DEBUG:botocore.hooks:Event choose-signer.s3.PutObject: calling handler <bound method ClientCreator._default_s3_presign_to_sigv2 of <botocore.client.ClientCreator object at 0x7f451502aca0>>
DEBUG:botocore.hooks:Event choose-signer.s3.PutObject: calling handler <function set_operation_specific_signer at 0x7f451504d8b0>
DEBUG:botocore.hooks:Event before-sign.s3.PutObject: calling handler <bound method S3EndpointSetter.set_endpoint of <botocore.utils.S3EndpointSetter object at 0x7f4515eca100>>
DEBUG:botocore.auth:Calculating signature using v4 auth.
DEBUG:botocore.auth:CanonicalRequest:
PUT
/testbucket/asdf

content-md5:kS7IA7LOSeSlQQaNSVq1cA==
host:localhost:4222
x-amz-content-sha256:f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b
x-amz-date:20210108T054525Z

content-md5;host;x-amz-content-sha256;x-amz-date
f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b
DEBUG:botocore.auth:StringToSign:
AWS4-HMAC-SHA256
20210108T054525Z
20210108/us-east-1/s3/aws4_request
fb345018dd94165335f2ad78a7076768baa678e8e69098e413ea5c70a042a6f0
DEBUG:botocore.auth:Signature:
019048d2d3fe57728eff3400af57b2c4516496b8593ab06031cbc6b48335bd9f
DEBUG:botocore.endpoint:Sending http request: <AWSPreparedRequest stream_output=False, method=PUT, url=http://localhost:4222/testbucket/asdf, headers={'User-Agent': b'Boto3/1.14.32 Python/3.8.6 Linux/5.8.0-29-generic Botocore/1.16.4', 'Content-MD5': b'kS7IA7LOSeSlQQaNSVq1cA==', 'Expect': b'100-continue', 'X-Amz-Date': b'20210108T054525Z', 'X-Amz-Content-SHA256': b'f0e4c2f76c58916ec258f246851bea091d14d4247a2fc3e18694461b1816e13b', 'Authorization': b'AWS4-HMAC-SHA256 Credential=minio/20210108/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=019048d2d3fe57728eff3400af57b2c4516496b8593ab06031cbc6b48335bd9f', 'Content-Length': '4'}>
DEBUG:botocore.awsrequest:Waiting for 100 Continue response.
DEBUG:botocore.awsrequest:100 Continue response seen, now sending request body.
DEBUG:urllib3.connectionpool:http://localhost:4222 "PUT /testbucket/asdf HTTP/1.1" 200 None
WARNING:urllib3.connectionpool:Failed to parse headers (url=http://localhost:4222/testbucket/asdf): [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nDate: Fri, 08 Jan 2021 05:45:25 GMT\r\nContent-Length: 0\r\n\r\n'
Traceback (most recent call last):
  File "/home/harsha/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 465, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/home/harsha/.local/lib/python3.8/site-packages/urllib3/util/response.py", line 91, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nDate: Fri, 08 Jan 2021 05:45:25 GMT\r\nContent-Length: 0\r\n\r\n'
DEBUG:botocore.parsers:Response headers: {}
DEBUG:botocore.parsers:Response body:
b''
```

The error seems to be originating in urllib3 client-side parsing.

**Comment by harshavardhana** [comment]
So ended up writing a much simpler tool with just urllib3

```py
import urllib3
import logging

if __name__ == "__main__":
    logging.basicConfig(level="DEBUG")

    http = urllib3.PoolManager()

    with open("asdf", "w") as f:
        f.write("asdf")

    # This line finishes, but seems to cause the next upload to hang.
    http.urlopen('PUT', 'http://localhost:4222', body=b'')

    # This line prints.
    logging.debug("-------------------------------------")

    # This line prints an error and hangs.
    http.urlopen('PUT', 'http://localhost:4222', body=b'asdf')
```

No issues here
```
~  python test.py 
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): localhost:4222
DEBUG:urllib3.connectionpool:http://localhost:4222 "PUT / HTTP/1.1" 200 0
DEBUG:root:-------------------------------------
DEBUG:urllib3.connectionpool:http://localhost:4222 "PUT / HTTP/1.1" 200 0
~ 
```

```go
package main

import (
        "fmt"
        "io"
        "log"
        "net/http"
        "os"
        "time"
)

func basicHandler(w http.ResponseWriter, r *http.Request) {
        switch r.Method {
        case http.MethodPut:
                io.Copy(os.Stdout, r.Body)
                fmt.Println()
                fmt.Println(r.URL, r.Method)
        default:
                fmt.Fprintf(w, "Sorry, only PUT methods are supported.")
        }
}

func main() {
        mux := http.NewServeMux()
        mux.HandleFunc("/", basicHandler)

        s := &http.Server{
                Addr:              ":4222",
                Handler:           mux,
                ReadHeaderTimeout: 2 * time.Second,
                IdleTimeout:       10 * time.Second,
                MaxHeaderBytes:    1 << 20,
        }

        if err := s.ListenAndServe(); err != nil {
                log.Fatal(err)
        }
}
```

So looks like this is basically boto3 doing something funky with urllib3 pool management leading to bugs.

**Comment by harshavardhana** [comment]
Closing this as not our bug, please report this to boto3 upstream.

**Comment by rb-determined-ai** [comment]
Ok, sorry for costing you a bunch of time.

I'm happy to give another shot at having boto3 fix this.  Can you explain to me quite what your last code example shows?  Is the idea that, with that golang server (known valid server), the boto3 code fails but the similar urllib3 code does not fail?

Just want to make sure I don't have my wires crossed before I post a bug to boto3.

**Comment by harshavardhana** [comment]
> Ok, sorry for costing you a bunch of time.
> 
> I'm happy to give another shot at having boto3 fix this. Can you explain to me quite what your last code example shows? Is the idea that, with that golang server (known valid server), the boto3 code fails but the similar urllib3 code does not fail?
> 
> Just want to make sure I don't have my wires crossed before I post a bug to boto3.

Mainly urllib3 doesn't have any issue, because even minio-py uses the same library and there are no issues.

It is boto3 that is doing something funky here with network connection which messes up urllib3 parser.

**Comment by harshavardhana** [comment]
Btw don't waste your time with boto3 we followed up for multiple years and it has never been merged.

FWIW you can use minio-py and it is feature par with boto3 if all you are using is S3 APIs
