### ISSUE TITLE
Distributed docker cluster container reboot loop [segmentation violation code=0x1]

### ISSUE THREAD

**Issue by riazarbi** [minio/minio#11442]
## Expected Behavior
I expect the docker containers running minio nodes in distributed mode to remain up until I restart them

## Current Behavior
- We are running a 4 node cluster in an air-gapped environment via docker. 
- The cluster intializes and runs happily - the overall cluster is stable.
- But each node's minio container restarts randomly after 0-10 minutes, resulting in dropped connections if that node is currently servicing a request.

## Possible Solution
It looks like an error in the erasure coding go routine. 

## Steps to Reproduce (for bugs)
We cannot reproduce as this is a live system, but include our logs and trace:

Sample logs from a container immediately prior to reboot

```
Host: storage-41:9000
UserAgent: aws-sdk-ruby3/3.104.3 ruby/2.6.6 x86_64-linux aws-sdk-s3/1.76.0
Error: Marking http://storage-31:9000/minio/peer/v12 temporary offline; caused by Post "http://storage-31:9000/minio/peer/v12/cyclebloom?": dial tcp 172.29.100.56:9000: connect: connection refused (*fmt.wrapError)
       5: cmd/rest/client.go:123:rest.(*Client).Call()
       4: cmd/peer-rest-client.go:68:cmd.(*peerRESTClient).callWithContext()
       3: cmd/peer-rest-client.go:471:cmd.(*peerRESTClient).cycleServerBloomFilter()
       2: cmd/notification.go:595:cmd.(*NotificationSys).findEarliestCleanBloomFilter.func1()
       1: pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()

API: ListObjectsV2(bucket=ds-k3s-logs)
Time: 12:38:22 UTC 02/04/2021
DeploymentID: 4be4a7b5-d1f1-4f47-9046-381dd1cb4ac0
RequestID: 16608BBB1DAA285F
RemoteHost: 10.42.1.1
Host: storage-41:9000
UserAgent: aws-sdk-ruby3/3.104.3 ruby/2.6.6 x86_64-linux aws-sdk-s3/1.76.0
Error: Post "http://storage-31:9000/minio/peer/v12/cyclebloom?": dial tcp 172.29.100.56:9000: connect: connection refused (*rest.NetworkError)
       2: cmd/notification.go:604:cmd.(*NotificationSys).findEarliestCleanBloomFilter.func1()
       1: pkg/sync/errgroup/errgroup.go:55:errgroup.(*Group).Go.func1()
Client http://storage-31:9000/minio/storage/minio/disk3/v26 online
Client http://storage-31:9000/minio/peer/v12 online
Client http://storage-31:9000/minio/lock/v5 online
Client http://storage-31:9000/minio/storage/minio/disk7/v26 online
Client http://storage-31:9000/minio/storage/minio/disk2/v26 online
Client http://storage-31:9000/minio/storage/minio/disk4/v26 online
Client http://storage-31:9000/minio/storage/minio/disk8/v26 online
Client http://storage-31:9000/minio/storage/minio/disk1/v26 online
Client http://storage-31:9000/minio/storage/minio/disk6/v26 online
Client http://storage-31:9000/minio/storage/minio/disk5/v26 online
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x18a3afb]

goroutine 861923 [running]:
github.com/minio/minio/cmd.erasureObjects.crawlAndGetDataUsage.func2(0xc007692b20, 0xc004125700, 0x10, 0x10, 0xc002543aa0, 0x22a6640, 0xc007ab9780, 0x10, 0x4, 0x1, ...)
	github.com/minio/minio/cmd/erasure.go:417 +0x59b
created by github.com/minio/minio/cmd.erasureObjects.crawlAndGetDataUsage
	github.com/minio/minio/cmd/erasure.go:384 +0x837
```

Sample trace immediately prior to reboot:

```
12:39:11.529 [200 OK] s3.PutObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-epi-widgets-city-map-plot-city-ae8f6e8c_airflow-workers_base-69e6f921a4efd60dc1942046fe97254c505841536766a7c408db23a47b92a4d5.log/20201207T16:00:00Z_0.gz 10.42.1.1         368.584ms    ↑ 5.4 KiB ↓ 230 B
12:39:14.932 [200 OK] s3.ListObjectsV2 lake.REDACTED/ds-k3s-logs?list-type=2&max-keys=1&prefix=logs%2F%24%7Btag%7D%2F  10.42.1.1         29.894ms     ↑ 230 B ↓ 825 B
12:39:14.985 [200 OK] s3.HeadBucket lake.REDACTED/ds-k3s-logs 10.42.1.1         6.452ms      ↑ 229 B ↓ 189 B
12:39:16.924 [404 Not Found] s3.HeadObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-epi-widgets-city-map-plot-city-db5f6344_airflow-workers_base-8ac95571b495f45109b79ad3ec3515bef468568a497537f98c634be3e515e4b4.log/20201207T16:00:00Z_0.gz 10.42.1.1         38.468ms     ↑ 229 B ↓ 196 B
12:39:16.977 [200 OK] s3.PutObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-epi-widgets-city-map-plot-city-db5f6344_airflow-workers_base-8ac95571b495f45109b79ad3ec3515bef468568a497537f98c634be3e515e4b4.log/20201207T16:00:00Z_0.gz 10.42.1.1         344.067ms    ↑ 5.4 KiB ↓ 230 B
12:39:20.146 [200 OK] s3.ListObjectsV2 lake.REDACTED/ds-k3s-logs?list-type=2&max-keys=1&prefix=logs%2F%24%7Btag%7D%2F  10.42.1.1         28.622ms     ↑ 230 B ↓ 825 B
12:39:20.183 [200 OK] s3.HeadBucket lake.REDACTED/ds-k3s-logs 10.42.1.1         8.382ms      ↑ 229 B ↓ 189 B
12:39:22.355 [404 Not Found] s3.HeadObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-epi-widgets-city-hotspot-map-plot-city-all-dc0a8722_airflow-workers_base-2bbfd8407ac4b96e356b6a6ec2a8e9594ce171776a3be003cb3b9908ff94fef1.log/20201207T16:00:00Z_0.gz 10.42.1.1         39.103ms     ↑ 229 B ↓ 196 B
12:39:22.412 [200 OK] s3.PutObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-epi-widgets-city-hotspot-map-plot-city-all-dc0a8722_airflow-workers_base-2bbfd8407ac4b96e356b6a6ec2a8e9594ce171776a3be003cb3b9908ff94fef1.log/20201207T16:00:00Z_0.gz 10.42.1.1         317.545ms    ↑ 16 KiB ↓ 230 B
12:39:25.264 [200 OK] s3.ListObjectsV2 lake.REDACTED/ds-k3s-logs?list-type=2&max-keys=1&prefix=logs%2F%24%7Btag%7D%2F  10.42.1.1         92.71ms      ↑ 230 B ↓ 825 B
12:39:25.369 [200 OK] s3.HeadBucket lake.REDACTED/ds-k3s-logs 10.42.1.1         5.065ms      ↑ 229 B ↓ 189 B
12:39:28.264 [404 Not Found] s3.HeadObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-epi-widgets-city-map-plot-city-66c04910_airflow-workers_base-5974b78105b95faef17d9a4ad07a1bc4b3e44b132c125f7539981548faa4bc02.log/20201207T16:00:00Z_0.gz 10.42.1.1         30.259ms     ↑ 229 B ↓ 196 B
12:39:28.302 [200 OK] s3.PutObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-epi-widgets-city-map-plot-city-66c04910_airflow-workers_base-5974b78105b95faef17d9a4ad07a1bc4b3e44b132c125f7539981548faa4bc02.log/20201207T16:00:00Z_0.gz 10.42.1.1         156.77ms     ↑ 5.4 KiB ↓ 230 B
12:39:30.519 [200 OK] s3.ListObjectsV2 lake.REDACTED/ds-k3s-logs?list-type=2&max-keys=1&prefix=logs%2F%24%7Btag%7D%2F  10.42.1.1         36.882ms     ↑ 230 B ↓ 825 B
12:39:30.870 [200 OK] s3.HeadBucket lake.REDACTED/ds-k3s-logs 10.42.1.1         4.562ms      ↑ 229 B ↓ 189 B
12:39:33.480 [404 Not Found] s3.HeadObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-hr-widgets-hr-latest-values-energy-and-climate-change-78a05883_airflow-workers_base-8bab77ebfb2409300cf61c51939d096fa9ef7307d617de62cf82bc337e0e90ae.log/20201207T16:00:00Z_0.gz 10.42.1.1         62.706ms     ↑ 229 B ↓ 196 B
12:39:33.553 [200 OK] s3.PutObject lake.REDACTED/ds-k3s-logs/logs/unmatched.kubernetes.var.log.containers.covid-19-hr-widgets-hr-latest-values-energy-and-climate-change-78a05883_airflow-workers_base-8bab77ebfb2409300cf61c51939d096fa9ef7307d617de62cf82bc337e0e90ae.log/20201207T16:00:00Z_0.gz 10.42.1.1         302.303ms    ↑ 4.2 KiB ↓ 230 B
12:39:35.809 [200 OK] s3.ListObjectsV2 lake.REDACTED/ds-k3s-logs?list-type=2&max-keys=1&prefix=logs%2F%24%7Btag%7D%2F  10.42.1.1         50.759ms     ↑ 230 B ↓ 825 B
12:39:35.887 [200 OK] s3.HeadBucket lake.REDACTED/ds-k3s-logs 10.42.1.1         3.767ms      ↑ 229 B ↓ 189 B
^Cmc: <ERROR> Unable to listen to http trace. Canceling upon user request.

```

## Context
The issue is only noticeable to the end user if they happen to be routed to a node that goes down for reboot while serving data.

This impacts our ability to transfer large datasets to and from processing workflows.

## Regression
Maybe.
We notices this after upgrading to minio version RELEASE.2021-02-01T22-56-52Z

## Your Environment

Minio server version: 
```
ubuntu-admin@storage-41:~$ sudo docker exec -it minio-lake minio --version
minio version RELEASE.2021-02-01T22-56-52Z
```

Host OS:
```buntu-admin@storage-41:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
ubuntu-admin@storage-41
```

Sample docker run command:
```
sudo docker run \
-d \
--restart always \
--name minio-lake \
-p 9000:9000 \
-v /minio/disk1:/minio/disk1 \
-v /minio/disk2:/minio/disk2 \
-v /minio/disk3:/minio/disk3 \
-v /minio/disk4:/minio/disk4 \
-v /minio/disk5:/minio/disk5 \
-v /minio/disk6:/minio/disk6 \
-v /minio/disk7:/minio/disk7 \
-v /minio/disk8:/minio/disk8 \
-v /etc/hosts:/etc/hosts:ro \
-e MINIO_ACCESS_KEY=REDACTED \
-e MINIO_SECRET_KEY=REDACTED \
minio/minio \
server \
http://storage-{1...4}1:9000/minio/disk{1...8}
```

User traffic load balancing:

- The nodes are on separate machines and talk to each other via raw IP addresses. 
- User traffic routes to a traefik proxy running on k3s which routes traffic to one of the nodes in equally weighted fashion. This arrangement has worked with no issues for several months prior to emergence of the bug.

**Comment by klauspost** [comment]
Should have been fixed by https://github.com/minio/minio/pull/11419 which will be in the next release.

First error causes the second one.
