### ISSUE TITLE
Multipart download fails on some content

### ISSUE THREAD

**Issue by Druckles** [minio/minio#11824]
## Expected Behavior

I have a ZIP file in a folder:

```
|- repository/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b
`- test.zip
```

Downloading the entire folder using the AWS SDK for Java has worked flawlessly till now, i.e.

```
transferManager.downloadDirectory("bucket", "repository/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b", tempDir)
                .waitForCompletion();
```

The folder is downloaded with the contained file and no exception is thrown.

## Current Behavior

However, since RELEASE.2021-01-30T00-20-58Z, MinIO appears to stop sending the entire file:

```
Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:54)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 35,932,379; received: 5,242,880)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:47)
	... 5 more
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 35,932,379; received: 5,242,880)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:71)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:36)
	... 4 more
```

The MinIO trace logs (using `mc admin trace`):

```
11:14:38.008 [200 OK] s3.ListObjectsV1 192.168.59.101:9000/bucket/?prefix=reposito
ry%2F8e%2F9f123eb2-7bb2-470d-bfbf-48b5104f905b&delimiter=%2F&encoding-type=url
192.168.59.99     403µs       ↑ 153 B ↓ 658 B
11:14:38.083 [200 OK] s3.ListObjectsV1 192.168.59.101:9000/bucket/?prefix=reposito
ry%2F8e%2F9f123eb2-7bb2-470d-bfbf-48b5104f905b%2F&delimiter=%2F&encoding-type=ur
l  192.168.59.99     912µs       ↑ 153 B ↓ 937 B
11:14:38.100 [200 OK] s3.HeadObject 192.168.59.101:9000/bucket/repository/8e/9f123
eb2-7bb2-470d-bfbf-48b5104f905b/test.zip 192.168.59.99     611µs       ↑ 15
3 B ↓ 323 B
11:14:38.106 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168
.59.99     523µs       ↑ 153 B ↓ 401 B
11:14:38.122 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168
.59.99     728µs       ↑ 153 B ↓ 401 B
11:14:38.131 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168
.59.99     970µs       ↑ 153 B ↓ 401 B
11:14:38.141 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=2  192.168
.59.99     548µs       ↑ 153 B ↓ 401 B
11:14:38.147 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=3  192.168
.59.99     1.003ms      ↑ 153 B ↓ 401 B
11:14:38.161 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=4  192.168
.59.99     728µs       ↑ 153 B ↓ 401 B
11:14:38.171 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=5  192.168
.59.99     581µs       ↑ 153 B ↓ 401 B
11:14:38.177 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=6  192.168
.59.99     798µs       ↑ 153 B ↓ 401 B
11:14:38.183 [206 Partial Content] s3.HeadObject 192.168.59.101:9000/bucket/reposi
tory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=7  192.168
.59.99     411µs       ↑ 153 B ↓ 401 B
11:14:38.135 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=1  192.168.
59.99     113.301ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.143 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=2  192.168.
59.99     204.809ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.149 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=3  192.168.
59.99     214.809ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.297 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=5  192.168.
59.99     829.543ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.289 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=4  192.168.
59.99     839.761ms    ↑ 153 B ↓ 5.0 MiB
11:14:38.293 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=6  192.168.
59.99     1.306906s    ↑ 153 B ↓ 5.0 MiB
11:14:38.299 [206 Partial Content] s3.GetObject 192.168.59.101:9000/bucket/reposit
ory/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b/test.zip?partNumber=7  192.168.
59.99     1.308151s    ↑ 153 B ↓ 4.3 MiB
```

There were no errors printed in the console.

## Steps to Reproduce (for bugs)

Here is a minimum example using the AWS SDK for Java:

```
package com.tts.premature_end_content;

import com.amazonaws.auth.AWSStaticCredentialsProvider;
import com.amazonaws.auth.BasicAWSCredentials;
import com.amazonaws.client.builder.AwsClientBuilder;
import com.amazonaws.regions.Regions;
import com.amazonaws.services.s3.AmazonS3Client;
import com.amazonaws.services.s3.transfer.TransferManagerBuilder;

import java.io.IOException;
import java.nio.file.Files;

public class Test {
    public static void main(String[] args) throws InterruptedException, IOException {
        var transferManager = TransferManagerBuilder.standard()
                .withS3Client(AmazonS3Client.builder()
                        .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://192.168.59.101:9000", Regions.DEFAULT_REGION.getName()))
                        .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials("minio", "minio123")))
                        .build()
                )
                .build();
        var tempFile = Files.createTempDirectory("test").toFile();
        var download = transferManager.downloadDirectory("ttps", "repository/8e/9f123eb2-7bb2-470d-bfbf-48b5104f905b",
                tempFile);
        System.out.println("Waiting for completion...");
        download.waitForCompletion();
        System.out.println("Finished!");
    }
}
```

*However*, it is only reproducible with particular files. I have tried to create a minimal ZIP file that reproduces the problem but it appears to be dependent on the combination of files contained. Here are some of the features of the ZIP file that fails. It:

* is 35,091 KB compressed
* is 43,945 KB uncompressed
* contains 1,847 files
* contains files of sizes between 80 B and 7 MB

It still doesn't work after removing many of the files, but it's arbitrary as to which and sometimes removing a file is ok if other files are removed with it. For example, I made a smaller version that also fails which:

* is 16,390 KB compressed
* is 16,827 KB uncompressed
* contains 899 files
* contains files of sizes between 1 KB and 5.2 MB

Other things I've tried:

* Downloading the individual ZIP (Works)
* Downloading the unzipped contents in a directory (Works)
* Renaming the file/extension (Fails, i.e. filename is irrelevant)
* Using different prefixes (Fails, i.e. prefix is irrelevant)
* Rezipping the contents, uploading them through MinIO & downloading the directory again (Fails, i.e. not a corrupt ZIP)
* Renaming the contents, e.g. to 001, 002, .. 899 (Fails, i.e. filenames unimportant)

Unfortunately I can't send the file as it contains copyrighted material, e.g. music files. The files inside are pretty arbitrary though, as they're only used for test purposes.

## Regression

Yes, it first occurs in RELEASE.2021-01-30T00-20-58Z. There was no problem in RELEASE.2021-01-16T02-19-44Z and earlier. 

## Your Environment

* MinIO version as above
* MinIO running in Windows standalone and in a Linux VM (Ubuntu) in a Docker container  
For some reason it does appear to work when MinIO was running as a Windows Service, but there may be another reason for that.
* Client/code running in Windows 10 19041.867
* AWS SDK versions 1.11.710 and 1.11.975 (no difference)

**Comment by klauspost** [comment]
@Druckles 

* Are there any errors printed in any of the server logs?
* Your setup, commandline used, etc.
* Is all AV checking/HTTP snooping "cloud protection" software disabled?  << This is my primary suspect.
* Does it fail when client is downloading from another machine?
* Do you use encryption and/or compression on the server?
* Does it work when downloading with `mc` client?

**Comment by Druckles** [comment]
Sorry, I forgot to add the logs and have updated the above post. There was nothing untoward in any of them.

If you mean MinIO setup, mine is run using Docker Compose in a Linux VM:

```
  minio:
    image: minio/minio:RELEASE.2021-01-30T00-20-58Z
    volumes:
      - data:/data
    networks:
      - internal
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data/miniostore
```

But as mentioned above, it's also run standalone and as a service in Windows.

* Just disabled all antivirus and protection software and reran the above example. It still failed.
* It fails when downloading from the same machine (Windows -> Windows) and when downloading from a virtual machine (Linux VM -> Windows). This is the case for at least 3 different machines. I don't have the ability to test it over two physically different machines, but can't imagine it being any different from a connection to a virtual machine.
* There's no compression happening at all and no encryption on the MinIO server; it fails regardless of whether MinIO is behind a load balancer or not, SSL or no.
* If you send me an appropriate `mc` command, I am happy to run it. Downloading the file individually using the MinIO web UI obviously works fine.

**Comment by harshavardhana** [comment]
@Druckles please upgrade and let us know.

**Comment by Druckles** [comment]
Just pulled the latest image I could find (17.3.21 2:33) and ran my test again. The same error is thrown:

![image](https://user-images.githubusercontent.com/9626712/111673702-88781e00-881b-11eb-8dd8-8e2acdd5f64b.png)

```
Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:54)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 35,932,379; received: 5,242,880)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:47)
	... 5 more
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 35,932,379; received: 5,242,880)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:71)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:36)
	... 4 more
```

**Comment by harshavardhana** [comment]
> Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.

how do you know the part numbers here? @Druckles

**Comment by Druckles** [comment]
I'm sorry, I'm not sure I entirely understand the question. This is the error from the AWS SDK. I don't know which part exactly it's referring to. It is strange that it expects 36 MB (the full size of the document) but only receives 5 MB (the size of the part).

**Comment by harshavardhana** [comment]
> I'm sorry, I'm not sure I entirely understand the question. This is the error from the AWS SDK. I don't know which part exactly it's referring to. It is strange that it expects 36 MB (the full size of the document) but only receives 5 MB (the size of the part).

Because its trying to download part by part.

**Comment by mohitt01** [comment]
I have been facing a similar issue with the aws-sdk. On drilling down, I believe I have identified where exactly things start failing
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L540

Background:
The aws-sdk for java has a component called `TransferManager`, which automatically parallelises uploads larger than a configured size (default: 16MB). I've been able to replicate the issue with a random 32MB file and using the sdk to upload it and download it back.

Steps to reproduce:
1. Generate a 16MB file with random text
`openssl rand -out sample16.txt -base64 $(( 2**24 * 3/4 ))`
2. Run the below piece of code with a recent version of aws-java-sdk-s3
I used `group: 'com.amazonaws', name: 'aws-java-sdk-s3', version: '1.11.988'` for the test
```
public class ParallelDownloadTest {
    private static final long MB = 1024 * 1024;

    public static void main(String[] args) throws Exception {
        AmazonS3 client = amazons3();
        TransferManager transferManager = TransferManagerBuilder.standard()
                .withS3Client(client)
                .withMultipartUploadThreshold(10 * MB)
                .withMinimumUploadPartSize(5 * MB)
                .build();

        String filename = "sample16.txt";
        Upload upload = transferManager.upload("testbucket", filename, Path.of(filename).toFile());
        upload.waitForCompletion();

        Download download = transferManager.download("testbucket", filename, Path.of(filename + ".downloaded").toFile());
        download.waitForCompletion();
    }

    private static AmazonS3 amazons3() {
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");
        return AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9000", Regions.US_EAST_1.name()))
                .withPathStyleAccessEnabled(true)
                .withClientConfiguration(clientConfiguration)
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(
                        "<ACCESS KEY>",
                        "<SECRET KEY>"
                )))
                .build();
    }
}
```


Output:
Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:54)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)

	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:47)
	... 5 more
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)

	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:71)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:36)
	... 4 more

> Task :core:ParallelDownloadTest.main() FAILED

Execution failed for task ':core:ParallelDownloadTest.main()'.
> Build cancelled while executing task ':core:ParallelDownloadTest.main()'

**Comment by mohitt01** [comment]
I have been facing a similar issue with the aws-sdk. On drilling down, I believe I have identified where exactly things start failing

Background:
The aws-sdk for java has a component called `TransferManager`, which automatically parallelises uploads larger than a configured size (default: 16MB). I've been able to replicate the issue with a random 32MB file and using the sdk to upload it and download it back.

Steps to reproduce:
1. Generate a 16MB file with random text
`openssl rand -out sample16.txt -base64 $(( 2**24 * 3/4 ))`
2. Run the below piece of code with a recent version of aws-java-sdk-s3
I used `group: 'com.amazonaws', name: 'aws-java-sdk-s3', version: '1.11.988'` for the test
```
public class ParallelDownloadTest {
    private static final long MB = 1024 * 1024;

    public static void main(String[] args) throws Exception {
        AmazonS3 client = amazons3();
        TransferManager transferManager = TransferManagerBuilder.standard()
                .withS3Client(client)
                .withMultipartUploadThreshold(10 * MB)
                .withMinimumUploadPartSize(5 * MB)
                .build();

        String filename = "sample16.txt";
        Upload upload = transferManager.upload("testbucket", filename, Path.of(filename).toFile());
        upload.waitForCompletion();

        Download download = transferManager.download("testbucket", filename, Path.of(filename + ".downloaded").toFile());
        download.waitForCompletion();
    }

    private static AmazonS3 amazons3() {
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");
        return AmazonS3ClientBuilder.standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://localhost:9000", Regions.US_EAST_1.name()))
                .withPathStyleAccessEnabled(true)
                .withClientConfiguration(clientConfiguration)
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(
                        "<ACCESS KEY>",
                        "<SECRET KEY>"
                )))
                .build();
    }
}
```


Output:
```
Exception in thread "main" com.amazonaws.SdkClientException: Unable to complete multipart download. Individual part download failed.
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:54)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:29)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
Caused by: java.util.concurrent.ExecutionException: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)

	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.amazonaws.services.s3.transfer.internal.CompleteMultipartDownload.call(CompleteMultipartDownload.java:47)
	... 5 more
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)
Caused by: org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 17,039,360; received: 5,242,880)

	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:178)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.event.ProgressInputStream.read(ProgressInputStream.java:180)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.util.LengthCheckInputStream.read(LengthCheckInputStream.java:107)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at com.amazonaws.services.s3.internal.S3AbortableInputStream.read(S3AbortableInputStream.java:125)
	at com.amazonaws.internal.SdkFilterInputStream.read(SdkFilterInputStream.java:90)
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:71)
	at com.amazonaws.services.s3.transfer.internal.DownloadS3ObjectCallable.call(DownloadS3ObjectCallable.java:36)
	... 4 more

> Task :core:ParallelDownloadTest.main() FAILED

Execution failed for task ':core:ParallelDownloadTest.main()'.
> Build cancelled while executing task ':core:ParallelDownloadTest.main()'
```

Problem:
This is how the sdk gets the part size. The minio server responds with a Content-Length of the full file, even when querying for a specific part number.
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/ServiceUtils.java#L540

Also able to replicate this via CLI:
`aws --endpoint-url http://localhost:9000 s3api head-object --bucket hermes --key sample16.txt --part-number 1`
```
{
    "AcceptRanges": "bytes",
    "LastModified": "2021-04-01T12:47:44+00:00",
    "ContentLength": 17039360,
    "ETag": "\"9a5dba42aabe4be0cd45474b844bd019-4\"",
    "ContentType": "text/plain",
    "Metadata": {},
    "PartsCount": 4
}
```
`aws --endpoint-url http://localhost:9000 s3api head-object --bucket testbucket --key sample16.txt --part-number 2`
```
{
    "AcceptRanges": "bytes",
    "LastModified": "2021-04-01T12:47:44+00:00",
    "ContentLength": 17039360,
    "ETag": "\"9a5dba42aabe4be0cd45474b844bd019-4\"",
    "ContentType": "text/plain",
    "Metadata": {},
    "PartsCount": 4
}
```

**Comment by harshavardhana** [comment]
are you using single drive mode here? @mohitt01
