### ISSUE TITLE
S3 error

### ISSUE THREAD

**Issue by ashishdocforce** [minio/minio#11904]
I get this error while connecting throught the node app. It doesn't stating any messages so I am not able to understand what is going wrong. minio server is working properly with S3. just can't able to handle it through my app. 

```
error S3Error
    at Object.parseError (/app/server/node_modules/minio/dist/main/xml-parsers.js:79:11)
    at /app/server/node_modules/minio/dist/main/transformers.js:156:22
    at DestroyableTransform._flush (/app/server/node_modules/minio/dist/main/transformers.js:80:10)
    at DestroyableTransform.prefinish (/app/server/node_modules/readable-stream/lib/_stream_transform.js:138:10)
    at DestroyableTransform.emit (events.js:314:20)
    at DestroyableTransform.EventEmitter.emit (domain.js:483:12)
    at prefinish (/app/server/node_modules/readable-stream/lib/_stream_writable.js:619:14)
    at finishMaybe (/app/server/node_modules/readable-stream/lib/_stream_writable.js:627:5)
    at endWritable (/app/server/node_modules/readable-stream/lib/_stream_writable.js:638:3)
    at DestroyableTransform.Writable.end (/app/server/node_modules/readable-stream/lib/_stream_writable.js:594:41)
    at IncomingMessage.onend (_stream_readable.js:683:10)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
    at IncomingMessage.EventEmitter.emit (domain.js:483:12)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  amzRequestid: null,
  amzId2: null,
  amzBucketRegion: null
}
```

Is there any other environment variables I will needed to add for minio? My current configuration is as below:

```
const client = new Client({
  endPoint: process.env.STORAGE_ENDPOINT,
  port: process.env.STORAGE_PORT || 9000,
  useSSL: false,
  accessKey: process.env.STORAGE_ACCESS_KEY,
  secretKey: process.env.STORAGE_SECRET_KEY,
});
```

And my environment variables:

export STORAGE_ENDPOINT=localhost
export STORAGE_PORT=9000
export STORAGE_ACCESS_KEY=AWS_ACCESS_KEY
export STORAGE_SECRET_KEY=AWS_SECRET_KEY

**Comment by harshavardhana** [comment]
@ashishdocforce can you provide `mc admin trace -v` output?

**Comment by ashishdocforce** [comment]
> @ashishdocforce can you provide `mc admin trace -v` output?

```
NAME:
  mc admin trace - show http trace for MinIO server

USAGE:
  mc admin trace [FLAGS] TARGET

FLAGS:
  --verbose, -v                 print verbose trace
  --all, -a                     trace all traffic (includes internode traffic from MinIO cluster)
  --status-code value           trace only matching status code
  --method value                trace only matching HTTP method
  --funcname value              trace only matching func name
  --path value                  trace only matching path
  --errors, -e                  trace only failed requests
  --config-dir value, -C value  path to configuration folder (default: "/home/ubuntu/.mc")
  --quiet, -q                   disable progress bar display
  --no-color                    disable color theme
  --json                        enable JSON lines formatted output
  --debug                       enable debug output
  --insecure                    disable SSL certificate verification
  --help, -h                    show help
  
EXAMPLES:
  1. Show verbose console trace for MinIO server
     $ mc admin trace -v -a myminio

  2. Show trace only for failed requests for MinIO server
    $ mc admin trace -v -e myminio

  3. Show verbose console trace for requests with '503' status code
    $ mc admin trace -v --status-code 503 myminio

  4. Show console trace for a specific path
    $ mc admin trace --path my-bucket/my-prefix/ myminio

  5. Show console trace for requests with '404' and '503' status code
    $ mc admin trace --status-code 404 --status-code 503 myminio

```

**Comment by ashishdocforce** [comment]
> @ashishdocforce can you provide `mc admin trace -v` output?

@harshavardhana  Above is the output of your command. and if I'm providing alias at the end like `mc admin trace -v minio-server`  It does nothing just process on hold and no output.

**Comment by nitisht** [comment]
If it does nothing, it means there are no requests reaching the server @ashishdocforce . This is something on client side, we can’t able to help you much here.

**Comment by ashishdocforce** [comment]
> If it does nothing, it means there are no requests reaching the server @ashishdocforce . This is something on client side, we can’t able to help you much here.

But if that is the case, It should throw minio error instead of s3 error right?

**Comment by harshavardhana** [comment]
> But if that is the case, It should throw minio error instead of s3 error right?

MinIO is an S3 compatible API implementation, there is no connection between your app and server - so an error on client side.

**Comment by ashishdocforce** [comment]
@harshavardhana But these configurations from client is enough to connect through s3?

```
const client = new Client({
  endPoint: process.env.STORAGE_ENDPOINT,
  port: process.env.STORAGE_PORT || 9000,
  useSSL: false,
  accessKey: process.env.STORAGE_ACCESS_KEY,
  secretKey: process.env.STORAGE_SECRET_KEY,
});

```
Or any additional key needs to be passed?
