### ISSUE TITLE
Minio server cras with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by gedOHub** [minio/minio#11946]
Server crashes from time to time

## Current Behavior
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ac832]

goroutine 1313994 [running]:
io.(*nopCloser).Read(0xc00c26b090, 0xc0013c8000, 0x2000, 0x2000, 0x40db9b, 0xc00c26b080, 0x40a6bf)
        <autogenerated>:1 +0x32
io.discard.ReadFrom(0x7f24c01823a0, 0xc00c26b090, 0x1d141e0, 0x1, 0x7f24c030af08)
        io/io.go:598 +0x95
io.copyBuffer(0x279d760, 0x3494ec0, 0x7f24c01823a0, 0xc00c26b090, 0x0, 0x0, 0x0, 0x0, 0xc00c26b001, 0xc003a8bd40)
        io/io.go:409 +0x357
io.Copy(...)
        io/io.go:382
github.com/minio/minio/cmd/http.DrainBody(0x27b5778, 0xc00c26b090)
        github.com/minio/minio/cmd/http/close.go:40 +0xdd
github.com/minio/minio/cmd.(*storageRESTClient).CreateFile(0xc001efea00, 0x27cc988, 0xc00003e090, 0x1f42bbe, 0xe, 0xc0092991d0, 0x50, 0xcb3, 0x279ac60, 0xc0161cc8a0, ...)
        github.com/minio/minio/cmd/storage-rest-client.go:346 +0x53c
github.com/minio/minio/cmd.newStreamingBitrotWriter.func1(0xc93, 0x15556, 0x27d15c0, 0xc005033110, 0xc0161cc8a0, 0x27f3658, 0xc001efea00, 0x1f42bbe, 0xe, 0xc0092991d0, ...)
        github.com/minio/minio/cmd/bitrot-streaming.go:85 +0x104
created by github.com/minio/minio/cmd.newStreamingBitrotWriter
        github.com/minio/minio/cmd/bitrot-streaming.go:79 +0x2bd

```

## Steps to Reproduce (for bugs)
Run warp mixed test

## Your Environment

* Version used `minio version RELEASE.2021-03-26T00-00-41Z`
* Server setup and configuration:
```bash
4 x (2 CPU, 8GB RAM, 2 disks (1st - /, 2nd - /minio)
MINIO_VOLUMES="http://minio-server-{1...4}/minio/disk{1...16}"
```
* Operating System and version `Linux minio-server-3 4.19.0-14-cloud-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux`

**Comment by vadmeste** [comment]
@gedOHub this should be fixed with this PR, https://github.com/minio/minio/pull/11939

You need to test with master for now.
