### ISSUE TITLE
Closing the page during the upload process causes the program to terminate

### ISSUE THREAD

**Issue by liuaiyuan** [minio/minio#11958]
## Current Behavior
```shell

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ac832]

goroutine 5159 [running]:
io.(*nopCloser).Read(0xc003a518a0, 0xc0002ca000, 0x2000, 0x2000, 0x2797720, 0xc000070110, 0x40a6bf)
        <autogenerated>:1 +0x32
io.discard.ReadFrom(0x7f5cab2f47f8, 0xc003a518a0, 0x1d141e0, 0x2797701, 0x7f5cab3dd740)
        io/io.go:598 +0x95
io.copyBuffer(0x279d760, 0x3494ec0, 0x7f5cab2f47f8, 0xc003a518a0, 0x0, 0x0, 0x0, 0xc000070100, 0xc003a51800, 0xc001745d40)
        io/io.go:409 +0x357
io.Copy(...)
        io/io.go:382
github.com/minio/minio/cmd/http.DrainBody(0x27b5778, 0xc003a518a0)
        github.com/minio/minio/cmd/http/close.go:40 +0xdd
github.com/minio/minio/cmd.(*storageRESTClient).CreateFile(0xc000ae7700, 0x27cc988, 0xc0000420d8, 0x1f42bbe, 0xe, 0xc000e0fa40, 0x50, 0xa15ccca, 0x279ac60, 0xc0095baeb8, ...)
        github.com/minio/minio/cmd/storage-rest-client.go:346 +0x53c
github.com/minio/minio/cmd.newStreamingBitrotWriter.func1(0xa15a46a, 0x80000, 0x27d15c0, 0xc0005492b0, 0xc0095baeb8, 0x27f3658, 0xc000ae7700, 0x1f42bbe, 0xe, 0xc000e0fa40, ...)
        github.com/minio/minio/cmd/bitrot-streaming.go:85 +0x104
created by github.com/minio/minio/cmd.newStreamingBitrotWriter
        github.com/minio/minio/cmd/bitrot-streaming.go:79 +0x2bd
```

1. Upload a larger file 200-500M;
2. Refresh the page when he uploads to about 30%;

![image](https://user-images.githubusercontent.com/68437472/113472279-be143c80-9494-11eb-931e-bb962a2cb0a8.png)
3. minio has ceased operation
![image](https://user-images.githubusercontent.com/68437472/113472294-dc7a3800-9494-11eb-8bda-b472cb9ed364.png)

## Your Environment
* mnio version RELEASE.2021-03-26T00-00-41Z
* Centos7

**Comment by harshavardhana** [comment]
This is fixed in #11939
