### ISSUE TITLE
api: Server crash and multiple Sucess on concurrent bucket creation 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1198]
Here is the program which crashed the server, https://gist.github.com/hackintoshrao/109861edeffdd0f5ace7 . 

The same program also gave success two times on creation of same bucket.

**Comment by harshavardhana** [comment]
```
Function:fs.Filesystem.MakeBucket Env:map[]} {Line:281 Filename:bucket-handlers.go Function:main.storageAPI.PutBucketHandler Env:map[]}] SysInfo:map[host.os:darwin host.name:Karthics-MacBook-Pro.local host.lang:go1.6 mem.total:5.2MB host.arch:amd64 host.cpus:4 mem.used:1.9MB mem.heap.used:1.9MB mem.heap.total:3.5MB]}
fatal error: ERRO[256253] MakeBucket failed.                            Error={Cause:Bucket exists: test1 Type:fs.BucketExists CallTrace:[{Line:146 Filename:pkg/fs/fs-bucket.go Function:fs.Filesystem.MakeBucket Env:map[]} {Line:281 Filename:bucket-handlers.go Function:main.storageAPI.PutBucketHandler Env:map[]}] SysInfo:map[host.arch:amd64 host.lang:go1.6 host.cpus:4 host.os:darwin host.name:Karthics-MacBook-Pro.local mem.used:2.1MB mem.total:5.2MB mem.heap.used:2.1MB mem.heap.total:3.4MB]}

concurrent map read and map write

goroutine 53 [running]:
runtime.throw(0x7364a0, 0x21)
    /usr/local/go/src/runtime/panic.go:530 +0x90 fp=0xc8202eb040 sp=0xc8202eb028
runtime.mapaccess2_faststr(0x6637e0, 0xc8201cbe30, 0xc8202aa320, 0x9, 0xdcdae0, 0x0)
    /usr/local/go/src/runtime/hashmap_fast.go:307 +0x5b fp=0xc8202eb0a0 sp=0xc8202eb040
github.com/minio/minio/pkg/s3/signature4.extractSignedHeaders(0xc820312800, 0x4, 0x4, 0xc8201cbe30, 0xece6d6a00)
    /Users/hackintoshrao/mycode/go/src/github.com/minio/minio/pkg/s3/signature4/v4-utils.go:101 +0x114 fp=0xc8202eb170 sp=0xc8202eb0a0
github.com/minio/minio/pkg/s3/signature4.(*Sign).DoesSignatureMatch(0xc820013900, 0xc8203127c0, 0x40, 0xc8203127c0, 0x40)
    /Users/hackintoshrao/mycode/go/src/github.com/minio/minio/pkg/s3/signature4/v4-signature.go:348 +0x1ab fp=0xc8202eb398 sp=0xc8202eb170
main.storageAPI.PutBucketHandler(0x0, 0x7fff5fbffc78, 0x1c, 0x5, 0xc82018e9e0, 0xc82018e780, 0xc82018e840, 0xc8200607e0, 0xc820060840, 0xc820013900, ...)
    /Users/hackintoshrao/mycode/go/src/github.com/minio/minio/bucket-handlers.go:266 +0xa83 fp=0xc8202eb4e8 sp=0xc8202eb398
main.(storageAPI).PutBucketHandler-fm(0x131a348, 0xc82029ea90, 0xc82028e620)
    /Users/hackintoshrao/mycode/go/src/github.com/minio/minio/routers.go:144 +0x54 fp=0xc8202eb568 sp=0xc8202eb4e8
net/http.HandlerFunc.ServeHTTP(0xc8201d1490, 0x131a348, 0xc82029ea90, 0xc82028e620)
    /usr/local/go/src/net/http/server.go:1618 +0x3a fp=0xc8202eb588 sp=0xc8202eb568
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820014960, 0x131a348, 0xc82029ea90, 0xc82028e620)
    /Users/hackintoshrao/mycode/go/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:100 +0x29e fp=0xc8202eb6a0 sp=0xc8202eb588
main.redirectHandler.ServeHTTP(0x1318f10, 0xc820014960, 0x69ec68, 0x6, 0x131a348, 0xc82029ea90, 0xc82028e620)
```

**Comment by harshavardhana** [comment]
Fixed in current master.
