### ISSUE TITLE
WebDownloadZip() - fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#12082]
#### Context:

Federation with 3 clusters.
Version: `2021-04-06T23:11:00Z`
An user wanted to download a folder with 1000+ pngs causing a crash due to `fatal error: concurrent map iteration and map write` for `WebDownloadZip()`

#### Error:

```
API: WebDownloadZip()
Time: 19:57:39 UTC 04/17/2021
DeploymentID: 1543b90c-3079-4a27-a8f3-14135f9a5c10
RequestID: 1676BD3D96FF0E3F
RemoteHost: {IP}
Host: minio1.domain.com:9000
UserAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36 Edg/84.0.522.52
Error: Operation timed out (cmd.OperationTimedOut)
       objectErasureMap=map[...]
       fatal error: concurrent map iteration and map write
       1: cmd/web-handlers.go:1775:cmd.(*webAPIHandlers).DownloadZip()
      
goroutine 587579 [running]:
runtime.throw(0x1f7fdd9, 0x26)
	runtime/panic.go:1117 +0x72 fp=0xc015a953b0 sp=0xc015a95380 pc=0x438312
runtime.mapiternext(0xc00f1327e0)
	runtime/map.go:858 +0x54c fp=0xc015a95430 sp=0xc015a953b0 pc=0x410d2c
reflect.mapiternext(0xc00f1327e0)
	runtime/map.go:1346 +0x2b fp=0xc015a95448 sp=0xc015a95430 pc=0x46be0b
reflect.Value.MapKeys(0x1c54ec0, 0xc010257cb0, 0x15, 0x0, 0xc020ed4e38, 0xc01077f680)
	reflect/value.go:1227 +0x10c fp=0xc015a954d8 sp=0xc015a95448 pc=0x4fe3ec
encoding/json.mapEncoder.encode(0xc0142de930, 0xc005844080, 0x1c54ec0, 0xc010257cb0, 0x15, 0x1c50100)
	encoding/json/encode.go:797 +0x13c fp=0xc015a95680 sp=0xc015a954d8 pc=0x7c38bc
encoding/json.mapEncoder.encode-fm(0xc005844080, 0x1c54ec0, 0xc010257cb0, 0x15, 0xc010250100)
	encoding/json/encode.go:779 +0x6d fp=0xc015a956c0 sp=0xc015a95680 pc=0x7cf4ad
encoding/json.(*encodeState).reflectValue(0xc005844080, 0x1c54ec0, 0xc010257cb0, 0x15, 0xc010250100)
	encoding/json/encode.go:360 +0x82 fp=0xc015a956f8 sp=0xc015a956c0 pc=0x7c0ba2
encoding/json.interfaceEncoder(0xc005844080, 0x1c222e0, 0xc0031b6d70, 0x94, 0xc0031b0100)
	encoding/json/encode.go:716 +0xac fp=0xc015a95740 sp=0xc015a956f8 pc=0x7c308c
encoding/json.mapEncoder.encode(0x2503198, 0xc005844080, 0x1c566c0, 0xc0175de208, 0x195, 0x100)
	encoding/json/encode.go:813 +0x366 fp=0xc015a958e8 sp=0xc015a95740 pc=0x7c3ae6
encoding/json.mapEncoder.encode-fm(0xc005844080, 0x1c566c0, 0xc0175de208, 0x195, 0x100)
	encoding/json/encode.go:779 +0x6d fp=0xc015a95928 sp=0xc015a958e8 pc=0x7cf4ad
encoding/json.structEncoder.encode(0xc009ff8240, 0x3, 0x4, 0xc01f713080, 0xc005844080, 0x1d5ab40, 0xc0175de1e0, 0x199, 0x4c0100)
	encoding/json/encode.go:761 +0x2ab fp=0xc015a959c0 sp=0xc015a95928 pc=0x7c352b
encoding/json.structEncoder.encode-fm(0xc005844080, 0x1d5ab40, 0xc0175de1e0, 0x199, 0xc0175d0100)
	encoding/json/encode.go:732 +0x8c fp=0xc015a95a18 sp=0xc015a959c0 pc=0x7cf40c
encoding/json.ptrEncoder.encode(0xc01f7130b0, 0xc005844080, 0x1b51080, 0xc006b62138, 0x96, 0x100)
	encoding/json/encode.go:944 +0x125 fp=0xc015a95ad8 sp=0xc015a95a18 pc=0x7c52a5
encoding/json.ptrEncoder.encode-fm(0xc005844080, 0x1b51080, 0xc006b62138, 0x96, 0x100)
	encoding/json/encode.go:929 +0x6d fp=0xc015a95b18 sp=0xc015a95ad8 pc=0x7cf68d
encoding/json.structEncoder.encode(0xc000fdd600, 0xb, 0x10, 0xc01f7130e0, 0xc005844080, 0x1e85ce0, 0xc006b620a0, 0x99, 0x1e80100)
	encoding/json/encode.go:761 +0x2ab fp=0xc015a95bb0 sp=0xc015a95b18 pc=0x7c352b
encoding/json.structEncoder.encode-fm(0xc005844080, 0x1e85ce0, 0xc006b620a0, 0x99, 0xc006b60100)
	encoding/json/encode.go:732 +0x8c fp=0xc015a95c08 sp=0xc015a95bb0 pc=0x7cf40c
encoding/json.(*encodeState).reflectValue(0xc005844080, 0x1e85ce0, 0xc006b620a0, 0x99, 0xc006b60100)
	encoding/json/encode.go:360 +0x82 fp=0xc015a95c40 sp=0xc015a95c08 pc=0x7c0ba2
encoding/json.interfaceEncoder(0xc005844080, 0x1c222e0, 0xc006c2e920, 0x194, 0xc006c20100)
	encoding/json/encode.go:716 +0xac fp=0xc015a95c88 sp=0xc015a95c40 pc=0x7c308c
encoding/json.ptrEncoder.encode(0x2503198, 0xc005844080, 0x1b652c0, 0xc006c2e920, 0x16, 0x1b60100)
	encoding/json/encode.go:944 +0x125 fp=0xc015a95d48 sp=0xc015a95c88 pc=0x7c52a5
encoding/json.ptrEncoder.encode-fm(0xc005844080, 0x1b652c0, 0xc006c2e920, 0x16, 0x100)
	encoding/json/encode.go:929 +0x6d fp=0xc015a95d88 sp=0xc015a95d48 pc=0x7cf68d
encoding/json.(*encodeState).reflectValue(0xc005844080, 0x1b652c0, 0xc006c2e920, 0x16, 0xc015a90100)
	encoding/json/encode.go:360 +0x82 fp=0xc015a95dc0 sp=0xc015a95d88 pc=0x7c0ba2
encoding/json.(*encodeState).marshal(0xc005844080, 0x1b652c0, 0xc006c2e920, 0xc047920100, 0x0, 0x0)
	encoding/json/encode.go:332 +0xf9 fp=0xc015a95e20 sp=0xc015a95dc0 pc=0x7c0799
encoding/json.Marshal(0x1b652c0, 0xc006c2e920, 0xc013048b01, 0x0, 0x0, 0x21, 0x2799760)
	encoding/json/encode.go:161 +0x52 fp=0xc015a95e98 sp=0xc015a95e20 pc=0x7bfc12
github.com/minio/minio/cmd/logger/target/http.(*Target).startHTTPLogger.func1(0xc0152f87e0)
	github.com/minio/minio/cmd/logger/target/http/http.go:108 +0xea fp=0xc015a95fd8 sp=0xc015a95e98 pc=0x14681ea
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc015a95fe0 sp=0xc015a95fd8 pc=0x4726a1
created by github.com/minio/minio/cmd/logger/target/http.(*Target).startHTTPLogger
	github.com/minio/minio/cmd/logger/target/http/http.go:106 +0x3f

goroutine 1 [chan receive, 5079 minutes]:
github.com/minio/minio/cmd.serverMain(0xc000476820)
	github.com/minio/minio/cmd/server-main.go:549 +0xafd
github.com/minio/cli.HandleAction(0x1bad960, 0x2504da8, 0xc000476820, 0xc000795400, 0x0)
	github.com/minio/cli@v1.22.0/app.go:500 +0xc2
github.com/minio/cli.Command.Run(0x1f3908a, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1f6403e, 0x1b, 0x0, ...)
	github.com/minio/cli@v1.22.0/command.go:225 +0x9bb
github.com/minio/cli.(*App).Run(0xc00003dba0, 0xc00003a080, 0x4, 0x4, 0x0, 0x0)
	github.com/minio/cli@v1.22.0/app.go:261 +0x768
github.com/minio/minio/cmd.Main(0xc00003a080, 0x4, 0x4)
	github.com/minio/minio/cmd/main.go:167 +0x89
main.main()
	github.com/minio/minio/main.go:35 +0x45
```

**Comment by ToLToL** [comment]
I think that the user tried to download multiple times while the last `WebDownloadZip()` was still running.
