### ISSUE TITLE
Service restarting after every 5 min.

### ISSUE THREAD

**Issue by kollisaisriharsha** [minio/minio#12443]
The MinIO service on some servers in a cluster is restarting continuously. With high ram utilization.

## Current Behavior
restarting every frequently (5-10 min span) 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context
Here is a log snippet in the log file when this is happening.
```
goroutine 1613091 [IO wait]:
internal/poll.runtime_pollWait(0x7fe0cb8218a8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xdb929ab598, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xdb929ab580, 0xdbd991bb41, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xdb929ab580, 0xdbd991bb41, 0x1, 0x1, 0xc097c9b600, 0x1000000010000, 0xc00181c780)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xcd96dcdc60, 0xdbd991bb41, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xdbd991bb30)
	net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:688 +0xd5

goroutine 1599536 [semacquire]:
sync.runtime_SemacquireMutex(0xc0010b7df4, 0x0, 0x1)
	runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0010b7df0)
	sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
github.com/minio/minio/cmd.(*localLocker).Lock(0xc0010b7df0, 0x2ce3c20, 0xda85e29dd0, 0xda85e3274c, 0x24, 0xda85e3fd00, 0x1, 0x1, 0xda85e3cb80, 0x39, ...)
	github.com/minio/minio/cmd/local-locker.go:83 +0x42d
github.com/minio/minio/cmd.(*lockRESTServer).LockHandler(0xc00241d3b0, 0x2cd7990, 0xda85e34780, 0xda85e0df00)
	github.com/minio/minio/cmd/lock-rest-server.go:136 +0x178
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x2cd7990, 0xda85e34780, 0xda85e0df00)
	github.com/minio/minio/cmd/handler-utils.go:381 +0x70
net/http.HandlerFunc.ServeHTTP(0xc0010b7fa0, 0x2cd7990, 0xda85e34780, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRedirectHandler.func1(0x2cd7990, 0xda85e34780, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:138 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc9cf0947f8, 0x2cd7990, 0xda85e34780, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addCustomHeaders.func1(0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:563 +0x174
net/http.HandlerFunc.ServeHTTP(0xc9cf094810, 0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addSecurityHeaders.func1(0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:572 +0x1ea
net/http.HandlerFunc.ServeHTTP(0xc9cf094828, 0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBucketForwardingHandler.func1(0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:446 +0xad
net/http.HandlerFunc.ServeHTTP(0xc9cf094840, 0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestValidityHandler.func1(0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:434 +0x493
net/http.HandlerFunc.ServeHTTP(0xc9cf094858, 0x2cd7960, 0xc9cf094990, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setHTTPStatsHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:365 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc9cf094870, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:51 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc9cf094888, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:71 +0x202
net/http.HandlerFunc.ServeHTTP(0xc9cf0948a0, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x2cb45a0, 0xc9cf0948a0, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/crossdomain-xml-handler.go:52 +0x82
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:164 +0x74
net/http.HandlerFunc.ServeHTTP(0xc9cf0948b8, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setReservedBucketHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:286 +0x278
net/http.HandlerFunc.ServeHTTP(0xc9cf0948d0, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:265 +0x1ce
net/http.HandlerFunc.ServeHTTP(0xc9cf0948e8, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setTimeValidityHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:352 +0x42c
net/http.HandlerFunc.ServeHTTP(0xc9cf094900, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setAuthHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/auth-handler.go:500 +0x355
net/http.HandlerFunc.ServeHTTP(0xc9cf094918, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setSSETLSHandler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:606 +0x74
net/http.HandlerFunc.ServeHTTP(0xc9cf094930, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.filterReservedMetadata.func1(0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	github.com/minio/minio/cmd/generic-handlers.go:111 +0x1e8
net/http.HandlerFunc.ServeHTTP(0xc9cf094948, 0x2cda120, 0xda7a8bf180, 0xda85e0df00)
	net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005786c0, 0x2cda120, 0xda7a8bf180, 0xda85e0dd00)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x2cda120, 0xda7a8bf180, 0xda85e0dd00)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc00138eb40, 0x2cda120, 0xda7a8bf180, 0xda85e0dd00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x2cb45a0, 0xc00138eb40, 0x2cda120, 0xda7a8bf180, 0xda85e0dd00)
	github.com/minio/minio/cmd/generic-handlers.go:591 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x2cda120, 0xda7a8bf180, 0xda85e0dd00)
	github.com/minio/minio/cmd/http/server.go:103 +0x258
net/http.HandlerFunc.ServeHTTP(0xc001602000, 0x2cda120, 0xda7a8bf180, 0xda85e0dd00)
	net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0003e86c0, 0x2cda120, 0xda7a8bf180, 0xda85e0dd00)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xda85e346e0, 0x2ce3c20, 0xc978ec8040)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b

goroutine 1626080 [IO wait]:
internal/poll.runtime_pollWait(0x7fdf828c9c78, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xdd42d84c18, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xdd42d84c00, 0xdd68be7ae1, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xdd42d84c00, 0xdd68be7ae1, 0x1, 0x1, 0x0, 0x1000000010000, 0xc00181c780)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xdd2934e698, 0xdd68be7ae1, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xdd68be7ad0)
	net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:688 +0xd5

goroutine 1586910 [IO wait]:
internal/poll.runtime_pollWait(0x7fe090ea2c38, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xcd4e771498, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xcd4e771480, 0xcd5d460e21, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xcd4e771480, 0xcd5d460e21, 0x1, 0x1, 0xcba2c87cf8, 0x2cae120, 0xc00011cba0)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xcd3e1d59d8, 0xcd5d460e21, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xcd5d460e10)
	net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:688 +0xd5

goroutine 1502073 [runnable]:
internal/poll.runtime_pollWait(0x7fe0cc9c0be8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xc01d6b8418, 0x72, 0x8000, 0x8000, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc01d6b8400, 0xc0084ec000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xc01d6b8400, 0xc0084ec000, 0x8000, 0x8000, 0x6, 0x0, 0x0)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc01504acd0, 0xc0084ec000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*persistConn).Read(0xc005d02240, 0xc0084ec000, 0x8000, 0x8000, 0x6, 0x0, 0x0)
	net/http/transport.go:1922 +0x77
bufio.(*Reader).fill(0xc000446180)
	bufio/bufio.go:101 +0x108
bufio.(*Reader).ReadSlice(0xc000446180, 0xc08c76960a, 0xc0084ec004, 0x2, 0x1, 0x8000, 0x0)
	bufio/bufio.go:360 +0x3d
net/http/internal.readChunkLine(0xc000446180, 0x2, 0x0, 0x0, 0x10f, 0x10f)
	net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc08c7695f0)
	net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc08c7695f0, 0xc08ad77ccf, 0x1, 0x1, 0x1, 0x0, 0x0)
	net/http/internal/chunked.go:93 +0x134
net/http.(*body).readLocked(0xc08c752d00, 0xc08ad77ccf, 0x1, 0x1, 0x1, 0x0, 0x0)
	net/http/transfer.go:842 +0x5f
net/http.(*body).Read(0xc08c752d00, 0xc08ad77ccf, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/http/transfer.go:834 +0xf9
net/http.(*bodyEOFSignal).Read(0xc08c752d40, 0xc08ad77ccf, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/http/transport.go:2764 +0xe2
io.ReadAtLeast(0x2cb1d80, 0xc08c752d40, 0xc08ad77ccf, 0x1, 0x1, 0x1, 0x1, 0x0, 0x0)
	io/io.go:328 +0x87
io.ReadFull(...)
	io/io.go:347
github.com/minio/minio/cmd.waitForHTTPStream(0x2ccbe88, 0xc08c752d40, 0x2cb1980, 0xc073a87738, 0xc0004c9b40, 0x10)
	github.com/minio/minio/cmd/storage-rest-server.go:890 +0xd3
github.com/minio/minio/cmd.(*storageRESTClient).NSScanner.func2(0xc073a87738, 0x2ccbe88, 0xc08c752d40)
	github.com/minio/minio/cmd/storage-rest-client.go:224 +0x4b
created by github.com/minio/minio/cmd.(*storageRESTClient).NSScanner
	github.com/minio/minio/cmd/storage-rest-client.go:223 +0x50e

goroutine 1519736 [chan receive]:
github.com/minio/minio/cmd.erasureObjects.nsScanner.func3.1(0xc00177ea80, 0xc01083e240, 0xc004408f00, 0xc008032780, 0xc00f906ab0)
	github.com/minio/minio/cmd/erasure.go:485 +0xb2
created by github.com/minio/minio/cmd.erasureObjects.nsScanner.func3
	github.com/minio/minio/cmd/erasure.go:483 +0x610

goroutine 1614084 [IO wait]:
internal/poll.runtime_pollWait(0x7fe0cc40faf8, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xdbf37a0418, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xdbf37a0400, 0xdbfbc70d91, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xdbf37a0400, 0xdbfbc70d91, 0x1, 0x1, 0xc09491fe60, 0x0, 0xdbb6bf4818)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xcdbfee3a38, 0xdbfbc70d91, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xdbfbc70d80)
	net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:688 +0xd5

goroutine 1626175 [select]:
net/http.(*persistConn).writeLoop(0xdd7431ca20)
	net/http/transport.go:2382 +0xf7
created by net/http.(*Transport).dialConn
	net/http/transport.go:1744 +0xc9c

goroutine 1626755 [IO wait]:
internal/poll.runtime_pollWait(0x7fdf81a95a00, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xdd41a7cb18, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xdd41a7cb00, 0xdd7ae564f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xdd41a7cb00, 0xdd7ae564f1, 0x1, 0x1, 0xdd4456bbe0, 0x1, 0x1)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xdd05dbd358, 0xdd7ae564f1, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xdd7ae564e0)
	net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:688 +0xd5

goroutine 1602230 [IO wait]:
internal/poll.runtime_pollWait(0x7fe0cce942c0, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xdb360f2998, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xdb360f2980, 0xdb402a1721, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xdb360f2980, 0xdb402a1721, 0x1, 0x1, 0xc00361cd20, 0x0, 0xc980bd26d8)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc0006bc660, 0xdb402a1721, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xdb402a1710)
	net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:688 +0xd5

goroutine 1606594 [IO wait]:
internal/poll.runtime_pollWait(0x7fe0c3f09d88, 0x72, 0xffffffffffffffff)
	runtime/netpoll.go:222 +0x55
internal/poll.(*pollDesc).wait(0xdb35a33d18, 0x72, 0x0, 0x1, 0xffffffffffffffff)
	internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xdb35a33d00, 0xdb84c411e1, 0x1, 0x1, 0x0, 0x0, 0x0)
	internal/poll/fd_unix.go:166 +0x1d5
net.(*netFD).Read(0xdb35a33d00, 0xdb84c411e1, 0x1, 0x1, 0xffffffffffffffff, 0xdb3b6507a0, 0x1000000000001)
	net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00000e910, 0xdb84c411e1, 0x1, 0x1, 0x0, 0x0, 0x0)
	net/net.go:183 +0x91
net/http.(*connReader).backgroundRead(0xdb84c411d0)
	net/http/server.go:692 +0x58
created by net/http.(*connReader).startBackgroundRead
	net/http/server.go:688 +0xd5

goroutine 1591383 [semacquire]:
sync.runtime_SemacquireMutex(0xc0010b7df4, 0x0, 0x1)
	runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0010b7df0)
	sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
	sync/mutex.go:81
github.com/minio/minio/cmd.(*localLocker).Lock(0xc0010b7df0, 0x2ce3c20, 0xd7ad40a4e0, 0xd6f5ebd259, 0x24, 0xc78a300ab0, 0x1, 0x1, 0xc79d29a6f0, 0x26, ...)
	github.com/minio/minio/cmd/local-locker.go:83 +0x42d
github.com/minio/minio/cmd.(*lockRESTServer).LockHandler(0xc00241d3b0, 0x2cd7990, 0xc8e63ac320, 0xd7aa951a00)
	github.com/minio/minio/cmd/lock-rest-server.go:136 +0x178
net/http.HandlerFunc.ServeHTTP(...)
	net/http/server.go:2069
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x2cd7990, 0xc8e63ac320, 0xd7aa951a00)
	github.com/minio/minio/cmd/handler-utils.go:381 +0x70
net/http.HandlerFunc.ServeHTTP(0xc0010b7fa0, 0x2cd7990, 0xc8e63ac320, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRedirectHandler.func1(0x2cd7990, 0xc8e63ac320, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:138 +0xd3
net/http.HandlerFunc.ServeHTTP(0xc0702def00, 0x2cd7990, 0xc8e63ac320, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addCustomHeaders.func1(0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:563 +0x174
net/http.HandlerFunc.ServeHTTP(0xc0702def18, 0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.addSecurityHeaders.func1(0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:572 +0x1ea
net/http.HandlerFunc.ServeHTTP(0xc0702def30, 0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBucketForwardingHandler.func1(0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:446 +0xad
net/http.HandlerFunc.ServeHTTP(0xc0702def48, 0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestValidityHandler.func1(0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:434 +0x493
net/http.HandlerFunc.ServeHTTP(0xc0702def60, 0x2cd7960, 0xc0702df098, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setHTTPStatsHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:365 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc0702def78, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestSizeLimitHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:51 +0xeb
net/http.HandlerFunc.ServeHTTP(0xc0702def90, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setRequestHeaderSizeLimitHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:71 +0x202
net/http.HandlerFunc.ServeHTTP(0xc0702defa8, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x2cb45a0, 0xc0702defa8, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/crossdomain-xml-handler.go:52 +0x82
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:164 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0702defc0, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setReservedBucketHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:286 +0x278
net/http.HandlerFunc.ServeHTTP(0xc0702defd8, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setBrowserCacheControlHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:265 +0x1ce
net/http.HandlerFunc.ServeHTTP(0xc0702deff0, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setTimeValidityHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:352 +0x42c
net/http.HandlerFunc.ServeHTTP(0xc0702df008, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setAuthHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/auth-handler.go:500 +0x355
net/http.HandlerFunc.ServeHTTP(0xc0702df020, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.setSSETLSHandler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:606 +0x74
net/http.HandlerFunc.ServeHTTP(0xc0702df038, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.filterReservedMetadata.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	github.com/minio/minio/cmd/generic-handlers.go:111 +0x1e8
net/http.HandlerFunc.ServeHTTP(0xc0702df050, 0x2cda120, 0xd7aa96e380, 0xd7aa951a00)
	net/http/server.go:2069 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005786c0, 0x2cda120, 0xd7aa96e380, 0xd7aa951800)
	github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3
github.com/rs/cors.(*Cors).Handler.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951800)
	github.com/rs/cors@v1.7.0/cors.go:219 +0x1b9
net/http.HandlerFunc.ServeHTTP(0xc00138eb40, 0x2cda120, 0xd7aa96e380, 0xd7aa951800)
	net/http/server.go:2069 +0x44
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x2cb45a0, 0xc00138eb40, 0x2cda120, 0xd7aa96e380, 0xd7aa951800)
	github.com/minio/minio/cmd/generic-handlers.go:591 +0x85
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x2cda120, 0xd7aa96e380, 0xd7aa951800)
	github.com/minio/minio/cmd/http/server.go:103 +0x258
net/http.HandlerFunc.ServeHTTP(0xc001602000, 0x2cda120, 0xd7aa96e380, 0xd7aa951800)
	net/http/server.go:2069 +0x44
net/http.serverHandler.ServeHTTP(0xc0003e86c0, 0x2cda120, 0xd7aa96e380, 0xd7aa951800)
	net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc8e63ac280, 0x2ce3c20, 0xc011f3ccc0)
	net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	net/http/server.go:3013 +0x39b

goroutine 1482867 [select, 1 minutes]:
net/http.(*persistConn).readLoop(0xc005ea0000)
	net/http/transport.go:2203 +0x967
created by net/http.(*Transport).dialConn
	net/http/transport.go:1743 +0xc77
```

## Your Environment

* Version used (`minio --version`):RELEASE.2021-05-27T22-06-31Z
* Server setup and configuration: distributed MinIO running on bear-metal servers. (20 machines 10 disk each)
* Operating System and version (`uname -a`): Linux minio20 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vadmeste** [comment]
@kollisaisriharsha that log is not enough, it doesn't show why the server is crashed, could you upload all your logs ?

**Comment by kollisaisriharsha** [comment]
@vadmeste, Sure. Uploaded the log file below in tar format. Please let me know if you need any other data.

Thank you!
[service.log.tar.gz](https://github.com/minio/minio/files/6599243/service.log.tar.gz)

**Comment by klauspost** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x1ac7717]

goroutine 956131 [running]:
github.com/minio/minio/cmd.erasureObjects.putObject(0xa, 0x4, 0x11, 0x0, 0xc002ad5f50, 0xc002ad5f68, 0xc002ad5f80, 0xc002ad5890, 0xc002ad58a8, 0xc003305680, ...)
	github.com/minio/minio/cmd/erasure-object.go:614 +0x2717
github.com/minio/minio/cmd.(*erasureObjects).listPath.func3.2(0xc01439c190, 0x0, 0x0)
	github.com/minio/minio/cmd/metacache-set.go:658 +0x5e5
github.com/minio/minio/cmd.newMetacacheBlockWriter.func1.2()
	github.com/minio/minio/cmd/metacache-stream.go:774 +0xcf
github.com/minio/minio/cmd.newMetacacheBlockWriter.func1(0xc012454210, 0xc01373ba80, 0xc00285f980)
	github.com/minio/minio/cmd/metacache-stream.go:803 +0x3aa
created by github.com/minio/minio/cmd.newMetacacheBlockWriter
	github.com/minio/minio/cmd/metacache-stream.go:755 +0xbb
ent).call()
       3: cmd/storage-rest-client.go:505:cmd.(*storageRESTClient).ReadVersion()
       2: cmd/erasure-metadata-utils.go:131:cmd.readAllFileInfo.func1()
       1: pkg/sync/errgroup/errgroup.go:123:errgroup.(*Group).Go.func1()
```

**Comment by klauspost** [comment]
Found it.
