### ISSUE TITLE
putObject AccessDenied whith 7.0.2

### ISSUE THREAD

**Issue by wzc570738205** [minio/minio#12464]
```
 public static class Main {
        public static void main(String[] args) {
            String path = "/Users/wangzhichao/Downloads/dCMZxkwz_400x400.jpg";
            String ob = "dCMZxkwz2.jpg";
            File file = new File(path);
            try {
                FileInputStream inputStream = new FileInputStream(file);
                String minioUrl = "https://xxxxx.com";
                String bucketName = "safety-policing-local";
                Integer expires = 7 * 3600;
                Integer port = 443;
                String accessKey = "xxxx";
                String secretKey = "xxxxx";

                MinioClient minioClient = new MinioClient(minioUrl, port, accessKey, secretKey, true);


              
                System.out.println(minioClient);
                System.out.println("login ok");
                System.out.println(inputStream.available());
                minioClient.putObject(bucketName, ob, inputStream, new PutObjectOptions(inputStream.available(), -1));
                System.out.println("xxxxx");
                String url = minioClient.presignedGetObject(bucketName, ob, expires);
                System.out.println(url);

            } catch (FileNotFoundException | InvalidEndpointException | InvalidPortException e) {
                System.out.println(e.getMessage());
            } catch (InvalidBucketNameException e) {
                e.printStackTrace();
            } catch (InsufficientDataException e) {
                e.printStackTrace();
            } catch (ErrorResponseException e) {
                e.printStackTrace();
            } catch (IOException e) {
                e.printStackTrace();
            } catch (NoSuchAlgorithmException e) {
                e.printStackTrace();
            } catch (InvalidExpiresRangeException e) {
                e.printStackTrace();
            } catch (InvalidKeyException e) {
                e.printStackTrace();
            } catch (XmlParserException e) {
                e.printStackTrace();
            } catch (InvalidResponseException e) {
                e.printStackTrace();
            } catch (InternalException e) {
                e.printStackTrace();
            }
        }
    }
```
there is my error
```
io.minio.MinioClient@185d8b6
login ok
15440
error occurred
ErrorResponse(code = AccessDenied, message = There were headers present in the request which were not signed, bucketName = safety-policing-local, objectName = null, resource = /safety-policing-local, requestId = 168689F66B3857DB, hostId = b577bdce-c597-4018-92f8-71e768f7e71e)
request={method=GET, url=https://minio.safetypolicing.com/safety-policing-local?location=, headers=Host: minio.safetypolicing.com
Accept-Encoding: identity
User-Agent: MinIO (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: UNSIGNED-PAYLOAD
x-amz-date: 20210608T071324Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210608/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=Server: marco/2.14
Date: Tue, 08 Jun 2021 07:13:27 GMT
Content-Type: application/xml
Content-Length: 342
Connection: keep-alive
X-Source: C/400
Content-Security-Policy: block-all-mixed-content
X-Xss-Protection: 1; mode=block
X-Amz-Request-Id: 168689F66B3857DB
Accept-Ranges: bytes
X-Request-Id: 7f91eecee16069c6ed6411c43d46fe89
Via: S.mix-js-czx2-046, T.46.D, V.mix-js-czx2-047, T.69.D, M.ctn-zj-jgh-061
}

	at io.minio.MinioClient.execute(MinioClient.java:1211)
	at io.minio.MinioClient.execute(MinioClient.java:1236)
	at io.minio.MinioClient.updateRegionCache(MinioClient.java:1253)
	at io.minio.MinioClient.getRegion(MinioClient.java:1279)
	at io.minio.MinioClient.executePost(MinioClient.java:1392)
	at io.minio.MinioClient.createMultipartUpload(MinioClient.java:5092)
	at io.minio.MinioClient.putObject(MinioClient.java:3708)
	at io.minio.MinioClient.putObject(MinioClient.java:3870)
	at com.sp.cloud.MinioCloudStorageService$Main.main(MinioCloudStorageService.java:217)

Process finished with exit code 0

```
Who can tell me why？，very thanks

**Comment by balamurugana** [comment]
Duplicate of https://github.com/minio/minio-java/issues/1194
