### ISSUE TITLE
Fatal error: concurrent map writes

### ISSUE THREAD

**Issue by ToLToL** [minio/minio#12476]
Hi,

I have a `fatal error: concurrent map writes` with the latest release: ` RELEASE.2021-06-07T21-40-51Z `.
Distributed setup with 2 pools (3 nodes in each).
Logger and audit enabled.

I have other distributed setups with 1 pool and never had this problem, maybe it happens only with multiple pools.

```
fatal error: concurrent map writes

goroutine 8710541 [running]:
runtime.throw(0x2494072, 0x15)
	runtime/panic.go:1117 +0x72 fp=0xc00b3310a0 sp=0xc00b331070 pc=0x438592
runtime.mapassign_faststr(0x21320e0, 0xc00f3e3b00, 0xc00f1f7aa5, 0x4a, 0x6)
	runtime/map_faststr.go:291 +0x3d8 fp=0xc00b331108 sp=0xc00b3310a0 pc=0x414858
github.com/minio/minio/cmd.auditObjectErasureSet(0x2d69220, 0xc00f51f2c0, 0xc00f1f7aa5, 0x4a, 0xc002053ec0)
	github.com/minio/minio/cmd/erasure-sets.go:550 +0x1fd fp=0xc00b331188 sp=0xc00b331108 pc=0x1b6123d
github.com/minio/minio/cmd.(*erasureSets).GetObjectInfo(0xc0001ffb00, 0x2d69220, 0xc00f51f2c0, 0xc00c0d1b30, 0x2f, 0xc00f1f7aa5, 0x4a, 0x0, 0x0, 0x0, ...)
	github.com/minio/minio/cmd/erasure-sets.go:905 +0x132 fp=0xc00b3319d0 sp=0xc00b331188 pc=0x1b646f2
github.com/minio/minio/cmd.(*erasureServerPools).getPoolIdxExisting.func1(0xc00da77400, 0x2d69220, 0xc00f51f2c0, 0xc00c0d1b30, 0x2f, 0xc00f1f7aa5, 0x4a, 0xc00e09c900, 0x2, 0x2, ...)
	github.com/minio/minio/cmd/erasure-server-pool.go:252 +0x118 fp=0xc00b331f68 sp=0xc00b3319d0 pc=0x1d44758
runtime.goexit()
	runtime/asm_amd64.s:1371 +0x1 fp=0xc00b331f70 sp=0xc00b331f68 pc=0x472901
created by github.com/minio/minio/cmd.(*erasureServerPools).getPoolIdxExisting
	github.com/minio/minio/cmd/erasure-server-pool.go:250 +0x1ec

goroutine 1 [chan receive, 219 minutes]:
github.com/minio/minio/cmd.serverMain(0xc0004364e0)
	github.com/minio/minio/cmd/server-main.go:581 +0xae5
github.com/minio/cli.HandleAction(0x204df40, 0x2a45290, 0xc0004364e0, 0xc00009c900, 0x0)
	github.com/minio/cli@v1.22.0/app.go:500 +0xc2
github.com/minio/cli.Command.Run(0x2478049, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x24a3a69, 0x1b, 0x0, ...)
	github.com/minio/cli@v1.22.0/command.go:225 +0x9bb
github.com/minio/cli.(*App).Run(0xc00003dba0, 0xc00003a0a0, 0x5, 0x5, 0x0, 0x0)
	github.com/minio/cli@v1.22.0/app.go:261 +0x768
github.com/minio/minio/cmd.Main(0xc00003a0a0, 0x5, 0x5)
	github.com/minio/minio/cmd/main.go:168 +0x89
main.main()
	github.com/minio/minio/main.go:30 +0x45

goroutine 6 [chan receive, 219 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).dispatch(0xc00007cf60, 0xc00007cea0)
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:36 +0xb6
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:29 +0xe5

goroutine 7 [chan receive, 219 minutes]:
github.com/rjeczalik/notify.(*nonrecursiveTree).internal(0xc00007cf60, 0xc00007cf00)
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:81 +0x58
created by github.com/rjeczalik/notify.newNonrecursiveTree
	github.com/rjeczalik/notify@v0.9.2/tree_nonrecursive.go:30 +0x111

goroutine 8 [sleep, 10 minutes]:
time.Sleep(0x1a3185c5000)
	runtime/time.go:193 +0xd2
github.com/minio/minio/internal/logger.(*logOnceType).cleanupRoutine(0xc0001d09c0)
	github.com/minio/minio/internal/logger/logonce.go:65 +0x36
created by github.com/minio/minio/internal/logger.newLogOnceType
	github.com/minio/minio/internal/logger/logonce.go:72 +0x77

goroutine 19 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc0000e2080)
	go.opencensus.io@v0.22.5/stats/view/worker.go:276 +0xcd
created by go.opencensus.io/stats/view.init.0
	go.opencensus.io@v0.22.5/stats/view/worker.go:34 +0x68

goroutine 20 [select]:
github.com/minio/minio/internal/http.NewDNSCache.func1(0xc000100640, 0xc0005016b0, 0x6fc23ac00, 0xc0001005f0)
	github.com/minio/minio/internal/http/dial_dnscache.go:132 +0x13e
created by github.com/minio/minio/internal/http.NewDNSCache
	github.com/minio/minio/internal/http/dial_dnscache.go:128 +0x2a8
```

**Comment by vadmeste** [comment]
Thanks for reporting this @ToLToL, sending a fix..
