### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by GGORG0** [minio/minio#12709]
Starting the MinIO server fails with a SIGSEGV error
## Expected Behavior

It should just start 😄

## Current Behavior

It doesn't work 😞 
(I replaced some sensitive values with `nope`)
```
./minio server /mnt/data

API: SYSTEM()
Time: 09:52:12 UTC 07/14/2021
DeploymentID: aaa0ceb9-ff2d-43c0-94cd-be8fd8e99624
Error: Unable to initialize config, some features may be missing open config/config.json: not a directory (*fmt.wrapError)
       3: cmd/server-main.go:394:cmd.initAllSubsystems()
       2: cmd/server-main.go:325:cmd.initServer()
       1: cmd/server-main.go:545:cmd.serverMain()
API: http://nope:9000  http://127.0.0.1:9000
RootUser: nope
RootPass: nope

Console: http://nope:37017 http://127.0.0.1:37017
RootUser: nope
RootPass: nope

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://nope:9000 nope nope

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (37017), please use --console-address ":PORT" to choose a static port.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd83ce6]

goroutine 73 [running]:
sync.(*Mutex).Lock(...)
        sync/mutex.go:74
github.com/minio/minio/internal/config/identity/openid.(*Config).ProviderEnabled(0x6280aa0, 0x49e2700)
        github.com/minio/minio/internal/config/identity/openid/jwt.go:105 +0x46
github.com/minio/minio/cmd.(*IAMSys).Init(0xc0003087e0, 0x49e27f8, 0xc0003f7ac0, 0x4a2ffa8, 0xc000265d50)
        github.com/minio/minio/cmd/iam.go:653 +0x8ef
created by github.com/minio/minio/cmd.serverMain
        github.com/minio/minio/cmd/server-main.go:562 +0xa3f
```

## Possible Solution

no idea

## Steps to Reproduce (for bugs)

```bash
ufw enable
ufw allow 9000
wget https://dl.min.io/server/minio/release/linux-amd64/minio
chmod +x minio
echo "MINIO_ROOT_USER=nope MINIO_ROOT_PASSWORD=nope ./minio server /mnt/data" > minio.sh
chmod +x minio.sh
./minio.sh
```

## Context

I was just trying to start the MinIO server, commands above

## Regression

I don't know

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2021-07-12T02-44-53Z`
* Server setup and configuration: Linode Ubuntu 20.04 LTS server with ufw enabled
* Operating System and version (`uname -a`): `Linux localhost 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux` (Ubuntu 20.04 LTS)

**Comment by vadmeste** [comment]
@GGORG0 did you upgrade from older version ?

**Comment by GGORG0** [comment]
@vadmeste No, it was a fresh install

**Comment by vadmeste** [comment]
> @vadmeste No, it was a fresh install

/mnt/data seems to contain some data already, could you run this ?

```
tree /mnt/data/.minio.sys/
```

**Comment by GGORG0** [comment]
> 
> 
> > @vadmeste No, it was a fresh install
> 
> /mnt/data seems to contain some data already, could you run this ?
> 
> ```
> tree /mnt/data/.minio.sys/
> ```

Sorry for late reply, here is the output
```
/mnt/data/.minio.sys/
|-- buckets
|-- config
|   `-- iam
|       `-- format.json
|-- format.json
|-- multipart
`-- tmp
    |-- 0168b1ee-8001-4978-8f0f-583ae238b142
    |-- 0350acbe-d8ce-49d1-8633-c7a0ce41a165
    |-- 08eb1f40-b8df-4b12-828c-5167cc7d490e
    |-- 1523bc3c-ae63-463e-99d2-9243686eebcb
    |-- 155beaed-243a-47ec-b698-eed2dd02f3e8
    |-- 18dc20d1-59f9-4914-b5b3-6378bfa42ca4
    |-- 1ba7bea0-7467-41c0-9849-5279edda82bb
    |-- 2237b2de-7065-4eac-9e67-76f1b814031b
    |-- 258d1da5-8386-418f-9a7d-f09994bd9014
    |-- 26ef09e6-132e-44ca-98d3-1f2fcacdac3f
    |-- 30eced76-a135-46b2-9036-694223a1fb4d
    |-- 36dbc287-c72b-46ec-a99f-691c94e46cf1
    |-- 3eb3fddb-dd97-4682-8430-84d9365ba3b9
    |-- 4816cd27-b0e3-4c23-9013-a0702469beaf
    |-- 4ab15ff6-11af-40ab-b190-67bcd8549f3e
    |-- 50abbb0d-87f4-4d13-8fca-2163c567451b
    |-- 5174490a-fdb0-4867-807f-503a1b77ebe3
    |-- 55058332-42c3-47df-ba92-81e7362f8d38
    |-- 5a2b1671-e74a-45db-a512-56ee29f08cce
    |-- 5c46fdfd-3013-4455-866a-99585e66025b
    |-- 61e26356-78bb-4503-8e53-7abf71389d1f
    |-- 6e448284-44c5-490c-a64b-251bca9e6230
    |-- 7e8a0c1e-0e91-4605-b202-baaafab0c013
    |-- 94e1e731-b0e2-43a9-a14f-c02236a2ba92
    |-- a2a1d588-7d17-41db-b554-e3d907fd3c7d
    |-- a89bfb4e-cceb-4443-9cc4-224b69d28170
    |-- b34392a3-f2fb-4c2b-bc79-ad5041a0e8e8
    |-- b993890a-612d-41ed-b7ae-9abd57f2f63f
    |-- bca6232a-c580-420c-96f1-56c5fcd7d7c6
    |-- c5672b54-e6c5-482c-a785-5c6742ba6cf6
    |-- cb395537-ec09-4260-a0d2-806c81dcbfbf
    |-- cbe0c664-b19e-48cd-a6da-a04f470e26c1
    |-- d4f69aec-36f7-421c-9c2d-28287bb696cc
    |-- dcf3126e-620d-4089-b2ec-b264b7ad3016
    |-- e2920e11-321a-4c58-bc96-bb41a0a7e37b
    |-- f00de869-3278-4486-b475-f92b62dee5fb
    |-- f65d8171-9323-4caa-81ef-4f3f13ddc8de
    `-- f8ea6db7-03e1-4850-94c2-45463a5be009
```

**Comment by vadmeste** [comment]
@GGORG0 thanks, what about `cat /mnt/data/.minio.sys/format.json` ?

**Comment by GGORG0** [comment]
> cat /mnt/data/.minio.sys/format.json

`{"version":"1","format":"fs","id":"aaa0ceb9-ff2d-43c0-94cd-be8fd8e99624","fs":{"version":"2"}}`

**Comment by harshavardhana** [comment]
> Error: Unable to initialize config, some features may be missing open config/config.json: not a directory (*fmt.wrapError)

what is your setup here? looks like something is corrupted and not accessible
