### ISSUE TITLE
Please reduce your request

### ISSUE THREAD

**Issue by kendn1993** [minio/minio#13151]
## Expected Behavior
success

## Current Behavior
Caused by: io.minio.errors.ErrorResponseException: Please reduce your request
        at io.minio.MinioClient.execute(MinioClient.java:1201)
        at io.minio.MinioClient.executePost(MinioClient.java:1348)
        at io.minio.MinioClient.initMultipartUpload(MinioClient.java:4318)
        at io.minio.MinioClient.putObject(MinioClient.java:3754)
        at io.minio.MinioClient.putObject(MinioClient.java:3383)

## Steps to Reproduce (for bugs)
This exception is occasionally reported when uploading files

## Your Environment

* Version used (`minio --version`):
mc version RELEASE.2020-08-08T02-33-58Z
* Server setup and configuration: 
* #!/bin/bash
#访问用户名
export MINIO_ACCESS_KEY=admin
#访问密码
export MINIO_SECRET_KEY=123456
#数据存放目录
export MINIO_VOLUMES="/home/minio/data/"
#自定义端口
port=9333
nohup ./minio server --config-dir /etc/minio \
               --address ":$port" \
               http://10.10.10.86$MINIO_VOLUMES \
               http://10.10.10.88$MINIO_VOLUMES \
               http://10.10.10.89$MINIO_VOLUMES \
               http://10.10.10.90$MINIO_VOLUMES &
* Operating System and version (`uname -a`): Linux hadoop003 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Please upgrade and test again. There has been 1000s of changes since then.

Please upgrade and test again.
