### ISSUE TITLE
MinIO Tenant Pods are continuously crashing and restarting 

### ISSUE THREAD

**Issue by nirav-chotai** [minio/minio#13174]
Suddenly, without any change, all of the MinIO tenant pods started restarting and throwing below error in the logs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4ac832]

goroutine 3687360 [running]:
io.(*nopCloser).Read(0xc0398dc990, 0xc0f68da000, 0x2000, 0x2000, 0x40db9b, 0xc0398dc980, 0x40a6bf)
        <autogenerated>:1 +0x32
io.discard.ReadFrom(0x7f178aba1738, 0xc0398dc990, 0x1d141e0, 0x1, 0x7f178b47a058)
        io/io.go:598 +0x95
io.copyBuffer(0x279d760, 0x3494ec0, 0x7f178aba1738, 0xc0398dc990, 0x0, 0x0, 0x0, 0x0, 0xc0398dc901, 0xc00436fd40)
        io/io.go:409 +0x357
io.Copy(...)
        io/io.go:382
github.com/minio/minio/cmd/http.DrainBody(0x27b5778, 0xc0398dc990)
        github.com/minio/minio/cmd/http/close.go:40 +0xdd
github.com/minio/minio/cmd.(*storageRESTClient).CreateFile(0xc000535300, 0x27cc988, 0xc000042098, 0x1f42bbe, 0xe, 0xc0cd0eced0, 0x2b, 0x15896, 0x279ac60, 0xc005f942b0, ...)
        github.com/minio/minio/cmd/storage-rest-client.go:346 +0x53c
github.com/minio/minio/cmd.newStreamingBitrotWriter.func1(0x15876, 0x40000, 0x27d15c0, 0xc0879788f0, 0xc005f942b0, 0x27f3658, 0xc000535300, 0x1f42bbe, 0xe, 0xc0cd0eced0, ...)
        github.com/minio/minio/cmd/bitrot-streaming.go:85 +0x104
created by github.com/minio/minio/cmd.newStreamingBitrotWriter
        github.com/minio/minio/cmd/bitrot-streaming.go:79 +0x2bd
```

## Expected Behavior
MinIO pods should not crash and give some clear error or exception rather than panic

## Current Behavior
MinIO panic and restarting pods

## Possible Solution
Don't know

## Your Environment
Running MinIO Operator on Kubernetes
```
NAME                              READY   STATUS    RESTARTS   AGE
minio-ss-0-0                      1/1     Running   12         2d23h
minio-ss-0-1                      1/1     Running   13         2d23h
minio-ss-0-2                      1/1     Running   12         2d23h
minio-ss-0-3                      1/1     Running   13         2d23h
```
* Version used (`minio --version`): RELEASE.2021-03-26T00-00-41Z
* Server setup and configuration: Onprem Kubernetes Environment setup by Kubeadm
* Operating System and version (`uname -a`): Ubuntu 18.04.1 LTS

**Comment by nirav-chotai** [comment]
There are more errors as well in the logs 

```
Error: Unable to write all the data to client write tcp 192.168.123.39:9000->192.168.101.64:32519: write: broken pipe (*fmt.wrapError)
       2: cmd/object-handlers.go:513:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```
and
```
Error: Unable to write all the data to client write tcp 192.168.123.39:9000->192.168.75.192:58211: write: connection reset by peer (*fmt.wrapError)
       2: cmd/object-handlers.go:513:cmd.objectAPIHandlers.GetObjectHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```
and
```
Error: write tcp 192.168.123.39:9000->192.168.67.111:45040: write: broken pipe (*net.OpError)
       2: cmd/storage-rest-server.go:532:cmd.(*storageRESTServer).ReadFileStreamHandler()
       1: net/http/server.go:2069:http.HandlerFunc.ServeHTTP()
```
Are these errors causing panic?

**Comment by klauspost** [comment]
Strange. Haven't seen this. I will investigate.

**Comment by klauspost** [comment]
(yes, the errors are the cause, but obviously shouldn't crash)

**Comment by klauspost** [comment]
@nirav-chotai Ah. See you are on an old version. Upgrading should fix this.

**Comment by nirav-chotai** [comment]
Thanks, @klauspost , will go for `RELEASE.2021-09-03T03-56-13Z`

Is it just updating the new image in `tenant.yaml` and apply it in Kubernetes? I do not see any guide or instructions for MinIO upgrade on Kubernetes using MinIO Operator.
