### ISSUE TITLE
[signal SIGSEGV: segmentation violation on Minio Start

### ISSUE THREAD

**Issue by adenau** [minio/minio#13359]
When I start my Minio container, it crashes with a SIGSEGV signal.

## Expected Behavior
Minio should start.

## Current Behavior
When starting minio container, I get the following stack trace :

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb3be76]

goroutine 1 [running]:
github.com/minio/minio/internal/logger.fatal({0x426e0a0, 0xc0001b4780}, {0x2cc31d4, 0x2b292c0}, {0x0, 0x40d187, 0xc000753948})
	github.com/minio/minio/internal/logger/console.go:61 +0x56
github.com/minio/minio/internal/logger.FatalIf(...)
	github.com/minio/minio/internal/logger/logger.go:404
github.com/minio/minio/cmd.mustGetLocalIP4()
	github.com/minio/minio/cmd/net.go:51 +0x69
github.com/minio/minio/cmd.init()
```

## Possible Solution
???

## Steps to Reproduce (for bugs)
```
> root@xyz:~# docker pull minio/minio
Using default tag: latest
latest: Pulling from minio/minio
Digest: sha256:4e0fa6e4f454536bc67fd30f489d964e382a793baea7e3b6013d582459da7766
Status: Image is up to date for minio/minio:latest
docker.io/minio/minio:latest
>  root@xyz:~# docker run minio/minio server /data
```

## Context
Being unable to start Minio, I cannot complete my backups.

## Regression
Unknown, minio worked fine until about 2 weeks ago.

## Your Environment
```
> root@xyz:~# more /etc/debian_version
10.10
> root@xyz:~# docker -v
Docker version 20.10.8, build 3967b7d
> root@xyz:~# uname -a 
Linux xyz 5.4.78-2-pve #1 SMP PVE 5.4.78-2 (Thu, 03 Dec 2020 14:26:17 +0100) x86_64 GNU/Linux
```
Docker image latest is currently at RELEASE.2021-10-02T16-31-05Z

**Comment by harshavardhana** [comment]
```
~ docker pull minio/minio
Using default tag: latest
latest: Pulling from minio/minio
dde93efae2ff: Pull complete 
94249d6f79d2: Pull complete 
f21f49b5c566: Pull complete 
86368541e521: Pull complete 
5b9edb6bc092: Pull complete 
4e08df8ed8a1: Pull complete 
d6f6be3ccd04: Pull complete 
Digest: sha256:4e0fa6e4f454536bc67fd30f489d964e382a793baea7e3b6013d582459da7766
Status: Downloaded newer image for minio/minio:latest
docker.io/minio/minio:latest
```

Looks like your setup is broken on your system, please re-install your docker runtime.

```
` docker run --rm minio/minio server /data
API: http://172.17.0.3:9000  http://127.0.0.1:9000       

Console: http://172.17.0.3:33239 http://127.0.0.1:33239    

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (33239), please use --console-address ":PORT" to choose a static port.
WARNING: Detected default credentials 'minioadmin:minioadmin', we recommend that you change these values with 'MINIO_ROOT_USER' and 'MINIO_ROOT_PASSWORD' environment variables
```

**Comment by adenau** [comment]
For those that might be interested, the problem was not docker. App Armor was suddenly activated on that particular server and preventing that particular container from accessing the TCP stack. I temporarily fixed it with the following extra option : --security-opt apparmor=unconfined

**Comment by harshavardhana** [comment]
> For those that might be interested, the problem was not docker. App Armor was suddenly activated on that particular server and preventing that particular container from accessing the TCP stack. I temporarily fixed it with the following extra option : --security-opt apparmor=unconfined

Good to know, but it is silly.
