### ISSUE TITLE
Running benchmarks w/o also running tests panics in minio/cmd.BenchmarkListObjects

### ISSUE THREAD

**Issue by dr2chase** [minio/minio#13380]
## Expected Behavior

Benchmarks running without panicking.

## Current Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2657042]

goroutine 213023 [running]:
github.com/minio/minio/cmd.(*BucketMetadataSys).Set(0x0, 0x32e7964, 0x13, 0x32e7964, 0x13, 0x1d68bcd1, 0xed8f15671, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/bucket-metadata-sys.go:69 +0x42
github.com/minio/minio/cmd.(*FSObjects).MakeBucketWithLocation(0xc000032070, 0x49897e8, 0xc000054068, 0x32e7964, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/fs-v1.go:466 +0x3b8
github.com/minio/minio/cmd.BenchmarkListObjects(0xc0003e8b40)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/object-api-listobjects_test.go:1405 +0x1ba
testing.(*B).runN(0xc0003e8b40, 0x1)
	/usr/local/google/home/drchase/work/bent/goroots/Control/src/testing/benchmark.go:192 +0xeb
testing.(*B).run1.func1(0xc0003e8b40)
	/usr/local/google/home/drchase/work/bent/goroots/Control/src/testing/benchmark.go:232 +0x57
created by testing.(*B).run1
	/usr/local/google/home/drchase/work/bent/goroots/Control/src/testing/benchmark.go:225 +0x7f
```

## Possible Solution

Quoting colleague:
"looks like the benchmark is missing a call to newAllSystems to initialize a global: https://github.com/minio/minio/blob/3a7c79e2c71f7b09974ff1a1c70e4d149a83a6a9/cmd/server-main.go#L218"

## Steps to Reproduce (for bugs)

1. mkdir build ; cd build ; go mod init build
2. go get -d -t -v github.com/minio/minio/cmd@latest
3. go test -run=none -bench=BenchmarkListObjects github.com/minio/minio/cmd
4.

## Context

I am trying to add minio to a set of frequently run benchmarks for the Go compiler and runtime.
This same bug may also affect `BenchmarkPutObjectPart5MbFS`; it also crashes, like so, when I filter "BenchmarkLi" out of the regular expression for benchmarks to run:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2657042]

goroutine 205460 [running]:
github.com/minio/minio/cmd.(*BucketMetadataSys).Set(0x0, 0xc000127580, 0x3c, 0xc000127580, 0x3c, 0x1f28b1bf, 0xed8f15d3b, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/bucket-metadata-sys.go:69 +0x42
github.com/minio/minio/cmd.(*FSObjects).MakeBucketWithLocation(0xc0005be000, 0x49897e8, 0xc000124010, 0xc000127580, 0x3c, 0x0, 0x0, 0x7fe8e40b0000, 0x0, 0x0)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/fs-v1.go:466 +0x3b8
github.com/minio/minio/cmd.runPutObjectPartBenchmark(0xc0003be240, 0x49db850, 0xc0005be000, 0x500000)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/benchmark-utils_test.go:79 +0xe5
github.com/minio/minio/cmd.benchmarkPutObjectPart(0xc0003be240, 0x32bc342, 0x2, 0x500000)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/benchmark-utils_test.go:143 +0x1d5
github.com/minio/minio/cmd.BenchmarkPutObjectPart5MbFS(0xc0003be240)
	/usr/local/google/home/drchase/work/bent/gopath/pkg/mod/github.com/minio/minio@v0.0.0-20211007050347-8e417e28d1a1/cmd/object-api-multipart_test.go:1838 +0x49
testing.(*B).runN(0xc0003be240, 0x1)
	/usr/local/google/home/drchase/work/bent/goroots/Control/src/testing/benchmark.go:192 +0xeb
testing.(*B).run1.func1(0xc0003be240)
	/usr/local/google/home/drchase/work/bent/goroots/Control/src/testing/benchmark.go:232 +0x57
created by testing.(*B).run1
	/usr/local/google/home/drchase/work/bent/goroots/Control/src/testing/benchmark.go:225 +0x7f
```

## Regression
 No, this is old, I saw it a long time ago and figured, "eh, software, bugs".

## Your Environment

* Version used (`minio --version`): I didn't actually build it, but go.mod contains (latest as of right now):
```
  	github.com/minio/argon2 v1.0.0 // indirect
	github.com/minio/cli v1.22.0 // indirect
	github.com/minio/colorjson v1.0.1 // indirect
	github.com/minio/console v0.10.3 // indirect
	github.com/minio/csvparser v1.0.0 // indirect
	github.com/minio/direct-csi v1.3.5-0.20210601185811-f7776f7961bf // indirect
	github.com/minio/filepath v1.0.0 // indirect
	github.com/minio/highwayhash v1.0.2 // indirect
	github.com/minio/kes v0.14.0 // indirect
	github.com/minio/madmin-go v1.1.7 // indirect
	github.com/minio/mc v0.0.0-20210626002108-cebf3318546f // indirect
	github.com/minio/md5-simd v1.1.1 // indirect
	github.com/minio/minio v0.0.0-20211007050347-8e417e28d1a1 // indirect
	github.com/minio/minio-go/v7 v7.0.15-0.20210928020726-a58653d41dd8 // indirect
	github.com/minio/operator v0.0.0-20210812082324-26350f153661 // indirect
	github.com/minio/operator/logsearchapi v0.0.0-20210812082324-26350f153661 // indirect
	github.com/minio/parquet-go v1.0.0 // indirect
	github.com/minio/pkg v1.1.4 // indirect
	github.com/minio/selfupdate v0.3.1 // indirect
	github.com/minio/sha256-simd v1.0.0 // indirect
	github.com/minio/simdjson-go v0.2.1 // indirect
	github.com/minio/sio v0.3.0 // indirect
	github.com/minio/zipindex v0.2.0 // indirect
```

* Server setup and configuration: none
* Operating System and version (`uname -a`): Darwin drchase-macbookpro1.roam.corp.google.com 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
* Operating System and version (`uname -a`): Linux drchase.c.REDACTED.com 5.10.46-4REDACTED-amd64  SMP Debian 5.10.46-4REDACTED (2021-09-06) x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
You can't just run individual benchmarks like this. They are not self contained and of course you need to make sure all the necessary data structures are initialized.

Right now there is no good reason for us to invest time on this, we will get to it when we can.

Closing this not an issue for us at the moment. Feel free to send a fix by looking at other tests on how to do proper setup.

**Comment by dr2chase** [comment]
Just to be clear, this also reproduces if I run *all* the benchmarks, in order.  Specifying just that one by name saves you time by failing faster.  E.g., 
```
mkdir build ; cd build ; go mod init build
go get -d -t -v github.com/minio/minio/cmd@latest
go test -run=none -bench=Benchmark github.com/minio/minio/cmd
```

Minio is also unique among all the benchmarks that I run (currently 47 different packages) in requiring that I run some (undocumented) test before these particular benchmarks.  In the meantime, we have a workaround, which is to not measure the benchmarks that fail, using this benchmark specification:
```
-test.bench=Benchmark([^LPG]|L[^]i|G[^e]|P[^ua]|Parallel([^LPG]|L[^]i|G[^e]|P[^u]))
```
Since you are happy with things (not) working this way and we have a workaround, I won't be bothering to submit a fix.

**Comment by harshavardhana** [comment]
FWIW @dr2chase fixed this upstream - there was only one benchmark that failed in this manner.
