### ISSUE TITLE
Minio Azure Gateway unable to write delta table from Apache Spark

### ISSUE THREAD

**Issue by gbakthavatchalam** [minio/minio#13486]
I am trying to write a spark dataframe into Azure container through Minio Azure Gateway in delta table format. But 

## Expected Behavior
Delta table should be written to azure

## Current Behavior
Getting error `Path is a file` while writing the delta table on Azure through Minio gateway

```
Exception in thread "main" org.apache.hadoop.fs.s3a.AWSBadRequestException: PUT 0-byte object  on bakthaminio/bakthaminio-randomchkminio-1634762164130-raw/_delta_log/: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName; Request ID: 16AFD789877C5B79; S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b), S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b:InvalidBucketName: The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName; Request ID: 16AFD789877C5B79; S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b)
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:224)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:111)
	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:265)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:261)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:236)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.createEmptyObject(S3AFileSystem.java:2786)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.createFakeDirectory(S3AFileSystem.java:2761)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerMkdirs(S3AFileSystem.java:2088)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:2021)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2275)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.write(WriteIntoDelta.scala:103)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1(WriteIntoDelta.scala:65)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1$adapted(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:188)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.run(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:148)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:362)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)

```

## Steps to Reproduce (for bugs)

1. Configure minio azure gateway to azure storage account
2. create dataframe in spark
2. set minio credentials on the spark context
3. write dataframe to minio url using delta format
```dataframe.write.format("delta").save("s3a://bucket/folder1/folder2")```

## Your Environment
* minio:latest azure gateway running in kubernetes 
* docker version 4.1.1
* docker engine 20.10.8

* Operating System and version (`uname -a`):
mac os catalina

**Comment by harshavardhana** [comment]
Azure Gateway's not meant to support all kinds of I/O @gbakthavatchalam especially Spark-related I/O please use MinIO server mode - this looks like some limitation that you might have observed.

**Comment by gbakthavatchalam** [comment]
Sorry @harshavardhana . The error shared previously was incorrect. 

below is the correct stacktrace

```
Exception in thread "main" org.apache.hadoop.fs.s3a.AWSBadRequestException: PUT 0-byte object  on bakthaminio/bakthaminio-randomchkminio-1634762164130-raw/_delta_log/: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName; Request ID: 16AFD789877C5B79; S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b), S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b:InvalidBucketName: The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName; Request ID: 16AFD789877C5B79; S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b)
	at org.apache.hadoop.fs.s3a.S3AUtils.translateException(S3AUtils.java:224)
	at org.apache.hadoop.fs.s3a.Invoker.once(Invoker.java:111)
	at org.apache.hadoop.fs.s3a.Invoker.lambda$retry$3(Invoker.java:265)
	at org.apache.hadoop.fs.s3a.Invoker.retryUntranslated(Invoker.java:322)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:261)
	at org.apache.hadoop.fs.s3a.Invoker.retry(Invoker.java:236)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.createEmptyObject(S3AFileSystem.java:2786)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.createFakeDirectory(S3AFileSystem.java:2761)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.innerMkdirs(S3AFileSystem.java:2088)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:2021)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:2275)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.write(WriteIntoDelta.scala:103)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1(WriteIntoDelta.scala:65)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.$anonfun$run$1$adapted(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.DeltaLog.withNewTransaction(DeltaLog.scala:188)
	at org.apache.spark.sql.delta.commands.WriteIntoDelta.run(WriteIntoDelta.scala:64)
	at org.apache.spark.sql.delta.sources.DeltaDataSource.createRelation(DeltaDataSource.scala:148)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:46)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:70)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:68)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:90)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$execute$1(SparkPlan.scala:180)
	at org.apache.spark.sql.execution.SparkPlan.$anonfun$executeQuery$1(SparkPlan.scala:218)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:215)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:176)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:132)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:131)
	at org.apache.spark.sql.DataFrameWriter.$anonfun$runCommand$1(DataFrameWriter.scala:989)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:103)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:163)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:90)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:775)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:989)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:438)
	at org.apache.spark.sql.DataFrameWriter.saveInternal(DataFrameWriter.scala:362)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:293)

```

**Comment by grcanosa** [comment]
I am having the same issue.
Using
- spark 3.1.1
- hadoop 3.2.0
- minio docker image version docker.io/bitnami/minio:2021.10.23-debian-10-r0

I can read correctly from any file but any write operation returns the same error. 

Did you had any luck solving the issue??
Thanks.

**Comment by vadmeste** [comment]
@gbakthavatchalam the error says, InvalidBucketName

```
Exception in thread "main" org.apache.hadoop.fs.s3a.AWSBadRequestException: PUT 0-byte object  on bakthaminio/bakthaminio-randomchkminio-1634762164130-raw/_delta_log/: com.amazonaws.services.s3.model.AmazonS3Exception: The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName; Request ID: 16AFD789877C5B79; S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b), S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b:InvalidBucketName: The specified bucket is not valid. (Service: Amazon S3; Status Code: 400; Error Code: InvalidBucketName; Request ID: 16AFD789877C5B79; S3 Extended Request ID: c94aa331-6398-4e74-8909-0ca6735cb10b)
```

What is your bucket name here ?

**Comment by grcanosa** [comment]
I have tried with different bucket names, including: data, data-hive, data2, test, ...
I always get the same error.

**Comment by vadmeste** [comment]
It looks like spark is sending empty object name here. We can confirm using `mc admin trace <alias>`. Before that, are you sure this script is supported 
```
dataframe.write.format("delta").save("s3a://bucket/folder1/folder2")
```

Can you try with AWS S3 first ?

**Comment by grcanosa** [comment]
Hi. 

I did't tried it with delta.

I am trying to do this: 

df.write.csv("s3a://bucket/test.csv")

and other variations. Any write operation fails with the same error. 

Sadly I don't have access to an AWS S3 right now.

**Comment by grcanosa** [comment]
Hi, I have tried running the mc admin trace command

```
2021-11-08T09:52:24:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv 10.1.0.225        171.348ms    ↑ 137 B ↓ 291 B
2021-11-08T09:52:24:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv/ 10.1.0.225        41.122ms     ↑ 137 B ↓ 291 B
2021-11-08T09:52:24:000 [200 OK] s3.ListObjectsV2 minio.infra-data.svc.cluster.local:9000/data/?list-type=2&delimiter=%2F&max-keys=1&prefix=test.csv%2F&fetch-owner=false  10.1.0.225        50.854ms     ↑ 137 B ↓ 581 B
2021-11-08T09:52:24:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv/_temporary/0 10.1.0.225        64.507ms     ↑ 137 B ↓ 291 B
2021-11-08T09:52:25:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv/_temporary/0/ 10.1.0.225        43.054ms     ↑ 137 B ↓ 291 B
2021-11-08T09:52:25:000 [200 OK] s3.ListObjectsV2 minio.infra-data.svc.cluster.local:9000/data/?list-type=2&delimiter=%2F&max-keys=1&prefix=test.csv%2F_temporary%2F0%2F&fetch-owner=false  10.1.0.225        43.26ms      ↑ 137 B ↓ 594 B
2021-11-08T09:52:25:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv/_temporary 10.1.0.225        47.609ms     ↑ 137 B ↓ 291 B
2021-11-08T09:52:25:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv/_temporary/ 10.1.0.225        44.598ms     ↑ 137 B ↓ 291 B
2021-11-08T09:52:25:000 [200 OK] s3.ListObjectsV2 minio.infra-data.svc.cluster.local:9000/data/?list-type=2&delimiter=%2F&max-keys=1&prefix=test.csv%2F_temporary%2F&fetch-owner=false  10.1.0.225        44.583ms     ↑ 137 B ↓ 592 B
2021-11-08T09:52:25:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv 10.1.0.225        43.156ms     ↑ 137 B ↓ 291 B
2021-11-08T09:52:25:000 [404 Not Found] s3.HeadObject minio.infra-data.svc.cluster.local:9000/data/test.csv/ 10.1.0.225        40.795ms     ↑ 137 B ↓ 291 B
2021-11-08T09:52:25:000 [200 OK] s3.ListObjectsV2 minio.infra-data.svc.cluster.local:9000/data/?list-type=2&delimiter=%2F&max-keys=1&prefix=test.csv%2F&fetch-owner=false  10.1.0.225        46.767ms     ↑ 137 B ↓ 581 B
2021-11-08T09:52:25:000 [200 OK] s3.ListObjectsV2 minio.infra-data.svc.cluster.local:9000/data/?list-type=2&delimiter=%2F&max-keys=1&prefix=&fetch-owner=false  10.1.0.225        43.679ms     ↑ 137 B ↓ 1.2 KiB
2021-11-08T09:52:25:000 [400 Bad Request] s3.PutObject minio.infra-data.svc.cluster.local:9000/data/test.csv/_temporary/0/ 10.1.0.225        59.875ms     ↑ 173 B ↓ 665 B
````
It seems to me that the bucket name is sent correctly. 

Is there any way to see why the request is responded with Bad Request ??

**Comment by grcanosa** [comment]
I have now the verbose stack:

```
minio.infra-data.svc.cluster.local:9000 [REQUEST s3.ListObjectsV2] [2021-11-08T09:56:40:000] [Client IP: 10.1.0.227]
minio.infra-data.svc.cluster.local:9000 GET /data/?list-type=2&delimiter=%2F&max-keys=1&prefix=&fetch-owner=false
minio.infra-data.svc.cluster.local:9000 Proto: HTTP/1.1
minio.infra-data.svc.cluster.local:9000 Host: minio.infra-data.svc.cluster.local:9000
minio.infra-data.svc.cluster.local:9000 X-Amz-Date: 20211108T095640Z
minio.infra-data.svc.cluster.local:9000 Amz-Sdk-Invocation-Id: adef5c4a-b37b-9390-3cfd-b3e42df4e02e
minio.infra-data.svc.cluster.local:9000 Amz-Sdk-Retry: 0/0/500
minio.infra-data.svc.cluster.local:9000 Authorization: AWS4-HMAC-SHA256 Credential=[AZURE_STORAGEACCOUNTNAME]/20211108/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=[SIGNATURE]8ab775d0c44a4fa93d0518d3284fa71c9f8ebe374e816f92d07943a8c8a53486
minio.infra-data.svc.cluster.local:9000 Content-Length: 0
minio.infra-data.svc.cluster.local:9000 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
minio.infra-data.svc.cluster.local:9000 Connection: Keep-Alive
minio.infra-data.svc.cluster.local:9000 Content-Type: application/octet-stream
minio.infra-data.svc.cluster.local:9000 User-Agent: Hadoop 3.2.0, aws-sdk-java/1.11.375 Linux/5.10.16.3-microsoft-standard-WSL2 OpenJDK_64-Bit_Server_VM/11.0.10+9 java/11.0.10 scala/2.12.10
minio.infra-data.svc.cluster.local:9000 
minio.infra-data.svc.cluster.local:9000 [RESPONSE] [2021-11-08T09:56:40:000] [ Duration 42.635ms  ↑ 137 B  ↓ 1.2 KiB ]
minio.infra-data.svc.cluster.local:9000 200 OK
minio.infra-data.svc.cluster.local:9000 Content-Security-Policy: block-all-mixed-content
minio.infra-data.svc.cluster.local:9000 Content-Type: application/xml
minio.infra-data.svc.cluster.local:9000 Server: MinIO
minio.infra-data.svc.cluster.local:9000 Vary: Origin,Accept-Encoding
minio.infra-data.svc.cluster.local:9000 X-Xss-Protection: 1; mode=block
minio.infra-data.svc.cluster.local:9000 Accept-Ranges: bytes
minio.infra-data.svc.cluster.local:9000 Content-Length: 873
minio.infra-data.svc.cluster.local:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
minio.infra-data.svc.cluster.local:9000 X-Amz-Request-Id: 16B589A98B5A53AD
minio.infra-data.svc.cluster.local:9000 X-Content-Type-Options: nosniff
minio.infra-data.svc.cluster.local:9000 <?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>data</Name><Prefix></Prefix><NextContinuationToken>e21pbmlvfTIhMTcyIU1EQXdNRGcwSVZaQ1luWXlXbTFOT0hKUGEyZFlSVmxOUW1kWVl6STVjMlJZVW5CaU1qVm1Xa2RzYUZvelNtaGlVelZyWTIxR00yRlhPRmQwUzJsaGVXUXlhRFowWTBSSFFVRlhOWFp4WjJkTmRXYzJkR05FUVVGQlBTRXdNREF3TWpnaE1qQXlNUzB4TVMwd09GUXdPVG8xTmpvek9TNHdOVFl5TVRFMldpRS0=</NextContinuationToken><KeyCount>1</KeyCount><MaxKeys>1</MaxKeys><Delimiter>/</Delimiter><IsTruncated>true</IsTruncated><Contents><Key>Datos prueba MN.csv</Key><LastModified>2021-11-08T09:26:54.000Z</LastModified><ETag>&#34;0x8D9A299E78B2440-1&#34;</ETag><Size>2158838</Size><Owner><ID>02d6176db174dc93cb1b899f7c6078f08654445fe8cf1b6ce98d8855f66bdbf4</ID><DisplayName>minio</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
minio.infra-data.svc.cluster.local:9000 
minio.infra-data.svc.cluster.local:9000 [REQUEST s3.PutObject] [2021-11-08T09:56:40:000] [Client IP: 10.1.0.227]
minio.infra-data.svc.cluster.local:9000 PUT /data/test.csv/_temporary/0/
minio.infra-data.svc.cluster.local:9000 Proto: HTTP/1.1
minio.infra-data.svc.cluster.local:9000 Host: minio.infra-data.svc.cluster.local:9000
minio.infra-data.svc.cluster.local:9000 Connection: Keep-Alive
minio.infra-data.svc.cluster.local:9000 Content-Length: 86
minio.infra-data.svc.cluster.local:9000 Content-Type: application/octet-stream
minio.infra-data.svc.cluster.local:9000 X-Amz-Date: 20211108T095640Z
minio.infra-data.svc.cluster.local:9000 X-Amz-Decoded-Content-Length: 0
minio.infra-data.svc.cluster.local:9000 Amz-Sdk-Invocation-Id: 6ea8c4bd-dd47-53cd-ab91-485f6f8eb384
minio.infra-data.svc.cluster.local:9000 Amz-Sdk-Retry: 0/0/500
minio.infra-data.svc.cluster.local:9000 Authorization: AWS4-HMAC-SHA256 Credential=[AZURE STORAGE ACCOUNT NAME]/20211108/us-east-1/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=[SIGNATURE (DIFFERENT THAN PREVIOUS ONE)]
minio.infra-data.svc.cluster.local:9000 Expect: 100-continue
minio.infra-data.svc.cluster.local:9000 User-Agent: Hadoop 3.2.0, aws-sdk-java/1.11.375 Linux/5.10.16.3-microsoft-standard-WSL2 OpenJDK_64-Bit_Server_VM/11.0.10+9 java/11.0.10 scala/2.12.10
minio.infra-data.svc.cluster.local:9000 X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
minio.infra-data.svc.cluster.local:9000 <BODY>
minio.infra-data.svc.cluster.local:9000 [RESPONSE] [2021-11-08T09:56:41:000] [ Duration 56.091ms  ↑ 173 B  ↓ 665 B ]
minio.infra-data.svc.cluster.local:9000 400 Bad Request
minio.infra-data.svc.cluster.local:9000 Content-Length: 340
minio.infra-data.svc.cluster.local:9000 Content-Security-Policy: block-all-mixed-content
minio.infra-data.svc.cluster.local:9000 Server: MinIO
minio.infra-data.svc.cluster.local:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
minio.infra-data.svc.cluster.local:9000 X-Xss-Protection: 1; mode=block
minio.infra-data.svc.cluster.local:9000 Accept-Ranges: bytes
minio.infra-data.svc.cluster.local:9000 Content-Type: application/xml
minio.infra-data.svc.cluster.local:9000 Vary: Origin,Accept-Encoding
minio.infra-data.svc.cluster.local:9000 X-Amz-Request-Id: 16B589A98E727F8A
minio.infra-data.svc.cluster.local:9000 X-Content-Type-Options: nosniff
minio.infra-data.svc.cluster.local:9000 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidBucketName</Code><Message>The specified bucket is not valid.</Message><Key>test.csv/_temporary/0/</Key><BucketName>data</BucketName><Resource>/data/test.csv/_temporary/0/</Resource><RequestId>16B589A98E727F8A</RequestId><HostId>7c522012-4fe8-4b76-8ae9-5ac173f0f07c</HostId></Error>
minio.infra-data.svc.cluster.local:9000
```

**Comment by grcanosa** [comment]
And this is the trace when I copy an object using the minio client:

```
localhost:9000 [REQUEST s3.PutObject] [2021-11-08T10:45:49:000] [Client IP: 127.0.0.1]
localhost:9000 PUT /data/test_file.pdf
localhost:9000 Proto: HTTP/1.1
localhost:9000 Host: localhost:9000
localhost:9000 X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD
localhost:9000 X-Amz-Date: 20211108T104549Z
localhost:9000 X-Amz-Decoded-Content-Length: 116326
localhost:9000 Authorization: AWS4-HMAC-SHA256 Credential=[AZURE STORAGEACCOUNTNAME]/20211108/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length,Signature=[SIGNATURE (different one)]
localhost:9000 Content-Length: 116591
localhost:9000 Content-Type: application/pdf
localhost:9000 User-Agent: MinIO (windows; amd64) minio-go/v7.0.15 mc.exe/RELEASE.2021-11-05T10-05-06Z
localhost:9000 <BODY>
localhost:9000 [RESPONSE] [2021-11-08T10:45:49:000] [ Duration 348.802ms  ↑ 114 KiB  ↓ 325 B ]
localhost:9000 200 OK
localhost:9000 Accept-Ranges: bytes
localhost:9000 Content-Length: 0
localhost:9000 Content-Security-Policy: block-all-mixed-content
localhost:9000 Server: MinIO
localhost:9000 Strict-Transport-Security: max-age=31536000; includeSubDomains
localhost:9000 Vary: Origin,Accept-Encoding
localhost:9000 ETag: "37607980bd339545f5ed95c6b5e5ad42"
localhost:9000 X-Amz-Request-Id: 16B58C57FE928DB1
localhost:9000 X-Content-Type-Options: nosniff
localhost:9000 X-Xss-Protection: 1; mode=block
localhost:9000 <BODY>
```

**Comment by vadmeste** [comment]
```
minio.infra-data.svc.cluster.local:9000 PUT /data/test.csv/_temporary/0/
```

It looks like your storage account doesn't support an object name with a trailing slash in it. I tested with a normal storage account and it works but you are probably enabling some specific features in your storage account here, ADLSv2 ?

Anyway we can't do much here.

**Comment by grcanosa** [comment]
OMG! That was it. I created a new storage account but i didn't enable the hierarchical namespace feature and I think it works!! :) Thank you soo much!!

I have to run all the other tests but I think that was it!

**Comment by gbakthavatchalam** [comment]
Yes @grcanosa . Minio does not work with Azure Data Lake Gen 2 Storage Account. Whereas I found it to work nicely on Gen 1 storage accounts

**Comment by vadmeste** [comment]
>  Minio does not work with Azure Data Lake Gen 2 Storage Account

It does. It just doesn't handle a trailing slash in object names when the backend does not support it.

**Comment by harshavardhana** [comment]
> Yes @grcanosa . Minio does not work with Azure Data Lake Gen 2 Storage Account. Whereas I found it to work nicely on Gen 1 storage accounts

We are limited by what Azure can support @gbakthavatchalam

**Comment by harshavardhana** [comment]
@ravindk89 @vadmeste we should document this perhaps?

**Comment by ravindk89** [comment]
Yeah - migrating the legacy gateway docs to nextgen is on my list, and I can include this restriction as part of that work.
