### ISSUE TITLE
Uncatch SSL certification error when using MinIO python API to access remote bucket

### ISSUE THREAD

**Issue by FrostNova2021** [minio/minio#14428]
I'm running a MinIO docker and learn how to using minio python api,but the minio docker of https SSL certification maybe unsupport verifiy.

install docker script:
```
mkdir /data
docker pull minio/minio
docker run --name minio -p 9000:9000 -p 9090:9090 -e "MINIO_ROOT_USER=user" -e "MINIO_ROOT_PASSWORD=password" -v /data:/data  minio/minio server /data --console-address ":9090" --address ":9000"
```

and try using python api to access minio with access key and secret key:
```
$ python3
Python 3.8.10 (default, Nov 26 2021, 20:14:08)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from minio import Minio
>>> minio_client = Minio('192.168.21.149:9090','test_akak','test_sksk')
>>> minio_client.bucket_exists('test')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 996, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 366, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 383, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fuzzing/.local/lib/python3.8/site-packages/minio/api.py", line 652, in bucket_exists
    self._execute("HEAD", bucket_name)
  File "/home/fuzzing/.local/lib/python3.8/site-packages/minio/api.py", line 394, in _execute
    region = self._get_region(bucket_name, None)
  File "/home/fuzzing/.local/lib/python3.8/site-packages/minio/api.py", line 461, in _get_region
    response = self._url_open(
  File "/home/fuzzing/.local/lib/python3.8/site-packages/minio/api.py", line 266, in _url_open
    response = self._http.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/poolmanager.py", line 330, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 747, in urlopen
    return self.urlopen(
  [Previous line repeated 2 more times]
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='192.168.21.149', port=9090): Max retries exceeded with url: /test?location= (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1131)')))
>>>
```

## Your Environment
=== MinIO Docker ===
2022-02-26T02:54:46Z

===  Client  ===
python 3.8.10
> import minio
> minio.__version__
> '7.1.4'

**Comment by klauspost** [comment]
Just google, could you check if this is your problem: https://stackoverflow.com/a/66656188/681490

**Comment by klauspost** [comment]
(tried to move this to [minio-py](https://github.com/minio/minio-py), but doesn't appear to work currectly)
