### ISSUE TITLE
Api: Server crash on setting invalid regexp characters. 

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1482]
`mc access writeonly myminio/exp/o*` crashes the server. The following is the error output by mc 

`mc: <ERROR> Unable to set access permission ‘writeonly’ for ‘myminio/exp/o*’. Put http://localhost:9000/exp/?policy=: Connection closed by foreign host http://localhost:9000/exp/?policy=. Retry again.` . 

Regexp match for invalid characters should be handled.

**Comment by harshavardhana** [comment]
```
2016/05/05 19:21:32 http: panic serving [::1]:65305: regexp: Compile(`testbucket/o**`): error parsing regexp: invalid nested repetition operator: `**`
goroutine 68 [running]:
net/http.(*conn).serve.func1(0xc82025ac00)
    /usr/local/opt/go/libexec/src/net/http/server.go:1389 +0xc1
panic(0x506f20, 0xc820156bf0)
    /usr/local/opt/go/libexec/src/runtime/panic.go:426 +0x4e9
regexp.MustCompile(0xc820271fad, 0xe, 0x10)
    /usr/local/opt/go/libexec/src/regexp/regexp.go:232 +0x16f
main.checkBucketPolicyResources(0xc8204669c5, 0xa, 0xc820156a50, 0xa, 0xc8203fc240, 0x5, 0x5, 0x5)
    /Users/harsha/mygo/src/github.com/minio/minio/bucket-policy-parser.go:244 +0x5b4
main.objectAPIHandlers.PutBucketPolicyHandler(0x1905750, 0xc820236ba0, 0x190c098, 0xc820140270, 0xc820411a40)
    /Users/harsha/mygo/src/github.com/minio/minio/bucket-policy-handlers.go:207 +0x514
main.(objectAPIHandlers).PutBucketPolicyHandler-fm(0x190c098, 0xc820140270, 0xc820411a40)
    /Users/harsha/mygo/src/github.com/minio/minio/api-router.go:68 +0x4a
net/http.HandlerFunc.ServeHTTP(0xc8202cfaa0, 0x190c098, 0xc820140270, 0xc820411a40)
    /usr/local/opt/go/libexec/src/net/http/server.go:1618 +0x3a
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc8200145f0, 0x190c098, 0xc820140270, 0xc820411a40)
```
