### ISSUE TITLE
handlers: restic functional test crash with released binary - darwin

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1502]
```
AccessKey: KEBIYDZ87HCIH5D17YCN  SecretKey: bVX1KhipSBPopEfmhc7rGz8ooxx27xdJ7Gkh1mVe  Region: us-east-1
Minio Object Storage:
    http://127.0.0.1:9000
Minio Browser:
    http://127.0.0.1:9000
To configure Minio Client:
    $ wget https://dl.minio.io/client/mc/release/darwin-amd64/mc
    $ chmod 755 mc
    $ ./mc config host add myminio http://localhost:9000 KEBIYDZ87HCIH5D17YCN bVX1KhipSBPopEfmhc7rGz8ooxx27xdJ7Gkh1mVe
CI: stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x3261af]
goroutine 122 [running]:
panic(0x536920, 0x8209f0110)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
bufio.(*Writer).WriteString(0x0, 0x6483c0, 0x19, 0x45fb60, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/bufio/bufio.go:660 +0x3f
net/http.(*expectContinueReader).Read(0x820e03a40, 0x8214a0000, 0x8000, 0x8000, 0x7df06, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:636 +0xc7
io.(*LimitedReader).Read(0x820dfbb20, 0x8214a0000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:426 +0xbd
io.copyBuffer(0x8820a3c778, 0x820dfbb00, 0x8820a7eb40, 0x820dfbb20, 0x8214a0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:380 +0x247
io.Copy(0x8820a3c778, 0x820dfbb00, 0x8820a7eb40, 0x820dfbb20, 0x820dfbb00, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:350 +0x64
io.CopyN(0x8820a3c778, 0x820dfbb00, 0x8820a3c7a0, 0x820e03a40, 0x500000, 0x0, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:326 +0xf7
main.objectStorageAPI.PutObjectPartHandler.func1(0x820b92578, 0x821426620, 0x500000, 0x1)
    /home/builder/mygo/src/github.com/minio/minio/object-handlers.go:810 +0x1fb
created by main.objectStorageAPI.PutObjectPartHandler
    /home/builder/mygo/src/github.com/minio/minio/object-handlers.go:832 +0xf32
command [go test -cover -coverprofile /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/gotestcover-571319138 restic/backend/s3]: exit status 1
tests.go:279: unexpected error: Put http://127.0.0.1:9000/restictestbucket/data/0000000000000000000000000000000000000000000000000000000000000000-1?partNumber=1&uploadId=e02b7ff1-0724-4679-b4ac-50188449bcc6: dial tcp 127.0.0.1:9000: getsockopt: connection refused
--- FAIL: TestS3BackendSave (0.97s)
--- FAIL: TestS3BackendSaveFilenames (0.00s)
    tests.go:52: Open returned unexpected error: Put http://127.0.0.1:9000/restictestbucket/?location=: dial tcp 127.0.0.1:9000: getsockopt: connection refused
--- FAIL: TestS3BackendBackend (0.00s)
    tests.go:52: Open returned unexpected error: Put http://127.0.0.1:9000/restictestbucket/?location=: dial tcp 127.0.0.1:9000: getsockopt: connection refused
--- FAIL: TestS3BackendDelete (0.00s)
    tests.go:52: Open returned unexpected error: Put http://127.0.0.1:9000/restictestbucket/?location=: dial tcp 127.0.0.1:9000: getsockopt: connection refused
FAIL
coverage: 68.1% of statements
FAIL    restic/backend/s3   2.082s
ok      restic/backend/sftp 0.049s  coverage: 13.5% of statements
ok      restic/backend/test 0.440s  coverage: 75.4% of statements
ok      restic/checker  8.267s  coverage: 75.7% of statements
ok      restic/crypto   0.527s  coverage: 64.6% of statements
?       restic/debug    [no test files]
ok      restic/filter   0.335s  coverage: 84.8% of statements
?       restic/fs   [no test files]
ok      restic/fuse 0.885s  coverage: 31.2% of statements
ok      cmds/restic 186.673s    coverage: 47.0% of statements
ok      restic/location 0.030s  coverage: 87.5% of statements
ok      restic/pack 0.059s  coverage: 74.0% of statements
ok      restic/pipe 0.101s  coverage: 78.9% of statements
?       restic/test [no test files]
ok      restic/worker   0.034s  coverage: 100.0% of statements
ok      restic/repository   11.744s coverage: 62.5% of statements
test failed
error: error running gotestcover -coverprofile all.cov cmds/... restic/...: exit status 1
CI: run travis teardown
CI: stopping minio server
CI: minio server returned error: exit status 2
CI: stdout: foo
AccessKey: KEBIYDZ87HCIH5D17YCN  SecretKey: bVX1KhipSBPopEfmhc7rGz8ooxx27xdJ7Gkh1mVe  Region: us-east-1
Minio Object Storage:
    http://127.0.0.1:9000
Minio Browser:
    http://127.0.0.1:9000
To configure Minio Client:
    $ wget https://dl.minio.io/client/mc/release/darwin-amd64/mc
    $ chmod 755 mc
    $ ./mc config host add myminio http://localhost:9000 KEBIYDZ87HCIH5D17YCN bVX1KhipSBPopEfmhc7rGz8ooxx27xdJ7Gkh1mVe
CI: stderr: panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x18 pc=0x3261af]
goroutine 122 [running]:
panic(0x536920, 0x8209f0110)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
bufio.(*Writer).WriteString(0x0, 0x6483c0, 0x19, 0x45fb60, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/bufio/bufio.go:660 +0x3f
net/http.(*expectContinueReader).Read(0x820e03a40, 0x8214a0000, 0x8000, 0x8000, 0x7df06, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:636 +0xc7
io.(*LimitedReader).Read(0x820dfbb20, 0x8214a0000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:426 +0xbd
io.copyBuffer(0x8820a3c778, 0x820dfbb00, 0x8820a7eb40, 0x820dfbb20, 0x8214a0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:380 +0x247
io.Copy(0x8820a3c778, 0x820dfbb00, 0x8820a7eb40, 0x820dfbb20, 0x820dfbb00, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:350 +0x64
io.CopyN(0x8820a3c778, 0x820dfbb00, 0x8820a3c7a0, 0x820e03a40, 0x500000, 0x0, 0x0, 0x0)
    /home/builder/.gimme/versions/go1.6.linux.amd64/src/io/io.go:326 +0xf7
main.objectStorageAPI.PutObjectPartHandler.func1(0x820b92578, 0x821426620, 0x500000, 0x1)
    /home/builder/mygo/src/github.com/minio/minio/object-handlers.go:810 +0x1fb
created by main.objectStorageAPI.PutObjectPartHandler
    /home/builder/mygo/src/github.com/minio/minio/object-handlers.go:832 +0xf32
```

**Comment by harshavardhana** [comment]
// cc @fd0

**Comment by fd0** [comment]
Oh, did you manage to track it down? Or is the output above from the restic travis run?

**Comment by fd0** [comment]
I can try to minimize the test for the crash to occur...

**Comment by fd0** [comment]
Preliminary results: The crash depends on the directory used for `minio`. 

Using something like `minio-srv` in the local directory did not produce the crash (but some other failures I haven't investigated further): https://travis-ci.org/restic/restic/builds/128544141

My integration tests use a directory in `$TMPDIR`, which is set to something like `/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/` on Travis CI. This is a log of the crash:
https://travis-ci.org/restic/restic/builds/128546141

Output on stderr is:

```
time="2016-05-07T18:30:44Z" level=fatal msg="Unable to validate the path" error="stat /var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/ci-test.63TV3hUd\nminio-server-rFtNlT: no such file or directory" probe="{\"cause\":{\"Op\":\"stat\",\"Path\":\"/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/ci-test.63TV3hUd\\nminio-server-rFtNlT\",\"Err\":2},\"trace\":[{\"line\":269,\"file\":\"server-main.go\",\"func\":\"main.serverMain\"}],\"sysinfo\":{\"host.arch\":\"amd64\",\"host.cpus\":\"2\",\"host.lang\":\"go1.6\",\"host.name\":\"Traviss-Mac-445.local\",\"host.os\":\"darwin\",\"mem.heap.total\":\"5.8MB\",\"mem.heap.used\":\"1.9MB\",\"mem.total\":\"8.8MB\",\"mem.used\":\"1.9MB\"}}"
```

I noticed that there is a stray `\n` in the path:

```
/var/folders/gw/_2jq29095y7b__wtby9dg_5h0000gn/T/ci-test.63TV3hUd\nminio-server-rFtNlT
```

This is the code from the `.travis.yml` that can be used to reproduce it: https://gist.github.com/e3c08c6e0bfc804fe1476e1466a3b3fd

**Comment by fd0** [comment]
Found the source of the stray `\n`: wrong use of `mktemp` on darwin.

**Comment by harshavardhana** [comment]
Going to close this! @fd0 - please reopen if you see this again.

**Comment by fd0** [comment]
will do, thanks!
