### ISSUE TITLE
MinIO Java SDK getPresignedObjectUrl get 403 forbidden: signature does not match

### ISSUE THREAD

**Issue by aliciz** [minio/minio#15173]
I configured nginx according to the example on the website [https://docs.min.io/docs/setup-nginx-proxy-with-minio.html]( https://docs.min.io/docs/setup-nginx-proxy-with-minio.html)

```
http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for" $http_host';

    access_log  logs/access.log  main;

    sendfile        on;
    keepalive_timeout  65;

    ignore_invalid_headers off;
    client_max_body_size 0;
    proxy_buffering off;

    upstream minio {
        least_conn;
        server 192.168.253.111:9000;
        server 192.168.253.112:9000;
    }

    server {
        listen       80;
        server_name  localhost;

        location /dev/ {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Host $http_host;

          proxy_connect_timeout 300;
          # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          chunked_transfer_encoding off;

          proxy_pass http://192.168.253.111:9000;
        }

        location / {
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
         proxy_set_header Host $http_host;

          proxy_connect_timeout 300;
          proxy_http_version 1.1;
          proxy_set_header Connection "";
          chunked_transfer_encoding off;
          proxy_pass http://192.168.253.111:9001;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }

}
```

JAVA SDK:
```
 public static void main(String[] args) {
        MinioClient minioClient = getClient();
        String url = uploadUrl(minioClient, "logo (2).jpg");
//        String url = donwloadUrl(minioClient);
//        String url = deleteUrl(minioClient);
    }

    static public String uploadUrl(MinioClient minioClient, String objectKey){
        String url = null;
        try {
            GetPresignedObjectUrlArgs build = GetPresignedObjectUrlArgs.builder()
                    .method(Method.PUT)
                    .bucket(bucket)
                    .object(objectKey)
                    .expiry(1, TimeUnit.HOURS)
                    .build();
            url = minioClient.getPresignedObjectUrl(build);
        } catch (ErrorResponseException e) {
            log.error("错误返回异常", e);
        } catch (InsufficientDataException e) {
            log.error("不充足数据异常", e);
        } catch (InternalException e) {
            log.error("内部异常", e);
        } catch (InvalidKeyException e) {
            log.error("key不正确异常", e);
        } catch (InvalidResponseException e) {
            log.error("不正确返回异常", e);
        } catch (IOException e) {
            log.error("IO异常", e);
        } catch (NoSuchAlgorithmException e) {
            log.error("无此算法异常", e);
        } catch (XmlParserException e) {
            log.error("xml转换异常", e);
        } catch (ServerException e) {
            log.error("服务器异常", e);
        }
        System.out.println(url);
        return url;
    }
```
when i run this code,i get the exception:

```
io.minio.errors.ErrorResponseException: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	at io.minio.S3Base$1.onResponse(S3Base.java:690)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
null
```

finally i found that modify nginx config:

```
 location /dev/ {
   // ....//

 }
```
TO

```
 location /dev {
   // ....//

 }
```

Program can run fine. why?  the nginx example is wrong?

## Environment
```
minio version RELEASE.2022-06-17T02-00-35Z (commit-id=55ee94bed030874c35c8adc85f2d942765231f33)
Runtime: go1.18.3 linux/amd64
Copyright (c) 2015-2022 MinIO, Inc.
Licence AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
```
sdk dependencies:
```
<dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.10.0</version>
        </dependency>
        <dependency>
            <groupId>io.minio</groupId>
            <artifactId>minio</artifactId>
            <version>8.4.2</version>
            <exclusions>
                <exclusion>
                    <groupId>com.squareup.okhttp3</groupId>
                    <artifactId>okhttp</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by harshavardhana** [comment]
> location /dev/ {
>           proxy_set_header X-Real-IP $remote_addr;
>           proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>           proxy_set_header X-Forwarded-Proto $scheme;
>           proxy_set_header Host $http_host;
> 
>           proxy_connect_timeout 300;
>           # Default is HTTP/1, keepalive is only enabled in HTTP/1.1
>           proxy_http_version 1.1;
>           proxy_set_header Connection "";
>           chunked_transfer_encoding off;
> 
>           proxy_pass http://192.168.253.111:9000;
>         }

You cannot do these kinds of nginx settings S3 API must land at `/` not at custom prefixes.
