### ISSUE TITLE
Set subpath to api from ingress of k8s

### ISSUE THREAD

**Issue by murata-yu** [minio/minio#15281]
Hi, there.

I used [this chart](https://artifacthub.io/packages/helm/bitnami/minio) to deploy minio on k8s.

Error occurs when I try to operate resource with `boto3` by setting  apiIngress.path to something other than `/` (e.g. `/minio_api (/ | $) (. *)` ) and specifying `https:// <hostname><apiIngress.path>` as endpoint.

## Expected Behavior
Here is the code to reproduce my problem.

```yaml
# values.yaml

apiIngress:
  tls: true  
  enabled: true
  selfSigned: true

  ingressClassName=nginx
  hostname=minio-api.dev-01.com

  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  path: /minio_api(/|$)(.*)
```

```python
# minio-test.py

import boto3
import os

host = 'minio-api.dev-01.com'
path = '/minio-api'
endpoint = f"https://{host}{path}"

access_key = 'admin'
secret_key = 'admin'

os.environ['no_proxy'] += f',{host}'

resource = boto3.resource('s3',
                          endpoint_url=endpoint,
                          aws_access_key_id=access_key,
                          aws_secret_access_key=secret_key,
                          verify=False)

for bucket in resource.buckets.all():
    print(bucket)
```

Expected results
```
s3.Bucket(name='mybucket1')
s3.Bucket(name='mybucket2')
```

## Current Behavior

```
Traceback (most recent call last):
  File "test/minio-test.py", line 19, in <module>
    for bucket in resource.buckets.all():
  File "/opt/deepops/env/lib/python3.8/site-packages/boto3/resources/collection.py", line 81, in __iter__
    for page in self.pages():
  File "/opt/deepops/env/lib/python3.8/site-packages/boto3/resources/collection.py", line 166, in pages
    pages = [getattr(client, self._py_operation_name)(**params)]
  File "/opt/deepops/env/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/deepops/env/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SignatureDoesNotMatch) when calling the ListBuckets operation: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

## Possible Solution
- If `path` is set to `/`, it works correctly.
- If `path` is wrong(e.g.  `/minio-API`), it returns 404 code.
```
Traceback (most recent call last):
  File "test/minio-test.py", line 19, in <module>
    for bucket in resource.buckets.all():
  File "/opt/deepops/env/lib/python3.8/site-packages/boto3/resources/collection.py", line 81, in __iter__
    for page in self.pages():
  File "/opt/deepops/env/lib/python3.8/site-packages/boto3/resources/collection.py", line 166, in pages
    pages = [getattr(client, self._py_operation_name)(**params)]
  File "/opt/deepops/env/lib/python3.8/site-packages/botocore/client.py", line 508, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/deepops/env/lib/python3.8/site-packages/botocore/client.py", line 915, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the ListBuckets operation: Not Found
```

So I don't think I made a mistake in the password or URL.

## Steps to Reproduce (for bugs)
1. make `values.yaml` and `minio-test.py`
2. `helm repo add minio https://charts.bitnami.com/bitnami/` 
3. `helm repo update`
4. `helm upgrade --install minio bitnami/minio --version 11.7.7 -f vallues.yaml`
6. `pip install boto3==1.24.23 `
7. `python minio-test.py` 

### minio version
```
●  minio:9000
   Uptime: 6 days 
   Version: 2022-06-25T15:50:16Z
   Network: 1/1 OK 
   Drives: 1/1 OK 
   Pool: 1st
```

### k8s version
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:09:28Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"9dd794e454ac32d97cde41ae10be801ae98f75df", GitTreeState:"clean", BuildDate:"2021-03-18T01:00:06Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

### helm version
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.15.8"}
```

### python version
```
Python 3.8.10
```

### boto3 version
```
boto3==1.24.23  
```

### OS version
```
Linux controlplane 5.4.0-91-generic #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by vadmeste** [comment]
@murata-yu S3 spec protects against the request path tampering. You cannot make your load balancer modifying it.
