### ISSUE TITLE
minio server returns MalformedXML when unknown region is passed

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1531]
When running minio-java functional test on minio server, it returns `MalformedXML` error when unknown region is passed.  

```
Test: makeBucket(String bucketName, String region)
error occured
ErrorResponse(code=MalformedXML, message=The XML you provided was not well-formed or did not validate against our published schema., bucketName=null,\
 objectName=null, resouce=/minio-java-test-2br5vju, requestId=3L137, hostId=3L137)
request={method=PUT, url=http://127.0.0.1:60000/minio-java-test-2br5vju, headers=x-amz-acl: private
Host: 127.0.0.1:60000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: 1cbf7893f59961cfa0cfd9f69b54229248bc9c5d83e0fb974f0e2c7578927e56
x-amz-date: 20160508T095433Z
Authorization: AWS4-HMAC-SHA256 Credential=B4TDG3O5V27UBVY3UG6V/20160508/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-acl;x-amz-content-sha256\
;x-amz-date, Signature=43c4268bae3fe96567a0bf4de38b8e335e54a6b2aa3d6cd54a5d63ab4df762c7
Content-Type: application/octet-stream
Transfer-Encoding: chunked
}
response={code=400, headers=Accept-Ranges: bytes
Server: Minio/DEVELOPMENT.2016-05-08T09-37-27Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: H4RF3EYP9MYOXIDU
Date: Sun, 08 May 2016 09:54:33 GMT
Content-Type: text/xml; charset=utf-8
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1462701273970
OkHttp-Received-Millis: 1462701273977
}

        at io.minio.MinioClient.execute(MinioClient.java:789)
        at io.minio.MinioClient.executePut(MinioClient.java:950)
        at io.minio.MinioClient.makeBucket(MinioClient.java:1808)
        at io.minio.MinioClient.makeBucket(MinioClient.java:1744)
        at FunctionalTest.makeBucket_test2(FunctionalTest.java:100)
        at FunctionalTest.main(FunctionalTest.java:690)

```

Is it expected behaviour?

**Comment by harshavardhana** [comment]
Can you paste the request body sent from the java code?

**Comment by balamurugana** [comment]
Request body:

```
 <?xml version="1.0"?><CreateBucketConfiguration xmlns=""><LocationConstraint>eu-west-1</LocationConstraint></CreateBucketConfiguration>
```

**Comment by harshavardhana** [comment]
> <?xml version="1.0"?><CreateBucketConfiguration xmlns=""><LocationConstraint>eu-west-1</LocationConstraint></CreateBucketConfiguration>

The namespace is wrong - `xmlns=""` should not be empty it should be, unmarshalling fails because of this. 

http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html

```
<CreateBucketConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"> 
  <LocationConstraint>BucketRegion</LocationConstraint> 
  </CreateBucketConfiguration>
```

**Comment by abperiasamy** [comment]
Even if Amazon S3 is relaxed about incorrect input, lets not encourage bad behavior. MalformedXML response is appropriate.
