### ISSUE TITLE
GetObjectAsync error: MinIO API responded with message=Connection error:'0xEF' is an invalid start of a value. 

### ISSUE THREAD

**Issue by mocsharp** [minio/minio#15453]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

With latest `minio/minio:latest` ([af60396902a1](https://hub.docker.com/layers/minio/minio/latest/images/sha256-af60396902a133ed33afaf3c27491e5d6ef8df3849b1a8d50e4b3fa1a462ea24?context=explore)) release, the get object API is returning the following using minio.net

```
 Minio.Exceptions.ConnectionException : MinIO API responded with message=Connection error:'0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.. Status code=0, response='0xEF' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0., content=
  Stack Trace:
     at Minio.MinioClient.ParseErrorNoContent(ResponseResult response) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 602
   at Minio.MinioClient.ParseError(ResponseResult response) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 585
   at Minio.MinioClient.<>c.<.ctor>b__130_0(ResponseResult response) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 54
   at Minio.MinioClient.HandleIfErrorResponse(ResponseResult response, IEnumerable`1 handlers, DateTime startTime) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 782
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, HttpRequestMessageBuilder requestMessageBuilder, CancellationToken cancellationToken, Boolean isSts) in /root/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 563
   at Minio.MinioClient.getObjectStreamAsync(GetObjectArgs args, ObjectStat objectStat, Action`1 cb, CancellationToken cancellationToken) in /root/.q/sources/minio-dotnet/Minio/Helper/OperationsHelper.cs:line 111
   at Minio.MinioClient.getObjectHelper(GetObjectArgs args, CancellationToken cancellationToken) in /root/.q/sources/minio-dotnet/Minio/Helper/OperationsHelper.cs:line 55
```

## Expected Behavior
Expect the `GetObjectAsync` call to stream the requested objects back.

## Current Behavior
Throwing error as describe above.

## Possible Solution

For now, `RELEASE.2022-07-30T05-21-40Z` works without any issue.

## Steps to Reproduce (for bugs)

1. Download any given object on minio.
E.g.
```
var getMetadataObjectArgs = new GetObjectArgs()
              .WithBucket("my-bucket")
              .WithObject($"some-file-on-minio")
              .WithCallbackStream((stream) =>
              {
                  using var memoryStream = new MemoryStream();
                  stream.CopyTo(memoryStream);
                  ...
              });
          await minioClient.GetObjectAsync(getMetadataObjectArgs);

```

## Regression
Is this issue a regression? Yes 

```
minio/minio:latest
DIGEST:sha256:af60396902a133ed33afaf3c27491e5d6ef8df3849b1a8d50e4b3fa1a462ea24
```
## Your Environment

* Version used (`minio --version`):
* Server setup and configuration:
* Operating System and version (`uname -a`):
```
Linux ubuntu 5.4.0-122-generic #138-Ubuntu SMP Wed Jun 22 15:00:31 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```
Client: Docker Engine - Community
 Version:           20.10.16
 API version:       1.41
 Go version:        go1.17.10
 Git commit:        aa7e414
 Built:             Thu May 12 09:17:23 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.16
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.10
  Git commit:       f756502
  Built:            Thu May 12 09:15:28 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b638
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by harshavardhana** [comment]
@mocsharp whats your endpoint configuration?
