### ISSUE TITLE
XL: A disk disappears while multipart or single put object is in progress causes NoSuchBucket error (May-12)

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1552]
Below is the test trace

```
Test: multipart: putObject(String bucketName, String objectName, String fileName)
error occured
ErrorResponse(code=NoSuchBucket, message=The specified bucket does not exist., bucketName=null, objectName=null, resouce=/minio-java-test-2jv692u, re\
questId=3L137, hostId=3L137)
request={method=GET, url=http://127.0.0.1:60000/minio-java-test-2jv692u?max-uploads=1000&upload-id-marker&prefix=minio-java-test-a4o6fm&delimiter&key\
-marker&uploads=, headers=Host: 127.0.0.1:60000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20160509T060923Z
Authorization: AWS4-HMAC-SHA256 Credential=B4TDG3O5V27UBVY3UG6V/20160509/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-dat\
e, Signature=7deb48e1d16f3a6adbd3bfe1097f65828bc7dd21789c7c974693da2993a196ec
}
response={code=404, headers=Accept-Ranges: bytes
Server: Minio/DEVELOPMENT.2016-05-08T09-37-27Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: N1HCPPPKWRM112M1
Date: Mon, 09 May 2016 06:09:23 GMT
Content-Type: text/xml; charset=utf-8
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1462774163626
OkHttp-Received-Millis: 1462774163733
}

        at io.minio.MinioClient.execute(MinioClient.java:790)
        at io.minio.MinioClient.executeGet(MinioClient.java:869)
        at io.minio.MinioClient.listIncompleteUploads(MinioClient.java:2423)
        at io.minio.MinioClient.access$100(MinioClient.java:93)
        at io.minio.MinioClient$3$1.populate(MinioClient.java:2288)
        at io.minio.MinioClient$3$1.hasNext(MinioClient.java:2323)
        at io.minio.MinioClient.getLatestIncompleteUploadId(MinioClient.java:2191)
        at io.minio.MinioClient.putObject(MinioClient.java:2125)
        at io.minio.MinioClient.putObject(MinioClient.java:1996)
        at FunctionalTest.putObject_test2(FunctionalTest.java:208)
        at FunctionalTest.main(FunctionalTest.java:708)

```

**Comment by harshavardhana** [comment]
@balamurugana can you test with latest master?

**Comment by balamurugana** [comment]
With 

```
$ minio version
Version: 2016-05-10T13:34:20Z
Release-Tag: DEVELOPMENT.2016-05-10T13-34-20Z
Commit-ID: 409e09c1e55ab448419a3d62cd8a5704312b2172

```

I am getting `InternalError`

**Comment by balamurugana** [comment]
Steps to reproduce the issue
1. Run minio server

``` shell
minio server --address=:60000 /mnt/sd{b..e}1/bala/mydisk
```
1. Run minio-java function test

``` shell
javac -cp 'build/libs/minio-1.0.2.jar:/home/bala/java/jar/*' test/FunctionalTest.java
java -cp 'build/libs/minio-1.0.2.jar:/home/bala/java/jar/*:test' FunctionalTest http://127.0.0.1:60000 HRNO0T03JQ31CIFJH1K0 dwb4p7eexrUP6JzBmF6IlIHxSch/NQSPTb/V3SWt
```
1. While `Test: multipart: putObject(String bucketName, String objectName, String fileName)` in progress, run below command

``` shell
rm -fr /mnt/sde1/bala/mydisk
```
1. We get `InternalError`

**Comment by harshavardhana** [comment]
> Steps to reproduce the issue
> 1. Run minio server
> 
> minio server --address=:60000 /mnt/sd{b..e}1/bala/mydisk
> Run minio-java function test
> javac -cp 'build/libs/minio-1.0.2.jar:/home/bala/java/jar/_' test/FunctionalTest.java
> java -cp 'build/libs/minio-1.0.2.jar:/home/bala/java/jar/_:test' FunctionalTest http://127.0.0.1:60000 HRNO0T03JQ31CIFJH1K0 dwb4p7eexrUP6JzBmF6IlIHxSch/NQSPTb/V3SWt
> While Test: multipart: putObject(String bucketName, String objectName, String fileName) in progress, run below command
> rm -fr /mnt/sde1/bala/mydisk
> We get InternalError

Yeah now the POSIX sends errDiskNotFound, which should be handled inside CreateFile.

**Comment by balamurugana** [comment]
The error occurred in below code path

```
ERRO[0404] listOnlineDisks failed with file not found    path=multipart/minio-java-test-n74mbk/minio-java-test-ur52lp/82e6e021-e989-4a53-94b0-81a8efcea224/00000.incomplete volume=.minio
ERRO[0406] CreateFile failed with mkdir tmp/d6/.minio/tmp/minio-java-test-n74mbk: no such file or directory  path=tmp/minio-java-test-n74mbk/minio-java-test-kji645/00000.minio.multipart volume=.minio
ERRO[0406] RenameFile failed with file not found         dstPath=minio-java-test-kji645/00000.minio.multipart/file.6 dstVolume=minio-java-test-n74mbk srcPath=tmp/minio-java-test-n74mbk/minio-java-test-kji645/00000.minio.multipart/file.6 srcVolume=.minio
ERRO[0453] listOnlineDisks failed with file not found    path=minio-java-test-18bnsc7/00000.minio.multipart volume=minio-java-test-spfk6e
ERRO[0455] MakeVol failed with error no such file or directory  volume=minio-java-test-spfk6e
[DEBUG] disk not found
ERRO[0455] listMetaBucketMultipartFiles failed with disk not found  markerPath= maxUploads=1000 prefixPath=multipart/minio-java-test-spfk6e/minio-java-test-18u4cbs recursive=true
ERRO[0455] ListMultipartUploads failed.                  Error={Cause:disk not found Type:*errors.errorString}
[DEBUG] disk not found

```

**Comment by balamurugana** [comment]
This bug reappears in

```
$ minio version
Version: 2016-06-02T16:48:22Z
Release-Tag: DEVELOPMENT.2016-06-02T16-48-22Z
Commit-ID: de21126f7e0565105b467134da16d01465e0c7ac
```
