### ISSUE TITLE
XL: Server crash during cp using aws cli (May 15th)

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1553]
Here is the command that was used. 
`aws --endpoint-url http://localhost:9001 s3  cp  --recursive /home/minio/gopath/ s3://testbucket/`

Here is the stack trace when it cashed, 

```
goroutine 57 [running]:
panic(0xa08dc0, 0xc8200100e0)
    /home/minio/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 +0x3e6
bufio.(*Writer).WriteString(0x0, 0xb442c0, 0x19, 0x917bc0, 0x0, 0x0)
    /home/minio/.gimme/versions/go1.6.linux.amd64/src/bufio/bufio.go:660 +0x3f
net/http.(*expectContinueReader).Read(0xc8204ac600, 0xc8204dc000, 0x8000, 0x8000, 0x4b5b06, 0x0, 0x0)
    /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:636 +0xc7
io.(*LimitedReader).Read(0xc8204a2060, 0xc8204dc000, 0x8000, 0x8000, 0x8000, 0x0, 0x0)
    /home/minio/.gimme/versions/go1.6.linux.amd64/src/io/io.go:426 +0xbd
io.copyBuffer(0x7fa0a6f510b0, 0xc8204a2020, 0x7fa0a6f94250, 0xc8204a2060, 0xc8204dc000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
    /home/minio/.gimme/versions/go1.6.linux.amd64/src/io/io.go:380 +0x247
io.Copy(0x7fa0a6f510b0, 0xc8204a2020, 0x7fa0a6f94250, 0xc8204a2060, 0xc8204a2020, 0x0, 0x0)
    /home/minio/.gimme/versions/go1.6.linux.amd64/src/io/io.go:350 +0x64
io.CopyN(0x7fa0a6f510b0, 0xc8204a2020, 0x7fa0a6f510d8, 0xc8204ac600, 0x32b090, 0xc820223790, 0x0, 0x0)
    /home/minio/.gimme/versions/go1.6.linux.amd64/src/io/io.go:326 +0xf7
main.objectAPIHandlers.PutObjectHandler.func1(0xc820032098, 0xc8204db260, 0x32b090, 0xc8204b0550)
    /home/minio/gopath/src/github.com/minio/minio/object-handlers.go:579 +0x2a0
created by main.objectAPIHandlers.PutObjectHandler
    /home/minio/gopath/src/github.com/minio/minio/object-handlers.go:602 +0x9e2
```

**Comment by harshavardhana** [comment]
```
func (ecr *expectContinueReader) Read(p []byte) (n int, err error) {
    if ecr.closed {
        return 0, ErrBodyReadAfterClose
    }
    if !ecr.resp.wroteContinue && !ecr.resp.conn.hijacked() {
        ecr.resp.wroteContinue = true
        ecr.resp.conn.bufw.WriteString("HTTP/1.1 100 Continue\r\n\r\n") ---> Here is the bug. 
        ecr.resp.conn.bufw.Flush()
    }
    n, err = ecr.readCloser.Read(p)
    if err == io.EOF {
        ecr.sawEOF = true
    }
    return
}
```

The bufw.WriteString() is unprotected and does not know if the client already closed the reader. It is a very tricky bug but can be reproduced with the combination of io.Pipe() a go-routine inside a handler.

Also this is related to a client which is setting the header "Expect: 100-continue" , will open a bug on Golang will have to find a solution for this in the meantime.

**Comment by hackintoshrao** [comment]
Sure. 👍
