### ISSUE TITLE
XL: Healing code crashed

### ISSUE THREAD

**Issue by hackintoshrao** [minio/minio#1556]
Minio server crashed during the follwing copy operation from aws cli.

`aws --endpoint-url http://localhost:9001 s3  cp  --recursive /usr/ s3://testbucket/`

```
panic: runtime error: invalid memory address or nil pointer dereference         [signal 0xb code=0x1 addr=0x20 pc=0x63d010]                                     
 goroutine 36827 [running]: panic(0xa0a100, 0xc82000e0f0)      

/home/minio/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:464 
0x3e6                 

 o.ReadAtLeast(0x0, 0x0, 0xc82344e000, 0xccccd, 0xccccd, 0xccccd, 0x0, 0x0, 0x0)

/home/minio/.gimme/versions/go1.6.linux.amd64/src/io/io.go:297 +0xe0   

 o.ReadFull(0x0, 0x0, 0xc82344e000, 0xccccd, 0xccccd, 0xccccd, 0x0, 0x0)        

/home/minio/.gimme/versions/go1.6.linux.amd64/src/io/io.go:315 +0x62    main.XL.healFile(0x7f27b7a8b1b0, 0xc82026e5a0, 0x5, 0x5, 0xc820248780, 0xa, 0xa,0x6, 0x8, 0xac14d0, ...)                                            

/home/minio/gopath/src/github.com/minio/minio/xl-erasure-v1-healfile.go:119 +0x2407                   

main.XL.StatFile.func1(0xc82020ee80, 0x7f27b7a8b1b0, 0xc82026e5a0, 0x5, 0x5, 0xc820248780, 0xa, 0xa, 0x6, 0x8, ...)                

/home/minio/gopath/src/github.com/minio/minio/xl-erasure-v1.go:439 +0x6dcreated by main.XL.StatFile          

/home/minio/gopath/src/github.com/minio/minio/xl-erasure-v1.go:446 +0x61     
```

**Comment by harshavardhana** [comment]
Fixed by #1562
