### ISSUE TITLE
PutObject fails when a disk is down

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#1561]
@balamurugana setup:

```
Test: multipart: putObject(String bucketName, String objectName, String fileName)
error occured
ErrorResponse(code=NoSuchBucket, message=The specified bucket does not exist., bucketName=null, objectName=null, resouce=/minio-java-test-2jv692u, requestId=3L137, hostId=3L137)
request={method=GET, url=http://127.0.0.1:60000/minio-java-test-2jv692u?max-uploads=1000&upload-id-marker&prefix=minio-java-test-a4o6fm&delimiter&key-marker&uploads=, headers=Host: 127.0.0.1:60000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20160509T060923Z
Authorization: AWS4-HMAC-SHA256 Credential=B4TDG3O5V27UBVY3UG6V/20160509/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=7deb48e1d16f3a6adbd3bfe1097f65828bc7dd217\
89c7c974693da2993a196ec
}
response={code=404, headers=Accept-Ranges: bytes
Server: Minio/DEVELOPMENT.2016-05-08T09-37-27Z (linux; amd64)
Vary: Origin
X-Amz-Request-Id: N1HCPPPKWRM112M1
Date: Mon, 09 May 2016 06:09:23 GMT
Content-Type: text/xml; charset=utf-8
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1462774163626
OkHttp-Received-Millis: 1462774163733
}
```

bala rm -rf'ed 8th disk.

**Comment by krishnasrinivas** [comment]
On my setup,
if I rm -rf the bucket/, putObject succeeds
if I rm -rf the disk/, putObject fails with:

```
mc: <DEBUG> GET /test1/?max-uploads=1000&prefix=10mbfile&uploads= HTTP/1.1
Host: 127.0.0.1:10000
User-Agent: Minio (linux; amd64) minio-go/1.0.1 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20160509/us-east-1/s3/aws4_request, SignedHeaders=expect;host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Expect: 100-continue
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20160509T134003Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 503 Service Unavailable
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: text/xml; charset=utf-8
Date: Mon, 09 May 2016 13:40:03 GMT
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: YXE78N6Z6DTS0D77

105
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>ReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key></Key><BucketName></BucketName><Resource>/test1/</Resource><RequestId>3L137</RequestId><HostId>3L137</HostId></Error>
0

mc: <DEBUG> Response Time:  1.885566ms
```

**Comment by krishnasrinivas** [comment]
mc ls makes it panic:

```
Minio Object Storage:
    http://127.0.0.1:10000
    http://192.168.1.11:10000

Minio Browser:
    http://127.0.0.1:10000
    http://192.168.1.11:10000

To configure Minio Client:
    $ wget https://dl.minio.io/client/mc/release/linux-amd64/mc
    $ chmod 755 mc
    $ ./mc config host add myminio http://127.0.0.1:10000 7EK16BG19GRBIG1USWP2 8wzq0+aFslpwJ8cL5GCPbs/TFQAKxPhJlb1uxLU8
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x28 pc=0x46ec1e]

goroutine 2845 [running]:
panic(0x9fbfc0, 0xc8200100e0)
        /home/krishna/go/src/runtime/panic.go:481 +0x3e6
main.XL.healFile(0x7f13817330e0, 0xc82008fbd0, 0x5, 0x5, 0xc8202050e0, 0xa, 0xa, 0x6, 0x8, 0xc8202c99b5, ...)
        /home/krishna/gocode/src/github.com/minio/minio/xl-erasure-v1-healfile.go:187 +0x203e
main.XL.StatFile.func1(0xc820339160, 0x7f13817330e0, 0xc82008fbd0, 0x5, 0x5, 0xc8202050e0, 0xa, 0xa, 0x6, 0x8, ...)
        /home/krishna/gocode/src/github.com/minio/minio/xl-erasure-v1.go:439 +0x6d
created by main.XL.StatFile
        /home/krishna/gocode/src/github.com/minio/minio/xl-erasure-v1.go:446 +0x618
```

**Comment by harshavardhana** [comment]
Fixed by #1562

**Comment by krishnasrinivas** [comment]
@harshavardhana bala saw this error:

```
ErrorResponse(code=NoSuchBucket, message=The specified bucket does not exist., bucketName=null, objectName=null, resouce=/minio-java-test-2jv692u, requestId=3L137, hostId=3L137)
request={method=GET, url=http://127.0.0.1:60000/minio-java-test-2jv692u?max-uploads=1000&upload-id-marker&prefix=minio-java-test-a4o6fm&delimiter&key-marker&uploads=, headers=Host: 127.0.0.1:60000
```

different from panic.

**Comment by harshavardhana** [comment]
There is a bug for that #1552
