### ISSUE TITLE
Encrypted bucket becomes unresponsive - MinIO seems to be taking up all backend connections to KMS

### ISSUE THREAD

**Issue by rluetzner** [minio/minio#16475]
We configured multiple MinIO nodes with local kes services as a KMS (all kes instances use the same key store). We created multiple buckets, for some of which we enabled encryption.

After a few days we noticed that access to the encrypted buckets was no longer possible. Listing, reading or writing objects would hang indefinitely **on one of the nodes**. Access on the other nodes was fine.

Looking at the kes logs, we noticed that calls to /v1/metrics were being rejected. This is disallowed by default in our config, which we set up according to MinIO documentation.

After we ran out of ideas, we stopped MinIO with SIGABORT. The resulting core dump indicates that a lot of goroutines were stuck collecting metrics for the Prometheus endpoint. Some of these goroutines were stuck for more than a day.

[minio.log](https://github.com/minio/minio/files/10500220/minio.log)

Here's an excerpt from the file linked above:

```text
goroutine 440971197 [semacquire, 3842 minutes]:
runtime.gopark(0x7f7e63ca7c20?, 0x0?, 0x40?, 0xe2?, 0x40d93f?)
        runtime/proc.go:363 +0xd6 fp=0xc009534e18 sp=0xc009534df8 pc=0x43cd36
runtime.goparkunlock(...)
        runtime/proc.go:369
runtime.semacquire1(0xc019eec188, 0xc0?, 0x1, 0x0)
        runtime/sema.go:150 +0x1fe fp=0xc009534e80 sp=0xc009534e18 pc=0x44df3e
sync.runtime_Semacquire(0xc00e5b8cc0?)
        runtime/sema.go:62 +0x25 fp=0xc009534eb0 sp=0xc009534e80 pc=0x46a765
sync.(*WaitGroup).Wait(0xc0025dc870?)
        sync/waitgroup.go:139 +0x52 fp=0xc009534ed8 sp=0xc009534eb0 pc=0x47aa92
github.com/minio/minio/cmd.(*minioClusterCollector).Collect(0xc00031c760, 0xc0045fdd40)
        github.com/minio/minio/cmd/metrics-v2.go:2212 +0x197 fp=0xc009534f30 sp=0xc009534ed8 pc=0x20f7477
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
        github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:453 +0x10d fp=0xc009534fe0 sp=0xc009534f30 pc=0x14750ad
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc009534fe8 sp=0xc009534fe0 pc=0x46ea81
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
        github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:464 +0x55d

------------------------------------------------------------------------------------------------------------------------------------

goroutine 453965040 [select, 3749 minutes]:
runtime.gopark(0xc028f83bf8?, 0x2?, 0xfa?, 0x5a?, 0xc028f83a14?)
        runtime/proc.go:363 +0xd6 fp=0xc028f83860 sp=0xc028f83840 pc=0x43cd36
runtime.selectgo(0xc028f83bf8, 0xc028f83a10, 0x0?, 0x0, 0x0?, 0x1)
        runtime/select.go:328 +0x7bc fp=0xc028f839a0 sp=0xc028f83860 pc=0x44ce7c
github.com/prometheus/client_golang/prometheus.(*Registry).Gather(0xc00140ad20)
        github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:520 +0x9a5 fp=0xc028f83e70 sp=0xc028f839a0 pc=0x1474a45
github.com/prometheus/client_golang/prometheus.Gatherers.Gather({0xc00051a820, 0x1, 0x5191f20?})
        github.com/prometheus/client_golang@v1.13.0/prometheus/registry.go:726 +0x213 fp=0xc028f841c0 sp=0xc028f83e70 pc=0x1475e33
github.com/minio/minio/cmd.metricsServerHandler.func1({0x51add58, 0xc036936c60}, 0xc0350a3500)
        github.com/minio/minio/cmd/metrics-v2.go:2356 +0xf2 fp=0xc028f842e0 sp=0xc028f841c0 pc=0x20f9132
net/http.HandlerFunc.ServeHTTP(0xc028f85400?, {0x51add58?, 0xc036936c60?}, 0x47962e?)
        net/http/server.go:2109 +0x2f fp=0xc028f84308 sp=0xc028f842e0 pc=0x7094ef
github.com/minio/minio/cmd.setBucketForwardingHandler.func1({0x51add58, 0xc036936c60}, 0xc0350a3500)
        github.com/minio/minio/cmd/generic-handlers.go:477 +0x22d fp=0xc028f84700 sp=0xc028f84308 pc=0x206ef6d
net/http.HandlerFunc.ServeHTTP(0x206d9e1?, {0x51add58?, 0xc036936c60?}, 0x206d6d9?)
        net/http/server.go:2109 +0x2f fp=0xc028f84728 sp=0xc028f84700 pc=0x7094ef
github.com/minio/minio/cmd.setUploadForwardingHandler.func1({0x51add58, 0xc036936c60}, 0xc0350a3500)
        github.com/minio/minio/cmd/generic-handlers.go:587 +0x182 fp=0xc028f848f0 sp=0xc028f84728 pc=0x2070622
net/http.HandlerFunc.ServeHTTP(0x51add28?, {0x51add58?, 0xc036936c60?}, 0x10?)
        net/http/server.go:2109 +0x2f fp=0xc028f84918 sp=0xc028f848f0 pc=0x7094ef
github.com/minio/minio/cmd.addCustomHeaders.func1({0x51add28, 0xc03cc77668}, 0xc0350e9760?)
        github.com/minio/minio/cmd/generic-handlers.go:552 +0x3c2 fp=0xc028f849b8 sp=0xc028f84918 pc=0x206fcc2
net/http.HandlerFunc.ServeHTTP(0x282c340?, {0x51add28?, 0xc03cc77668?}, 0x39?)
        net/http/server.go:2109 +0x2f fp=0xc028f849e0 sp=0xc028f849b8 pc=0x7094ef
github.com/minio/minio/cmd.setRequestValidityHandler.func1({0x51add28, 0xc03cc77668}, 0xc0350a3500)
        github.com/minio/minio/cmd/generic-handlers.go:465 +0xe75 fp=0xc028f84e10 sp=0xc028f849e0 pc=0x206ea95
net/http.HandlerFunc.ServeHTTP(0x40?, {0x51add28?, 0xc03cc77668?}, 0x6564af0?)
        net/http/server.go:2109 +0x2f fp=0xc028f84e38 sp=0xc028f84e10 pc=0x7094ef
github.com/minio/minio/cmd.setHTTPStatsHandler.func1({0x51b04e8?, 0xc011880a80}, 0xc0350a3500)
        github.com/minio/minio/cmd/generic-handlers.go:304 +0x119 fp=0xc028f84ea8 sp=0xc028f84e38 pc=0x206d6d9
net/http.HandlerFunc.ServeHTTP(0xc0345ccb70?, {0x51b04e8?, 0xc011880a80?}, 0xc02e979f80?)
        net/http/server.go:2109 +0x2f fp=0xc028f84ed0 sp=0xc028f84ea8 pc=0x7094ef
github.com/minio/minio/cmd.setRequestLimitHandler.func1({0x51b04e8?, 0xc011880a80}, 0xc0350a3500)
        github.com/minio/minio/cmd/generic-handlers.go:129 +0x4b0 fp=0xc028f85028 sp=0xc028f84ed0 pc=0x206ca70
net/http.HandlerFunc.ServeHTTP(0x291dac7?, {0x51b04e8?, 0xc011880a80?}, 0x206cb16?)
        net/http/server.go:2109 +0x2f fp=0xc028f85050 sp=0xc028f85028 pc=0x7094ef
github.com/minio/minio/cmd.setCrossDomainPolicy.func1({0x51b04e8?, 0xc011880a80?}, 0x1?)
        github.com/minio/minio/cmd/crossdomain-xml-handler.go:43 +0xef fp=0xc028f85080 sp=0xc028f85050 pc=0x1f65e6f
net/http.HandlerFunc.ServeHTTP(0xc0350a3500?, {0x51b04e8?, 0xc011880a80?}, 0xc011da1100?)
        net/http/server.go:2109 +0x2f fp=0xc028f850a8 sp=0xc028f85080 pc=0x7094ef
github.com/minio/minio/cmd.setBrowserRedirectHandler.func1({0x51b04e8, 0xc011880a80}, 0xc0350a3500)
        github.com/minio/minio/cmd/generic-handlers.go:160 +0x183 fp=0xc028f851f0 sp=0xc028f850a8 pc=0x206cd83
net/http.HandlerFunc.ServeHTTP(0x2536ac0?, {0x51b04e8?, 0xc011880a80?}, 0x10?)
        net/http/server.go:2109 +0x2f fp=0xc028f85218 sp=0xc028f851f0 pc=0x7094ef
github.com/minio/minio/cmd.setAuthHandler.func1({0x51b04e8, 0xc011880a80}, 0xc0350a3500)
        github.com/minio/minio/cmd/auth-handler.go:581 +0x4f7 fp=0xc028f853f0 sp=0xc028f85218 pc=0x1e95817
net/http.HandlerFunc.ServeHTTP(0x51b6100?, {0x51b04e8?, 0xc011880a80?}, 0x7501bd?)
        net/http/server.go:2109 +0x2f fp=0xc028f85418 sp=0xc028f853f0 pc=0x7094ef
github.com/minio/minio/cmd.httpTracer.func1({0x51b04e8, 0xc011880a80}, 0xc0350a3500)
        github.com/minio/minio/cmd/http-tracer.go:129 +0x4ec fp=0xc028f857d8 sp=0xc028f85418 pc=0x207d18c
net/http.HandlerFunc.ServeHTTP(0xc0350a3400?, {0x51b04e8?, 0xc011880a80?}, 0x20300c?)
        net/http/server.go:2109 +0x2f fp=0xc028f85800 sp=0xc028f857d8 pc=0x7094ef
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000344480, {0x51b04e8, 0xc011880a80}, 0xc0350a3000)
        github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf fp=0xc028f85928 sp=0xc028f85800 pc=0x75288f
github.com/rs/cors.(*Cors).Handler.func1({0x51b04e8, 0xc011880a80}, 0xc0350a3000)
        github.com/rs/cors@v1.8.2/cors.go:231 +0x1c4 fp=0xc028f85980 sp=0xc028f85928 pc=0x1691584
net/http.HandlerFunc.ServeHTTP(0x0?, {0x51b04e8?, 0xc011880a80?}, 0x40dc87?)
        net/http/server.go:2109 +0x2f fp=0xc028f859a8 sp=0xc028f85980 pc=0x7094ef
github.com/minio/minio/cmd.setCriticalErrorHandler.func1({0x51b04e8?, 0xc011880a80?}, 0x0?)
        github.com/minio/minio/cmd/generic-handlers.go:576 +0x83 fp=0xc028f85a08 sp=0xc028f859a8 pc=0x206fe23
net/http.HandlerFunc.ServeHTTP(0x0?, {0x51b04e8?, 0xc011880a80?}, 0x0?)
        net/http/server.go:2109 +0x2f fp=0xc028f85a30 sp=0xc028f85a08 pc=0x7094ef
github.com/minio/minio/internal/http.(*Server).Start.func1({0x51b04e8?, 0xc011880a80?}, 0x7f7e644c5a78?)
        github.com/minio/minio/internal/http/server.go:111 +0x19c fp=0xc028f85aa0 sp=0xc028f85a30 pc=0x7773dc
net/http.HandlerFunc.ServeHTTP(0x0?, {0x51b04e8?, 0xc011880a80?}, 0x46c9ee?)
        net/http/server.go:2109 +0x2f fp=0xc028f85ac8 sp=0xc028f85aa0 pc=0x7094ef
net/http.serverHandler.ServeHTTP({0xc0345cc810?}, {0x51b04e8, 0xc011880a80}, 0xc0350a3000)
        net/http/server.go:2947 +0x30c fp=0xc028f85b78 sp=0xc028f85ac8 pc=0x70c8ec
net/http.(*conn).serve(0xc0269debe0, {0x51b1fc8, 0xc00150e1e0})
        net/http/server.go:1991 +0x607 fp=0xc028f85fb8 sp=0xc028f85b78 pc=0x707fc7
net/http.(*Server).Serve.func3()
        net/http/server.go:3102 +0x2e fp=0xc028f85fe0 sp=0xc028f85fb8 pc=0x70d22e
runtime.goexit()
        runtime/asm_amd64.s:1594 +0x1 fp=0xc028f85fe8 sp=0xc028f85fe0 pc=0x46ea81
created by net/http.(*Server).Serve
        net/http/server.go:3102 +0x4db
```

My working theory is that MinIO opened up a ton of connections to kes, reaching the connection limit. Because no more connections were available any further requests to kes timed out, preventing us from reading from an encrypted bucket.

## Expected Behavior

MinIO should not saturate the connection limit to it's KMS.

## Current Behavior

Any S3 actions on the encrypted bucket or any of its objects hang indefinitely, because MinIO is blocking all connections to its KMS.

## Possible Solution

The preferred solution is for MinIO not to block connections to its KMS.

Alternatively or in addition to that, the documentation should be updated to include /v1/metrics as a mandatory endpoint that must be allowed in the kes config.

## Steps to Reproduce (for bugs)

**Unconfirmed so far, because the problem only occurred after multiple days. Restarting MinIO fixed it for now!!!**

1. Configure MinIO with kes as a KMS.
2. Set the minimum permissions in kes' config.yml to allow MinIO to create, generate and decrypt, i.e.
    ```yaml
    allow:
    - /v1/key/create/minio-kms*
    - /v1/key/generate/minio-kms*
    - /v1/key/decrypt/minio-kms*
    ```
3. Create a bucket and enable encryption.
4. Write data (for a few days).

## Context

We're using MinIO in combination with kes to allow for bucket encryption.

## Regression

No?

## Your Environment

* Version used (`minio --version`): `minio version RELEASE.2022-11-17T23-20-09Z (commit-id=a22b4adf4c5cc3e4db13fe92da683ef1ce45cd5a)`
* Server setup and configuration: two nodes with kes running as a local service, connecting to a shared key store
* Operating System and version (`uname -a`): `Linux fs-fujitsu-2 5.3.18-24.96-default Nr.1 SMP Mon Nov 22 08:33:36 UTC 2021 (9a413cc) x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
> * Version used (`minio --version`): `minio version RELEASE.2022-11-17T23-20-09Z (commit-id=a22b4adf4c5cc3e4db13fe92da683ef1ce45cd5a)`

Please upgrade to the latest release @rluetzner and let us know how it goes we do not offer support for older releases for Community users.

Can you attach the entire SIGABORT trace? - we would like to see how many connections are pending on kes.

Can you also state what is your kes version here?

**Comment by harshavardhana** [comment]
Can you also enable `/v1/metrics` and reproduce this?

**Comment by rluetzner** [comment]
@harshavardhana , I'll try to reproduce this without allowing `/v1/metrics` for now. I'm interested to see if the problem simply goes away when I update the config and allow the endpoint.

`kes --version`: `kes v0.22.0 (commit=865c63819a6d82a833ad4354101e286291b420bc)`

If I'm able to consistently reproduce the issue, I'll consider updating the MinIO version. However, I don't think the version really matters. As far as I could see from the latest GitHub issues and release notes, nothing of the sort was fixed. If there was a problem in MinIO's code, I'm pretty sure it's still there.

I'll clean up the journal output and attach the entire trace as a file.

**Comment by rluetzner** [comment]
I've attached the log.

**Comment by harshavardhana** [comment]
You should upgrade there have been bug fixes in this area since this commit @rluetzner 

```
~ git tag --contains 09d4f8cd0f
RELEASE.2022-11-29T23-40-49Z
RELEASE.2022-12-02T19-19-22Z
RELEASE.2022-12-07T00-56-37Z
RELEASE.2022-12-12T19-27-27Z
RELEASE.2023-01-02T09-40-09Z
RELEASE.2023-01-06T18-11-18Z
RELEASE.2023-01-12T02-06-16Z
RELEASE.2023-01-18T04-36-38Z
RELEASE.2023-01-20T02-05-44Z
RELEASE.2023-01-25T00-19-54Z
```

One of the reasons why we ask users to upgrade if you are not subscribed to us, you would have no way of managing a production cluster in this manner. 

You are better off subscribing to us to get peace of mind in managing a production deployment.

**Comment by harshavardhana** [comment]
Closing, please re-open if seen again.
