### ISSUE TITLE
XL: healFile complains about failed to reconstruct even with writeQuorum available

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#1684]
```
ERRO[0049] Unable to heal file testbucket2/main.go.      cause=Verification failed after reconstruction, data likely corrupted. stack=goroutine 123 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
    /usr/local/opt/go/libexec/src/runtime/debug/stack.go:24 +0x80
main.errorIf(0xbac028, 0xc8201be5f0, 0xc8200ccb10, 0x28, 0x0, 0x0, 0x0)
    /Users/harsha/mygo/src/github.com/minio/minio/logger.go:57 +0x2f9
main.XL.StatFile.func1(0x1904170, 0xc8202220a0, 0x5, 0x5, 0xc8202421e0, 0xa, 0xa, 0x6, 0x8, 0xc820496666, ...)
    /Users/harsha/mygo/src/github.com/minio/minio/xl-erasure-v1.go:465 +0x14c
created by main.XL.StatFile
    /Users/harsha/mygo/src/github.com/minio/minio/xl-erasure-v1.go:466 +0x280
 sysInfo=map[host.lang:go1.6 host.cpus:4 mem.used:2.6MB mem.heap.used:2.6MB host.os:darwin host.arch:amd64 host.name:command.local mem.total:9.3MB mem.heap.total:5.8MB] type=*errors.errorString
```

The file is in-fact though can be read properly. Easy to recreate.

Start with 10disks, 

```
minio server /tmp/bc{1..10}
```

```
mc mb myminio/testbucket
rm -rf /tmp/bc9 /tmp/bc10
```

```
mc cp main.go myminio/testbucket
```

```
mc ls test/testbucket2/main.go
[2016-05-18 17:32:38 PDT] 7.8KiB main.go
```

**Comment by krishnasrinivas** [comment]
i am getting a different error:

```
krishna@escape:~/xl-exports$ rm -rf disk10
krishna@escape:~/xl-exports$ mc mb myminio/test1
Bucket created successfully ‘myminio/test1’.
krishna@escape:~/xl-exports$ mc cp /etc/passwd myminio/test1
0 B / 2.15 KB ┃░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░�mc: <ERROR> Failed to copy ‘/etc/passwd’. Bucket ‘test1’ does not exist.
krishna@escape:~/xl-exports$ 
```

**Comment by krishnasrinivas** [comment]
because of this commit 4bc923e6

```
@@ -92,6 +92,10 @@ func (xl XL) writeErasure(volume, path string, reader *io.PipeReader, wcloser *w
                                xl.cleanupCreateFileOps(volume, path, append(writers, metadataWriters...)...)
                                reader.CloseWithError(err)
                                return
+                       } else if err == errVolumeNotFound {
+                               xl.cleanupCreateFileOps(volume, path, append(writers, metadataWriters...)...)
+                               reader.CloseWithError(err)
+                               return
                        }
```

**Comment by krishnasrinivas** [comment]
Is the above diff needed? because I have removed it in the PR along with another fix https://github.com/minio/minio/pull/1693
