### ISSUE TITLE
AWS S3 library / malformed XML from "delete objects" / since `RELEASE.2023-06-09T07-32-12Z` image tag

### ISSUE THREAD

**Issue by snazy** [minio/minio#17394]
Java AWS S3 library complains about malformed XML for a "delete objects" request. All previous image tags on quay.io work fine.

## Expected Behavior
no error

## Current Behavior
"Malformed XML error" since `RELEASE.2023-06-09T07-32-12Z` image tag (quay.io).

Links:
* [failing Java test code line](https://github.com/projectnessie/nessie/blob/main/gc/gc-iceberg-inttest/src/intTest/java/org/projectnessie/gc/iceberg/inttest/ITSparkIcebergNessieS3.java#L114)
* [Our first failed CI build after the `RELEASE.2023-06-09T07-32-12Z`  release](https://github.com/projectnessie/nessie/actions/runs/5229220822/jobs/9442077715)
* [CI test failure stack trace from that same CI run](https://scans.gradle.com/s/4jy2obvtmkkmc/tests/:nessie-gc-iceberg-inttest:intTest/org.projectnessie.gc.iceberg.inttest.ITSparkIcebergNessieS3/roundTrips(TestCase)%5B1%5D?top-execution=1)

Full Java stack trace:
```
software.amazon.awssdk.services.s3.model.S3Exception: The XML you provided was not well-formed or did not validate against our published schema. (Service: S3, Status Code: 400, Request ID: 17675AF91DDAADCD, Extended Request ID: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:95)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:270)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:72)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:78)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:52)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptMetricCollectionStage.execute(ApiCallAttemptMetricCollectionStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:81)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)
	at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:48)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallMetricCollectionStage.execute(ApiCallMetricCollectionStage.java:31)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
	at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:193)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:103)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:171)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:179)
	at software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at software.amazon.awssdk.services.s3.DefaultS3Client.deleteObjects(DefaultS3Client.java:2734)
	at org.projectnessie.gc.iceberg.inttest.ITSparkIcebergNessieS3.lambda$purgeS3$1(ITSparkIcebergNessieS3.java:114)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.projectnessie.gc.iceberg.inttest.ITSparkIcebergNessieS3.purgeS3(ITSparkIcebergNessieS3.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptLifecycleMethod(TimeoutExtension.java:128)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptAfterEachMethod(TimeoutExtension.java:110)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeMethodInExtensionContext(ClassBasedTestDescriptor.java:520)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$synthesizeAfterEachMethodAdapter$24(ClassBasedTestDescriptor.java:510)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachMethods$10(TestMethodTestDescriptor.java:243)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:276)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:276)
```

## Steps to Reproduce (for bugs)

1. `git clone https://github.com/projectnessie/nessie.git`
2. `./gradlew :nessie-gc-iceberg-inttest:intTest` fails
    (implicitly pulls `quay.io/minio/minio:latest`)

Working fine w/ older release:
1. Change "latest" in line 47 of `testing/s3minio/src/main/java/org/projectnessie/minio/MinioContainer.java` to `RELEASE.2023-06-02T23-17-26Z`
2. `./gradlew :nessie-gc-iceberg-inttest:intTest` passes

## Context
We experience the issue in our CI runs.

## Regression
Is this issue a regression? Yes

Last working version: Docker tag `RELEASE.2023-06-02T23-17-26Z` (from quay.io/minio/minio)
Broken version: Docker tag `RELEASE.2023-06-09T07-32-12Z` (from quay.io/minio/minio)

## Your Environment
* Version: See above
* Server setup and configuration: via Java "testcontainers" - effectively `docker run quay.io/minio/minio:TAG server /data` with `MINIO_DOMAIN=localhost` and random values for `MINIO_ROOT_USER` + `MINIO_SECRET_KEY`
* Operating System and version (`uname -a`): on Github hosted runners (Ubuntu 22.04) and latest Ubuntu (23.04 + latest Linux kernel)

**Comment by harshavardhana** [comment]
Strange we test this against aws-sdk-java for every PR, is this AWS-SDK-java 2? @snazy

**Comment by snazy** [comment]
It's v2.20.80

**Comment by harshavardhana** [comment]
@snazy 

```
ITSparkIcebergNessieS3 > roundTrips(TestCase) > [1] testCase=TestCase{steps=[Step{sql=CREATE TABLE nessie.tc_1.tbl_a (id int, name string), expired=true, expireManifestList=false}, Step{sql=
INSERT INTO nessie.tc_1.tbl_a select 23, "test", expired=true, expireManifestList=true}, Step{sql=INSERT INTO nessie.tc_1.tbl_a select 24, "case", expired=false, expireManifestList=false}, S
tep{sql=CREATE TABLE nessie.tc_1.tbl_b (id int, name string), expired=true, expireManifestList=false}, Step{sql=INSERT INTO nessie.tc_1.tbl_b select 42, "foo", expired=false, expireManifestL
is… FAILED                                                                                                                                                                                    
    software.amazon.awssdk.services.s3.model.S3Exception at ITSparkIcebergNessieS3.java:114                                                                                                   
                                                                                                                                                                                              
ITSparkIcebergNessieS3 > roundTrips(TestCase) > [2] testCase=TestCase{steps=[Step{sql=CREATE TABLE nessie.tc_2.tbl_a (id int, name string), expired=true, expireManifestList=false}, Step{sql=
INSERT INTO nessie.tc_2.tbl_a select 23, "test", expired=false, expireManifestList=false}, Step{branch=branch_tc_2, sql=CREATE TABLE nessie.tc_2.tbl_b (id int, name string), expired=true, ex
pireManifestList=false}, Step{branch=branch_tc_2, sql=INSERT INTO nessie.tc_2.tbl_b select 42, "foo", expired=false, expireManifestList=false}, Step{sql=INSERT INTO nessie.tc_2.tbl_a select 
24… FAILED                                                                                                                                                                                    
    software.amazon.awssdk.services.s3.model.S3Exception at ITSparkIcebergNessieS3.java:114                                                                                                   
                                                                                                                                                                                              
ITContentToFilesCrossCheck > partitionedTable() FAILED                                                                                                                                        
    org.apache.iceberg.exceptions.ValidationException at ITContentToFilesCrossCheck.java:72                                                                                                   
                                                                                                                                                                                              
ITSparkIcebergNessieLocal > roundTripLocal() FAILED                                             
    org.apache.iceberg.exceptions.ValidationException at ITSparkIcebergNessieLocal.java:70

ITSparkIcebergNessieLocalNoSchema > roundTripLocal() FAILED                                     
    org.apache.iceberg.exceptions.ValidationException at ITSparkIcebergNessieLocalNoSchema.java:75

5 tests completed, 5 failed                                                                     

> Task :nessie-gc-iceberg-inttest:intTest FAILED
Cleaning up 1 Nessie Quarkus services

FAILURE: Build failed with an exception.
```

I can't get the build itself working? or is this not supposed to be what I am seeing? - I see that it hasn't started MinIO yet.

**Comment by snazy** [comment]
The `ITSparkIcebergNessieS3` test did start Minio, it just shuts it down after the test class.
The other failures are strange - but definitely unrelated (no Minio involved there) - hard to tell why w/o the test report.

**Comment by snazy** [comment]
If it helps, that "delete" sends this XML using `POST`:
```xml
<?xml version="1.0" encoding="UTF-8"?><Delete xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></Delete>
```
with these HTTP headers:
```
{Content-Length=[103], Content-MD5=[F0pA5trxwpC64TURGrVxlA==], Content-Type=[application/xml]}
```
and with a null `delete` query parameter as
```
http://bucket-e6abxa.localhost:41437/?delete
```.

**Comment by snazy** [comment]
Ah!!
So it doesn't look like the delete is causing the failure.
It's `S3Client.listObjectsV2Paginator().stream().forEach(r -> {})` passing _empty_ `ListObjectsV2Response` (no contents). 
Aka the list-objects is not working correctly ([source link](https://github.com/projectnessie/nessie/blob/main/gc/gc-iceberg-inttest/src/intTest/java/org/projectnessie/gc/iceberg/inttest/ITSparkIcebergNessieS3.java#L108)).

**Comment by snazy** [comment]
Could #17373 caused this one?
The constant `S3_PATH_PREFIX` in our test class is `/my/prefix` - using `my/prefix` instead seems to be working.
Not sure now whether a leading `/` is generally fine or not.

**Comment by snazy** [comment]
Yea - seems to be a bug in that particular test class (on our side). It's been the only one using a leading `/`.

**Comment by harshavardhana** [comment]
You shouldn't be using a leading `/` - we had to change this because a leading / for prefix must never trim it and instead return empty because there are no keys saved with / as prefixed.

We had to change this for compliance with the results from AWS S3.
