### ISSUE TITLE
XL: On slow read of get object in progress, remove object is timing out

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1798]
Steps to reproduce
1. Have a program to read an object sized 8MiB where the program reads the stream slowly.
2. Have another program to delete the object.  This program times out.

```
$ javac -cp "build/libs/minio-2.0.0.jar:/home/bala/java/jar/*" examples/MinioRemoveObject.java && java -cp "build/libs/minio-2.0.0.jar:/home/bala/java/jar/*:examples" MinioRemoveObject
Exception in thread "main" java.net.SocketTimeoutException: timeout
    at okio.Okio$3.newTimeoutException(Okio.java:207)
    at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
    at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
    at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
    at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
    at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
    at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
    at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
    at com.squareup.okhttp.Call.getResponse(Call.java:287)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
    at com.squareup.okhttp.Call.execute(Call.java:80)
    at io.minio.MinioClient.execute(MinioClient.java:699)
    at io.minio.MinioClient.executeDelete(MinioClient.java:904)
    at io.minio.MinioClient.removeObject(MinioClient.java:1416)
    at MinioRemoveObject.main(MinioRemoveObject.java:37)
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketInputStream.read(SocketInputStream.java:203)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at okio.Okio$2.read(Okio.java:139)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    ... 17 more
```

Whereas the delete operation was successful.

The same steps work successfully with Amazon S3 ie one end of get object is running fine and another end of delete object is successful.

**Comment by harshavardhana** [comment]
This requires granular locking we don't have that.  We don't allow simultaneous mutating operations on a `bucket\object` .

**Comment by balamurugana** [comment]
**The problem**
Our current approach is as below
1. When [xlObjects.GetObject()](https://github.com/minio/minio/blob/rewrite-xl/xl-v1-object.go#L19) is invoked, it locks the namespace before it reads [erasure.ReadFile()](https://github.com/minio/minio/blob/rewrite-xl/xl-v1-object.go#L66)
2. Its known that [erasure.ReadFile()](https://github.com/minio/minio/blob/rewrite-xl/erasure-readfile.go#L22) has to be invoked after locking the namespace and it does [disk.ReadFile()](https://github.com/minio/minio/blob/rewrite-xl/erasure-readfile.go#L44) for each block, decodes erasure blocks and return final data.

Our directory structure on each disk is as below as example

```
/mnt/sd{b..i}1/bala/mydisk/mybucket/myobject/object{1,2}
/mnt/sd{b..i}1/bala/mydisk/mybucket/myobject/xl.json
```

To serve get-object request, we would need to lock namespace `mybucket/myobject`.

As reported in the issue, when delete-object has come when get-object is in progress, get-object holds the read lock to `mybucket/myobject` and delete-object's lock request blocks until get-object releases it.

**Pointers for solution**
Anyone of approach can be taken to fix the issue.
- delete-object can return error to tell the client to retry after sometime.  Amazon S3 doesn't work this way.
- get-object could lock individual data files and delete-object can remove xl.json only.  This brings stale data files appearance.
- get-object could have copy of data files in a separate location, but this will bring delay in servicing get-object call.

**Comment by harshavardhana** [comment]
> Pointers for solution
> Anyone of approach can be taken to fix the issue.
> 
> delete-object can return error to tell the client to retry after sometime. Amazon S3 doesn't work this way.

This is makes more sense to me to throw an error as EBUSY or Retry again error. It is similar to how windows and certain OS behave. Since it is a right behavior to lock the name space. There is no reason to parallelly delete an object while it is being read on the other end.
