### ISSUE TITLE
XL: http server panics

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#1837]
In a various combination of put/get/delete objects in parallel causes below crash of minio server.

```
http: panic serving 127.0.0.1:39968: runtime error: integer divide by zero
goroutine 1613859 [running]:
net/http.(*conn).serve.func1(0xc82023a600)
    /home/bala/golang/goroot/src/net/http/server.go:1389 +0xc1
panic(0x9f7c80, 0xc8200100c0)
    /home/bala/golang/goroot/src/runtime/panic.go:443 +0x4e9
main.erasureReadFile(0xc820922080, 0x8, 0x8, 0xc820d889c5, 0x8, 0xc820108370, 0x4e, 0xc8203f26d7, 0x7, 0x2873, ...)
    /home/bala/golang/gopath/src/github.com/minio/minio/erasure-readfile.go:58 +0x18c
main.xlObjects.GetObject(0xc82000a0e0, 0x8, 0x8, 0xc82023a900, 0x8, 0x8, 0x4, 0x4, 0x5, 0x7, ...)
    /home/bala/golang/gopath/src/github.com/minio/minio/xl-v1-object.go:99 +0xe9e
main.(*xlObjects).GetObject(0xc820218060, 0xc820d889c5, 0x8, 0xc820d889ce, 0x46, 0x0, 0x2873, 0x7f3a6094e140, 0xc82099f040, 0x0, ...)
    <autogenerated>:256 +0x131
main.objectAPIHandlers.GetObjectHandler(0x7f3a60a00a88, 0xc820218060, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/object-handlers.go:139 +0x693
main.(objectAPIHandlers).GetObjectHandler-fm(0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/api-router.go:49 +0x4a
net/http.HandlerFunc.ServeHTTP(0xc820166ba0, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/goroot/src/net/http/server.go:1618 +0x3a
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc820d9c230, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:100 +0x29e
main.redirectHandler.ServeHTTP(0x7f3a60a00fe0, 0xc820d9c230, 0xaacf38, 0x6, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/generic-handlers.go:71 +0x278
main.(*redirectHandler).ServeHTTP(0xc82013e040, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    <autogenerated>:118 +0xb4
main.minioPrivateBucketHandler.ServeHTTP(0x7f3a60a01008, 0xc82013e040, 0xaacf38, 0x6, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/generic-handlers.go:119 +0x1a5
main.(*minioPrivateBucketHandler).ServeHTTP(0xc82013e060, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    <autogenerated>:120 +0xb4
main.cacheControlHandler.ServeHTTP(0x7f3a60a01030, 0xc82013e060, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/generic-handlers.go:100 +0x26a
main.(*cacheControlHandler).ServeHTTP(0xc82022f160, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    <autogenerated>:119 +0xb6
main.timeHandler.ServeHTTP(0x7f3a60a01058, 0xc82022f160, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/generic-handlers.go:188 +0x25a
main.(*timeHandler).ServeHTTP(0xc82022f170, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    <autogenerated>:121 +0xb6
github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:185 +0x1c5
net/http.HandlerFunc.ServeHTTP(0xc82013e0e0, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/goroot/src/net/http/server.go:1618 +0x3a
main.resourceHandler.ServeHTTP(0x7f3a60a00cb0, 0xc82013e0e0, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/generic-handlers.go:248 +0x392
main.(*resourceHandler).ServeHTTP(0xc82022f1e0, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    <autogenerated>:122 +0xb6
main.authHandler.ServeHTTP(0x7f3a60a010a8, 0xc82022f1e0, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/gopath/src/github.com/minio/minio/auth-handler.go:154 +0x76
main.(*authHandler).ServeHTTP(0xc82022f1f0, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    <autogenerated>:55 +0xb6
net/http.serverHandler.ServeHTTP(0xc820088b80, 0x7f3a5c638080, 0xc82099f040, 0xc820012c40)
    /home/bala/golang/goroot/src/net/http/server.go:2081 +0x19e
net/http.(*conn).serve(0xc82023a600)
    /home/bala/golang/goroot/src/net/http/server.go:1472 +0xf2e
created by net/http.(*Server).Serve
    /home/bala/golang/goroot/src/net/http/server.go:2137 +0x44e
```

**Comment by harshavardhana** [comment]
Not able to reproduce this. It almost looks like `xl.json` was never written properly.

**Comment by harshavardhana** [comment]
> Not able to reproduce this. It almost looks like xl.json was never written properly.

This is also fixed.
