### ISSUE TITLE
segfaults with site replication

### ISSUE THREAD

**Issue by vixns** [minio/minio#18589]
## NOTE

Since the update to version 2023-12-02T10:51:33Z, some minio nodes are crashing
We have 2 clusters with site replication, this appends one one node on each side.

```
2023-12-04_19:29:10.01902 [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x2387956]
2023-12-04_19:29:10.01903
2023-12-04_19:29:10.01904 goroutine 370653 [running]:
2023-12-04_19:29:10.01909 github.com/minio/minio/cmd.(*SiteReplicationSys).SiteReplicationMetaInfo(0x609f540, {0x49f14d0, 0xc0196a8be0}, {0x4a1d4d8?, 0xc0019ea000}, {0x0, 0x0, 0x0, 0x0, 0x0, ...})
2023-12-04_19:29:10.01910 	github.com/minio/minio/cmd/site-replication.go:3734 +0x3996
2023-12-04_19:29:10.01913 github.com/minio/minio/cmd.(*SiteReplicationSys).siteReplicationStatus.func1()
2023-12-04_19:29:10.01913 	github.com/minio/minio/cmd/site-replication.go:2729 +0x9f
2023-12-04_19:29:10.01916 github.com/minio/minio/cmd.(*SiteReplicationSys).concDo.func1(0x1)
2023-12-04_19:29:10.01919 	github.com/minio/minio/cmd/site-replication.go:2222 +0x135
2023-12-04_19:29:10.01922 created by github.com/minio/minio/cmd.(*SiteReplicationSys).concDo in goroutine 256752
2023-12-04_19:29:10.01922 	github.com/minio/minio/cmd/site-replication.go:2218 +0x25f
```

**Comment by harshavardhana** [comment]
Did you upgrade all instances to this release? under site replication? @vixns

**Comment by vixns** [comment]
@harshavardhana yes, all instances were using the same version.
