### ISSUE TITLE
SIGSEGV: segmentation violation multi-site replication 

### ISSUE THREAD

**Issue by c4m4** [minio/minio#18808]
## Context
We have a multi site replica setup, 2 vms of 32G of ram and 8 cpus, the replica works good, but at somepoint everything stopped to work and minio died with the following segment faul:

```
Jan 16 14:52:10 minio02.area.local minio[244887]: SIGSEGV: segmentation violation
Jan 16 14:52:10 minio02.area.local minio[244887]: PC=0x455b24 m=76 sigcode=1
Jan 16 14:52:10 minio02.area.local minio[244887]: goroutine 0 [idle]:
Jan 16 14:52:10 minio02.area.local minio[244887]: runtime.findsghi(...)
Jan 16 14:52:10 minio02.area.local minio[244887]:         runtime/stack.go:796
Jan 16 14:52:10 minio02.area.local minio[244887]: runtime.copystack(0xc1c5a39a00, 0xc061531c70?)
Jan 16 14:52:10 minio02.area.local minio[244887]:         runtime/stack.go:906 +0x344 fp=0xc061531ac8 sp=0xc0615317d0 pc=0x455b24
Jan 16 14:52:10 minio02.area.local minio[244887]: runtime.shrinkstack(0xc1c5a39a00)
Jan 16 14:52:10 minio02.area.local minio[244887]:         runtime/stack.go:1218 +0x113 fp=0xc061531ae8 sp=0xc061531ac8 pc=0x456993
Jan 16 14:52:10 minio02.area.local minio[244887]: runtime.scanstack(0xc1c5a39a00, 0x1?)
Jan 16 14:52:10 minio02.area.local minio[244887]:         runtime/mgcmark.go:776 +0xdb fp=0xc061531e20 sp=0xc061531ae8 pc=0x42235b
Jan 16 14:52:10 minio02.area.local minio[244887]: runtime.markroot.func1()

```
## Your Environment
uname -r
5.14.0-362.13.1.el9_3.x86_64

minio --version
minio version RELEASE.2023-12-07T04-16-00Z (commit-id=cfed671ea39d56987596e3301d0b6c5ec6cbd1f8)
Runtime: go1.21.5 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

**Comment by harshavardhana** [comment]
An upstream issue https://github.com/golang/go/issues/64781 - please try setting env `GODEBUG=gcshrinkstackoff=1` to potentially avoid a runtime bug.
