### ISSUE TITLE
panic: duplicate label names in constant and variable labels for metric "minio_cluster_replication_current_active_workers"

### ISSUE THREAD

**Issue by T-M-A** [minio/minio#18893]
## NOTE
After update

Server `vk-ms` updated successfully from 2023-12-23T07:19:11Z to 2024-01-29T03-56-32Z

```
Jan 29 08:35:47 node13 minio[914731]: {"level":"INFO","errKind":"","time":"2024-01-29T05:35:47.424311087Z","message":"\nDocumentation: https://min.io/docs/minio/linux/index.html"}
Jan 29 08:35:56 node13 minio[914731]: panic: duplicate label names in constant and variable labels for metric "minio_cluster_replication_current_active_workers"
Jan 29 08:35:56 node13 minio[914731]: goroutine 11694 [running]:
Jan 29 08:35:56 node13 minio[914731]: github.com/prometheus/client_golang/prometheus.MustNewConstMetric(...)
Jan 29 08:35:56 node13 minio[914731]:         github.com/prometheus/client_golang@v1.18.0/prometheus/value.go:129
Jan 29 08:35:56 node13 minio[914731]: github.com/minio/minio/cmd.(*minioNodeCollector).Collect.func1({{{0x2c4eed5, 0xd}, {0x2c4a1f5, 0xb}, {0x2c6aafa, 0x16}, {0x2cb876b, 0x2a}, {0x2c4a032, 0xb}}, ...})
Jan 29 08:35:56 node13 minio[914731]:         github.com/minio/minio/cmd/metrics-v2.go:3987 +0x64e
Jan 29 08:35:56 node13 minio[914731]: github.com/minio/minio/cmd.populateAndPublish({0xc000160ba0, 0xb, 0xc113aea2f8?}, 0xc0017efef0)
Jan 29 08:35:56 node13 minio[914731]:         github.com/minio/minio/cmd/metrics-v2.go:3943 +0x11e
Jan 29 08:35:56 node13 minio[914731]: github.com/minio/minio/cmd.(*minioNodeCollector).Collect(0xc0010238c0, 0xc113b97320)
Jan 29 08:35:56 node13 minio[914731]:         github.com/minio/minio/cmd/metrics-v2.go:3955 +0xc5
Jan 29 08:35:56 node13 minio[914731]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
Jan 29 08:35:56 node13 minio[914731]:         github.com/prometheus/client_golang@v1.18.0/prometheus/registry.go:455 +0x102
Jan 29 08:35:56 node13 minio[914731]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather in goroutine 11689
Jan 29 08:35:56 node13 minio[914731]:         github.com/prometheus/client_golang@v1.18.0/prometheus/registry.go:547 +0xbab
Jan 29 08:35:56 node13 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 29 08:35:56 node13 systemd[1]: minio.service: Failed with result 'exit-code'.
Jan 29 08:35:56 node13 systemd[1]: minio.service: Service RestartSec=100ms expired, scheduling restart.
Jan 29 08:35:56 node13 systemd[1]: minio.service: Scheduled restart job, restart counter is at 3.
Jan 29 08:35:56 node13 systemd[1]: Stopped MinIO.

```

**Comment by harshavardhana** [comment]
@T-M-A As a workaround stop scraping node metrics for now.  The fix is available in #18894

**Comment by T-M-A** [comment]
Thanks!

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/18894 fixed and merged should available in the next release.
