### ISSUE TITLE
Latest version - could not connect using S3, had to rollback 

### ISSUE THREAD

**Issue by nandan121** [minio/minio#18971]
## Expected Behavior
I use cloudberry free(for backup from my win10 home machine) to connect to my minio server, setup on Oracle OCI. Using the keys etc, it was coming up with an error. I had to rollback the minio exe from " RELEASE.2024-01-31T20-20-33Z (commit-id=24ecc44bac566b25a5bfa9772d946a19ce551035)" to "RELEASE.2024-01-18T22-51-28Z (commit-id=19387cafab76133c2e7642de4aac8c81b9f4f8c7)" to get it working.

## Current Behavior
Below is the error log from cloudberry
```
2024-02-05 10:00:04,635 [S3] [8] INFO  - Listing buckets
2024-02-05 10:00:04,635 [S3] [8] WARN  - Updating regions list for S3Compatible is not supported
2024-02-05 10:00:04,705 [Base] [8] ERROR - Response status: ProtocolError
Response text:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>17B0EF25A3BB7705</RequestId><HostId>b2bd42182ac6a8872c76db866738d47e04f66a3d2cf5c359962008baa052dbc4</HostId></Error>
2024-02-05 10:00:04,705 [Base] [8] ERROR - Header Strict-Transport-Security: max-age=31536000; includeSubDomains
2024-02-05 10:00:04,706 [Base] [8] ERROR - Header Vary: Origin,Accept-Encoding
2024-02-05 10:00:04,706 [Base] [8] ERROR - Header X-Amz-Id-2: b2bd42182ac6a8872c76db866738d47e04f66a3d2cf5c359962008baa052dbc4
2024-02-05 10:00:04,707 [Base] [8] ERROR - Header X-Amz-Request-Id: 17B0EF25A3BB7705
2024-02-05 10:00:04,715 [Base] [8] ERROR - Header X-Content-Type-Options: nosniff
2024-02-05 10:00:04,716 [Base] [8] ERROR - Header X-Xss-Protection: 1; mode=block
2024-02-05 10:00:04,716 [Base] [8] ERROR - Header Accept-Ranges: bytes
2024-02-05 10:00:04,717 [Base] [8] ERROR - Header Content-Length: 254
2024-02-05 10:00:04,717 [Base] [8] ERROR - Header Content-Type: application/xml
2024-02-05 10:00:04,718 [Base] [8] ERROR - Header Date: Mon, 05 Feb 2024 10:00:03 GMT
2024-02-05 10:00:04,719 [Base] [8] ERROR - Header Server: MinIO
2024-02-05 10:00:04,719 [S3] [8] WARN  - InitializeItems
CloudBerryLab.Base.Exceptions.AccessDeniedException
Access Denied.
   at amc.b(aMx )
   at amc.C(aMx )
   at amc.c(aMx )
   at amd.OW(aMx )
   at amd.A(aMx )
   at Bal.B(ICancelable )
   at BeL.Sq(ICancelable )
   at BGl.A(Boolean , Boolean , String , aPw )
CloudBerryLab.S3Client.Exceptions.S3WebException
Access Denied.

System.Net.WebException
The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at amc.a(aMx )

2024-02-05 10:00:10,294 [S3] [1] INFO  - Creating bucket cloudberrybackup762d6c86-6b4b-4ae7-8094-312a5afdc7cf
2024-02-05 10:00:10,295 [S3] [1] WARN  - Updating regions list for S3Compatible is not supported
2024-02-05 10:00:10,343 [Base] [1] ERROR - Response status: ProtocolError
Response text:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><BucketName>cloudberrybackup762d6c86-6b4b-4ae7-8094-312a5afdc7cf</BucketName><Resource>/cloudberrybackup762d6c86-6b4b-4ae7-8094-312a5afdc7cf</Resource><RequestId>17B0EF26F3CE11A4</RequestId><HostId>b2bd42182ac6a8872c76db866738d47e04f66a3d2cf5c359962008baa052dbc4</HostId></Error>
2024-02-05 10:00:10,344 [Base] [1] ERROR - Header Strict-Transport-Security: max-age=31536000; includeSubDomains
2024-02-05 10:00:10,344 [Base] [1] ERROR - Header Vary: Origin,Accept-Encoding
2024-02-05 10:00:10,344 [Base] [1] ERROR - Header X-Amz-Id-2: b2bd42182ac6a8872c76db866738d47e04f66a3d2cf5c359962008baa052dbc4
2024-02-05 10:00:10,344 [Base] [1] ERROR - Header X-Amz-Request-Id: 17B0EF26F3CE11A4
2024-02-05 10:00:10,345 [Base] [1] ERROR - Header X-Content-Type-Options: nosniff
2024-02-05 10:00:10,345 [Base] [1] ERROR - Header X-Xss-Protection: 1; mode=block
2024-02-05 10:00:10,345 [Base] [1] ERROR - Header Accept-Ranges: bytes
2024-02-05 10:00:10,346 [Base] [1] ERROR - Header Content-Length: 383
2024-02-05 10:00:10,346 [Base] [1] ERROR - Header Content-Type: application/xml
2024-02-05 10:00:10,346 [Base] [1] ERROR - Header Date: Mon, 05 Feb 2024 10:00:09 GMT
2024-02-05 10:00:10,346 [Base] [1] ERROR - Header Server: MinIO
2024-02-05 10:00:10,347 [UI] [1] ERROR - Cannot create Bucket
CloudBerryLab.Base.Exceptions.AccessDeniedException
Access Denied.
   at amc.b(aMx )
   at amc.C(aMx )
   at amc.c(aMx )
   at amd.OW(aMx )
   at amd.A(aMx )
   at Bal.A(String , Bao , Boolean , Boolean , ICancelable )
   at CloudBerryLab.Backup.Engine.Cloud.Connection.S3CommonConnection.CreateBucket(String name)
   at CloudBerryLab.Backup.Console.WPF.ViewModel.CreateBucketViewModel.BaseCreateBucketViewModel.CreateBucket(Window o)
CloudBerryLab.S3Client.Exceptions.S3WebException
Access Denied.

System.Net.WebException
The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at amc.a(aMx )
```

## Steps to Reproduce (for bugs)
Using cloudberry free, try to connect to the server using S3

## Regression
 Yes

I had to rollback the minio exe from " RELEASE.2024-01-31T20-20-33Z (commit-id=24ecc44bac566b25a5bfa9772d946a19ce551035)" to "RELEASE.2024-01-18T22-51-28Z (commit-id=19387cafab76133c2e7642de4aac8c81b9f4f8c7)" to get it working.
## Your Environment

* Version used (`minio --version`):  RELEASE.2024-01-31T20-20-33Z (commit-id=24ecc44bac566b25a5bfa9772d946a19ce551035)
* Server setup and configuration: I have just set up minio server and nothing else on this server.  
```
ubuntu@vm-minio-ubuntu22-04-minioserver:~/del1$ ps -ef |grep minio
minio-u+    7720       1  0 10:42 ?        00:00:02 /usr/local/bin/minio server -C /etc/minio --address :9092 --console-address :9091 --certs-dir /etc/minio/certs /mnt/minio/

ubuntu@vm-minio-ubuntu22-04-minioserver:~/del1$ sudo cat /etc/default/minio
MINIO_ACCESS_KEY="minio"
MINIO_VOLUMES="/mnt/minio/"
MINIO_OPTS="-C /etc/minio --address :9092 --console-address :9091 --certs-dir /etc/minio/certs"
MINIO_ROOT_USER="xxx"
MINIO_ROOT_PASSWORD="xxx"


```

* Operating System and version (`uname -a`): `Linux vm-minio-ubuntu22-04-minioserver 5.15.0-1049-oracle #55-Ubuntu SMP Mon Nov 20 19:53:49 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux`
*

**Comment by harshavardhana** [comment]
You should upgrade to the latest @nandan121 we had a regression in access keys permissions/
