### ISSUE TITLE
unexpected EOF error for some correctly saved objects

### ISSUE THREAD

**Issue by lukasz-borek** [minio/minio#18992]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

unexpected EOF error for some objects after upgrade to 20240129035632

## Current Behavior

After upgrade i notice some files not able to be replicated :
```
:~$ mcli stat minio/ backup/[....]billing.s2
Name      : billing.s2
Date      : 2024-02-06 13:56:05 CET
Size      : 4.1 GiB
ETag      : 8d8e33160025064308b9ea67380359d0-444
VersionID : c3aef69f-3960-4ca2-9fdf-6b65ad7ea395
Type      : file
Metadata  :
  X-Amz-Object-Lock-Retain-Until-Date: 2024-02-20T12:52:16.272Z
  X-Amz-Object-Lock-Mode             : GOVERNANCE
  Content-Type                       : binary/octet-stream
**Replication Status: FAILED**
```
Problem is more complex as those files are not able to be reed : 
```
$ mcli cp   minio/ backup-prod/[....]billing.s2 .
mcli: <ERROR> Failed to copy `http://url:9000/backup/billing.s2`. unexpected EOF
```

At version 20240129035632.0.0 lots of errors like below for failed object :
```
Error: Reading erasure shards at (ble:9000/mnt/disk8: 
    ble.7a256fbc-3a11-41ae-b3b3-24b4330d7dda/part.1788) returned 'unexpected EOF', will attempt to reconstruct if we have quorum 
```

At version 20240204223613.0.0 above errors gone, left only replication related.

## Context

Not able to read some correctly written objects. 

## Regression

Upgrade from 20231007150738.0.0 -> 20240129035632.0.0 (and later to 20240204223613.0.0)

## Your Environment

* Version used (`minio --version`):inio version RELEASE.2024-02-04T22-36-13Z
* Server setup and configuration: 2 pools (4 * Dell R740, 12 * HDD) configuration dedicated for backup applications, versioning, replication and object locking
* Operating System and version (`uname -a`):  Ubuntu 22.04.3 LTS 5.15.0-89-generic x86_64

**Comment by harshavardhana** [comment]
What kind of a backend filesystem do you have ?

**Comment by harshavardhana** [comment]
Can you collect the xl.meta of this object from the backend disk and also do `ls -l UUID/`

Replace UUID to the actual uuid directory name at the object path.

We will try to see what it might be.

To me it feels like you are on ext4 filesystem as your backend disks.

**Comment by lukasz-borek** [comment]
Hi @harshavardhana, thanks for responce. 

FIlesystem is xfs : 

```
root@nodehdd2:# mount | grep mnt
/dev/sdc1 on /mnt/disk1 type xfs (rw,noatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)
[...]
```

Looks like for some reason few file parts are missing : 

parts per drive per pool member  : 

```
nodehdd1 : 444 444 444 444
nodehdd2 : 439 440 438 438
nodehdd3 : 444 444 444 444
nodehdd4 : 444 442 442 443
```

Attached 
[minio-corrupted-objects.txt](https://github.com/minio/minio/files/14192759/minio-corrupted-objects.txt)

**Comment by harshavardhana** [comment]
can you do `mc ls --versions alias/bucket/object-name` ?

**Comment by lukasz-borek** [comment]
```
$ mcli ls --versions minio/[...]billing.s2
[2024-02-06 13:56:05 CET] 4.1GiB STANDARD c3aef69f-3960-4ca2-9fdf-6b65ad7ea395 v1 PUT [....]billing.s2
```

**Comment by harshavardhana** [comment]
There is no code that touches individual parts so it is quite impossible to delete specific part files with in MinIO. From what I can tell you had some kind of a filesystem corruption here.

Is there anything special in `dmesg -T` from these two nodes? 

> nodehdd2 : 439 440 438 438

> nodehdd4 : 444 442 442 443

**Comment by lukasz-borek** [comment]
No hardware problems i can see. HDDs are on havie load, but it may cause missing file parts? And it's possible to PUT an object and not save all "parts", returning OK to the client? 

This one is interesting, around time corrupted object was uploaded : 
```
eb  6 13:41:26 minio2-nodehdd2 minio[2983331]: panic: send on closed channel
Feb  6 13:41:26 minio2-nodehdd2 minio[2983331]: goroutine 144348531 [running]:
Feb  6 13:41:26 minio2-nodehdd2 minio[2983331]: github.com/minio/minio/internal/pubsub.(*PubSub[...]).SubscribeJSON.func1()
Feb  6 13:41:26 minio2-nodehdd2 minio[2983331]: #011github.com/minio/minio/internal/pubsub/pubsub.go:139 +0x12d
Feb  6 13:41:26 minio2-nodehdd2 minio[2983331]: created by github.com/minio/minio/internal/pubsub.(*PubSub[...]).SubscribeJSON in goroutine 144348496
Feb  6 13:41:26 minio2-nodehdd2 minio[2983331]: #011github.com/minio/minio/internal/pubsub/pubsub.go:124 +0x352
Feb  6 13:41:27 minio2-nodehdd2 systemd[1]: minio.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Feb  6 13:41:27 minio2-nodehdd2 systemd[1]: minio.service: Failed with result 'exit-code'.
Feb  6 13:41:27 minio2-nodehdd2 systemd[1]: minio.service: Consumed 14h 30min 52.059s CPU time.
Feb  6 13:41:27 minio2-nodehdd2 systemd[1]: minio.service: Scheduled restart job, restart counter is at 1.
Feb  6 13:41:27 minio2-nodehdd2 systemd[1]: Stopped MinIO.
Feb  6 13:41:27 minio2-nodehdd2 systemd[1]: minio.service: Consumed 14h 30min 52.059s CPU time.
Feb  6 13:41:27 minio2-nodehdd2 systemd[1]: Starting MinIO...
Feb  6 13:41:27 minio2-nodehdd2 kernel: [5254430.308915] audit: type=1400 audit(1707223287.419:344551): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/proc/3252423/cmdline" pid=3179499 comm="sssd_nss" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  6 13:41:27 minio2-nodehdd2 kernel: [5254430.328374] audit: type=1400 audit(1707223287.435:344552): apparmor="ALLOWED" operation="open" profile="/usr/sbin/sssd" name="/proc/3252424/cmdline" pid=3179499 comm="sssd_nss" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]: API: SYSTEM()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]: Time: 12:41:29 UTC 02/06/2024
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]: Error: saving pool.bin for pool index 0 failed with: Storage resources are insufficient for the write operation .minio.sys/pool.bin (*errors.errorString)
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:       10: internal/logger/logger.go:243:logger.LogIf()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        9: cmd/erasure-server-pool-decom.go:473:cmd.poolMeta.save()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        8: cmd/erasure-server-pool-decom.go:517:cmd.(*erasureServerPools).Init()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        7: cmd/erasure-server-pool.go:193:cmd.newErasureServerPools.func3()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        6: cmd/server-main.go:491:cmd.bootstrapTrace()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        5: cmd/erasure-server-pool.go:192:cmd.newErasureServerPools()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        4: cmd/server-main.go:1052:cmd.newObjectLayer()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        3: cmd/server-main.go:792:cmd.serverMain.func10()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        2: cmd/server-main.go:491:cmd.bootstrapTrace()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        1: cmd/server-main.go:790:cmd.serverMain()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]: API: SYSTEM()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]: Time: 12:41:29 UTC 02/06/2024
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]: Error: Unable to initialize backend: Storage resources are insufficient for the write operation .minio.sys/pool.bin, retrying in 4.203430272s (*fmt.wrapError)
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        6: internal/logger/logger.go:243:logger.LogIf()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        5: cmd/erasure-server-pool.go:200:cmd.newErasureServerPools()
Feb  6 13:41:29 minio2-nodehdd2 minio[3252424]:        4: cmd/server-main.go:1052:cmd.newObjectLayer()
[...]
eb  6 13:53:23 minio2-nodehdd2 minio[3261116]: Error: Unable to initialize backend: Storage resources are insufficient for the write operation .minio.sys/pool.bin, retrying in 4.701961269s (*fmt.wrapError)
Feb  6 13:53:23 minio2-nodehdd2 minio[3261116]:        6: internal/logger/logger.go:243:logger.LogIf()
Feb  6 13:53:23 minio2-nodehdd2 minio[3261116]:        5: cmd/erasure-server-pool.go:200:cmd.newErasureServerPools()
Feb  6 13:53:23 minio2-nodehdd2 minio[3261116]:        4: cmd/server-main.go:1052:cmd.newObjectLayer()
Feb  6 13:53:23 minio2-nodehdd2 minio[3261116]:        3: cmd/server-main.go:792:cmd.serverMain.func10()
Feb  6 13:53:23 minio2-nodehdd2 minio[3261116]:        2: cmd/server-main.go:491:cmd.bootstrapTrace()
Feb  6 13:53:23 minio2-nodehdd2 minio[3261116]:        1: cmd/server-main.go:790:cmd.serverMain()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]: API: SYSTEM()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]: Time: 12:53:27 UTC 02/06/2024
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]: Error: saving pool.bin for pool index 0 failed with: Storage resources are insufficient for the write operation .minio.sys/pool.bin (*errors.errorString)
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:       10: internal/logger/logger.go:243:logger.LogIf()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        9: cmd/erasure-server-pool-decom.go:473:cmd.poolMeta.save()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        8: cmd/erasure-server-pool-decom.go:517:cmd.(*erasureServerPools).Init()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        7: cmd/erasure-server-pool.go:193:cmd.newErasureServerPools.func3()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        6: cmd/server-main.go:491:cmd.bootstrapTrace()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        5: cmd/erasure-server-pool.go:192:cmd.newErasureServerPools()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        4: cmd/server-main.go:1052:cmd.newObjectLayer()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        3: cmd/server-main.go:792:cmd.serverMain.func10()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        2: cmd/server-main.go:491:cmd.bootstrapTrace()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        1: cmd/server-main.go:790:cmd.serverMain()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]: API: SYSTEM()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]: Time: 12:53:27 UTC 02/06/2024
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]: Error: Unable to initialize backend: Storage resources are insufficient for the write operation .minio.sys/pool.bin, retrying in 1.71261463s (*fmt.wrapError)
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        6: internal/logger/logger.go:243:logger.LogIf()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        5: cmd/erasure-server-pool.go:200:cmd.newErasureServerPools()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        4: cmd/server-main.go:1052:cmd.newObjectLayer()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        3: cmd/server-main.go:792:cmd.serverMain.func10()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        2: cmd/server-main.go:491:cmd.bootstrapTrace()
Feb  6 13:53:27 minio2-nodehdd2 minio[3261116]:        1: cmd/server-main.go:790:cmd.serverMain()
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: Waiting for all MinIO sub-systems to be initialize...
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: Automatically configured API requests per node based on available memory on the system: 2142
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: All MinIO sub-systems initialized successfully in 77.672223ms
Feb  6 13:53:29 minio2-nodehdd2 systemd[1]: Started MinIO.
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: Cluster replication initialized
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: MinIO Object Storage Server
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: Copyright: 2015-2024 MinIO, Inc.
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Feb  6 13:53:29 minio2-nodehdd2 minio[3261116]: Version: RELEASE.2024-02-04T22-36-13Z (go1.21.6 linux/amd64)


```

**Comment by harshavardhana** [comment]
Client would not have received any 200 OK in this scenario, it simply exists as partial transaction on the namespace. Basically it was never successfully uploaded. One of the reasons why it has "replication" failed status set on it indicate

- Either replication target is down or network is down
- Or READ side failure.

i.e Client didn't get a 200 OK, however server was at the end of commit phase during CompleteMultipartUpload().

However a rename() was triggered from multipart -> namespace during this time the server crashed in between leaving an inconsistent state on those two specific nodes. So this backup was never really saved properly.

It shows up in `List` output because xl.meta has enough quorum, list() doesn't verify the rest of the contiguous parts, as it generally can be a very expensive operation to do so.

The correct approach is to purge the object and re-upload the content. 

>   6 13:41:26 minio2-nodehdd2 minio[2983331]: panic: send on closed channel

This crash is fixed, please avoid using `mc admin trace alias/` to ensure servers don't crash, we will be making a new release shortly.

**Comment by lukasz-borek** [comment]
Thanks for the tip about trace command. 

Unfortunately backup app (mongo pbm) was happy about this object : 

```
2024-02-06T12:52:15.225+0000    Mux open namespace ble.billing
2024-02-06T12:52:15.225+0000    Mux open namespace admin.pbmOpLog
2024-02-06T12:52:15.225+0000    Mux open namespace admin.pbmLockOp
2024-02-06T12:52:15.225+0000    Mux open namespace admin.pbmAgents
2024-02-06T12:52:15.225+0000    Mux open namespace admin.pbmPITRChunks
2024-02-06T12:52:15.225+0000    Mux open namespace config.settings
2024-02-06T12:52:15.225+0000    Mux open namespace admin.pbmLock
2024-02-06T12:52:15.225+0000    done dumping admin.pbmRUsers (12 documents)
2024-02-06T12:52:15.225+0000    counted 25734097 documents in ble.billing
2024-02-06T12:52:15.225+0000    counted 134 documents in admin.pbmOpLog
2024-02-06T12:52:15.225+0000    counted 1 document in admin.pbmLock
2024-02-06T12:52:15.225+0000    counted 2586 documents in admin.pbmLog
2024-02-06T12:52:15.225+0000    counted 1 document in config.settings
2024-02-06T12:52:15.225+0000    counted 4 documents in admin.pbmAgents
2024-02-06T12:52:15.225+0000    counted 1 document in admin.pbmLockOp
2024-02-06T12:52:15.225+0000    counted 0 documents in admin.pbmPITRChunks
2024-02-06T12:52:15.238+0000    Mux close namespace admin.pbmRUsers
2024-02-06T12:52:15.242+0000    done dumping admin.pbmLockOp (1 document)
2024-02-06T12:52:15.261+0000    Mux close namespace admin.pbmLockOp
2024-02-06T12:52:15.261+0000    done dumping admin.pbmAgents (4 documents)
2024-02-06T12:52:15.262+0000    Mux close namespace admin.pbmAgents
2024-02-06T12:52:15.262+0000    Mux close namespace admin.pbmPITRChunks
2024-02-06T12:52:15.262+0000    done dumping admin.pbmPITRChunks (0 documents)
2024-02-06T12:52:15.273+0000    done dumping admin.pbmLog (2586 documents)
2024-02-06T12:52:15.282+0000    Mux close namespace admin.pbmLog
2024-02-06T12:52:15.282+0000    done dumping admin.pbmLock (1 document)
2024-02-06T12:52:15.291+0000    Mux close namespace admin.pbmLock
2024-02-06T12:52:15.291+0000    done dumping admin.pbmRRoles (2 documents)
2024-02-06T12:52:15.292+0000    Mux close namespace admin.pbmRRoles
2024-02-06T12:52:15.292+0000    done dumping config.settings (1 document)
2024-02-06T12:52:15.293+0000    Mux close namespace config.settings
2024-02-06T12:52:15.293+0000    done dumping admin.pbmOpLog (134 documents)
2024-02-06T12:52:15.294+0000    Mux close namespace admin.pbmOpLog
2024-02-06T12:52:16.000+0000 I [delete/2024-01-23T00:00:00Z] done
2024/02/06 12:53:15 [######..................]  ble.billing  6624782/25734097  (25.7%)
2024/02/06 12:54:15 [############............]  ble.billing  13311794/25734097  (51.7%)
2024/02/06 12:55:15 [##################......]  ble.billing  19923399/25734097  (77.4%)
2024/02/06 12:56:04 [########################]  ble.billing  25734509/25734097  (100.0%)
2024-02-06T12:56:04.665+0000    done dumping ble.billing (25734509 documents)
2024-02-06T12:56:04.665+0000    dump phase III: the oplog
2024-02-06T12:56:04.665+0000    finishing dump
2024-02-06T12:56:04.667+0000    Mux close namespace ble.billing
2024-02-06T12:56:04.667+0000    Mux finish
2024-02-06T12:56:04.667+0000    mux completed successfully
2024-02-06T12:56:05.000+0000 I [backup/2024-02-06T12:52:10Z] mongodump finished, waiting for the oplog
2024-02-06T12:56:08.000+0000 D [backup/2024-02-06T12:52:10Z] set oplog span to {1707223932 27} / {1707224165 5}
2024-02-06T12:56:09.000+0000 I [backup/2024-02-06T12:52:10Z] dropping tmp collections
2024-02-06T12:56:09.000+0000 D [backup/2024-02-06T12:52:10Z] epoch set to {1707224169 4}
2024-02-06T12:56:11.000+0000 I [backup/2024-02-06T12:52:10Z] backup finished
2024-02-06T12:56:11.000+0000 D [backup/2024-02-06T12:52:10Z] releasing lock
```

```
Backups:
========
S3 pl-kra 
  Snapshots:
    2024-02-07T08:51:29Z 4.31GB <logical> [restore_to_time: 2024-02-07T08:55:32Z]
    2024-02-06T12:52:10Z 4.13GB <logical> [restore_to_time: 2024-02-06T12:56:05Z]
    2024-02-05T16:52:22Z 4.27GB <logical> [restore_to_time: 2024-02-05T16:56:17Z]
    2024-02-04T20:51:44Z 4.25GB <logical> [restore_to_time: 2024-02-04T20:55:35Z]
    2024-02-04T00:52:09Z 4.23GB <logical> [restore_to_time: 2024-02-04T00:56:00Z]
    2024-02-03T04:51:11Z 4.06GB <logical> [restore_to_time: 2024-02-03T04:54:53Z]
    2024-02-02T08:51:35Z 4.20GB <logical> [restore_to_time: 2024-02-02T08:55:30Z]
    2024-02-01T12:52:04Z 4.19GB <logical> [restore_to_time: 2024-02-01T12:55:59Z]
    2024-01-31T16:51:05Z 4.01GB <logical> [restore_to_time: 2024-01-31T16:54:52Z]
    2024-01-30T20:51:19Z 3.99GB <logical> [restore_to_time: 2024-01-30T20:55:04Z]
    2024-01-30T00:51:24Z 3.97GB <logical> [restore_to_time: 2024-01-30T00:55:02Z]
    2024-01-29T04:51:07Z 4.10GB <logical> [restore_to_time: 2024-01-29T04:54:47Z]
    2024-01-28T08:51:26Z 4.07GB <logical> [restore_to_time: 2024-01-28T08:55:07Z]
    2024-01-27T12:51:08Z 3.90GB <logical> [restore_to_time: 2024-01-27T12:54:50Z]
    2024-01-26T16:51:16Z 3.89GB <logical> [restore_to_time: 2024-01-26T16:54:53Z]
    2024-01-25T20:51:04Z 3.87GB <logical> [restore_to_time: 2024-01-25T20:54:44Z]
    2024-01-25T00:52:00Z 4.00GB <logical> [restore_to_time: 2024-01-25T00:55:32Z]
    2024-01-24T04:51:06Z 3.98GB <logical> [restore_to_time: 2024-01-24T04:54:41Z]
```

Is there a method to detect such failures? Now i doing mcli stat -r and look for replication failure. But it would be nice to have a red flag for that, as it's worst case scenario.

**Comment by harshavardhana** [comment]
Was this object written after upgrade or before?

**Comment by lukasz-borek** [comment]
I notice the problem after upgrade from 20231007150738.0.0 to 20240129035632.0.0. Later upgraded to 20240204223613.0.0. Objects created before look good (at last from replication perspective).

**Comment by harshavardhana** [comment]
> I notice the problem after upgrade from 20231007150738.0.0 to 20240129035632.0.0. Later upgraded to 20240204223613.0.0. Objects created before look good (at last from replication perspective).

No wait the question is when the object was being uploaded were you running traces?

**Comment by lukasz-borek** [comment]
Good question....some our backup jobs takie hours to complete uploading one file. Will let you know tomorrow. No traces from now :)

**Comment by harshavardhana** [comment]
> Good question....some our backup jobs takie hours to complete uploading one file. Will let you know tomorrow. No traces from now :)

Okay, sure, @lukasz-borek. It looks like there was a partial transaction issue when the server was offline and online. 

It is concerning that the client didn't see an error and is unsure why. Do you have audit logs enabled in your deployment?

**Comment by lukasz-borek** [comment]
No. Just serwer logs. 

Should i follow [Publish Audit Logs to HTTP Webhook](https://min.io/docs/minio/windows/operations/monitoring/minio-logging.html?utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=8976569894&hsa_cam=20593618271&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAlJKuBhAdEiwAnZb7lWAggRRcijRLLjt0nrX-0-b4cV4ok9JWqdKDaQTsH5hN5k1iRBM1bxoCr6AQAvD_BwE#id2)?

**Comment by harshavardhana** [comment]
> No. Just serwer logs.
> 
> Should i follow [Publish Audit Logs to HTTP Webhook](https://min.io/docs/minio/windows/operations/monitoring/minio-logging.html?utm_term=&utm_campaign=&utm_source=adwords&utm_medium=ppc&hsa_acc=8976569894&hsa_cam=20593618271&hsa_grp=&hsa_ad=&hsa_src=x&hsa_tgt=&hsa_kw=&hsa_mt=&hsa_net=adwords&hsa_ver=3&gad_source=1&gclid=CjwKCAiAlJKuBhAdEiwAnZb7lWAggRRcijRLLjt0nrX-0-b4cV4ok9JWqdKDaQTsH5hN5k1iRBM1bxoCr6AQAvD_BwE#id2)?

Yes you need to enable that to make sure we have a history. It helps us know what client saw and what server wrote to disk etc.

Did you verify the latest backup?

**Comment by lukasz-borek** [comment]
Hi @harshavardhana! 

Cluster is still under mongo backup traffic (lots of k8s based pods write there using percona backup for mongodb). Upgraded to latest version yesterday and added additional pool. My guesses are: we see object failure only during minio service restart, crash (because of mcli admin trace bug) or node maintenance. Trying to confirm that in wider time frame. 

Question: if we're  running multipart transfer and we lost/restart one minio node (all nodes behind load balancer). What should be done with active file transfer? Current one is terminated, client is asked to re-try and is directed to another node by load balancer? Is it possible that client not handling such situation correctly? 

I will try to simulate such case on dev cluster and capture the logs. 

Thanks!

**Comment by harshavardhana** [comment]
> Question: if we're running multipart transfer and we lost/restart one minio node (all nodes behind load balancer). What should be done with active file transfer? The current one is terminated, the client is asked to re-try and is directed to another node by the load balancer. Is it possible that the client is not handling such a situation correctly?

It is definitely possible only when the client sees a 200 OK for a PutObjectPart(), but it didn't because the 2 servers went down at the time rename() was about to complete.

- are you using some load balancer between MongoDB -> MinIO?
- what is uptime of all of your 4 nodes?

**Comment by lukasz-borek** [comment]
> are you using some load balancer between MongoDB -> MinIO?
Yes, there is haproxy in front of minio. 
> what is uptime of all of your 4 nodes?
Low, as i did reboot before last upgrade

After last upgrade, clean failed object at filesystem level (mc rm time out) and adding new pool to reduce node load - problem is solved (i hope). If not i will return with audit logs captured. 

Thanks for help!

**Comment by harshavardhana** [comment]
Okay, will wait to hear from you.
