### ISSUE TITLE
(linux/arm32) panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by ojarva** [minio/minio#19213]
minio crashes with `panic: runtime error: makeslice: len out of range`

## Expected Behavior

minio would start serving files.

## Current Behavior

Executing `minio serve /mnt/storage/minio` where the folder is empty, disk is writable and has plenty of space crashes with

```
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/klauspost/reedsolomon.AllocAligned(...)
	/opt/go/pkg/mod/github.com/klauspost/reedsolomon@v1.12.1/unsafe.go:30
github.com/minio/minio/internal/bpool.(*BytePoolCap).Populate(0x7ea81a0)
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/internal/bpool/bpool.go:47 +0x74
github.com/minio/minio/cmd.newErasureServerPools({0x46605e8, 0x7f1aa80}, {0x862af90, 0x1, 0x1})
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/cmd/erasure-server-pool.go:107 +0x2a0
github.com/minio/minio/cmd.newObjectLayer(...)
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/cmd/server-main.go:1048
github.com/minio/minio/cmd.serverMain.func10()
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/cmd/server-main.go:806 +0x58
github.com/minio/minio/cmd.bootstrapTrace({0x266a2f8, 0xe}, 0x7b5f940)
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/cmd/server-main.go:495 +0x130
github.com/minio/minio/cmd.serverMain(0x717fa48)
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/cmd/server-main.go:804 +0x6e0
github.com/minio/cli.HandleAction({0x220c750, 0x4228b3c}, 0x717fa48)
	/opt/go/pkg/mod/github.com/minio/cli@v1.24.2/app.go:492 +0x9c
github.com/minio/cli.Command.Run({{0x2655b1e, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x2696106, 0x1b}, {0x0, ...}, ...}, ...)
	/opt/go/pkg/mod/github.com/minio/cli@v1.24.2/command.go:242 +0x8b4
github.com/minio/cli.(*App).Run(0x85d1958, {0x7042228, 0x3, 0x3})
	/opt/go/pkg/mod/github.com/minio/cli@v1.24.2/app.go:260 +0x878
github.com/minio/minio/cmd.Main({0x7042228, 0x3, 0x3})
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/cmd/main.go:215 +0x118
main.main()
	/opt/go/pkg/mod/github.com/minio/minio@v0.0.0-20240305044844-1b5f28e99b14/main.go:30 +0x38
```

Both with current head (e91a4a414c240e338ca38bb3ecd8600ec019f90f), and with the latest release.

Running on raspberry pi 4, built with `go version go1.22.1 linux/arm`

uname -a: `Linux hostname 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux`

**Comment by harshavardhana** [comment]
This looks like arm32 issue.

**Comment by harshavardhana** [comment]
Looks like this needs a fix in the upstream library.

**Comment by klauspost** [comment]
@harshavardhana It is allocating more than 2GB on 32 bit platform - that is the issue.

**Comment by harshavardhana** [comment]
> @harshavardhana It is allocating more than 2GB on 32 bit platform - that is the issue.

Ah I see. Let me check if we can make this platform specific.

**Comment by klauspost** [comment]
`const is32Bit = (^uint(0))>>63 == 0` should detect 32 bits.

**Comment by harshavardhana** [comment]
> `const is32Bit = (^uint(0))>>63 == 0` should detect 32 bits.

Thinking I can just do this strconv.IntSize == 32

**Comment by harshavardhana** [comment]
fixed by https://github.com/minio/minio/pull/19225
