### ISSUE TITLE
mc admin update doesn't work at all

### ISSUE THREAD

**Issue by Nik0-0** [minio/minio#19251]
## Expected Behavior
Everything should update normally like before without issues

## Current Behavior
After running mc admin update minio throws throws an error:

```
panic: "POST /minio/admin/v3/update?updateURL=": runtime error: invalid memory address or nil pointer dereference
goroutine 664 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x64
github.com/minio/minio/cmd.serverMain.func8.setCriticalErrorHandler.func2.1()
	github.com/minio/minio/cmd/generic-handlers.go:555 +0x7c
panic({0x20ccbc0?, 0x5aee2c0?})
	runtime/panic.go:914 +0x218
github.com/minio/pkg/v2/workers.(*Workers).Wait(...)
	github.com/minio/pkg/v2@v2.0.9-0.20240209124402-7990a27fd79d/workers/workers.go:62
github.com/minio/minio/cmd.(*NotificationGroup).Wait(...)
	github.com/minio/minio/cmd/notification.go:102
github.com/minio/minio/cmd.(*NotificationSys).VerifyBinary(0x4000df8ae0, {0x450a858?, 0x408ffce000}, 0x408f7e1440, {0x409198a580, 0x20, 0x40}, {0x409198c191, 0x22}, {0x40b9b00000, ...})
	github.com/minio/minio/cmd/notification.go:391 +0x2f8
github.com/minio/minio/cmd.adminAPIHandlers.ServerUpdateHandler({}, {0x4504e30, 0x4000ffbf40}, 0x408f7d5e00)
	github.com/minio/minio/cmd/admin-handlers.go:363 +0x4ec
net/http.HandlerFunc.ServeHTTP(0x4bac78a?, {0x4504e30?, 0x4000ffbf40?}, 0x4536b68?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.adminMiddleware.func1.httpTraceAll.httpTrace.func1({0x4504e30, 0x4000ffbf40}, 0x4000ffbf40?)
	github.com/minio/minio/cmd/http-tracer.go:189 +0xec
github.com/minio/minio/cmd.adminMiddleware.func1({0x4504e30?, 0x4000ffbf40}, 0x408f7d5d00)
	github.com/minio/minio/cmd/admin-router.go:132 +0x230
net/http.HandlerFunc.ServeHTTP(0x5aff8e0?, {0x4504e30?, 0x4000ffbf40?}, 0x4?)
	net/http/server.go:2136 +0x38
github.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x4503eb0, 0x408f7b6480}, 0x254dada?)
	github.com/klauspost/compress@v1.17.6/gzhttp/compress.go:497 +0x2d0
net/http.HandlerFunc.ServeHTTP(0x408f7dfe00?, {0x4503eb0?, 0x408f7b6480?}, 0x0?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.setBucketForwardingMiddleware.func1({0x4503eb0, 0x408f7b6480}, 0x408f7d5d00)
	github.com/minio/minio/cmd/generic-handlers.go:460 +0x2e0
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4503eb0?, 0x408f7b6480?}, 0x0?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.setUploadForwardingMiddleware.func1({0x4503eb0?, 0x408f7b6480}, 0x408f7d5d00)
	github.com/minio/minio/cmd/generic-handlers.go:573 +0x1fc
net/http.HandlerFunc.ServeHTTP(0x23fc560?, {0x4503eb0?, 0x408f7b6480?}, 0x39?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.setRequestValidityMiddleware.func1({0x4503eb0?, 0x408f7b6480}, 0x408f7d5d00)
	github.com/minio/minio/cmd/generic-handlers.go:443 +0x13b8
net/http.HandlerFunc.ServeHTTP(0x408f7dff20?, {0x4503eb0?, 0x408f7b6480?}, 0x1ee64?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.setRequestLimitMiddleware.func1({0x4503eb0?, 0x408f7b6480}, 0x408f7d5d00)
	github.com/minio/minio/cmd/generic-handlers.go:134 +0x500
net/http.HandlerFunc.ServeHTTP(0x2517a4d?, {0x4503eb0?, 0x408f7b6480?}, 0x1b6bf44?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.setCrossDomainPolicyMiddleware.func1({0x4503eb0?, 0x408f7b6480?}, 0x10?)
	github.com/minio/minio/cmd/crossdomain-xml-handler.go:42 +0x104
net/http.HandlerFunc.ServeHTTP(0x408f7d5d00?, {0x4503eb0?, 0x408f7b6480?}, 0x2526d7c?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.setBrowserRedirectMiddleware.func1({0x4503eb0, 0x408f7b6480}, 0x408f7d5d00)
	github.com/minio/minio/cmd/generic-handlers.go:164 +0x158
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4503eb0?, 0x408f7b6480?}, 0x10cdb438?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.setAuthMiddleware.func1({0x4503eb0?, 0x408f7b6480}, 0x408f7d5d00)
	github.com/minio/minio/cmd/auth-handler.go:637 +0x550
net/http.HandlerFunc.ServeHTTP(0x450a858?, {0x4503eb0?, 0x408f7b6480?}, 0x44e2340?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.httpTracerMiddleware.func1({0x4504950, 0x4000cf09a0}, 0x408f7d5c00)
	github.com/minio/minio/cmd/http-tracer.go:89 +0x2f4
net/http.HandlerFunc.ServeHTTP(0x22b7100?, {0x4504950?, 0x4000cf09a0?}, 0xa?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.addCustomHeadersMiddleware.func1({0x4504950, 0x4000cf09a0}, 0x4000d0e5c0?)
	github.com/minio/minio/cmd/generic-handlers.go:538 +0x3cc
net/http.HandlerFunc.ServeHTTP(0x408f7d5b00?, {0x4504950?, 0x4000cf09a0?}, 0x11e4638?)
	net/http/server.go:2136 +0x38
github.com/minio/mux.(*Router).ServeHTTP(0x40000fc540, {0x4504950, 0x4000cf09a0}, 0x408f7d5b00)
	github.com/minio/mux@v1.9.0/mux.go:214 +0x1b4
github.com/minio/minio/cmd.corsHandler.(*Cors).Handler.func2({0x4504950, 0x4000cf09a0}, 0x408f7d5b00)
	github.com/rs/cors@v1.10.1/cors.go:281 +0x19c
net/http.HandlerFunc.ServeHTTP(0x408f749ab8?, {0x4504950?, 0x4000cf09a0?}, 0x2ca90?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/cmd.serverMain.func8.setCriticalErrorHandler.func2({0x4504950?, 0x4000cf09a0?}, 0x4000cf09a0?)
	github.com/minio/minio/cmd/generic-handlers.go:562 +0x78
net/http.HandlerFunc.ServeHTTP(0x408f749aa8?, {0x4504950?, 0x4000cf09a0?}, 0x2f35c4?)
	net/http/server.go:2136 +0x38
github.com/minio/minio/internal/http.(*Server).Init.func1({0x4504950?, 0x4000cf09a0?}, 0x408f7b4fb0?)
	github.com/minio/minio/internal/http/server.go:127 +0xb4
net/http.HandlerFunc.ServeHTTP(0x10?, {0x4504950?, 0x4000cf09a0?}, 0x4000cf09a0?)
	net/http/server.go:2136 +0x38
net/http.serverHandler.ServeHTTP({0x44fd0f8?}, {0x4504950?, 0x4000cf09a0?}, 0x6?)
	net/http/server.go:2938 +0xbc
net/http.(*conn).serve(0x408f7e1200, {0x450a858, 0x40010ba300})
	net/http/server.go:2009 +0x518
created by net/http.(*Server).Serve in goroutine 79
	net/http/server.go:3086 +0x4cc
```

## Possible Solution
?

## Steps to Reproduce (for bugs)

1. Use mc admin update command
2. Wait and see _mc: <ERROR> Unable to update the server. We encountered an internal error, please try again._

## Your Environment

minio version RELEASE.2024-02-14T21-36-02Z (commit-id=00cb58eaf346ca8e8595c1bc50f99ec635db6725)
Runtime: go1.21.7 linux/arm64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc.
OS: Debian GNU/Linux 12 (bookworm) aarch64 (Raspberry Pi 4 Model B Rev 1.4)

**Comment by ravindk89** [comment]
What is the mc version here?

How is MinIO running/configured?

**Comment by harshavardhana** [comment]
Please explain your deployment first @Nik0-0 until then closing the issue.
