### ISSUE TITLE
fix low hanging data races in internal/grid implementation

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#19295]
## NOTE
If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.

## Expected Behavior
No races

## Current Behavior
```
==================
WARNING: DATA RACE
Read at 0x00c000245be3 by goroutine 149:
  testing.(*common).logDepth()
      /opt/hostedtoolcache/go/1.21.8/x64/src/testing/testing.go:1011 +0xcd
  testing.(*common).log()
      /opt/hostedtoolcache/go/1.21.8/x64/src/testing/testing.go:1004 +0x7d
  testing.(*common).Log()
      /opt/hostedtoolcache/go/1.21.8/x64/src/testing/testing.go:1045 +0x55
  github.com/minio/minio/internal/grid.testStreamCancel.func2.1()
      /home/runner/work/minio/minio/internal/grid/grid_test.go:473 +0x124
  github.com/minio/minio/internal/grid.(*muxServer).handleRequests()
      /home/runner/work/minio/minio/internal/grid/muxserver.go:232 +0x21d
  github.com/minio/minio/internal/grid.newMuxStream.func3()
      /home/runner/work/minio/minio/internal/grid/muxserver.go:143 +0x23b

Previous write at 0x00c000245be3 by goroutine 136:
  testing.tRunner.func1()
      /opt/hostedtoolcache/go/1.21.8/x64/src/testing/testing.go:1582 +0x8fa
  runtime.deferreturn()
      /opt/hostedtoolcache/go/1.21.8/x64/src/runtime/panic.go:477 +0x30
  testing.(*T).Run.func1()
      /opt/hostedtoolcache/go/1.21.8/x64/src/testing/testing.go:1648 +0x44

Goroutine 149 (running) created at:
  github.com/minio/minio/internal/grid.newMuxStream()
      /home/runner/work/minio/minio/internal/grid/muxserver.go:140 +0xb30
  github.com/minio/minio/internal/grid.(*Connection).handleConnectMux.func2()
      /home/runner/work/minio/minio/internal/grid/connection.go:1250 +0x125
  github.com/minio/minio/internal/grid.(*lockedServerMap).LoadOrCompute()
      /home/runner/work/minio/minio/internal/grid/grid.go:283 +0x91
  github.com/minio/minio/internal/grid.(*Connection).handleConnectMux()
      /home/runner/work/minio/minio/internal/grid/connection.go:1249 +0x332
  github.com/minio/minio/internal/grid.(*Connection).handleMsg()
      /home/runner/work/minio/minio/internal/grid/connection.go:1201 +0x129
  github.com/minio/minio/internal/grid.(*Connection).handleMessages.func1()
      /home/runner/work/minio/minio/internal/grid/connection.go:982 +0x5b9
```

Occasional failure here

## Possible Solution
Not sure

## Steps to Reproduce (for bugs)
`go test -race --count 1000` times if you are lucky.

## Your Environment
Latest minio master

**Comment by jiuker** [comment]
```go
package grid

import (
	"fmt"
	"testing"
	"time"
)

func TestStreamSuite1(t *testing.T) {
	t.Run("testStreamCancel", func(t *testing.T) {
		defer timeout(5 * time.Second)()
		go func() {
			defer func() {
				if e := recover(); e != nil {
					t.Log("asd")
				}
			}()
			panic(fmt.Errorf("asd"))
		}()
	})
	return
}
```
go test -race --count 10000 -run=TestStreamSuite1

```log
jiuker@jiukerdeMacBook-Pro grid % go test -race -run=TestStreamSuite1  
PASS
==================
WARNING: DATA RACE
Read at 0x00c00033a523 by goroutine 12:
  testing.(*common).logDepth()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1017 +0x4af
  testing.(*common).log()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1004 +0x7d
  testing.(*common).Log()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1045 +0x55
  github.com/minio/minio/internal/grid.TestStreamSuite1.func1.1.1()
      /Users/jiuker/workspace/go/src/minio/internal/grid/mytest_test.go:15 +0x6a
  runtime.gopanic()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/runtime/panic.go:920 +0x26f

Previous write at 0x00c00033a523 by goroutine 9:
  testing.tRunner.func1()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1582 +0x81a
  runtime.deferreturn()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/runtime/panic.go:477 +0x30
  testing.(*T).Run.func1()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1648 +0x44

Goroutine 12 (running) created at:
  github.com/minio/minio/internal/grid.TestStreamSuite1.func1()
      /Users/jiuker/workspace/go/src/minio/internal/grid/mytest_test.go:12 +0xb1
  testing.tRunner()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1595 +0x238
  testing.(*T).Run.func1()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1648 +0x44

Goroutine 9 (finished) created at:
  testing.(*T).Run()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1648 +0x82a
  testing.runTests.func1()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:2054 +0x84
  testing.tRunner()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1595 +0x238
  testing.runTests()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:2052 +0x896
  testing.(*M).Run()
      /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1925 +0xb57
  main.main()
      _testmain.go:149 +0x2bd
==================
panic: asd [recovered]
        panic: Log in goroutine after TestStreamSuite1/testStreamCancel has completed: asd


goroutine 24 [running]:
testing.(*common).logDepth(0xc00033a820, {0xc0000140ec, 0x4}, 0x3)
        /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1022 +0x674
testing.(*common).log(...)
        /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1004
testing.(*common).Log(0xc00033a820, {0xc00007ee68, 0x1, 0x1})
        /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/testing/testing.go:1045 +0x7e
github.com/minio/minio/internal/grid.TestStreamSuite1.func1.1.1()
        /Users/jiuker/workspace/go/src/minio/internal/grid/mytest_test.go:15 +0x6b
panic({0x100aa17a0?, 0xc000046040?})
        /Users/jiuker/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.21.3.darwin-amd64/src/runtime/panic.go:920 +0x270
github.com/minio/minio/internal/grid.TestStreamSuite1.func1.1()
        /Users/jiuker/workspace/go/src/minio/internal/grid/mytest_test.go:18 +0xa7
created by github.com/minio/minio/internal/grid.TestStreamSuite1.func1 in goroutine 22
        /Users/jiuker/workspace/go/src/minio/internal/grid/mytest_test.go:12 +0xb2
exit status 2
FAIL    github.com/minio/minio/internal/grid    0.640s
jiuker@jiukerdeMacBook-Pro grid % 
```
@klauspost @harshavardhana cc

**Comment by klauspost** [comment]
It is injecting the logger with the `testing.T` to capture log errors.

This is testing only. You are welcome to see if you can come up with a cleaner solution.
