### ISSUE TITLE
fatal error: timer data corruption 

### ISSUE THREAD

**Issue by titansmc** [minio/minio#19531]
## Expected Behavior
To work

## Current Behavior

Here is the full log:
[messages.txt](https://github.com/minio/minio/files/15007716/messages.txt)

```
Apr 17 07:43:32 ops-object05 systemd[1]: timedatex.service: Succeeded.
Apr 17 07:45:23 ops-object05 minio[18751]: IAM refresh took 49.77s
Apr 17 07:49:46 ops-object05 minio[18751]: fatal error: timer data corruption
Apr 17 07:49:46 ops-object05 minio[18751]: runtime stack:
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.throw({0x2c4d0eb?, 0x0?})
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/panic.go:1077 +0x5c fp=0xc009991d60 sp=0xc009991d30 pc=0x43b77c
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.badTimer()
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/time.go:1143 +0x1f fp=0xc009991d80 sp=0xc009991d60 pc=0x45d87f
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.clearDeletedTimers(0xc00008ef00)
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/time.go:957 +0x3da fp=0xc009991de8 sp=0xc009991d80 pc=0x45d39a
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.checkTimers(0xc00008ef00, 0x6354d00?)
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/proc.go:3707 +0x17c fp=0xc009991e30 sp=0xc009991de8 pc=0x444d5c
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.findRunnable()
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/proc.go:2912 +0x74 fp=0xc009991f40 sp=0xc009991e30 pc=0x4430d4
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.schedule()
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/proc.go:3582 +0xb1 fp=0xc009991f78 sp=0xc009991f40 pc=0x4449f1
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.park_m(0xc0098431e0?)
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/proc.go:3745 +0x11f fp=0xc009991fc0 sp=0xc009991f78 pc=0x444eff
Apr 17 07:49:46 ops-object05 minio[18751]: traceback: unexpected SPWRITE function runtime.mcall
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.mcall()
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/asm_amd64.s:458 +0x4e fp=0xc009991fd8 sp=0xc009991fc0 pc=0x47004e
Apr 17 07:49:46 ops-object05 minio[18751]: goroutine 1 [chan receive, 196 minutes]:
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.gopark(0x2c3534c?, 0xd?, 0xd0?, 0xf8?, 0x10?)
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/proc.go:398 +0xce fp=0xc01a2c2f28 sp=0xc01a2c2f08 pc=0x43e5ce
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.chanrecv(0xc0001d2ae0, 0x0, 0x1)
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/chan.go:583 +0x3cd fp=0xc01a2c2fa0 sp=0xc01a2c2f28 pc=0x409a0d
Apr 17 07:49:46 ops-object05 minio[18751]: runtime.chanrecv1(0x2c3f500?, 0x2c25ee1?)
Apr 17 07:49:46 ops-object05 minio[18751]: #011runtime/chan.go:442 +0x12 fp=0xc01a2c2fc8 sp=0xc01a2c2fa0 pc=0x409612
Apr 17 07:49:46 ops-object05 minio[18751]: github.com/minio/minio/cmd.serverMain(0xc000103ba0)
Apr 17 07:49:46 ops-object05 minio[18751]: #011github.com/minio/minio/cmd/server-main.go:1045 +0xecb fp=0xc01a2c3478 sp=0xc01a2c2fc8 pc=0x239e82b
```

## Steps to Reproduce (for bugs)
Upgrade to `Version: 2024-01-05T22:17:24Z`

## Context
Crashing few times a day

## Regression
Don't know

## Your Environment

* Version used (`minio --version`): `2024-01-05T22:17:24Z`
* Server setup and configuration: `Rocky 8`
* Operating System and version (`uname -a`): `4.18.0-305.19.1.el8_4.x86_64`

**Comment by klauspost** [comment]
Please upgrade to latest, which is compiled with a newer point release (Go 1.21.9 vs 1.21.5).

**Comment by titansmc** [comment]
I have upgraded to latest, let's see, I will report back.
