### ISSUE TITLE
Service gets regularly killed with status=11/SEGV

### ISSUE THREAD

**Issue by sebastienbonami** [minio/minio#19822]
## Expected Behavior

The MinIO service on each node of my cluster should run 24/7.

## Current Behavior

About every day or so, the MinIO service on one of the nodes of my cluster gets killed. It's not always the same node.

Examples of logs when this happens:
```
minio[149597]: unexpected fault address 0x3a91
minio[149597]: fatal error: fault
systemd[1]: minio.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: minio.service: Failed with result 'signal'.
systemd[1]: minio.service: Consumed 4d 4h 23min 7.774s CPU time.
systemd[1]: minio.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped "Minio Service".
```

```
minio[149306]: runtime: g16194507552: frame.sp=0xc003ea7ca8 top=0xc003eadfe0
minio[149306]:         stack=[0xc003e9e000-0xc003eae000
minio[149306]: fatal error: traceback did not unwind completely
minio[149306]: runtime stack:
minio[149306]: runtime.throw({0x2d419ab?, 0x0?})
minio[149306]:         runtime/panic.go:1077 +0x5c fp=0xc23e25fa30 sp=0xc23e25fa00 pc=0x43bb1c
minio[149306]: runtime.(*unwinder).finishInternal(0xc23e25fad8?)
minio[149306]:         runtime/traceback.go:568 +0x12a fp=0xc23e25fa70 sp=0xc23e25fa30 pc=0x4627aa
minio[149306]: runtime.(*unwinder).next(0xc23e25fc98?)
minio[149306]:         runtime/traceback.go:449 +0x235 fp=0xc23e25fae8 sp=0xc23e25fa70 pc=0x4625b5
minio[149306]: runtime.scanstack(0xc224df4ea0, 0x2d?)
minio[149306]:         runtime/mgcmark.go:802 +0x272 fp=0xc23e25fe20 sp=0xc23e25fae8 pc=0x422772
minio[149306]: runtime.markroot.func1()
minio[149306]:         runtime/mgcmark.go:240 +0xb5 fp=0xc23e25fe70 sp=0xc23e25fe20 pc=0x4215f5
minio[149306]: runtime.markroot(0xc000070640, 0x1926, 0x1)
minio[149306]:         runtime/mgcmark.go:214 +0x1a8 fp=0xc23e25ff18 sp=0xc23e25fe70 pc=0x421288
minio[149306]: runtime.gcDrain(0xc000070640, 0x3)
minio[149306]:         runtime/mgcmark.go:1069 +0x379 fp=0xc23e25ff78 sp=0xc23e25ff18 pc=0x4231d9
minio[149306]: runtime.gcBgMarkWorker.func2()
minio[149306]:         runtime/mgc.go:1368 +0xa5 fp=0xc23e25ffc8 sp=0xc23e25ff78 pc=0x41f945
minio[149306]: runtime.systemstack()
minio[149306]:         runtime/asm_amd64.s:509 +0x4a fp=0xc23e25ffd8 sp=0xc23e25ffc8 pc=0x4704ca
... (AROUND 1300 LINES)
minio[149306]: goroutine 162 [select]:
minio[149306]: runtime.gopark(0xc001224f10?, 0x2?, 0x4a?, 0x2c?, 0xc001224ecc?)
minio[149306]:         runtime/proc.go:398 +0xce fp=0xc001224d50 sp=0xc001224d30 pc=0x43e96e
minio[149306]: runtime.selectgo(0x0, 0x0, 0x0?, 0x0, 0x0?, 0x0)
minio[149306]:         runtime/select.go:327 +0x725 fp=0xc001224e70 sp=0xc001224d50 pc=0x44f025
minio[149306]: created by github.com/minio/minio/cmd.newXLStorageDiskIDCheck in goroutine 1
minio[149306]:         github.com/minio/minio/cmd/xl-storage-disk-id-check.go:193 +0x285
minio[149306]: goroutine 4063766823625570153 [???, locked to thread]:
systemd[1]: minio.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: minio.service: Failed with result 'signal'.
systemd[1]: minio.service: Consumed 6d 19h 45min 48.672s CPU time.
systemd[1]: minio.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped "Minio Service".
```

```
minio[136799]: fatal error: unexpected signal during runtime execution
minio[136799]: fatal error: unexpected signal during runtime execution
minio[136799]: fatal error: slice bounds out of range
minio[136799]: fatal error: panic while printing panic value: type runtime.errorString
minio[136799]: runtime: g9194286908: frame.sp=0xc1ab62de88 top=0xc1ab62dfe0
minio[136799]:         stack=[0xc1ab61e000-0xc1ab62e000
minio[136799]: fatal error: traceback did not unwind completely
minio[136799]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x10600000000 pc=0x47e497]
minio[136799]: goroutine 9193136040 [running]:
minio[136799]: runtime.throw({0x2d5d0c0?, 0xc2437e6c58?})
minio[136799]:         runtime/panic.go:1077 +0x5c fp=0xc2437e6c10 sp=0xc2437e6be0 pc=0x43bb1c
minio[136799]: runtime.sigpanic()
minio[136799]:         runtime/signal_unix.go:845 +0x3e9 fp=0xc2437e6c70 sp=0xc2437e6c10 pc=0x452ec9
minio[136799]: sync.(*poolDequeue).popHead(0x1000000000000000?)
minio[136799]:         sync/poolqueue.go:115 +0x17 fp=0xc2437e6cb8 sp=0xc2437e6c70 pc=0x47e497
minio[136799]: sync.(*poolChain).popHead(0xc1b1a2ee60?)
minio[136799]:         sync/poolqueue.go:261 +0x32 fp=0xc2437e6cd8 sp=0xc2437e6cb8 pc=0x47e8f2
minio[136799]: sync.(*Pool).Get(0xc1b1a2ee60)
minio[136799]:         sync/pool.go:138 +0x5a fp=0xc2437e6d10 sp=0xc2437e6cd8 pc=0x47dc7a
minio[136799]: github.com/klauspost/compress/s2.(*Writer).write(0xc1b1a2ee00, {0xc16f5e2000, 0x4000, 0x4000})
minio[136799]:         github.com/klauspost/compress@v1.17.7/s2/writer.go:496 +0x2e5 fp=0xc2437e6de8 sp=0xc2437e6d10 pc=0x10f3d65
minio[136799]: github.com/klauspost/compress/s2.(*Writer).Write(0xc1b1a2ee00, {0xc16d1e0800, 0x48b, 0x800})
minio[136799]:         github.com/klauspost/compress@v1.17.7/s2/writer.go:192 +0x18b fp=0xc2437e6e48 sp=0xc2437e6de8 pc=0x10f256b
minio[136799]: github.com/tinylib/msgp/msgp.(*Writer).flush(0xc16d1a7410)
minio[136799]:         github.com/tinylib/msgp@v1.1.9/msgp/write.go:166 +0x48 fp=0xc2437e6e90 sp=0xc2437e6e48 pc=0x9df048
minio[136799]: github.com/tinylib/msgp/msgp.(*Writer).Write(0xc16d1a7410, {0xc268744000, 0x45a, 0x1000})
minio[136799]:         github.com/tinylib/msgp@v1.1.9/msgp/write.go:284 +0x3d fp=0xc2437e6ec8 sp=0xc2437e6e90 pc=0x9df97d
minio[136799]: github.com/tinylib/msgp/msgp.(*Writer).WriteBytes(0xc26901d000?, {0xc268744000, 0x45a, 0x1000})
minio[136799]:         github.com/tinylib/msgp@v1.1.9/msgp/write.go:450 +0x78 fp=0xc2437e6f00 sp=0xc2437e6ec8 pc=0x9e02d8
minio[136799]: github.com/minio/minio/cmd.(*metacacheWriter).stream.func1()
minio[136799]:         github.com/minio/minio/cmd/metacache-stream.go:186 +0x1cc fp=0xc2437e6fe0 sp=0xc2437e6f00 pc=0x22a146c
minio[136799]: runtime.goexit()
minio[136799]:         runtime/asm_amd64.s:1650 +0x1 fp=0xc2437e6fe8 sp=0xc2437e6fe0 pc=0x4722c1
minio[136799]: created by github.com/minio/minio/cmd.(*metacacheWriter).stream in goroutine 9193135966
minio[136799]:         github.com/minio/minio/cmd/metacache-stream.go:169 +0x147
... (AROUND 400 LINES)
minio[136799]: goroutine 29 [select, 1 minutes]:
minio[136799]: runtime.gopark(0xc2529e2fa8?, 0x2?, 0x70?, 0xfd?, 0xc2529e2f84?)
minio[136799]:         runtime/proc.go:398 +0xce fp=0xc2529e2e28 sp=0xc2529e2e08 pc=0x43e96e
minio[136799]: runtime.selectgo(0xc2529e2fa8, 0xc2529e2f80, 0x1dff760?, 0x0, 0xc001265f55?, 0x1)
minio[136799]:         runtime/select.go:327 +0x725 fp=0xc2529e2f48 sp=0xc2529e2e28 pc=0x44f025
minio[136799]: github.com/minio/minio/cmd.runDNSCache.func1()
minio[136799]:         github.com/minio/minio/cmd/common-main.go:512 +0xcb fp=0xc2529e2fe0 sp=0xc2529e2f48 pc=0x212002b
minio[136799]: runtime.goexit()
minio[136799]: runtime.goexit()
minio[136799]:         runtime/asm_amd64.s:1650 +0x1 fp=0xc2529e2fe8 sp=0xc2529e2fe0 pc=0x4722c1
minio[136799]: created by github.com/minio/minio/cmd.runDNSCache in goroutine 1
minio[136799]:         github.com/minio/minio/cmd/common-main.go:507 +0x77
systemd[1]: minio.service: Main process exited, code=killed, status=11/SEGV
systemd[1]: minio.service: Failed with result 'signal'.
systemd[1]: minio.service: Consumed 5d 6h 35min 43.954s CPU time.
systemd[1]: minio.service: Scheduled restart job, restart counter is at 1.
systemd[1]: Stopped "Minio Service".
```

## Context

I have a cluster of 4 nodes with the same config.

## Regression

Not sure, but I was having the same problem with version `RELEASE.2023-12-23T07-19-11Z` and now I'm using `RELEASE.2024-04-06T05-26-02Z`.

## Your Environment

* Version used (`minio --version`):
```
minio version RELEASE.2024-04-06T05-26-02Z (commit-id=9d63bb1b418f6c1bbcc8434fff5d8aba810ee5d7)
Runtime: go1.21.9 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2024 MinIO, Inc
```
* Server setup and configuration: https://github.com/Ferlab-Ste-Justine/terraform-cloudinit-templates/blob/v0.19.0/minio/user_data.yaml.tpl
* Operating System and version (`uname -a`):
```
Linux minio-1 5.15.0-72-generic #79-Ubuntu SMP Wed Apr 19 08:22:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by harshavardhana** [comment]
yeah this is a known upstream bug reproduced under specific Linux kernels. Refer https://github.com/minio/minio/issues/18808#issuecomment-1895441463

**Comment by klauspost** [comment]
Also upgrade.
