### ISSUE TITLE
MinIO-daemon crashes when listing objects through MinIO-Console

### ISSUE THREAD

**Issue by hamalchristiaan** [minio/minio#19989]
## Expected Behavior
No crash.

## Current Behavior
MinIO-daemon crashes when listing objects through MinIO-Console. Unconfirmed if it happens with the MinIO-Client as well. Audit-logs show a "ListObjectVersions" api-call right before crashing. Syslog shows "panic: send on closed channel".

## Steps to Reproduce (for bugs)
List objects in large bucket.

## Your Environment
* Version used (`minio --version`): minio version RELEASE.2024-06-11T03-13-30Z (commit-id=55aa431578ddc6c9b57b873bf39ebe9d3ee10239)
* Operating System and version (`uname -a`): Linux <redacted hostname> 5.10.0-30-amd64 #1 SMP Debian 5.10.218-1 (2024-06-01) x86_64 GNU/Linux

**Comment by hamalchristiaan** [comment]
Jun 24, 2024 @ 14:04:40.000	panic: send on closed channel

Jun 24, 2024 @ 14:04:40.000	goroutine 6808071233 [running]:

Jun 24, 2024 @ 14:04:40.000	#011github.com/minio/console@v1.5.0/api/ws_objects.go:49 +0x7d

Jun 24, 2024 @ 14:04:40.000	github.com/minio/console/api.(*wsMinioClient).objectManager.func2({0x4, 0xc02ff4c140, 0x0, {0xc02252a398, 0x8}, {0xc02252a3a0, 0xd}, {0x0, 0x0, 0x0}})

Jun 24, 2024 @ 14:04:40.000	#011github.com/minio/console@v1.5.0/api/ws_objects.go:130 +0x4b9

Jun 24, 2024 @ 14:04:40.000	github.com/minio/console/api.(*wsMinioClient).objectManager.func3.2()

Jun 24, 2024 @ 14:04:40.000	#011github.com/minio/console@v1.5.0/api/ws_objects.go:109 +0x45c

Jun 24, 2024 @ 14:04:40.000	created by github.com/minio/console/api.(*wsMinioClient).objectManager.func3 in goroutine 6807454044

**Comment by harshavardhana** [comment]
> MinIO-daemon crashes when listing objects through MinIO-Console. Unconfirmed if it happens with the MinIO-Client as well. Audit-logs show a "ListObjectVersions" api-call right before crashing. Syslog shows "panic: send on closed channel".

Yeah this is apparently the Console UI implementation issue.
