### ISSUE TITLE
MinIO server support 50TB object,but mc can't support

### ISSUE THREAD

**Issue by myrust-go** [minio/minio#20621]
## Expected Behavior

MinIO server support 50TB object,but mc can't support

## Current Behavior

Use mc  put a object to  MinIO server. but, the command line tips "panic":

```
panic: Your proposed upload size ‘27487790694400’ exceeds the maximum allowed object size ‘5497558138880’ for single PUT operation.

goroutine 67 [running]:
[github.com/minio/mc/cmd.(*ParallelManager).enoughMemForUpload.func1(0x190000000000)](http://github.com/minio/mc/cmd.(*ParallelManager).enoughMemForUpload.func1(0x190000000000))
        [github.com/minio/mc/cmd/parallel-manager.go:189](http://github.com/minio/mc/cmd/parallel-manager.go:189) +0x51
[github.com/minio/mc/cmd.(*ParallelManager).enoughMemForUpload](http://github.com/minio/mc/cmd.(*ParallelManager).enoughMemForUpload)(0xc0004ca780, 0x190000000000)
        [github.com/minio/mc/cmd/parallel-manager.go:204](http://github.com/minio/mc/cmd/parallel-manager.go:204) +0x94
[github.com/minio/mc/cmd.(*ParallelManager).doQueueTask](http://github.com/minio/mc/cmd.(*ParallelManager).doQueueTask)(0xc0004ca780, {0xc00051a0a0, 0x0, 0x190000000000})
        [github.com/minio/mc/cmd/parallel-manager.go:210](http://github.com/minio/mc/cmd/parallel-manager.go:210) +0x2d
[github.com/minio/mc/cmd.(*ParallelManager).queueTask(...)](http://github.com/minio/mc/cmd.(*ParallelManager).queueTask(...))
        [github.com/minio/mc/cmd/parallel-manager.go:167](http://github.com/minio/mc/cmd/parallel-manager.go:167)
[github.com/minio/mc/cmd.doCopySession.func2()](http://github.com/minio/mc/cmd.doCopySession.func2())
        [github.com/minio/mc/cmd/cp-main.go:441](http://github.com/minio/mc/cmd/cp-main.go:441) +0x71f
created by [github.com/minio/mc/cmd.doCopySession](http://github.com/minio/mc/cmd.doCopySession) in goroutine 1
        [github.com/minio/mc/cmd/cp-main.go:371](http://github.com/minio/mc/cmd/cp-main.go:371) +0x630
```

## Possible Solution

Edit MinIO client (mc)  signel object's size limit.
Old limit: 5TB;
New limit: 50TB;

## Steps to Reproduce (for bugs)

1. mc cp  TEST_OBJECT   minio/test/

## Your Environment

* Version used (`minio --version`):   [minio-20241029160148.0.0
* Server setup and configuration:   
* Operating System and version (`uname -a`):  Linux ecs-e86a 3.10.0-1160.92.1.el7.x86_64 #1 SMP Tue Jun 20 11:48:01 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
*  mc version:mc version RELEASE.2024-10-08T09-37-26Z (commit-id=cf128de2cf42e763e7bd30c6df8b749fa94e0c10)

**Comment by klauspost** [comment]
For mc we stick to the S3 maximum, 5TB.
