### ISSUE TITLE
go1.7: minio crashes when uploading a 5 GiB file

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#2456]
This doesn't happen systematically, please test on your side:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x59d34f]

goroutine 45 [running]:
panic(0xa0f2e0, 0xc420010130)
        /home/vadmeste/work/go/src/runtime/panic.go:500 +0x1a1
net/http.(*persistConn).closeConnIfStillIdle(0xc420513500)
        /home/vadmeste/work/go/src/net/http/transport.go:1311 +0x2f
net/http.(*persistConn).(net/http.closeConnIfStillIdle)-fm()
        /home/vadmeste/work/go/src/net/http/transport.go:683 +0x2a
created by time.goFunc
        /home/vadmeste/work/go/src/time/sleep.go:154 +0x44
```

**Comment by harshavardhana** [comment]
Closing as not reproducible anymore.
