### ISSUE TITLE
[distributed] Unable to look for valid XL metadata content

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#2562]
```
2016/08/28 00:29:12 http: panic serving 127.0.0.1:58286: Unable to look for valid XL metadata content
goroutine 380 [running]:
net/http.(*conn).serve.func1(0xc820530500)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/net/http/server.go:1389 +0xc1
panic(0xaa08c0, 0xc82046c700)
        /home/minio/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:426 +0x4e9
github.com/minio/minio/cmd.pickValidXLMeta(0xc820163500, 0x4, 0x4, 0xecf5489c8, 0x36e518ee, 0x1259b20, 0x0, 0x0, 0x0, 0x0, ...)
        /home/minio/gopath/src/github.com/minio/minio/cmd/xl-v1-metadata.go:204 +0x275
github.com/minio/minio/cmd.xlObjects.GetObject(0xc8203c1e00, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, 0xc82046aea0, 0xc8203c1e40, 0x1, ...)
        /home/minio/gopath/src/github.com/minio/minio/cmd/xl-v1-object.go:82 +0x9c3
github.com/minio/minio/cmd.(*xlObjects).GetObject(0xc820386050, 0xd29230, 0xa, 0xc8204495c0, 0x1e, 0x0, 0x24f, 0x7ff43d4d6d90, 0xc82022b030, 0x0, 
...)
        <autogenerated>:572 +0x12b
github.com/minio/minio/cmd.readBucketPolicy(0xc8203ee612, 0xa, 0x7ff43d511760, 0xc820386050, 0x1, 0x0, 0x0)
        /home/minio/gopath/src/github.com/minio/minio/cmd/bucket-policy.go:138 +0x40f
github.com/minio/minio/cmd.loadAllBucketPolicies(0x7ff43d511760, 0xc820386050, 0xc8203d5c20, 0x7ff43d4df190, 0xc820449580)
        /home/minio/gopath/src/github.com/minio/minio/cmd/bucket-policy.go:76 +0x1c1
github.com/minio/minio/cmd.initBucketPolicies(0x7ff43d511760, 0xc820386050, 0x0, 0x0)
        /home/minio/gopath/src/github.com/minio/minio/cmd/bucket-policy.go:98 +0x5e
github.com/minio/minio/cmd.newObjectLayerFactory.func1(0x0, 0x0)
        /home/minio/gopath/src/github.com/minio/minio/cmd/routers.go:82 +0x379
github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler(0xc8202ecf40, 0x7ff43d510e60, 0xc82007e1a0, 0xc82067b5e0)
```

**Comment by harshavardhana** [comment]
Looks like a stale bucket, closing.
