### ISSUE TITLE
[distributed] Optimize preamble code to minimize bucket locks

### ISSUE THREAD

**Issue by fwessels** [minio/minio#2566]
When eg doing a PutObject for distributed, there are 4 preceding RLock()s performend prior to actually acquiring a WriteLock.
Now that distributed locks have become expensive, we should try and limit this to ideally a single lock.

```
    cmd/xl-v1-bucket.go:181       --> GetBucketInfo()
    cmd/xl-v1-list-objects.go:115 --> ListObjects --> isBucketExist()
    cmd/xl-v1-list-objects.go:115 --> ListObjects --> isBucketExist()
    cmd/xl-v1-object.go:487       --> PutObject() --> isBucketExist()
```

Detailed call stacks:

```
 "bucket" 

goroutine 457 [running]:
github.com/minio/minio/cmd.xlObjects.GetBucketInfo(0xc82000a0c0, 0x4, 0x4, 0xc8202b2fc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-bucket.go:181 +0x1a7
github.com/minio/minio/cmd.(*xlObjects).GetBucketInfo(0xc8202a9030, 0xc82046d6a5, 0x5, 0x0, 0x0, 0x0, 0xc800000000, 0x0, 0x0, 0x0)
    <autogenerated>:541 +0x102
github.com/minio/minio/cmd.objectAPIHandlers.GetBucketLocationHandler(0xc820019f00, 0x7f16bdcac340, 0xc82022dee0, 0xc820310a80)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/bucket-handlers.go:90 +0x222
github.com/minio/minio/cmd.(objectAPIHandlers).GetBucketLocationHandler-fm(0x7f16bdcac340, 0xc82022dee0, 0xc820310a80)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/api-router.go:60 +0x41
net/http.HandlerFunc.ServeHTTP(0xc820465e90, 0x7f16bdcac340, 0xc82022dee0, 0xc820310a80)
    /usr/local/go/src/net/http/server.go:1618 +0x3a

 "bucket" 
goroutine 457 [running]:
github.com/minio/minio/cmd.xlObjects.isBucketExist(0xc82000a0c0, 0x4, 0x4, 0xc8202b2fc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-bucket.go:160 +0x5d
github.com/minio/minio/cmd.xlObjects.ListObjects(0xc82000a0c0, 0x4, 0x4, 0xc8202b2fc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-list-objects.go:115 +0x162
github.com/minio/minio/cmd.(*xlObjects).ListObjects(0xc8202a9030, 0xc82046bd15, 0x5, 0xc820465310, 0x9, 0x0, 0x0, 0xc8204652b1, 0x1, 0x3e8, ...)
    <autogenerated>:551 +0x15d
github.com/minio/minio/cmd.objectAPIHandlers.ListObjectsV1Handler(0xc820019f00, 0x7f16bdcac340, 0xc8203941a0, 0xc820267880)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/bucket-handlers-listobjects.go:168 +0x3d8
github.com/minio/minio/cmd.(objectAPIHandlers).ListObjectsV1Handler-fm(0x7f16bdcac340, 0xc8203941a0, 0xc820267880)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/api-router.go:72 +0x41
net/http.HandlerFunc.ServeHTTP(0xc82045d150, 0x7f16bdcac340, 0xc8203941a0, 0xc820267880)
    /usr/local/go/src/net/http/server.go:1618 +0x3a


 "bucket" 
goroutine 457 [running]:
github.com/minio/minio/cmd.xlObjects.isBucketExist(0xc82000a0c0, 0x4, 0x4, 0xc8202b2fc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-bucket.go:160 +0x5d
github.com/minio/minio/cmd.xlObjects.ListObjects(0xc82000a0c0, 0x4, 0x4, 0xc8202b2fc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-list-objects.go:115 +0x162
github.com/minio/minio/cmd.(*xlObjects).ListObjects(0xc8202a9030, 0xc8204564b5, 0x5, 0xc82045cb10, 0x9, 0x0, 0x0, 0xc82045ca51, 0x1, 0x3e8, ...)
    <autogenerated>:551 +0x15d
github.com/minio/minio/cmd.objectAPIHandlers.ListObjectsV1Handler(0xc820019f00, 0x7f16bdcac340, 0xc8203948f0, 0xc8203115e0)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/bucket-handlers-listobjects.go:168 +0x3d8
github.com/minio/minio/cmd.(objectAPIHandlers).ListObjectsV1Handler-fm(0x7f16bdcac340, 0xc8203948f0, 0xc8203115e0)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/api-router.go:72 +0x41
net/http.HandlerFunc.ServeHTTP(0xc82045d150, 0x7f16bdcac340, 0xc8203948f0, 0xc8203115e0)
    /usr/local/go/src/net/http/server.go:1618 +0x3a


 "bucket" 
goroutine 457 [running]:
github.com/minio/minio/cmd.xlObjects.isBucketExist(0xc82000a0c0, 0x4, 0x4, 0xc8202b2fc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-bucket.go:160 +0x5d
github.com/minio/minio/cmd.xlObjects.PutObject(0xc82000a0c0, 0x4, 0x4, 0xc8202b2fc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-object.go:487 +0x1a1
github.com/minio/minio/cmd.(*xlObjects).PutObject(0xc8202a9030, 0xc82044c1c5, 0x5, 0xc82044c1cb, 0x9, 0x19000, 0x7f16bdcac8d0, 0xc82044c7a0, 0xc8204173b0, 0x0, ...)
    <autogenerated>:574 +0x14c
github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler(0xc820019f00, 0x7f16bdcac340, 0xc82005e750, 0xc820267420)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/object-handlers.go:469 +0x1041
github.com/minio/minio/cmd.(objectAPIHandlers).PutObjectHandler-fm(0x7f16bdcac340, 0xc82005e750, 0xc820267420)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/api-router.go:53 +0x41
net/http.HandlerFunc.ServeHTTP(0xc820465930, 0x7f16bdcac340, 0xc82005e750, 0xc820267420)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
```

**Comment by harshavardhana** [comment]
isBucketExist() doesn't hold read locks anymore should be optimized to reduce these locked operations.
