### ISSUE TITLE
[distributed] Check if read and write lock can be combined for multipart uploads 

### ISSUE THREAD

**Issue by fwessels** [minio/minio#2568]
As per the calls stack below as well as the "lock"-traces, see if a read and write lock for the same name (eg `multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987`) can be combined for multipart uploads (ie just use a single write lock for both actions).

```
    cmd/xl-v1-multipart.go:342 --> PutObjectPart() --> RLock()
    cmd/xl-v1-multipart.go:424 --> PutObjectPart() --> Lock()
```

Details call stacks:

```
 .minio.sys multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987
goroutine 1827 [running]:
github.com/minio/minio/cmd.(*nsLockMap).RLock(0xc82035b460, 0xd2af30, 0xa, 0xc8202aa380, 0x3e)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/namespace-lock.go:193 +0x1e8
github.com/minio/minio/cmd.xlObjects.PutObjectPart(0xc82000a0c0, 0x4, 0x4, 0xc82028dcc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-multipart.go:342 +0x4ab
github.com/minio/minio/cmd.(*xlObjects).PutObjectPart(0xc8201d1e30, 0xc82051ecc5, 0x5, 0xc82051eccb, 0x9, 0xc82051eceb, 0x24, 0x4, 0x3424000, 0x7f2c6f53d930, ...)
    <autogenerated>:564 +0x188
github.com/minio/minio/cmd.objectAPIHandlers.PutObjectPartHandler(0xc820019f00, 0x7f2c6f56e208, 0xc8201456c0, 0xc8203d8540)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/object-handlers.go:637 +0xcb9
github.com/minio/minio/cmd.(objectAPIHandlers).PutObjectPartHandler-fm(0x7f2c6f56e208, 0xc8201456c0, 0xc8203d8540)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/api-router.go:39 +0x41
net/http.HandlerFunc.ServeHTTP(0xc820492e40, 0x7f2c6f56e208, 0xc8201456c0, 0xc8203d8540)
    /usr/local/go/src/net/http/server.go:1618 +0x3a

 .minio.sys multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987
goroutine 1827 [running]:
github.com/minio/minio/cmd.(*nsLockMap).Lock(0xc82035b460, 0xd2af30, 0xa, 0xc8202aa380, 0x3e)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/namespace-lock.go:179 +0x1e8
github.com/minio/minio/cmd.xlObjects.PutObjectPart(0xc82000a0c0, 0x4, 0x4, 0xc82028dcc0, 0x4, 0x4, 0x2, 0x2, 0x2, 0x3, ...)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/xl-v1-multipart.go:424 +0x15c6
github.com/minio/minio/cmd.(*xlObjects).PutObjectPart(0xc8201d1e30, 0xc82051ecc5, 0x5, 0xc82051eccb, 0x9, 0xc82051eceb, 0x24, 0x4, 0x3424000, 0x7f2c6f53d930, ...)
    <autogenerated>:564 +0x188
github.com/minio/minio/cmd.objectAPIHandlers.PutObjectPartHandler(0xc820019f00, 0x7f2c6f56e208, 0xc8201456c0, 0xc8203d8540)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/object-handlers.go:637 +0xcb9
github.com/minio/minio/cmd.(objectAPIHandlers).PutObjectPartHandler-fm(0x7f2c6f56e208, 0xc8201456c0, 0xc8203d8540)
    /home/ec2-user/gopath/src/github.com/minio/minio/cmd/api-router.go:39 +0x41
net/http.HandlerFunc.ServeHTTP(0xc820492e40, 0x7f2c6f56e208, 0xc8201456c0, 0xc8203d8540)
    /usr/local/go/src/net/http/server.go:1618 +0x3a
```
# 
### 100 MB file

"Lock"-trace for `mc cp 100MB.bin myminio/frank/a/b/file1`

```
++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1" true Release success

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true 0
++ RUnlock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true Release success

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true 0
++ RUnlock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true Release success

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true
+++++ Lock   "frank/a/b/file1" true
+++++ Lock     ".minio.sys/multipart/frank/a/b/file1" true
+++ Unlock     ".minio.sys/multipart/frank/a/b/file1" true Release success
+++ Unlock   "frank/a/b/file1" true Release success
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/38292538-6988-4aa3-b88d-780b46dc4a0b" true Release success

++++ RLock "frank/a/b/file1" true 0
++++ RLock "frank/a/b/file1" true 1
++ RUnlock "frank/a/b/file1" true remaining locks: 1
++++ RLock "frank/a/b/file1" true 1
++ RUnlock "frank/a/b/file1" true remaining locks: 1
++ RUnlock "frank/a/b/file1" true Release success (remaining locks: 0)
```
# 
### 250 MB file

"Lock"-trace for `mc cp 250MB.bin myminio/frank/a/b/file1`

```
++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)
++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)
++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)
++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)
++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1" true Release success

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true 0
++ RUnlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true 0
++ RUnlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true 0
++ RUnlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success

++++ RLock "frank" true 0
++ RUnlock "frank" true Release success (remaining locks: 0)

++++ RLock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true 0
++ RUnlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success (remaining locks: 0)

+++++ Lock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success

++++ RLock "frank" true 0
+++++ Lock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true
++ RUnlock "frank" true Release success (remaining locks: 0)
+++++ Lock   "frank/a/b/file1" true
+++++ Lock     ".minio.sys/multipart/frank/a/b/file1" true
+++ Unlock     ".minio.sys/multipart/frank/a/b/file1" true Release success
+++ Unlock   "frank/a/b/file1" true Release success
++++ RLock "frank/a/b/file1" true 0
+++ Unlock ".minio.sys/multipart/frank/a/b/file1/e1ea1af0-bdf0-422d-85a0-a6c4d45e9987" true Release success
++++ RLock "frank/a/b/file1" true 1
++ RUnlock "frank/a/b/file1" true remaining locks: 1
++ RUnlock "frank/a/b/file1" true Release success (remaining locks: 0)
```

**Comment by krishnasrinivas** [comment]
The following two calls can't be combined into one:

```
    cmd/xl-v1-multipart.go:342 --> PutObjectPart() --> RLock()
    cmd/xl-v1-multipart.go:424 --> PutObjectPart() --> Lock()
```

because we do erasureCreateFile in-between them during which if we hold lock parallel uploads of parts will not be possible,

**Comment by fwessels** [comment]
Ok, of course we cannot have that (no parallel uploads), thanks for checking out, closing the issue.
