### ISSUE TITLE
Crash on ARM processor

### ISSUE THREAD

**Issue by alysdal** [minio/minio#2598]
## Expected behaviour

I tried running Minio on my [WD EX2 NAS](http://www.anandtech.com/show/7830/western-digital-my-cloud-ex2-2bay-nas-review). It has a ARM processor so i used that build. However when I try to start it, it gives the error below
## Actual behaviour

Fatal error

```
root@WDNAS apps # ./minio --help
unexpected fault address 0x5b8fcc
fatal error: fault
[signal 0xb code=0x2 addr=0x5b8fcc pc=0x5b8fcc]

goroutine 1 [running, locked to thread]:
runtime.throw(0x7160b8, 0x5)
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/runtime/panic.go:547 +0x78 fp=0x10d31d8c sp=0x10d31d80
runtime.sigpanic()
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/runtime/sigpanic_unix.go:27 +0x280 fp=0x10d31db8 sp=0x10d31d8c
crypto/x509/pkix.init()
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/crypto/x509/pkix/pkix.go:195 fp=0x10d31dbc sp=0x10d31dbc
crypto/x509.init()
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/crypto/x509/x509.go:2071 +0x78 fp=0x10d31dd0 sp=0x10d31dbc
crypto/tls.init()
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/crypto/tls/tls.go:298 +0x68 fp=0x10d31df0 sp=0x10d31dd0
net/http.init()
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/net/http/transport.go:1781 +0x54 fp=0x10d31ea0 sp=0x10d31df0
github.com/minio/minio/cmd.init()
        /home/builder/mygo/src/github.com/minio/minio/cmd/xl-v1.go:246 +0x64 fp=0x10d31f98 sp=0x10d31ea0
main.init()
        /home/builder/mygo/src/github.com/minio/minio/main.go:7 +0x4c fp=0x10d31f9c sp=0x10d31f98
runtime.main()
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/runtime/proc.go:177 +0x274 fp=0x10d31fc4 sp=0x10d31f9c
runtime.goexit()
        /home/builder/.gimme/versions/go1.6.3.linux.amd64/src/runtime/asm_arm.s:990 +0x4 fp=0x10d31fc4 sp=0x10d31fc4
```
## Steps to reproduce the behaviour

```
root@WDNAS apps # wget https://dl.minio.io/server/minio/release/linux-arm/minio
root@WDNAS apps # chmod 755 minio
root@WDNAS apps # ./minio --help
```
## Minio version
- Newest (1st Sept 2016)
## System information

```
root@WDNAS apps # cat /proc/cpuinfo
Processor       : Marvell PJ4Bv7 Processor rev 1 (v7l)
BogoMIPS        : 1196.85
Features        : swp half thumb fastmult vfp edsp vfpv3 vfpv3d16 tls
CPU implementer : 0x56
CPU architecture: 7
CPU variant     : 0x1
CPU part        : 0x581
CPU revision    : 1

Hardware        : Marvell Armada-370
Revision        : 0000
Serial      : 0000000000000000
root@WDNAS apps # uname -a
Linux WDNAS 3.2.40 #4 Fri Jul 31 16:04:18 CST 2015 armv7l GNU/Linux
```

**Comment by harshavardhana** [comment]
This bug has been fixed in master we will be making a new release soon. Thanks for your bug report @alysdal

**Comment by harshavardhana** [comment]
Fixed by https://github.com/minio/minio/commit/c39d3db7a036cdcce44ed020e10574edb2a466a7

**Comment by alysdal** [comment]
Thank you for your quick reply. I really like this project.
