### ISSUE TITLE
"authorization mechanism you have provided is not supported" error with aws-sdk JavaScript client

### ISSUE THREAD

**Issue by olalonde** [minio/minio#2642]
I'm trying to use minio with a Javascript library that uses the official aws-sdk Javascript library (https://github.com/aws/aws-sdk-js/).

I instantiate the client like this:

``` javascript
    const accessKeyId = process.env.S3_ACCESS_KEY_ID
    const secretAccessKey = process.env.S3_SECRET_ACCESS_KEY
    const client = new aws.S3({
      accessKeyId,
      secretAccessKey,
      endpoint: new aws.Endpoint(process.env.S3_ENDPOINT),
      s3ForcePathStyle: true, // needed with minio?
    })
```

with the following variables (I'm running minio locally with docker-compose):

```
export S3_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
export S3_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
export S3_ENDPOINT=http://192.168.99.100:9000
```

The minio server responds with the following error message:

``` javascript
/.../node_modules/aws-sdk/lib/request.js:31
            throw err;
            ^

InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
    at Request.extractError (/.../node_modules/aws-sdk/lib/services/s3.js:538:35)
    at Request.callListeners (/.../node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/.../node_modules/aws-sdk/lib/sequential_executor.js:77:10)
```

**Comment by harshavardhana** [comment]
@olalonde you need to use Signature V4 with Minio server.  Minio server does not support Signature v2. 

```
    const accessKeyId = process.env.S3_ACCESS_KEY_ID
    const secretAccessKey = process.env.S3_SECRET_ACCESS_KEY
    const client = new aws.S3({
      accessKeyId,
      secretAccessKey,
      endpoint: new aws.Endpoint(process.env.S3_ENDPOINT),
      s3ForcePathStyle: true, // needed with minio?
      signatureVersion: 'v4',
    })
```

**Comment by olalonde** [comment]
Thanks, that worked.
