### ISSUE TITLE
AWS sdk signature error.

### ISSUE THREAD

**Issue by rafael-leo-almeida** [minio/minio#2715]
Error on upload with java aws sdk after update from RELEASE.2016-08-21T02-44-47Z to RELEASE.2016-09-11T17-42-18Z

```
com.amazonaws.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 3L137), S3 Extended Request ID: 3L137
    at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1307)
    at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:894)
    at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:597)
    at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:363)
    at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:329)
    at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:308)
    at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3659)
    at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1422)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:131)
    at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:123)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139)
    at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:47)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
```
#1007

``` java
        ClientConfiguration clientConfiguration = new ClientConfiguration();
        clientConfiguration.setSignerOverride("AWSS3V4SignerType");

        AmazonS3 s3 = new AmazonS3Client(credentials, clientConfiguration);
        s3.setEndpoint("http://localhost:9000");
        S3ClientOptions clientOptions = new S3ClientOptions();
        clientOptions.withPathStyleAccess(true);
        clientOptions.disableChunkedEncoding();
        s3.setS3ClientOptions(clientOptions);
        System.setProperty("com.amazonaws.services.s3.disableGetObjectMD5Validation","true");
```

**Comment by harshavardhana** [comment]
> clientOptions.disableChunkedEncoding();

Can you remove this option and try again?

**Comment by rafael-leo-almeida** [comment]
@harshavardhana testing without `clientOptions.disableChunkedEncoding();` working like a charm.

PS: Working on both of last versions.

**Comment by harshavardhana** [comment]
We started supporting streaming signature. Figuring out why regular signature is not working.

**Comment by rafael-leo-almeida** [comment]
It's possible to keep compatibility with clients with chunkedEncoding disabled?

**Comment by harshavardhana** [comment]
Yes definitely sever supports both methods.

**Comment by harshavardhana** [comment]
@rafaelsisweb just tested 'master' works, release lacks the following fix. 

```
commit 241c56e6d76baf1854675d011172b461017b3a79
Author: Kevin Qiu <kevinqiu1@gmail.com>
Date:   Tue Sep 13 13:59:40 2016 -0400

    Use Set instead of Add in the event that the request already contains the content-length (#2683)
```

Will make a release to fix this problem - thanks for reporting @rafaelsisweb .

**Comment by matti** [comment]
so this hasn't been fixed in the `:latest` docker image? why is this issue closed if it's not released?

**Comment by matti** [comment]
oh, it's in `:edge` :D 👯
