### ISSUE TITLE
Sporadic TLS handshare errors

### ISSUE THREAD

**Issue by fwessels** [minio/minio#2985]
During testing sporadic TLS handshake errors were reported (on about 4 out of the 8 servers).

```
2016/10/17 20:35:08 http: TLS handshake error from 93.170.187.41:49846: tls: first record does not look like a TLS handshake
2016/10/17 20:35:09 http: panic serving 93.170.187.41:50374: runtime error: slice bounds out of range
goroutine 42811982 [running]:
net/http.(*conn).serve.func1(0xc42d762180)
    /home/ec2-user/bin/go/src/net/http/server.go:1491 +0x12a
panic(0xab3820, 0xc4200120f0)
    /home/ec2-user/bin/go/src/runtime/panic.go:458 +0x243
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0xee3fa0, 0xc4203b71c0, 0xee8120, 0xc436f78270, 0xc42d871c20)
    /home/ec2-user/go/src/github.com/minio/minio/cmd/generic-handlers.go:242 +0x305
github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP(0xc4203b5710, 0xee8120, 0xc436f78270, 0xc42d871c20)
    <autogenerated>:170 +0x79
github.com/minio/minio/cmd.authHandler.ServeHTTP(0xee39e0, 0xc4203b5710, 0xee8120, 0xc436f78270, 0xc42d871c20)
    /home/ec2-user/go/src/github.com/minio/minio/cmd/auth-handler.go:238 +0x169
github.com/minio/minio/cmd.(*authHandler).ServeHTTP(0xc4203b5720, 0xee8120, 0xc436f78270, 0xc42d871c20)
    <autogenerated>:70 +0x79
net/http.serverHandler.ServeHTTP(0xc4203448f0, 0xee8120, 0xc436f78270, 0xc42d871c20)
    /home/ec2-user/bin/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc42d762180, 0xee8b60, 0xc42d85ab80)
    /home/ec2-user/bin/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /home/ec2-user/bin/go/src/net/http/server.go:2293 +0x44d
2016/10/17 20:35:09 http: TLS handshake error from 93.170.187.41:50401: tls: oversized record received with length 19264
```

```
2016/10/17 22:40:52 http: TLS handshake error from 93.170.187.41:58218: tls: first record does not look like a TLS handshake
2016/10/17 22:40:53 http: panic serving 93.170.187.41:58729: runtime error: slice bounds out of range
goroutine 84692785 [running]:
net/http.(*conn).serve.func1(0xc73a278280)
    /home/ec2-user/bin/go/src/net/http/server.go:1491 +0x12a
panic(0xab3820, 0xc4200120f0)
    /home/ec2-user/bin/go/src/runtime/panic.go:458 +0x243
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0xee3fa0, 0xc4203b59a0, 0xee8120, 0xc6a61d0820, 0xc44d0254a0)
    /home/ec2-user/go/src/github.com/minio/minio/cmd/generic-handlers.go:242 +0x305
github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP(0xc4203b7bb0, 0xee8120, 0xc6a61d0820, 0xc44d0254a0)
    <autogenerated>:170 +0x79
github.com/minio/minio/cmd.authHandler.ServeHTTP(0xee39e0, 0xc4203b7bb0, 0xee8120, 0xc6a61d0820, 0xc44d0254a0)
    /home/ec2-user/go/src/github.com/minio/minio/cmd/auth-handler.go:238 +0x169
github.com/minio/minio/cmd.(*authHandler).ServeHTTP(0xc4203b7bc0, 0xee8120, 0xc6a61d0820, 0xc44d0254a0)
    <autogenerated>:70 +0x79
net/http.serverHandler.ServeHTTP(0xc420342a50, 0xee8120, 0xc6a61d0820, 0xc44d0254a0)
    /home/ec2-user/bin/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc73a278280, 0xee8b60, 0xc44cfeb780)
    /home/ec2-user/bin/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /home/ec2-user/bin/go/src/net/http/server.go:2293 +0x44d
2016/10/17 22:40:53 http: TLS handshake error from 93.170.187.41:58755: tls: oversized record received with length 19264
```

```
2016/10/17 23:39:06 http: TLS handshake error from 93.170.187.41:54612: tls: first record does not look like a TLS handshake
2016/10/17 23:39:06 http: panic serving 93.170.187.41:55142: runtime error: slice bounds out of range
goroutine 102215059 [running]:
net/http.(*conn).serve.func1(0xc5742d6900)
    /home/ec2-user/bin/go/src/net/http/server.go:1491 +0x12a
panic(0xab61a0, 0xc4200120f0)
    /home/ec2-user/bin/go/src/runtime/panic.go:458 +0x243
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0xee9020, 0xc420387ec0, 0xeed1a0, 0xc7a6192000, 0xc63cebf770)
    /home/ec2-user/go/src/github.com/minio/minio/cmd/generic-handlers.go:235 +0x305
github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP(0xc420397820, 0xeed1a0, 0xc7a6192000, 0xc63cebf770)
    <autogenerated>:170 +0x79
github.com/minio/minio/cmd.authHandler.ServeHTTP(0xee8a20, 0xc420397820, 0xeed1a0, 0xc7a6192000, 0xc63cebf770)
    /home/ec2-user/go/src/github.com/minio/minio/cmd/auth-handler.go:238 +0x169
github.com/minio/minio/cmd.(*authHandler).ServeHTTP(0xc420397830, 0xeed1a0, 0xc7a6192000, 0xc63cebf770)
    <autogenerated>:71 +0x79
net/http.serverHandler.ServeHTTP(0xc4203aa580, 0xeed1a0, 0xc7a6192000, 0xc63cebf770)
    /home/ec2-user/bin/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc5742d6900, 0xeedbe0, 0xc810147540)
    /home/ec2-user/bin/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
    /home/ec2-user/bin/go/src/net/http/server.go:2293 +0x44d
2016/10/17 23:39:07 http: TLS handshake error from 93.170.187.41:55168: tls: oversized record received with length 19264
```

**Comment by vadmeste** [comment]
@fwessels, so to confirm, you did enable tls in minio server but you are getting this sporadic error ?

**Comment by vadmeste** [comment]
@fwessels, can you tell what is the current commit id of your repository /home/ec2-user/go/src/github.com/minio/minio/ ? stack trace line number points to a comment in the current master

**Comment by fwessels** [comment]
@vadmeste  this is the commit id: 6303f263308b3f1f9f47a4e23a34643d3faa0878

**Comment by fwessels** [comment]
@vadmeste but also commit id: 6199aa0707ee9ca0c8e781f1198ee6aa802c3abb is in use at some servers (not setup at same time)

Stack trace with `/home/ec2-user/go/src/github.com/minio/minio/cmd/generic-handlers.go:235` is related to commit id 6303f263308b3f1f9f47a4e23a34643d3faa0878
Stack trace with  `/home/ec2-user/go/src/github.com/minio/minio/cmd/generic-handlers.go:242` is related to commit id 6199aa0707ee9ca0c8e781f1198ee6aa802c3abb

**Comment by fwessels** [comment]
Just FYI: this was a test during which in total 12 million objects were uploaded to the 8 node cluster, so we have about 4 errors in 12 million operations.

**Comment by vadmeste** [comment]
> Just FYI: this was a test during which in total 12 million objects were uploaded to the 8 node cluster, so we have about 4 errors in 12 million operations.

Thanks! yeah.. looks like a golang bug, I will investigate more

**Comment by fwessels** [comment]
>  Thanks! yeah.. looks like a golang bug, I will investigate more

Great, I should be able to reproduce it although will take a couple of hours before any errors to show up

**Comment by vadmeste** [comment]
I tested with 5 millions requests (listing, to gain time) with FS backend and 10 millions requests with XL (8 nodes).. but I failed to reproduce this bug.

r.Path.URL shouldn't be empty, this is a golang bug.. also it seems that someone is tried to connect with the server (TLS handshake error from 93.170.187.41:54612: tls: first record does not look like a TLS handshake)

I think this is a low priority bug and could be moved to a later milestone (or closed)

**Comment by fwessels** [comment]
Let's see if it happens more often, I agree it is not a high priority bug

**Comment by fwessels** [comment]
After upgrading to golang 1.7.3 have not seen this happen anymore.
So I think we can close the issue.
