### ISSUE TITLE
api: CopyObject should support updating object metadata.

### ISSUE THREAD

**Issue by opendedup** [minio/minio#3316]
In order to update metadata from the AWS Java API you must use a copyobject call where the source and the destination object are the same but the metadata is different. This opperation fails with a " This copy request is illegal because it is trying to copy an object to itself" error when using minio
## Expected Behavior
Copy of an object over itself should not throw an exception. Especially if the metadata has changed.

## Current Behavior
Fails with 
2016-11-22 12:53:26,856 [sdfs] [org.opendedup.sdfs.filestore.cloud.BatchAwsS3ChunkStore$DeleteObject] [2509] [pool-10-thread-3]  - Unable to delete object -6061387925563889599
com.amazonaws.services.s3.model.AmazonS3Exception: This copy request is illegal because it is trying to copy an object to itself. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRequest; Request ID: 3L137), S3 Extended Request ID: 3L137
        at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1341)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:959)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:736)
        at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:487)
        at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:448)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:397)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:378)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4039)
        at com.amazonaws.services.s3.AmazonS3Client.copyObject(AmazonS3Client.java:1714)
        at org.opendedup.sdfs.filestore.cloud.BatchAwsS3ChunkStore$DeleteObject.run(BatchAwsS3ChunkStore.java:2506)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
## Possible Solution
remove 

// Source and destination objects cannot be same, reply back error.
	if sourceObject == object && sourceBucket == bucket {
		writeErrorResponse(w, r, ErrInvalidCopyDest, r.URL.Path)
		return
	}

from CopyObjectHandler

## Steps to Reproduce (for bugs)
1. create and object
2.update object metadata
3. copy opbject with new metadata over itself
4.

## Context
Unable to run Minio with OpenDedup as an object storage backend for backup

## Your Environment
OpenDedupe Target
On Ubuntu Linux
Minio 2016-11-22T00:35:30Z running in a docker container

**Comment by harshavardhana** [comment]
Currently this is expected @opendedup - we are discouraging using lot metadata on server side and any operations related to this. Metadata that gets saved is not queriable in any form and object storage is not the real place to store this information.  

A database should be used instead to store and query this information, but we will fix this lieu of S3 compatibility we strongly believe in minimizing the impact of metadata on the server side.

**Comment by opendedup** [comment]
I agree that there should not be a lot of metadata for objects but for
opendedupe some is required for encryption iv and counting object
references.

**Comment by harshavardhana** [comment]
> I agree that there should not be a lot of metadata for objects but for
> opendedupe some is required for encryption iv and counting object
> references.

We will work on addressing this thanks @opendedup

**Comment by badc0re** [comment]
Is this issue going to be fixed in the next version?

**Comment by harshavardhana** [comment]
We will fix it soon @badc0re

**Comment by harshavardhana** [comment]
This change requires an architecture change being able to mutate metadata without mutating the data, current code base doesn't allow that. 

We will discuss internally on the feasibility of such an approach and its underlying complications. For now its not possible.

**Comment by opendedup** [comment]
I ended up working around the issue by copying the object to a temp object
then deleting the origional and then coping the temp object back to the
origional name.

**Comment by harshavardhana** [comment]
@opendedup we fixed the CopyObject API to conform with S3 API.  Can you test master branch and let us know if you face further issues.. Please open a new github issue if you have issues.
