### ISSUE TITLE
Marker not common with prefix is not implemented

### ISSUE THREAD

**Issue by szepeviktor** [minio/minio#3364]
I've just ran into this.

https://github.com/minio/minio/blob/bef0a50bc1651960e3c83a173614ae8c84544fd1/cmd/bucket-handlers.go#L139
https://github.com/minio/minio/blob/bef0a50bc1651960e3c83a173614ae8c84544fd1/cmd/bucket-handlers-listobjects.go#L44

Are there plans to implement prefix?

I use s3ql with a prefix set.

**Comment by harshavardhana** [comment]
Can you paste the s3ql test script?

**Comment by szepeviktor** [comment]
~.s3ql/authinfo2
```
[minio]
storage-url: s3c://1.2.3.4:9000/bucket01/pref_
backend-login: Q19313GLKEBNS7D179D4
backend-password: aB4W0QnTrm/r/mHLspD48w8BVSO3QWhUkIK5SjPp
fs-passphrase: 111
```
fsck.s3ql runs ok with prefix
and `mount.s3ql --backend-options no-ssl s3c://1.2.3.4:9000/bucket01/pref_ /mnt`

```
Traceback (most recent call last):
  File "/usr/bin/mount.s3ql", line 11, in <module>
    load_entry_point('s3ql==2.21', 'console_scripts', 'mount.s3ql')()
  File "/usr/lib/s3ql/s3ql/mount.py", line 129, in main
    (param, db) = get_metadata(backend, cachepath)
  File "/usr/lib/s3ql/s3ql/mount.py", line 358, in get_metadata
    seq_no = get_seq_no(backend)
  File "/usr/lib/s3ql/s3ql/common.py", line 45, in get_seq_no
    seq_nos = list(backend.list('s3ql_seq_no_'))
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 108, in wrapped
    return method(*a, **kw)
  File "/usr/lib/s3ql/s3ql/backends/common.py", line 217, in __next__
    el = next(self.iterator)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 245, in list
    'max-keys': 1000 })
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 540, in _do_request
    self._parse_error_response(resp)
  File "/usr/lib/s3ql/s3ql/backends/s3c.py", line 574, in _parse_error_response
    raise get_S3Error(tree.findtext('Code'), tree.findtext('Message'), resp.headers)
s3ql.backends.s3c.S3Error: NotImplemented: A header you provided implies functionality that is not implemented
```

Later I've dumped the sent headers:
```
Authorization: AWS Q19313GLKEBNS7D179D4:PHf+ZTmdP9dBNeY5dRH8Vl1+hpQ=
Date: Tue, 29 Nov 2016 02:30:09 GMT
```

Latest minio on go 1.7.3 + S3QL 2.21

**Comment by harshavardhana** [comment]
There is a bug in how s3ql sends the marker - marker and prefix are interchanged.

**Comment by harshavardhana** [comment]
```2016-11-28 19:50:18.241 19887:MainThread s3ql.backends.s3c._send_request: sending GET /testbucket/?max-keys=1000&marker=prefix&prefix=prefixs3ql_seq_no_```

This is not needed.

**Comment by szepeviktor** [comment]
@Nikratio Could you help us?

**Comment by harshavardhana** [comment]
```
diff -r 04d24c44e4ed src/s3ql/backends/s3c.py
--- a/src/s3ql/backends/s3c.py	Wed Nov 23 17:09:06 2016 +0000
+++ b/src/s3ql/backends/s3c.py	Mon Nov 28 20:23:37 2016 -0800
@@ -230,7 +230,10 @@
         log.debug('started with %s, %s', prefix, start_after)
 
         keys_remaining = True
-        marker = self.prefix + start_after
+        marker = ''
+        if start_after:
+            marker = self.prefix + start_after
+
         prefix = self.prefix + prefix
 
         while keys_remaining:
```

**Comment by harshavardhana** [comment]
this might fix the problem @szepeviktor

**Comment by harshavardhana** [comment]
can you apply this patch locally and test it?

**Comment by szepeviktor** [comment]
Thank you!

`Mounting s3c://1.2.3.4:9000/bocket01/pref_ at /mnt...`

**Comment by szepeviktor** [comment]
https://bitbucket.org/nikratio/s3ql/issues/242/setting-marker-on-s3

Thank you again.
