### ISSUE TITLE
AWS SDK with running distributed

### ISSUE THREAD

**Issue by huytn** [minio/minio#3455]
I can not create Bucket by using AWS boto3 with distributed.

```
>>> import boto3
>>> from botocore.config import Config
>>> 
>>> s3 = boto3.resource('s3',
...                     endpoint_url='http://172.16.233.130:9000',
...                     aws_access_key_id='BKIKJAA5BMMU2RHO6IBB',
...                     aws_secret_access_key='V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12',
...                     config=Config(signature_version='s3v4'),
...                     region_name='us-east-1')
>>> s3.create_bucket(Bucket="huyntbk")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.ReadTimeout: HTTPConnectionPool(host='172.16.233.130', port=9000): Read timed out. (read timeout=60)
>>> s3lv = boto3.client('s3', region_name='us-east-1', use_ssl=False, endpoint_url='http://172.16.233.129:9000', aws_access_key_id='BKIKJAA5BMMU2RHO6IBB', aws_secret_access_key='V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12',config=Config(signature_version='s3v4'))
>>> s3lv.create_bucket(Bucket="huyntbk")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 251, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/client.py", line 526, in _make_api_call
    operation_model, request_dict)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 170, in _send_request
    success_response, exception):
  File "/Library/Python/2.7/site-packages/botocore/endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Library/Python/2.7/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Library/Python/2.7/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.ReadTimeout: HTTPConnectionPool(host='172.16.233.129', port=9000): Read timed out. (read timeout=60)
```
I can access on browser and I can use this api with running standalone.

**Comment by huytn** [comment]
I can also not create bucket from web browser

**Comment by koolhead17** [comment]
@huytn can you run make bucket operation using mc client with --debug flag, please run it from same machine you are accessing your minio configuration to create bucket via browser. 

```
mc mb --debug myminio/huyntbk 
```

**Comment by huytn** [comment]
No outputs in ten minutes
```
$ ./mc config host add myminio http://172.16.233.130:9000 BKIKJAA5BMMU2RHO6IBB V8f1CwQqAcwo80UEIJEjc5gVQUSSx5ohQ9GSrr12
mc: Configuration written to ‘/Users/huytn/.mc/config.json’. Please update your access credentials.
mc: Successfully created ‘/Users/huytn/.mc/share’.
mc: Initialized share uploads ‘/Users/huytn/.mc/share/uploads.json’ file.
mc: Initialized share downloads ‘/Users/huytn/.mc/share/downloads.json’ file.
Added ‘myminio’ successfully.
$ ./mc mb --debug myminio/huyntbk

```

**Comment by koolhead17** [comment]
@huytn I tried to replicate your setup with 4 node Minio distributed setup.

Please confirm if all the Minio nodes in your distributed setup are up and running. 

This is what my output shows.
```
 mc mb --debug localxl/mybucket2
mc: <DEBUG> PUT /mybucket2/ HTTP/1.1
Host: 192.168.1.107:9000
User-Agent: Minio (darwin; amd64) minio-go/2.0.2 mc/DEVELOPMENT.GOGET
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20161215/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20161215T110511Z
Accept-Encoding: gzip

mc: <DEBUG> Accept-Ranges: bytes
Content-Length: 0
Content-Type: text/plain; charset=utf-8
Date: Thu, 15 Dec 2016 11:04:07 GMT
Location: /mybucket2
Server: Minio/DEVELOPMENT.GOGET (linux; amd64)
Vary: Origin
X-Amz-Request-Id: XFC2N0ZRM40PVDQX

mc: <DEBUG> Response Time:  4.077377ms

Bucket created successfully ‘localxl/mybucket2’.
```

**Comment by harshavardhana** [comment]
Can you paste your minio version @huytn ?

**Comment by huytn** [comment]
@harshavardhana 
on servers
```
$ bin/minio version
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
```
on client
```
./mc version
Version: 2016-08-21T03:02:49Z
Release-tag: RELEASE.2016-08-21T03-02-49Z
Commit-id: 768be74f74578137951f65874cfc2e454b64aca0
```

@koolhead17,
I think all nodes are setup and running
![172 16 233 129](https://cloud.githubusercontent.com/assets/5128892/21255757/6e1f486a-c3a0-11e6-81b6-5727f16efe1d.png)
![172 16 233 130](https://cloud.githubusercontent.com/assets/5128892/21255758/6e78252a-c3a0-11e6-9319-2f8fe8660b5e.png)

**Comment by harshavardhana** [comment]
> $ bin/minio version
> Version: DEVELOPMENT.GOGET
> Release-Tag: DEVELOPMENT.GOGET
> Commit-ID: DEVELOPMENT.GOGET

what is the commit id from which this was built?  can you provide us `git rev-parse HEAD`

**Comment by huytn** [comment]
@harshavardhana 
I installed Minio from source code.

**Comment by harshavardhana** [comment]
> @harshavardhana
> I installed Minio from source code.

I see we fixed a bug similar to the one you reported - that is why wanted to know the exact commit that you built your binary from.

**Comment by huytn** [comment]
@harshavardhana 
on server 130
```
$git rev-parse HEAD
2d6f8153fabdb67c7823436593958ddd035dc08b
```
on server 129
```
$git rev-parse HEAD
8e665105b1c104c2aa0d129b9d876dd881e1b57a
```

**Comment by koolhead17** [comment]
@huytn can you please run latest and same version of Minio on both the nodes and let us know if the issue gets resolved.

**Comment by huytn** [comment]
@koolhead17 

I upgrade to latest version and the it works.

Thanks you.
