### ISSUE TITLE
slice bounds out of range error

### ISSUE THREAD

**Issue by TNTest** [minio/minio#3553]
Single server, same error as #2985 ,    golang is upgraded to 1.7.3. 
According to #2985 , upgrading go to 1.7.3 should fix it, but it is not.
This error will cause the minio server down, so considering as a low priority bug is a good idea?
```
2017/1/4 下午3:34:142017/01/04 07:34:14 http: TLS handshake error from 123.151.92.176:43822: tls: oversized record received with length 61393
2017/1/4 下午9:25:372017/01/04 13:25:37 http: TLS handshake error from 60.191.52.254:37517: tls: first record does not look like a TLS handshake
2017/1/6 下午10:31:352017/01/06 14:31:35 http: TLS handshake error from 183.136.190.22:42396: tls: first record does not look like a TLS handshake
2017/1/7 上午1:32:322017/01/06 17:32:32 http: TLS handshake error from 60.191.52.254:60855: tls: first record does not look like a TLS handshake
2017/1/7 上午2:59:042017/01/06 18:59:04 http: TLS handshake error from 183.136.190.22:17768: tls: first record does not look like a TLS handshake
2017/1/7 上午10:09:132017/01/07 02:09:13 http: TLS handshake error from 183.136.190.22:57911: tls: first record does not look like a TLS handshake
2017/1/9 下午4:46:072017/01/09 08:46:07 http: panic serving 121.42.171.160:49580: runtime error: slice bounds out of range
2017/1/9 下午4:46:07goroutine 3447 [running]:
2017/1/9 下午4:46:07net/http.(*conn).serve.func1(0xc42000e200)
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:1491 +0x12a
2017/1/9 下午4:46:07panic(0xa28de0, 0xc4200140b0)
2017/1/9 下午4:46:07	/usr/local/go/src/runtime/panic.go:458 +0x243
2017/1/9 下午4:46:07github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0xe0bd20, 0xc420433a60, 0xe0f6a0, 0xc4200ee000, 0xc4200e41e0)
2017/1/9 下午4:46:07	/go/src/github.com/minio/minio/cmd/generic-handlers.go:238 +0x305
2017/1/9 下午4:46:07github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP(0xc420446650, 0xe0f6a0, 0xc4200ee000, 0xc4200e41e0)
2017/1/9 下午4:46:07	<autogenerated>:150 +0x79
2017/1/9 下午4:46:07github.com/minio/minio/cmd.authHandler.ServeHTTP(0xe0b760, 0xc420446650, 0xe0f6a0, 0xc4200ee000, 0xc4200e41e0)
2017/1/9 下午4:46:07	/go/src/github.com/minio/minio/cmd/auth-handler.go:222 +0x169
2017/1/9 下午4:46:07github.com/minio/minio/cmd.(*authHandler).ServeHTTP(0xc420446660, 0xe0f6a0, 0xc4200ee000, 0xc4200e41e0)
2017/1/9 下午4:46:07	<autogenerated>:63 +0x79
2017/1/9 下午4:46:07net/http.serverHandler.ServeHTTP(0xc420113ad0, 0xe0f6a0, 0xc4200ee000, 0xc4200e41e0)
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:2202 +0x7d
2017/1/9 下午4:46:07net/http.(*conn).serve(0xc42000e200, 0xe100e0, 0xc4203da140)
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:1579 +0x4b7
2017/1/9 下午4:46:07created by net/http.(*Server).Serve
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:2293 +0x44d
2017/1/9 下午4:46:072017/01/09 08:46:07 http: panic serving 121.42.171.160:49582: runtime error: slice bounds out of range
2017/1/9 下午4:46:07goroutine 3448 [running]:
2017/1/9 下午4:46:07net/http.(*conn).serve.func1(0xc42000e400)
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:1491 +0x12a
2017/1/9 下午4:46:07panic(0xa28de0, 0xc4200140b0)
2017/1/9 下午4:46:07	/usr/local/go/src/runtime/panic.go:458 +0x243
2017/1/9 下午4:46:07github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0xe0bd20, 0xc420433a60, 0xe0f6a0, 0xc4200ee1a0, 0xc4200e42d0)
2017/1/9 下午4:46:07	/go/src/github.com/minio/minio/cmd/generic-handlers.go:238 +0x305
2017/1/9 下午4:46:07github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP(0xc420446650, 0xe0f6a0, 0xc4200ee1a0, 0xc4200e42d0)
2017/1/9 下午4:46:07	<autogenerated>:150 +0x79
2017/1/9 下午4:46:07github.com/minio/minio/cmd.authHandler.ServeHTTP(0xe0b760, 0xc420446650, 0xe0f6a0, 0xc4200ee1a0, 0xc4200e42d0)
2017/1/9 下午4:46:07	/go/src/github.com/minio/minio/cmd/auth-handler.go:222 +0x169
2017/1/9 下午4:46:07github.com/minio/minio/cmd.(*authHandler).ServeHTTP(0xc420446660, 0xe0f6a0, 0xc4200ee1a0, 0xc4200e42d0)
2017/1/9 下午4:46:07	<autogenerated>:63 +0x79
2017/1/9 下午4:46:07net/http.serverHandler.ServeHTTP(0xc420113ad0, 0xe0f6a0, 0xc4200ee1a0, 0xc4200e42d0)
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:2202 +0x7d
2017/1/9 下午4:46:07net/http.(*conn).serve(0xc42000e400, 0xe100e0, 0xc4203da400)
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:1579 +0x4b7
2017/1/9 下午4:46:07created by net/http.(*Server).Serve
2017/1/9 下午4:46:07	/usr/local/go/src/net/http/server.go:2293 +0x44d
```

## Your Environment

* Version used: 2016-10-24T21:23:47Z | go1.7.3
* Environment name and version: minio official docker image

**Comment by harshavardhana** [comment]
We have made few more releases after this can you upgrade and validate ?

**Comment by harshavardhana** [comment]
The panic happens because of this 

```
   // Skip the first element which is usually '/' and split the rest.                                                                       
	 splits := strings.SplitN(r.URL.Path[1:], "/", 2)
```
Looks like `r.URL.Path` is empty for some reason due to a bug in Go, we can fix this by avoiding this situation ourselves. 

Do you have a consistent way to reproduce this issue @TNTest ?

**Comment by TNTest** [comment]
@harshavardhana  We failed to find out consistent reproducing steps, sorry.  2 months works fine until today. In my opinion,  empty check before slice operation is much stronger here.  Since this panic will cause the server down.

**Comment by balamurugana** [comment]
> Looks like r.URL.Path is empty for some reason due to a bug in Go, we can fix this by avoiding this situation ourselves.


Its not a Go bug.

```
 A URL represents a parsed URL (technically, a URI reference). The general form represented is:

scheme://[userinfo@]host/path[?query][#fragment]

URLs that do not start with a slash after the scheme are interpreted as:

scheme:opaque[?query][#fragment]

Note that the Path field is stored in decoded form: /%47%6f%2f becomes /Go/. A consequence is that it is impossible to tell which slashes in the Path were slashes in the raw URL and which were %2f. This distinction is rarely important, but when it is, code must not use Path directly.

Go 1.5 introduced the RawPath field to hold the encoded form of Path. The Parse function sets both Path and RawPath in the URL it returns, and URL's String method uses RawPath if it is a valid encoding of Path, by calling the EscapedPath method.

In earlier versions of Go, the more indirect workarounds were that an HTTP server could consult req.RequestURI and an HTTP client could construct a URL struct directly and set the Opaque field instead of Path. These still work as well. 
```

It looks like `scheme:opaque[?query][#fragment]` is passed/parsed.

example: For `c:hello` here path is empty but opaque is `hello`

**Comment by harshavardhana** [comment]
> Its not a Go bug.

This is an incorrect analogy, `r.URL.Path` is never empty or should never be empty coming from Go http server passed through the handlers - it is empty for odd reasons we don't know and it only started happening since go1.6.x or go.1.7 days.

**Comment by harshavardhana** [comment]
> This is an incorrect analogy, r.URL.Path is never empty or should never be empty coming from Go http server passed through the handlers - it is empty for odd reasons we don't know and it only started happening since go1.6.x or go.1.7 days.

But we should handle it ourselves nevertheless.
