### ISSUE TITLE
Browser: cannot change TCP port

### ISSUE THREAD

**Issue by edsiper** [minio/minio#3674]
I am trying to make the minio browser run in a different port than 8080, it was suggested to modify the configuration file __webpack.config.js__ but the changes not take effect.

## Expected Behavior

Run the browser in a different TCP port

## Current Behavior

Cannot start minio as it wants to use 8080 which is already binded by a different service:

```
$ yarn dev
yarn dev v0.19.1
$ NODE_ENV=dev webpack-dev-server --devtool eval --progress --colors --hot --content-base dev 
 70% 1/1 build modules[HPM] Proxy created: /minio/webrpc  ->  http://localhost:19000
[HPM] Proxy created: /minio/upload  ->  http://localhost:19000
[HPM] Proxy created: /minio/download  ->  http://localhost:19000
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at net.js:1405:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
error Command failed with exit code 1.
[@monotop:~/coding/minio/browser GIT(master) 1]
$ cat webpack.config.js | grep 8080
```
## Your Environment

- Ubuntu 16.10

**Comment by vadmeste** [comment]
> Error: listen EADDRINUSE 127.0.0.1:8080

It seems you have another instance/program listening to port 8080, can you manage to kill it and test again ?

**Comment by edsiper** [comment]
I cannot kill my local 8080 service, I am using it. 

My goal is to use minio browser in a different TCP port.

**Comment by harshavardhana** [comment]
> My goal is to use minio browser in a different TCP port.

Here is how you can do it

```diff
$ git diff
diff --git a/browser/webpack.config.js b/browser/webpack.config.js
index 3ccdaba..fc1d215 100644
--- a/browser/webpack.config.js
+++ b/browser/webpack.config.js
@@ -58,6 +58,7 @@ var exports = {
     historyApiFallback: {
       index: '/minio/'
     },
+    port: 8888,
     proxy: {
       '/minio/webrpc': {
        target: 'http://localhost:9000',
```

**Comment by edsiper** [comment]
thanks, that worked!

Please document that somewhere.
