### ISSUE TITLE
Unable to upload empty files to Minio. (unexpected EOF / #has incomplete body)

### ISSUE THREAD

**Issue by chrisgavin** [minio/minio#3691]
I seem to be unable to upload empty files to a Minio server running the latest master. This occurs using the official S3 Java library, but not the command line client.

## Expected Behavior
It should be possible to upload empty files from the official Java library.

## Current Behavior
In the Java client this exception is thrown:

```
com.amazonaws.services.s3.model.AmazonS3Exception: You did not provide the number of bytes specified by the Content-Length HTTP header. (Service: Amazon S3; Status Code: 400; Error Code: IncompleteBody; Request ID: 3L137), S3 Extended Request ID: 3L137
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1545)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1183)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:964)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:676)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:650)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:633)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$300(AmazonHttpClient.java:601)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:583)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:447)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4031)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1585)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1443)
```

The Minio log shows these errors:
```
ERRO[0325] Failed to create object bucket/empty            cause=unexpected EOF source=[fs-v1.go:621:fsObjects.PutObject()] stack=fs-v1-helpers.go:263:fsCreateFile fs-v1.go:618:fsObjects.PutObject <autogenerated>:266:(*fsObjects).PutObject object-handlers.go:457:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
ERRO[0325] Unable to create an object.                   cause=#has incomplete body source=[object-handlers.go:479:objectAPIHandlers.PutObjectHandler()] stack=fs-v1-helpers.go:263:fsCreateFile fs-v1.go:618:fsObjects.PutObject <autogenerated>:266:(*fsObjects).PutObject object-handlers.go:457:objectAPIHandlers.PutObjectHandler api-router.go:60:(objectAPIHandlers).PutObjectHandler-fm
```

## Steps to Reproduce (for bugs)
1. `touch /tmp/empty`
2.
```
AmazonS3Client client = new AmazonS3Client(credentials, new ClientConfiguration());
client.setS3ClientOptions(S3ClientOptions.builder().setPathStyleAccess(true).build());
client.setEndpoint("http://minio-server:9000");
client.putObject("bucket", "empty", new File("/tmp/empty"));
```

## Your Environment

* Version used: 6717a0b
* Operating System and version: Ubuntu 16.04

Thanks for this awesome project. It's great.

**Comment by vadmeste** [comment]
Taking this.
