### ISSUE TITLE
httpResponseRecorder missing Hijack interface leads to crash.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3708]
```
minio2_1  | goroutine 304 [running]:
minio2_1  | net/http.(*conn).serve.func1(0xc4204cc980)
minio2_1  | 	/usr/local/go/src/net/http/server.go:1491 +0x12a
minio2_1  | panic(0xba08e0, 0xc4203b9400)
minio2_1  | 	/usr/local/go/src/runtime/panic.go:458 +0x243
minio2_1  | net/rpc.(*Server).ServeHTTP(0xc4204524c0, 0x106d8a0, 0xc420312420, 0xc42046f1d0)
minio2_1  | 	/usr/local/go/src/net/rpc/server.go:690 +0x1ac
minio2_1  | github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4203bc730, 0x106d8a0, 0xc420312420, 0xc42046f1d0)
minio2_1  | 	/go/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0x10d
minio2_1  | github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x10667e0, 0xc4203bc730, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/generic-handlers.go:403 +0xac
minio2_1  | github.com/minio/minio/cmd.(*httpStatsHandler).ServeHTTP(0xc420469080, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:290 +0x79
minio2_1  | github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1069160, 0xc420469080, 0x144000000, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/generic-handlers.go:64 +0x100
minio2_1  | github.com/minio/minio/cmd.(*requestSizeLimitHandler).ServeHTTP(0xc4204c1fc0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:282 +0x82
minio2_1  | github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1069260, 0xc4204c1fc0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x65
minio2_1  | github.com/minio/minio/cmd.(*crossDomainPolicy).ServeHTTP(0xc4204690a0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:217 +0x79
minio2_1  | github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x10690e0, 0xc4204690a0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/generic-handlers.go:129 +0xc0
minio2_1  | github.com/minio/minio/cmd.(*redirectHandler).ServeHTTP(0xc4204690b0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:283 +0x79
minio2_1  | github.com/minio/minio/cmd.minioPrivateBucketHandler.ServeHTTP(0x1069220, 0xc4204690b0, 0xc7ed84, 0x6, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/generic-handlers.go:175 +0x6a
minio2_1  | github.com/minio/minio/cmd.(*minioPrivateBucketHandler).ServeHTTP(0xc4204c1fe0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:285 +0x8b
minio2_1  | github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x10691e0, 0xc4204c1fe0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/generic-handlers.go:156 +0x60
minio2_1  | github.com/minio/minio/cmd.(*cacheControlHandler).ServeHTTP(0xc4204690c0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:284 +0x79
minio2_1  | github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x10690a0, 0xc4204690c0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/generic-handlers.go:245 +0x1eb
minio2_1  | github.com/minio/minio/cmd.(*timeValidityHandler).ServeHTTP(0xc4204690d0, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:286 +0x79
minio2_1  | github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190 +0xe9
minio2_1  | net/http.HandlerFunc.ServeHTTP(0xc4204b2060, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/usr/local/go/src/net/http/server.go:1726 +0x44
minio2_1  | github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x10699a0, 0xc4204b2060, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/generic-handlers.go:357 +0xa2
minio2_1  | github.com/minio/minio/cmd.(*resourceHandler).ServeHTTP(0xc420469150, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:287 +0x79
minio2_1  | github.com/minio/minio/cmd.authHandler.ServeHTTP(0x10692a0, 0xc420469150, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/auth-handler.go:224 +0x157
minio2_1  | github.com/minio/minio/cmd.(*authHandler).ServeHTTP(0xc420469160, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	<autogenerated>:144 +0x79
minio2_1  | github.com/minio/minio/cmd.(*ServerMux).ListenAndServe.func1(0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/go/src/github.com/minio/minio/cmd/server-mux.go:458 +0xac
minio2_1  | net/http.HandlerFunc.ServeHTTP(0xc42046a020, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/usr/local/go/src/net/http/server.go:1726 +0x44
minio2_1  | net/http.serverHandler.ServeHTTP(0xc4204cc000, 0x106e960, 0xc420101110, 0xc42046eff0)
minio2_1  | 	/usr/local/go/src/net/http/server.go:2202 +0x7d
minio2_1  | net/http.(*conn).serve(0xc4204cc980, 0x106f520, 0xc4203b9300)
minio2_1  | 	/usr/local/go/src/net/http/server.go:1579 +0x4b7
minio2_1  | created by net/http.(*Server).Serve
minio2_1  | 	/usr/local/go/src/net/http/server.go:2293 +0x44d
minio3_1  | 2017/02/07 07:13:26 http: panic serving 172.18.0.3:47186: interface conversion: *cmd.httpResponseRecorder is not http.Hijacker: missing method Hijack
``` 

## Expected Behavior
Hijack method should be overloaded.

## Current Behavior
Crashes the server.

## Possible Solution
Add a Hijack method.

## Steps to Reproduce (for bugs)
Just start distributed server from master.

**Comment by vadmeste** [comment]
I wonder why we haven't seen this before.

**Comment by harshavardhana** [comment]
You didn't use distributed setup. @vadmeste when we wrap we need to pass the right interfaces. Go http library doesn't expect users to wrap http.ResponseWriter 

Hijack is used by RPC calls only.

**Comment by vadmeste** [comment]
> You didn't use distributed setup. @vadmeste when we wrap we need to pass the right interfaces. Go http library doesn't expect users to wrap http.ResponseWriter
> 
> Hijack is used by RPC calls only.

:+1:
