### ISSUE TITLE
postPolicyBucketHandler crashed invalid memory

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#3752]
```
2017/02/11 23:48:04 http: panic serving 73.15.184.243:55430: runtime error: invalid memory address or nil pointer dereference
goroutine 101795 [running]:
net/http.(*conn).serve.func1(0xc420133100)
        /home/ubuntu/.gimme/versions/go1.7.4.linux.amd64/src/net/http/server.go:1491 +0x12a
panic(0xb9bca0, 0xc4200140f0)
        /home/ubuntu/.gimme/versions/go1.7.4.linux.amd64/src/runtime/panic.go:458 +0x243
github.com/minio/minio/cmd.objectAPIHandlers.PostPolicyBucketHandler(0xcf6938, 0x10738e0, 0xc425460ea0, 0xc425614870)
        /home/ubuntu/mygo/src/github.com/minio/minio/cmd/bucket-handlers.go:432 +0x2d5
github.com/minio/minio/cmd.(objectAPIHandlers).PostPolicyBucketHandler-fm(0x10738e0, 0xc425460ea0, 0xc425614870)
        /home/ubuntu/mygo/src/github.com/minio/minio/cmd/api-router.go:89 +0x4e
net/http.HandlerFunc.ServeHTTP(0xc42052f7f0, 0x10738e0, 0xc425460ea0, 0xc425614870)
        /home/ubuntu/.gimme/versions/go1.7.4.linux.amd64/src/net/http/server.go:1726 +0x44
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc42033c230, 0x10738e0, 0xc425460ea0, 0xc425614870)
        /home/ubuntu/mygo/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0x10d
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x106c820, 0xc42033c230, 0x10749a0, 0xc420543ba0, 0xc425614690)
        /home/ubuntu/mygo/src/github.com/minio/minio/cmd/generic-handlers.go:405 +0x9c
github.com/minio/minio/cmd.(*httpStatsHandler).ServeHTTP(0xc42052fa50, 0x10749a0, 0xc420543ba0, 0xc425614690)
        <autogenerated>:290 +0x79
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x106f1a0, 0xc42052fa50, 0x144000000, 0x10749a0, 0xc420543ba0, 0xc425614690)
        /home/ubuntu/mygo/src/github.com/minio/minio/cmd/generic-handlers.go:66 +0x100
github.com/minio/minio/cmd.(*requestSizeLimitHandler).ServeHTTP(0xc42028e8c0, 0x10749a0, 0xc420543ba0, 0xc425614690)
        <autogenerated>:282 +0x82
```

## Expected Behavior
Shouldn't crash.

## Current Behavior
Crashes consistently. 

## Possible Solution
Nothing right now. 

## Steps to Reproduce (for bugs)
Just use POST policy.

## Context
Uploading through signed POST policy.

## Your Environment
Current master.

**Comment by harshavardhana** [comment]
Fixed by this commit c9b1468c3bf41630fbb1647b782d46257eb7ce1c

```
commit c9b1468c3bf41630fbb1647b782d46257eb7ce1c
Author: Anis Elleuch <vadmeste@gmail.com>
Date:   Thu Feb 9 21:37:32 2017 +0100

    Presigend Post: Error out when File is not found (#3723)
    
    Follow S3 behavior when no File is sent in the presigned
    post request form.
```
