### ISSUE TITLE
gateway: [s3] aws cli fails to listing objects

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4129]
## Expected Behavior

```
aws s3 --endpoint-url https://play.minio.io:9000/ ls s3://testbucket
                           PRE accounts/
                           PRE documents/
                           PRE resumes/
```

## Current Behavior
```
aws s3 --endpoint-url http://localhost:9000/ ls s3://testbucket

list index out of range
```

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
Configure `aws cli` using `aws configure` . 
```
$ cat ~/.aws/config
[default]
region = us-east-1
s3 =
    signature_version = s3v4
```

```
$ cat ~/.aws/credentials
[default]
# Play creds
aws_access_key_id = Q3AM3UQ867SPQQA43P2F
aws_secret_access_key = zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
```

## Context
S3 compatibility errors.

## Your Environment
Download binary: http://minio-download.s3.amazonaws.com/minio and use the latest `aws cli`

**Comment by harshavardhana** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>testbucket</Name><Prefix></Prefix><Marker></Marker><NextMarker>resumes/</NextMarker><MaxKeys>1000</MaxKeys><Delimiter>/</Delimiter><IsTruncated>false</IsTruncated><CommonPrefixes><Prefix></Prefix></CommonPrefixes></ListBucketResult>
2017-04-14 16:30:49,602 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjects: calling handler <botocore.retryhandler.RetryHandler object at 0x7f22406e5590>
2017-04-14 16:30:49,602 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2017-04-14 16:30:49,602 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListObjects: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x7f224069e690>>
2017-04-14 16:30:49,602 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function decode_list_object at 0x7f224174ced8>
2017-04-14 16:30:49,602 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListObjects: calling handler <function enhance_error_msg at 0x7f2240cd1c08>
2017-04-14 16:30:49,602 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/awscli/clidriver.py", line 186, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3/subcommands.py", line 473, in _run_main
    bucket, key, parsed_args.page_size, parsed_args.request_payer)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3/subcommands.py", line 501, in _list_all_objects
    self._display_page(response_data)
  File "/usr/local/lib/python2.7/dist-packages/awscli/customizations/s3/subcommands.py", line 511, in _display_page
    prefix = prefix_components[-2]
IndexError: list index out of range
```

**Comment by harshavardhana** [comment]
Fixed in latest update to gateway.
