### ISSUE TITLE
[gateway] Crash if no arguments are provided

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#4314]
## Expected Behavior
Using default parameters when no argument is provided when running Gateway s3 and Azure

## Current Behavior
Crash:
```
$ MINIO_ACCESS_KEY="minio" MINIO_SECRET_KEY="minio123" minio gateway s3
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0xe2c920, 0xc420016150)
	/home/vadmeste/work/go/src/runtime/panic.go:500 +0x1a1
github.com/minio/minio/cmd.newS3Gateway(0xc42000c350, 0x0, 0x0, 0x2, 0xc420179b60, 0x1, 0xf86c5a)
	/home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/gateway-s3.go:104 +0x3e0
github.com/minio/minio/cmd.newGatewayLayer(0x7fffec26af5d, 0x2, 0xc42000c350, 0x0, 0x0, 0x0, 0x0, 0x0, 0x5)
	/home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/gateway-main.go:122 +0x8a
github.com/minio/minio/cmd.gatewayMain(0xc4202ec160)
	/home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/gateway-main.go:206 +0x1fb
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xdcd8c0, 0x10004f8, 0xc4202ec160, 0xc420183200, 0x0)
	/home/vadmeste/work/gospace/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xf6190d, 0x7, 0x0, 0x0, 0x0, 0x0, 0x0, 0xf7b0d4, 0x1d, 0x0, ...)
	/home/vadmeste/work/gospace/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xb9a
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc4202b2680, 0xc42000c330, 0x3, 0x3, 0x0, 0x0)
	/home/vadmeste/work/gospace/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x816
github.com/minio/minio/cmd.Main(0xc42000c330, 0x3, 0x3)
	/home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/main.go:143 +0x4d
main.main()
	/home/vadmeste/work/gospace/src/github.com/minio/minio/main.go:68 +0x7b
```

## Possible Solution
Small fix in the code

## Steps to Reproduce (for bugs)
1. `MINIO_ACCESS_KEY="access" MINIO_SECRET_KEY="secret" minio gateway s3`

## Your Environment
Detected in gcs-feature branch
All environments

**Comment by vadmeste** [comment]
Taking this
