### ISSUE TITLE
[gateway-gcs] RemoveIncompleteUpload doesn't delete the uploaded parts.

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4322]
## Expected Behavior
Able to delete the bucket at the end of java functional tests.

## Current Behavior
```
$ ./gradlew -PendPoint=http://localhost:9000 -PaccessKey=minio -PsecretKey=minio123 runFunctionalTest
:api:compileJava UP-TO-DATE
:api:processResources UP-TO-DATE
:api:classes UP-TO-DATE
:api:jar UP-TO-DATE
:functional:compileJava
:functional:processResources UP-TO-DATE
:functional:classes
:functional:runFunctionalTest
Test: makeBucket(String bucketName)
Test: listBuckets()
Test: bucketExists(String bucketName)
Test: removeBucket(String bucketName)
Test: putObject(String bucketName, String objectName, String filename)
Test: statObject(String bucketName, String objectName)
Test: getObject(String bucketName, String objectName)
Test: listObjects(final String bucketName)
Test: removeObject(String bucketName, String objectName)
Test: listIncompleteUploads(String bucketName)
Test: removeIncompleteUpload(String bucketName, String objectName)
Test: presignedGetObject(String bucketName, String objectName)
Test: presignedPutObject(String bucketName, String objectName)
Test: presignedPostPolicy(PostPolicy policy)
Test: copyObject(String bucketName, String objectName, String destBucketName)
error occured
ErrorResponse(code=BucketNotEmpty, message=The bucket you tried to delete is not empty, bucketName=null, objectName=null, resource=/minio-java-test-2gnag9i, requestId=3L137, hostId=3L137)
request={method=DELETE, url=http://localhost:9000/minio-java-test-2gnag9i, headers=Host: localhost:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20170511T075137Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170511/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=409, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-05-11T06-52-24Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14BD7DEA93BD4847
Date: Thu, 11 May 2017 07:51:37 GMT
Transfer-Encoding: chunked
OkHttp-Sent-Millis: 1494489097349
OkHttp-Received-Millis: 1494489097811
}

        at io.minio.MinioClient.execute(MinioClient.java:1028)
        at io.minio.MinioClient.executeDelete(MinioClient.java:1154)
        at io.minio.MinioClient.removeBucket(MinioClient.java:2625)
        at FunctionalTest.teardown(FunctionalTest.java:165)
        at FunctionalTest.runFastTests(FunctionalTest.java:1408)
        at FunctionalTest.main(FunctionalTest.java:1434)
:functional:runFunctionalTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':functional:runFunctionalTest'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 7.604 secs
```

```
$ mc ls -r mygcs/minio-java-test-2gnag9i 
[2017-05-11 00:51:01 PDT]     0B ZZZZ-Minio/multipart-minio-java-test-17vnaqm-2a1f7966-7ddc-4910-b26d-3fb55f6586ea-00000
[2017-05-11 00:51:06 PDT] 5.0MiB ZZZZ-Minio/multipart-minio-java-test-17vnaqm-2a1f7966-7ddc-4910-b26d-3fb55f6586ea-00001
[2017-05-11 00:51:07 PDT]     0B ZZZZ-Minio/multipart-minio-java-test-34ujc29-2a4a8a14-91c7-4992-be6e-bf9ef3304112-00000
[2017-05-11 00:51:13 PDT] 5.0MiB ZZZZ-Minio/multipart-minio-java-test-34ujc29-2a4a8a14-91c7-4992-be6e-bf9ef3304112-00001
```

There are left over files.

## Possible Solution
Not sure.

## Steps to Reproduce (for bugs)
Just run `java functional` tests pointing to the GCS gateway server.

## Context
GCS testing.

## Your Environment
```
Version: 2017-05-11T06:52:24Z
Release-Tag: DEVELOPMENT.2017-05-11T06-52-24Z
Commit-ID: 8dcd491ff6255ebaf276dd412114b2e4ddc7af77
```

**Comment by harshavardhana** [comment]
To run faster tests in minio-java functional tests, with following code modifications.

```diff
diff --git a/functional/FunctionalTest.java b/functional/FunctionalTest.java
index 988a4a5..e432c1d 100644
--- a/functional/FunctionalTest.java
+++ b/functional/FunctionalTest.java
@@ -1049,7 +1049,7 @@ public class FunctionalTest {
     String filename = createFile(3 * MB);
     client.putObject(bucketName, filename, filename);
     Files.delete(Paths.get(filename));
-    
+
     String destBucketName = getRandomName();
     client.makeBucket(destBucketName);
 
@@ -1427,10 +1427,10 @@ public class FunctionalTest {
       client = new MinioClient(endpoint, accessKey, secretKey);
       // Enable trace for debugging.
       // client.traceOn(System.out);
-      FunctionalTest.runTests();
+      // FunctionalTest.runTests();
 
       // Run fast test with region parameter passed to the constructor
-      client = new MinioClient(endpoint, accessKey, secretKey, region);
+      //      client = new MinioClient(endpoint, accessKey, secretKey, region);
       FunctionalTest.runFastTests();
 
     } catch (Exception e) {
```

```
$ git clone https://github.com/minio/minio-java
... apply the diff now..... 
$ ./gradlew -PendPoint=http://localhost:9000 -PaccessKey=minio -PsecretKey=minio123 runFunctionalTest
```

**Comment by nl5887** [comment]
@vadmeste fixed this already

**Comment by vadmeste** [comment]
Currently, I wasn't able to test this because it seems that listing uploads is not working properly. The following code taken from examples of `minio-go` lists all the incomplete uploads.


```
package main

import (
	"fmt"
	"log"

	"github.com/minio/minio-go"
)

func main() {
	s3Client, err := minio.New("localhost:9000", "YOUR-ACCESSKEYID", "YOUR-SECRETACCESSKEY", true)
	if err != nil {
		log.Fatalln(err)
	}

	doneCh := make(chan struct{})
	defer close(doneCh)

	for multipartObject := range s3Client.ListIncompleteUploads("vadmestetest", "", true, doneCh) {
		if multipartObject.Err != nil {
			fmt.Println(multipartObject.Err)
			return
		}
		fmt.Println(multipartObject)
	}
	return
}
```

**Comment by vadmeste** [comment]
This is fixed now and can be closed.

**Comment by harshavardhana** [comment]
Fixed in feature-gcs branch.
