### ISSUE TITLE
Minio-Java test fail on GCS branch

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4432]
## Expected Behavior
Java Functional Tests should pass

## Current Behavior
Test `removeObject_test2` failed with 

```
ErrorResponse(code=MissingContentMD5, message=Missing required header for this request: Content-Md5., bucketName=null, objectName=null, resource=/minio-java-test-2dn01b8, requestId=3L137, hostId=3L137)
request={method=POST, url=http://127.0.0.1:9000/minio-java-test-2dn01b8?delete=, headers=Host: 127.0.0.1:9000
User-Agent: Minio (x86_64; x86_64) minio-java/dev
x-amz-content-sha256: c69ea726b2b37c2882d287f987e5cab5735e786dc6a6c14498002b1b0bc0a138
x-amz-date: 20170525T162201Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170525/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=400, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-05-17T16-47-28Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14C1E5E473110D77
Date: Thu, 25 May 2017 16:22:00 GMT
Transfer-Encoding: chunked
}

        at io.minio.MinioClient.execute(MinioClient.java:1104)
        at io.minio.MinioClient.executePost(MinioClient.java:1251)
        at io.minio.MinioClient.removeObject(MinioClient.java:2180)
        at io.minio.MinioClient.access$000(MinioClient.java:158)
        at io.minio.MinioClient$4$1.populate(MinioClient.java:2258)
        at io.minio.MinioClient$4$1.hasNext(MinioClient.java:2279)
        at FunctionalTest.removeObject_test2(FunctionalTest.java:724)
        at FunctionalTest.runTests(FunctionalTest.java:1549)
        at FunctionalTest.main(FunctionalTest.java:1630)
:functional:runFunctionalTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':functional:runFunctionalTest'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3 mins 56.808 secs
```

## Steps to Reproduce (for bugs)
Run Minio Java functional test on Gateway

## Context
GCS branch testing

## Your Environment
macOS

**Comment by nitisht** [comment]
Looks like this is a minio-java bug, there is a PR for this https://github.com/minio/minio-java/pull/581 

Will test with this PR.

**Comment by deekoder** [comment]
ok

**Comment by harshavardhana** [comment]
This is not a minio server issue and can be closed.
