### ISSUE TITLE
minio-java functional tests fails with gateway-gcs

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#4601]
@balamurugana reported this issue on slack:

```
Test: recursive: listObjects(final String bucketName, final String prefix, final boolean recursive)
java.net.SocketTimeoutException: timeout
    at okio.Okio$4.newTimeoutException(Okio.java:227)
    at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
    at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
    at okhttp3.RealCall.execute(RealCall.java:69)
    at io.minio.MinioClient.execute(MinioClient.java:998)
    at io.minio.MinioClient.executeGet(MinioClient.java:1189)
    at io.minio.MinioClient.listObjectsV2(MinioClient.java:2556)
    at io.minio.MinioClient.access$100(MinioClient.java:158)
    at io.minio.MinioClient$5$1.populate(MinioClient.java:2430)
    at io.minio.MinioClient$5$1.hasNext(MinioClient.java:2458)
    at FunctionalTest.listObject_test5(FunctionalTest.java:689)
    at FunctionalTest.runTests(FunctionalTest.java:1580)
    at FunctionalTest.main(FunctionalTest.java:1665)
Caused by: java.net.SocketException: Socket closed
    at java.net.SocketInputStream.read(SocketInputStream.java:190)
    at java.net.SocketInputStream.read(SocketInputStream.java:122)
    at okio.Okio$2.read(Okio.java:138)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
    ... 28 more
:functional:runFunctionalTest FAILED
```

@NitishT responded:
> I tried Java tests with gateway. Looks like `listObject_test5` goes to infinite loop for GCS gateway.

This needs to be debugged.

**Comment by nitisht** [comment]
Sent PR https://github.com/minio/minio/pull/4608

**Comment by nitisht** [comment]
Can be closed now.
