### ISSUE TITLE
azure: minio-java test fails on azure gateway 

### ISSUE THREAD

**Issue by nitisht** [minio/minio#4640]
## Expected Behavior
Minio-Java functional tests work on azure gateway 

## Current Behavior
Minio-Java Functional Tests fails on azure backend. 

```
$ ./gradlew runFunctionalTest
:api:compileJava UP-TO-DATE
:api:processResources UP-TO-DATE
:api:classes UP-TO-DATE
:api:jar UP-TO-DATE
:functional:compileJava UP-TO-DATE
:functional:processResources UP-TO-DATE
:functional:classes UP-TO-DATE
:functional:runFunctionalTest
Test: makeBucket(String bucketName)
Test: listBuckets()
Test: bucketExists(String bucketName)
Test: removeBucket(String bucketName)
Test: putObject(String bucketName, String objectName, String filename)
Test: multipart: putObject(String bucketName, String objectName, String filename)
Test: multipart resume: putObject(String bucketName, String objectName, String filename)
Test: putObject(String bucketName, String objectName, String contentType, long size, InputStream body)
Test: putObject(String bucketName, String objectName, String filename, String contentType)
Test: objectName with path segments: putObject(String bucketName, String objectName, String filename)
Test: putObject(String bucketName, String objectName, InputStream body, String contentType)
Test: multipart: putObject(String bucketName, String objectName, InputStream body, String contentType)
java.net.SocketException: Connection reset
        at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
        at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
        at okio.Okio$1.write(Okio.java:78)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:41)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:109)
        at io.minio.MinioClient$3.writeTo(MinioClient.java:871)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
        at okhttp3.RealCall.execute(RealCall.java:69)
        at io.minio.MinioClient.execute(MinioClient.java:998)
        at io.minio.MinioClient.executePut(MinioClient.java:1266)
        at io.minio.MinioClient.executePut(MinioClient.java:1288)
        at io.minio.MinioClient.putObject(MinioClient.java:3480)
        at io.minio.MinioClient.putObject(MinioClient.java:3590)
        at io.minio.MinioClient.putObject(MinioClient.java:3175)
        at FunctionalTest.putObject_test8(FunctionalTest.java:291)
        at FunctionalTest.runTests(FunctionalTest.java:1601)
        at FunctionalTest.main(FunctionalTest.java:1704)
:functional:runFunctionalTest FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':functional:runFunctionalTest'.
> Process 'command '/usr/lib/jvm/java-8-openjdk-amd64/bin/java'' finished with non-zero exit value 255

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 59.525 secs

```

## Possible Solution
Not known

## Steps to Reproduce (for bugs)
- Build Minio server from current master
- Run it in `azure` gateway mode. 
- Point minio-java functional tests to your Minio instance and run with `./gradlew runFunctionalTest`

**Comment by nitisht** [comment]
Server output

```
ERRO[0204] Unable to create object part.                 cause=storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
RequestId:85428cc4-0001-00db-3da5-f64938000000
Time:2017-07-06T22:13:48.1727972Z, RequestId=85428cc4-0001-00db-3da5-f64938000000, QueryParameterName=, QueryParameterValue= source=[object-handlers.go:817:objectAPIHandlers.PutObjectPartHandler()] stack=gateway-azure.go:548:(*azureObjects).PutObjectPart object-handlers.go:814:objectAPIHandlers.PutObjectPartHandler api-router.go:46:(objectAPIHandlers).PutObjectPartHandler-fm
ERRO[0205] Unable to create object part.                 cause=storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
RequestId:6c24d2f5-0001-0026-74a5-f6765a000000
Time:2017-07-06T22:13:48.6298810Z, RequestId=6c24d2f5-0001-0026-74a5-f6765a000000, QueryParameterName=, QueryParameterValue= source=[object-handlers.go:817:objectAPIHandlers.PutObjectPartHandler()] stack=gateway-azure.go:548:(*azureObjects).PutObjectPart object-handlers.go:814:objectAPIHandlers.PutObjectPartHandler api-router.go:46:(objectAPIHandlers).PutObjectPartHandler-fm
ERRO[0280] Unable to create object part.                 cause=storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
RequestId:d9683b17-0001-0073-13a5-f69d2d000000
Time:2017-07-06T22:15:04.4142591Z, RequestId=d9683b17-0001-0073-13a5-f69d2d000000, QueryParameterName=, QueryParameterValue= source=[object-handlers.go:817:objectAPIHandlers.PutObjectPartHandler()] stack=gateway-azure.go:548:(*azureObjects).PutObjectPart object-handlers.go:814:objectAPIHandlers.PutObjectPartHandler api-router.go:46:(objectAPIHandlers).PutObjectPartHandler-fm
ERRO[0281] Unable to create object part.                 cause=storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
RequestId:6bf93f63-0001-00c1-39a5-f66657000000
Time:2017-07-06T22:15:05.4774073Z, RequestId=6bf93f63-0001-00c1-39a5-f66657000000, QueryParameterName=, QueryParameterValue= source=[object-handlers.go:817:objectAPIHandlers.PutObjectPartHandler()] stack=gateway-azure.go:548:(*azureObjects).PutObjectPart object-handlers.go:814:objectAPIHandlers.PutObjectPartHandler api-router.go:46:(objectAPIHandlers).PutObjectPartHandler-fm
```

**Comment by balamurugana** [comment]
Failure at minio-java side is due to server closing connection.  Unfortunately I am not able to find any code in minio http handlers closing the connection.  However I found `http.Response` object has a field `closeAfterReply` set to `true`.  It could be possible that `net/http` package may close this connection which is causing a `connection reset` at minio-java side.

Below is the response value.
```
&{conn:0xc420780b80 req:0xc4206e7a40 reqBody:0xc420476940 cancelCtx:0x82c920 wroteHeader:true wroteContinue:false wants10KeepAlive:false wantsClose:false w:0xc4204769c0 cw:{res:0xc4201385b0 header:map[Vary:[Origin] X-Amz-Request-Id:[14CF0D7A083339CD] Server:[Minio/DEVELOPMENT.2017-07-07T12-50-34Z (linux; amd64)] X-Amz-Bucket-Region:[us-east-1] Accept-Ranges:[bytes] Content-Type:[application/xml]] wroteHeader:true chunking:true} handlerHeader:map[X-Amz-Bucket-Region:[us-east-1] Accept-Ranges:[bytes] Content-Type:[application/xml] Vary:[Origin] X-Amz-Request-Id:[14CF0D7A083339CD] Server:[Minio/DEVELOPMENT.2017-07-07T12-50-34Z (linux; amd64)]] calledHeader:true written:305 contentLength:-1 status:500 closeAfterReply:true requestBodyLimitHit:true trailers:[] handlerDone:0 dateBuf:[70 114 105 44 32 48 55 32 74 117 108 32 50 48 49 55 32 49 50 58 53 51 58 51 56 32 71 77 84] clenBuf:[0 0 0 0 0 0 0 0 0 0] closeNotifyCh:<nil>}
```

Server's console shows below
```
ERRO[0046] Unable to create object part.                 cause=storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
RequestId:6698c830-0001-00d0-1920-f7514c000000
Time:2017-07-07T12:53:38.8124343Z, RequestId=6698c830-0001-00d0-1920-f7514c000000, QueryParameterName=, QueryParameterValue= source=[object-handlers.go:833:objectAPIHandlers.PutObjectPartHandler()] stack=gateway-azure.go:553:(*azureObjects).PutObjectPart object-handlers.go:828:objectAPIHandlers.PutObjectPartHandler api-router.go:46:(objectAPIHandlers).PutObjectPartHandler-fm
```

**Comment by harshavardhana** [comment]
> ERRO[0046] Unable to create object part.                 cause=storage: service returned error: StatusCode=413, ErrorCode=RequestBodyTooLarge, ErrorMessage=The request body is too large and exceeds the maximum permissible limit.
> RequestId:6698c830-0001-00d0-1920-f7514c000000

Isn't this the actual error here? ``The request body is too large and exceeds the maximum permissible limit`` - this is because azure only support 100MB maximum part size per part? 

// cc @krishnasrinivas

**Comment by harshavardhana** [comment]
> Isn't this the actual error here? The request body is too large and exceeds the maximum permissible limit - this is because azure only support 100MB maximum part size per part?

Perhaps the tests which fail are uploading 525MB part ?

**Comment by harshavardhana** [comment]
https://godoc.org/github.com/Azure/azure-sdk-for-go/storage#Blob.PutBlockWithLength

```
PutBlockWithLength saves the given data stream of exactly specified size to the block blob with given ID. It is an alternative to PutBlocks where data comes as stream but the length is known in advance.

The API rejects requests with size > 100 MiB (but this limit is not checked by the SDK).

See https://docs.microsoft.com/en-us/rest/api/storageservices/fileservices/Put-Block
```

**Comment by balamurugana** [comment]
>> Isn't this the actual error here? The request body is too large and exceeds the maximum permissible limit - this is because azure only support 100MB maximum part size per part?
>> 
> Perhaps the tests which fail are uploading 525MB part ?

Yes. The test is doing unknown sized stream multipart upload.  The situation is like below
1. okhttp streams 525MB of data in one end and the connection is set to keep alive.
2. server reads the stream and passes to azure. azure fails due to the stream size is beyond 100MB in the middle of read.
3. the server replies the error and closes the connection.
4. async write to okhttp fails to write (java.net.SocketException: Connection reset at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)) because of the connection is closed at server side.
5. even though the error response to the call is available, write to the connection throws error before reading the response.
5. It looks like a violation in closing keep alive connection.

I am investigating more with Go http client.

**Comment by balamurugana** [comment]
Observed same error using minio-go ie `2017/07/08 21:22:01 read tcp [::1]:44448->[::1]:9000: use of closed network connection`

```
---------START-HTTP---------
GET /mybucket/?location= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170709T042115Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Sun, 09 Jul 2017 04:21:15 GMT
Server: Minio/DEVELOPMENT.2017-07-09T04-14-28Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14CF8EAD31C68945
---------END-HTTP---------
---------START-HTTP---------
POST /mybucket/myobject?uploads= HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 0
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
Content-Type: application/octet-stream
X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20170709T042115Z
Accept-Encoding: gzip

HTTP/1.1 200 OK
Transfer-Encoding: chunked
Accept-Ranges: bytes
Content-Type: application/xml
Date: Sun, 09 Jul 2017 04:21:15 GMT
Server: Minio/DEVELOPMENT.2017-07-09T04-14-28Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14CF8EAD31EE7488
---------END-HTTP---------
---------START-HTTP---------
PUT /mybucket/myobject?partNumber=1&uploadId=myobject HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 603979776
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e30a781d3b48046cbb6f27cd7319ee6f61181d569fadac193f5a81d15407155c
X-Amz-Date: 20170709T042133Z
Accept-Encoding: gzip

---------START-HTTP---------
PUT /mybucket/myobject?partNumber=1&uploadId=myobject HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 603979776
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e30a781d3b48046cbb6f27cd7319ee6f61181d569fadac193f5a81d15407155c
X-Amz-Date: 20170709T042139Z
Accept-Encoding: gzip

---------START-HTTP---------
PUT /mybucket/myobject?partNumber=1&uploadId=myobject HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 603979776
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e30a781d3b48046cbb6f27cd7319ee6f61181d569fadac193f5a81d15407155c
X-Amz-Date: 20170709T042145Z
Accept-Encoding: gzip

---------START-HTTP---------
PUT /mybucket/myobject?partNumber=1&uploadId=myobject HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 603979776
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e30a781d3b48046cbb6f27cd7319ee6f61181d569fadac193f5a81d15407155c
X-Amz-Date: 20170709T042150Z
Accept-Encoding: gzip

---------START-HTTP---------
PUT /mybucket/myobject?partNumber=1&uploadId=myobject HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Content-Length: 603979776
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e30a781d3b48046cbb6f27cd7319ee6f61181d569fadac193f5a81d15407155c
X-Amz-Date: 20170709T042156Z
Accept-Encoding: gzip

---------START-HTTP---------
DELETE /mybucket/myobject?uploadId=myobject HTTP/1.1
Host: localhost:9000
User-Agent: Minio (linux; amd64) minio-go/3.0.0
Authorization: AWS4-HMAC-SHA256 Credential=minioazure/20170709/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20170709T042201Z
Accept-Encoding: gzip

Accept-Ranges: bytes
Date: Sun, 09 Jul 2017 04:22:01 GMT
Server: Minio/DEVELOPMENT.2017-07-09T04-14-28Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14CF8EB7FFBD8A6B
---------END-HTTP---------
2017/07/08 21:22:01 read tcp [::1]:44448->[::1]:9000: use of closed network connection
exit status 1
```

**Comment by balamurugana** [comment]
I tried to identify the behavior by reducing globalMaxPartSize to 100MiB doesn't help ie clients kept writing data than reading the reply, hence closed connection error appears.

**Comment by krishnasrinivas** [comment]
https://github.com/krishnasrinivas/minio/tree/azure-max-body-limit should fix, testing it

**Comment by harshavardhana** [comment]
We should open a bug on minio-go or minio-java to handle this situation of server closing the connection @balamurugana and this issue can be closed.

**Comment by harshavardhana** [comment]
After further discussions it can be seen that both server and client are behaving appropriately.  We could further dig and ask Go upstream about this behavior .. if not we can close this bug as non issue.

**Comment by balamurugana** [comment]
As this is neither server nor client (minio-java) issue, we would need to discuss and close it accordingly.

**Comment by harshavardhana** [comment]
> As this is neither server nor client (minio-java) issue, we would need to discuss and close it accordingly.

What else is there to discuss? @balamurugana

**Comment by balamurugana** [comment]
As per discussion with @abperiasamy, this is gateway issue not supporting 525MB or any allowable S3 part size.  If data in stream is >100MB, Azure gateway code needs to split into new parts internally i.e. every 100MB of data is created with separate parts till end of stream.

@krishnasrinivas the above requires further discussion on the design/implementation.

**Comment by krishnasrinivas** [comment]
> As per discussion with @abperiasamy, this is gateway issue not supporting 525MB or any allowable S3 part size. If data in stream is >100MB, Azure gateway code needs to split into new parts internally i.e. every 100MB of data is created with separate parts till end of stream.

no @balamurugana, I think AB might have misunderstood the problem because the above solution will make the gateway very complex. We had decided to inherit limitations of Backends i.e if backend supports 100MB size we will inherit this limitation.

I suspect this issue would be same as https://github.com/golang/go/issues/11745

**Comment by harshavardhana** [comment]
why is this still blocked?

**Comment by balamurugana** [comment]
Refer https://github.com/minio/minio/issues/3475
