### ISSUE TITLE
Crash in FS mode when Erasure coded mode is already running

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#4715]
## Expected Behavior
```
ERRO[0000] Initializing object layer failed              cause=FS backend format required. Found 'xl' source=[server-main.go:206:serverMain()]
```

## Current Behavior
```
$ minio server /tmp/1
ERRO[0000] Initializing object layer failed              cause=FS backend format required. Found 'xl' source=[server-main.go:206:serverMain()]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8daaf1]

goroutine 1 [running]:
panic(0xe898c0, 0xc420010120)
	/home/harsha/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/minio/minio/pkg/http.(*httpListener).Close(0x0, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/pkg/http/listener.go:227 +0x41
github.com/minio/minio/pkg/http.(*Server).Shutdown(0xc4201784e0, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/pkg/http/server.go:128 +0xa6
github.com/minio/minio/cmd.serverMain(0xc4201e7340)
	/home/harsha/mygo/src/github.com/minio/minio/cmd/server-main.go:207 +0x89e
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xe239e0, 0x1071ba8, 0xc4201e7340, 0xc420181600, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xfccc8f, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfe6756, 0x1c, 0x0, ...)
	/home/harsha/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xb9a
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc420065d40, 0xc42000a270, 0x3, 0x3, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x816
github.com/minio/minio/cmd.Main(0xc42000a270, 0x3, 0x3)
	/home/harsha/mygo/src/github.com/minio/minio/cmd/main.go:145 +0x8d
main.main()
	/home/harsha/mygo/src/github.com/minio/minio/main.go:68 +0x7b
```

## Possible Solution
Looks like the crash is inside listener close.. 
```
// Close - closes underneath all TCP listeners.
func (listener *httpListener) Close() (err error) {
        listener.mutex.Lock()  ---> L227 looks like listener.mutex is nil or listener is nil. 
        defer listener.mutex.Unlock()
        if listener.doneCh == nil {
                return syscall.EINVAL
        }

        for i := range listener.tcpListeners {
                listener.tcpListeners[i].Close()
        }
        close(listener.doneCh)

        listener.doneCh = nil
        return nil
}
```

## Steps to Reproduce (for bugs)
Start a erasure coded mode `minio server /tmp/{1..4}` and subsequently attempt to start `minio server /tmp/1` when the erasure coded minio server is still running.

## Context
 Release testing. 

## Your Environment
master

**Comment by harshavardhana** [comment]
Reproducible in vice versa manner as well, keep a running `minio server /tmp/1` in FS mode and start erasure coded mode including the disk `/tmp/1` 

```
$ minio server /tmp/{1..4}
ERRO[0000] Initializing object layer failed              cause=Unsupported backend format [fs] found source=[server-main.go:206:serverMain()]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8daaf1]

goroutine 1 [running]:
panic(0xe898c0, 0xc420010110)
	/home/harsha/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/minio/minio/pkg/http.(*httpListener).Close(0x0, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/pkg/http/listener.go:227 +0x41
github.com/minio/minio/pkg/http.(*Server).Shutdown(0xc4201749c0, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/pkg/http/server.go:128 +0xa6
github.com/minio/minio/cmd.serverMain(0xc420284420)
	/home/harsha/mygo/src/github.com/minio/minio/cmd/server-main.go:207 +0x89e
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xe239e0, 0x1071ba8, 0xc420284420, 0xc42017d600, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xfccc8f, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfe6756, 0x1c, 0x0, ...)
	/home/harsha/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xb9a
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc4202ba340, 0xc42000a120, 0x6, 0x6, 0x0, 0x0)
	/home/harsha/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x816
github.com/minio/minio/cmd.Main(0xc42000a120, 0x6, 0x6)
	/home/harsha/mygo/src/github.com/minio/minio/cmd/main.go:145 +0x8d
main.main()
	/home/harsha/mygo/src/github.com/minio/minio/main.go:68 +0x7b
```

**Comment by harshavardhana** [comment]
Fixed by 

>commit 0aca2ab9707f86be436800a437606301674e922a
Author: ebozduman <ersan.bozduman@gmail.com>
Date:   Fri Aug 4 10:44:46 2017 -0700
>
>    Stop attempting to close nil Listener (#4753)
