### ISSUE TITLE
"Invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by sebastiaanluca** [minio/minio#4773]
Starting the Minio server fails with a SIGSEGV exception.

## Expected Behavior

The server should start.

## Current Behavior

It doesn't 😁

Exception trace:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x4b6d8c]

goroutine 1 [running]:
panic(0xe8aac0, 0xc42000e0a0)
        /home/builder/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1a1
github.com/minio/minio/cmd.migrateV16ToV17(0xc420282c68, 0x2)
        /home/builder/mygo/src/github.com/minio/minio/cmd/config-migrate.go:1180 +0x2ac
github.com/minio/minio/cmd.migrateConfig(0xc42027b440, 0x20)
        /home/builder/mygo/src/github.com/minio/minio/cmd/config-migrate.go:134 +0x217
github.com/minio/minio/cmd.initConfig()
        /home/builder/mygo/src/github.com/minio/minio/cmd/common-main.go:58 +0x5d
github.com/minio/minio/cmd.serverMain(0xc420199b80)
        /home/builder/mygo/src/github.com/minio/minio/cmd/server-main.go:146 +0x113
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xe24b80, 0x10732b0, 0xc420199b80, 0xc42006f800, 0x0)
        /home/builder/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0xfce1af, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0xfe7c74, 0x1c, 0x0, ...)
        /home/builder/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xb9a
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc42026e340, 0xc42000a120, 0x3, 0x3, 0x0, 0x0)
        /home/builder/mygo/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x816
github.com/minio/minio/cmd.Main(0xc42000a120, 0x3, 0x3)
        /home/builder/mygo/src/github.com/minio/minio/cmd/main.go:145 +0x8d
main.main()
        /home/builder/mygo/src/github.com/minio/minio/main.go:68 +0x7b
```

## Possible Solution

No idea. Just wanted to try out Minio on a local Ubuntu VM.

## Steps to Reproduce (for bugs)

```
sudo wget -O /usr/bin/minio https://dl.minio.io/server/minio/release/linux-amd64/minio --no-verbose
sudo chmod +x /usr/bin/minio
mkdir -p ~/.minio
cp -v /vagrant/scripts/vm/config/minio/config.json ~/.minio/config.json
minio server ~
```

## Context

config.json (keys are just random, doesn't matter I post them here):
```
{
    "version": "16",
    "credential": {
        "accessKey": "mex6EuHc4YeHnBIZdG88",
        "secretKey": "ko5Th9UrJXv746HBc5cPnIXX1qEL4ltbxmSCkCSS"
    },
    "region": "eu-west-1",
    "browser": "on"
}
```

## Your Environment

Minio version:

```
Version: 2017-07-24T18:27:35Z
Release-Tag: RELEASE.2017-07-24T18-27-35Z
Commit-ID: 461d60095df56cdb1370f20135429a5a24b400b3
```

Nginx:
```
nginx version: nginx/1.13.3
```

Server (vagrant/Virtualbox virtual machine):

```
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial

Linux dev1 4.4.0-81-generic #104-Ubuntu SMP Wed Jun 14 08:17:06 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

Probably related to https://github.com/minio/minio/issues/2541.

**Comment by harshavardhana** [comment]
> {
>     "version": "16",
>     "credential": {
>         "accessKey": "mex6EuHc4YeHnBIZdG88",
>         "secretKey": "ko5Th9UrJXv746HBc5cPnIXX1qEL4ltbxmSCkCSS"
>     },
>     "region": "eu-west-1",
>     "browser": "on"
> }

Looks like you hand wrote this `config.json` - it has missing fields perhaps this is the reason. We need to check if the `Logger` field is `nil` in migration. 
```
srvConfig.Logger.Console = cv16.Logger.Console                                                                
srvConfig.Logger.File = cv16.Logger.File   
```

Lets say if you add this part of the config it will work fine
```json
        "version": "16",
        "credential": {
                "accessKey": "USWUXHGYZQYFYFFIT3RE",
                "secretKey": "MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03"
        },
        "region": "us-east-1",
        "browser": "on",
        "logger": {
                "console": {
                        "enable": true
                },
                "file": {
                        "enable": false,
                        "filename": ""
                }
        },
        "notify": {}
```

**Comment by harshavardhana** [comment]
Also its not related to #2541

**Comment by sebastiaanluca** [comment]
Aha, was not aware that a full configuration file was required. Thought each key was optional.

This fixes my issue. Thank you for your help!
