### ISSUE TITLE
mint tests for gateways fail on putobject call with SocketTimeoutException

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4892]
For all three gateways, multipart put call fails on mint.

Stack trace for gcs:

java.net.SocketTimeoutException: timeout
	at okio.Okio$4.newTimeoutException(Okio.java:227)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:284)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:240)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:344)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.minio.MinioClient.execute(MinioClient.java:998)
	at io.minio.MinioClient.executePut(MinioClient.java:1266)
	at io.minio.MinioClient.executePut(MinioClient.java:1288)
	at io.minio.MinioClient.putObject(MinioClient.java:3480)
	at io.minio.MinioClient.putObject(MinioClient.java:3564)
	at io.minio.MinioClient.putObject(MinioClient.java:3441)
	at io.minio.MinioClient.putObject(MinioClient.java:3375)
	at FunctionalTest.putObject_test10(FunctionalTest.java:391)
	at FunctionalTest.runTests(FunctionalTest.java:1608)
	at FunctionalTest.main(FunctionalTest.java:1717)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:204)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	... 29 more

Stack trace for s3
error occured
ErrorResponse(code=InternalError, message=We encountered an internal error, please try again., bucketName=null, objectName=null, resource=/minio-java-test-15fpcms/minio-java-test-1gttcrt, requestId=3L137, hostId=3L137)
request={method=PUT, url=http://192.168.1.157:9000/minio-java-test-15fpcms/minio-java-test-1gttcrt?uploadId=oebyWI2cSx1e254wMwh28pRMtl0iUYmI0hCfebuGY99LCDsBY5wE9TB44dxatUSKHxEBEmgp6._2H4_4bf2nGTj5cnao9v8I91XWainM3gO4._djYePAsOMN77PpUFaF&partNumber=1, headers=Host: 192.168.1.157:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: c036cbb7553a909f8b8877d4461924307f27ecb66cff928eeeafd569c3887e29
x-amz-date: 20170901T213457Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170901/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=500, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/RELEASE.2017-09-01T19-22-40Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14E05A6CCCC742A3
Date: Fri, 01 Sep 2017 21:34:58 GMT
Transfer-Encoding: chunked
}

	at io.minio.MinioClient.execute(MinioClient.java:1099)
	at io.minio.MinioClient.executePut(MinioClient.java:1266)
	at io.minio.MinioClient.executePut(MinioClient.java:1288)
	at io.minio.MinioClient.putObject(MinioClient.java:3480)
	at io.minio.MinioClient.putObject(MinioClient.java:3590)
	at io.minio.MinioClient.putObject(MinioClient.java:3001)
	at io.minio.MinioClient.putObject(MinioClient.java:3038)
	at FunctionalTest.putObject_test2(FunctionalTest.java:238)
	at FunctionalTest.runTests(FunctionalTest.java:1600)
	at FunctionalTest.main(FunctionalTest.java:1717)

Stack trace for azure
java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at okio.Okio$1.write(Okio.java:78)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:179)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
	at okio.RealBufferedSink.write(RealBufferedSink.java:41)
	at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:286)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
	at okio.RealBufferedSink.write(RealBufferedSink.java:109)
	at io.minio.MinioClient$3.writeTo(MinioClient.java:871)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
	at okhttp3.RealCall.execute(RealCall.java:69)
	at io.minio.MinioClient.execute(MinioClient.java:998)
	at io.minio.MinioClient.executePut(MinioClient.java:1266)
	at io.minio.MinioClient.executePut(MinioClient.java:1288)
	at io.minio.MinioClient.putObject(MinioClient.java:3480)
	at io.minio.MinioClient.putObject(MinioClient.java:3590)
	at io.minio.MinioClient.putObject(MinioClient.java:3175)
	at FunctionalTest.putObject_test8(FunctionalTest.java:347)
	at FunctionalTest.runTests(FunctionalTest.java:1606)
	at FunctionalTest.main(FunctionalTest.java:1717)

**Comment by deekoder** [comment]
Found in the release build.

**Comment by krishnasrinivas** [comment]
is there any error log by minio server @balamurugana ? do you know if minio-java does anything in particular? because multipart PUT otherwise works fine.

**Comment by balamurugana** [comment]
@krishnasrinivas Basically three issues as per the trace.
1. GCS gateway times out.  The test is put object with client side encryption.
2. S3 gateway returns internal error on `putObject_test2()` which does multipart put object. `ErrorResponse(code=InternalError, message=We encountered an internal error, please try again., bucketName=null, objectName=null, resource=/minio-java-test-15fpcms/minio-java-test-1gttcrt, requestId=3L137, hostId=3L137)`
3. Azure gateway returns `connection reset` i.e. server closes the connection.  This is because 525MiB part upload.  PR https://github.com/minio/minio/pull/4869 is fixing this issue.

**Comment by balamurugana** [comment]
All minio SDK could increase socket timeout to 15 minutes to avoid timing out in the server.

**Comment by kannappanr** [comment]
Not seeing this issue anymore with the gateway runs in Mint.
