### ISSUE TITLE
[gateway/s3] list object v2 does not work properly

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#4900]
Test doing recursive list object v2 for 1050 objects, fails.
```
java.lang.Exception: [FAILED] Test: recursive: listObject_test5(), number of items, expected: 1050, found: 21248000
        at FunctionalTest.listObject_test5(FunctionalTest.java:676)
        at FunctionalTest.runTests(FunctionalTest.java:1624)
        at FunctionalTest.main(FunctionalTest.java:1717)
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by balamurugana** [comment]
The test fails after listing first 1000 objects

error occured
ErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=null, objectName=null, resource=/minio-java-test-11lqkou, requestId=3L137, hostId=3L137)
request={method=GET, url=http://127.0.0.1:9000/minio-java-test-11lqkou?list-type=2&continuation-token=2%2188%21MDAwMDIyIW1pbmlvLWphdmEtdGVzdC1yZGJua3UhMDAwMDI4ITk5OTktMTItMzFUMjM6NTk6NTkuOTk5OTk5OVoh&prefix=minio, headers=Host: 127.0.0.1:9000
User-Agent: Minio (amd64; amd64) minio-java/dev
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20170912T231946Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20170912/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=501, headers=Accept-Ranges: bytes
Content-Type: application/xml
Server: Minio/DEVELOPMENT.2017-09-12T23-06-56Z (linux; amd64)
Vary: Origin
X-Amz-Bucket-Region: us-east-1
X-Amz-Request-Id: 14E3C08708C499D2
Date: Tue, 12 Sep 2017 23:19:46 GMT
Transfer-Encoding: chunked
}

	at io.minio.MinioClient.execute(MinioClient.java:1192)
	at io.minio.MinioClient.executeGet(MinioClient.java:1285)
	at io.minio.MinioClient.listObjectsV2(MinioClient.java:2702)
	at io.minio.MinioClient.access$100(MinioClient.java:158)
	at io.minio.MinioClient$5$1.populate(MinioClient.java:2576)
	at io.minio.MinioClient$5$1.hasNext(MinioClient.java:2604)
	at FunctionalTest.listObject_test5(FunctionalTest.java:1113)
	at FunctionalTest.runTests(FunctionalTest.java:2366)
	at FunctionalTest.main(FunctionalTest.java:2474)
