### ISSUE TITLE
Mint failure on azure gateway

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#5316]
For https://data.minio.io:10000/minio/release-minio/staging/DEVELOPMENT.2017-12-21T22-27-09Z/
Mint logs:

```
(1/1) Running minio-dotnet tests ... ./run.sh: line 26:    14 Aborted                 (core dumped) /mint/run/core/minio-dotnet/out/Minio.Functional.Tests >> "$output_log_file" 2> "$error_log_file"
FAILED in 3 minutes and 54 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail()
   at Minio.Functional.Tests.FunctionalTest.<PutObject_Task>d__52.MoveNext() in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Minio.Functional.Tests.FunctionalTest.<ListObjects_Test5>d__72.MoveNext() in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1658
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 216

Executed 0 out of 1 tests successfully.
Running with
SERVER_ENDPOINT: 192.168.1.123:9000
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'sudo docker cp 3c44a96a46d4:/mint/log /tmp/mint-logs'
(1/1) Running minio-go tests ... done in 56 minutes and 9 seconds

All tests ran successfully
Running with
SERVER_ENDPOINT: 192.168.1.123:9000
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'sudo docker cp dae3618063cf:/mint/log /tmp/mint-logs'
(1/1) Running minio-java tests ... FAILED in 1 minutes and 46 seconds
{
  "name": "minio-java",
  "function": "presignedPostPolicy(PostPolicy policy)",
  "duration": 10076,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.Okio$4.newTimeoutException(Okio.java:227), okio.AsyncTimeout.exit(AsyncTimeout.java:284), okio.AsyncTimeout$2.read(AsyncTimeout.java:240), okio.RealBufferedSource.indexOf(RealBufferedSource.java:344), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:216), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:210), okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185), okhttp3.RealCall.execute(RealCall.java:69), FunctionalTest.presignedPostPolicy_test(FunctionalTest.java:1636), FunctionalTest.runQuickTests(FunctionalTest.java:2643), FunctionalTest.main(FunctionalTest.java:2691)]"
}

```

**Comment by nitisht** [comment]
Tried to reproduce this with latest `minio/mint:edge` image. All tests passed except `minio-dotnet`

```
nitish@minio:~/dev$ sudo docker run -e "SERVER_ENDPOINT=127.0.0.1:9000" -e "ACCESS_KEY=XXX" -e "SECRET_KEY=XXXX" -e "ENABLE_HTTPS=0" --net=host minio/mint:edge

Running with
SERVER_ENDPOINT: 127.0.0.1:9000
ACCESS_KEY:      minioazure
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'sudo docker cp 9a2b8dd48a57:/mint/log /tmp/mint-logs'
(1/11) Running aws-sdk-go tests ... done in 2 seconds
(2/11) Running aws-sdk-php tests ... done in 2 minutes and 17 seconds
(3/11) Running aws-sdk-ruby tests ... done in 1 minutes and 13 seconds
(4/11) Running awscli tests ... done in 1 minutes and 59 seconds
(5/11) Running mc tests ... done in 8 minutes and 49 seconds
(6/11) Running minio-dotnet tests ... ./run.sh: line 26:  1084 Aborted                 (core dumped) /mint/run/core/minio-dotnet/out/Minio.Functional.Tests >> "$output_log_file" 2> "$error_log_file"
FAILED in 3 minutes and 28 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail()
   at Minio.Functional.Tests.FunctionalTest.<PutObject_Task>d__52.MoveNext() in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 755
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Minio.Functional.Tests.FunctionalTest.<ListObjects_Test5>d__72.MoveNext() in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1658
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 216

Executed 5 out of 11 tests successfully.
```

```
nitish@minio:~/dev$ sudo docker run -e "SERVER_ENDPOINT=127.0.0.1:9000" -e "ACCESS_KEY=XXX" -e "SECRET_KEY=XXX" -e "ENABLE_HTTPS=0" --net=host minio/mint:edge minio-go minio-java minio-py minio-js s3cmd

Running with
SERVER_ENDPOINT: 127.0.0.1:9000
ACCESS_KEY:      minioazure
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'sudo docker cp e1ea551cdd35:/mint/log /tmp/mint-logs'
(1/5) Running minio-go tests ... done in 10 minutes and 43 seconds
(2/5) Running minio-java tests ... done in 1 minutes and 9 seconds
(3/5) Running minio-py tests ... done in 2 minutes and 11 seconds
(4/5) Running minio-js tests ... done in 4 minutes and 19 seconds
(5/5) Running s3cmd tests ... done in 5 minutes and 56 seconds

All tests ran successfully

```

**Comment by poornas** [comment]
The failing test uploads 1050 objects to test listing - test fails because azure gateway is not able to save object because of too many open files. The objects get uploaded asynchronously - so possible azure is not able to handle the concurrent upload.Subsequently the connection times out.

```
ERRO[0507] Unable to save an object /miniodotnetoywqhf8ehowme0q/miniodotnet3epbx410mj235  cause=Head https://minioazure1.blob.core.windows.net/miniodotnetoywqhf8ehowme0q/miniodotnet3epbx410mj235: dial tcp: lookup minioazure1.blob.core.windows.net on 127.0.0.53:53: dial udp 127.0.0.53:53: socket: too many open files source=[gateway-handlers.go:307:gatewayAPIHandlers.PutObjectHandler()] stack=/q/.q/sources/gopath/src/github.com/minio/minio/cmd/gateway/azure/gateway-azure.go:592:(*azureObjects).GetObjectInfo() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/gateway/azure/gateway-azure.go:619:(*azureObjects).PutObject() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/gateway-handlers.go:261:(GatewayLayer).PutObject-fm() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/gateway-handlers.go:305:gatewayAPIHandlers.PutObjectHandler() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/gateway-router.go:111:(gatewayAPIHandlers).PutObjectHandler-fm() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107:(*Router).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:558:pathValidityHandler.ServeHTTP() <autogenerated>:1:(*pathValidityHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:65:requestSizeLimitHandler.ServeHTTP() <autogenerated>:1:(*requestSizeLimitHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51:crossDomainPolicy.ServeHTTP() <autogenerated>:1:(*crossDomainPolicy).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:219:redirectHandler.ServeHTTP() <autogenerated>:1:(*redirectHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:267:minioReservedBucketHandler.ServeHTTP() <autogenerated>:1:(*minioReservedBucketHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:246:cacheControlHandler.ServeHTTP() <autogenerated>:1:(*cacheControlHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:337:timeValidityHandler.ServeHTTP() <autogenerated>:1:(*timeValidityHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190:(*Cors).Handler.func1() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:448:resourceHandler.ServeHTTP() <autogenerated>:1:(*resourceHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:234:authHandler.ServeHTTP() <autogenerated>:1:(*authHandler).ServeHTTP() /q/.q/sources/gopath/src/github.com/minio/minio/pkg/http/server.go:107:(*Server).Start.func1() /opt/go/src/net/http/server.go:1918:HandlerFunc.ServeHTTP() /opt/go/src/net/http/server.go:2619:serverHandler.ServeHTTP() /opt/go/src/net/http/server.go:1801:(*conn).serve()
```

**Comment by kannappanr** [comment]
I ran minio-java alone and that ran fine.  Here is the output from my run.

```
Running with
SERVER_ENDPOINT: 192.168.86.102:9000
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       full

To get logs, run 'sudo docker cp 188bbe4925a2:/mint/log /tmp/mint-logs'
(1/1) Running minio-java tests ... done in 34 minutes and 21 seconds

All tests ran successfully
```

**Comment by krishnasrinivas** [comment]
It might have been a temporary problem in my tests then

**Comment by deekoder** [comment]
I will mark this high pri and regression as we did not encounter this issue in our previous mint runs. This is also blocking release. Hence the high priority.
