### ISSUE TITLE
mint dotnet on gcs gateway fails

### ISSUE THREAD

**Issue by krishnasrinivas** [minio/minio#5320]
Logs:
```
(1/1) Running minio-dotnet tests ... ./run.sh: line 26:    14 Aborted                 (core dumped) /mint/run/core/minio-dotnet/out/Minio.Functional.Tests >> "$output_log_file" 2> "$error_log_file"
FAILED in 1 minutes and 20 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail()
   at Minio.Functional.Tests.FunctionalTest.<StatObject_Test1>d__54.MoveNext() in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 858
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 198

Executed 0 out of 1 tests successfully.
Running with
SERVER_ENDPOINT: 10.0.0.73:9000
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

```

**Comment by harshavardhana** [comment]
Should we close this issue !

**Comment by kannappanr** [comment]
Closing this issue as fixed.
