### ISSUE TITLE
[PR#5160] server crashes when expanded endpoints are used

### ISSUE THREAD

**Issue by balamurugana** [minio/minio#5497]
To reproduce this issue
1. run freshly `minio server sda{1...4} sdb{1...8}`. it works fine.
2. stop minio
3. start with expanded endpoints `$ minio server sda1 sda2 sda3 sda4 sdb1 sdb2 sdb3 sdb4 sdb5 sdb6 sdb7 sdb8`, now it crashes with below
```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/minio/minio/cmd.newXLSets(0xc4202aeb40, 0xc, 0xc, 0xc420506150, 0x1, 0xc, 0xc420506150)
	/home/bala/golang/gopath/src/github.com/minio/minio/cmd/xl-sets.go:182 +0xc13
github.com/minio/minio/cmd.newObjectLayer(0xc4202aeb40, 0xc, 0xc, 0x2, 0xc4203fdc60, 0x0, 0xc4201f85a0)
	/home/bala/golang/gopath/src/github.com/minio/minio/cmd/server-main.go:281 +0xcd
github.com/minio/minio/cmd.serverMain(0xc420220dc0)
	/home/bala/golang/gopath/src/github.com/minio/minio/cmd/server-main.go:244 +0x7e6
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xf58780, 0x117f138, 0xc420220dc0, 0xc4201ad300, 0x0)
	/home/bala/golang/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0x11361be, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x114fd9c, 0x1c, 0x0, ...)
	/home/bala/golang/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xa99
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc4201abba0, 0xc42000e0e0, 0xe, 0xe, 0x0, 0x0)
	/home/bala/golang/gopath/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x758
github.com/minio/minio/cmd.Main(0xc42000e0e0, 0xe, 0xe)
	/home/bala/golang/gopath/src/github.com/minio/minio/cmd/main.go:149 +0x8d
main.main()
	/home/bala/golang/gopath/src/github.com/minio/minio/main.go:71 +0x108
```

Either we need to error out properly or honor accordingly.

**Comment by harshavardhana** [comment]
Going to fail like this 

```
minio server sda1 sda2 sda3 sda4 sdb1 sdb2 sdb3 sdb4 sdb5 sdb6 sdb7 sdb8


Trace: 1: cmd/server-main.go:247:cmd.serverMain()
       2: vendor/github.com/minio/cli/app.go:499:cli.HandleAction()
       3: vendor/github.com/minio/cli/command.go:214:cli.Command.Run()
       4: vendor/github.com/minio/cli/app.go:260:cli.(*App).Run()
       5: cmd/main.go:149:cmd.Main()
       6: main.go:71:main.main()
[2018-02-06T11:03:29.925130135Z] [ERROR] Initializing object layer failed (Previous erasure backend format found, incompatible with input args ([sda1 sda2 sda3 sda4 sdb1 sdb2 sdb3 sdb4 sdb5 sdb6 sdb7 sdb8]) with - make sure to check your command line options)
```

**Comment by harshavardhana** [comment]
Actually i don't need to.

**Comment by harshavardhana** [comment]
Fixed this 

```
minio server sda{1...4} sdb{1...8}

Drive Capacity: 412 GiB Free, 939 GiB Total
```

```
minio server sda1 sda2 sda3 sda4 sdb1 sdb2 sdb3 sdb4 sdb5 sdb6 sdb7 sdb8

Drive Capacity: 412 GiB Free, 939 GiB Total
```

**Comment by harshavardhana** [comment]
Can you check @balamurugana you need to pull the latest.. ?

**Comment by balamurugana** [comment]
It works. Also `minio server sda1 sda2 sda3 sda4 sdb1 sdb2 sdb3 sdb4 sdb5 sdb6 sdb7 sdb8` and `minio sda{1...4} sdb{1...8}` work.

Now it leads to two ways to do the same thing.  Similarly ellipsis format as set representation is lost and mis-communicating.

Not sure what's our stand point on this.

**Comment by harshavardhana** [comment]
I am thinking we should fail @balamurugana will check with @abperiasamy - But i think we can fail to avoid confusion. We have to convey to the user on what happened though since we don't know previous arguments we can only tell them a minimum information regarding how the layout of the set was.

**Comment by harshavardhana** [comment]
Fixed in the PR this time it errors out @balamurugana

**Comment by harshavardhana** [comment]
Closing this as fixed in the PR, please re-open if seen again.
