### ISSUE TITLE
Missing 'ETag' key/value of awscli

### ISSUE THREAD

**Issue by Giangblackk** [minio/minio#5719]
I'm trying to using `Dask` to connect to Minio Storage Server instead of AWS S3 bucket:
```python
import dask.dataframe as dd
df = dd.read_csv("s3://test/sample_submission.csv",
    storage_options={
        "anon": False,
        "use_ssl": False,
        "key":"****************************",
        "secret":"*****************************************",
        "client_kwargs":{
            "region_name":"us-east-1",
            "endpoint_url":"http://localhost:9000"
        }
    })
```
But I got the error:
```python-traceback
Traceback (most recent call last):
  File "connect_minio_as_s3.py", line 56, in <module>
    'endpoint_url':'http://localhost:9000'
  File "/home/user/python3/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 426, in read
    **kwargs)
  File "/home/user/python3/lib/python3.6/site-packages/dask/dataframe/io/csv.py", line 302, in read_pandas
    **(storage_options or {}))
  File "/home/user/python3/lib/python3.6/site-packages/dask/bytes/core.py", line 89, in read_bytes
    size = logical_size(fs, path, compression)
  File "/home/user/python3/lib/python3.6/site-packages/dask/bytes/core.py", line 485, in logical_size
    return fs.size(path)
  File "/home/user/python3/lib/python3.6/site-packages/dask/bytes/s3.py", line 41, in size
    return self.info(path)['Size']
  File "/home/user/python3/lib/python3.6/site-packages/s3fs/core.py", line 407, in info
    out = {'ETag': out['ETag'], 'Key': '/'.join([bucket, key]),
KeyError: 'ETag'
```

After debugging, I found that when using function `head_object` from `awscli` library, the response of Minio is different from AWS S3 response:
- Minio Code:
```python
import boto3
conf = Config(connect_timeout=30,
            read_timeout=45)
client_kwargs = {
    'region_name':'us-east-1',
    'endpoint_url':'http://localhost:9000'
}
session = boto3.Session(
    aws_access_key_id='****************************',
    aws_secret_access_key='*****************************************',
    region_name='us-east-1'
)
s3.head_object(Bucket='test',Key='sample_submission.csv')
```
and get response:
```json
{
    "AcceptRanges": "bytes",
    "ContentLength": 448924,
    "ContentType": "text/csv",
    "LastModified": "2016-12-13T05:37:35",
    "Metadata": {},
    "ResponseMetadata": {
        "HTTPHeaders": {
            "accept-ranges": "bytes",
            "content-length": "448924",
            "content-type": "text/csv",
            "date": "Tue, 27 Mar 2018 12:18:55 GMT",
            "last-modified": "Tue, 13 Dec 2016 05:37:35 GMT",
            "server": "Minio/RELEASE.2018-03-19T19-22-06Z (linux; amd64)",
            "vary": "Origin",
            "x-amz-request-id": "151FC6362E8FAB8B"
        },
        "HTTPStatusCode": 200,
        "HostId": "",
        "RequestId": "151FC6362E8FAB8B",
        "RetryAttempts": 0
    }
}
```
- AWS S3 code:
```python
import boto3
from botocore.client import Config
conf = Config(connect_timeout=30,
                read_timeout=45)
client_kwargs = {
                'region_name':'us-east-1'
                }
session = boto3.Session(
         aws_access_key_id='******************',
         aws_secret_access_key='********************************',
         region_name='us-east-1'
     )
s3 = session.client('s3', config=conf, use_ssl=True,
                    **client_kwargs)
s3.head_object(Bucket='spacenet-dataset',Key='manifest.txt')
```
and get response:
```json
{
    "AcceptRanges": "bytes",
    "ContentLength": 3404,
    "ContentType": "binary/octet-stream",
    "ETag": "4986584c41293205874405b237559ec7",
    "LastModified": "2018-03-08T00:34:33",
    "Metadata": {},
    "ResponseMetadata": {
        "HTTPHeaders": {
            "accept-ranges": "bytes",
            "content-length": "3404",
            "content-type": "binary/octet-stream",
            "date": "Tue, 27 Mar 2018 11:26:49 GMT",
            "etag": "4986584c41293205874405b237559ec7",
            "last-modified": "Thu, 08 Mar 2018 00:34:33 GMT",
            "server": "AmazonS3",
            "x-amz-id-2": "T4M/4lY/Q7+xuFVVq0jNHs7jKoha2wr5yZ8nEOghWpHUV1s+q9dcGypbwqXOwY2a5KwSgJoAJas=",
            "x-amz-request-id": "514039251402DD95"
        },
        "HTTPStatusCode": 200,
        "HostId": "T4M/4lY/Q7+xuFVVq0jNHs7jKoha2wr5yZ8nEOghWpHUV1s+q9dcGypbwqXOwY2a5KwSgJoAJas=",
        "RequestId": "514039251402DD95",
        "RetryAttempts": 0
    }
}
```

There are missing `ETag` in `Minio` response.
Is this an incompatible problem between AWS S3 and Minio?

### Minio and system info:

    Version
    2018-03-19T19:22:06Z
    Memory
    Used: 3.0 MB | Allocated: 20 MB | Used-Heap: 3.0 MB | Allocated-Heap: 9.0 MB
    Platform
    Host: Workstation | OS: linux | Arch: amd64
    Runtime
    Version: go1.9.4 | CPUs: 24

**Comment by harshavardhana** [comment]
Did you upload the object through API ? Or were you directly using it from the disk like an existing file ?

**Comment by Giangblackk** [comment]
Oh, That's true. The object that I tested already existed before I started `Minio` Server.

I've tried on an object uploaded through API and it worked perfectly.
I close this issue.
Thank you for your support.
