### ISSUE TITLE
High CPU usage on minio during streaming backup with mc mirror --watch

### ISSUE THREAD

**Issue by curantes** [minio/minio#5854]
## Expected Behavior

Run `mc mirror --watch --remove` from my my backup node and target minio cluster. This should just stream all files from minio cluster to my local backup server without High CPU load.

## Current Behavior

Run `mc mirror --watch --remove` and slowly it starts to consume all available CPU until there is no CPU available and minio start to have high latency in serving files. this is ilustrated in below Load, CPU and Memory graph.
![screenshot from 2018-04-25 14-18-13](https://user-images.githubusercontent.com/6643262/39245442-1aa86a98-4894-11e8-84e8-c7f1f04444ae.png)

When interrupting `mc mirror --watch --remove` it does not respond for first `ctrl-c` but next `ctrl-c` it stops mirror and leaves a lot of bucket notification (SQS ARNs) that gets only cleaned upp if I do a rolling restart of minio cluster.
```
●  localhost:9091
   Uptime : online since 20 hours ago
  Version : 2018-04-12T23:41:09Z
   Region : 
 SQS ARNs : arn:minio:sqs::httpclient+69c38483-372a-4d96-a72e-486a952ff7da+10.98.32.147:51858+5e9c84f3-b89e-4693-8e17-7461073b1a37 arn:minio:sqs::httpclient+e2e2e515-4493-4ef6-857a-fa93f744b697+10.98.32.147:32486+75b0e735-db8b-4843-92c3-ddbfa838b4bd arn:minio:sqs::httpclient+1743dd7e-08b5-47d3-8476-4626714794c6+10.98.32.147:21104+de61f412-b8fa-4e2c-9c16-0c183ca081a3 arn:minio:sqs::httpclient+5d132120-48f2-4fe7-a160-3588cdb1897a+10.98.32.147:21144+7c74973f-b434-498b-b923-74899dc66925 arn:minio:sqs::httpclient+c7fb08fb-8ddd-4f6c-b94a-1ef55f2919fa+10.98.32.147:52536+7e620df2-e432-47d6-ad6d-29427eab2c7b arn:minio:sqs::httpclient+883e2cf4-e161-4762-bae3-4fd39a43bf25+10.98.32.147:16748+fcdf9b68-aa2d-4e6d-b1ef-f5da8486293e arn:minio:sqs::httpclient+e08b9ce1-eb09-4297-b03a-191bc91e6aa4+10.98.32.147:51838+e81e5604-d02e-4524-9378-74e6627edd10 arn:minio:sqs::httpclient+900eae1e-2c9d-4d54-a19b-1ad2b6ebb2ae+10.98.32.147:36898+6a54fdb9-33a5-4086-bd51-d89597a7a48d arn:minio:sqs::httpclient+6f527383-8dee-4d86-8a93-4fdb4a8a084a+10.98.32.147:36938+5b85d05b-6c4e-49c4-bf88-3071ab72fcf7 arn:minio:sqs::httpclient+4acc2385-aae2-4d64-8551-a60511acc935+10.98.32.147:45934+97f55f6e-6cf5-453a-b477-ee89d858e9a4 arn:minio:sqs::httpclient+b59d6e04-2945-4d4c-899e-9a8c6f6b85a3+10.98.32.147:21904+88b46454-af06-491f-a0ba-b85e9459b56e arn:minio:sqs::httpclient+ba766278-4987-4a10-8037-555d8e5313f3+10.98.32.147:16728+3175a498-e87b-449a-837e-c16ead12dad8 arn:minio:sqs::httpclient+67ef46aa-4992-4760-9ff8-74597862e951+10.98.32.147:16708+ff959918-2f79-4bdd-9c48-4dc5f0d2b389 arn:minio:sqs::httpclient+8f2d895a-a736-4558-87f4-511ad19bf7b0+10.98.32.147:33096+9a651caf-e771-40f2-a9fa-9e01a4b7e929 arn:minio:sqs::httpclient+bdad3bee-c0fe-4bfe-85ae-216ae2e32e80+10.98.32.147:32506+b0425b1e-c051-47cc-bd07-b1037ca518cd arn:minio:sqs::httpclient+5b0343c0-c363-46bf-a15e-847dda3bd164+10.98.32.147:32526+13fd2eba-8310-41eb-bd56-6b3f8a9a537d arn:minio:sqs::httpclient+534efb43-729e-4010-ab8d-08afc72905df+10.98.32.147:52516+0861511b-ed6a-45cc-9973-1a0099f9d03b arn:minio:sqs::httpclient+c762abec-7fe6-4c5b-960d-b2f46a986926+10.98.32.147:45894+da15936c-7d5b-4228-b9f3-6eb9ce43c137 arn:minio:sqs::httpclient+67d4839c-22c5-4836-9229-fca5dee94686+10.98.32.147:45914+a715d83f-390c-4198-9e6c-4186789a3ec8 arn:minio:sqs::httpclient+fb01d9be-57e8-4e9e-8e83-c6a0a4d4d00f+10.98.32.147:36918+53a4ff42-11fe-413c-a97d-b845ae855d56 arn:minio:sqs::httpclient+83b8ddc6-2081-476f-af7b-6a5bc5380a14+10.98.32.147:33136+f1a96c27-5e07-421b-82a5-827306eb16f0 arn:minio:sqs::httpclient+fe32f93f-a5d8-47b7-8e5b-460208be7c75+10.98.32.147:52496+fe64fde9-68bf-44da-80eb-30e9af91ab5c arn:minio:sqs::httpclient+d0f6d7a2-a531-433c-9305-ce409b266113+10.98.32.147:16688+b7b51c90-c9ee-428c-9035-079503fd55a9 arn:minio:sqs::httpclient+45008da1-df22-4b8a-b1c7-3f795dc629bc+10.98.32.147:33116+340e3ff1-e7b1-486f-b9ef-5556048def39 arn:minio:sqs::httpclient+9c10aefb-5864-4099-94ce-9aa09b3e0709+10.98.32.147:51878+cc0216d7-1cec-4a6a-a2f8-66f71ac5dd7e arn:minio:sqs::httpclient+dc3ebcb7-29e5-42c3-91db-4fd6b87faccb+10.98.32.147:21084+e3c10734-cb91-4b33-ac06-b5eb4b233b61 arn:minio:sqs::httpclient+272753cc-25e2-4153-b1ed-9668358ddb3d+10.98.32.147:21864+91669033-9286-4517-b19b-d559bdb9d355 arn:minio:sqs::httpclient+bbd26640-6f9e-48f0-987a-6d96d9a433af+10.98.32.147:21124+3ec77aa1-188e-4b5b-aa1a-d4f172806f6a arn:minio:sqs::httpclient+71d822fc-f8aa-4ecb-92fd-31972c083130+10.98.32.147:21884+221e5671-9a70-43b4-b107-697f4ad600d0 
    Stats : Incoming 2.1GiB, Outgoing 2.0GiB
  Storage : Total 1000GiB, Free 218GiB
    Disks : 10, 0
```

## Steps to Reproduce (for bugs)

1. setup minio distributed cluster
2. have appprox 40 buckets with enough files in approx 1mb size each so it takes some time to do the mirror 
3. run `mc mirror --watch --remove` from cluster to a local disk. during time the CPU usage increas steady until there is no more free.

## Context

This is our backup solution we, we have 10 node minio cluster and a FreeNAS server which have a local minio-client (mc) which have a script that keeps running `mc mirror --watch --remove <minio cluster> <local path>`

## Your Environment

* Version used (`minio version`): 2018-04-12T23:41:09Z
* Environment name and version (e.g. nginx 1.9.1): 
* Server type and version: Vmware VM, 10 nodes, 2 Cores, 4GB mem
* Operating System and version (`uname -a`):Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project:

**Comment by curantes** [comment]
I can add that after interupting the `mc mirror` yesterday there seems to still be a base load and cpu usage from when I stopped the mirror. It seems to just get corrected after a rolling restart.

![screenshot from 2018-04-26 08-18-14](https://user-images.githubusercontent.com/6643262/39289035-bb5f74f4-492a-11e8-85fe-eef3b137b16b.png)

**Comment by harshavardhana** [comment]
> I can add that after interupting the mc mirror yesterday there seems to still be a base load and cpu usage from when I stopped the mirror. It seems to just get corrected after a rolling restart.

How many files do you have on these buckets? @curantes

**Comment by curantes** [comment]
@harshavardhana not sure if this is enough but did a quick inode check on minio volume and I have
```
Filesystem                       Inodes    IUsed    IFree IUse% Mounted on
/dev/mapper/vg_minio-lv_minio 104855552 32064550 72791002   31% /minio
```
this is one of 10 nodes/disks

**Comment by harshavardhana** [comment]
> @harshavardhana not sure if this is enough but did a quick inode check on minio volume and I have
> 
> Filesystem                       Inodes    IUsed    IFree IUse% Mounted on
> /dev/mapper/vg_minio-lv_minio 104855552 32064550 72791002   31% /minio
> this is one of 10 nodes/disks

Thanks, @curantes this looks like an acceptable number, btw are the backend disks ext4 or xfs?

**Comment by curantes** [comment]
> Thanks, @curantes this looks like an acceptable number, btw are the backend disks ext4 or xfs?

@harshavardhana we use xfs for all our minio setups

**Comment by curantes** [comment]
We continue to have issues with this cluster. This time after interrupting the mirror as before the load and CPU usage stays the same. Also the Admin API was not responding with `mc admin`

Our devs also report that writes are failing but reads works but with higher latency than usual. During this time I tried to copy file with `mc copy` and delete and it worked. 

dev with alias kp in slack helped me with some troubleshooting. But in the end, after I completed a total restart of all minio instances in the cluster the Admin API started to respond and also the devs reported that writes are working again with normal latencies.

During this time there were about 300 files that failed to upload which we need to resync manually. 

When doing the restart of minio it did not respond to to TERM signal so I had to force kill with `kill -9 <PID>`

I have strong believes that this issue have something to do with `mc mirror --watch` as we have had similar issues in the past like, #5311

**Comment by vadmeste** [comment]
It looks like I am able to reproduce this, I have 40% constant cpu consumption after mirroring only 10k files but I am surprised to see that the stack trace (kill ABRT) not showing any suspicious activity. I will try with go 1.9 then I will do some profiling to understand.

```
11:51 $ minio server /mnt/p10/vadmeste/fs/

Drive Capacity: 7.4 GiB Free, 22 GiB Total

Endpoint:  http://192.168.1.169:9000  http://127.0.0.1:9000
AccessKey: minio
SecretKey: minio123

Browser Access:
   http://192.168.1.169:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.169:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
SIGABRT: abort
PC=0x45b9f3 m=0 sigcode=0

goroutine 42 [syscall]:
runtime.notetsleepg(0x1aed5e0, 0x1fc38, 0x0)
        /home/vadmeste/work/go/src/runtime/lock_futex.go:227 +0x42 fp=0xc42049df60 sp=0xc42049df30 pc=0x411212
runtime.timerproc(0x1aed5c0)
        /home/vadmeste/work/go/src/runtime/time.go:261 +0x2e7 fp=0xc42049dfd8 sp=0xc42049df60 pc=0x44b657
runtime.goexit()
        /home/vadmeste/work/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc42049dfe0 sp=0xc42049dfd8 pc=0x45a451
created by runtime.(*timersBucket).addtimerLocked
        /home/vadmeste/work/go/src/runtime/time.go:160 +0x107

goroutine 1 [select, 3 minutes]:
github.com/minio/minio/cmd.handleSignals()
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/signals.go:60 +0x12d
github.com/minio/minio/cmd.serverMain(0xc420125340)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/server-main.go:282 +0x8b8
github.com/minio/minio/vendor/github.com/minio/cli.HandleAction(0xf13ec0, 0x115e9f8, 0xc420125340, 0xc42008b500, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:499 +0x7c
github.com/minio/minio/vendor/github.com/minio/cli.Command.Run(0x1110ecc, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x112be58, 0x1c, 0x0, ...)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/vendor/github.com/minio/cli/command.go:214 +0xa35
github.com/minio/minio/vendor/github.com/minio/cli.(*App).Run(0xc42035a820, 0xc420030090, 0x3, 0x3, 0x0, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/vendor/github.com/minio/cli/app.go:260 +0x700
github.com/minio/minio/cmd.Main(0xc420030090, 0x3, 0x3)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/main.go:155 +0x8d
main.main()
        /home/vadmeste/work/gospace/src/github.com/minio/minio/main.go:71 +0x103

goroutine 5 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
        /home/vadmeste/work/go/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /home/vadmeste/work/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
        /home/vadmeste/work/go/src/os/signal/signal_unix.go:28 +0x41

goroutine 39 [chan receive, 1 minutes]:
github.com/minio/minio/cmd/http.(*httpListener).Accept(0xc42008a060, 0x1160150, 0xc420589720, 0x12098a0, 0xc420620120)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/http/listener.go:240 +0x57
net/http.(*Server).Serve(0xc4203505a0, 0x1205260, 0xc42008a060, 0x0, 0x0)
        /home/vadmeste/work/go/src/net/http/server.go:2770 +0x1a5
github.com/minio/minio/cmd/http.(*Server).Start(0xc4203505a0, 0x45a456, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/http/server.go:117 +0x23a
github.com/minio/minio/cmd.serverMain.func1()
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/server-main.go:258 +0x2d
created by github.com/minio/minio/cmd.serverMain
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/server-main.go:257 +0x730

goroutine 40 [select, 3 minutes, locked to thread]:
runtime.gopark(0x11607e0, 0x0, 0x1110ec0, 0x6, 0x18, 0x1)
        /home/vadmeste/work/go/src/runtime/proc.go:291 +0x11a
runtime.selectgo(0xc42049e750, 0xc4204bc0c0)
        /home/vadmeste/work/go/src/runtime/select.go:392 +0xe50
runtime.ensureSigM.func1()
        /home/vadmeste/work/go/src/runtime/signal_unix.go:549 +0x1f4
runtime.goexit()
        /home/vadmeste/work/go/src/runtime/asm_amd64.s:2361 +0x1

goroutine 61 [IO wait, 1 minutes]:
internal/poll.runtime_pollWait(0x7f48da7b0d60, 0x72, 0x0)
        /home/vadmeste/work/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42021a118, 0x72, 0xc420308200, 0x0, 0x0)
        /home/vadmeste/work/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(0xc42021a118, 0xffffffffffffff00, 0x0, 0x0)
        /home/vadmeste/work/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Accept(0xc42021a100, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vadmeste/work/go/src/internal/poll/fd_unix.go:372 +0x1a8
net.(*netFD).accept(0xc42021a100, 0xc4202144c8, 0x0, 0x0)
        /home/vadmeste/work/go/src/net/fd_unix.go:238 +0x42
net.(*TCPListener).accept(0xc42020a028, 0x456b80, 0xc42007df88, 0xc42007df90)
        /home/vadmeste/work/go/src/net/tcpsock_posix.go:136 +0x2e
net.(*TCPListener).AcceptTCP(0xc42020a028, 0xc4204a8080, 0xc4202144c8, 0xc42024a0c0)
        /home/vadmeste/work/go/src/net/tcpsock.go:246 +0x49
github.com/minio/minio/cmd/http.(*httpListener).start.func3(0xc42020a028, 0xc42024a0c0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/http/listener.go:220 +0x41
created by github.com/minio/minio/cmd/http.(*httpListener).start
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/http/listener.go:234 +0x1af

goroutine 66 [select, 3 minutes]:
github.com/minio/minio/cmd.(*FSObjects).cleanupStaleMultipartUploads(0xc42038ccc0, 0x1209820, 0xc42003a868, 0x4e94914f0000, 0x44c1ff2520000, 0xc4200443c0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/fs-v1-multipart.go:718 +0x102
created by github.com/minio/minio/cmd.NewFSObjectLayer
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/fs-v1.go:153 +0x61a

rax    0xfffffffffffffffc
rbx    0x1fc38
rcx    0x45b9f3
rdx    0x0
rdi    0x1aed5e0
rsi    0x0
rbp    0xc42049dee8
rsp    0xc42049dea0
r8     0x0
r9     0x0
r10    0xc42049ded8
r11    0x202
r12    0x77587a3b746
r13    0x5d7
r14    0xc420ab69c0
r15    0x1
rip    0x45b9f3
rflags 0x202
cs     0x33
fs     0x0
gs     0x0
```

**Comment by vadmeste** [comment]
@curantes The fix for your issue is merged in master now, is it possible for you to test it ? if you are using Docker you can use this image minio/minio:edge

**Comment by curantes** [comment]
@vadmeste I have upgraded and tested this now and it looks great! thanks for the fix.
