### ISSUE TITLE
Rare crash due to a concurrent map writes

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#5897]
## Expected Behavior
No crash

## Current Behavior
Rare crash

```
fatal error: concurrent map writes

goroutine 2505706 [running]:
runtime.throw(0x112243a, 0x15)
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/panic.go:616 +0x81 fp=0xc4200f1eb0 sp=0xc4200f1e90 pc=0x42cc61
runtime.mapassign(0xf77fe0, 0xc4260962a0, 0xc4200f1f78, 0x11fb5a0)
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/hashmap.go:607 +0x553 fp=0xc4200f1f40 sp=0xc4200f1eb0 pc=0x409da3
github.com/minio/minio/cmd.(*NotificationSys).DeleteBucket.func1(0xc4245f4f30, 0xc4204e6b48, 0x32, 0xc4260962a0, 0x7ffde2a453ba, 0x9, 0xc42501238f, 0xc42021e330)
        /home/minio/vadmeste/gospace/src/github.com/minio/minio/cmd/notification.go:71 +0xf0 fp=0xc4200f1fa0 sp=0xc4200f1f40 pc=0xc49270
runtime.goexit()
        /home/minio/.gimme/versions/go1.10.1.linux.amd64/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200f1fa8 sp=0xc4200f1fa0 pc=0x45a451
created by github.com/minio/minio/cmd.(*NotificationSys).DeleteBucket
        /home/minio/vadmeste/gospace/src/github.com/minio/minio/cmd/notification.go:68 +0x16e
```

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
Running minio-py in full mode multiple times.

```sh
while true; do 
   docker run --net="host" -e SERVER_ENDPOINT=65.xx.xx.xx:9101 -e ACCESS_KEY=minio -e SECRET_KEY=minio123 -e ENABLE_HTTPS=0 -e MINT_MODE=full minio/mint:edge minio-py; 
done
```

## Context
Testing

## Your Environment
All, master

**Comment by harshavardhana** [comment]
Actually i am seeing this too, it is not rare the usage of map inside a go-routine is wrong. - almost all (*notifiationSys) calls are affected by this.

**Comment by krishnasrinivas** [comment]
This is easily reproduced using these steps:

```
krishna@escape:~$ mc events add myminio/test arn:minio:sqs:us-east-1:1:webhook 
Successfully added arn:minio:sqs:us-east-1:1:webhook
krishna@escape:~$ mc events add myminio/test arn:minio:sqs:us-east-1:2:webhook 
Successfully added arn:minio:sqs:us-east-1:2:webhook
krishna@escape:~$ 
```

then do `mc cp /etc/passwd myminio/test/` two times to see the crash

**Comment by harshavardhana** [comment]
Yes @krishnasrinivas it is quite easy to reproduce.

**Comment by krishnasrinivas** [comment]
Still reproducible with the above mentioned steps. (with two event notifiers)

**Comment by krishnasrinivas** [comment]
Here is the panic log:
```
API: SYSTEM(bucket=test, object=passwd)
Time: 12:51:30 PDT 05/09/2018
Error: Post http://localhost:9001: dial tcp 127.0.0.1:9001: connect: connection refused
       EventName=s3:ObjectCreated:Put, targetID=webhook
       1: cmd/notification.go:524:cmd.sendEvent()
       2: cmd/object-handlers.go:769:cmd.objectAPIHandlers.PutObjectHandler()
       3: cmd/api-router.go:77:cmd.(objectAPIHandlers).PutObjectHandler-fm()
       4: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
fatal error: concurrent map writes

goroutine 97 [running]:
runtime.throw(0x113cd39, 0x15)
	/home/krishna/goroot/go/src/runtime/panic.go:616 +0x81 fp=0xc420845d68 sp=0xc420845d48 pc=0x42cc61
runtime.mapassign(0xf8e720, 0xc4201fdf50, 0xc420845f68, 0x112d9a0)
	/home/krishna/goroot/go/src/runtime/hashmap.go:607 +0x553 fp=0xc420845df8 sp=0xc420845d68 pc=0x409da3
github.com/minio/minio/pkg/event.(*TargetList).Send.func1(0xc42051c440, 0xc42045e2c0, 0xc4201fdf50, 0xc4201babef, 0x1, 0xc4201babf1, 0x7, 0x12220e0, 0xc420284240)
	/home/krishna/go/src/github.com/minio/minio/pkg/event/targetlist.go:114 +0x14a fp=0xc420845f98 sp=0xc420845df8 pc=0x7b8dba
runtime.goexit()
	/home/krishna/goroot/go/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420845fa0 sp=0xc420845f98 pc=0x45a451
created by github.com/minio/minio/pkg/event.(*TargetList).Send
	/home/krishna/go/src/github.com/minio/minio/pkg/event/targetlist.go:111 +0x27a
```
