### ISSUE TITLE
Minio server crashes when healing recursively

### ISSUE THREAD

**Issue by rafaelsierra** [minio/minio#5917]
## Expected Behavior
Calling `mc admin heal -r myminio` should not crash the server

## Current Behavior
Server exits with the following message:

```
API: Heal()
Time: 09:55:22 UTC 05/10/2018
RemoteHost: 10.255.0.2
Error: disk not found

       1: cmd/xl-v1-healing.go:111:cmd.healBucket()
       2: cmd/xl-v1-healing.go:82:cmd.xlObjects.HealBucket()
       3: cmd/xl-sets.go:1184:cmd.(*xlSets).HealBucket()
       4: cmd/admin-heal-ops.go:597:cmd.(*healSequence).healBucket()
       5: cmd/admin-heal-ops.go:577:cmd.(*healSequence).healBuckets()
       6: cmd/admin-heal-ops.go:523:cmd.healBuckets)-fm()
       7: cmd/admin-heal-ops.go:516:cmd.(*healSequence).traverseAndHeal.func1()
       8: cmd/admin-heal-ops.go:523:cmd.(*healSequence).traverseAndHeal()
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xc0e063]

goroutine 614 [running]:
github.com/minio/minio/cmd.doTreeWalk(0x121d300, 0xc420182f00, 0xc420502a4a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/tree-walk.go:186 +0x873
github.com/minio/minio/cmd.startTreeWalk.func1(0x121d300, 0xc420182f00, 0xc420502a4a, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/tree-walk.go:259 +0x10a
created by github.com/minio/minio/cmd.startTreeWalk
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/tree-walk.go:257 +0x1c3

```

## Steps to Reproduce (for bugs)

1. Using Docker swarm deploy 2 services with 4 exports each in distributed mode
2. Remove the content from 2 exports inside a single service
3. Use `mc` to heal the missing 2 exports
4. Minio server crashes

## Context
I was trying to move half of the exports to a second server and mount it using NFS, but when I tried to issue the `heal` command the server crashed, then I rolled back to using local disks, removed the same content locally and tried again, with the same crash result (meaning that NFS played no role in the issue).

The server has around 150MB of random files I had laying around on my personal computer, one folder has 530 files.

## Your Environment
* Version used (`minio version`):
```
Version: 2018-05-10T00:00:42Z
Release-Tag: RELEASE.2018-05-10T00-00-42Z
Commit-ID: cc8178cdc4096ebf66fc2f467fd8f3be9ff1b99b
```
* Docker version: 
```
Client:
 Version:       17.12.1-ce
 API version:   1.35
 Go version:    go1.9.4
 Git commit:    3dfb8343b139d6342acfd9975d7f1068b5b1c3d3
 Built: Tue Apr  3 23:37:44 2018
 OS/Arch:       linux/amd64

Server:
 Engine:
  Version:      17.12.1-ce
  API version:  1.35 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   7390fc6/17.12.1-ce
  Built:        Tue Apr  3 23:38:52 2018
  OS/Arch:      linux/amd64
  Experimental: false

```
* Environment name and version: Minio was the only thing running inside a docker swarm environment
* Server type and version: Amazon default Linux AMI on a micro instance: 
* Operating System and version (`uname -a`): `Linux 4.14.33-51.37.amzn1.x86_64 #1 SMP Thu May 3 20:07:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Link to your project: [docker-swarm.yml](https://gist.github.com/rafaelsierra/eab0e3d06cfcdfb169a1179a2022371c) being used with `docker stack deploy`

**Comment by rafaelsierra** [comment]
Probaly introduced by 6d5f2a43910b722b43c76f6a896e731978a17118, the issue does not happen when using `RELEASE.2018-05-04T23-13-12Z`
