### ISSUE TITLE
Minio and S3 handle list_objects_v2 with a blank ContinuationToken differently

### ISSUE THREAD

**Issue by zackelan** [minio/minio#5931]
Repro:

```
$ docker run -d --name minio -p 9000:9000 \
  -e "MINIO_ACCESS_KEY=access_key" \
  -e "MINIO_SECRET_KEY=secret_key" \
  minio/minio server /data
$ python3
>>> import boto3
>>> minio = boto3.client('s3', endpoint_url='http://localhost:9000', aws_access_key_id='access_key', aws_secret_access_key='secret_key')
>>> minio.create_bucket(Bucket='test')
>>> minio.list_objects_v2(Bucket='test', ContinuationToken='')
{'ResponseMetadata': {'RequestId': '152E9E3A911F7F45', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'accept-ranges': 'bytes', 'content-security-policy': 'block-all-mixed-content', 'content-type': 'application/xml', 'server': 'Minio/RELEASE.2018-05-11T00-29-24Z (linux; amd64)', 'vary': 'Origin', 'x-amz-request-id': '152E9E3A911F7F45', 'x-xss-protection': '"1; mode=block"', 'date': 'Mon, 14 May 2018 20:54:58 GMT', 'transfer-encoding': 'chunked'}, 'RetryAttempts': 0}, 'IsTruncated': False, 'Name': 'test', 'Prefix': '', 'Delimiter': '', 'MaxKeys': 1000, 'KeyCount': 0}
```

vs.

```
>>> s3 = boto3.client('s3', aws_access_key_id='redacted', aws_secret_access_key='redacted')
>>> s3.list_objects_v2(Bucket='some-bucket', ContinuationToken='')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zack/.venv/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/zack/.venv/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidArgument) when calling the ListObjectsV2 operation: The continuation token provided is incorrect
>>> s3.list_objects_v2(Bucket='some-bucket')
(actual list objects response)
```

So Minio ignores ContinuationToken when it's the empty string, whereas S3 barfs on it and returns an error.

I don't know what the goal is with regards to exact compatibility with the S3 API...feel free to wontfix this if compatibility at this level is a non-goal.

I think Minio's current behavior is arguably better and more user-friendly, but this caused a small issue for us when developing against Minio locally and then deploying to production and targeting "real" S3.

Environment:
- Minio RELEASE.2018-05-11T00-29-24Z
- boto3 1.7.19
- Python 3.6.4

**Comment by harshavardhana** [comment]
> I don't know what the goal is with regards to exact compatibility with the S3 API...feel free to wontfix this if compatibility at this level is a non-goal.

We should be compatible, looks like this is a recent addition. ContinuationToken was allowed to be empty previously in AWS S3.  We will fix it.
