### ISSUE TITLE
Nil pointer reference if accessed too quickly on startup

### ISSUE THREAD

**Issue by bmerry** [minio/minio#6324]
I use minio inside a unit test that fires up an minio server for the test and then uses keeps trying to make HTTP connections until one succeeds, so that it knows when the server is up and ready for the test. However, in our CI environment I think this is hitting a race condition where the HTTP server starts serving before minio is fully ready, leading to a nil pointer deference.

## Expected Behavior
An HTTP call at any time should not crash the server.

## Current Behavior
Using 2018-08-21T00-37-20Z I get this stack trace:
```
2018-08-21 16:03:12.605644 I | http: panic serving 127.0.0.1:55484: runtime error: invalid memory address or nil pointer dereference
18:03:12 goroutine 28 [running]:
18:03:12 net/http.(*conn).serve.func1(0xc4201a21e0)
18:03:12 	/opt/go/src/net/http/server.go:1726 +0xd0
18:03:12 panic(0x12767e0, 0x2029710)
18:03:12 	/opt/go/src/runtime/panic.go:502 +0x229
18:03:12 github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:771 +0x93
18:03:12 panic(0x12767e0, 0x2029710)
18:03:12 	/opt/go/src/runtime/panic.go:502 +0x229
18:03:12 github.com/minio/minio/cmd.(*PolicySys).IsAllowed(0x0, 0xc420044011, 0xa, 0x146d4a7, 0x13, 0x0, 0x0, 0xc42038e270, 0x1, 0x0, ...)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/policy.go:80 +0x42
18:03:12 github.com/minio/minio/cmd.checkRequestAuthType(0x15902a0, 0xc42038e210, 0xc420186200, 0x146d4a7, 0x13, 0x0, 0x0, 0x0, 0x0, 0x4fca59)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:177 +0x2aa
18:03:12 github.com/minio/minio/cmd.objectAPIHandlers.ListBucketsHandler(0x14bc288, 0x14bc280, 0x15892a0, 0xc4202464c0, 0xc420186200)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/bucket-handlers.go:198 +0x195
18:03:12 github.com/minio/minio/cmd.(objectAPIHandlers).ListBucketsHandler-fm(0x15892a0, 0xc4202464c0, 0xc420186200)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:116 +0x57
18:03:12 net/http.HandlerFunc.ServeHTTP(0xc4205175e0, 0x15892a0, 0xc4202464c0, 0xc420186200)
18:03:12 	/opt/go/src/net/http/server.go:1947 +0x44
18:03:12 github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200bbd60, 0x15892a0, 0xc4202464c0, 0xc420186200)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0xdc
18:03:12 github.com/minio/minio/cmd.requestIDHeaderHandler.ServeHTTP(0x157eaa0, 0xc4200bbd60, 0x15892a0, 0xc4202464c0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:742 +0x9e
18:03:12 github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1580c00, 0xc420512c50, 0x15892a0, 0xc4202464c0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:757 +0xdc
18:03:12 github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc420517600, 0x1580c80, 0xc420512c60, 0x15892a0, 0xc4202464c0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:628 +0x88
18:03:12 github.com/minio/minio/cmd.rateLimit.ServeHTTP(0xc420506a50, 0x1580a80, 0xc420517620, 0x15892a0, 0xc4202464c0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:722 +0x123
18:03:12 github.com/minio/minio/cmd.pathValidityHandler.ServeHTTP(0x1580ba0, 0xc420517640, 0x15892a0, 0xc4202464c0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:615 +0x1b8
18:03:12 github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1580b80, 0xc420512c80, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:554 +0xba
18:03:12 github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1580b20, 0xc420512c90, 0x50004000000, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:71 +0xde
18:03:12 github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1580c20, 0xc420517660, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:96 +0xa7
18:03:12 github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1580be0, 0xc420512ca0, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x8a
18:03:12 github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1580ae0, 0xc420512cb0, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:248 +0x92
18:03:12 github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1580bc0, 0xc420512cc0, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:306 +0x78
18:03:12 github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1580b60, 0xc420512cd0, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:275 +0x73
18:03:12 github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1580aa0, 0xc420512ce0, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:376 +0x1af
18:03:12 github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190 +0xfe
18:03:12 net/http.HandlerFunc.ServeHTTP(0xc420517700, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/opt/go/src/net/http/server.go:1947 +0x44
18:03:12 github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1581c00, 0xc420517700, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:505 +0xd2
18:03:12 github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1580c60, 0xc420512d50, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:12 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:287 +0x157
18:03:12 github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1580a60, 0xc420512d60, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:13 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:139 +0xa7
18:03:13 github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1580c40, 0xc420512d70, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:13 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:774 +0x8d
18:03:13 github.com/minio/minio/cmd/http.(*Server).Start.func1(0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:13 	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:114 +0xe7
18:03:13 net/http.HandlerFunc.ServeHTTP(0xc42000a0c0, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:13 	/opt/go/src/net/http/server.go:1947 +0x44
18:03:13 net/http.serverHandler.ServeHTTP(0xc420112240, 0x158ed20, 0xc4201ae0e0, 0xc420344800)
18:03:13 	/opt/go/src/net/http/server.go:2694 +0xbc
18:03:13 net/http.(*conn).serve(0xc4201a21e0, 0x15901e0, 0xc4203828c0)
18:03:13 	/opt/go/src/net/http/server.go:1830 +0x651
18:03:13 created by net/http.(*Server).Serve
18:03:13 	/opt/go/src/net/http/server.go:2795 +0x27b
```

## Possible Solution
I've never written Go so I might have it all wrong, but these lines https://github.com/minio/minio/blob/7d7e21aebb159d1ab84906b548eee6e9bc54750a/cmd/server-main.go#L301-L303 seem like they are too early and should move down to after globals including `globalPolicySys` have been initialised.

## Steps to Reproduce (for bugs)
Annoyingly, I can't seem to get the timing right to reproduce this on my dev machine in a standalone test, even when running the same Docker image that runs on our CI server. But the basic approach is
1. Create an empty directory to hold config and another to hold data.
2. Set environment variables MINIO_BROWSER=off, MINIO_ACCESS_KEY, MINIO_SECRET_KEY.
3. Run `minio server --address 127.0.0.1:<port> -C <configdir> <datadir>`.
4. At the same time, make HEAD requests to `http://127.0.0.1:<port>` as fast as possible.

## Context
Unit testing

## Your Environment
* Version used (`minio version`):
Release-Tag: RELEASE.2018-08-18T03-49-57Z
Commit-ID: 9f14433cbd4bde157b00c2afe3228bac0fe1f9d9
* Environment name and version (e.g. nginx 1.9.1): Python 3.5.2 with requests 2.8.1
* Server type and version: Ubuntu 16.04
* Operating System and version (`uname -a`): `Linux kryton 4.15.0-32-generic #35~16.04.1-Ubuntu SMP Fri Aug 10 21:54:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by harshavardhana** [comment]
@bmerry we will fix it - this is related to startup issue on certain subsystems.
