### ISSUE TITLE
Can not set bucket policy via JS API

### ISSUE THREAD

**Issue by ilya-sharonov** [minio/minio#6476]
Minio JavaScript API SDK constantly throws errors when trying to set bucket policy.
```javascript
const Minio = require('minio');

var minioClient = new Minio.Client({
    endPoint: 'localhost',
    port: 9000,
    useSSL: false,
    accessKey: 'AIOUR3892NG79230GN832AKHP',
    secretKey: 'HL8sllkjdsf83mvKda30fnldl3rho',
});

const policy = {
    Version: '2018-09-15',
    Id: 'test-policy-1',
    Statement: [
        {
            Action: ['s3:GetObject'],
            Effect: 'Allow',
            Principal: {
                AWS: ['*'],
            },
            Resource: ['arn:aws:s3:::nextbucket/*'],
        },
    ],
};

minioClient.makeBucket('nextbucket', 'region-1', function(err) {
    if (err) return console.log('Error creating bucket.', err);

    console.log('Bucket created successfully in "region-1".');

    minioClient.setBucketPolicy('nextbucket', JSON.stringify(policy), function(err) {
        if (err) throw err;
        console.log('Bucket policy set');
    });
});

```

## Expected Behavior
The code above should make a new bucket and set anonymous access policy to it.

## Current Behavior
The code above successfully creates a new bucket but fails to set policy with the following error:
```javascript
S3Error: Policy has invalid resource.
    at Object.parseError (.../minio-js/node_modules/minio/dist/main/xml-parsers.js:86:11)
    at .../minio-js/node_modules/minio/dist/main/transformers.js:159:22
    at DestroyableTransform._flush (.../minio-js/node_modules/minio/dist/main/transformers.js:89:10)
    at DestroyableTransform.<anonymous> (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at finishMaybe (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
```

## Steps to Reproduce (for bugs)

1. Install and run latest mini via docker
2. Setup js app environment
3. Run the code above

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by harshavardhana** [comment]
Thanks for the reproducer @ilya-sharonov we will take a look

**Comment by kanagarajkm** [comment]
@ilya-sharonov can you remove `JSON.stringify` and check again. The code should look like following

```javascript
    minioClient.setBucketPolicy('nextbucket', policy, function(err) {
        if (err) throw err;
        console.log('Bucket policy set');
    });
```

**Comment by kanagarajkm** [comment]
@ilya-sharonov  please ignore my previous comment.

Version on the policy object should be  `2012-10-17`

So the policy would be 
```javascript
const policy = {
    Version: '2012-10-17',
    Id: 'test-policy-1',
    Statement: [
        {
            Action: ['s3:GetObject'],
            Effect: 'Allow',
            Principal: {
                AWS: ['*'],
            },
            Resource: ['arn:aws:s3:::nextbucket/*'],
        },
    ],
};
```

**Comment by ilya-sharonov** [comment]
Hi @kanagarajkm 
Adjusted the policy following your instructions, still getting the same error:
```javascript
S3Error: Policy has invalid resource.
    at Object.parseError (.../minio-js/node_modules/minio/dist/main/xml-parsers.js:104:13)
    at .../minio-js/node_modules/minio/dist/main/transformers.js:159:22
    at DestroyableTransform._flush (.../minio-js/node_modules/minio/dist/main/transformers.js:89:10)
    at DestroyableTransform.<anonymous> (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:135:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
    at DestroyableTransform.emit (events.js:208:7)
    at finishMaybe (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:371:12)
    at endWritable (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:378:3)
    at DestroyableTransform.Writable.end (.../minio-js/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:356:5)
```
Attempt to set the same policy using Java API SDK was successful - everything worked as expected.

**Comment by kanagarajkm** [comment]
After further analysis, i found that the problem is with `Id: 'test-policy-1'`. When the `Id` field contains ` `(space) or `-`, its failing. But the same works fine on AWS S3.

For example, following json works on AWS S3 and not on minio
```json
{
    "Version": "2012-10-17",
    "Id": "abc-test",
    "Statement": [
        {
            "Action": [
                "s3:GetObject"
            ],
            "Effect": "Allow",
            "Principal": {
                "AWS": [
                    "*"
                ]
            },
            "Resource": [
                "arn:aws:s3:::mk-test11/*"
            ]
        }
    ]
}
```

I have tested with minio-js, minio-go, and minio-java. All of them are failing for above json.

@ilya-sharonov if you remove the `-` from  `Id` it should work. Can you pleas provide the sample Java code where its working fine.

**Comment by ilya-sharonov** [comment]
@kanagarajkm 
Thanks a lot for your research and comments, I managed to set policy using JS SDK with the following object:
```javascript
const policy = {
    Version: '2012-10-17',
    Statement: [
        {
            Action: ['s3:GetBucketLocation', 's3:ListBucket'],
            Effect: 'Allow',
            Principal: {
                AWS: ['*'],
            },
            Resource: ['arn:aws:s3:::nextbucket'],
        },
        {
            Action: ['s3:GetObject'],
            Effect: 'Allow',
            Principal: {
                AWS: ['*'],
            },
            Resource: ['arn:aws:s3:::nextbucket/*'],
        },
    ],
};
```
I removed 'Id' parameter completely, and added another statement object with 's3:GetBucketLocation' and 's3:ListBucket' actions. This made the trick.
Interesting thing is that if I omit statement object with 's3:GetBucketLocation' and 's3:ListBucket' actions, then setBucketPolicy() exits with no errors but the policy is not set. Probably it's worth adding a note to the docs about such behavior or fix it if that's not expected.
Working java code for policy manipulation is the following:
```java
import java.io.IOException;
import java.security.NoSuchAlgorithmException;
import java.security.InvalidKeyException;

import org.xmlpull.v1.XmlPullParserException;

import io.minio.MinioClient;
import io.minio.errors.MinioException;

public class SetPolicy {
    /**
     * MinioClient.setBucketPolicy() example.
     */
    public static void main(String[] args)
            throws IOException, NoSuchAlgorithmException, InvalidKeyException, XmlPullParserException {
        try {
            /* play.minio.io for test and development. */
            MinioClient minioClient = new MinioClient("http://localhost:9000", "AIOUR3892NG79230GN832AKHP",
                    "HL8sllkjdsf83mvKda30fnldl3rho");

            /* Amazon S3: */
            // MinioClient minioClient = new MinioClient("https://s3.amazonaws.com",
            // "YOUR-ACCESSKEYID",
            // "YOUR-SECRETACCESSKEY");

            StringBuilder builder = new StringBuilder();
            builder.append("{\n");
            builder.append("    \"Statement\": [\n");
            builder.append("        {\n");
            builder.append("            \"Action\": [\n");
            builder.append("                \"s3:GetBucketLocation\",\n");
            builder.append("                \"s3:ListBucket\"\n");
            builder.append("            ],\n");
            builder.append("            \"Effect\": \"Allow\",\n");
            builder.append("            \"Principal\": \"*\",\n");
            builder.append("            \"Resource\": \"arn:aws:s3:::nextbucket\"\n");
            builder.append("        },\n");
            builder.append("        {\n");
            builder.append("            \"Action\": \"s3:GetObject\",\n");
            builder.append("            \"Effect\": \"Allow\",\n");
            builder.append("            \"Principal\": \"*\",\n");
            builder.append("            \"Resource\": \"arn:aws:s3:::nextbucket/*\"\n");
            builder.append("        }\n");
            builder.append("    ],\n");
            builder.append("    \"Version\": \"2012-10-17\"\n");
            builder.append("}\n");
            minioClient.setBucketPolicy("nextbucket", builder.toString());
        } catch (MinioException e) {
            System.out.println("Error occurred: " + e);
        }
    }
}
```

**Comment by harshavardhana** [comment]
This is an issue our implemented Sid values can be any UTF characters we only support alphanumeric. Sending a fix.
