### ISSUE TITLE
Request go routine can crash in notification subsystem code

### ISSUE THREAD

**Issue by vadmeste** [minio/minio#6484]
## Expected Behavior
No go routine crash in the log

## Current Behavior
```

http: panic serving 10.98.94.201:50898: runtime error: invalid memory address or nil pointer dereference
goroutine 100829 [running]:
net/http.(*conn).serve.func1(0xc420595cc0)
        /opt/go/src/net/http/server.go:1726 +0xd0
panic(0x12788a0, 0x202b760)
        /opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:771 +0x93
panic(0x12788a0, 0x202b760)
        /opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.(*NotificationSys).send(0x0, 0xc42082d8f6, 0x3, 0xc42082d4d8, 0x3, 0xc42082d850, 0x8, 0x0, 0x0, 0xc420681a60, ...)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/notification.go:420 +0x3a
github.com/minio/minio/cmd.(*peerRPCReceiver).SendEvent(0x2065bc8, 0xc4207f61c0, 0xc42082d94e, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/peer-rpc-server.go:145 +0x10a
reflect.Value.call(0xc4203f0f00, 0xc4201864c0, 0x13, 0x145a060, 0x4, 0xc42089cf70, 0x3, 0x3, 0x119a6c0, 0x0, ...)
        /opt/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4203f0f00, 0xc4201864c0, 0x13, 0xc42089cf70, 0x3, 0x3, 0xc420a03540, 0x1, 0x1)
        /opt/go/src/reflect/value.go:308 +0xa4
github.com/minio/minio/cmd/rpc.(*Server).call(0xc4203eb020, 0xc42082d0b0, 0xe, 0xc4208f7500, 0x643, 0x643, 0xc42072a2a0, 0xc420521180, 0x6b22b8)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc/server.go:204 +0x755
github.com/minio/minio/cmd/rpc.(*Server).ServeHTTP(0xc4203eb020, 0x158b640, 0xc4205e4580, 0xc420330200)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc/server.go:245 +0x1c2
github.com/minio/minio/cmd/rpc.(*Server).ServeHTTP-fm(0x158b640, 0xc4205e4580, 0xc420330200)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/admin-rpc-server.go:86 +0x48
net/http.HandlerFunc.ServeHTTP(0xc420369860, 0x158b640, 0xc4205e4580, 0xc420330200)
        /opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc420184be0, 0x158b640, 0xc4205e4580, 0xc420330200)
        /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0xdc
github.com/minio/minio/cmd.requestIDHeaderHandler.ServeHTTP(0x1580e40, 0xc420184be0, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:742 +0x9e
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1582fa0, 0xc420473b20, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:757 +0xdc
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc4201820c0, 0x1583020, 0xc420473b30, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:628 +0x88
github.com/minio/minio/cmd.rateLimit.ServeHTTP(0xc420461630, 0x1582e20, 0xc4201820e0, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:722 +0x123
github.com/minio/minio/cmd.pathValidityHandler.ServeHTTP(0x1582f40, 0xc420182100, 0x158b640, 0xc4205e4580, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:615 +0x1b8
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1582f20, 0xc420473b50, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:554 +0xba
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1582ec0, 0xc420473b60, 0x50004000000, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:71 +0xde
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1582fc0, 0xc420182120, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:96 +0xa7
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1582f80, 0xc420473b70, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x8a
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1582e80, 0xc420473b80, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:248 +0x92
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1582f60, 0xc420473b90, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:306 +0x78
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1582f00, 0xc420473ba0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:275 +0x73
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1582e40, 0xc420473bb0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:376 +0x1af
github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc4201821e0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1583fa0, 0xc4201821e0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:505 +0xd2
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1583000, 0xc420473c20, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:287 +0x157
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1582e00, 0xc420473c30, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:139 +0xa7
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1582fe0, 0xc420473c40, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:774 +0x8d
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:115 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc4202196a0, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /opt/go/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc420104b40, 0x15910c0, 0xc42066ca80, 0xc42017ba00)
        /opt/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420595cc0, 0x1592580, 0xc420410ec0)
        /opt/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /opt/go/src/net/http/server.go:2795 +0x27b
```

## Possible Solution
Do not know yet

## Steps to Reproduce (for bugs)
We need to ask @curantes for a reliable way to reproduce

## Context
@curantes reported this bug

## Regression
Do not know

## Your Environment
RELEASE.2018-09-01T00-38-25Z

**Comment by harshavardhana** [comment]
This is perhaps because object layer is not yet initialized ? This is fixed in the latest releases IMO.

**Comment by vadmeste** [comment]
> This is perhaps because object layer is not yet initialized ? This is fixed in the latest releases IMO.

The user was using RELEASE.2018-09-01T00-38-25Z and I took a look on commits since the version, nothing seems to be related to this issue

**Comment by harshavardhana** [comment]
> /opt/go/src/runtime/panic.go:502 +0x229 github.com/minio/minio/cmd.(*NotificationSys).send(0x0, 0xc42082d8f6, 0x3, 0xc42082d4d8, 0x3, 0xc42082d850, 0x8, 0x0, 0x0, 0xc420681a60, ...) /q/.q/sources/gopath/src/github.com/minio/minio/cmd/notification.go:420 +0x3a github.com/minio/minio/cmd.(*peerRPCReceiver).SendEvent(0x2065bc8, 0xc4207f61c0, 0xc420

This is perhaps also because the targetList map is empty which I don't know how.

**Comment by curantes** [comment]
@vadmeste thanks for your help, let me know if you need any further info.

**Comment by harshavardhana** [comment]
> panic(0x12788a0, 0x202b760) /opt/go/src/runtime/panic.go:502 +0x229 github.com/minio/minio/cmd.(*NotificationSys).send(0x0, 0xc42082d8f6, 0x3, 0xc42082d4d8, 0x3, 0xc42082d850, 0x8, 0x0, 0x0, 0xc420681a60, ...) /q/.q/sources/gopath/src/github.com/minio/minio/cmd/notification.go:420 +0x3a github.com/minio/minio/cmd.(*peerRPCReceiver).SendEvent(0x2065bc8, 0xc4207f61c0, 0xc42082d94e, 0x0, 0x0) /q/.q/sources/gopath/src/github.com/minio/minio/cmd/peer-rpc-server.go:145 +0x10a reflect.Value.call(0xc4203f0f00, 0xc4201864c0, 0x13, 0x145a060, 0x4, 0xc42089cf70, 0x3, 0x3

This has happened because notificationSys is `nil` and SendEvent was sent without object layer being initialized.
