### ISSUE TITLE
MissingHeaderBodySeparatorDefect Warning After Uploading Empty File with Boto3

### ISSUE THREAD

**Issue by Jimmyscene** [minio/minio#6540]
Hey guys,

Got a really weird issue concerning communication between the boto3 python client and a minio server.

When using the boto3 client in conjunction with a minio server, I get the following error when attempting to upload a non-empty file, after having uploaded an empty file
```
Failed to parse headers (url=http://localhost:9000/test/not_empty_file): [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nAccept-Ranges: bytes\r\nContent-Security-Policy: block-all-mixed-content\r\nEtag: "28e802510bdb8f3b4c6fd1f3d53c93e6"\r\nServer: Minio/RELEASE.2018-09-25T21-34-43Z (linux; amd64)\r\nVary: Origin\r\nX-Amz-Request-Id: 15589D208CE73388\r\nX-Xss-Protection: 1; mode=block\r\nDate: Fri, 28 Sep 2018 16:27:15 GMT\r\nContent-Length: 0\r\n\r\n'
```

To be clear, steps to reproduce:
1. touch empty_file
2. echo 'stuff' >> not_empty_file
3. Connect to minio server with boto3 client
4. Upload empty file (No error)
5. Upload not_empty_file 
6. Wait ~30 seconds
7 Receive urllib3.exceptions.HeaderParsingError

Workaround:
If you reinstantiate the boto3 client before each file upload, the warning does not occur. This seems inefficient though.

I've attached a test script here to demonstrate that this is only reproducible with the minio server and the boto3 client. I've tested with https://hub.docker.com/r/scality/s3server/ to check that this isn't an issue with the boto3 client, and the error is not present there.

I'm not really sure where to begin investigating this, or if this is the correct place to report it. 

Test Python Script to reproduce(Please replace variables at the top with your secets/endpoints/access keys)

```python
import boto3
import os
import shutil
import logging
from minio import Minio
from botocore.exceptions import ClientError

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - [%(levelname)s] %(message)s'
)
#  docker run -p 9000:9000 minio/minio  server /data
logger = logging.getLogger('runner')
MINIO_SERVER_ACCESS_KEY = "PINWVTJ9BS3YC9B2CQIO"
MINIO_SERVER_SECRET_KEY = "x5/NY/WZYYOD7ZgDfR6wdNKsDAwWexhNvRLaTvCg"
MINIO_ENDPOINT = "localhost:9000"
# docker run -it 8000:8000 scality/s3server
S3_SERVER_ACCESS_KEY = "accessKey1"
S3_SERVER_SECRET_KEY = "verySecretKey1"
S3_SERVER_ENDPOINT = "http://localhost:8000"


def getBotoClient():
    return boto3.client(
        's3',
        endpoint_url="http://" + MINIO_ENDPOINT,
        aws_access_key_id=MINIO_SERVER_ACCESS_KEY,
        aws_secret_access_key=MINIO_SERVER_SECRET_KEY
    )


def getMinioClient():
    return Minio(
        MINIO_ENDPOINT,
        access_key=MINIO_SERVER_ACCESS_KEY,
        secret_key=MINIO_SERVER_SECRET_KEY,
        secure=False
    )


def getS3Client():
    return boto3.client(
        's3',
        endpoint_url=S3_SERVER_ENDPOINT,
        aws_access_key_id=S3_SERVER_ACCESS_KEY,
        aws_secret_access_key=S3_SERVER_SECRET_KEY
    )


def create_files(directory):
    os.makedirs(directory, exist_ok=True)
    f = open(os.path.join(directory, "empty_file"), 'w+')
    f.close()
    f = open(os.path.join(directory, "not_empty_file"), 'w+')
    f.write("literally anything")
    f.close()
    return ["empty_file", "not_empty_file"]


def delete_files(directory):
    shutil.rmtree(directory)


def getClients():
    return [
        ("MINIO CLIENT WITH MINIO SERVER", getMinioClient(), True),
        ("BOTO CLIENT WITH MINIO SERVER", getBotoClient(), False),
        ("BOTO CLIENT WITH S3Server", getS3Client(), False)
    ]


directory = "foo"
files = create_files(directory)

for test, mc, minio in getClients():
    logger.info(test)
    task_id = "test"
    if minio:
        if not mc.bucket_exists(task_id):
            mc.make_bucket(task_id)
    else:
        try:
            mc.head_bucket(Bucket=task_id)
        except ClientError as e:
            mc.create_bucket(Bucket=task_id)

    for file in files:
        logger.info("Putting " + file)
        if minio:
            mc.fput_object(task_id, file, '%s/%s' % (directory, file))
        else:
            mc.upload_file('%s/%s' % (directory, file), task_id, file)
    if minio:
        [_ for _ in mc.remove_objects(task_id, (x.object_name for x in mc.list_objects(task_id)))]
        mc.remove_bucket(task_id)
    else:
        mc.delete_objects(
            Bucket=task_id,
            Delete={
                'Objects':
                [
                    {'Key': x['Key']}
                    for x in mc.list_objects(Bucket=task_id)['Contents']
                ]
            }
        )
        mc.delete_bucket(Bucket=task_id)

delete_files(directory)
```

The output I get from this is:

```
2018-09-28 12:27:15,796 - [INFO] MINIO CLIENT WITH MINIO SERVER
2018-09-28 12:27:15,803 - [INFO] Putting empty_file
2018-09-28 12:27:15,808 - [INFO] Putting not_empty_file
2018-09-28 12:27:15,824 - [INFO] BOTO CLIENT WITH MINIO SERVER
2018-09-28 12:27:15,840 - [INFO] Putting empty_file
2018-09-28 12:27:15,852 - [INFO] Putting not_empty_file
2018-09-28 12:27:15,862 - [WARNING] Failed to parse headers (url=http://localhost:9000/test/not_empty_file): [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nAccept-Ranges: bytes\r\nContent-Security-Policy: block-all-mixed-content\r\nEtag: "28e802510bdb8f3b4c6fd1f3d53c93e6"\r\nServer: Minio/RELEASE.2018-09-25T21-34-43Z (linux; amd64)\r\nVary: Origin\r\nX-Amz-Request-Id: 15589D208CE73388\r\nX-Xss-Protection: 1; mode=block\r\nDate: Fri, 28 Sep 2018 16:27:15 GMT\r\nContent-Length: 0\r\n\r\n'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/connectionpool.py", line 396, in _make_request
    assert_header_parsing(httplib_response.msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/urllib3/util/response.py", line 66, in assert_header_parsing
    raise HeaderParsingError(defects=defects, unparsed_data=unparsed_data)
urllib3.exceptions.HeaderParsingError: [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nAccept-Ranges: bytes\r\nContent-Security-Policy: block-all-mixed-content\r\nEtag: "28e802510bdb8f3b4c6fd1f3d53c93e6"\r\nServer: Minio/RELEASE.2018-09-25T21-34-43Z (linux; amd64)\r\nVary: Origin\r\nX-Amz-Request-Id: 15589D208CE73388\r\nX-Xss-Protection: 1; mode=block\r\nDate: Fri, 28 Sep 2018 16:27:15 GMT\r\nContent-Length: 0\r\n\r\n'
2018-09-28 12:28:16,882 - [INFO] BOTO CLIENT WITH S3Server
2018-09-28 12:28:17,015 - [INFO] Putting empty_file
2018-09-28 12:28:17,080 - [INFO] Putting not_empty_file
```

**Comment by kannappanr** [comment]
@Jimmyscene Thanks for filing this issue. We will try to reproduce the issue and fix it.

**Comment by kannappanr** [comment]
@Jimmyscene There is a pending PR for this issue in boto core. https://github.com/boto/botocore/pull/1328

**Comment by Jimmyscene** [comment]
@kannappanr Gotcha, I'll follow up with those guys then. Thanks! I'll close this out

**Comment by harshavardhana** [comment]
```diff
diff -pruN /usr/local/lib/python3.6/dist-packages/botocore/awsrequest.py.orig /usr/local/lib/python3.6/dist-packages/botocore/awsrequest.py--- /usr/local/lib/python3.6/dist-packages/botocore/awsrequest.py.orig	2018-09-28 17:11:16.481518995 -0700
+++ /usr/local/lib/python3.6/dist-packages/botocore/awsrequest.py	2018-09-28 17:07:33.089465131 -0700
@@ -115,6 +115,8 @@ class AWSConnection(object):
                 break
 
     def _send_request(self, method, url, body, headers, *args, **kwargs):
+        if headers.get('Content-Length') == '0':
+            headers.pop('Expect')
         self._response_received = False
         if headers.get('Expect', b'') == b'100-continue':
             self._expect_header_set = True
```

This is the fix @Jimmyscene FWIW

**Comment by antonio-antuan** [comment]
got the same warning with minio/minio:latest docker image
```
612315 2019-09-25T12:40:16.+0000 WARNING Failed to parse headers (url=http://127.0.0.1:9000/gg-server/media/sports/teams/26e36213-09dd-4e69-83b8-1bf9e35ccdcc.png): [MissingHeaderBodySeparatorDefect()], unparsed data: 'HTTP/1.1 200 OK\r\nAccept-Ranges: bytes\r\nContent-Length: 0\r\nContent-Security-Policy: block-all-mixed-content\r\nETag: "67528ce266ded257124ea9751fb16491"\r\nServer: MinIO/RELEASE.2019-09-18T21-55-05Z\r\nVary: Origin\r\nX-Amz-Request-Id: 15C7AED31D37A061\r\nX-Xss-Protection: 1; mode=block\r\nDate: Wed, 25 Sep 2019 12:40:16 GMT\r\n\r\n'
```
and code freezes for a minute after that warning

**Comment by harshavardhana** [comment]
@aCLr this is a botocore bug, follow up with them to get it merged and fixed.
