### ISSUE TITLE
Error on accessing to cacheObjects.GetObjectNInfo

### ISSUE THREAD

**Issue by takumn** [minio/minio#6602]
When minio gateway runs with disk cache enabled, it cannot seem to handle `GetObject` requests for objects have not been cached. Perhaps the same problem as mentioned in [#6551](https://github.com/minio/minio/pull/6561#pullrequestreview-161299858)?

## Expected Behavior

`GetObject` requests for objects have not been cached are successfully handled.

## Current Behavior

Errors occur during handling requests.

```
2018-10-10 14:29:45.748785 I | http: panic serving 127.0.0.1:51353: runtime error: invalid memory address or nil pointer dereference
goroutine 318 [running]:
net/http.(*conn).serve.func1(0xc420365f40)
	/opt/go/src/net/http/server.go:1726 +0xd0
panic(0x1eccfc0, 0x2cb9a90)
	/opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:771 +0x93
panic(0x1eccfc0, 0x2cb9a90)
	/opt/go/src/runtime/panic.go:502 +0x229
github.com/minio/minio/cmd.cacheObjects.GetObjectNInfo(0xc4201626c0, 0xc4201626e0, 0xc4202dcdb0, 0x1, 0x1, 0x0, 0x211f978, 0x211f980, 0x211f988, 0x211f990, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-cache.go:240 +0x56f
github.com/minio/minio/cmd.(CacheObjectLayer).GetObjectNInfo-fm(0x21fa960, 0xc42080b020, 0xc42018d7a5, 0x19, 0xc42018d7bf, 0x48, 0x0, 0xc42080acc0, 0x1, 0x0, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:159 +0xc5
github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler(0x211f940, 0x211f938, 0x21f37a0, 0xc42064a980, 0xc420185300)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:358 +0x651
github.com/minio/minio/cmd.(objectAPIHandlers).GetObjectHandler-fm(0x21f37a0, 0xc42064a980, 0xc420185300)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/api-router.go:68 +0x57
net/http.HandlerFunc.ServeHTTP(0xc42024bc00, 0x21f37a0, 0xc42064a980, 0xc420185300)
	/opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4200c22d0, 0x21f37a0, 0xc42064a980, 0xc420185300)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107 +0xdc
github.com/minio/minio/cmd.requestIDHeaderHandler.ServeHTTP(0x21e87a0, 0xc4200c22d0, 0x21f37a0, 0xc42064a980, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:742 +0x9e
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x21eab60, 0xc420347c40, 0x21f37a0, 0xc42064a980, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:757 +0xdc
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc42000ae60, 0x21eabe0, 0xc420347c50, 0x21f37a0, 0xc42064a980, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:628 +0x88
github.com/minio/minio/cmd.rateLimit.ServeHTTP(0xc420186e10, 0x21ea9e0, 0xc42000ae80, 0x21f37a0, 0xc42064a980, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:722 +0x123
github.com/minio/minio/cmd.pathValidityHandler.ServeHTTP(0x21eab00, 0xc42000aea0, 0x21f37a0, 0xc42064a980, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:615 +0x1b8
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x21eaae0, 0xc420347c70, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:554 +0xba
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x21eaa80, 0xc420347c80, 0x50004000000, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:71 +0xde
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x21eab80, 0xc42000aec0, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:96 +0xa7
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x21eab40, 0xc420347c90, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/crossdomain-xml-handler.go:51 +0x8a
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x21eaa40, 0xc420347ca0, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:248 +0x92
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x21eab20, 0xc420347cb0, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:306 +0x78
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x21eaac0, 0xc420347cc0, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:275 +0x73
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x21eaa00, 0xc420347cd0, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:376 +0x1af
github.com/minio/minio/vendor/github.com/rs/cors.(*Cors).Handler.func1(0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/rs/cors/cors.go:190 +0xfe
net/http.HandlerFunc.ServeHTTP(0xc42000af60, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/opt/go/src/net/http/server.go:1947 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x21ebc00, 0xc42000af60, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:505 +0xd2
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x21eabc0, 0xc420347d40, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/auth-handler.go:287 +0x157
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x21ea9c0, 0xc420347d50, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:139 +0xa7
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x21eaba0, 0xc420347d60, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/generic-handlers.go:774 +0x8d
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x21f9260, 0xc4201a6000, 0xc420184e00)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/http/server.go:115 +0xe7
net/http.HandlerFunc.ServeHTTP(0xc4202d60a0, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/opt/go/src/net/http/server.go:1947 +0x44
net/http.serverHandler.ServeHTTP(0xc42011e480, 0x21f9260, 0xc4201a6000, 0xc420184e00)
	/opt/go/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc420365f40, 0x21fa8a0, 0xc4200b26c0)
	/opt/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
	/opt/go/src/net/http/server.go:2795 +0x27b
```

## Possible Solution

Though `cacheObjects.GetObjectNInfo` is not initialized in [`newServerCacheObjects`](https://github.com/minio/minio/blob/66d911653f17b9b180493e3e21c6131170741dcf/cmd/disk-cache.go#L955), it is referred in [`objectAPIHandlers.SelectObjectContentHandler`](https://github.com/minio/minio/blob/66d911653f17b9b180493e3e21c6131170741dcf/cmd/object-handlers.go#L159). 

I tried [the patch](https://github.com/takumn/minio/commit/56f58e60258ca760e842a8a924ca19939435c76e), which seems to resolve the problem, but minio gateway hanged when requesting objects have been cached but expired. So I took goroutine stacktrace for it.

```
1 @ 0x102d9cb 0x102da73 0x100577e 0x10054ab 0x1a55168 0x1a54f4a 0x1b0dbce 0x1b0e7df 0x1af6f30 0x1ab9934 0x1abdbec 0x1bb9a48 0x1bbd865 0x1b20050 0x1bbba37 0x12e6364 0x1317540 0x1b0218e 0x1bd9223 0x1b0230c 0x1bd9a03 0x1b015b4 0x1bcedac 0x1b02031 0x1bd8b5c 0x1b014c2 0x1bd8903 0x1b01085 0x1bd6a63 0x1afef6f 0x1bd93cc 0x1aff0f8
#	0x1a55167	github.com/minio/minio/vendor/github.com/minio/lsync.(*LRWMutex).lockLoop+0x147	/Users/takumn/go/src/github.com/minio/minio/vendor/github.com/minio/lsync/lrwmutex.go:85
#	0x1a54f49	github.com/minio/minio/vendor/github.com/minio/lsync.(*LRWMutex).GetLock+0x39	/Users/takumn/go/src/github.com/minio/minio/vendor/github.com/minio/lsync/lrwmutex.go:55
#	0x1b0dbcd	github.com/minio/minio/cmd.(*nsLockMap).lock+0x1fd				/Users/takumn/go/src/github.com/minio/minio/cmd/namespace-lock.go:167
#	0x1b0e7de	github.com/minio/minio/cmd.(*lockInstance).GetLock+0xde				/Users/takumn/go/src/github.com/minio/minio/cmd/namespace-lock.go:288
#	0x1af6f2f	github.com/minio/minio/cmd.(*FSObjects).DeleteObject+0xaf			/Users/takumn/go/src/github.com/minio/minio/cmd/fs-v1.go:962
#	0x1ab9933	github.com/minio/minio/cmd.(*cacheFSObjects).Delete+0x73			/Users/takumn/go/src/github.com/minio/minio/cmd/disk-cache-fs.go:293
#	0x1abdbeb	github.com/minio/minio/cmd.cacheObjects.GetObjectNInfo+0xdcb			/Users/takumn/go/src/github.com/minio/minio/cmd/disk-cache.go:225
#	0x1bbd864	github.com/minio/minio/cmd.CacheObjectLayer.GetObjectNInfo-fm+0xc4		/Users/takumn/go/src/github.com/minio/minio/cmd/object-handlers.go:159
#	0x1b2004f	github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler+0x65f		/Users/takumn/go/src/github.com/minio/minio/cmd/object-handlers.go:358
#	0x1bbba36	github.com/minio/minio/cmd.objectAPIHandlers.GetObjectHandler-fm+0x56		/Users/takumn/go/src/github.com/minio/minio/cmd/api-router.go:68
#	0x12e6363	net/http.HandlerFunc.ServeHTTP+0x43						/usr/local/Cellar/go/1.11/libexec/src/net/http/server.go:1964
#	0x131753f	github.com/minio/minio/vendor/github.com/gorilla/mux.(*Router).ServeHTTP+0xdf	/Users/takumn/go/src/github.com/minio/minio/vendor/github.com/gorilla/mux/mux.go:107
#	0x1b0218d	github.com/minio/minio/cmd.requestIDHeaderHandler.ServeHTTP+0x9d		/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:742
#	0x1b0230b	github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP+0xdb			/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:757
#	0x1b015b3	github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP+0x83		/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:628
#	0x1b02030	github.com/minio/minio/cmd.rateLimit.ServeHTTP+0x120				/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:722
#	0x1b014c1	github.com/minio/minio/cmd.pathValidityHandler.ServeHTTP+0x1c1			/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:615
#	0x1b01084	github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP+0xb4			/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:554
#	0x1afef6e	github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP+0xce		/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:71
#	0x1aff0f7	github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP+0xa7		/Users/takumn/go/src/github.com/minio/minio/cmd/generic-handlers.go:96
```

I considered existence of incomplete lockings, and tried [another patch](https://github.com/takumn/minio/commit/9efb79ee2be81abfc06ec6e6892242a5d52a4c30). This seems to resolve the hangs, but I'm not sure this approach is correct.

## Steps to Reproduce (for bugs)

1. Remove cache directories if exist.
2. Run minio gateway with disk cache enabled.
3. Request `GetObject` APIs for objects which exist on backend.

Example for `awscli`:
```
AWS_ACCESS_KEY_ID=$MINIO_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$MINIO_SECRET_KEY aws --endpoint=http://127.0.0.1:9000 s3 cp s3://bucket-name/prefix/object-name .
```

## Your Environment

 * Version used (`minio version`): `2018-10-06T00:15:16Z RELEASE.2018-10-06T00-15-16Z 66d911653f17b9b180493e3e21c6131170741dcf`
 * Operating System and version (uname -a): `Darwin mbppro 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64`

**Comment by kannappanr** [comment]
@takumn Thanks for filing this issue with steps to reproduce the issue. We will reproduce the issue and get back to you.
