### ISSUE TITLE
Signature mismatch on text/plain put object (C# AWS SDK)

### ISSUE THREAD

**Issue by petertiedemann** [minio/minio#6971]
Using the C# AWS SDK a PutObject request that succeeds against S3 itself, causes a signature exception.

## Expected Behavior
Expecting Put operation to succeed

## Current Behavior
```
Unhandled Exception: Amazon.S3.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your key and signing method. ---> Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
   at Amazon.Runtime.HttpWebRequestMessage.GetResponseAsync(CancellationToken cancellationToken) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 539
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
   at Amazon.Runtime.Internal.RedirectHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.Unmarshaller.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext)
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 60
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 212
   at Amazon.Runtime.Internal.ErrorHandler.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 104
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CredentialsRetriever.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\Handlers\CredentialsRetriever.cs:line 98
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.RetryHandler.InvokeAsync[T](IExecutionContext executionContext) in E:\JenkinsWorkspaces\v3-trebuchet-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 137
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.CallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Amazon.Runtime.Internal.MetricsHandler.InvokeAsync[T](IExecutionContext executionContext)
   at Program.MainAsync() in C:\Users\peter\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 33
   at Program.Main(String[] args) in C:\Users\peter\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 12
```

## Steps to Reproduce (for bugs)
I am testing with the following snippet, directly based on the C# example on minio.io
```
using Amazon.S3;
using System;
using System.Threading.Tasks;
using Amazon;
using Amazon.S3.Model;

class Program {
  private const string accessKey = ..;
  private const string secretKey = ..;

  static void Main( string[] args ) {
    Task.Run( MainAsync ).GetAwaiter().GetResult();
  }

  private static async Task MainAsync() {
    var config = new AmazonS3Config {
      RegionEndpoint = RegionEndpoint.USEast1, 
      ServiceURL = "http://localhost:9000",
      ForcePathStyle = true 
    };
    var amazonS3Client = new AmazonS3Client( accessKey, secretKey, config );

    await amazonS3Client.DeleteBucketAsync( "mybucket" );
    await amazonS3Client.PutBucketAsync( "mybucket" );

    var req = new PutObjectRequest {
      BucketName = "mybucket",
      ContentType = "text/plain",
      ContentBody = "42",
      Key = "prefix#lala/key1"
    };

    var p = await amazonS3Client.PutObjectAsync( req );
  }
}
```

## Context
I have an existing code base that supports (amongst others) S3, and i would like to support Minio for on-premise, and i am trying to find out if i can do that by using the existing S3 based implementation. I got some basic tests working, but the above operation fails.

## Your Environment
* Version used (`minio version`): 2018-12-13T02:04:19Z
* Environment name and version (e.g. nginx 1.9.1): n/a
* Server type and version: n/a
* Operating System and version (`uname -a`): Windows 10
* Link to your project: n/a

I have no customized the minio configuration at all, simply downloaded it and started it using: `.\minio.exe server C:\temp\minio1 C:\temp\minio2`

**Comment by kannappanr** [comment]
@petertiedemann Thanks for this issue and the example code. Also, are you seeing this issue only with this `keyname`? What is the behavior if you use a `keyname` named say `object`?

**Comment by kannappanr** [comment]
@petertiedemann I think this is the same issue as explained in https://github.com/minio/minio/issues/6548#issuecomment-435494339

This is a bug with `AWS .NET SDK`

**Comment by petertiedemann** [comment]
@kannappanr Thanks for the quick reply. Doesn't sound like something that is easily fixed. I guess it is better to simply support Minio's own API directly, probably also less brittle going forward.

**Comment by harshavardhana** [comment]
We already have C# SDK which you can migrate to https://github.com/minio/minio-dotnet

**Comment by petertiedemann** [comment]
@harshavardhana Thanks for the tip, however i had already noticed. It looks to be very close to the S3 API, so it will be pretty trivial to implement it as an alternative storage backend.

**Comment by harshavardhana** [comment]
> @harshavardhana Thanks for the tip, however i had already noticed. It looks to be very close to the S3 API, so it will be pretty trivial to implement it as an alternative storage backend.

There is no reason to write a separate backend minio-dotnet SDK works the same way with S3 and Minio - so you simply have to remove AWS SDK requirement unless you use other AWS services.

**Comment by petertiedemann** [comment]
@harshavardhana What i mean with "backend" is that we have an interface through which we abstract away the underlying storage (ie Azure Blob Storage, local disk, zip file, S3, etc). Implementing this interface against the Minio API is what looks pretty trivial. Originally i had planned to simply use our S3 implementation of this interface, but because of the above bug, i looked into using your C# SDK directly, and it is actually much nicer than the AWS SDK :)

But i guess your point is that i could simply use the Minio based implementation to talk to both AWS and Minio?

**Comment by harshavardhana** [comment]
Yes that is correct Minio SDK can talk to AWS and Minio

**Comment by kannappanr** [comment]
Closing this issue as we already have #6548 open to track the issue with AWS .Net SDK.
