### ISSUE TITLE
Spark writing to minio error

### ISSUE THREAD

**Issue by thbeh** [minio/minio#7020]
## Current Behavior
Lately I have testing PySpark and using minio as my object storage. While I can read files in Minio S3 and uses minio s3 as spark history logs but whenever I try to write to minio it give java.lang.NullPointerException event though the folder is created with /thbeh/test_1/_temporary/0/

## Steps to Reproduce (for bugs)
df1 = spark.createDataFrame([('john', 33)], ('name', 'age'))
df1.write.json('s3a://thbeh/test_1')

## Context
Not able to establish PySpark->Minio S3 integration

## Your Environment
kubernetes v1.11
Docker version 17.03.3-ce, build e19b718
minio/minio-latest (4 days ago)
Ubuntu 16.04.5 LTS
Apache Spark 2.2.0

## Snippet of error:-
Py4JJavaError: An error occurred while calling o1323.json.
: java.lang.NullPointerException
	at com.amazonaws.util.BinaryUtils.fromHex(BinaryUtils.java:70)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1410)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.createEmptyObject(S3AFileSystem.java:1191)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.createFakeDirectory(S3AFileSystem.java:1168)
	at org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:871)
	at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:1881)
	at org.apache.hadoop.mapreduce.lib.output.FileOutputCommitter.setupJob(FileOutputCommitter.java:313)
	at org.apache.spark.internal.io.HadoopMapReduceCommitProtocol.setupJob(HadoopMapReduceCommitProtocol.scala:124)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply$mcV$sp(FileFormatWriter.scala:176)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$$anonfun$write$1.apply(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:65)
	at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:173)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:145)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.datasources.DataSource.writeInFileFormat(DataSource.scala:438)
	at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:474)
	at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:48)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
	at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
	at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
	at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:610)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
	at org.apache.spark.sql.DataFrameWriter.json(DataFrameWriter.scala:488)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)

**Comment by harshavardhana** [comment]
Null pointer exception looks like a setup issue on your end, we have successfully used spark even to write to Minio.

**Comment by thbeh** [comment]
This is how I define my spark config, if that's the setup you are refering to -
from pyspark import SparkContext
from pyspark.sql import SparkSession

sc=spark

hadoop_conf=sc._jsc.hadoopConfiguration()
hadoop_conf.set("fs.s3a.impl","org.apache.hadoop.fs.s3a.S3AFileSystem")
hadoop_conf.set("fs.s3a.endpoint","http://192.168.34.202:9000")
hadoop_conf.set("fs.s3a.access.key","minio")
hadoop_conf.set("fs.s3a.secret.key","minio123")
hadoop_conf.set("fs.s3a.path.style.access","True")

**Comment by harshavardhana** [comment]
```
~ pyspark --jars "spark/jars/hadoop-aws-2.8.5.jar,spark/jars/httpclient-4.5.3.jar,spark/jars/aws-java-sdk-core-1.11.234.jar,spark/jars/aws-java-sdk-kms-1.11.234.jar,spark/jars/aws-java-sdk-1.11.234.jar,spark/jars/aws-java-sdk-s3-1.11.234.jar,spark/jars/joda-time-2.9.9.jar"
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
2018-12-24 16:40:03 WARN  Utils:66 - Your hostname, backspace resolves to a loopback address: 127.0.1.1; using 10.0.0.17 instead (on interface wlp59s0)
2018-12-24 16:40:03 WARN  Utils:66 - Set SPARK_LOCAL_IP if you need to bind to another address
2018-12-24 16:40:03 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
Welcome to
      ____              __
     / __/__  ___ _____/ /__
    _\ \/ _ \/ _ `/ __/  '_/
   /__ / .__/\_,_/_/ /_/\_\   version 2.3.1
      /_/

Using Python version 2.7.15rc1 (default, Nov 12 2018 14:31:15)
SparkSession available as 'spark'.
>>> df1 = spark.createDataFrame([('john', 33)], ('name', 'age'))
>>> df1.write.json('s3a://vadmeste/test_1')
>>>                                             
```

```
~  mc ls myminio/vadmeste/test_1/
[2018-12-24 16:40:43 PST]     0B _SUCCESS
[2018-12-24 16:40:36 PST]     0B part-00000-6f35ac4b-af55-42fb-99fa-273460c03662-c000.json
[2018-12-24 16:40:40 PST]    25B part-00003-6f35ac4b-af55-42fb-99fa-273460c03662-c000.json
```

Seems to be working fine @thbeh - this is why I said your local configuration might be wrong.

**Comment by thbeh** [comment]
Thanks. I am running from jupyter, so will have a look at jupyter conf.

**Comment by thbeh** [comment]
I guess I know where the issue lies. Using the above example with all jars relate to hadoop 2.8.5 works without any issue. My issues are my code have dependencies on hadoop 2.7.4 and thus only aws-sdk 1.7.4 . Looking back at my histories it did work few months back probably with an older version of Minio but couldn't detect which version it was.

**Comment by thbeh** [comment]
it has to do with generating a null value for MD5Checksum, something similar to #5232

**Comment by harshavardhana** [comment]
Those were actually bugs in aws-sdk-java https://github.com/minio/minio/issues/5232#issuecomment-347074296 - you should use the later versions such as 1.11.234 used in my test.

**Comment by nitisht** [comment]
@thbeh closing this based on previous comments, looks like there is no action from Minio server perspective.

**Comment by skonto** [comment]
@nitisht with Spark 3.0.0 I get:
```
com.amazonaws.services.s3.model.AmazonS3Exception: Status Code: 405, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: Method Not Allowed
```
I understand that it should fail but It would be helpful if default spark hadoop versions were supported. 
Spark on K8s could benefit from this and I know 2.7.4 is quite old ;).In general storage on K8s is a bit of an issue to setup so minio could be helpful, especially for short cycles like dev/test in the big data world.

**Comment by harshavardhana** [comment]
Spark 3.0.0 should work fine, not sure what is the issue here. Can you open a new issue with more details and also enable MINIO_HTTP_TRACE=/dev/stdout environment variable to trace the API calls.

**Comment by skonto** [comment]
@harshavardhana 
Im using the old lib versions (because I dont want to build Spark without hadoop, not so convenient)
```
--packages com.amazonaws:aws-java-sdk:1.7.4,org.apache.hadoop:hadoop-aws:2.7.6 \
--conf spark.hadoop.fs.s3a.access.key=minio \
--conf spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem \
--conf spark.hadoop.fs.s3a.secret.key=minio123  \
--conf spark.hadoop.fs.s3a.path.style.access=True \
--conf spark.hadoop.fs.s3a.endpoint=http://localhost:9000
```
So I guess I hit the same issue.

**Comment by MollyGu-CN** [comment]
@harshavardhana
Same issue here.
spark-2.4.0-bin-hadoop2.7 with latest Minio version in local 
`Version: 2019-02-26T19:51:46Z  
Release-Tag: RELEASE.2019-02-26T19-51-46Z
Commit-ID: 78d116c487278350406e8957d7d35e47caa963d6`

`spark-shell --jars "/Users/juan/IdeaProjects/test_cos/target/testLib/hadoop-aws-2.7.7.jar,/Users/juan/IdeaProjects/test_cos/target/testLib/aws-java-sdk-1.7.4.jar,/Users/juan/IdeaProjects/test_cos/target/testLib/httpclient-4.2.5.jar,/Users/juan/IdeaProjects/test_cos/target/testLib/joda-time-2.10.jar"`

scala code:
`val data = Array(1, 2, 3, 4, 5)`
`val distData = sc.parallelize(data)`
`distData.saveAsTextFile("s3a://test/test-write")`

Error here:
`java.lang.NullPointerException
  at com.amazonaws.util.BinaryUtils.fromHex(BinaryUtils.java:70)
  at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1410)
  at org.apache.hadoop.fs.s3a.S3AFileSystem.createEmptyObject(S3AFileSystem.java:1191)
  at org.apache.hadoop.fs.s3a.S3AFileSystem.createFakeDirectory(S3AFileSystem.java:1168)
  at org.apache.hadoop.fs.s3a.S3AFileSystem.mkdirs(S3AFileSystem.java:871)
  at org.apache.hadoop.fs.FileSystem.mkdirs(FileSystem.java:1881)
  at   ...`

Can you help point out how can we get an older version minio that can work with hadoop 2.7 version?
