### ISSUE TITLE
s3.copy raises error NoSuchKey but s3.get_objects works with the same key

### ISSUE THREAD

**Issue by nazarred** [minio/minio#7240]
Hi all! I'm trying to change metadata, namely 'ContentDisposition'. This is my script:
```python
import boto3

AWS_S3_ENDPOINT_URL = 'https://storage.blah.com:9001'
AWS_S3_USE_SSL = True

AWS_S3_BUCKET = 'blah-blah'


session = boto3.session.Session()
s3 = session.client(
    's3',
    endpoint_url=AWS_S3_ENDPOINT_URL,
    use_ssl=AWS_S3_USE_SSL,
)

this_key_works   =     'projects/3ceda660-f475-43db-8438-d3a53bdd7e37/artifact/140aa3c1-68c6-43c7-83fc-49924499aca4/data_files/06603020-e508-4085-b660-bdff043185bc.poq'
this_key_doesnt_work = 'projects/95cdf19e-dc63-4f73-948d-bd117a84fbd9/artifact/ab00b39b-8e19-4fad-a47b-65afaa678da6/data_files/bca04fca-29c3-4568-8062-21ff146d43b9.HCN'
file_name = 'some_name.poq'

obj = s3.get_object(Bucket=AWS_S3_BUCKET, Key=this_key_doesnt_work)
print(obj)

s3.copy(
    {'Bucket': AWS_S3_BUCKET, 'Key': this_key_doesnt_work},
    AWS_S3_BUCKET,
    this_key_doesnt_work,
    ExtraArgs={
        "ContentDisposition": f'attachment; filename={file_name}',
        "MetadataDirective": "REPLACE",
    }
)

```
It's works perfect when I use `this_key_works` but when I try to change metadata for `this_key_doesnt_work` I recieved error:
`botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.`
However this key exists because I received object when called `s3.get_object()`. Error raises only when I call s3.copy(). 

Outputs:

```
{'ResponseMetadata': {'RequestId': '1582F03A74D0814F', 'HostId': '', 'HTTPStatusCode': 200, 'HTTPHeaders': {'accept-ranges': 'bytes', 'content-length': '3164828', 'content-security-policy': 'block-all-mixed-content', 'content-type': 'application/octet-stream', 'etag': '"00000000000000000000000000000000-1"', 'last-modified': 'Fri, 27 Jul 2018 02:00:46 GMT', 'server': 'Minio/DEVELOPMENT.GOGET (linux; amd64)', 'vary': 'Origin', 'x-amz-request-id': '1582F03A74D0814F', 'x-xss-protection': '1; mode=block', 'date': 'Wed, 13 Feb 2019 13:42:35 GMT'}, 'RetryAttempts': 0}, 'AcceptRanges': 'bytes', 'LastModified': datetime.datetime(2018, 7, 27, 2, 0, 46, tzinfo=tzutc()), 'ContentLength': 3164828, 'ETag': '"00000000000000000000000000000000-1"', 'ContentType': 'application/octet-stream', 'Metadata': {}, 'Body': <botocore.response.StreamingBody object at 0x7f61dfb5ad30>}
Traceback (most recent call last):
  File "/home/nazar/starnavi/dron/lidarmill-backend/fix_s3_names.py", line 29, in <module>
    "MetadataDirective": "REPLACE",
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/boto3/s3/inject.py", line 379, in copy
    return future.result()
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/s3transfer/copies.py", line 286, in _main
    CopySource=copy_source, Bucket=bucket, Key=key, **extra_args)
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/nazar/starnavi/dron/lidarmill-backend/venv/lib/python3.6/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.NoSuchKey: An error occurred (NoSuchKey) when calling the CopyObject operation: The specified key does not exist.

Process finished with exit code 1
```
Outputs of `journalctl -u minio`
```
Feb 13 14:51:54 storage minio[25078]: API: CopyObject(bucket=blah-blah, object=projects/95cdf19e-dc63-4f73-948d-bd117a84fbd9/artifact/ab00b39b-8e19-4fad-a47b-65afaa678da6/data_files/bca04fca-29c3-4568-8062-21ff146d43b9.HCN)
Feb 13 14:51:54 storage minio[25078]: Time: 14:51:54 CET 02/13/2019
Feb 13 14:51:54 storage minio[25078]: RequestID: 1582F0BCA8B6C66B
Feb 13 14:51:54 storage minio[25078]: RemoteHost: 46.200.20.169
Feb 13 14:51:54 storage minio[25078]: UserAgent: Boto3/1.7.84 Python/3.6.7 Linux/4.4.0-31-generic Botocore/1.10.84
Feb 13 14:51:54 storage minio[25078]: Error: file not found
Feb 13 14:51:54 storage minio[25078]:        1: /build/minio/src/go/src/github.com/minio/minio/cmd/logger/logger.go:294:logger.LogIf()
Feb 13 14:51:54 storage minio[25078]:        2: /build/minio/src/go/src/github.com/minio/minio/cmd/fs-v1.go:437:cmd.(*FSObjects).CopyObject()
Feb 13 14:51:54 storage minio[25078]:        3: /build/minio/src/go/src/github.com/minio/minio/cmd/object-handlers.go:918:cmd.objectAPIHandlers.CopyObjectHandler()
Feb 13 14:51:54 storage minio[25078]:        4: /build/minio/src/go/src/github.com/minio/minio/cmd/api-router.go:70:cmd.objectAPIHandlers.CopyObjectHandler-fm()
Feb 13 14:51:54 storage minio[25078]:        5: net/http/server.go:1964:http.HandlerFunc.ServeHTTP()

```

## Your Environment

* Version used (`minio version`):
Version: DEVELOPMENT.GOGET
Release-Tag: DEVELOPMENT.GOGET
Commit-ID: DEVELOPMENT.GOGET
* Server type and version:
* Operating System and version (`uname -a`):
Linux storage 4.17.2-1-ARCH #1 SMP PREEMPT Sat Jun 16 11:08:59 UTC 2018 x86_64 GNU/Linux

**Comment by nitisht** [comment]
Thanks @nazarred we'll try this and get back to you

**Comment by Praveenrajmani** [comment]
Hi @nazarred ,

This worked fine for me.

The steps i did were

- Uploaded a large file to the key you provided. 

- `mc stat myminio/blahblah/projects/95cdf19e-dc63-4f73-948d-bd117a84fbd9/artifact/ab00b39b-8e19-4fad-a47b-65afaa678da6/data_files/bca04fca-29c3-4568-8062-21ff146d43b9.HCN` gave me

![image](https://user-images.githubusercontent.com/5410427/52729987-5498f180-2fe0-11e9-8a39-56aee86a54ee.png)

- I ran the below script

```
import boto3

AWS_S3_ENDPOINT_URL = 'http://192.168.0.120:9000'
AWS_S3_USE_SSL = False

AWS_S3_BUCKET = 'blahblah'


session = boto3.session.Session()
s3 = session.client(
    's3',
    endpoint_url=AWS_S3_ENDPOINT_URL,
    use_ssl=AWS_S3_USE_SSL,
)

this_key_works   =     'projects/3ceda660-f475-43db-8438-d3a53bdd7e37/artifact/140aa3c1-68c6-43c7-83fc-49924499aca4/data_files/06603020-e508-4085-b660-bdff043185bc.poq'
this_key_doesnt_work = 'projects/95cdf19e-dc63-4f73-948d-bd117a84fbd9/artifact/ab00b39b-8e19-4fad-a47b-65afaa678da6/data_files/bca04fca-29c3-4568-8062-21ff146d43b9.HCN'
file_name = 'some_name.poq'

#obj = s3.get_object(Bucket=AWS_S3_BUCKET, Key=this_key_doesnt_work)
#print(obj)

s3.copy(
    {'Bucket': AWS_S3_BUCKET, 'Key': this_key_doesnt_work},
    AWS_S3_BUCKET,
    this_key_doesnt_work,
    ExtraArgs={
        "ContentDisposition": f'altered_attachment; filename={file_name}',
        "MetadataDirective": "REPLACE",
    }
)
```

- Now i can see the metadata been altered. The mc stat on the key gives me

![image](https://user-images.githubusercontent.com/5410427/52730260-eef93500-2fe0-11e9-8d5a-50a7d6516719.png)

Am i missing something? As far as i know, there are no such restriction in the object keys. So, this should work flawlessly.

**Comment by nazarred** [comment]
Thanks @Praveenrajmani !
Looks like you did all proper. But I'm not surprised that you can't reproduce this error. I'll try to give more explanations.

We use Minio more than one year. A few days ago when we try to download some old files we saw that some files have strange names like `bca04fca-29c3-4568-8062-21ff146d43b9.HCN` instead `fine_name.HCN`. 
When I called S3.get_object() for this file I saw that `ContentDisposition` missing in the metadata. If I add it (e. g. "ContentDisposition": 'altered_attachment; filename=fine_name.HCN') file will download with name fine_name.HCN.
In our project, we store file name and related S3 key in the database so I created the script which checks if the file has  `ContentDisposition` fields and if hasn't - adds this field by S3.copy() method. 
This script fixed a lot of files (maybe about a half) but for some files, it raises error NoSuchKey and it weird because of S3.get_object() works fine for the same keys.

**Comment by nazarred** [comment]
BTW this my outputs of `mc stat`
![image](https://user-images.githubusercontent.com/34417569/52736043-92dae480-2fd1-11e9-8819-36ef712a4ca7.png)

and for the same file if I use S3.get_object:

```
{
    'ResponseMetadata': {
        'RequestId': '1582F03A74D0814F',
        'HostId': '',
        'HTTPStatusCode': 200,
        'HTTPHeaders': {
            'accept-ranges': 'bytes',
            'content-length': '3164828',
            'content-security-policy': 'block-all-mixed-content',
            'content-type': 'application/octet-stream',
            'etag': '"00000000000000000000000000000000-1"',
            'last-modified': 'Fri, 27 Jul 2018 02:00:46 GMT',
            'server': 'Minio/DEVELOPMENT.GOGET (linux; amd64)',
            'vary': 'Origin',
            'x-amz-request-id': '1582F03A74D0814F',
            'x-xss-protection': '1; mode=block',
            'date': 'Wed, 13 Feb 2019 13:42:35 GMT'
        },
        'RetryAttempts': 0
    },
    'AcceptRanges': 'bytes',
    'LastModified': datetime.datetime(2018, 7, 27, 2, 0, 46, tzinfo = tzutc()),
    'ContentLength': 3164828,
    'ETag': '"00000000000000000000000000000000-1"',
    'ContentType': 'application/octet-stream',
    'Metadata': {},
    'Body': < botocore.response.StreamingBody object at 0x7f61dfb5ad30 >
}
```

**Comment by kannappanr** [comment]
@nazarred What is your minio setup? Is it Distributed? If you do not have enough `WriteQuorum`, but enough `ReadQuorum`, this might happen.

**Comment by kannappanr** [comment]
@nazarred Can you try copying this file into some other object name say `A` and then copy it back to this name again? You can delete the object `A` then.

**Comment by Praveenrajmani** [comment]
@nazarred Did you try kannappan's suggestion ?

**Comment by nazarred** [comment]
> @nazarred Can you try copying this file into some other object name say `A` and then copy it back to this name again? You can delete the object `A` then.

@kannappanr @Praveenrajmani  Your solution works for me!!! Thank you very much!!!

**Comment by kannappanr** [comment]
@nazarred You should definitely heal your `minio` setup.  Closing this issue as answered. Please feel free to reach out to us if you have more questions.
