### ISSUE TITLE
Crash reported in net/http request

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#7359]
** not using the template ** 

```
panic: runtime error: slice bounds out of range
goroutine 37542302 [running]:
bytes.(*Buffer).Bytes(...)
	/opt/go/src/bytes/buffer.go:55
net/http.NewRequest(0x15b6293, 0x4, 0xc0299c94a0, 0x5b, 0x17b8200, 0xc001c6e070, 0x0, 0x0, 0x0)
	/opt/go/src/net/http/request.go:826 +0x81a
net/http.(*Client).Post(0xc00054b980, 0xc0299c94a0, 0x5b, 0x0, 0x0, 0x17b8200, 0xc001c6e070, 0xc0004c7130, 0xb, 0x0)
	/opt/go/src/net/http/client.go:764 +0x68
github.com/minio/minio/cmd/rpc.(*Client).Call(0xc000242900, 0x15bf3a5, 0xb, 0x13d22c0, 0xc01e0a7c20, 0x12e0d00, 0xc002333060, 0x0, 0x0)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc/client.go:70 +0x31d
github.com/minio/minio/cmd.(*RPCClient).Call.func1(0xc001288560, 0x40c498)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc.go:215 +0x289
github.com/minio/minio/cmd.(*RPCClient).Call.func2(0x149e540, 0xc0030ec8c0)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc.go:219 +0x3c
github.com/minio/minio/cmd.(*RPCClient).Call(0xc00038d180, 0x15bf3a5, 0xb, 0x17b86e0, 0xc01e0a7c20, 0x12e0d00, 0xc002333060, 0x8, 0xc0203f6840)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/rpc.go:236 +0x12c
github.com/minio/minio/cmd.(*LockRPCClient).RLock(0xc000690110, 0xc001fd1d10, 0x24, 0xc0043309e0, 0x11, 0xc00050eb40, 0x48, 0xc0004c7130, 0xb, 0xc001fd1d40, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/cmd/lock-rpc-client.go:45 +0xc6
github.com/minio/minio/vendor/github.com/minio/dsync.lock.func1(0xc0005bcb40, 0xc001fd1d10, 0x24, 0xc0043309e0, 0x11, 0xc0001143c0, 0xc001fd1d40, 0x2f, 0xc01fca52c0, 0x4, ...)
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:191 +0x1e1
created by github.com/minio/minio/vendor/github.com/minio/dsync.lock
	/q/.q/sources/gopath/src/github.com/minio/minio/vendor/github.com/minio/dsync/drwmutex.go:177 +0x1d2

```

**Comment by harshavardhana** [comment]
The crash is here

```
// Bytes returns a slice of length b.Len() holding the unread portion of the buffer.                                                                           
// The slice is valid for use only until the next buffer modification (that is,                                                                                
// only until the next call to a method like Read, Write, Reset, or Truncate).                                                                                 
// The slice aliases the buffer content at least until the next buffer modification,                                                                           
// so immediate changes to the slice will affect the result of future reads.                                                                                   
func (b *Buffer) Bytes() []byte { return b.buf[b.off:] }  
```

**Comment by harshavardhana** [comment]
Anis reproduced this it looks like an upstream Go issue, for now, @vadmeste to fill in more.

**Comment by vadmeste** [comment]
The upstream issue https://github.com/golang/go/issues/31192

**Comment by harshavardhana** [comment]
This is fixed in MinIO by moving to http1.1 for internode communication.
