### ISSUE TITLE
S3 PutObject ETag using GCS gateway incompatible with aws-sdk-java

### ISSUE THREAD

**Issue by orevial** [minio/minio#7642]
For PUT object requests using java AWS SDK client, Minio transforms the original MD5 eTag returned by GCS into an invalid eTag that fails checksum validator on the client-side.

## Expected Behavior
Minio gateway should forward MD5 eTag "as-is" on PUT object requests when applicable, as per [the spec](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html):

> Objects created by the PUT Object, POST Object, or Copy operation, or through the AWS Management Console, and are encrypted by SSE-S3 or plaintext, have ETags that are an MD5 digest of their object data.

Result example:
* We make a `PutObjectRequest` with a file content of `content`
* GCS returns an eTag corresponding to the MD5 content of the file: `"9a0364b9e99bb480dd25e1f0284c8555"`
* Minio forwards the same MD5 eTag: `"9a0364b9e99bb480dd25e1f0284c8555"`

## Current Behavior
Minio gateway for GCS currently applies 2 transformations to the original MD5 eTag received from GCS:

* [Convert the original MD5 eTag to a CRC32C eTag](https://github.com/minio/minio/blob/master/cmd/gateway/gcs/gateway-gcs.go):
```go
ETag: minio.ToS3ETag(fmt.Sprintf("%d", attrs.CRC32C)),
```
* [Add a `-1` suffix to the transformed eTag](https://github.com/minio/minio/blob/master/cmd/utils.go):
```go
if !strings.HasSuffix(etag, "-1") {
    // Tools like s3cmd uses ETag as checksum of data to validate.
    // Append "-1" to indicate ETag is not a checksum.
    etag += "-1"
}
```

Result example:
* We make a `PutObjectRequest` with a file content of `content`
* GCS returns an eTag corresponding to the MD5 content of the file: `"9a0364b9e99bb480dd25e1f0284c8555"`
* Minio transforms the original MD5 eTag and returns an invalid eTag: `"1638888755-1"`

## Possible Solution
Do not apply eTag transformation on PUT object requests when client is expecting a MD5 hash in the eTag.

## Steps to Reproduce (for bugs)

* Use aws-java-sdk:
```xml
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>s3</artifactId>
    <version>2.5.25</version>
</dependency>
```

* Instantiate a S3 client:
```java
AwsBasicCredentials credentials = AwsBasicCredentials.create(config.getKey(), config.getSecret());
return S3Client.builder()
    .endpointOverride(URI.create(config.getEndpoint()))
    .region(Region.of(config.getRegion()))
    .credentialsProvider(StaticCredentialsProvider.create(credentials))
    .serviceConfiguration(S3Configuration.builder().pathStyleAccessEnabled(true).build())
    .build();
```

* Try a simple PUT object request:
```java
byte[] content = "content".getBytes();
RequestBody requestBody = RequestBody.fromBytes(content);
PutObjectRequest build = PutObjectRequest.builder().bucket(BUCKET).key("test-file").build();
s3Client.putObject(build, requestBody);
```

* Client checksum validation will fail on [this class](https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L125) at `validatePutObjectChecksum` trying to decode an invalid eTag.

Exception thrown:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Invalid base 16 character: '-'). Response Code: 200, Response Text: OK

    at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleSuccessResponse(HandleResponseStage.java:100)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.handleResponse(HandleResponseStage.java:70)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:58)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:41)
    at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:64)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:36)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.doExecute(RetryableStage.java:113)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage$RetryExecutor.execute(RetryableStage.java:86)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:62)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:42)
    at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
    at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:57)
    at software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:37)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)
    at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
    at software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)
    at software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)
    at software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:240)
    at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:96)
    at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:120)
    at software.amazon.awssdk.core.client.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:73)
    at software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:44)
    at software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)
    at software.amazon.awssdk.services.s3.DefaultS3Client.putObject(DefaultS3Client.java:3053)
    at com.airbus.geocloud.dm.client.storage.sync.SyncStorageClientIntegrationTest$Local.simplePut(SyncStorageClientIntegrationTest.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
    at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: Invalid base 16 character: '-'
    at software.amazon.awssdk.utils.internal.Base16Codec.pos(Base16Codec.java:80)
    at software.amazon.awssdk.utils.internal.Base16Codec.decode(Base16Codec.java:66)
    at software.amazon.awssdk.utils.internal.Base16Lower.decode(Base16Lower.java:65)
    at software.amazon.awssdk.services.s3.checksums.ChecksumsEnabledValidator.validatePutObjectChecksum(ChecksumsEnabledValidator.java:131)
    at software.amazon.awssdk.services.s3.internal.handlers.SyncChecksumValidationInterceptor.afterUnmarshalling(SyncChecksumValidationInterceptor.java:88)
```

## Context
Issue reproduced on PUT object requests on both sync and async clients of the v2 version.

## Your Environment
* Version used (`minio version`):
```
Version: 2019-05-02T19:07:09Z
Release-Tag: RELEASE.2019-05-02T19-07-09Z
Commit-ID: 4b858b562a0887e10bfd0414dc87e68f1af31c3a
```
* AWS SDK Java v2.5.25

**Comment by nitisht** [comment]
Thanks for reporting @orevial we'll take a look

**Comment by kannappanr** [comment]
Closed by #7643

**Comment by haneefkassam** [comment]
Sorry for the bump, but I'm noticing a similar issue with the minio server and minio gateway azure.  I'll try to dig into it a bit more in the next few days, but this may be a blocker.  Tried it on the docker build RELEASE.2019-07-24T02-02-23Z, also using v2.5.X of the aws s3 sdk.

**Comment by harshavardhana** [comment]
> Sorry for the bump, but I'm noticing a similar issue with the minio server and minio gateway azure. I'll try to dig into it a bit more in the next few days, but this may be a blocker. Tried it on the docker build RELEASE.2019-07-24T02-02-23Z, also using v2.5.X of the aws s3 sdk.

start the server with `--compat` option if you want AWS S3 behavior @haneefkassam

**Comment by haneefkassam** [comment]
Worked like a charm! (at least for the server...still need to verify with azure).  Thank you! :)

**Comment by haneefkassam** [comment]
> > Sorry for the bump, but I'm noticing a similar issue with the minio server and minio gateway azure. I'll try to dig into it a bit more in the next few days, but this may be a blocker. Tried it on the docker build RELEASE.2019-07-24T02-02-23Z, also using v2.5.X of the aws s3 sdk.
> 
> start the server with `--compat` option if you want AWS S3 behavior @haneefkassam

Worked like a charm! (at least for the server...still need to verify with azure).  Thank you! :)
