### ISSUE TITLE
Unable to verify integrity of data upload

### ISSUE THREAD

**Issue by McPo** [minio/minio#7859]
Any attempt to upload a file above ~5mb using the S3 Transfer Utility (AWS SDK for Android), results in
```
E/MainActivity: java.util.concurrent.ExecutionException: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.
```
## Expected Behavior
The file should successfully upload

## Current Behavior
The file partially uploads ~50-80% and then bombs out with 
```
2019-07-01 16:45:06.843 29592-29652/com.example.emcpoland.miniouploader E/UploadPartTask: Upload part interrupted: com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.
2019-07-01 16:45:06.843 29592-29652/com.example.emcpoland.miniouploader E/nsferNetworkLossHandler: TransferNetworkLossHandler is not created. Please call `TransferNetworkLossHandler.getInstance(Context)` to instantiate it before retrieving
2019-07-01 16:45:06.844 29592-29652/com.example.emcpoland.miniouploader E/UploadPartTask: TransferUtilityException: [com.amazonaws.mobileconnectors.s3.transferutility.TransferUtilityException: TransferNetworkLossHandler is not created. Please call `TransferNetworkLossHandler.getInstance(Context)` to instantiate it before retrieving]
2019-07-01 16:45:06.860 29592-29652/com.example.emcpoland.miniouploader E/UploadPartTask: Encountered error uploading part 
    com.amazonaws.AmazonClientException: Unable to verify integrity of data upload.  Client calculated content hash didn't match hash calculated by Amazon S3.  You may need to delete the data stored in Amazon S3.
        at com.amazonaws.services.s3.AmazonS3Client.uploadPart(AmazonS3Client.java:3681)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:60)
        at com.amazonaws.mobileconnectors.s3.transferutility.UploadPartTask.call(UploadPartTask.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

## Possible Solution
Unknown

## Steps to Reproduce (for bugs)
* Setup Docker instance with and SSL Cert
```
docker run -d -p 443:9000 --name minio \
  -e "MINIO_ACCESS_KEY=XXXXX" \
  -e "MINIO_SECRET_KEY=XXXXXXXXX" \
  -v /mnt/data:/data \
  -v /mnt/config:/home/minio/.minio \
  minio/minio:RELEASE.2019-06-19T18-24-42Z  server /data
```
* Open browser and navigate to minio UI
* Upload file <5mb using TransferUtility of AWS Android SDK
* Verify file successfully uploaded
* Attempt to upload file >5mb. It will fail.
```
override fun onActivityResult(requestCode: Int, resultCode: Int, resultData: Intent?) {
        if (requestCode == READ_REQUEST_CODE && resultCode == Activity.RESULT_OK) {
            resultData?.data?.also { uri ->
                Log.i(TAG, "Uri: ${uri} |||| ${uri.path}")


                val credentials = BasicAWSCredentials("XXXXX", "XXXXXXXXX")
                val clientConfiguration = ClientConfiguration()
                clientConfiguration.signerOverride ="AWSS3V4SignerType"

                val options = S3ClientOptions.builder()
                    .setPathStyleAccess(true)
                    .build()

                val s3Client = AmazonS3Client(credentials, clientConfiguration)
                s3Client.endpoint = "https://XXX.XXX.XXX"
                s3Client.setS3ClientOptions(options)

                val transferUtility = TransferUtility.builder()
                    .context(applicationContext)
                    .s3Client(s3Client)
                    .build()

                val file = getFileFromURI(uri)

                transferUtility.upload(
                    "uploads",
                    file?.name,
                    file
                ).setTransferListener(object : TransferListener {

                    override fun onStateChanged(id: Int, state: TransferState) {
                        if (TransferState.COMPLETED === state) {
                            Snackbar.make(window.decorView.rootView, "File uploaded", Snackbar.LENGTH_LONG)
                                .show()
                        }
                    }

                    override fun onProgressChanged(id: Int, bytesCurrent: Long, bytesTotal: Long) {
                        val percentDonef = bytesCurrent.toFloat() / bytesTotal.toFloat() * 100
                        val percentDone = percentDonef.toInt()

                        Log.i(
                            TAG,
                            "ID:$id bytesCurrent: $bytesCurrent bytesTotal: $bytesTotal $percentDone%"
                        )
                    }

                    override fun onError(id: Int, ex: Exception) {
                        Log.e(TAG, ex.toString())
                        Snackbar.make(window.decorView.rootView, "An error occured", Snackbar.LENGTH_LONG)
                            .show()
                    }
                })
            }
        }
    }
```

## Context
Unable to upload large files using the AWS SDK + minio. (Prefer to use the AWS SDK, as I would assume that it probably has more reliable uploads than the Minio SDK)

## Regression
Unknown

## Your Environment
* RELEASE.2019-06-19T18-24-42Z
* Docker
* HTTPS
* Android Oreo 8.1.0/8.0.0 (BlackBerry / Emulator)
* com.amazonaws:aws-android-sdk-s3:2.13.6

## Notes
Ive also attempted

**Comment by harshavardhana** [comment]
Use --compat mode for S3 compatible md5sum hex generation.

**Comment by McPo** [comment]
Thanks for the quick reply. That seems to have done it.
And of course I now notice the other issues where you mentioned the `--compat`.

Would it be worth potentially adding it to the documentation (I dont seem to be able to find it mentioned) or even the initial stdout when the server starts. It sort of lures you into a false sense of security that everything is correctly setup for S3 support with `Object API (Amazon S3 compatible):...`.

Also just for the next person that comes along. You will have to respecify the `--certs-dir` as well.
```
docker run -d -p 443:9000 --name minio \
  -e "MINIO_ACCESS_KEY=XXXXX" \
  -e "MINIO_SECRET_KEY=XXXXXXXXX" \
  -v /mnt/data:/data \
  -v /mnt/config:/home/minio/.minio \
  minio/minio:RELEASE.2019-06-19T18-24-42Z server --compat --certs-dir /home/minio/.minio/certs /data
```

Anyway,
Great piece of kit,

Thanks again,
Emmet
