### ISSUE TITLE
Regression(?) In STS Support in Minio

### ISSUE THREAD

**Issue by edude03** [minio/minio#8062]
Hello, I'm attempting to use the STS support in Minio and I'm finding it's not working. When testing locally I've been using version `RELEASE.2019-02-26T19-51-46Z` when using version `RELEASE.2019-07-17T22-54-12Z` and newer I'm unable to authenticate. 

Here's how I'm testing. I wrote a little script to run the docker image to make the test reproducible.

```
$ cat run-minio-docker.sh
#!/usr/bin/env bash

docker run \
  -e MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY \
  -e MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE \
  -e MINIO_IAM_JWKS_URL=https://myproject.auth0.com/.well-known/jwks.json \
  -p 9000:9000 \
  -v $(PWD):/data \
  minio/minio:RELEASE.2019-02-26T19-51-46Z \ 
  server /data
``` 
Then I fetch and set the `AWS_SECRET_ACCESS_KEY` `AWS_ACCESS_KEY_ID` and `AWS_SESSION_TOKEN`.

When I run 
`aws --endpoint-url http://localhost:9000 s3 ls` 

with version `RELEASE.2019-02-26T19-51-46Z` I get the list of contents in the /data folder,
with version `RELEASE.2019-07-17T22-54-12Z` and `latest` I get 

`An error occurred (InternalError) when calling the ListBuckets operation (reached max retries: 4): We encountered an internal error, please try again.` from AWS CLI and
```
Error: Authentication failed, check your access credentials
       5: cmd/api-errors.go:1692:cmd.toAPIErrorCode()
       4: cmd/auth-handler.go:251:cmd.checkClaimsFromToken()
       3: cmd/auth-handler.go:287:cmd.checkRequestAuthType()
       2: cmd/bucket-handlers.go:210:cmd.objectAPIHandlers.ListBucketsHandler()
       1: net/http/server.go:1995:http.HandlerFunc.ServeHTTP()
```

in the console.

**Comment by harshavardhana** [comment]
are you setting session token properly? I seem to be able to use it properly.

**Comment by harshavardhana** [comment]
Can you provide --debug output from the aws cli ? - also how are you authenticating? are you using client credentials or web identity?

**Comment by harshavardhana** [comment]
Also, are you trying to use the STS generated from 

>   minio/minio:RELEASE.2019-02-26T19-51-46Z 

and trying to use it with 

> minio/minio:RELEASE.2019-07-17T22-54-12Z

tag? 

I am afraid that may not work since we added extra 
claims to JWT and it requires that you generate a new STS
with 

> minio/minio:RELEASE.2019-07-17T22-54-12Z

**Comment by edude03** [comment]
Hi @harshavardhana, thanks for giving me some leads. 

I am regenerating the token between each test, so it's not an issue of using a token with the incorrect version. 

the debug output looks like this 

```
host;x-amz-content-sha256;x-amz-date;x-amz-security-token
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2019-08-11 14:26:10,315 - MainThread - botocore.auth - DEBUG - StringToSign:
AWS4-HMAC-SHA256
20190811T062610Z
20190811/us-east-1/s3/aws4_request
1cccd831bc13d6cd414c1771c70cb4d02baa32882ec83d948d4d0fd0aba795c1
2019-08-11 14:26:10,315 - MainThread - botocore.auth - DEBUG - Signature:
625fdb271ada2729bb52e6f3e78605777137c8322530e2eed8c26bcade2626bb
2019-08-11 14:26:10,315 - MainThread - botocore.endpoint - DEBUG - Sending http request: <AWSPreparedRequest stream_output=False, method=GET, url=http://localhost:9000/, headers={'X-Amz-Content-SHA256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': 'AWS4-HMAC-SHA256 Credential=6BHXJUXM4UCPAV2CBAIF/20190811/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=625fdb271ada2729bb52e6f3e78605777137c8322530e2eed8c26bcade2626bb', 'X-Amz-Security-Token': 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI2QkhYSlVYTTRVQ1BBVjJDQkFJRiIsImF1ZCI6IjNEcXlMcW5QQ3Q4VWRwTlBTcm1seHJ4Z01pR2JWNUdhIiwiZW1haWwiOiJtaWNoYWVsQG1lbGVuaW9uLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZXhwIjoxNTY1NTM2OTg4LCJpYXQiOjE1NjU1MDA5ODgsImlzcyI6Imh0dHBzOi8vY3JhdGVob3VzZS5hdXRoMC5jb20vIiwibmFtZSI6Im1pY2hhZWxAbWVsZW5pb24uY29tIiwibmlja25hbWUiOiJtaWNoYWVsIiwicGljdHVyZSI6Imh0dHBzOi8vcy5ncmF2YXRhci5jb20vYXZhdGFyLzIwMDAyMjU0MDcwMzM4ODJhNzVmZjk2MjlkMzc4ZGU1P3M9NDgwXHUwMDI2cj1wZ1x1MDAyNmQ9aHR0cHMlM0ElMkYlMkZjZG4uYXV0aDAuY29tJTJGYXZhdGFycyUyRm1pLnBuZyIsInN1YiI6ImF1dGgwfDVkNDk0ZWJjNTI3M2Q1MGNhNWIxZjFlZiIsInVwZGF0ZWRfYXQiOiIyMDE5LTA4LTExVDA1OjIzOjA4LjE0OFoifQ.AaCProROmrVPWTxyPprNWocOcGqoh-cINQVZsgA3jrvqAQ8boNYuNTm-uPCO3q6rKjiytoV12KZqV5bhZ0zjVg', 'X-Amz-Date': '20190811T062610Z', 'User-Agent': 'aws-cli/1.16.170 Python/2.7.16 Darwin/18.7.0 botocore/1.12.160'}>
2019-08-11 14:26:10,316 - MainThread - urllib3.util.retry - DEBUG - Converted retries value: False -> Retry(total=False, connect=None, read=None, redirect=0, status=None)
2019-08-11 14:26:10,319 - MainThread - urllib3.connectionpool - DEBUG - http://localhost:9000 "GET / HTTP/1.1" 500 264
2019-08-11 14:26:10,319 - MainThread - botocore.parsers - DEBUG - Response headers: {'Content-Length': '264', 'X-Xss-Protection': '1; mode=block', 'Content-Security-Policy': 'block-all-mixed-content', 'Accept-Ranges': 'bytes', 'Vary': 'Origin', 'Server': 'MinIO/RELEASE.2019-08-07T01-59-21Z', 'X-Amz-Request-Id': '15B9CA4B5155324C', 'Date': 'Sun, 11 Aug 2019 06:26:10 GMT', 'Content-Type': 'application/xml'}
2019-08-11 14:26:10,319 - MainThread - botocore.parsers - DEBUG - Response body:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InternalError</Code><Message>We encountered an internal error, please try again.</Message><Resource>/</Resource><RequestId>15B9CA4B5155324C</RequestId><HostId>de9a9680-cbc3-477d-a997-52f5e215c17e</HostId></Error>
2019-08-11 14:26:10,320 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <botocore.retryhandler.RetryHandler object at 0x1127e2950>
2019-08-11 14:26:10,320 - MainThread - botocore.retryhandler - DEBUG - retry needed: retryable HTTP status code received: 500
2019-08-11 14:26:10,320 - MainThread - botocore.retryhandler - DEBUG - Reached the maximum number of retry attempts: 5
2019-08-11 14:26:10,320 - MainThread - botocore.retryhandler - DEBUG - No retry needed.
2019-08-11 14:26:10,320 - MainThread - botocore.hooks - DEBUG - Event needs-retry.s3.ListBuckets: calling handler <bound method S3RegionRedirector.redirect_from_error of <botocore.utils.S3RegionRedirector object at 0x1127e2990>>
2019-08-11 14:26:10,320 - MainThread - botocore.hooks - DEBUG - Event after-call.s3.ListBuckets: calling handler <function enhance_error_msg at 0x111f53cf8>
2019-08-11 14:26:10,323 - MainThread - awscli.clidriver - DEBUG - Exception caught in main()
Traceback (most recent call last):
  File "/nix/store/nmqp211izrkak9zbvrlf3zbck5gcrn55-awscli-1.16.170/lib/python2.7/site-packages/awscli/clidriver.py", line 207, in main
    return command_table[parsed_args.command](remaining, parsed_args)
  File "/nix/store/nmqp211izrkak9zbvrlf3zbck5gcrn55-awscli-1.16.170/lib/python2.7/site-packages/awscli/customizations/commands.py", line 190, in __call__
    parsed_globals)
  File "/nix/store/nmqp211izrkak9zbvrlf3zbck5gcrn55-awscli-1.16.170/lib/python2.7/site-packages/awscli/customizations/commands.py", line 187, in __call__
    return self._run_main(parsed_args, parsed_globals)
  File "/nix/store/nmqp211izrkak9zbvrlf3zbck5gcrn55-awscli-1.16.170/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 479, in _run_main
    self._list_all_buckets()
  File "/nix/store/nmqp211izrkak9zbvrlf3zbck5gcrn55-awscli-1.16.170/lib/python2.7/site-packages/awscli/customizations/s3/subcommands.py", line 544, in _list_all_buckets
    response_data = self.client.list_buckets()
  File "/nix/store/w7jpwlvg2f33wx87rkbk86fjplplc4j8-python2.7-botocore-1.12.160/lib/python2.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/nix/store/w7jpwlvg2f33wx87rkbk86fjplplc4j8-python2.7-botocore-1.12.160/lib/python2.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
ClientError: An error occurred (InternalError) when calling the ListBuckets operation (reached max retries: 4): We encountered an internal error, please try again.
2019-08-11 14:26:10,329 - MainThread - awscli.clidriver - DEBUG - Exiting with rc 255
```

The token is included in the request so it is apparently set correctly.

**Comment by harshavardhana** [comment]
Is there a way I can test this ? Using auth0 @edude03 ?

**Comment by harshavardhana** [comment]
I am not able to reproduce this @edude03 can you help?
