### ISSUE TITLE
[Notification] Check for EOF and `Service Unavailable` from webhooks behind proxies

### ISSUE THREAD

**Issue by Praveenrajmani** [minio/minio#8194]
Webhooks running proxies responds with EOF/`Service Unavailable` for connection failures

## Expected Behavior
Should not panic for connection failures

## Current Behavior
MinIO panic while sending the event in such scenarios

## Possible Solution
Check for EOF/Server Unavailable while pinging 

## Steps to Reproduce (for bugs)

1. Run a webhook behind nginx
```
server {
listen 18080 default_server;
root /var/www/html;
index index.html index.htm index.nginx-debian.html;
server_name _;
access_log /var/log/nginx/access.log main;
#logging
location /api/logs {
access_log /var/log/nginx/minio-logs.log json_postdata;
limit_except POST { deny all; }
proxy_pass $scheme://127.0.0.1:$server_port/success;
}
location /api/webhook {
access_log /var/log/nginx/minio-access.log json_postdata;
limit_except POST { deny all; }
proxy_pass $scheme://127.0.0.1:$server_port/success;
}

location /success {
access_log off;
return 200;
}
}
```
2. Reset/stop the connection 
3. The server will panic while sending events

## Regression

No

## Your Environment

* Version used (`minio version`):
* Environment name and version (e.g. nginx 1.9.1):
* Server type and version:
* Operating System and version (`uname -a`):
* Link to your project:

**Comment by Praveenrajmani** [comment]
Related to https://github.com/minio/minio/issues/8178#issuecomment-528736777

**Comment by mrsrvman** [comment]
Patch  did not help

**Comment by mrsrvman** [comment]
```
Sep 19 04:52:09 node01 minio: Object API (Amazon S3 compatible):
Sep 19 04:52:09 node01 minio: Go: https://docs.min.io/docs/golang-client-quickstart-guide
Sep 19 04:52:09 node01 minio: Java: https://docs.min.io/docs/java-client-quickstart-guide
Sep 19 04:52:09 node01 minio: Python: https://docs.min.io/docs/python-client-quickstart-guide
Sep 19 04:52:09 node01 minio: JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
Sep 19 04:52:09 node01 minio: .NET: https://docs.min.io/docs/dotnet-client-quickstart-guide
Sep 19 04:53:17 node01 minio: panic: target.Send() failed with 'Post http://10.101.6.64:8080/api/webhook: EOF'
Sep 19 04:53:17 node01 minio: goroutine 1936 [running]:
Sep 19 04:53:17 node01 minio: github.com/minio/minio/pkg/event/target.sendEvents.func1(0xc003144e82, 0x24, 0x2)
Sep 19 04:53:17 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:125 +0x26d
Sep 19 04:53:17 node01 minio: github.com/minio/minio/pkg/event/target.sendEvents(0x1c42100, 0xc0004202a0, 0xc0007b1c20, 0xc000494000)
Sep 19 04:53:17 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:146 +0x1ba
Sep 19 04:53:17 node01 minio: created by github.com/minio/minio/pkg/event/target.NewWebhookTarget
Sep 19 04:53:17 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/webhook.go:205 +0x296
Sep 19 04:53:17 node01 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 19 04:53:17 node01 systemd: Unit minio.service entered failed state.
Sep 19 04:53:17 node01 systemd: minio.service failed.
Sep 19 04:54:07 node01 systemd: Starting Minio...
Sep 19 04:54:07 node01 systemd: Started Minio.
```

```
Sep 19 05:57:46 node01 minio: DeploymentID: 2193f469-c66a-4faa-9964-7835f80eedd1
Sep 19 05:57:46 node01 minio: Error: the maximum store limit reached
Sep 19 05:57:46 node01 minio: EventName=s3:ObjectCreated:Put, targetID=webhook
Sep 19 05:57:46 node01 minio: 3: cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
Sep 19 05:57:46 node01 minio: 2: cmd/logger/logonce.go:80:logger.LogOnceIf()
Sep 19 05:57:46 node01 minio: 1: cmd/notification.go:1171:cmd.sendEvent.func1()
Sep 19 05:58:10 node01 minio: panic: target.Send() failed with 'sending event failed with 500 Internal Server Error'
Sep 19 05:58:10 node01 minio: goroutine 907 [running]:
Sep 19 05:58:10 node01 minio: github.com/minio/minio/pkg/event/target.sendEvents.func1(0xc00209b602, 0x24, 0x2)
Sep 19 05:58:10 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:125 +0x26d
Sep 19 05:58:10 node01 minio: github.com/minio/minio/pkg/event/target.sendEvents(0x1c42100, 0xc000b801c0, 0xc000b72780, 0xc0000eac00)
Sep 19 05:58:10 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:146 +0x1ba
Sep 19 05:58:10 node01 minio: created by github.com/minio/minio/pkg/event/target.NewWebhookTarget
Sep 19 05:58:10 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/webhook.go:205 +0x296
Sep 19 05:58:11 node01 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 19 05:58:11 node01 systemd: Unit minio.service entered failed state.
Sep 19 05:58:11 node01 systemd: minio.service failed.
Sep 19 05:58:31 node01 systemd: Starting Minio...
Sep 19 05:58:31 node01 systemd: Started Minio.
```

```
Sep 19 04:59:30 node01 minio: UserAgent: aws-cli/1.11.13 Python/3.5.3 Linux/4.19.0-0.bpo.5-amd64 botocore/1.4.70
Sep 19 04:59:30 node01 minio: Error: Post http://10.101.6.66:9000/minio/storage/v9/data/deletefile?file-path=80994586-687a-4caa-954b-2a38c65a2920%2Fpart.1&instance-id=81b3b32b-4e39-40aa-9bc6-6722707bfe18&volume=.minio.sys%2Ftmp: EOF
Sep 19 04:59:30 node01 minio: 4: cmd/object-api-common.go:116:cmd.cleanupDir.func1()
Sep 19 04:59:30 node01 minio: 3: cmd/object-api-common.go:139:cmd.cleanupDir.func1()
Sep 19 04:59:30 node01 minio: 2: cmd/object-api-common.go:145:cmd.cleanupDir()
Sep 19 04:59:30 node01 minio: 1: cmd/xl-v1-object.go:759:cmd.xlObjects.deleteObject.func1()
Sep 19 04:59:31 node01 minio: panic: target.Send() failed with 'sending event failed with 503 Service Unavailable'
Sep 19 04:59:31 node01 minio: goroutine 1927 [running]:
Sep 19 04:59:31 node01 minio: github.com/minio/minio/pkg/event/target.sendEvents.func1(0xc004a0f242, 0x24, 0x2)
Sep 19 04:59:31 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:125 +0x26d
Sep 19 04:59:31 node01 minio: github.com/minio/minio/pkg/event/target.sendEvents(0x1c42100, 0xc0002e0380, 0xc0009bd380, 0xc000590060)
Sep 19 04:59:31 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:146 +0x1ba
Sep 19 04:59:31 node01 minio: created by github.com/minio/minio/pkg/event/target.NewWebhookTarget
Sep 19 04:59:31 node01 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/webhook.go:205 +0x296
Sep 19 04:59:31 node01 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 19 04:59:31 node01 systemd: Unit minio.service entered failed state.
Sep 19 04:59:31 node01 systemd: minio.service failed.
Sep 19 05:01:01 node01 systemd: Created slice User Slice of root.
Sep 19 05:01:01 node01 systemd: Started Session 4051 of user root.
Sep 19 05:01:02 node01 systemd: Removed slice User Slice of root.
Sep 19 05:02:00 node01 systemd: Starting Minio...
Sep 19 05:02:00 node01 systemd: Started Minio.
```

```
Sep 19 04:51:40 node03 minio: Object API (Amazon S3 compatible):
Sep 19 04:51:40 node03 minio: Go: https://docs.min.io/docs/golang-client-quickstart-guide
Sep 19 04:51:40 node03 minio: Java: https://docs.min.io/docs/java-client-quickstart-guide
Sep 19 04:51:40 node03 minio: Python: https://docs.min.io/docs/python-client-quickstart-guide
Sep 19 04:51:40 node03 minio: JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
Sep 19 04:51:40 node03 minio: .NET: https://docs.min.io/docs/dotnet-client-quickstart-guide
Sep 19 04:52:49 node03 minio: panic: target.Send() failed with 'Post http://10.101.6.64:8080/api/webhook: net/http: timeout awaiting response headers'
Sep 19 04:52:49 node03 minio: goroutine 890 [running]:
Sep 19 04:52:49 node03 minio: github.com/minio/minio/pkg/event/target.sendEvents.func1(0xc001c236a2, 0x24, 0x2)
Sep 19 04:52:49 node03 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:125 +0x26d
Sep 19 04:52:49 node03 minio: github.com/minio/minio/pkg/event/target.sendEvents(0x1c42100, 0xc0004be2a0, 0xc000885da0, 0xc000020000)
Sep 19 04:52:49 node03 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:146 +0x1ba
Sep 19 04:52:49 node03 minio: created by github.com/minio/minio/pkg/event/target.NewWebhookTarget
Sep 19 04:52:49 node03 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/webhook.go:205 +0x296
Sep 19 04:52:49 node03 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 19 04:52:49 node03 systemd: Unit minio.service entered failed state.
Sep 19 04:52:49 node03 systemd: minio.service failed.
Sep 19 04:53:45 node03 systemd: Starting Minio...
Sep 19 04:53:46 node03 systemd: Started Minio.
```

**Comment by Praveenrajmani** [comment]
@mrsrvman can you get me the latest commit id / MinIO version?. The fix is not yet released

**Comment by mrsrvman** [comment]
Version: 2019-09-18T21:55:05Z

SQS ARNs: arn:minio:sqs::1:webhook

**Comment by mrsrvman** [comment]
On latest release RELEASE.2019-09-25T18-25-51Z

```

Sep 26 04:49:08 node03 minio: panic: target.Send() failed with 'sending event failed with 500 Internal Server Error'
Sep 26 04:49:08 node03 minio: goroutine 649 [running]:
Sep 26 04:49:08 node03 minio: github.com/minio/minio/pkg/event/target.sendEvents.func1(0xc006ba6ac2, 0x24, 0x2)
Sep 26 04:49:08 node03 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:125 +0x26d
Sep 26 04:49:08 node03 minio: github.com/minio/minio/pkg/event/target.sendEvents(0x1c44280, 0xc0004d41c0, 0xc000c5bec0, 0xc0000a81e0)
Sep 26 04:49:08 node03 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/store.go:146 +0x1ba
Sep 26 04:49:08 node03 minio: created by github.com/minio/minio/pkg/event/target.NewWebhookTarget
Sep 26 04:49:08 node03 minio: /q/.q/sources/gopath/src/github.com/minio/minio/pkg/event/target/webhook.go:208 +0x296
Sep 26 04:49:08 node03 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 26 04:49:08 node03 systemd: Unit minio.service entered failed state.
```

**Comment by harshavardhana** [comment]
@Praveenrajmani why are panicking I am not able to understand ..We should perhaps not panic at all so deep in the call flow.

It is either simply better to log such an error and move on as dropped events.
