### ISSUE TITLE
upload from android

### ISSUE THREAD

**Issue by sea-sol** [minio/minio#8369]
## Expected Behavior
I am trying to upload some file to Minio
the server is ubuntu and I am using android studio
the code is sample code from
[https://golb.hplar.ch/2017/02/Upload-files-from-Java-to-a-Minio-server.html](url) 
and building is ok, but after this, when app run. some bugs appear and I couldn't fix it

## Current Behavior
Now the access key and secret key is OK. and all the other is no problem
but

AmazonS3 s3Client = AmazonS3ClientBuilder
                .standard()
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration("http://10.3.1.124:9000", Regions.US_EAST_1.name()))
                .withPathStyleAccessEnabled(true)
                .withClientConfiguration(clientConfiguration)
                .withCredentials(new AWSStaticCredentialsProvider(credentials))
                .build();

here error appear.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: social.media.minio, PID: 5936
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sun/jmx/mbeanserver/GetPropertyAction;
        at javax.management.ObjectName.<clinit>(ObjectName.java:296)
        at javax.management.MBeanServerFactory.<clinit>(MBeanServerFactory.java:396)
        at javax.management.MBeanServerFactory.findMBeanServer(Unknown Source:0)
        at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:111)
        at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:50)
        at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
        at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:398)
        at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:359)
        at com.amazonaws.metrics.AwsSdkMetrics.addAll(AwsSdkMetrics.java:662)
        at com.amazonaws.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:395)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at social.media.minio.MainActivity.onCreate(MainActivity.java:66)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.sun.jmx.mbeanserver.GetPropertyAction" on path: DexPathList[[zip file "/data/app/social.media.minio-vpIHAeiaD5WAwi_xHNHa0Q==/base.apk"],nativeLibraryDirectories=[/data/app/social.media.minio-vpIHAeiaD5WAwi_xHNHa0Q==/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at javax.management.ObjectName.<clinit>(ObjectName.java:296) 
        at javax.management.MBeanServerFactory.<clinit>(MBeanServerFactory.java:396) 
        at javax.management.MBeanServerFactory.findMBeanServer(Unknown Source:0) 
        at com.amazonaws.jmx.MBeans.getMBeanServer(MBeans.java:111) 
        at com.amazonaws.jmx.MBeans.registerMBean(MBeans.java:50) 
        at com.amazonaws.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27) 
        at com.amazonaws.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:398) 
        at com.amazonaws.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:359) 
        at com.amazonaws.metrics.AwsSdkMetrics.addAll(AwsSdkMetrics.java:662) 
        at com.amazonaws.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:395) 
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35) 
        at com.amazonaws.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32) 
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64) 
        at com.amazonaws.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28) 
        at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46) 
        at social.media.minio.MainActivity.onCreate(MainActivity.java:66) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
## Steps to Reproduce (for bugs)
1. this issue appear when after build the app and run it 

## Context
because of this error, I can't make my app so that I can't upload file to the Minio with my phone.

## Regression
this error is appear every time.

## Your Environment

* Version used (`2019-10-02T21:19:38Z`):
* Environment name and version (Arch: amd64):
* Server type and version: Host: ubuntu | OS: linux | 
* Operating System and version (`ubuntu`):
* Link to your project: [https://github.com/Rolland-K/MinIO]

**Comment by vadmeste** [comment]
> E/AndroidRuntime: FATAL EXCEPTION: main
> Process: social.media.minio, PID: 5936
> java.lang.NoClassDefFoundError: Failed resolution of: Lcom/sun/jmx/mbeanserver/GetPropertyAction;

@Rolland-K this looks more like an issue while adding AWS libraries in your Android project (is that already supported ?)

**Comment by sea-sol** [comment]
I have upload many files to aws S3 with my phone.
now I am going to make server with Minio, and upload file to there.
but as I said, I couldn't.

I think this is not about AWS libraries, may be jmx problem.
if anyone know the solution of this, please let me know.

**Comment by ghost** [comment]
FWIW, I used to use S3Anywhere on the Android and worked without issues.
Since then I moved to using Nextcloud using Minio as a backend.

**Comment by sea-sol** [comment]
Mr Alex. 
so you can upload file to minio, not amazone s3 with android?
without any code change?
I  think the code should be different.
but if it is true, could you kindly share your code link?

**Comment by ghost** [comment]
if I am understanding the question:  Can I upload a file from Android to
Minio?


Yes.  I (personally) used an app and supplied the minio credentials and had
zero issues uploading files from Android to Minio.  There are many S3 apps
and I just chose the Nextcloud route just for the Android <> Minio auto
sync feature.

A

**Comment by sea-sol** [comment]
Could you kindly share your code?

**Comment by sea-sol** [comment]
the amazone s3 code can't used for Minio.
please let me know how to upload to Minio in android without any issue

**Comment by ghost** [comment]
https://play.google.com/store/apps/details?id=lysesoft.s3anywhere

**Comment by sea-sol** [comment]
This will upload to amazone s3 
I have already made such app and this is running for me.
what I really need is upload to Minio not Amazone S3.
I can't use same code. when I use the sample code of Minio Documentation , I have error.
need solve this error, or new running code.
I can't find any other code for uploading to Minio from android.
this is what I mean.

**Comment by ghost** [comment]
I use that app and just use my minio DNS name and credentials...  works
great for Minio.

**Comment by kannappanr** [comment]
@Rolland-K I believe you can use something like https://play.google.com/store/apps/details?id=lysesoft.s3anywhere

Closing this issue here. Please feel free to reach out to us at https://slack.min.io for further such questions

**Comment by sea-sol** [comment]
please let me know how to set the target url(not bucket) in uploading file to s3(Minio)
what I really want to know is working code. to upload file to Minio in android.
if anyone have or know about this, kindly let me know about that.
