### ISSUE TITLE
Minio won't start due to "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by vsfalexanderpilch** [minio/minio#8387]
Minio won't start in latest version on docker swarm (image minio:latest) since today. The previous release is fine.

We're using AssumeRoleWithWebidentity/the MINIO_IAM_JWKS_URL setting, so that might cause the issue.

Here's the log
[log.txt](https://github.com/minio/minio/files/3716942/log.txt)

**Comment by vadmeste** [comment]
@vsfalexanderpilch thanks for reporting this:

I filtered the log you attached above to only show the stacktrace of the node that is crashing.

```
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | panic: runtime error: invalid memory address or nil pointer dereference
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45ee88]
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | goroutine 1 [running]:
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/pkg/iam/openid.(*JWKSArgs).PopulatePublicKey(0xc00065cc48, 0x0, 0x0)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/pkg/iam/openid/jwt.go:75 +0x44c
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/pkg/iam/openid.LookupConfig(0xc00058c900, 0xc000a265d0, 0x0, 0x0, 0xc0009fe000, 0x1a03958, 0x3, 0x0, 0xc000a4a310, 0x7, ...)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/pkg/iam/openid/jwt.go:219 +0xcd
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/cmd.(*serverConfigV33).lookupConfigs(0xc000160000)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config-current.go:310 +0x5c6
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/cmd.loadConfig(0x1c95fc0, 0xc00077b7c0, 0x0, 0x0)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config-current.go:536 +0x72
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/cmd.initConfig(0x1c95fc0, 0xc00077b7c0, 0x2, 0x0)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config.go:190 +0x126
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/cmd.(*ConfigSys).Init(0x2df8bb0, 0x1c95fc0, 0xc00077b7c0, 0x0, 0x0)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config.go:144 +0x211
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/cmd.serverMain(0xc0003c4900)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:342 +0x815
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/cli.HandleAction(0x1648880, 0x1a03748, 0xc0003c4900, 0xc0003b0400, 0x0)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:500 +0x7c
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/cli.Command.Run(0x1978272, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x199dc78, 0x1b, 0x0, ...)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/command.go:221 +0x991
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/cli.(*App).Run(0xc0000ac000, 0xc00003a0c0, 0x4, 0x4, 0x0, 0x0)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:261 +0x6ab
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | github.com/minio/minio/cmd.Main(0xc00003a0c0, 0x4, 0x4)
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:161 +0x89
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    | main.main()
minio_node5.1.tqtf6hmidwgc@lmanlxapp43    |     /q/.q/sources/gopath/src/github.com/minio/minio/main.go:37 +0x45
```

However, it seems that node is not really updated to the last Minio image (of today), I know because the stack trace points to a line that is impossible to crash:

```
https://github.com/minio/minio/blob/RELEASE.2019-10-11T00-38-09Z/pkg/iam/openid/jwt.go#L75
```

Please check again on your side.

**Comment by vsfalexanderpilch** [comment]
Here's the image we're using. It was fine in minio/minio:RELEASE.2019-10-02T21-19-38Z
```
# docker pull minio/minio
Using default tag: latest
latest: Pulling from minio/minio
Digest: sha256:6acd190e0e9f6a23f59c69bf93c828951da1da368bf01e5858139a84ae44143a
Status: Image is up to date for minio/minio:latest
docker.io/minio/minio:latest

# docker images
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
minio/minio                          latest              e0680b6041a8        11 hours ago        51MB
minio/minio                          <none>              139e46c9cb92        8 days ago          50.9MB
```

**Comment by vsfalexanderpilch** [comment]
@vadmeste After setting a fixed version (RELEASE.2019-10-11T00-38-09Z), the issue is still the same:

```
# docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                           PORTS               NAM                                                                        ES
7df9ab1982e6        minio/minio:RELEASE.2019-10-11T00-38-09Z    "/usr/bin/docker-ent…"   12 seconds ago      Up 1 second (health: starting)   9000/tcp            min                                                                        io_node3.1.8q6otlkylzatc0pbfnql15n4j
55897abd4a31        minio/minio:RELEASE.2019-10-11T00-38-09Z    "/usr/bin/docker-ent…"   2 minutes ago       Up 2 minutes (healthy)           9000/tcp            min                                                                        io_node4.1.z2quzl6q1fl9nizbozer6vdq2

lmanlxapp42:/root
# docker logs 7d
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x45ee88]

goroutine 1 [running]:
github.com/minio/minio/pkg/iam/openid.(*JWKSArgs).PopulatePublicKey(0xc00058eb68, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/minio/pkg/iam/openid/jwt.go:75 +0x44c
github.com/minio/minio/pkg/iam/openid.LookupConfig(0xc000dc5580, 0xc000e26ae0, 0x0, 0x0, 0xc00087a640, 0x1a03958, 0x3, 0x0, 0xc0007c8d20, 0x7, ...)
        /q/.q/sources/gopath/src/github.com/minio/minio/pkg/iam/openid/jwt.go:219 +0xcd
github.com/minio/minio/cmd.(*serverConfigV33).lookupConfigs(0xc000a20c00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config-current.go:310 +0x5c6
github.com/minio/minio/cmd.newSrvConfig(0x1c95fc0, 0xc000797ea0, 0x1c229a0, 0xc00009c0c0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config-current.go:506 +0x34
github.com/minio/minio/cmd.migrateConfigToMinioSys(0x1c95fc0, 0xc000797ea0, 0x1c25840, 0xc000e4c2d0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config-migrate.go:2474 +0x74c
github.com/minio/minio/cmd.initConfig(0x1c95fc0, 0xc000797ea0, 0x2, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config.go:181 +0xc4
github.com/minio/minio/cmd.(*ConfigSys).Init(0x2df8bb0, 0x1c95fc0, 0xc000797ea0, 0x0, 0x0)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/config.go:144 +0x211
github.com/minio/minio/cmd.serverMain(0xc00021ef00)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/server-main.go:342 +0x815
github.com/minio/cli.HandleAction(0x1648880, 0x1a03748, 0xc00021ef00, 0xc000233c00, 0x0)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:500 +0x7c
github.com/minio/cli.Command.Run(0x1978272, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x199dc78, 0x1b, 0x0, ...)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/command.go:221 +0x991
github.com/minio/cli.(*App).Run(0xc0002511e0, 0xc0000b6040, 0x4, 0x4, 0x0, 0x0)
        /q/.q/sources/gopath/pkg/mod/github.com/minio/cli@v1.21.0/app.go:261 +0x6ab
github.com/minio/minio/cmd.Main(0xc0000b6040, 0x4, 0x4)
        /q/.q/sources/gopath/src/github.com/minio/minio/cmd/main.go:161 +0x89
main.main()
        /q/.q/sources/gopath/src/github.com/minio/minio/main.go:37 +0x45
```

We've got 2 container per server. Only one of them is running. The other one is crashing. Might be coincidence:

```
# docker service ls
ID                  NAME                MODE                REPLICAS            IMAGE                                       PORTS
jp84629erqwn        minio_haproxy       global              3/3                 127.0.0.1:5000/minio-haproxy:latest   *:80->80/tcp, *:443->443/tcp, *:32000->32000/tcp
jxe1n3x0s0i1        minio_node1         replicated          1/1                 minio/minio:RELEASE.2019-10-11T00-38-09Z
m4vmtk44w0kn        minio_node2         replicated          0/1                 minio/minio:RELEASE.2019-10-11T00-38-09Z
ip17fsgudgv0        minio_node3         replicated          0/1                 minio/minio:RELEASE.2019-10-11T00-38-09Z
y47s3ctx2rac        minio_node4         replicated          1/1                 minio/minio:RELEASE.2019-10-11T00-38-09Z
ocp5s1s5uo32        minio_node5         replicated          0/1                 minio/minio:RELEASE.2019-10-11T00-38-09Z
lvtvyn5n6ugi        minio_node6         replicated          1/1                 minio/minio:RELEASE.2019-10-11T00-38-09Z
```

**Comment by harshavardhana** [comment]
We will fix it - it is some recent refactors which led to the crash here.

**Comment by harshavardhana** [comment]
@vsfalexanderpilch I am not able to reproduce this issue and also the line number of the crash is wrong because of the line number simply 

54ae364def pkg/iam/validator/jwt.go (Harshavardhana 2018-10-09 14:00:01 -0700  75)      return nil

Are you sure all your containers are using the latest?

**Comment by vsfalexanderpilch** [comment]
It's working fine again. Thanks a lot for fixing it.
