### ISSUE TITLE
can't acces server thru javascript. can acces in browser.

### ISSUE THREAD

**Issue by NicTanghe** [minio/minio#8414]
## Expected Behavior
Minio should be able to connect in JS.

## Current Behavior
I get an error.

```
C:\Users\nicta\Documents\dev\react\tests\test1\hasura\node_modules\minio\dist\main\minio.js:88
      throw new errors.InvalidEndpointError(`Invalid endPoint : ${params.endPoint}`);
      ^
InvalidEndpointError: Invalid endPoint : http://localhost
    at new Client (C:\Users\nicta\Documents\dev\react\tests\test1\hasura\node_modules\minio\dist\main\minio.js:88:13)
    at Object.<anonymous> (C:\Users\nicta\Documents\dev\react\tests\test1\hasura\test.js:6:19)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11
```

## Steps to Reproduce (for bugs)
host a server with windows, connect with

new minio client

## Context

 trying to upload a file using node.js

## Your Environment

* Version used (`minio version`):

Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812
* Environment name and version (e.g. nginx 1.9.1):
node
* Server type and version:
windwows 10 home
* Operating System and version (`uname -a`):
windwows 10 home
* Link to your project:
```javascript
var Minio = require("minio");
const fs = require("fs");

// Instantiate the minio client with the endpoint
// and access keys as shown below.
var minioClient = new Minio.Client({
  endPoint: "http://localhost",
  port: 9000,
  useSSL: true,
  accessKey: "ABW2JVTAQQJ9YQ895B80",
  secretKey: "cclFlqWaZKgtFRll71CUyZW8tkCP3YB7J8STm0IB"
});

// File that needs to be uploaded.
var file = "./tmp/snowstormbear.png";
var metaData = { user: "value", filetype: "mario" };
// Make a bucket called europetrip.
// minioClient.makeBucket("europetrip", "us-east-1", function(err) {
//   if (err) return console.log(err);

//   console.log('Bucket created successfully in "us-east-1".');

//   var metaData = {
//     "Content-Type": "application/octet-stream",
//     "X-Amz-Meta-Testing": 1234,
//     example: 5678
//   };
// Using fPutObject API upload your file to the bucket europetrip.

function deleteFileTemp() {
  fs.unlink(file, err => {
    if (err) {
      console.error("deletelocal" + err);
      return;
    }

    //file removed
  });
}
minioClient.fPutObject("Ben", "photos-europe.tar", file, metaData, function(
  err,
  etag
) {
  if (err) return console.log("fputobj" + err);
  console.log("File uploaded successfully.");
  deleteFileTemp();
});

// });

```

``` 
λ minio server C:\miniodata\
Endpoint:  http://169.254.21.200:9000  http://169.254.232.186:9000  http://169.254.212.166:9000  http://169.254.77.165:9000  http://169.254.163.164:9000  http://192.168.1.2:9000  http://192.168.56.1:9000  http://192.168.99.1:9000  http://127.0.0.1:9000
AccessKey: ABW2JVTAQQJ9YQ895B80
SecretKey: cclFlqWaZKgtFRll71CUyZW8tkCP3YB7J8STm0IB

Browser Access:
   http://169.254.21.200:9000  http://169.254.232.186:9000  http://169.254.212.166:9000  http://169.254.77.165:9000  http://169.254.163.164:9000  http://192.168.1.2:9000  http://192.168.56.1:9000  http://192.168.99.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc.exe config host add myminio http://169.254.21.200:9000 ABW2JVTAQQJ9YQ895B80 cclFlqWaZKgtFRll71CUyZW8tkCP3YB7J8STm0IB

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

```

**Comment by harshavardhana** [comment]
>   endPoint: "http://localhost",

This is invalid the correct value is 

>   endPoint: "localhost",

Also in your case server is not running in TLS so disable SSL.

>   useSSL: false,

**Comment by NicTanghe** [comment]
thx

**Comment by khoajunior** [comment]
try useSSL: false
