### ISSUE TITLE
Need configuration for temporary credentials

### ISSUE THREAD

**Issue by napat1412** [minio/minio#8428]
I try to user minio on docker with my keycloak server. I use client grants to retrieve temporary credential through OIDC. I got the temporary credential from minio server and then i try to access object with python: boto3 but I can't access object in bucket.

## Expected Behavior

I can use temporary credential to access object in bucket with phthon: boto3.

## Current Behavior

I start minio server with docker.
```
docker run -dt -p 9000:9000 --name minio1 \
  -e MINIO_IAM_JWKS_URL=https://<keycloak-server>/auth/realms/<realms-name>/protocol/openid-connect/certs \
  -e MINIO_ACCESS_KEY=minio \
  -e MINIO_SECRET_KEY=minio123 \
  -e MINIO_HTTP_TRACE=/dev/stdout \
  minio/minio:RELEASE.2019-09-25T18-25-51Z \
  server /data
```
I retrieve JWT token from keycloak and use it to retrieve minio's temporary credential.
```
POST http://172.16.0.215:9000?Action=AssumeRoleWithClientGrants&DurationSeconds=40000&Version=2011-06-15&Token={{access_token}}
```
The Response:
```
<?xml version="1.0" encoding="UTF-8"?>
<AssumeRoleWithClientGrantsResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/">
    <AssumeRoleWithClientGrantsResult>
        <AssumedRoleUser>
            <Arn></Arn>
            <AssumeRoleId></AssumeRoleId>
        </AssumedRoleUser>
        <Credentials>
            <AccessKeyId>{{ACCESS-KEY}}</AccessKeyId>
            <SecretAccessKey>{{SECRET}}</SecretAccessKey>
            <Expiration>2019-10-22T15:55:09Z</Expiration>
            <SessionToken>{{TOKEN}}</SessionToken>
        </Credentials>
        <SubjectFromToken>1e1c396e-aaae-4f98-805b-3fe4da6b73cd</SubjectFromToken>
    </AssumeRoleWithClientGrantsResult>
    <ResponseMetadata>
        <RequestId>15CFDBD8A9FC20CC</RequestId>
    </ResponseMetadata>
</AssumeRoleWithClientGrantsResponse>
```
I add policy: readwrite to temporary credential.
```
$ mc admin policy set myminio readwrite user={{ACCESS-KEY}}
$ mc admin user list myminio
enabled    {{ACCESS-KEY}}  readwrite
```

I run python: boto3 with docker: python:3.7.3-stretch and is use example python code to access s3 object from https://docs.min.io/docs/how-to-use-aws-sdk-for-python-with-minio-server.html
$ docker run -it --rm --entrypoint bash python:3.7.3-stretch
$ pip install boto3
$ python
```
>>>import boto3
>>>from botocore.client import Config
>>>s3 = boto3.resource('s3',
                    endpoint_url='http://172.16.0.215:9000',
                    aws_access_key_id='<ACCESS-KEY>',
                    aws_secret_access_key='<SECRET>',
                    aws_session_token='<TOKEN>',
                    config=Config(signature_version='s3v4'),
                    region_name='us-east-1')


>>> s3.Bucket('demo').download_file('hello.txt', '/tmp/hello.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line 246, in bucket_download_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 255, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/s3transfer/download.py", line 345, in _submit
    **transfer_future.meta.call_args.extra_args
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
```

$ mc admin trace -v -a --debug myminio
```
172.16.0.215 [REQUEST s3.HeadObject] 04:00:51.109
172.16.0.215 HEAD /demo/hello.txt
172.16.0.215 Host: 172.16.0.215:9000
172.16.0.215 Accept-Encoding: identity
172.16.0.215 Authorization: AWS4-HMAC-SHA256 Credential=ZZ9AC3F67RU9GEA3C9ZL/20191022/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=dd4da3835e81adb0fbd3ddf022dd8639890efe170ca1540568063b22d2f58737
172.16.0.215 Content-Length: 0
172.16.0.215 User-Agent: Boto3/1.9.253 Python/3.7.3 Linux/3.10.0-862.11.6.el7.x86_64 Botocore/1.12.253 Resource
172.16.0.215 X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
172.16.0.215 X-Amz-Date: 20191022T040051Z
172.16.0.215 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJaWjlBQzNGNjdSVTlHRUEzQzlaTCIsImFjciI6IjEiLCJhdWQiOiJhY2NvdW50IiwiYXV0aF90aW1lIjowLCJhenAiOiJtaW5pbyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZXhwIjoxNTcxNzU5NzA5LCJpYXQiOjE1NzE3MTY1MDksImlzcyI6Imh0dHBzOi8vc3NvLm1lY2EuaW4udGgvYXV0aC9yZWFsbXMvZGF0YXBsYXRmb3JtIiwianRpIjoiYTJmNTNkMjQtOTZkYS00NjA1LTkyYWUtMzQ5NTYwNDU1NGMyIiwibmJmIjowLCJwb2xpY3ktdG1wIjpbInJlYWR3cml0ZSJdLCJwb2xpY3ktdWEiOiJhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6Imxva2lvcyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsInNlc3Npb25fc3RhdGUiOiJkNjdhNDBiNC1mOWJiLTQ5MjEtOTU4OS1mNDBhYmI0MzNmZjkiLCJzdWIiOiIxZTFjMzk2ZS1hYWFlLTRmOTgtODA1Yi0zZmU0ZGE2YjczY2QiLCJ0eXAiOiJCZWFyZXIifQ.6J1hhCVAHbmxU4b-2-qdLDyr_HQLU839it_wgsSHE6EfXVoYwQhUs6KKK3GNtdniTU_HL6ktpyqRH111vEEoMg
172.16.0.215
172.16.0.215 [RESPONSE] [04:00:51.109] [ Duration 359µs  🠉 114 B  🠋 225 B ]
172.16.0.215 403 Forbidden
172.16.0.215 Content-Security-Policy: block-all-mixed-content
172.16.0.215 Server: MinIO/RELEASE.2019-09-25T18-25-51Z
172.16.0.215 Vary: Origin
172.16.0.215 X-Amz-Request-Id: 15CFDC2615DEE924
172.16.0.215 X-Xss-Protection: 1; mode=block
172.16.0.215 Accept-Ranges: bytes
172.16.0.215 Content-Length: 0
```

```
>>> print("In python")
>>> s3.Bucket('demo').upload_file('/etc/resolv.conf', 'resolv.conf')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 279, in upload_file
    future.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line 209, in bucket_upload_file
    ExtraArgs=ExtraArgs, Callback=Callback, Config=Config)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line 131, in upload_file
    extra_args=ExtraArgs, callback=Callback)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/transfer.py", line 287, in upload_file
    filename, '/'.join([bucket, key]), e))
boto3.exceptions.S3UploadFailedError: Failed to upload /etc/resolv.conf to demo/resolv.conf: An error occurred (AccessDenied) when calling the PutObject operation: Access Denied.
```

$ mc admin trace -v -a --debug myminio
```
172.16.0.215 [REQUEST s3.PutObject] 04:01:25.398
172.16.0.215 PUT /demo/resolv.conf
172.16.0.215 Host: 172.16.0.215:9000
172.16.0.215 Accept-Encoding: identity
172.16.0.215 Authorization: AWS4-HMAC-SHA256 Credential=ZZ9AC3F67RU9GEA3C9ZL/20191022/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=e6bab236473a74e9b5b2e9ad2a8987b9a9211f58f9897ef2a7c7115c44a973db
172.16.0.215 Content-Length: 59
172.16.0.215 Expect: 100-continue
172.16.0.215 X-Amz-Content-Sha256: ac06eea953ef0385212eebeb17340d8e144faf0bd8594d57176b3807fbec388a
172.16.0.215 X-Amz-Date: 20191022T040125Z
172.16.0.215 X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJaWjlBQzNGNjdSVTlHRUEzQzlaTCIsImFjciI6IjEiLCJhdWQiOiJhY2NvdW50IiwiYXV0aF90aW1lIjowLCJhenAiOiJtaW5pbyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZXhwIjoxNTcxNzU5NzA5LCJpYXQiOjE1NzE3MTY1MDksImlzcyI6Imh0dHBzOi8vc3NvLm1lY2EuaW4udGgvYXV0aC9yZWFsbXMvZGF0YXBsYXRmb3JtIiwianRpIjoiYTJmNTNkMjQtOTZkYS00NjA1LTkyYWUtMzQ5NTYwNDU1NGMyIiwibmJmIjowLCJwb2xpY3ktdG1wIjpbInJlYWR3cml0ZSJdLCJwb2xpY3ktdWEiOiJhZG1pbiIsInByZWZlcnJlZF91c2VybmFtZSI6Imxva2lvcyIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJhZG1pbiIsInVtYV9hdXRob3JpemF0aW9uIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwic2NvcGUiOiJvcGVuaWQgZW1haWwgcHJvZmlsZSIsInNlc3Npb25fc3RhdGUiOiJkNjdhNDBiNC1mOWJiLTQ5MjEtOTU4OS1mNDBhYmI0MzNmZjkiLCJzdWIiOiIxZTFjMzk2ZS1hYWFlLTRmOTgtODA1Yi0zZmU0ZGE2YjczY2QiLCJ0eXAiOiJCZWFyZXIifQ.6J1hhCVAHbmxU4b-2-qdLDyr_HQLU839it_wgsSHE6EfXVoYwQhUs6KKK3GNtdniTU_HL6ktpyqRH111vEEoMg
172.16.0.215 Content-Md5: SJNZaRc8BxZf967mlWakbw==
172.16.0.215 User-Agent: Boto3/1.9.253 Python/3.7.3 Linux/3.10.0-862.11.6.el7.x86_64 Botocore/1.12.253 Resource
172.16.0.215 <BODY>
172.16.0.215 [RESPONSE] [04:01:26.398] [ Duration 1.000549s  🠉 133 B  🠋 550 B ]
172.16.0.215 403 Forbidden
172.16.0.215 Vary: Origin
172.16.0.215 X-Amz-Request-Id: 15CFDC2E11A4F7DF
172.16.0.215 X-Xss-Protection: 1; mode=block
172.16.0.215 Accept-Ranges: bytes
172.16.0.215 Content-Length: 293
172.16.0.215 Content-Security-Policy: block-all-mixed-content
172.16.0.215 Content-Type: application/xml
172.16.0.215 Server: MinIO/RELEASE.2019-09-25T18-25-51Z
172.16.0.215 <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Key>resolv.conf</Key><BucketName>demo</BucketName><Resource>/demo/resolv.conf</Resource><RequestId>15CFDC2E11A4F7DF</RequestId><HostId>d501fc03-1ed3-4f03-b9db-44ce6235a93a</HostId></Error>
172.16.0.215
```

## Your Environment

I set up environment follow #8391 
* Version used (`minio version`): 
```
Version: 2019-09-25T18:25:51Z
Release-Tag: RELEASE.2019-09-25T18-25-51Z
Commit-ID: c8fbc943295af9caf51a9441a0b046c72a5a3f56
```
* Environment name and version (e.g. nginx 1.9.1):
```
docker: minio/minio:RELEASE.2019-09-25T18-25-51Z
docker: python:3.7.3-stretch
pip-19.3.1
boto3-1.9.253 (botocore-1.12.253 docutils-0.15.2 jmespath-0.9.4 python-dateutil-2.8.0 s3transfer-0.2.1 six-1.12.0 urllib3-1.25.6)

aws-cli 1.16.113 (I also test with aws-cli but it is not work.)
```
* Operating System and version (`uname -a`): `Linux hub.service.local 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
* Docker Version: `Docker version 1.13.1, build b2f74b2/1.13.1`

**Comment by harshavardhana** [comment]
@napat1412 

# Keycloak Quickstart Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io)

Keycloak is an open-source Identity and Access Management solution aimed at modern applications and services, this document covers configuring Keycloak to be used as an identity provider for MinIO server STS API.

## 1. Prerequisites

- JAVA 1.8 and above installed
- Download and start Keycloak server by following the [installation guide](https://www.keycloak.org/docs/latest/getting_started/index.html) (finish up to section 3.4)

## 2. Configure Keycloak

- Go to Users -> Click on the user -> Attribute, add a new attribute `Key` is `policy`, `Value` is name of the policy in minio (ex: `readwrite`). Click Add and then Save.
- Go to Clients -> Click on `account` -> Settings, set `Valid Redirect URIs` to `*`, expand `Advanced Settings` and set `Access Token Lifespan` to `1 Hours`, then Save.
- Go to Clients -> Client on `account` -> Mappers -> Create, `Name` can be any text, `Mapper Type` is `User Attribute`, `User Attribute` is `policy`, `Token Claim Name` is `policy`, `Claim JSON Type` is `string`, then Save.

Make sure you have added the right policy claims @napat1412 once done you can access using the temporary credentials

**Comment by napat1412** [comment]
After configuration keycloak follow @harshavardhana  suggestion. It's work.
But I have a question. From my understanding, we can't assign policy more than 1 policy to a user.
If i need dynamic policy, i should use minio + open policy agent(opa).
Do you have any suggestions for dymamic policy in minio?

**Comment by harshavardhana** [comment]
Dynamic policy is based on policies which can have variable substitution we support that too using look at #8393

**Comment by harshavardhana** [comment]
Closing this issue working as intended
