### ISSUE TITLE
Pending action items on config migration to KV

### ISSUE THREAD

**Issue by harshavardhana** [minio/minio#8434]
**not using template** for few TODOs with the merge of #8392 

- [x] Remaining migration of few env only values such as MINIO_ETCD* should be moved to config as etcdSubSys
- [x] Encrypt all objects inside `.minio.sys/config` prefix along with being able to rotate/re-encrypt the encrypted content.
- [ ] Merge env values with `mc admin config get` output using `env:` keyword
- [x] Implement `mc admin config env` command to document all the ENVs
- [x] Implement `mc admin config get --no-color` and `mc admin config get --json` mode 
- [x] Auto-completion support for all keys in all `mc admin config` sub-commands

Please add anything else that you might have @minio/core

**Comment by harshavardhana** [comment]
- [x] Encrypt all objects inside `.minio.sys/config` prefix along with being able to rotate/re-encrypt the encrypted content. - relevant PR is sent here https://github.com/minio/minio/pull/8439

**Comment by harshavardhana** [comment]
* [x]  Implement `mc admin config get --no-color` and `mc admin config get --json` mode

New PR sent #8441

**Comment by harshavardhana** [comment]
* [x] Implement `mc admin config env` command to document all the ENVs 

https://github.com/harshavardhana/minio/pull/new/support-env

This is implemented as well along with `mc admin config help --env` sub-flag

**Comment by harshavardhana** [comment]
-  [x] Remaining migration of few env only values such as MINIO_ETCD* should be moved to config as etcdSubSys

https://github.com/harshavardhana/minio/pull/new/etcd-config

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/8439 all the functionality is merged into single PR for easier review.

**Comment by krisis** [comment]
Steps to reproduce:
1. Start MinIO with valid values for env vars MINIO_ACCESS_KEY, MINIO_SECRET_KEY
2. Restart MiniO without these env vars.
3. We get the following error message
`ERROR Unable to initialize config system: invalid character '\u0091' looking for beginning of value`
This doesn't guide the user to provide the corresponding env vars to MinIO server during startup to resolve this issue.

**Comment by harshavardhana** [comment]
@krisis resolved the issue and PR updated #8439

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/8439 the PR is now updated without encryption and has all the following functionalities implemented

- [x] Remaining migration of few env only values such as MINIO_ETCD* should be moved to config as etcdSubSys
- [x] Implement `mc admin config help --env` command to document all the ENVs
- [x] Implement `mc admin config get --no-color` and `mc admin config get --json` mode

**Comment by harshavardhana** [comment]
### Pending items 

- [x] Bring safe mode operation for MinIO server which allows access to object layer to manipulate configs, but avoids enabling S3 APIs - this is to allow users to recover MinIO serves remotely
- [x] Encrypt all objects inside .minio.sys/config prefix along with being able to rotate/re-encrypt the encrypted content.
- [ ]  Merge env values with mc admin config get output using env: keyword, (this is still pending discussion)

### Future items

- [x] Auto-completion support for all keys in all mc admin config sub-commands

**Comment by harshavardhana** [comment]
### Pending items

- [x] Validate KV settings without ENV overrides to disallow setting incorrect values

```
> I see an issue with not validating etcd endpoints at the time of setting it via cli (may arise for other notification targets and kms also)
> test scenario -
> 
> ```
> export MINIO_ETCD_ENDPOINTS=http://localhost:2379
> ./minio server ~/export
> # Now change etcd config
> ➜  mc git:(fbf61127) mc admin config set myminio etcd coredns_path="/skyxxx" state="on" endpoints="http://localhost:1000000"
> etcd coredns_path=/skyxxx state=on endpoints=http://localhost:1000000
> Setting new key has been successful.
> Please restart your server with `mc admin service restart myminio`.
> 
> ➜  mc git:(fbf61127) mc admin service restart myminio
> Restart command successfully sent to `myminio`.
> Restarted `myminio` successfully.
> ```
> 
> Everything is happy until the server is killed and unset MINIO_ETCD_ENDPOINTS. Now the server will not start because of invalid port in the etcd endpoint on the config file.
> 
> ```
> ERROR Unable to initialize etcd config: port must be between 0 to 65535
> ```
```

**Comment by harshavardhana** [comment]
https://github.com/minio/minio/pull/8483 another pending item to enhance the `mc admin config history` output

**Comment by poornas** [comment]
Some config validations seem to have broken in the latest PR (safe mode)
Cache gets enabled in server mode even when state=off. Similarly found that turning off kms settings set in config doesn't disable config from taking effect. 
```
➜  testpgm mc admin config set myminio cache drives="/tmp/cache{1...4}"  state="on"      
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio`.

➜  testpgm mc admin service restart myminio                                        
Restart command successfully sent to `myminio`.
Restarted `myminio` successfully.
➜  testpgm mc cp /etc/issue myminio/testbucket
/etc/issue:      26 B / 26 B ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 100.00% 2.43 KiB/s 0s


➜  minio git:(e01529595) ./minio server ~/export
**Disk caching is recommended only for gateway deployments**
Cache Capacity: 238 GiB Free, 882 GiB Total
```

**Comment by harshavardhana** [comment]
Caching is once again disabled in server mode now @poornas - also SSE_* are honored properly as well.

**Comment by poornas** [comment]
etcd endpoint is not being validated when MINIO_ETCD_ENDPOINTS is set in NAS gateway - note the validation is ok in server mode, and if etcd set via `mc admin config`

```
export MINIO_ETCD_ENDPOINTS=http://localhost:2379  # etcd server is not running here.
./minio gateway nas ~/export   # gateway comes up anyway without showing any error
```

**Comment by harshavardhana** [comment]
You need to enable state as well @poornas

**Comment by harshavardhana** [comment]
But that may be incompatible so need to be fixed

**Comment by poornas** [comment]
> But that may be incompatible so need to be fixed

WatchConfigNASDisk swallows the validation error  returned by loadConfig

**Comment by poornas** [comment]
```
➜  minio git:(06d296f7f) ./minio server /tmp/data{1...4}
Server startup failed with 'Unable to initialize config system: Unable to initialize etcd config: dial tcp 127.0.0.1:2379: connect: connection refused'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
```
Instead of pointing to `mc admin`, we need comprehensive docs on fixing the config and recovering to fully operational mode here.

**Comment by harshavardhana** [comment]
Scenario auto-heal of config when one of the node is down in distributed setup
```
#!/bin/bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio123"

set -x
endpoints=""
for i in {02..05}; do
    endpoints="$endpoints http://127.0.0.1:90${i}/tmp/${i}"
done

for i in {02..05}; do
    minio server --address ":90${i}" ${endpoints} &
done
```

```
~ ~ jq .stat.modTime /tmp/*/.minio.sys/config/config.json/xl.json
"2019-11-10T02:10:28.72172403Z"
"2019-11-10T02:10:28.72172403Z"
"2019-11-10T02:10:28.72172403Z"
"2019-11-10T02:10:28.72172403Z"
```

```
~ killall minio
Exiting on signal: TERMINATED
Exiting on signal: TERMINATED
Exiting on signal: TERMINATED
Exiting on signal: TERMINATED
```

Rotate creds when one of the server is down
```
#!/bin/bash

export MINIO_ACCESS_KEY="minio"
export MINIO_SECRET_KEY="minio1234"
export MINIO_ACCESS_KEY_OLD="minio"
export MINIO_SECRET_KEY_OLD="minio123"

endpoints=""
for i in {02..05}; do
    endpoints="$endpoints http://127.0.0.1:90${i}/tmp/${i}"
done

for i in {02..04}; do
    minio server --address ":90${i}" ${endpoints} &
done
```
```
~ jq .stat.modTime /tmp/*/.minio.sys/config/config.json/xl.json
"2019-11-10T02:12:04.737451357Z"
"2019-11-10T02:12:04.737451357Z"
"2019-11-10T02:12:04.737451357Z"
"2019-11-10T02:10:28.72172403Z"
```


All start-up, now bring the downed node back
```
~ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio1234 minio server --address :9005 http://127.0.0.1:9002/tmp/02 http://127.0.0.1:9003/tmp/03 http://127.0.0.1:9004/tmp/04 http://127.0.0.1:9005/tmp/05
Status:         4 Online, 0 Offline. 
...
```

Auto-heal kicks in 
```
~ jq .stat.modTime /tmp/*/.minio.sys/config/config.json/xl.json
"2019-11-10T02:12:04.737451357Z"
"2019-11-10T02:12:04.737451357Z"
"2019-11-10T02:12:04.737451357Z"
"2019-11-10T02:12:04.737451357Z"
```

**Comment by harshavardhana** [comment]
Pending items once again 

- [ ] Merge env values with mc admin config get output using env: keyword, (this is still pending discussion)
- [ ] Instead of pointing to mc admin, we need comprehensive docs on fixing the config and recovering to fully operational mode here.
```
minio git:(06d296f7f) ./minio server /tmp/data{1...4}
Server startup failed with 'Unable to initialize config system: Unable to initialize etcd config: dial tcp 127.0.0.1:2379: connect: connection refused'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
```

**Comment by harshavardhana** [comment]
### We need to test situations like
- migration from old config to new
- migration from old config to new encrypted config
- use master mc to see all functionalities presented work
- look for any crashes during the operation of config updates and deletes
- look for any functionality issues with env being set

### Two things pending still to be conveyed
- if somehow you reach safe mode - extensive documentation how to get out of the situation
- merging of ENVs with config values, which is minor will add in another PR (format is already decided by AB). Envs will override always and any set will succeed as well but

> Note: incorrect set of configs are still not allowed even with env overrides.

**Comment by nitisht** [comment]
```
$ ./mc admin config set myminio worm state=on
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio`.

$ ./mc admin config get myminio worm
# Settings for WORM, after migrating config
worm state="on" 
```

Server reports the value of a config item as `on`, without a restart. This is a change from earlier behaviour. If a restart is missed by the user, this may become confusing

**Comment by nitisht** [comment]
On FS mode, trying to update from `RELEASE.2018-05-10T00-00-42Z` to latest master, see below behaviour. Note that it does finally start after another try

```
$ ./minio.RELEASE.2018-05-10T00-00-42Z server /tmp/test

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 1 year ago ┃
┃ Update: Run `minio update`                                    ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Drive Capacity: 148 GiB Free, 221 GiB Total

Endpoint:  http://192.168.86.184:9000  http://172.17.0.1:9000  http://127.0.0.1:9000
AccessKey: TO3LNW50V03K395HK6ZO 
SecretKey: /uVFgpiR0lmi7zKGSpY1/5/ZUPIjXKush7saIf2t 
Region:    us-east-1

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.86.184:9000 TO3LNW50V03K395HK6ZO /uVFgpiR0lmi7zKGSpY1/5/ZUPIjXKush7saIf2t

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
^CExiting on signal interrupt

$ ./minio server /tmp/test
Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 1s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 3s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 5s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 12s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 17s)

^CAnother minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 46s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 1m4s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 1m10s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 1m15s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 1m23s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 1m47s)

Another minio process(es) might be holding a lock to the file /tmp/test/.minio.sys/format.json. Please kill that minio process(es) (elapsed 1m47s)

```

**Comment by nitisht** [comment]
Server moved to safe mode when updating a local XL setup, with reason provided as rrs can't be empty. Earlier it was possible to start the server with RRS being empty - is this intended?

```
$ ./minio.RELEASE.2018-05-10T00-00-42Z server /tmp/test{1...4}
Created minio configuration file successfully at /home/nitish/.minio
Drive Capacity: 297 GiB Free, 443 GiB Total
Status:         4 Online, 0 Offline. 

Endpoint:  http://192.168.86.184:9000  http://172.17.0.1:9000  http://127.0.0.1:9000
AccessKey: FJK9Q83Z463LSHQOGYDU 
SecretKey: amnySfQWGYb3J/4yyI5adhD3wtOi12iDDs0c2DT+ 

Browser Access:
   http://192.168.86.184:9000  http://172.17.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.86.184:9000 FJK9Q83Z463LSHQOGYDU amnySfQWGYb3J/4yyI5adhD3wtOi12iDDs0c2DT+

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide
^CExiting on signal interrupt

$ ./minio server /tmp/test{1...4}
Configuration file /home/nitish/.minio/config.json migrated from version '23' to '24' successfully.
Configuration file /home/nitish/.minio/config.json migrated from version '24' to '25' successfully.
Configuration file /home/nitish/.minio/config.json migrated from version '25' to '26' successfully.
Configuration file /home/nitish/.minio/config.json migrated from version '26' to '27' successfully.
Configuration file /home/nitish/.minio/config.json migrated from version '27' to '28' successfully.
Configuration file config/config.json migrated from version '28' to '29' successfully.
Configuration file config/config.json migrated from version '29' to '30' successfully.
Configuration file config/config.json migrated from version '30' to '31' successfully.
Configuration file config/config.json migrated from version '31' to '32' successfully.
Configuration file config/config.json migrated from version '32' to '33' successfully.
Configuration file config/config.json migrated from version '33' to new KV format successfully.
Server startup failed with 'Unable to initialize config system: Unable to initialize storage class config: 'rrs' key cannot be empty if you wish to enable storage class'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
Status:         4 Online, 0 Offline. 
Endpoint:  http://192.168.86.184:9000  http://172.17.0.1:9000  http://127.0.0.1:9000      
AccessKey: FJK9Q83Z463LSHQOGYDU 
SecretKey: amnySfQWGYb3J/4yyI5adhD3wtOi12iDDs0c2DT+ 
Region:    us0

Command-line Access: https://docs.min.io/docs/minio-admin-complete-guide.html
   $ mc config host add myminio http://192.168.86.184:9000 FJK9Q83Z463LSHQOGYDU amnySfQWGYb3J/4yyI5adhD3wtOi12iDDs0c2DT+ --api s3v4
   $ mc admin --help


```

**Comment by kanagarajkm** [comment]
Following error is thrown while migrating a setup which has `MINIO_ACCESS_KEY` and `MINIO_SECRET_KEY` set on the environment. 

```
$ minio version
Version: 2019-10-12T01:39:57Z
Release-Tag: RELEASE.2019-10-12T01-39-57Z
Commit-ID: bd106408462ecef70debf51f1e6179de950c5812

$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio server /tmp/data
Endpoint:  http://192.168.86.145:9000  http://172.17.0.1:9000  http://172.20.0.1:9000  http://192.168.122.1:9000  http://127.0.0.1:9000          
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://192.168.86.145:9000  http://172.17.0.1:9000  http://172.20.0.1:9000  http://192.168.122.1:9000  http://127.0.0.1:9000          

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.86.145:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
^CExiting on signal: INTERRUPT

```

```
$ ./minio version
Version: 2019-11-11T06:39:29Z
Release-Tag: DEVELOPMENT.2019-11-11T06-39-29Z
Commit-ID: 822eb5ddc76c7edb52b7f38550caf58717c76ea1

$ MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ./minio server /tmp/data
Attempting encryption of all config, IAM users and policies on MinIO backend
Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: ReadMapCB: expect { or n, but found , error found in #0 byte of ...||..., bigger context ...||...'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
Endpoint:  http://192.168.86.145:9000  http://172.17.0.1:9000  http://172.20.0.1:9000  http://192.168.122.1:9000  http://127.0.0.1:9000          
AccessKey: minio 
SecretKey: minio123 

Command-line Access: https://docs.min.io/docs/minio-admin-complete-guide.html
   $ mc config host add myminio http://192.168.86.145:9000 minio minio123 --api s3v4
   $ mc admin --help
```

**Comment by nitisht** [comment]
when the rotating credentials are incorrect via ENV vars, e.g.

```
$ export MINIO_SECRET_KEY=newminio1231
$ export MINIO_ACCESS_KEY=minio
$ ./minio server /tmp/kj
Attempting rotation of encrypted config, IAM users and policies on MinIO with newly supplied credentials
Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: Invalid rotating credentials'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
Endpoint:  http://192.168.86.184:9000  http://172.17.0.1:9000  http://127.0.0.1:9000      
AccessKey: newminio 
SecretKey: newminio1231 

Command-line Access: https://docs.min.io/docs/minio-admin-complete-guide.html
   $ mc config host add myminio http://192.168.86.184:9000 newminio newminio1231 --api s3v4
   $ mc admin --help
^CExiting on signal: INTERRUPT

```

There doesn't seems to be a way this can be fixed via `mc admin command`, hence IMO there is no point in starting the server at all

**Comment by Praveenrajmani** [comment]
I get this while migration

![image](https://user-images.githubusercontent.com/5410427/68582664-4a3d5280-04a1-11ea-8ef2-6db3929f9286.png)

**Comment by kanagarajkm** [comment]
Audit logging is not working.

MinIO is started with the following command
```
$ MINIO_LOGGER_HTTP_AUDIT_ENDPOINT_target1=http://webhook.site/6f29ab59-bfd3-4358-9508-021da43d3d57 MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 ./minio server /tmp/data
```

Some operations were performed using `mc`. But no events are received by the webhook server.

**Comment by vielmetti** [comment]
Like @Praveenrajmani I am seeing the error

```Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: ReadMapCB: expect { or n, but found  , error found in #0 byte of ...||..., bigger context ...||...'```

This is on a fresh install of the development version, running on arm64.

**Comment by poornas** [comment]
should you be allowing updates to default configuration?  for example mc allows
```
mc admin config set myminio notify_elasticsearch format="namespace" index="myminio" queue_dir="" queue_limit="0" state="on" url="http://localhost:9200"
```
Note the default target in the SQS ARNs below -- the event notifications fails 
```
tp://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                  
AccessKey: minio 
SecretKey: minio123 
SQS ARNs:  arn:minio:sqs::_:elasticsearch

Browser Access:
   http://192.168.1.196:9000  http://192.168.122.1:9000  http://172.16.238.1:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                  

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.196:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

```

On the same note, `mc event add  myminio/images arn:minio:sqs::_:elasticsearch --suffix .jpg` should be disallowed on server side.

**Comment by harshavardhana** [comment]
Yes default config updates are allowed, default is nothing but a special target. I don't think it should not be disallowed it is implemented as per what @abperiasamy wanted. 

What is the issue, does it not work?

**Comment by poornas** [comment]
> Yes default config updates are allowed, default is nothing but a special target. I don't think it should not be disallowed it is implemented as per what @abperiasamy wanted.
> 
> What is the issue, does it not work?

nvm, it does work as expected.

**Comment by poornas** [comment]
When AK,SK env is not set, and credentials are changed via `mc admin`, should see server startup without error since .minio.sys/config dir is not encrypted. Server goes into safe mode as seen here.
```
➜  minio git:(ab8666673) ✗ mc admin config set myminio credentials access_key=minio secret_key=minio12345
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio`.

➜  minio git:(ab8666673) ✗ mc admin service restart myminio
Restart command successfully sent to `myminio`.
Failed to restart `myminio`. error: The access key ID you provided does not exist in our records.

➜  minio git:(ab8666673) ✗ ./minio server ~/export3
Configuration file config/config.json migrated from version '28' to '29' successfully.
Configuration file config/config.json migrated from version '29' to '30' successfully.
Configuration file config/config.json migrated from version '30' to '31' successfully.
Configuration file config/config.json migrated from version '31' to '32' successfully.
Configuration file config/config.json migrated from version '32' to '33' successfully.
Configuration file config/config.json migrated from version '33' to new KV format successfully.
Endpoint:  http://192.168.1.196:9000  http://192.168.122.1:9000  http://172.16.238.1:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                  
AccessKey: minio 
SecretKey: minio123 
Region:    us-west-1

Browser Access:
   http://192.168.1.196:9000  http://192.168.122.1:9000  http://172.16.238.1:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                  

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.196:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Restarting on service signal
Server startup failed with 'Unable to handle encrypted backend for config, iam and policies: Credentials missing'
Server switching to safe mode
Please use 'mc admin' commands to fix this issue
Endpoint:  http://192.168.1.196:9000  http://192.168.122.1:9000  http://172.16.238.1:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://172.19.0.1:9000  http://127.0.0.1:9000                  
AccessKey:  
SecretKey:  


```

 "credentials": {
    "_": {
      "access_key": "minio",
      "comment": "Settings for credentials, after migrating config",
      "secret_key": "minio123",
      "state": "on"
    }
  },
Credentials did not update either

**Comment by Praveenrajmani** [comment]
![image](https://user-images.githubusercontent.com/5410427/68646887-65ac6a00-0542-11ea-82e7-a503e17eb6c5.png)

The title `# Default settings for AMQP notification` can be on the next line..

**Comment by kanagarajkm** [comment]
Inconsistent status on user list,  before and after upgrade

Before upgrade
```
$ mc admin user list local
enabled    SSVCETQHVX0ENLAEKHCR  readwrite           
enabled    UPUXDPCDQZPRL2GZDRG3  readwrite
```

Upgraded and created a STS user
```
$ ./mc admin user list local
on         I1ACU2241RWTPUQFU3YS  readwrite           
enabled    SSVCETQHVX0ENLAEKHCR  readwrite           
enabled    UPUXDPCDQZPRL2GZDRG3  readwrite
```

**Comment by vadmeste** [comment]
Simple migration leads to a little formatting issue in mc admin config get output:

```
$ ./minio.RELEASE.2018-05-10T00-00-42Z server /tmp/xl/{1..4}
Control-C
$ minio server /tmp/xl/{1..4}
```

In another terminal
```
$ mc admin config get myminio/ notify_mysql
# Default settings for MySQL notification
notify_mysql password="" port="" queue_limit="0" format="namespace" queue_dir="" state="off" host="" table="" database="" dsn_string="" username="" # Settings for MySQL notification, after migrating config
notify_mysql:1 database="" format="" password="" table="" queue_dir="" state="off" dsn_string="" port="" host="" queue_limit="0" username=""    
```

**Comment by harshavardhana** [comment]
This is fixed in PR #8510

**Comment by vadmeste** [comment]
> This is fixed in PR #8510

I don't think it does, it tried it twice with your PR #8510

**Comment by vadmeste** [comment]
If I am correct there is a problem with logging in gateway mode:
```
2019/11/14 15:45:39 http: panic serving 192.168.100.20:32964: runtime error: invalid memory address or nil pointer dereference
goroutine 83 [running]:
net/http.(*conn).serve.func1(0xc000373040)
        /home/vadmeste/work/go/src/net/http/server.go:1767 +0x139
panic(0x1737120, 0x2e32300)
        /home/vadmeste/work/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x1ca84e0, 0xc0002fe8c0, 0xc00044c500)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/generic-handlers.go:765 +0x248
panic(0x1737120, 0x2e32300)
        /home/vadmeste/work/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.(*HTTPConsoleLoggerSys).Send(0x0, 0x1932500, 0xc0005c4000, 0x19bd1dd, 0x5, 0xc0003382a0, 0x1e)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/consolelogger.go:126 +0x136
github.com/minio/minio/cmd/logger.logIf(0x1caf8e0, 0xc0003c3200, 0x1c7abc0, 0xc000336160, 0x0, 0x0, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/logger/logger.go:380 +0x616
github.com/minio/minio/cmd/logger.LogIf(0x1caf8e0, 0xc0003c3200, 0x1c7abc0, 0xc000336160, 0x0, 0x0, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/logger/logger.go:307 +0x95
github.com/minio/minio/cmd.toAPIErrorCode(0x1caf8e0, 0xc0003c3200, 0x1c7abc0, 0xc000336160, 0x9)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/api-errors.go:1700 +0x47b
github.com/minio/minio/cmd.toAPIError(0x1caf8e0, 0xc0003c3200, 0x1c7abc0, 0xc000336160, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/api-errors.go:1725 +0x9e
github.com/minio/minio/cmd.objectAPIHandlers.GetBucketLocationHandler(0x1a4f3f8, 0x1a4f3e8, 0xc0005b1850, 0xc0005b1860, 0x1ca5da0, 0xc00038db40, 0xc00044c700)
        /home/vadmeste/work/gospace/src/github.com/minio/minio/cmd/bucket-handlers.go:159 +0x5f7
net/http.HandlerFunc.ServeHTTP(...)
```

An easy way to reproduce this:
```
1.
MINIO_ACCESS_KEY=minio MINIO_SECRET_KEY=minio123 minio gateway azure

2.
mc config host add myazure http://localhost:9000 minio minio123 
```

**Comment by harshavardhana** [comment]
Sure will fix it ..

**Comment by harshavardhana** [comment]
Closing this umbrella issue.
