### ISSUE TITLE
Failure to build browser/ui-assets.go

### ISSUE THREAD

**Issue by gversmee** [minio/minio#8449]
## Expected Behavior
We should be able to build `browser/ui-assets.go` within the `Dockerfile` in order to customize the UI.

## Current Behavior
Here is the Dockerfile I wrote:
```
FROM golang:1.13-alpine

ENV GOPATH=/go \
    CGO_ENABLED=0 \
    GO111MODULE=on

RUN go get github.com/elazarl/go-bindata-assetfs/... && \
    wget https://bin.equinox.io/a/75VeNN6mcnk/github-com-kevinburke-go-bindata-go-bindata-linux-amd64.tar.gz && \
    tar xvf github-com-kevinburke-go-bindata-go-bindata-linux-amd64.tar.gz -C /usr/bin && \
    apk add --no-cache git yarn

RUN git clone https://github.com/minio/minio

RUN cd /go/minio/browser && yarn && yarn release

RUN cd /go/minio && go install -v -ldflags "$(go run buildscripts/gen-ldflags.go)"

FROM alpine:3.9

ENV MINIO_UPDATE=off \
    MINIO_ACCESS_KEY_FILE=access_key \
    MINIO_SECRET_KEY_FILE=secret_key \
    MINIO_KMS_MASTER_KEY_FILE=kms_master_key

EXPOSE 9000

COPY --from=0 /go/bin/minio /usr/bin/minio
COPY --from=0 /go/minio/dockerscripts/docker-entrypoint.sh /usr/bin/

RUN  apk add --no-cache ca-certificates 'curl>7.61.0' 'su-exec>=0.2' && \
     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
```

Building the Docker image fails at the `yarn release`, giving the following output:
```
yarn run v1.16.0
$ NODE_ENV=production MINIO_UI_BUILD=RELEASE node build.js
Running webpack -p --config webpack.production.config.js
{ Error: Command failed: webpack -p --config webpack.production.config.js

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
  killed: false,
  code: 2,
  signal: null,
  cmd: 'webpack -p --config webpack.production.config.js' }
Done in 21.85s.
```

## Steps to Reproduce (for bugs)
Run the Dockerfile above

## Regression
The Dockerfile above worked until commit 941fed8e4ae990d5bb1b354f2045af3eb8df6f02

**Comment by harshavardhana** [comment]
We do not support yarn, so please use `npm run release` - make sure to cleanup your node_modules 

Also why are you generating new assets ?

**Comment by gversmee** [comment]
I have the exact same error message when using `npm`.
I want to customize the css, that's why I'm generating new assets.

**Comment by harshavardhana** [comment]
@gversmee I can't reproduce it, so most probably it's on your side - try to cleanup node_modules, etc - not sure what else we can help here.

**Comment by harshavardhana** [comment]
Best way to know what you did and what is the issue here run 

```
~ webpack --debug -p --config webpack.production.config.js
```

**Comment by gversmee** [comment]
I found the error. I used a modified version of `variables.less`. After commit #941fed8e4ae990d5bb1b354f2045af3eb8df6f02, there was a section added to this file, and I hadn't updated mine. Now it works fine.
If anyone is interested, here is the `Dockerfile` I'm using.

```
FROM golang:1.13-alpine

ENV GOPATH=/go \
    CGO_ENABLED=0 \
    GO111MODULE=on

RUN go get github.com/elazarl/go-bindata-assetfs/... && \
    go get github.com/go-bindata/go-bindata/go-bindata && \
    apk add --no-cache git nodejs npm && \
    git clone https://github.com/minio/minio --depth 1

# Copy custom files in the container
COPY ./browser/. /go/minio/browser/

RUN cd /go/minio/browser && npm install && npm run release && \
    cd /go/minio && go install -ldflags "$(go run buildscripts/gen-ldflags.go)"

FROM alpine:3.9

ENV MINIO_UPDATE=off \
    MINIO_ACCESS_KEY_FILE=access_key \
    MINIO_SECRET_KEY_FILE=secret_key \
    MINIO_KMS_MASTER_KEY_FILE=kms_master_key

EXPOSE 9000

COPY --from=0 /go/bin/minio /usr/bin/minio
COPY --from=0 /go/minio/dockerscripts/docker-entrypoint.sh /usr/bin/

RUN  apk add --no-cache ca-certificates 'curl>7.61.0' 'su-exec>=0.2' && \
     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf

ENTRYPOINT ["/usr/bin/docker-entrypoint.sh"]
```
