### ISSUE TITLE
`brew test minio/stable/minio` command fails

### ISSUE THREAD

**Issue by kaankabalak** [minio/minio#8680]
When we install the package using `brew install minio/stable/minio` and test it using `brew test minio/stable/minio`, the test fails with the following message. It seems like test command successfully starts the server while we are expecting a connection refused error.

```
An exception occurred within a child process:
  Test::Unit::AssertionFailedError: </getsockopt:\ connection\ refused/> expected to be =~
<"Configuration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '14' to '15' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '15' to '16' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '16' to '17' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '17' to '18' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '18' to '19' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '19' to '20' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '20' to '21' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '21' to '22' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '22' to '23' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '23' to '24' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '24' to '25' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '25' to '26' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '26' to '27' successfully.\nConfiguration file /private/tmp/minio-test-20190827-95665-io0pyi/config.json migrated from version '27' to '28' successfully.\nConfiguration file config/config.json migrated from version '28' to '29' successfully.\nConfiguration file config/config.json migrated from version '29' to '30' successfully.\nConfiguration file config/config.json migrated from version '30' to '31' successfully.\nConfiguration file config/config.json migrated from version '31' to '32' successfully.\nConfiguration file config/config.json migrated from version '32' to '33' successfully.\n\nAPI: SYSTEM()\nTime: 16:31:11 PDT 08/27/2019\nDeploymentID: f62297e5-572f-4b9c-ab0b-75d02c52cc93\nError: dial tcp 127.0.0.1:6379: connect: connection refused\n       3: cmd/config-current.go:774:cmd.getNotificationTargets()\n       2: cmd/notification.go:1039:cmd.NewNotificationSys()\n       1: cmd/server-main.go:370:cmd.serverMain()\nEndpoint:  http://192.168.1.170:9000  http://127.0.0.1:9000            \n\nBrowser Access:\n   http://192.168.1.170:9000  http://127.0.0.1:9000            \n\nObject API (Amazon S3 compatible):\n   Go:         https://docs.min.io/docs/golang-client-quickstart-guide\n   Java:       https://docs.min.io/docs/java-client-quickstart-guide\n   Python:     https://docs.min.io/docs/python-client-quickstart-guide\n   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide\n   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide\nExiting on signal: INTERRUPT\n">.
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:55:in `block in assert_block'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1627:in `_wrap_assertion'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:53:in `assert_block'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:542:in `block in assert_match'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:1632:in `_wrap_assertion'
/Library/Ruby/Gems/2.3.0/gems/test-unit-3.1.5/lib/test/unit/assertions.rb:533:in `assert_match'
/usr/local/Homebrew/Library/Taps/minio/homebrew-stable/minio.rb:62:in `block in <class:Minio>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1727:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:479:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1726:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:866:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1725:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1964:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1963:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1719:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:30:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/timeout.rb:106:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:29:in `<main>'
```

**Comment by harshavardhana** [comment]
Moved the issue here from homebrew tap, @kaankabalak do you have any recommendation for a fix?

**Comment by harshavardhana** [comment]
`brew test` is fixed now https://github.com/minio/homebrew-stable/commit/6fdf746d4e1745f2d9905d06e526903ce23a4854
