### ISSUE TITLE
"mc admin heal -r <alias>" cause panic  (integer divide by zero)

### ISSUE THREAD

**Issue by ebozduman** [minio/minio#8916]
Running `"mc admin heal -r dist/"` caused the following crash on my 4 node/4 disk MinIO server where `"dist"` is my alias.

```
$ mc admin heal -r dist/
panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/minio/mc/cmd.hri.getReplicatedFileHCCChange.func1(0x0, 0x0, 0x0, 0x4118ea, 0x90)
	/home/ersan/work/src/github.com/minio/mc/cmd/admin-heal-result-item.go:58 +0xc1
github.com/minio/mc/cmd.hri.getReplicatedFileHCCChange(0xc00015dcd8, 0xc00038ac30, 0x0, 0xc0004180d8, 0xed5c54878, 0x0, 0xb4901be5)
	/home/ersan/work/src/github.com/minio/mc/cmd/admin-heal-result-item.go:66 +0x67
github.com/minio/mc/cmd.(*uiData).updateStats(0xc00015e460, 0x1, 0xc00029d3e0, 0x8, 0x0, 0x0, 0x0, 0x0, 0xc00029d3f0, 0xb, ...)
	/home/ersan/work/src/github.com/minio/mc/cmd/admin-heal-ui.go:132 +0x123
github.com/minio/mc/cmd.(*uiData).UpdateDisplay(0xc00015e460, 0xc00015e048, 0x0, 0x0)
	/home/ersan/work/src/github.com/minio/mc/cmd/admin-heal-ui.go:380 +0x109
github.com/minio/mc/cmd.(*uiData).DisplayAndFollowHealStatus(0xc00015e460, 0x7ffc5156aec1, 0x5, 0xc00029d3c8, 0x8, 0x0, 0x0, 0x27e8e8fa, 0xed5c54878, 0x0, ...)
	/home/ersan/work/src/github.com/minio/mc/cmd/admin-heal-ui.go:428 +0x275
github.com/minio/mc/cmd.mainAdminHeal(0xc0002e7d40, 0x0, 0x2e7d40)
	/home/ersan/work/src/github.com/minio/mc/cmd/admin-heal.go:257 +0xf94
github.com/minio/cli.HandleAction(0xc06080, 0xd76f18, 0xc0002e7d40, 0xc00035db00, 0x0)
	/home/ersan/work/pkg/mod/github.com/minio/cli@v1.22.0/app.go:498 +0xc8
github.com/minio/cli.Command.Run(0xd215db, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd4ca7c, 0x2f, 0x0, ...)
	/home/ersan/work/pkg/mod/github.com/minio/cli@v1.22.0/command.go:225 +0x991
github.com/minio/cli.(*App).RunAsSubcommand(0xc0002e76c0, 0xc0002e6340, 0x0, 0x0)
	/home/ersan/work/pkg/mod/github.com/minio/cli@v1.22.0/app.go:387 +0x7fa
github.com/minio/cli.Command.startApp(0xd22133, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd309eb, 0x14, 0x0, ...)
	/home/ersan/work/pkg/mod/github.com/minio/cli@v1.22.0/command.go:313 +0x809
github.com/minio/cli.Command.Run(0xd22133, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0xd309eb, 0x14, 0x0, ...)
	/home/ersan/work/pkg/mod/github.com/minio/cli@v1.22.0/command.go:111 +0x127b
github.com/minio/cli.(*App).Run(0xc0002e6000, 0xc000030050, 0x5, 0x5, 0x0, 0x0)
	/home/ersan/work/pkg/mod/github.com/minio/cli@v1.22.0/app.go:261 +0x6ab
github.com/minio/mc/cmd.Main(0xc000030050, 0x5, 0x5)
	/home/ersan/work/src/github.com/minio/mc/cmd/main.go:113 +0x29c
main.main()
	/home/ersan/work/src/github.com/minio/mc/main.go:34 +0x45
```

## Expected Behavior
No panic.

## Current Behavior
Crash (integer divide by zero)

## Steps to Reproduce (for bugs)
1. Start MinIO server with 4 nodes/4  disks
2. Create a bucket
3. Remove one of the `".minio.sys"` directories of a node in the local filesystem using Linux OS `"rm -rf"` command
4. Run `"mc admin heal -r dist/"` and cause the crash

## Regression
Not sure

## Your Environment
* Version used (`minio version`): DEVELOPMENT.2020-01-30T18-41-57Z
* Environment name and version (e.g. nginx 1.9.1): MinIO server with 4 nodes/4 disks
* Server type and version: Xl
* Operating System and version (`uname -a`): Linux ersanscomputer 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
e

Additional information:
This  behavior is not limited to `"--recrusive"` option.
`"mc admin heal <alias>/<bucket-name>"` in the same setup.

**Comment by klauspost** [comment]
This seems like an `mc` issue. Even if it is a server issue we should also fix it on the mc side.

**Comment by vadmeste** [comment]
@ebozduman it doesn't seem this is reproducible anymore with master. Could you try again on your side to check if I missed something ?

**Comment by ebozduman** [comment]
@vadmeste ,
You are right.
I also cannot see that or any other anomaly anymore. 
Closing the issue.
