### ISSUE TITLE
Select on parquet with DATA_PAGE_V2 format crashes minio server

### ISSUE THREAD

**Issue by yaozongyou** [minio/minio#9007]
Running sql on parquet with DATA_PAGE_V2 format may corrupt minio server

using mc running the following command:
./mc sql --query "select * from S3Object" myminio/testbucket/hello.parquet

Here is the backtrace:
```bash
# ./minio server /data/
Endpoint:  http://192.168.56.99:9000  http://10.0.2.15:9000  http://127.0.0.1:9000
AccessKey: minioadmin
SecretKey: minioadmin

Browser Access:
   http://192.168.56.99:9000  http://10.0.2.15:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.56.99:9000 minioadmin minioadmin

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'
2020/02/13 16:59:26 http: panic serving 192.168.56.99:41552: runtime error: integer divide by zero
goroutine 130 [running]:
net/http.(*conn).serve.func1(0xc00071f0e0)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1887360, 0x3091760)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:776 +0x248       panic(0x1887360, 0x3091760)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/parquet-go.readDeltaBinaryPackedInt(0xc0015330d8, 0x10, 0xc001532f20, 0x40c2d6, 0xc0003856e0, 0x30)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/decode.go:342 +0x642
github.com/minio/parquet-go.readDeltaLengthByteArrays(0xc0015330d8, 0x18505c0, 0xc000384ea0, 0xc000b459f8, 0xc001532f50, 0x4462bc)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/decode.go:377 +0x40
github.com/minio/parquet-go.readDataPageValues(0xc0015330d8, 0x6, 0x6, 0x0, 0x1, 0x0, 0x1, 0x0, 0x78, 0xc000bb1a00, ...)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/decode.go:473 +0x6cb
github.com/minio/parquet-go.readPage(0xc000374500, 0xc0012344d0, 0xc000384ea0, 0xc0003742c0, 0x4, 0x4, 0xc0003748c0, 0x0, 0x3ffffffffffffff, 0xffffffffffffffff, ...)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/page.go:263 +0x5cd
github.com/minio/parquet-go.(*column).readPage(0xc000bb1900)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/column.go:110 +0x71
github.com/minio/parquet-go.(*column).read(0xc000bb1900, 0xc0003851a0, 0xc000b459f8, 0x4)        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/column.go:139 +0xd6
github.com/minio/parquet-go.(*Reader).Read(0xc0003dc540, 0x126a8b0, 0x8, 0x1bbe0e8)              /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/reader.go:147 +0x1c1
github.com/minio/minio/pkg/s3select/parquet.(*Reader).Read(0xc0007b5950, 0x0, 0x0, 0xc0003dc5b0, 0x1e174c0, 0x0, 0x0)
        /data/richardyao/workspace/github/minio/pkg/s3select/parquet/reader.go:37 +0x3e  github.com/minio/minio/pkg/s3select.(*S3Select).Evaluate(0xc000212000, 0x1e47600, 0xc00009c1c0)
        /data/richardyao/workspace/github/minio/pkg/s3select/select.go:433 +0x1cd        github.com/minio/minio/cmd.objectAPIHandlers.SelectObjectContentHandler(0x1bbdc80, 0x1bbdc70, 0xc00096c2b0, 0xc00096c2d0, 0x1e47600, 0xc00009c1c0, 0xc0008cc100)
        /data/richardyao/workspace/github/minio/cmd/object-handlers.go:237 +0x1945       net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x1e47600, 0xc00009c1c0, 0xc0008cc100)            /data/richardyao/workspace/github/minio/cmd/handler-utils.go:353 +0x148
net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.collectAPIStats.func1(0x1e478c0, 0xc000616320, 0xc0008cc100)          /data/richardyao/workspace/github/minio/cmd/handler-utils.go:374 +0x158
net/http.HandlerFunc.ServeHTTP(0xc0003e0880, 0x1e478c0, 0xc000616320, 0xc0008cc100)              /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0007a00c0, 0x1e478c0, 0xc000616320, 0xc0002ebb00)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe2
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x1e18960, 0xc0007a00c0, 0x1e47640, 0xc000398040, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:747 +0x162       github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1e1c100, 0xc000b95e50, 0x1e47640, 0xc000398040, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:762 +0x1d6       github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc000be04b0, 0x1e1c240, 0xc000b95e60, 0x1e47640, 0xc000398040, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:623 +0xcc        github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x1e1c060, 0xc0003ebbc0, 0x1e47640, 0xc000398040, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:607 +0x58f       github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1e1c1e0, 0xc000b95e80, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:543 +0x106       github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1e1c120, 0xc000b95e90, 0x50004000000, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:68 +0xcf
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1e1c1c0, 0xc0003ebbe0, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:93 +0x264        github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1e1c1a0, 0xc000b95ea0, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/crossdomain-xml-handler.go:51 +0x81  github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1e1c0e0, 0xc000b95eb0, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:247 +0x68        github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1e1c180, 0xc000b95ec0, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:315 +0xac        github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1e1c160, 0xc000b95ed0, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:274 +0x1c2       github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1e1c080, 0xc000b95ee0, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:385 +0x32a       github.com/rs/cors.(*Cors).Handler.func1(0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /root/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc0003ebc60, 0x1e49c40, 0xc000578000, 0xc0002ebb00)              /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1e1ccc0, 0xc0003ebc60, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:523 +0xa8        github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1e1c220, 0xc000b95f40, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/auth-handler.go:450 +0x392
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x1e1c040, 0xc000b95f50, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:797 +0x454       github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1e1c260, 0xc000b95f60, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:136 +0x264       github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1e1c200, 0xc000b95f70, 0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:779 +0xac        github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1e49c40, 0xc000578000, 0xc0002ebb00)
        /data/richardyao/workspace/github/minio/cmd/http/server.go:104 +0x2ab
net/http.HandlerFunc.ServeHTTP(0xc000380160, 0x1e49c40, 0xc000578000, 0xc0002ebb00)              /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc000201b00, 0x1e49c40, 0xc000578000, 0xc0002ebb00)            /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00071f0e0, 0x1e515c0, 0xc00033ff00)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
2020/02/13 16:59:27 http: panic serving 192.168.56.99:41554: runtime error: integer divide by zero
goroutine 108 [running]:
net/http.(*conn).serve.func1(0xc0006166e0)
        /usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x1887360, 0x3091760)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP.func1(0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:776 +0x248       panic(0x1887360, 0x3091760)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/minio/parquet-go.readDeltaBinaryPackedInt(0xc0015330d8, 0x10, 0xc001532f20, 0x40c2d6, 0xc0007dfb30, 0x30)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/decode.go:342 +0x642
github.com/minio/parquet-go.readDeltaLengthByteArrays(0xc0015330d8, 0x18505c0, 0xc0007df3e0, 0xc000b37620, 0xc001532f50, 0x4462bc)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/decode.go:377 +0x40
github.com/minio/parquet-go.readDataPageValues(0xc0015330d8, 0x6, 0x6, 0x0, 0x1, 0x0, 0x1, 0x0, 0x78, 0xc0007c0900, ...)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/decode.go:473 +0x6cb
github.com/minio/parquet-go.readPage(0xc000375140, 0xc0006c4790, 0xc0007df3e0, 0xc000374f20, 0x4, 0x4, 0xc000375520, 0x0, 0x2ffffffffffffff, 0xffffffffffffffff, ...)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/page.go:263 +0x5cd
github.com/minio/parquet-go.(*column).readPage(0xc0007c0800)
        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/column.go:110 +0x71
github.com/minio/parquet-go.(*column).read(0xc0007c0800, 0xc0007df5f0, 0xc000b37620, 0x4)        /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/column.go:139 +0xd6
github.com/minio/parquet-go.(*Reader).Read(0xc00023c700, 0x126a8b0, 0x8, 0x1bbe0e8)              /root/go/pkg/mod/github.com/minio/parquet-go@v0.0.0-20200125064549-a1e49702e174/reader.go:147 +0x1c1
github.com/minio/minio/pkg/s3select/parquet.(*Reader).Read(0xc000b5e7b0, 0x0, 0x0, 0xc00023c770, 0x1e174c0, 0x0, 0x0)
        /data/richardyao/workspace/github/minio/pkg/s3select/parquet/reader.go:37 +0x3e  github.com/minio/minio/pkg/s3select.(*S3Select).Evaluate(0xc000212820, 0x1e47600, 0xc00009d6c0)
        /data/richardyao/workspace/github/minio/pkg/s3select/select.go:433 +0x1cd        github.com/minio/minio/cmd.objectAPIHandlers.SelectObjectContentHandler(0x1bbdc80, 0x1bbdc70, 0xc00096c2b0, 0xc00096c2d0, 0x1e47600, 0xc00009d6c0, 0xc0008cdb00)
        /data/richardyao/workspace/github/minio/cmd/object-handlers.go:237 +0x1945       net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x1e47600, 0xc00009d6c0, 0xc0008cdb00)            /data/richardyao/workspace/github/minio/cmd/handler-utils.go:353 +0x148
net/http.HandlerFunc.ServeHTTP(...)
        /usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.collectAPIStats.func1(0x1e478c0, 0xc000616820, 0xc0008cdb00)          /data/richardyao/workspace/github/minio/cmd/handler-utils.go:374 +0x158
net/http.HandlerFunc.ServeHTTP(0xc0003e0880, 0x1e478c0, 0xc000616820, 0xc0008cdb00)              /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0007a00c0, 0x1e478c0, 0xc000616820, 0xc0008cd800)
        /root/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe2
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x1e18960, 0xc0007a00c0, 0x1e47640, 0xc0003882c0, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:747 +0x162       github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1e1c100, 0xc000b95e50, 0x1e47640, 0xc0003882c0, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:762 +0x1d6       github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc000be04b0, 0x1e1c240, 0xc000b95e60, 0x1e47640, 0xc0003882c0, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:623 +0xcc        github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x1e1c060, 0xc0003ebbc0, 0x1e47640, 0xc0003882c0, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:607 +0x58f       github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1e1c1e0, 0xc000b95e80, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:543 +0x106       github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1e1c120, 0xc000b95e90, 0x50004000000, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:68 +0xcf
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1e1c1c0, 0xc0003ebbe0, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:93 +0x264        github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1e1c1a0, 0xc000b95ea0, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/crossdomain-xml-handler.go:51 +0x81  github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1e1c0e0, 0xc000b95eb0, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:247 +0x68        github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1e1c180, 0xc000b95ec0, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:315 +0xac        github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1e1c160, 0xc000b95ed0, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:274 +0x1c2       github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1e1c080, 0xc000b95ee0, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:385 +0x32a       github.com/rs/cors.(*Cors).Handler.func1(0x1e49c40, 0xc000579420, 0xc0008cd800)
        /root/go/pkg/mod/github.com/rs/cors@v1.6.0/cors.go:207 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc0003ebc60, 0x1e49c40, 0xc000579420, 0xc0008cd800)              /usr/local/go/src/net/http/server.go:2007 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1e1ccc0, 0xc0003ebc60, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:523 +0xa8        github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1e1c220, 0xc000b95f40, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/auth-handler.go:450 +0x392
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x1e1c040, 0xc000b95f50, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:797 +0x454       github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1e1c260, 0xc000b95f60, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:136 +0x264       github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1e1c200, 0xc000b95f70, 0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/generic-handlers.go:779 +0xac        github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1e49c40, 0xc000579420, 0xc0008cd800)
        /data/richardyao/workspace/github/minio/cmd/http/server.go:104 +0x2ab
net/http.HandlerFunc.ServeHTTP(0xc000380160, 0x1e49c40, 0xc000579420, 0xc0008cd800)              /usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc000201b00, 0x1e49c40, 0xc000579420, 0xc0008cd800)            /usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc0006166e0, 0x1e515c0, 0xc00009d540)
        /usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2928 +0x384
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4b3b7f]

goroutine 134 [running]:
bufio.(*Writer).Available(...)
        /usr/local/go/src/bufio/bufio.go:610
bufio.(*Writer).WriteString(0x0, 0x1b329bc, 0x9, 0x1d, 0x7, 0xc0015cb8c0)
        /usr/local/go/src/bufio/bufio.go:691 +0x7f
net/http.writeStatusLine(0x0, 0x1, 0xc8, 0xc0005780c3, 0x3, 0x3)
        /usr/local/go/src/net/http/server.go:1482 +0x65
net/http.(*chunkWriter).writeHeader(0xc000578038, 0xc0008ba000, 0x39, 0x800)
        /usr/local/go/src/net/http/server.go:1452 +0x700
net/http.(*chunkWriter).Write(0xc000578038, 0xc0008ba000, 0x39, 0x800, 0x7f00aa4ee908, 0xc0008b6420, 0x0)
        /usr/local/go/src/net/http/server.go:369 +0x2ba
bufio.(*Writer).Flush(0xc00009c140, 0x869900, 0x7f00aa4ee908)
        /usr/local/go/src/bufio/bufio.go:593 +0x75
net/http.(*response).Flush(0xc000578000)
        /usr/local/go/src/net/http/server.go:1638 +0x35
github.com/minio/minio/cmd.(*recordTrafficResponse).Flush(0xc000398040)
        /data/richardyao/workspace/github/minio/cmd/http-traffic-recorder.go:71 +0x57    github.com/minio/minio/cmd/logger.(*ResponseWriter).Flush(0xc000616320)
        /data/richardyao/workspace/github/minio/cmd/logger/audit.go:115 +0x57
github.com/minio/minio/cmd.(*recordAPIStats).Flush(0xc00009c1c0)
        /data/richardyao/workspace/github/minio/cmd/http-traffic-recorder.go:106 +0x57   github.com/minio/minio/pkg/s3select.(*messageWriter).write(0xc0003dc5b0, 0x2b445a0, 0x39, 0x39, 0x409401)
        /data/richardyao/workspace/github/minio/pkg/s3select/message.go:263 +0xa6        github.com/minio/minio/pkg/s3select.(*messageWriter).start(0xc0003dc5b0)
        /data/richardyao/workspace/github/minio/pkg/s3select/message.go:340 +0x4ff       created by github.com/minio/minio/pkg/s3select.newMessageWriter
        /data/richardyao/workspace/github/minio/pkg/s3select/message.go:430 +0x160
```

the reason may lie at:
https://github.com/minio/parquet-go/blob/master/page.go#L224
https://github.com/minio/parquet-go/blob/master/page.go#L239

maybe these two lines should be changed to
if pageType == parquet.PageType_DATA_PAGE_V2 {

because at https://github.com/minio/parquet-go/blob/master/page.go#L133
the repLevelsBuf and defLevelsBuf  are appended to dataBuf  only if pageType equals parquet.PageType_DATA_PAGE_V2

**Comment by yaozongyou** [comment]
[hello.zip](https://github.com/minio/minio/files/4212610/hello.zip)
unzip hello.zip will produce hello.parquet for reproducing this bug.

**Comment by harshavardhana** [comment]
Thanks for the heads 👍 @yaozongyou we do not support v2 format yet. 

Also changing the title to reflect the actual issue.

**Comment by klauspost** [comment]
This particular crash should be addressed by https://github.com/minio/minio/pull/9921

But https://github.com/minio/minio/pull/9920 is needed for making servers un-crashable.
