### ISSUE TITLE
Deadlock found in minio s3 gateway mode

### ISSUE THREAD

**Issue by ppwolf** [minio/minio#9105]
## Expected Behavior
No deadlocks found in pprof after stress test

## Current Behavior
deadlocks found when using putobject after stress test

There are many blocking goroutines in pprof, as shown below

```
goroutine 946 [semacquire, 10 minutes]:
sync.runtime_SemacquireMutex(0xc000b52b70, 0xc003008000, 0x1)
	/usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc000b52b6c)
	/usr/local/go/src/sync/mutex.go:138 +0xfc
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
net/http.(*body).Read(0xc000b52b40, 0xc003008000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:834 +0x157
io.(*LimitedReader).Read(0xc001b15380, 0xc003008000, 0x2000, 0x2000, 0x24, 0x40adcb, 0xc000032000)
	/usr/local/go/src/io/io.go:448 +0x63
io/ioutil.devNull.ReadFrom(0x0, 0x1e4d380, 0xc001b15380, 0x18dde60, 0x1, 0x7f96efcfe250)
	/usr/local/go/src/io/ioutil/ioutil.go:147 +0x92
io.copyBuffer(0x1e4f860, 0x3127d50, 0x1e4d380, 0xc001b15380, 0x0, 0x0, 0x0, 0x19fb8a0, 0x30f4b00, 0x7f96efdd8560)
	/usr/local/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/go/src/io/io.go:364
io.CopyN(0x1e4f860, 0x3127d50, 0x7f96efdd8560, 0xc000b52b40, 0x40001, 0x150, 0x150, 0xc005f16f20)
	/usr/local/go/src/io/io.go:340 +0x9a
net/http.(*chunkWriter).writeHeader(0xc001412498, 0xc001d36800, 0x145, 0x800)
	/usr/local/go/src/net/http/server.go:1350 +0xfc6
net/http.(*chunkWriter).Write(0xc001412498, 0xc001d36800, 0x145, 0x800, 0x7f96efdd8200, 0xc0025106e0, 0xc0014d90d0)
	/usr/local/go/src/net/http/server.go:369 +0x2ba
bufio.(*Writer).Flush(0xc001d16700, 0x86f900, 0x7f96efdd8200)
	/usr/local/go/src/bufio/bufio.go:593 +0x75
net/http.(*response).Flush(0xc001412460)
	/usr/local/go/src/net/http/server.go:1638 +0x35
github.com/minio/minio/cmd.(*recordTrafficResponse).Flush(0xc0019da740)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/http-traffic-recorder.go:61 +0x57
github.com/minio/minio/cmd/logger.(*ResponseWriter).Flush(0xc001559040)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/logger/audit.go:116 +0x57
github.com/minio/minio/cmd.(*recordAPIStats).Flush(0xc000b52c00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/http-traffic-recorder.go:90 +0x57
github.com/minio/minio/cmd.writeResponse(0x1e7a740, 0xc000b52c00, 0x1f7, 0xc0029ae1a0, 0x145, 0x19e, 0x1b6887e, 0xf)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/api-response.go:671 +0x215
github.com/minio/minio/cmd.writeErrorResponse(0x1e84840, 0xc001f23890, 0x1e7a740, 0xc000b52c00, 0x1b6c394, 0x11, 0x1b99efe, 0x25, 0x1f7, 0xc001207680, ...)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/api-response.go:735 +0x2d2
github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler(0x1bebba8, 0x1bebb98, 0xc00041d000, 0xc00041d010, 0x1e7a740, 0xc000b52c00, 0xc000673000)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1380 +0x272d
net/http.HandlerFunc.ServeHTTP(...)
	/usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.httpTraceHdrs.func1(0x1e7a740, 0xc000b52c00, 0xc000673000)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/handler-utils.go:353 +0x148
net/http.HandlerFunc.ServeHTTP(...)
	/usr/local/go/src/net/http/server.go:2007
github.com/minio/minio/cmd.collectAPIStats.func1(0x1e7aa00, 0xc001559040, 0xc000673000)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/handler-utils.go:376 +0x125
net/http.HandlerFunc.ServeHTTP(0xc00047c5a0, 0x1e7aa00, 0xc001559040, 0xc000673000)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0005aa000, 0x1e7aa00, 0xc001559040, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
github.com/minio/minio/cmd.customHeaderHandler.ServeHTTP(0x1e4b5a0, 0xc0005aa000, 0x1e7a780, 0xc0019da740, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:748 +0x162
github.com/minio/minio/cmd.securityHeaderHandler.ServeHTTP(0x1e4ed40, 0xc0003e6720, 0x1e7a780, 0xc0019da740, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:763 +0x1d6
github.com/minio/minio/cmd.bucketForwardingHandler.ServeHTTP(0xc0005ffc20, 0x1e4ee80, 0xc0003e6730, 0x1e7a780, 0xc0019da740, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:624 +0xcc
github.com/minio/minio/cmd.requestValidityHandler.ServeHTTP(0x1e4eca0, 0xc00046ea20, 0x1e7a780, 0xc0019da740, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:608 +0x58f
github.com/minio/minio/cmd.httpStatsHandler.ServeHTTP(0x1e4ee20, 0xc0003e6760, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:544 +0x106
github.com/minio/minio/cmd.requestSizeLimitHandler.ServeHTTP(0x1e4ed60, 0xc0003e6770, 0x50004000000, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:68 +0xcf
github.com/minio/minio/cmd.requestHeaderSizeLimitHandler.ServeHTTP(0x1e4ee00, 0xc00046ea40, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:93 +0x264
github.com/minio/minio/cmd.crossDomainPolicy.ServeHTTP(0x1e4ede0, 0xc0003e6790, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/crossdomain-xml-handler.go:51 +0x81
github.com/minio/minio/cmd.redirectHandler.ServeHTTP(0x1e4ed20, 0xc0003e67a0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:247 +0x68
github.com/minio/minio/cmd.minioReservedBucketHandler.ServeHTTP(0x1e4edc0, 0xc0003e67c0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:315 +0xac
github.com/minio/minio/cmd.cacheControlHandler.ServeHTTP(0x1e4eda0, 0xc0003e67d0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:274 +0x1c2
github.com/minio/minio/cmd.timeValidityHandler.ServeHTTP(0x1e4ecc0, 0xc0003e67e0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:385 +0x32a
github.com/rs/cors.(*Cors).Handler.func1(0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/vendor/github.com/rs/cors/cors.go:207 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc00046eac0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/minio/minio/cmd.resourceHandler.ServeHTTP(0x1e4f920, 0xc00046eac0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:525 +0xa8
github.com/minio/minio/cmd.authHandler.ServeHTTP(0x1e4ee60, 0xc0003e68b0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/auth-handler.go:449 +0x392
github.com/minio/minio/cmd.sseTLSHandler.ServeHTTP(0x1e4ec80, 0xc0003e68c0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:798 +0x454
github.com/minio/minio/cmd.reservedMetadataHandler.ServeHTTP(0x1e4eea0, 0xc0003e68d0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:136 +0x264
github.com/minio/minio/cmd.criticalErrorHandler.ServeHTTP(0x1e4ee40, 0xc0003e68e0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/generic-handlers.go:780 +0xac
github.com/minio/minio/cmd/http.(*Server).Start.func1(0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/http/server.go:104 +0x2ab
net/http.HandlerFunc.ServeHTTP(0xc00045e080, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
net/http.serverHandler.ServeHTTP(0xc000282fc0, 0x1e7cd80, 0xc001412460, 0xc000b7ad00)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc00060f180, 0x1e84780, 0xc0011ae2c0)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
```

```
goroutine 3603 [IO wait, 10 minutes]:
internal/poll.runtime_pollWait(0x7f96e8163b88, 0x72, 0xffffffffffffffff)
	/usr/local/go/src/runtime/netpoll.go:184 +0x55
internal/poll.(*pollDesc).wait(0xc00269f618, 0x72, 0xc300, 0xfb13, 0xffffffffffffffff)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/usr/local/go/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc00269f600, 0xc00605e4ed, 0xc313, 0xfb13, 0x0, 0x0, 0x0)
	/usr/local/go/src/internal/poll/fd_unix.go:169 +0x1cf
net.(*netFD).Read(0xc00269f600, 0xc00605e4ed, 0xc313, 0xfb13, 0x3f21db617c66c668, 0xe7662f8c714ac533, 0x874f42cabcbb74b9)
	/usr/local/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc000ab0310, 0xc00605e4ed, 0xc313, 0xfb13, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:184 +0x68
net/http.(*connReader).Read(0xc002433320, 0xc00605e4ed, 0xc313, 0xfb13, 0xc002710f90, 0x30, 0x30)
	/usr/local/go/src/net/http/server.go:785 +0xf4
bufio.(*Reader).Read(0xc002639380, 0xc00605e4ed, 0xc313, 0xfb13, 0xc00053aa01, 0x7f96efe426d8, 0x0)
	/usr/local/go/src/bufio/bufio.go:212 +0x153
io.(*LimitedReader).Read(0xc003117020, 0xc00605e4ed, 0xc313, 0xfb13, 0x30, 0x0, 0x1)
	/usr/local/go/src/io/io.go:448 +0x63
net/http.(*body).readLocked(0xc0032e2400, 0xc00605e4ed, 0xc313, 0xfb13, 0x0, 0x1, 0x2)
	/usr/local/go/src/net/http/transfer.go:847 +0x5f
net/http.(*body).Read(0xc0032e2400, 0xc00605e4ed, 0xc313, 0xfb13, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:839 +0x102
net/http.(*maxBytesReader).Read(0xc0032e24c0, 0xc00605e4ed, 0xc313, 0xfb13, 0x0, 0x400, 0x10000)
	/usr/local/go/src/net/http/request.go:1134 +0x8a
github.com/minio/minio/cmd.(*recordTrafficRequest).Read(0xc003117040, 0xc00605e4ed, 0xc313, 0xfb13, 0xc000720770, 0xc00605e000, 0x4c0)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/http-traffic-recorder.go:33 +0x55
github.com/minio/minio/cmd.(*detectDisconnect).Read(0xc003117280, 0xc00605e4ed, 0xc313, 0xfb13, 0x10000, 0x40, 0x4c0)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-api-utils.go:859 +0xa2
bufio.(*Reader).Read(0xc0024c4780, 0xc00605e4ed, 0xc313, 0xfb13, 0x4ed, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:212 +0x153
github.com/minio/minio/cmd.(*s3ChunkedReader).Read(0xc0016f09a0, 0xc00605e000, 0xc800, 0x10000, 0x0, 0xc0031bd738, 0x41953e)
	/go/src/git.guazi-corp.com/tianjun4/minio/cmd/streaming-signature-v4.go:276 +0x6a7
io.(*LimitedReader).Read(0xc003117420, 0xc00605e000, 0x10000, 0x10000, 0x8000, 0x3127e78, 0x7f96d86fa218)
	/usr/local/go/src/io/io.go:448 +0x63
github.com/minio/minio/pkg/hash.(*Reader).Read(0xc0005f21c0, 0xc00605e000, 0x10000, 0x10000, 0x0, 0xc00317a6f0, 0x7f96d86fa218)
	/go/src/git.guazi-corp.com/tianjun4/minio/pkg/hash/reader.go:88 +0x55
github.com/minio/minio-go/v6/pkg/s3signer.(*StreamingReader).Read(0xc001972a00, 0xc000c5e000, 0x8000, 0x8000, 0x18062e0, 0xc003183d01, 0xc000c5e000)
	/go/src/git.guazi-corp.com/tianjun4/minio/vendor/github.com/minio/minio-go/v6/pkg/s3signer/request-signature-streaming.go:255 +0xc9
io.(*LimitedReader).Read(0xc001861c20, 0xc000c5e000, 0x8000, 0x8000, 0x0, 0xc0031bd800, 0x40bde8)
	/usr/local/go/src/io/io.go:448 +0x63
io.copyBuffer(0x1e4f900, 0xc0009a9830, 0x1e4d380, 0xc001861c20, 0xc000c5e000, 0x8000, 0x8000, 0x3127e78, 0x0, 0x0)
	/usr/local/go/src/io/io.go:402 +0x122
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net.genericReadFrom(0x1e4d660, 0xc0000100d0, 0x1e4d380, 0xc001861c20, 0x0, 0x0, 0x1ad9600)
	/usr/local/go/src/net/net.go:625 +0x9a
net.(*TCPConn).readFrom(0xc0000100d0, 0x1e4d380, 0xc001861c20, 0xc0031bd9e8, 0x40c0ba, 0x18d1020)
	/usr/local/go/src/net/tcpsock_posix.go:54 +0xe2
net.(*TCPConn).ReadFrom(0xc0000100d0, 0x1e4d380, 0xc001861c20, 0x7f96efdd83a0, 0xc0000100d0, 0xc0031bda01)
	/usr/local/go/src/net/tcpsock.go:103 +0x4d
io.copyBuffer(0x1e4d660, 0xc0000100d0, 0x1e4d380, 0xc001861c20, 0x0, 0x0, 0x0, 0x196fec0, 0xc000067901, 0x7f96efdd8380)
	/usr/local/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net/http.persistConnWriter.ReadFrom(0xc001255200, 0x1e4d380, 0xc001861c20, 0x7f96efdd8380, 0xc001255200, 0x1)
	/usr/local/go/src/net/http/transport.go:1591 +0x85
bufio.(*Writer).ReadFrom(0xc000ee6000, 0x1e4d380, 0xc001861c20, 0x7f96efdd8360, 0xc000ee6000, 0x1)
	/usr/local/go/src/bufio/bufio.go:713 +0x34a
io.copyBuffer(0x1e4a140, 0xc000ee6000, 0x1e4d380, 0xc001861c20, 0x0, 0x0, 0x0, 0xc0031bdc38, 0x40e7a8, 0x20)
	/usr/local/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net/http.(*transferWriter).doBodyCopy(0xc003d57b80, 0x1e4a140, 0xc000ee6000, 0x1e4d380, 0xc001861c20, 0x18d11a0, 0xc0031bdcc0, 0x7282b2)
	/usr/local/go/src/net/http/transfer.go:400 +0x6a
net/http.(*transferWriter).writeBody(0xc003d57b80, 0x1e4a140, 0xc000ee6000, 0x2, 0x2)
	/usr/local/go/src/net/http/transfer.go:359 +0x6da
net/http.(*Request).write(0xc001972b00, 0x1e4a140, 0xc000ee6000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:682 +0x6d3
net/http.(*persistConn).writeLoop(0xc001255200)
	/usr/local/go/src/net/http/transport.go:2199 +0x1c8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1567 +0xb23
```

## Steps to Reproduce (for bugs)
0.  add pprof in minio
```go
// Handler for 'minio gateway s3' command line.
func s3GatewayMain(ctx *cli.Context) {
	args := ctx.Args()
	if !ctx.Args().Present() {
		args = cli.Args{"https://s3.amazonaws.com"}
	}

	// Validate gateway arguments.
	logger.FatalIf(minio.ValidateGatewayArguments(ctx.GlobalString("address"), args.First()), "Invalid argument")

         // Add this
	go func() {
		fmt.Println(http.ListenAndServe("0.0.0.0:9999", nil))
	}()

	// Start the gateway..
	minio.StartGateway(ctx, &S3{args.First()})
}
```

1. run minio in gateway mode
 minio gateway s3 http://s3-xxx.com
(http://s3-xxx.com represents the backend ceph cluster)

2. test putobject (Try a few more times)
```go
func TestPutObjectInPress(t *testing.T) {
	host := "the host of s3 gateway"
	accessKey := "xxx"
	secretKey := "yyy"
	minioClient, err := minio.New(host, accessKey, secretKey, false)
	assert.Nil(t, err)
	bucketName := "test-bucket"
	objectName := "hello.txt"
	var wg sync.WaitGroup
	for i := 0; i < 3000; i ++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			content := strings.Repeat(randStr(50), 1024)
			n, err := minioClient.PutObject(bucketName, objectName, strings.NewReader(content),
				int64(len(content)), minio.PutObjectOptions{})
			assert.Nil(t, err)
			assert.Equal(t, int64(50*1024), n)
			switch e := err.(type) {
			case minio.ErrorResponse:
				fmt.Println(e.Code, e.Message, e.StatusCode)
			}
		}()
	}
	wg.Wait()
	fmt.Println("see u next time")
}

var letterRunes = []rune("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ")

func randStr(n int) string {
	b := make([]rune, n)
	for i := range b {
		b[i] = letterRunes[rand.Intn(len(letterRunes))]
	}
	return string(b)
}
```
3.  view pprof
http://your-minio-gateway-host:9999/debug/pprof/goroutine?debug=2

## Context
deadlock may cause memory leak

## Your Environment
* Version used (`minio version`):
RELEASE.2020-03-06T22-23-56Z
* Environment name and version (e.g. nginx 1.9.1):
go 1.13
* Server type and version:
Debian GNU/Linux 9
* Operating System and version:
Linux minio-minio-b5d6bc945-h729q 4.19.2-1.el7.elrepo.x86_64 #1 SMP Tue Nov 13 16:18:09 EST 2018 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
Thanks @ppwolf

**Comment by poornas** [comment]
@ppwolf, I tested minio gateway with both s3 as backend and minio as backend with pprof -  the go routines shown in the pprof are mostly long running routines, not indicative of deadlock. Did you make other changes to source code apart from the http listener in gateway-s3.go? Lines like `/go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1388` don't match to an [instruction](https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/object-handlers.go#L1388) in RELEASE.2020-03-06T22-23-56Z

**Comment by klauspost** [comment]
This looks like hanging connections. Are the timeouts set on the HTTP server?

**Comment by ppwolf** [comment]
> @ppwolf, I tested minio gateway with both s3 as backend and minio as backend with pprof - the go routines shown in the pprof are mostly long running routines, not indicative of deadlock. Did you make other changes to source code apart from the http listener in gateway-s3.go? Lines like `/go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1388` don't match to an [instruction](https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/object-handlers.go#L1388) in RELEASE.2020-03-06T22-23-56Z


I am Sorry. I added some print statements, I have removed these  and reproduced them. Lines  /go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1380 match to an [instruction](https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/object-handlers.go#L1380) in RELEASE.2020-03-06T22-23-56Z

**Comment by ppwolf** [comment]
> This looks like hanging connections. Are the timeouts set on the HTTP server?

no， I just added pprof on minio.  it looks like the server didin't know that the client has disconnected, and I found that there are many established connections in the system, even if there are no requests now

**Comment by ppwolf** [comment]
> > @ppwolf, I tested minio gateway with both s3 as backend and minio as backend with pprof - the go routines shown in the pprof are mostly long running routines, not indicative of deadlock. Did you make other changes to source code apart from the http listener in gateway-s3.go? Lines like `/go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1388` don't match to an [instruction](https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/object-handlers.go#L1388) in RELEASE.2020-03-06T22-23-56Z
> 
> I am Sorry. I added some print statements, I have removed these and reproduced them. Lines /go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1380 match to an [instruction](https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/object-handlers.go#L1380) in RELEASE.2020-03-06T22-23-56Z


You may need to use more goroutines to test, because I find that deadlock do not occur under normal circumstances。

**Comment by poornas** [comment]
> > > @ppwolf, I tested minio gateway with both s3 as backend and minio as backend with pprof - the go routines shown in the pprof are mostly long running routines, not indicative of deadlock. Did you make other changes to source code apart from the http listener in gateway-s3.go? Lines like `/go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1388` don't match to an [instruction](https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/object-handlers.go#L1388) in RELEASE.2020-03-06T22-23-56Z
> > 
> > 
> > I am Sorry. I added some print statements, I have removed these and reproduced them. Lines /go/src/git.guazi-corp.com/tianjun4/minio/cmd/object-handlers.go:1380 match to an [instruction](https://github.com/minio/minio/blob/RELEASE.2020-03-06T22-23-56Z/cmd/object-handlers.go#L1380) in RELEASE.2020-03-06T22-23-56Z
> 
> You may need to use more goroutines to test, because I find that deadlock do not occur under normal circumstances。

thanks, will see if I can repro this.

**Comment by poornas** [comment]
@ppwolf , I ran minio gateway with a far higher load and still do not see any blocked goroutines. It seems to be working as expected.

**Comment by klauspost** [comment]
@poornas It is hanging TCP connections that never times out, not deadlocks as such. You cannot reproduce that easily. However, it is rather easily handled with timeouts.

**Comment by harshavardhana** [comment]
Most probably this is the fix https://github.com/minio/minio-go/pull/1247 @klauspost
