### ISSUE TITLE
[upstream issue] Remove "404" Log Entries from SysLog in Gateway Mode

### ISSUE THREAD

**Issue by philippjenni** [minio/minio#9366]
If you use MinIO in gateway mode with Azure and many files are called which do not exist in Azure, the SysLog is filled unnecessarily.

```
Apr 16 09:56:05 vstorage07 /usr/local/bin/minio[14914]: 2020/04/16 09:56:05 ==> REQUEST/RESPONSE (Try=1/3.229765ms, OpTime=3.323668ms) -- REQUEST ERROR#012   HEAD https://newhome.blob.core.windows.net/newhome-prod/public/3380425/ort-bad-zurzach/hauptstrasse-/haus/terrassenhaus-71451206-md.jpg?timeout=16#012   Authorization: REDACTED#012   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-03-14T02:21:58Z]#012   X-Ms-Client-Request-Id: [af1b7384-51a8-47db-60f1-37df3695b823]#012   X-Ms-Version: [2018-11-09]#012   x-ms-date: [Thu, 16 Apr 2020 07:56:05 GMT]#012   --------------------------------------------------------------------------------#012   RESPONSE Status: 404 The specified blob does not exist.#012   Date: [Thu, 16 Apr 2020 07:56:05 GMT]#012   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]#012   X-Ms-Error-Code: [BlobNotFound]#012   X-Ms-Request-Id: [a27134e5-b01e-0016-4bc4-13f43d000000]#012   X-Ms-Version: [2018-11-09]#012   --------------------------------------------------------------------------------#012   ERROR:#012-> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, /q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42#012===== RESPONSE ERROR (ServiceCode=BlobNotFound) =====#012Description=404 The specified blob does not exist., Details: (none)#012   HEAD https://newhome.blob.core.windows.net/newhome-prod/public/3380425/ort-bad-zurzach/hauptstrasse-/haus/terrassenhaus-71451206-md.jpg?timeout=16#012   Authorization: REDACTED#012   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-03-14T02:21:58Z]#012   X-Ms-Client-Request-Id: [af1b7384-51a8-47db-60f1-37df3695b823]#012   X-Ms-Date: [Thu, 16 Apr 2020 07:56:05 GMT]#012   X-Ms-Version: [2018-11-09]#012   --------------------------------------------------------------------------------#012   RESPONSE Status: 404 The specified blob does not exist.#012   Date: [Thu, 16 Apr 2020 07:56:05 GMT]#012   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]#012   X-Ms-Error-Code: [BlobNotFound]#012   X-Ms-Request-Id: [a27134e5-b01e-0016-4bc4-13f43d000000]#012   X-Ms-Version: [2018-11-09]#012#012#012#012goroutine 14174558 [running]:#012github.com/Azure/azure-storage-blob-go/azblob.stack(0xc026f96e40, 0xc026f90c00, 0xc026f48a20)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_request_log.go:146 +0x9d#012github.com/Azure/azure-storage-blob-go/azblob.NewRequestLogPolicyFactory.func1.1(0x1e9caa0, 0xc03899a840, 0xc026f90c00, 0x10, 0x182b680, 0x1, 0xc026fb91e0)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_request_log.go:96 +0x650#012github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc030009810, 0x1e9caa0, 0xc03899a840, 0xc026f90c00, 0xc026fb92c8, 0xc088194680, 0x3e, 0xc0126ee0f0)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x44#012github.com/Azure/azure-storage-blob-go/azblob.(*SharedKeyCredential).New.func1(0x1e9caa0, 0xc03899a840, 0xc026f90c00, 0x31291c0, 0x1e9caa0, 0xc03899a840, 0xc026f45f40)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_credential_shared_key.go:66 +0x2d2#012github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc026fbecf0, 0x1e9caa0, 0xc03899a840, 0xc026f90c00, 0xc03899a840, 0xc026f45f40, 0xc000000001, 0x0)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x44#012github.com/Azure/azure-storage-blob-go/azblob.NewRetryPolicyFactory.func1.1(0x1e9cae0, 0xc026fbe600, 0xc026f90b00, 0x10, 0x182b680, 0x64492d747301, 0xc026fb9080)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_retry.go:204 +0x66c#012github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc030009860, 0x1e9cae0, 0xc026fbe600, 0xc026f90b00, 0xc026fb9138, 0x30, 0xc026fe5708, 0x402dc1)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x44#012github.com/Azure/azure-storage-blob-go/azblob.NewUniqueRequestIDPolicyFactory.func1.1(0x1e9cae0, 0xc026fbe600, 0xc026f90b00, 0x10, 0x182b680, 0x40cb01, 0xc026fb9080)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_unique_request_id.go:19 +0xae#012github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc0239f5240, 0x1e9cae0, 0xc026fbe600, 0xc026f90b00, 0xc026fb9120, 0x23, 0xc000686090, 0xc026fe57e8)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x44#012github.com/Azure/azure-storage-blob-go/azblob.NewTelemetryPolicyFactory.func1.1(0x1e9cae0, 0xc026fbe600, 0xc026f90b00, 0x1, 0x0, 0x1, 0xc052fb4238)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zc_policy_telemetry.go:34 +0x15d#012github.com/Azure/azure-pipeline-go/pipeline.PolicyFunc.Do(0xc026fbed20, 0x1e9cae0, 0xc026fbe600, 0xc026f90b00, 0xc026fbed20, 0xc026f90b00, 0xc026fe58b8, 0x40cb48)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:43 +0x44#012github.com/Azure/azure-pipeline-go/pipeline.(*pipeline).Do(0xc0003380c0, 0x1e9cae0, 0xc026fbe600, 0x1e66560, 0xc026edd680, 0xc026f90b00, 0x1d, 0xc06c6ed860, 0x5d, 0x0)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-pipeline-go@v0.2.1/pipeline/core.go:129 +0x81#012github.com/Azure/azure-storage-blob-go/azblob.blobClient.GetProperties(0xc000686030, 0x5, 0x0, 0x0, 0x0, 0xc000686038, 0x1d, 0xc06c6ed860, 0x5d, 0x0, ...)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/zz_generated_blob.go:761 +0x3a5#012github.com/Azure/azure-storage-blob-go/azblob.BlobURL.GetProperties(0xc000686030, 0x5, 0x0, 0x0, 0x0, 0xc000686038, 0x1d, 0xc06c6ed860, 0x5d, 0x0, ...)#012#011/q/.q/sources/gopath/pkg/mod/github.com/!azure/azure-storage-blob-go@v0.8.0/azblob/url_blob.go:113 +0x11f#012github.com/minio/minio/cmd/gateway/azure.(*azureObjects).GetObjectInfo(0xc0004c0000, 0x1e9cae0, 0xc026fbe600, 0xc0211a8385, 0xc, 0xc0211a8392, 0x4f, 0x0, 0x0, 0x0, ...)#012#011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/gateway/azure/gateway-azure.go:754 +0x197#012github.com/minio/minio/cmd.newServerCacheObjects.func1(0x1e9cae0, 0xc026fbe600, 0xc0211a8385, 0xc, 0xc0211a8392, 0x4f, 0x0, 0x0, 0x0, 0x0, ...)#012#011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-cache.go:666 +0xfd#012github.com/minio/minio/cmd.(*cacheObjects).GetObjectInfo(0xc000595780, 0x1e9cae0, 0xc026fbe600, 0xc0211a8385, 0xc, 0xc0211a8392, 0x4f, 0x0, 0x0, 0x0, ...)#012#011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/disk-cache.go:343 +0x26d#012github.com/minio/minio/cmd.checkPutObjectLockAllowed(0x1e9cae0, 0xc026fbe600, 0xc026f90a00, 0xc0211a8385, 0xc, 0xc0211a8392, 0x4f, 0xc026f37998, 0x0, 0x0, ...)#012#011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-lock.go:173 +0x26d#012github.com/minio/minio/cmd.objectAPIHandlers.PutObjectHandler(0x1c028a0, 0x1c02890, 0xc000350740, 0xc000350770, 0x1e928a0, 0xc0487f8300, 0xc026f90a00)#012#011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/object-handlers.go:1338 +0x176a#012net/http.HandlerFunc.ServeHTTP(...)#012#011/opt/go/src/net/http/server.go:2007#012github.com/minio/minio/cmd.httpTraceHdrs.func1(0x1e928a0, 0xc0487f8300, 0xc026f90a00)#012#011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/handler-utils.go:353 +0x148#012net/http.HandlerFunc.ServeHTTP(...)#012#011/opt/go/src/net/http/server.go:2007#012github.com/minio/minio/cmd.collectAPIStats.func1(0x1e92b60, 0xc026edd5e0, 0xc026f90a00)#012#011/q/.q/sources/gopath/src/github.com/minio/minio/cmd/handler-utils.go:376 +0x125#012net/http.HandlerFunc.ServeHTTP(0xc0003320e0, 0x1e92b60, 0xc026edd5e0, 0xc026f90a00)#012#011/opt/go/src/net/http/server.go:2007 +0x44#012github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001f8000, 0x1e92b60, 0xc026edd5e0, 0xc026f90800)#012#011/q/.q/sources/gopath/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212 +0xe2#012github.com/minio/minio/cmd.cu
```

These log entires should be removed or there should be an option where you can disable the logs.

**Comment by kannappanr** [comment]
@philippjenni I am not sure if we can do anything about it. Microsoft is forcing it without any option to opt out

https://github.com/Azure/azure-storage-blob-go/issues/129

**Comment by harshavardhana** [comment]
Closing this as upstream issue for now.
