### ISSUE TITLE
aws cli not working with ldap backed assume-role

### ISSUE THREAD

**Issue by timhughes** [minio/minio#9435]
I have setup minio using the LDAP settings on https://github.com/minio/minio/blob/master/docs/sts/ldap.md with a AD backend. The example `ldap.go` program is working and returning a valid credentials struct but i cannot get it to work using the aws cli

## Expected Behavior
I am expecting not to get an error whe running 
```
aws --profile minio --endpoint-url http://localhost:9001 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything
```
## Current Behavior
```
 aws --profile minio --endpoint-url http://localhost:9001 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything

An error occurred (MalformedPolicyDocument) when calling the AssumeRole operation: The request was rejected because the policy document was malformed.
```

## Steps to Reproduce (for bugs)

1. setup minio with LDAP STS 
```
export MINIO_IDENTITY_LDAP_SERVER_ADDR=ad1.example.com:636
export MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER='(sAMAccountName=%s)'
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="dc=example,dc=com"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER='(&(objectclass=group)(member=%s))'
export MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE=cn
export MINIO_IDENTITY_LDAP_STS_EXPIRY=60h
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
```
2. start minio
```
/usr/bin/minio server --address :9001 /data/archive
```

3. test to confirm working using the `ldap.go` code from https://github.com/minio/minio/blob/master/docs/sts/ldap.go
4. setup aws profile
```
aws configure --profile minio
AWS Access Key ID [****************name]: myusername
AWS Secret Access Key [****************word]: mypassword
Default region name [us-east-1]: 
Default output format [None]: 
```
5. Run example aws sts asume-role command
```
aws --profile minio --endpoint-url http://localhost:9001 sts assume-role --policy '{"Version":"2012-10-17","Statement":[{"Sid":"Stmt1","Effect":"Allow","Action":"s3:*","Resource":"arn:aws:s3:::*"}]}' --role-arn arn:xxx:xxx:xxx:xxxx --role-session-name anything
``` 
Also tried using boto3 in a python script and get the same error.
```
#! /usr/bin/env python

import boto3
from getpass import getpass

username=input('LDAP username: ')
password=getpass('LDAP Password: ')
endpoint="http://minio.localhost:9001"

sts_client = boto3.client(
        'sts',
        aws_access_key_id=username,
        aws_secret_access_key=password,
        endpoint_url=endpoint,
        verify=False
        )


policy_document = """
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Action": "s3:*",
      "Effect": "Allow",
      "Resource": "arn:aws:s3:::*/*"
    }
  ]
}
"""

credentials = sts_client.assume_role(
    RoleArn='arn:xxx:xxx:xxx:xxxx',
    RoleSessionName='anything',
    #Policy=policy_document,
)
print(credentials)

s3_resource=boto3.resource(
    's3',
    aws_access_key_id=credentials['AccessKeyId'],
    aws_secret_access_key=credentials['SecretAccessKey'],
    aws_session_token=credentials['SessionToken'],
)

for bucket in s3_resource.buckets.all():
    print(bucket.name)
```
## Context

I am trying to do this so that staff within our business can access files in minio using their corporate credentials. This is both for convenience to take advantage of all the predefined staff groups and for audit purposes.

## Your Environment

* Version used (`minio version`): minio version RELEASE.2020-04-15T19-42-18Z
* Server type and version: CentOS release 6.10 (Final)
* Operating System and version (`uname -a`): Linux localhost.localdomain 2.6.32-754.14.2.el6.x86_64 #1 SMP Tue May 14 19:35:42 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by harshavardhana** [comment]
LDAP doesn't support AssumeRole directly @timhughes you need to use our custom API AssumeRoleWithLDAP which is not supported `aws` cli its an extension API by MinIO. 

Currently it's not possible to use it the way you want it. We may add it in future.

**Comment by timhughes** [comment]
What would you suggest then for using with python? I did a search of https://github.com/minio/minio-py/search?q=ldap&unscoped_q=ldap but that returned no mention of LDAP. I am thinking my best bet would to be to use `requests` and build a simple function to construct a URL similar to the following .

```
curl -d 'Action=AssumeRoleWithLDAPIdentity&LDAPUsername=xxxxxx&LDAPPassword=xxxxxxxxxxxxxx&Version=2011-06-15' http://localhost:9001
```
Which I have tried using `curl` but getting back the following error. I am hoping it is just a cli issue. I will try with some python code tomorrow
```
<?xml version="1.0" encoding="UTF-8"?>
<ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>Unsupported action AssumeRoleWithLDAPIdentity</Message></Error><RequestId>16088BEDAFE6AE56</RequestId></ErrorResponse>
```

**Comment by harshavardhana** [comment]
> What would you suggest then for using with python? I did a search of https://github.com/minio/minio-py/search?q=ldap&unscoped_q=ldap but that returned no mention of LDAP. I am thinking my best bet would to be to use `requests` and build a simple function to construct a URL similar to the following .
> 
> ```
> curl -d 'Action=AssumeRoleWithLDAPIdentity&LDAPUsername=xxxxxx&LDAPPassword=xxxxxxxxxxxxxx&Version=2011-06-15' http://localhost:9001
> ```
> 
> Which I have tried using `curl` but getting back the following error. I am hoping it is just a cli issue. I will try with some python code tomorrow
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <ErrorResponse xmlns="https://sts.amazonaws.com/doc/2011-06-15/"><Error><Type></Type><Code>InvalidParameterValue</Code><Message>Unsupported action AssumeRoleWithLDAPIdentity</Message></Error><RequestId>16088BEDAFE6AE56</RequestId></ErrorResponse>
> ```

once you obtain the tokens set the following ENV and use it with admin API. 

```
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY
AWS_SESSION_TOKEN
```

**Comment by timhughes** [comment]
I think I am almost there.  Wrote the script below (gist link) and it gets me the tokens but I cannot seem to get permission to list the buckets. I have used the inbuilt `readwrite` policy and applied to my user which should give me all access. Is there any way of debugging this. If i remove the MINIO_IDENTITY_LDAP_XXXX env vars from the server and setup the user the same way it has access.

https://gist.github.com/timhughes/2391e657e36b55ca4f5ec59a1b8b7117  

```
[root@localhost vagrant]# mc admin policy set local readwrite user=timhughes
Policy readwrite is set on user `timhughes`
[root@localhost vagrant]# mc admin user info local timhughes
AccessKey: timhughes
Status: 
PolicyName: readwrite
MemberOf: 
```
This is that gist script running
```
thughes@krypton [0] $ python minio_sts_ldap.py -u timhughes -p -e http://minio.localhost:9001
Password: 
-------------------------------------
export AWS_ACCESS_KEY_ID=VHKXF2Z6XPRRYGKZKKPV
export AWS_SECRET_ACCESS_KEY=DJv7fpVIuifcug+aasC5RHIGepv5+6nLem1kXFNB
export AWS_SESSION_TOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJWSEtYRjJaNlhQUlJZR0taS0tQViIsImV4cCI6MTU4Nzk2MjQ0NSwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJodWdoZXN0In0.S3LSAOfQrIRo33drvftBNEYxD9srtocHXyyb6hMo1Q4JvknbwbqMANxvVhm6pQ8OQyil2XRKPRsx1rkvFxpx6Q
-------------------------------------

Traceback (most recent call last):
  File "minio_sts_ldap.py", line 106, in <module>
    for bucket in s3_resource.buckets.all():
  File "/home/thughes/.cache/pypoetry/virtualenvs/minio-example-YCjzBjPW-py3.7/lib64/python3.7/site-packages/boto3/resources/collection.py", line 83, in __iter__
    for page in self.pages():
  File "/home/thughes/.cache/pypoetry/virtualenvs/minio-example-YCjzBjPW-py3.7/lib64/python3.7/site-packages/boto3/resources/collection.py", line 161, in pages
    pages = [getattr(client, self._py_operation_name)(**params)]
  File "/home/thughes/.cache/pypoetry/virtualenvs/minio-example-YCjzBjPW-py3.7/lib64/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/thughes/.cache/pypoetry/virtualenvs/minio-example-YCjzBjPW-py3.7/lib64/python3.7/site-packages/botocore/client.py", line 626, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied.
```

```
thughes@krypton [0] $ export AWS_ACCESS_KEY_ID=VHKXF2Z6XPRRYGKZKKPV
thughes@krypton [0] $ export AWS_SECRET_ACCESS_KEY=DJv7fpVIuifcug+aasC5RHIGepv5+6nLem1kXFNB
thughes@krypton [0] $ export AWS_SESSION_TOKEN=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJWSEtYRjJaNlhQUlJZR0taS0tQViIsImV4cCI6MTU4Nzk2MjQ0NSwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJodWdoZXN0In0.S3LSAOfQrIRo33drvftBNEYxD9srtocHXyyb6hMo1Q4JvknbwbqMANxvVhm6pQ8OQyil2XRKPRsx1rkvFxpx6Q
thughes@krypton [0] $ aws --endpoint-url http://minio.localhost:9001 s3 ls

An error occurred (AccessDenied) when calling the ListBuckets operation: Access Denied.
```

**Comment by harshavardhana** [comment]
@timhughes you need to set policy using `mc admin user` first you cannot carry any policy in session policies those are only meant to reduce the already existing policy on the user.

**Comment by timhughes** [comment]
@harshavardhana, thankyou for taking the time on this. This is what I have tried, is it incorrect ? 
```
[root@localhost vagrant]# cat allaccess.json|jq . 
{
  "Statement": [
    {
      "Resource": [
        "arn:aws:s3:::*"
      ],
      "Action": [
        "s3:*"
      ],
      "Effect": "Allow"
    }
  ],
  "Version": "2012-10-17"
}
[root@localhost vagrant]# mc admin policy add local allaccess allaccess.json
Added policy `allaccess` successfully.
[root@localhost vagrant]# mc admin policy set local allaccess user=timhughes
Policy allaccess is set on user `timhughes`
[root@localhost vagrant]# mc admin user info local timhughes
AccessKey: timhughes
Status: 
PolicyName: allaccess
MemberOf: 
```

**Comment by harshavardhana** [comment]
> @harshavardhana, thankyou for taking the time on this. This is what I have tried, is it incorrect ? 
> ```
> [root@localhost vagrant]# cat allaccess.json|jq . 
> {
>   "Statement": [
>     {
>       "Resource": [
>         "arn:aws:s3:::*"
>       ],
>       "Action": [
>         "s3:*"
>       ],
>       "Effect": "Allow"
>     }
>   ],
>   "Version": "2012-10-17"
> }
> [root@localhost vagrant]# mc admin policy add local allaccess allaccess.json
> Added policy `allaccess` successfully.
> [root@localhost vagrant]# mc admin policy set local allaccess user=timhughes
> Policy allaccess is set on user `timhughes`
> [root@localhost vagrant]# mc admin user info local timhughes
> AccessKey: timhughes
> Status: 
> PolicyName: allaccess
> MemberOf: 
> ```

This should work, do you still get access denied?

**Comment by harshavardhana** [comment]
Please test with the latest release @timhughes

**Comment by timhughes** [comment]
Been working on another project for a few days.  Will have a look in the morning. Thanks

**Comment by timhughes** [comment]
I think the changes in the new revision have caused a regression. Now the access key generated is immediately invalid.

```
[root@localhost vagrant]# minio --version
minio version RELEASE.2020-04-28T23-56-56Z
[root@localhost vagrant]# mc admin user info local timhughes
AccessKey: timhughes
Status: 
PolicyName: allaccess
MemberOf: 
[root@localhost vagrant]# ./minio-test-ldap -sts-ep http://minio.localhost:9001 -u timhughes -p xxxxxxxxxxxxxxxxxx
credentials.Value{AccessKeyID:"1LWJVPBJJOGP9G2KWTUU", SecretAccessKey:"8uFtDTTou35INkep274n3wQdF+WMb+9ingKSI++W", SessionToken:"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIxTFdKVlBCSkpPR1A5RzJLV1RVVSIsImV4cCI6MTU4ODQ1OTY0NCwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJodWdoZXN0In0.xa2uEzQIDtnWdIvNYaC_nw0Csx9BIUwLdhfgNNdF73tVnYpkW2lw5fkCggcWZ_wMFaJyDGD-_QDjvJjrwJbbGA", SignerType:1}
Calling list buckets with temp creds:
2020/04/30 10:47:24 The access key ID you provided does not exist in our records.
```

**Comment by timhughes** [comment]
I have been running through this with a debugger and I think I know what is going on. 
At this point here https://github.com/minio/minio/blob/master/cmd/config/identity/ldap/config.go#L156-L160 the username is being inserted into the `MINIO_IDENTITY_LDAP_USERNAME_FORMAT` string and `bindDN` looks like `cn=fry,ou=people,dc=planetexpress,dc=com` when it should look like `cn=Philip J. Fry,ou=people,dc=planetexpress,dc=com`

For a lot of setups the `username` is not the `cn`,  it is the `sAMAccountName` or `uid`. The `cn` is the users full name like **Philip J. Fry** or something.  

If i remove the environment variable `MINIO_IDENTITY_LDAP_USERNAME_FORMAT` and leave the 
`MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER='(uid=%s)'` then it appears to authenticate initially but them I cannot access the buckets



I have been testing using this docker container to provide a similar ldap structure (all the credentials are on https://github.com/go-gitea/test-openldap)

```
docker run -p 1389:389 -p 1636:636 --name test-ldap --detach gitea/test-openldap
```
and the following environment variables

```
export MINIO_IDENTITY_LDAP_SERVER_ADDR=127.0.0.1:1389
export MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER='(uid=%s)'
export MINIO_IDENTITY_LDAP_USERNAME_FORMAT='cn=%s,ou=people,dc=planetexpress,dc=com'
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="dc=planetexpress,dc=com"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER='(&(objectclass=group)(member=%s))'
export MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE=cn
export MINIO_IDENTITY_LDAP_STS_EXPIRY=60h
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
```


This is a couple of ldap searches against the ldap server showing the different result 
```
timhughes@krypton [0] $ ldapsearch -x -H ldap://localhost:1389 -b "dc=planetexpress,dc=com" -D "cn=Philip J. Fry,ou=people,dc=planetexpress,dc=com" -w fry '(uid=*)' dn
# extended LDIF
#
# LDAPv3
# base <dc=planetexpress,dc=com> with scope subtree
# filter: (uid=*)
# requesting: dn 
#

# Amy Wong + Kroker, people, planetexpress.com
dn: cn=Amy Wong+sn=Kroker,ou=people,dc=planetexpress,dc=com

# Bender Bending Rodr\C3\ADguez, people, planetexpress.com
dn:: Y249QmVuZGVyIEJlbmRpbmcgUm9kcsOtZ3VleixvdT1wZW9wbGUsZGM9cGxhbmV0ZXhwcmVzc
 yxkYz1jb20=

# Philip J. Fry, people, planetexpress.com
dn: cn=Philip J. Fry,ou=people,dc=planetexpress,dc=com

# Hermes Conrad, people, planetexpress.com
dn: cn=Hermes Conrad,ou=people,dc=planetexpress,dc=com

# Turanga Leela, people, planetexpress.com
dn: cn=Turanga Leela,ou=people,dc=planetexpress,dc=com

# Hubert J. Farnsworth, people, planetexpress.com
dn: cn=Hubert J. Farnsworth,ou=people,dc=planetexpress,dc=com

# John A. Zoidberg, people, planetexpress.com
dn: cn=John A. Zoidberg,ou=people,dc=planetexpress,dc=com

# gitea, service, planetexpress.com
dn: uid=gitea,ou=service,dc=planetexpress,dc=com

# search result
search: 2
result: 0 Success

# numResponses: 9
# numEntries: 8
```
```
timhughes@krypton [0] $ ldapsearch -x -H ldap://localhost:1389 -b "dc=planetexpress,dc=com" -D "cn=fry,ou=people,dc=planetexpress,dc=com" -w fry '(uid=*)' dn
ldap_bind: Invalid credentials (49)
```

**Comment by easyterm-devel** [comment]
Hello!

Please try this:

```
ldapsearch -x -H ldap://localhost:389 -b "dc=planetexpress,dc=com" -D "cn=admin,dc=planetexpress,dc=com" "objectclass=account" -w GoodNewsEveryone
# extended LDIF
#
# LDAPv3
# base <dc=planetexpress,dc=com> with scope subtree
# filter: objectclass=account
# requesting: ALL
#

# gitea, service, planetexpress.com
dn: uid=gitea,ou=service,dc=planetexpress,dc=com
objectClass: top
objectClass: account
objectClass: simpleSecurityObject
description: Service account for integration with Gitea
uid: gitea
userPassword:: e1NTSEF9Um0zVzF3UE51QUdkTEhmTm9NeGhEb3VuMEdZMEV0RHc=

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

```
ldapwhoami -vvv -x -w password -D "uid=gitea,ou=service,dc=planetexpress,dc=com" -H ldap://localhost:389/
ldap_initialize( ldap://localhost:389/??base )
dn:uid=gitea,ou=service,dc=planetexpress,dc=com
Result: Success (0)
```

minio.export:
```
export MINIO_IDENTITY_LDAP_SERVER_ADDR=192.168.88.244:389
export MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER='(uid=%s)'
export MINIO_IDENTITY_LDAP_USERNAME_FORMAT='uid=%s,ou=service,dc=planetexpress,dc=com'
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN="dc=planetexpress,dc=com"
export MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER='(&(objectclass=account)(uid=%s))'
export MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE=uid
export MINIO_IDENTITY_LDAP_STS_EXPIRY=60h
export MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY=on
export MINIO_IDENTITY_LDAP_SERVER_INSECURE=on
```

```
source minio.export
~/go/bin/minio server /home/aia/minio__share_item &
~/go/bin/mc  config host add myminio http://192.168.88.244:9000 minioadmin minioadmin
~/go/bin/mc admin config set myminio/ identity_ldap  --env
~/go/bin/mc admin policy add myminio llaccess allaccess.json
~/go/bin/mc admin policy set myminio llaccess user=gitea
 ./ldap  -u gitea -p password
credentials.Value{AccessKeyID:"1GZ8BEW36W7WI8SI05MM", SecretAccessKey:"6s84e1EpxzdLybvbPzmu+TaLx9BqimCEdY3uwYKU", SessionToken:"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIxR1o4QkVXMzZXN1dJOFNJMDVNTSIsImV4cCI6MTU4OTMzNDc5OCwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJnaXRlYSJ9.FFl1rqlTzhv8oDRYaCPIePs4zRmmk9CvteQBvxJBqN8atg1r_kfjSDb0-XhOpajJg1dgGPDYSQz36AaGRdjT8w", SignerType:1}
Calling list buckets with temp creds:
2020/05/10 16:53:18 The access key ID you provided does not exist in our records.
```

It is success for me for ldapsearch and mc test utility (excluding probably significant error on last string).
I have not use aws-cli (only minio client mc utility), but env variables above probably resolve search problem on existing LDAP data.
Can you tell me how apply this temporary credentials into terminal on localhost (I am very new user of minio) - may be exist some script?

**Comment by easyterm-devel** [comment]
I figured out pattern in documentation and after regenerate temporary triad appear error:

```
export MC_HOST_myalias=http://IY86FSR6DAZCR0DGRCOL:7gzlNlF4cSV1RGjHg+1D8iw++k1mHHdGlOjvmzpg:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJJWTg2RlNSNkRBWkNSMERHUkNPTCIsImV4cCI6MTU4OTM0NzQ5NCwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJnaXRlYSJ9._QSYWjZP4h_5YNecZ0OMAHNzOWeLQ6s4KxFDhllGXx_V9ebER80acSsTBmcBnCrt4MGEQpgF8hm05k5-3BoIiQ@192.168.88.244:9000
[aia@localhost minio_experiment_token]$ ~/go/bin/mc --debug ls myalias
mc: <DEBUG> GET / HTTP/1.1
Host: 192.168.88.244:9000
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200510/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200510T181233Z
X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJJWTg2RlNSNkRBWkNSMERHUkNPTCIsImV4cCI6MTU4OTM0NzQ5NCwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJnaXRlYSJ9._QSYWjZP4h_5YNecZ0OMAHNzOWeLQ6s4KxFDhllGXx_V9ebER80acSsTBmcBnCrt4MGEQpgF8hm05k5-3BoIiQ
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 279
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 10 May 2020 18:12:33 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 160DBD4649ACC1E8
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The access key ID you provided does not exist in our records.</Message><Resource>/</Resource><RequestId>160DBD4649ACC1E8</RequestId><HostId>5f5bb28a-2a17-414b-8533-dd7caf75e5dd</HostId></Error>mc: <DEBUG> Response Time:  3.419938ms

mc: <DEBUG> GET / HTTP/1.1
Host: 192.168.88.244:9000
User-Agent: MinIO (linux; amd64) minio-go/v6.0.56 mc/DEVELOPMENT.GOGET
Authorization: AWS4-HMAC-SHA256 Credential=**REDACTED**/20200510/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-security-token, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20200510T181233Z
X-Amz-Security-Token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJJWTg2RlNSNkRBWkNSMERHUkNPTCIsImV4cCI6MTU4OTM0NzQ5NCwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJnaXRlYSJ9._QSYWjZP4h_5YNecZ0OMAHNzOWeLQ6s4KxFDhllGXx_V9ebER80acSsTBmcBnCrt4MGEQpgF8hm05k5-3BoIiQ
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 403 Forbidden
Content-Length: 279
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 10 May 2020 18:12:33 GMT
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 160DBD4649E622C6
X-Xss-Protection: 1; mode=block

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidAccessKeyId</Code><Message>The access key ID you provided does not exist in our records.</Message><Resource>/</Resource><RequestId>160DBD4649E622C6</RequestId><HostId>5f5bb28a-2a17-414b-8533-dd7caf75e5dd</HostId></Error>mc: <DEBUG> Response Time:  2.188111ms

mc: <ERROR> Unable to list folder. The access key ID you provided does not exist in our records.
 (1) ls.go:133 cmd.doList(..) Tags: [http://192.168.88.244:9000/]
 (0) client-s3.go:1982 cmd.(*S3Client).listInRoutine(..)
 Release-Tag:DEVELOPMENT.GOGET | Commit:DEVELOPMENT. | Host:localhost.localdomain | OS:linux | Arch:amd64 | Lang:go1.13.8 | Mem:1.9 MB/72 MB | Heap:1.9 MB/66 MB
```

**Comment by easyterm-devel** [comment]
Thanks!

No more problem with mc:
```
[aia@localhost src]$ GO111MODULE=on go get github.com/minio/minio@1756b7c6ffbe580cd1708216978f01698b0481c4
go: finding github.com 1756b7c6ffbe580cd1708216978f01698b0481c4
go: finding github.com/minio/minio 1756b7c6ffbe580cd1708216978f01698b0481c4
go: finding github.com/minio 1756b7c6ffbe580cd1708216978f01698b0481c4
[aia@localhost src]$ 
[aia@localhost ~]$ source minio.export
[aia@localhost ~]$ ~/go/bin/minio server /home/aia/minio__share_item &
[1] 5043
[aia@localhost ~]$ Endpoint:  http://192.168.88.244:9000  http://172.17.0.1:9000  http://127.0.0.1:9000        
AccessKey: minioadmin 
SecretKey: minioadmin 

Browser Access:
   http://192.168.88.244:9000  http://172.17.0.1:9000  http://127.0.0.1:9000        

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.88.244:9000 minioadmin minioadmin

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
Detected default credentials 'minioadmin:minioadmin', please change the credentials immediately using 'MINIO_ACCESS_KEY' and 'MINIO_SECRET_KEY'

[aia@localhost ~]$ ~/go/bin/mc  config host add myminio http://192.168.88.244:9000 minioadmin minioadmin
Added `myminio` successfully.
[aia@localhost ~]$ ~/go/bin/mc admin config set myminio/ identity_ldap  --env
KEY:
identity_ldap  enable LDAP SSO support

ARGS:
MINIO_IDENTITY_LDAP_SERVER_ADDR*             (address)   AD/LDAP server address e.g. "myldapserver.com:636"
MINIO_IDENTITY_LDAP_USERNAME_FORMAT*         (list)      ";" separated list of username bind DNs e.g. "uid=%s,cn=accounts,dc=myldapserver,dc=com"
MINIO_IDENTITY_LDAP_USERNAME_SEARCH_FILTER*  (string)    user search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_FILTER*     (string)    search filter for groups e.g. "(&(objectclass=groupOfNames)(memberUid=%s))"
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN*    (list)      ";" separated list of group search base DNs e.g. "dc=myldapserver,dc=com"
MINIO_IDENTITY_LDAP_USERNAME_SEARCH_BASE_DN  (list)      ";" separated list of username search DNs
MINIO_IDENTITY_LDAP_GROUP_NAME_ATTRIBUTE     (string)    search attribute for group name e.g. "cn"
MINIO_IDENTITY_LDAP_STS_EXPIRY               (duration)  temporary credentials validity duration in s,m,h,d. Default is "1h"
MINIO_IDENTITY_LDAP_TLS_SKIP_VERIFY          (on|off)    trust server TLS without verification, defaults to "off" (verify)
MINIO_IDENTITY_LDAP_SERVER_INSECURE          (on|off)    allow plain text connection to AD/LDAP server, defaults to "off"
MINIO_IDENTITY_LDAP_COMMENT                  (sentence)  optionally add a comment to this setting
[aia@localhost ~]$ 
[aia@localhost ~]$ ~/go/bin/mc admin policy add myminio llaccess allaccess.json
Added policy `llaccess` successfully.
[aia@localhost ~]$ ~/go/bin/mc admin policy set myminio llaccess user=gitea
Policy llaccess is set on user `gitea`
[aia@localhost ~]$  ./ldap  -u gitea -p password
credentials.Value{AccessKeyID:"313UKJNV8853E33C1AZW", SecretAccessKey:"oC+rKCa4tZWXa0g7IsSz1ni6BWTd+tF+SK+AUoYT", SessionToken:"eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIzMTNVS0pOVjg4NTNFMzNDMUFaVyIsImV4cCI6MTU4OTUzMjY2NSwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJnaXRlYSJ9.97oZBQlTWVsmLQ8jduBVM8cg10TWvhwJ2bb8J1V4xozKwifd5YDjk1Ujsun2tscUef7m9cjWxMb_dfv6dN6reQ", SignerType:1}
Calling list buckets with temp creds:
[{item1 2020-05-10 13:50:10.389 +0000 UTC} {yful 2020-05-10 17:29:11.518 +0000 UTC}]
[aia@localhost ~]$ export MC_HOST_myalias=http://313UKJNV8853E33C1AZW:oC+rKCa4tZWXa0g7IsSz1ni6BWTd+tF+SK+AUoYT:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiIzMTNVS0pOVjg4NTNFMzNDMUFaVyIsImV4cCI6MTU4OTUzMjY2NSwibGRhcEdyb3VwcyI6bnVsbCwibGRhcFVzZXIiOiJnaXRlYSJ9.97oZBQlTWVsmLQ8jduBVM8cg10TWvhwJ2bb8J1V4xozKwifd5YDjk1Ujsun2tscUef7m9cjWxMb_dfv6dN6reQ@192.168.88.244:9000
[aia@localhost ~]$ ~/go/bin/mc ls myalias
[..erase..]
[aia@localhost ~]$ echo $?
0

```
