### ISSUE TITLE
[faq] Kafka Connect S3 Connector for Minio - cannot access to Minio.

### ISSUE THREAD

**Issue by tirelibirefe** [minio/minio#9623]
Hello;
My system is entirely on-prem and all on Kubernetes. My purpose is to integrate Minio with Kafka through Kafka S3 Connector plugin. I use Strimzi to deploy and manage Kafka stuff.

my minio-vars are:

```
MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE
MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
MINIO_DOMAIN=minio.dev-kik.io

```

my KafkaConnect config is:

```
...
spec:
  version: 2.4.0
  image: harbor.dev-kik.io/kafka/kc-with-minio-mssql:v0.1
  replicas: 1
  bootstrapServers: kafka-beytepe-kafka-bootstrap:9093
  externalConfiguration:
    volumes:
      - name: minio-vars
        secret:
          secretName: minioenvs
  tls:
    trustedCertificates:
      - secretName: kafka-beytepe-cluster-ca-cert
        certificate: ca.crt
  config:
    group.id: sql-minio-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
...
```
I see all these variables are passed into the pod successfully.

this is my S3 / Minio connector config:

```
...
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  config:
    storage.class: io.confluent.connect.s3.storage.S3Storage  
    format.class: io.confluent.connect.s3.format.avro.AvroFormat
    schema.generator.class: io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator
    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
    tasks.max: '1'
    topics: filesql1.dbo.files
    s3.bucket.name: dosyalar
    flush.size: '3'
    format: binary
    schema.compatibility: NONE
    store.url: http://minio.dev-kik.io
...
```
but my KafkaConnect cannot login to Minio and tries to login AWS all the time.

```
      Trace:  org.apache.kafka.connect.errors.ConnectException: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@4bb8805d: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@177438ab: Failed to connect to service endpoint: ]
              at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:121)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:305)
              at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:193)
              at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
              at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
              at java.util.concurrent.FutureTask.run(FutureTask.java:266)
              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
              at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.SdkClientException: Unable to load AWS credentials from any provider in the chain: [EnvironmentVariableCredentialsProvider: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY)), SystemPropertiesCredentialsProvider: Unable to load AWS credentials from Java system properties (aws.accessKeyId and aws.secretKey), WebIdentityTokenCredentialsProvider: You must specify a value for roleArn and roleSessionName, com.amazonaws.auth.profile.ProfileCredentialsProvider@4bb8805d: profile file cannot be null, com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@177438ab: Failed to connect to service endpoint: ]
  at com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials(AWSCredentialsProviderChain.java:136)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.getCredentialsFromContext(AmazonHttpClient.java:1251)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.runBeforeRequestHandlers(AmazonHttpClient.java:827)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:777)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:764)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:738)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:698)
  at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:680)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544)
  at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
  at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
  at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1413)
  at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1349)
  at io.confluent.connect.s3.storage.S3Storage.bucketExists(S3Storage.java:196)
  at io.confluent.connect.s3.S3SinkTask.start(S3SinkTask.java:108)
  ... 9 more
```

it looks like I do something missing; the connector must login to my Minio instead of AWS. Could you please advise?

**Comment by nitisht** [comment]
Can you try creating a `credentials` file with MinIO credentials in `~/.aws` directory. Contents would be 

```
[default]
aws_access_key_id=AKIAIOSFODNN7EXAMPLE
aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
```

Of course change the values to MinIO credentials

**Comment by tirelibirefe** [comment]
@nitisht thanks for your attention.
I did what you mentioned and the ERROR messages are gone.

...but I've another problem:
this is my minio connector config:

```
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  config:
    storage.class: io.confluent.connect.s3.storage.S3Storage  
    format.class: io.confluent.connect.s3.format.avro.AvroFormat
    schema.generator.class: io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator
    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
    tasks.max: '1'
    topics: s3-topic
    s3.bucket.name: dosyalar
    s3.part.size: '5242880'
    flush.size: '3'
    format: binary
    schema.compatibility: NONE
    max.request.size: "536870912"
    store.url: http://minio.dev-kik.io

```
I followed your article and created a topic "s3-topic", put some data as you described.
https://blog.minio.io/journaling-kafka-messages-with-s3-connector-and-minio-83651a51045d 

My Minio/S3 connector looks like working properly:

```
Name:         minio-connector
Namespace:    kafka
Labels:       strimzi.io/cluster=mssql-minio-connect-cluster
Annotations:  API Version:  kafka.strimzi.io/v1alpha1
Kind:         KafkaConnector
Metadata:
  Creation Timestamp:  2020-05-18T03:32:55Z
  Generation:          2
  Managed Fields:
    API Version:  kafka.strimzi.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:connectorStatus:
          .:
          f:connector:
            .:
            f:state:
            f:worker_id:
          f:name:
          f:tasks:
          f:type:
    Manager:         okhttp
    Operation:       Update
    Time:            2020-05-18T06:00:00Z
  Resource Version:  5561115
  Self Link:         /apis/kafka.strimzi.io/v1alpha1/namespaces/kafka/kafkaconnectors/minio-connector
  UID:               e8572892-fca9-4014-895d-a3f775ebc4d9
Spec:
  Class:  io.confluent.connect.s3.S3SinkConnector
  Config:
    flush.size:              3
    Format:                  binary
    format.class:            io.confluent.connect.s3.format.avro.AvroFormat
    max.request.size:        536870912
    partitioner.class:       io.confluent.connect.storage.partitioner.DefaultPartitioner
    s3.bucket.name:          dosyalar
    s3.part.size:            5242880
    schema.compatibility:    NONE
    schema.generator.class:  io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator
    storage.class:           io.confluent.connect.s3.storage.S3Storage
    store.url:               http://minio.dev-kik.io
    tasks.max:               1
    Topics:                  s3-topic
Status:
  Conditions:
    Last Transition Time:  2020-05-18T06:00:00.897Z
    Status:                True
    Type:                  Ready
  Connector Status:
    Connector:
      State:      RUNNING
      worker_id:  10.244.1.194:8083
    Name:         minio-connector
    Tasks:
      Id:               0
      State:            RUNNING
      worker_id:        10.244.1.194:8083
    Type:               sink
  Observed Generation:  2
Events:                 <none>
```

...but there is nothing in my Minio buckets?

**Comment by tirelibirefe** [comment]
@nitisht I changed my connector config; the new connector is here:

```
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  config:
    storage.class: io.confluent.connect.s3.storage.S3Storage  
    schema.generator.class: io.confluent.connect.storage.hive.schema.DefaultSchemaGenerator
    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner
    tasks.max: '1'
    topics: filesql1.dbo.Files
    s3.bucket.name: dosyalar
    s3.part.size: '5242880'
    flush.size: '1000'
    format: binary
    schema.compatibility: NONE
    max.request.size: "536870912"
    store.url: http://minio.dev-kik.io
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    format.class: io.confluent.connect.s3.format.bytearray.ByteArrayFormat
```

old issues gone, my Minio doesn't crash any more but there is still nothing in my Minio bucket.
Also there is no any error messages.
Could you please advise what I must check to get more information about the issue?

Regards

**Comment by hpsony94** [comment]
I have done it by using Kafka connect of confluent stack, 
please follow it via this link: https://docs.confluent.io/current/connect/kafka-connect-s3/index.html#connect-s3

:) please do it manually first to understand it, anyway thanks for giving Strimzi, good to know it :) 


I'm going to plan for Kafka connector gitops

**Comment by hpsony94** [comment]
@tirelibirefe  you can directly push minio credential into configuration parameters. ...

Let's try it
```
curl -i -X PUT -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/__sink-minio-teko/config \
    -d '
 {
    "name":"__sink-minio",
    "connector.class":"io.confluent.connect.s3.S3SinkConnector",
    "tasks.max":"1",
    "topics":"noname",
    "s3.bucket.name":"noname-log",
    "s3.part.size":"5242880",
    "s3.compression.type":"gzip",
    "flush.size":"3",
    "aws.secret.access.key": "password",
    "aws.access.key.id": "username",
    "store.url":"http://IP:PORT",
    "value.converter": "org.apache.kafka.connect.converters.ByteArrayConverter",
    "format.class": "io.confluent.connect.s3.format.json.JsonFormat",
    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "schema.compatibility": "NONE"
}'
```
