### ISSUE TITLE
Multipart error: googleapi: Error 400: The number of source components provided (37) exceeds the maximum (32), invalid

### ISSUE THREAD

**Issue by jlebrijo** [minio/minio#9646]
Trying to upload 6GB file to a minio server as GCS gateway.
I am having the same error:
* 5 MB chunks: `googleapi: Error 400: The number of source components provided (37) exceeds the maximum (32), invalid`
* 100 MB chunks: `googleapi: Error 400: The number of source components provided (36) exceeds the maximum (32), invalid`

Total file is 6 GB so first case we have 1200 chunks, and second 60 chuncks. So there is no relation with this 36-37. Seems like with the last chunks minion tries to merge without taking care of Google Storage limitation of 32.

## Expected Behavior
File should be totally uploaded as it is les than 5 TB

## Current Behavior
1. Trying to upload 6 GB file
2. at the end of the upload (100%):
  * Client raises: `Aws::S3::Errors::InvalidBucketName - The specified bucket is not valid.:`
  * Minion logs raises:
```
API: CompleteMultipartUpload(bucket=weopt-local, object=tus/225198636c34d7975ead8bc56e1301e1)
Time: 16:07:45 UTC 05/19/2020
DeploymentID: dcf051dd-73c6-43fe-8958-a391b3b4f669
RequestID: 161079A89354178B
RemoteHost: 89.141.130.121
UserAgent: aws-sdk-ruby3/3.95.0 ruby/2.6.3 x86_64-linux aws-sdk-s3/1.64.0
Error: googleapi: Error 400: The number of source components provided (36) exceeds the maximum (32), invalid
       3: github.com/minio/minio@/cmd/gateway/gcs/gateway-gcs.go:1350:gcs.(*gcsGateway).CompleteMultipartUpload()
       2: github.com/minio/minio@/cmd/object-handlers.go:2504:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```
## Possible Solution

Not sure, seems like minio tries to merge more chunks than GCS expected in the final steps.

Related with this issue: https://github.com/minio/minio/issues/7201

## Steps to Reproduce (for bugs)
1. Running minio server: `minio gateway gcs project-name`
2. Running tus-ruby-server to upload files
3. Sending 6GB file

## Context
We are using it to upload files from 32MB to 50GB to GCS via HTTP

## Regression
No

## Your Environment
* Version used (`minio version`): minio version RELEASE.2020-05-08T02-40-49Z
* Operating System and version (`uname -a`):
```
Linux minio 5.3.0-1018-gcp #19~18.04.1-Ubuntu SMP Tue Apr 14 12:49:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
* Link to your project: www.weopt.com

**Comment by ebozduman** [comment]
Hi @jlebrijo ,
Could you give more details about the reproduction steps, like the commands you've used or simply copy your script to the issue?
Thanks..

**Comment by jlebrijo** [comment]
Hi @ebozduman 

thanks for your response!

As I reported, I am using tus-ruby-server gem.

Created the file with this command: `head -c 6GB /dev/urandom > ostechnix.txt`

My script is this:

```ruby
    require "tus/storage/s3"
    require "stringio"

    storage = Tus::Storage::S3.new(
        access_key_id:     ENV['MINIO_ACCESS_KEY'], # "AccessKey" value
        secret_access_key: ENV['MINIO_SECRET_KEY'], # "SecretKey" value
        endpoint:          ENV['MINIO_ENDPOINT'],   # "Endpoint"  value
        bucket:            ENV['GCLOUD_BUCKET'],     # name of the bucket you created
        region:            ENV['GCLOUD_REGION'],
        prefix:            ENV['TUS_BUCKET_FOLDER'],
        force_path_style:  true,
        )

    file_path = 'ostechnix.txt'
    puts "File size: #{File.size(file_path)}"
    file_name = file_path.to_s.split('/').last
    storage.create_file(file_name, info = {})
    chunk_size = 500 * 1024 * 1024
    puts "Chunk size: #{chunk_size}"
    i=0
    File.open(file_path) do|file|
      until file.eof?
        chunk = file.read(chunk_size)
        puts "Part #{i+=1} - #{chunk.size} bytes"
        storage.patch_file(file_name, StringIO.new(chunk), info)
      end
    end
    storage.finalize_file(file_name, info)
```

If you run this script the output is:

```
File size: 6000000000
Chunk size: 524288000
Part 1 - 524288000 bytes
Part 2 - 524288000 bytes
Part 3 - 524288000 bytes
Part 4 - 524288000 bytes
Part 5 - 524288000 bytes
Part 6 - 524288000 bytes
Part 7 - 524288000 bytes
Part 8 - 524288000 bytes
Part 9 - 524288000 bytes
Part 10 - 524288000 bytes
Part 11 - 524288000 bytes
Part 12 - 232832000 bytes
  example at ./spec/models/concerns/source/url_upload_spec.rb:2 (FAILED - 1)

Failures:

  1) Source::UrlUpload
     Failure/Error: storage.finalize_file(file_name, info)

     Aws::S3::Errors::InvalidBucketName:
       The specified bucket is not valid.
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-core-3.95.0/lib/seahorse/client/plugins/raise_response_errors.rb:15:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-s3-1.64.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:22:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-s3-1.64.0/lib/aws-sdk-s3/plugins/dualstack.rb:26:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-s3-1.64.0/lib/aws-sdk-s3/plugins/accelerate.rb:35:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-core-3.95.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:20:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-core-3.95.0/lib/aws-sdk-core/plugins/idempotency_token.rb:17:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-core-3.95.0/lib/aws-sdk-core/plugins/param_converter.rb:24:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-core-3.95.0/lib/aws-sdk-core/plugins/response_paging.rb:10:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-core-3.95.0/lib/seahorse/client/plugins/response_target.rb:23:in `call'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-core-3.95.0/lib/seahorse/client/request.rb:70:in `send_request'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-s3-1.64.0/lib/aws-sdk-s3/client.rb:678:in `complete_multipart_upload'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-s3-1.64.0/lib/aws-sdk-s3/multipart_upload.rb:277:in `complete'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/aws-sdk-s3-1.64.0/lib/aws-sdk-s3/customizations/multipart_upload.rb:29:in `complete'
     # /home/jlebrijo/.rvm/gems/ruby-2.6.3@suppress/gems/tus-server-2.3.0/lib/tus/storage/s3.rb:156:in `finalize_file'
     # ./spec/models/concerns/source/url_upload_spec.rb:27:in `block (2 levels) in <top (required)>'
```

Minio server is running with this command: `minio gateway gcs project-name`

Minio server error in log is:

```
API: CompleteMultipartUpload(bucket=weopt-local, object=tus/ostechnix.txt)
Time: 15:20:16 UTC 05/21/2020
DeploymentID: 4c667aea-257d-435d-8e3e-acaa10a0430f
RequestID: 16111439F56DEB86
RemoteHost: 89.141.130.121
Host: minio.weopt.com:9000
UserAgent: aws-sdk-ruby3/3.95.0 ruby/2.6.3 x86_64-linux aws-sdk-s3/1.64.0
Error: googleapi: Error 400: The number of source components provided (36) exceeds the maximum (32), invalid
       3: github.com/minio/minio@/cmd/gateway/gcs/gateway-gcs.go:1350:gcs.(*gcsGateway).CompleteMultipartUpload()
       2: github.com/minio/minio@/cmd/object-handlers.go:2504:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

API: CompleteMultipartUpload(bucket=weopt-local, object=tus/ostechnix.txt)
Time: 15:20:51 UTC 05/21/2020
DeploymentID: 4c667aea-257d-435d-8e3e-acaa10a0430f
RequestID: 16111441F16B6AD5
RemoteHost: 89.141.130.121
Host: minio.weopt.com:9000
UserAgent: aws-sdk-ruby3/3.95.0 ruby/2.6.3 x86_64-linux aws-sdk-s3/1.64.0
Error: googleapi: Error 400: The number of source components provided (36) exceeds the maximum (32), invalid
       3: github.com/minio/minio@/cmd/gateway/gcs/gateway-gcs.go:1350:gcs.(*gcsGateway).CompleteMultipartUpload()
       2: github.com/minio/minio@/cmd/object-handlers.go:2504:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

API: CompleteMultipartUpload(bucket=weopt-local, object=tus/ostechnix.txt)
Time: 15:21:23 UTC 05/21/2020
DeploymentID: 4c667aea-257d-435d-8e3e-acaa10a0430f
RequestID: 1611144A17B35395
RemoteHost: 89.141.130.121
Host: minio.weopt.com:9000
UserAgent: aws-sdk-ruby3/3.95.0 ruby/2.6.3 x86_64-linux aws-sdk-s3/1.64.0
Error: googleapi: Error 400: The number of source components provided (36) exceeds the maximum (32), invalid
       3: github.com/minio/minio@/cmd/gateway/gcs/gateway-gcs.go:1350:gcs.(*gcsGateway).CompleteMultipartUpload()
       2: github.com/minio/minio@/cmd/object-handlers.go:2504:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()

API: CompleteMultipartUpload(bucket=weopt-local, object=tus/ostechnix.txt)
Time: 15:21:56 UTC 05/21/2020
DeploymentID: 4c667aea-257d-435d-8e3e-acaa10a0430f
RequestID: 16111451D9832B7B
RemoteHost: 89.141.130.121
Host: minio.weopt.com:9000
UserAgent: aws-sdk-ruby3/3.95.0 ruby/2.6.3 x86_64-linux aws-sdk-s3/1.64.0
Error: googleapi: Error 400: The number of source components provided (36) exceeds the maximum (32), invalid
       3: github.com/minio/minio@/cmd/gateway/gcs/gateway-gcs.go:1350:gcs.(*gcsGateway).CompleteMultipartUpload()
       2: github.com/minio/minio@/cmd/object-handlers.go:2504:cmd.objectAPIHandlers.CompleteMultipartUploadHandler()
       1: net/http/server.go:2007:http.HandlerFunc.ServeHTTP()
```

**Comment by ebozduman** [comment]
@jlebrijo ,
This is perfect.
Thank you very much.

**Comment by jlebrijo** [comment]
Just finished also a test with different file sizes:
* Worked: 1500MB 2000MB 2500MB 3000MB 3500MB 4000MB 4500MB 5000MB
* Broken: 5500MB 6000MB

Seems like a limit at 5GB

**Comment by ebozduman** [comment]
Hi @jlebrijo ,

I've tried your ruby script after installing `'tus-server'` and `'aws-sdk-s3'` gems in my environment with May 5th (minio.RELEASE.2020-05-08T02-40-49Z) and the latest May16th (minio.RELEASE.2020-05-16T01-33-21Z) builds. 

I used chunk size 5MiB for a 180MiB file, created with `truncate` command, which turned out as 36 chunk `Put` transactions, and everything worked fine with no error messages on the console or on the client side.
Here are the debug messages from your script:
```
$ ruby ~/Scripts/rubyScripts/reproIssue#9646.rb 
File size: 188743680
Chunk size: 5242880
Part 1 - 5242880 bytes
Part 2 - 5242880 bytes
Part 3 - 5242880 bytes
Part 4 - 5242880 bytes
Part 5 - 5242880 bytes
Part 6 - 5242880 bytes
Part 7 - 5242880 bytes
Part 8 - 5242880 bytes
Part 9 - 5242880 bytes
Part 10 - 5242880 bytes
Part 11 - 5242880 bytes
Part 12 - 5242880 bytes
Part 13 - 5242880 bytes
Part 14 - 5242880 bytes
Part 15 - 5242880 bytes
Part 16 - 5242880 bytes
Part 17 - 5242880 bytes
Part 18 - 5242880 bytes
Part 19 - 5242880 bytes
Part 20 - 5242880 bytes
Part 21 - 5242880 bytes
Part 22 - 5242880 bytes
Part 23 - 5242880 bytes
Part 24 - 5242880 bytes
Part 25 - 5242880 bytes
Part 26 - 5242880 bytes
Part 27 - 5242880 bytes
Part 28 - 5242880 bytes
Part 29 - 5242880 bytes
Part 30 - 5242880 bytes
Part 31 - 5242880 bytes
Part 32 - 5242880 bytes
Part 33 - 5242880 bytes
Part 34 - 5242880 bytes
Part 35 - 5242880 bytes
Part 36 - 5242880 bytes
```
Checked the copied file at the destination:
```
$ mc ls mygcs/dir1/dir2/
[2020-05-21 21:57:40 PDT]  180MiB onehundredeightyMeg.data
```
I also watched the progress of the data with `mc admin trace <alias>` command, which you can always use to have a peek at what is happening behind the scenes.
Here is its output:
```
$ mc admin trace mygcs/
04:54:09.506 [200 OK] s3.NewMultipartUpload localhost:9000/dir1/dir2/onehundredeightyMeg.data?uploads  127.0.0.1         474.322ms    ↑ 113 B ↓ 513 B
04:54:16.533 [200 OK] s3.PutObjectPart localhost:9000/dir1/dir2/onehundredeightyMeg.data?partNumber=1&uploadId=79ad7049-d07a-4f13-907f-3d840860c625  127.0.0.1         6.952045s    ↑ 5.0 MiB ↓ 248 B
04:54:22.274 [200 OK] s3.PutObjectPart localhost:9000/dir1/dir2/onehundredeightyMeg.data?partNumber=2&uploadId=79ad7049-d07a-4f13-907f-3d840860c625  127.0.0.1         5.669971s    ↑ 5.0 MiB ↓ 248 B
:
:
04:57:32.013 [200 OK] s3.PutObjectPart localhost:9000/dir1/dir2/onehundredeightyMeg.data?partNumber=35&uploadId=79ad7049-d07a-4f13-907f-3d840860c625  127.0.0.1         5.949828s    ↑ 5.0 MiB ↓ 248 B
04:57:36.406 [200 OK] s3.PutObjectPart localhost:9000/dir1/dir2/onehundredeightyMeg.data?partNumber=36&uploadId=79ad7049-d07a-4f13-907f-3d840860c625  127.0.0.1         4.32656s     ↑ 5.0 MiB ↓ 248 B
04:57:47.392 [200 OK] s3.CompleteMultipartUpload localhost:9000/dir1/dir2/onehundredeightyMeg.data?uploadId=79ad7049-d07a-4f13-907f-3d840860c625  127.0.0.1         10.969084s   ↑ 3.8 KiB ↓ 503 B
```

I've also repeated the same test with a minio-go sdk script. Please check it out! Since you already use MinIO gateway, you may like MinIO sdks.
Here is the go script that does the same job:
```
package main

import (
	"log"

	"github.com/minio/minio-go/v6"
)

func main() {
	s3Client, err := minio.New("localhost:9000", "<minio-gw-access-key>", "<minio-gw-secret-key>", false)
	if err != nil {
		log.Fatalln(err)
	}
	if _, err := s3Client.FPutObject("dir1", "dir2", "/tmp/twohundredoneMeg.data", minio.PutObjectOptions{
		ContentType: "application/csv",
		PartSize:    5 * 1024 * 1024,
	}); err != nil {
		log.Fatalln(err)
	}
	log.Println("Successfully uploaded object")
}
```
This script also works the same way and finishes without any problems or error messages. Please notice, this time the file size is 201MiB to have the last chunk less than 5MiB in size.

I think you might have something wrong in your environment, but of course it is not obvious.
The way you start your `minio gateway gcs` might be a little bit different. I use `gcs.json` file and here is the full command:
`$ GOOGLE_APPLICATION_CREDENTIALS=<path-to-gcs.json-file>/gcs.json MINIO_ACCESS_KEY=<minio-gw-access-key> MINIO_SECRET_KEY=<minio-gw-secret-key> minio gateway gcs`

I am not sure if it would make any change, but you may want to check the versions of the 2 gems.
Mine are:
```
aws-sdk-s3 (1.66.0)
tus-server (2.3.0)
```

Actually, it is better, if you could try the go script I've included to see if there is any change in the behavior. Here is the [MinIO Go Client API Reference](https://docs.minio.io/docs/golang-client-api-reference.html) and [MinIO Go Client Quick Start Guide](https://docs.minio.io/docs/golang-client-quickstart-guide.html) for your reference in case you need it. 

Please let us know if you still see the issue even with the provided go script.
Otherwise, please feel free to close the issue.

**Comment by jlebrijo** [comment]
I have the same gem versions, and credentials are passed the same way through environment variables.

Problem is not the number of chunks, or its size, you got the same error with 12 (as you can see in my example) or whatever. Problem are **always with files bigger than 5.5GB**.

Can you try with 5.5GB file, please? it should reproduce the error

**Comment by harshavardhana** [comment]
> I have the same gem versions, and credentials are passed the same way through environment variables.
> 
> Problem is not the number of chunks, or its size, you got the same error with 12 (as you can see in my example) or whatever. Problem are **always with files bigger than 5.5GB**.
> 
> Can you try with 5.5GB file, please? it should reproduce the error

This is actually a known limitation of GCS gateway , is worth just uploading without multipart which can upload easily upload upto 5TiB

We avoided this because without staging data ourselves (that would make gateway stateful) or we cannot circumvent the limits of GCS or we have to write a custom backend format to stage the data in chunks on GCS and then coalesce them later.

Currently what you see is the backend limits are exposed and we cannot do much here as kept things simple.

I don't think it's feasible for us to fix this issue at this point in time. GCS already supports S3 API use that directly instead.

**Comment by jlebrijo** [comment]
Ok, thanks for your quick response.

We have to work now with a 5GB limitation.
