### ISSUE TITLE
[not our bug] Cannot create Elasticsearch repository on minio - Failed to create repository

### ISSUE THREAD

**Issue by Marco-symplectic** [minio/minio#9922]
I am trying to create an Elasticsearch repository using the Elasticsearch S3 plugin to use minio as the  repository store

When trying to create an Elasticsearch repository I get a connection Unable to execute HTTP request.

My environment
- This is a 3 node Elasticsearch cluster.
- Minio is running on one of the nodes, and it is accessible to all nodes.
- Elasticsearch and minio are both configure with TLS.
- Latest stable release of minio
> root@mp-clstr03-node01:/home/marco# docker ps
> CONTAINER ID IMAGE COMMAND CREATED STATUS PORTSNAMESbe6c62c84348 minio/minio "/usr/bin/docker-ent…" 6 hours ago Up 6 hours 0.0.0.0:9433->9000/tcp objective_brahmagupta
> 
> root@mp-clstr03-node01:/home/marco# docker image list
> REPOSITORY TAG IMAGE ID CREATED SIZEminio/minio latest c9a590e11ff8 4 days ago 57MBminio/mc latest ccef166b50ec 5 days ago 24.7MBminio/minio f88482fd77da 7 days ago 57MB
> 
> root@mp-clstr03-node01:/home/marco# ./mc admin info myminio
> ●  mp-clstr03-node01:9443
> Uptime: 32 minutes
> Version: 2020-06-18T02:23:35Z
> Network: 1/1 OK
- Elasticsearch 5.6.7
- repository-s3 5.6.7
- openjdk version "1.8.0_252"
- OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1~18.04-b09)
- OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)

minio is running using:
- 0.0.0.0:9433:9000
- /var/elasticsearch_repositories/:/data
- /home/mp/certs/minio/:/root/.minio/certs

From all the nodes in the cluster the bellow is as expected
> curl https://mp-clstr03-node01:9443
> <?xml version="1.0" encoding="UTF-8"?>
> <Error><Code>AccessDenied</Code><Message>Access Denied.</Message><Resource>/</Resource><RequestId>161BE9BBB2F32A88</RequestId><HostId>1859a75f-1ced-486b-9126-bf4724381a22</HostId></Error>r
> 
> wget https://mp-clstr03-node01:9443
> Resolving mp-clstr03-node01 (mp-clstr03-node01)... 13.250.250.79
> Connecting to mp-clstr03-node01 (mp-clstr03-node01)|13.250.250.79|:9443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2020-06-25 22:26:44 ERROR 403: Forbidden.

To register the repository I run the following
> curl -k username:password -XPOST 'https://mp-clstr03-node01:9200/_snapshot/es-backup?pretty' -H 'Content-Type: application/json' -d '{"type": "s3", "settings": { "bucket": "elasticsearch", "endpoint": "https://mp-clstr03-node01:9433", "access_key": "access_key", "secret_key": "secretkey", "protocol": "https"}}'

The output result I get is the following
```
{
  "error" : {
    "root_cause" : [
      {
        "type" : "sdk_client_exception",
        "reason" : "sdk_client_exception: Unable to execute HTTP request: elasticsearch.mp-clstr03-node01"
      }
    ],
    "type" : "repository_exception",
    "reason" : "[disco_repository] failed to create repository",
    "caused_by" : {
      "type" : "sdk_client_exception",
      "reason" : "sdk_client_exception: Unable to execute HTTP request: elasticsearch.mp-clstr03-node01",
      "caused_by" : {
        "type" : "i_o_exception",
        "reason" : "elasticsearch.mp-clstr03-node01"
      }
    }
  },
  "status" : 500
}
```

The Elasticsearch log file shows this as a result of putting that request
 ```
[2020-06-25T22:14:20,896][WARN ][r.suppressed             ] path: /_snapshot/disco_repository, params: {pretty=, verify=false, repository=disco_repository}
org.elasticsearch.transport.RemoteTransportException: [mp-clstr03-node02][10.20.0.82:9300][cluster:admin/repository/put]
Caused by: org.elasticsearch.repositories.RepositoryException: [disco_repository] failed to create repository
        at org.elasticsearch.repositories.RepositoriesService.createRepository(RepositoriesService.java:388) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:356) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:56) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:109) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:634) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:612) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:571) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: sdk_client_exception: Unable to execute HTTP request: elasticsearch.mp-clstr03-node01
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleRetryableException(AmazonHttpClient.java:1114) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1064) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1326) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1266) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobStore.lambda$new$0(S3BlobStore.java:78) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
        at org.elasticsearch.repositories.s3.S3BlobStore.<init>(S3BlobStore.java:77) ~[?:?]
        at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:327) ~[?:?]
        at org.elasticsearch.repositories.s3.S3RepositoryPlugin.lambda$getRepositories$0(S3RepositoryPlugin.java:82) ~[?:?]
        at org.elasticsearch.repositories.RepositoriesService.createRepository(RepositoriesService.java:383) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:356) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:56) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:109) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:634) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:612) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:571) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
Caused by: java.io.IOException: elasticsearch.mp-clstr03-node01
        at java.net.InetAddress.getAllByName0(InetAddress.java:1281) ~[?:1.8.0_252]
        at java.net.InetAddress.getAllByName(InetAddress.java:1193) ~[?:1.8.0_252]
        at java.net.InetAddress.getAllByName(InetAddress.java:1127) ~[?:1.8.0_252]
        at com.amazonaws.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:27) ~[?:?]
        at com.amazonaws.http.DelegatingDnsResolver.resolve(DelegatingDnsResolver.java:38) ~[?:?]
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111) ~[?:?]
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_252]
        at com.amazonaws.http.conn.ClientConnectionManagerFactory$Handler.invoke(ClientConnectionManagerFactory.java:76) ~[?:?]
        at com.amazonaws.http.conn.$Proxy26.connect(Unknown Source) ~[?:?]
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380) ~[?:?]
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[?:?]
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184) ~[?:?]
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184) ~[?:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82) ~[?:?]
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55) ~[?:?]
        at com.amazonaws.http.apache.client.impl.SdkHttpClient.execute(SdkHttpClient.java:72) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1236) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.headBucket(AmazonS3Client.java:1326) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.doesBucketExist(AmazonS3Client.java:1266) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobStore.lambda$new$0(S3BlobStore.java:78) ~[?:?]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_252]
        at org.elasticsearch.repositories.s3.S3BlobStore.<init>(S3BlobStore.java:77) ~[?:?]
        at org.elasticsearch.repositories.s3.S3Repository.<init>(S3Repository.java:327) ~[?:?]
        at org.elasticsearch.repositories.s3.S3RepositoryPlugin.lambda$getRepositories$0(S3RepositoryPlugin.java:82) ~[?:?]
        at org.elasticsearch.repositories.RepositoriesService.createRepository(RepositoriesService.java:383) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService.registerRepository(RepositoriesService.java:356) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService.access$100(RepositoriesService.java:56) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.RepositoriesService$1.execute(RepositoriesService.java:109) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.ClusterStateUpdateTask.execute(ClusterStateUpdateTask.java:45) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.executeTasks(ClusterService.java:634) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.calculateTaskOutputs(ClusterService.java:612) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService.runTasks(ClusterService.java:571) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.ClusterService$ClusterServiceTaskBatcher.run(ClusterService.java:263) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:569) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:247) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:210) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_252]
```

From the error log what is puzzling me from the log files is on the **org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper** "error" why is it an HTTP request and why is there **elasticsearch** on the endpoint **mp-clstr03-node01**

The other thing that is might be weird is on the **RemoteTransportException** the Local IP I don't know if that could be an issue.
this same setup works with minio without TLS on the same cluster.

I have noticed, that this might be a limitation of curl + Elasticsearch repository API

if I use the following python script with the elasticsearch module.
```
#!/usr/bin/env python

import os

from elasticsearch import Elasticsearch

es = Elasticsearch('https://mp-clstr03-node01:9200', timeout=120, http_auth=('user','password'), use_ssl=True, verify_certs=False, ssl_show_warn=False)


index_name = "demo01-version"

os.umask(000)

create_repository_body = {
"type": "s3",
"settings": {
    "bucket": str(index_name),
    "endpoint": "https://mp-clstr03-node01:9433",
    "access_key": "AKEY",
    "secret_key": "SKEY",
    "protocol": "https"
    }
}
os.mkdir("/var/opt/backups/elasticsearch/"+index_name,0o777)
es.snapshot.create_repository(repository=index_name, body=create_repository_body, verify=False)

es.snapshot.create(repository=index_name, snapshot=index_name, body="{\"indices\":\"*-*\"}", wait_for_completion=True)
```
I get this output
```
Traceback (most recent call last):
  File "/opt/es-backup/test.py", line 32, in <module>
    es.snapshot.create(repository=index_name, snapshot=index_name, body="{\"indices\":\"*-*\"}", wait_for_completion=True)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 92, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/snapshot.py", line 28, in create
    body=body,
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 362, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 248, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 244, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(500, u'amazon_s3_exception', u'amazon_s3_exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: PUADE1U7KO6F; S3 Extended Request ID: J/tyN5+BIWks6asdf7asd0f9f7asdfak1h2r0WI+Ddq9lLalMIrM=)')
```

And as a result, a repository is registered in Elasticsearch and folder created in **/var/elasticsearch_repositories/**

I fill like Elasticsearch is not able to interpret the location of the minio endpoint correctly with the https and as a result is trying to make a repository on an S3 bucket.

Any advice would be appreciated.

**Comment by harshavardhana** [comment]
@Marco-symplectic this looks like you haven't set path_style_access you need to do that with https://www.elastic.co/guide/en/elasticsearch/plugins/current/repository-s3-client.html

**Comment by harshavardhana** [comment]
So clearly looks like a setup issue here.

**Comment by Marco-symplectic** [comment]
Hi,
Thanks, that helped, I can now create the repo with the curl command.

> curl -k username:password -XPOST 'https://mp-clstr03-node01:9200/_snapshot/es-backup?pretty' -H 'Content-Type: application/json' -d '{"type": "s3", "settings": { "bucket": "elasticsearch", "endpoint": "https://mp-clstr03-node01:9433", "access_key": "access_key", "secret_key": "secretkey", "protocol": "https"}}'

However, still fails with python with a similar issue

The python output is showing this error
```
elasticsearch.exceptions.TransportError: TransportError(500, u'amazon_s3_exception', u'amazon_s3_exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: ID; S3 Extended Request ID: ID)')
```

the log files is showing this
```
[2020-06-28T00:29:31,091][WARN ][r.suppressed             ] path: /_snapshot/repository/snapshot, params: {repository=repository, wait_for_completion=true, snapshot=snapshot}
org.elasticsearch.transport.RemoteTransportException: [mp-clstr03-node01][10.105.1.81:9300][cluster:admin/snapshot/create]
Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: amazon_s3_exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: EBB2BAA86AB71F48; S3 Extended Request ID: Dahd7zoXs9yMjzhATOK2SQdZ73yd+Z252hOyLS4/b7gOwGa+GtT1RSpDDKiE85XPaKpslbOtnAA=)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649) ~[?:?]
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4247) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4194) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4188) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:823) ~[?:?]
        at com.amazonaws.services.s3.AmazonS3Client.listObjects(AmazonS3Client.java:798) ~[?:?]
        at org.elasticsearch.repositories.s3.S3BlobContainer.listBlobsByPrefix(S3BlobContainer.java:142) ~[?:?]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.listBlobsToGetLatestIndexId(BlobStoreRepository.java:934) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.latestIndexBlobId(BlobStoreRepository.java:912) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.repositories.blobstore.BlobStoreRepository.getRepositoryData(BlobStoreRepository.java:750) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.snapshots.SnapshotsService.createSnapshot(SnapshotsService.java:236) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:82) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.action.admin.cluster.snapshots.create.TransportCreateSnapshotAction.masterOperation(TransportCreateSnapshotAction.java:41) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction.masterOperation(TransportMasterNodeAction.java:87) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.doRun(TransportMasterNodeAction.java:166) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:638) ~[elasticsearch-5.6.7.jar:5.6.7]
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) ~[elasticsearch-5.6.7.jar:5.6.7]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_252]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_252]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
```

As if again Elasticsearch is not detecting that is not an S3 bucket

It looks like the repository has been registered with **path_style_access**
```
{
  "snapshot" : {
    "type" : "s3",
    "settings" : {
      "bucket" : "bucket",
      "path_style_access" : "true",
      "endpoints" : "https://mp-clstr03-node01:9443",
      "protocol" : "https"
    }
  }
}
```

Snapshot, repository names name may not match I had anonymised the data.

This is how the relevant part of the python scrypt looks like right now
```
    create_repository_body = {
    "type": "s3",
    "settings": {
        "bucket": str(bucket),
        "path_style_access": "true",
        "endpoints": "https://mp-clstr03-node01:9443",
        "access_key": "AKEY",
        "secret_key": "SKEY",
        "protocol": "https"
        }
    }
    es.snapshot.create_repository(repository=repo, body=create_repository_body, verify=False)
    es.snapshot.create(repository=repo, snapshot=snapshot, body="{\"indices\":\"" + ','.join(instance_indexes) + "\"}", wait_for_completion=True)
```

Thanks

**Comment by harshavardhana** [comment]
> Caused by: org.elasticsearch.common.io.stream.NotSerializableExceptionWrapper: amazon_s3_exception: The AWS Access Key Id you provided does not exist in our records. (Service: Amazon S3; Status Code: 403; Error Code: InvalidAccessKeyId; Request ID: EBB2BAA86AB71F48; S3 Extended Request ID: Dahd7zoXs9yMjzhATOK2SQdZ73yd+Z252hOyLS4/b7gOwGa+GtT1RSpDDKiE85XPaKpslbOtnAA=)

This is not talking to MinIO from the RequestID it looks like it's still talking to AWS S3 - you need to figure out how to override the endpoint, even if they allow it or not. 

But this is not our issue @Marco-symplectic it is just configuration on your end.

**Comment by Marco-symplectic** [comment]
I had a typo.

Its **endpoint** rather and **endpoints**

I think we can close this now, thanks.
