### ISSUE TITLE
minio crashes on file access denied

### ISSUE THREAD

**Issue by brandsr** [minio/minio#9942]
## Expected Behavior
Should not crash on no file access.

## Current Behavior
Minio crashes on no file access. It logs an error:

```
Jun 30 08:22:24 csu1402 minio: API: SYSTEM()
Jun 30 08:22:24 csu1402 minio: Time: 08:22:24 CEST 06/30/2020
Jun 30 08:22:24 csu1402 minio: DeploymentID: 097dbbfe-990d-4a53-972e-a2d27158d709
Jun 30 08:22:24 csu1402 minio: Error: file access denied
Jun 30 08:22:24 csu1402 minio: 2: github.com/minio/minio@/cmd/fs-v1.go:284:cmd.(*FSObjects).CrawlAndGetDataUsage()
Jun 30 08:22:24 csu1402 minio: 1: github.com/minio/minio@/cmd/data-crawler.go:84:cmd.runDataCrawler()
Jun 30 08:22:24 csu1402 minio: panic: runtime error: invalid memory address or nil pointer dereference
Jun 30 08:22:24 csu1402 minio: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x146f5d0]
Jun 30 08:22:24 csu1402 minio: goroutine 29 [running]:
Jun 30 08:22:24 csu1402 minio: github.com/minio/minio/cmd.(*FSObjects).CrawlAndGetDataUsage(0xc000534180, 0x1faede0, 0xc00042aac0, 0x0, 0xc0006764e0, 0x0, 0x0)
Jun 30 08:22:24 csu1402 minio: github.com/minio/minio@/cmd/fs-v1.go:295 +0x770
Jun 30 08:22:24 csu1402 minio: github.com/minio/minio/cmd.runDataCrawler(0x1faede0, 0xc00042aac0, 0x1ff2ec0, 0xc000534180)
Jun 30 08:22:24 csu1402 minio: github.com/minio/minio@/cmd/data-crawler.go:84 +0x3bb
Jun 30 08:22:24 csu1402 minio: created by github.com/minio/minio/cmd.initDataCrawler
Jun 30 08:22:24 csu1402 minio: github.com/minio/minio@/cmd/data-crawler.go:52 +0xad
Jun 30 08:22:24 csu1402 systemd: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Jun 30 08:22:24 csu1402 systemd: Unit minio.service entered failed state.
Jun 30 08:22:24 csu1402 systemd: minio.service failed.
Jun 30 08:22:24 csu1402 systemd: minio.service holdoff time over, scheduling restart.
```
## Steps to Reproduce (for bugs)
Not exactly known. Errormessage return about every 2 hours in the message log.

## Context
Connections are killed, so io is aborted, which impacts applications using S3 storage.

## Your Environment
* Version used (`minio version`): minio version RELEASE.2020-06-22T03-12-50Z
* Environment name and version (e.g. nginx 1.9.1): Apache/2.4.6 (Red Hat Enterprise Linux)
* Server type and version: Red Hat Enterprise Linux Server release 7.2 (Maipo)
* Operating System and version (`uname -a`): 3.10.0-327.10.1.el7.x86_64 #1 SMP
* Link to your project: N/A

**Comment by harshavardhana** [comment]
@klauspost this was an issue with Gorilla mux already fixed in both branches master and release.
