### ISSUE TITLE
io.minio.errors.XmlParserException: null

### ISSUE THREAD

**Issue by kongmaster2016** [minio/minio#9997]
code:
minioClient.putObject(PutObjectArgs.builder().bucket(bucketName).object(ObjectName).stream(in,  -1, 10485760)

exception:
io.minio.errors.XmlParserException: null
	at io.minio.Xml.unmarshal(Xml.java:68)
	at io.minio.MinioClient.execute(MinioClient.java:1050)
	at io.minio.MinioClient.putObject(MinioClient.java:7582)
	at io.minio.MinioClient.putObject(MinioClient.java:4682)
	at io.minio.MinioClient.putObject(MinioClient.java:4881)

**Comment by kongmaster2016** [comment]
<dependency>
		   <groupId>io.minio</groupId>
		   <artifactId>minio</artifactId>
		   <version>7.1.0</version>
    	</dependency>
